guardian/support-frontend

cloud-formation/cfn.yaml

So that we can send logs off the box

Add permission to write to cloudwatch logs

---

assets/components/radioToggle/radioToggle.jsx
assets/components/radioToggle/radioToggle.scss
assets/pages/bundles-landing/actions/bundlesLandingActions.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundle.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/reducers/paperBundle.js
assets/stylesheets/main.scss
package.json

Continuing to flesh out the bundles landing page and experiment with modular components. This adds the second bundle, print/print+digital, and makes use of redux for user interaction.
**Note**: Putting all the copy in an object (in `Bundles.jsx`) may not be the best approach, let me know if you think there's a better way.
[**Trello Card**](https://trello.com/c/1KImhpNA/471-flesh-out-modular-design-architecture)
- Added redux.
- Added a radio toggle shared component.
- Added reducers and actions to bundles landing page.
- Added paper bundle.

Bundles Landing Page - Added Paper Bundle With Redux

---

app/controllers/Application.scala
app/filters/CheckCacheHeadersFilter.scala
app/lib/actions/CachedAction.scala
app/lib/actions/PrivateAction.scala
app/lib/httpheaders/CacheControl.scala
app/lib/httpheaders/package.scala
app/wiring/AppComponents.scala
build.sbt
test/controllers/ApplicationTest.scala
test/lib/actions/CachedActionTest.scala
test/lib/actions/PrivateActionTest.scala
test/lib/httpheaders/DateTime2ToHttpDateFormatTest.scala

Current cache time of 1 hour is too long.  This PR makes it easy to adjust the cache time of each route.
[**Trello Card**](https://trello.com/c/32Fj8QEk/476-sort-out-caching-and-asset-hashing-for-support-frontend)

Cache headers

---

assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaCircle/ctaCircle.scss
assets/components/infoText/infoText.scss
assets/components/simpleHeading/simpleHeading.jsx
assets/components/simpleHeading/simpleHeading.scss
assets/components/svg/svg.jsx
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/WayOfSupport.jsx
assets/pages/bundles-landing/components/WaysOfSupport.jsx
assets/stylesheets/gu-sass/breakpoints.scss
assets/stylesheets/gu-sass/typography.scss
assets/stylesheets/main.scss

This is the first attempt at implementing a section of the bundle landing page in the new support project.
Since our SVGs are not complicated, we decided to use a component with all the SVGs inline. Alternately, we could put all the SVGs in separated files, create a build step and use a webpack's SVG loader or file loader to load the SVG in the corresponding component. Nevertheless, considering our SVGs are simple (so far) we decided to go with the approach of the SVG component. Therefore, the developer whenever wants to add a new SVG, she or he must copy the content of the path tag inside the SVG component.    
[**Trello Card**](https://trello.com/c/oviKRuM6/483-other-ways-of-contribute-component)
* Defined an SVG component with the first SVGs.
* Created the other ways of support …

First draft of the other ways of support component

---

assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Introduction.jsx
assets/stylesheets/gu-sass/layout.scss

To add the introduction section to the bundles landing page. Also includes a margin fix.
[**Trello Card**](https://trello.com/c/gxM6AHn6/519-introduction)
- Added `Introduction` component.
- Added introduction styles.
- Fixed issues with margins for phablet.

Bundles Landing Introduction

---

.babelrc
.eslintrc
.flowconfig
assets/pages/bundles-landing/actions/__tests__/bundlesLandingActionsTest.js
assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/__tests__/reducersTest.js
assets/pages/bundles-landing/reducers/reducers.js
package.json
webpack.config.js

In order to improve our code quality, we decided to add tests for redux's actions and reducers. Therefore in this PR we are:
* Setting up Jest as our test framework.
* Adding tests for actions and reducers.
* Removing babel's configuration from webpack.config.js and putting it inside .babelrc
[**Trello Card**](https://trello.com/c/bkkhsfXD/520-writing-jest-tests-for-support-frontend)

Adding Jest tests for reducers and actions

---

app/lib/CustomHttpErrorHandler.scala
app/lib/actions/CachedAction.scala
app/lib/httpheaders/CacheControl.scala
app/wiring/AppComponents.scala

We have a filter that throws an exception if a Result doesn't have cache headers.  HTTP errors don't currently have cache headers so all return 500 Internal server error. 
This change means that we serve a 404 if a file isn't found instead of a 500, with a cache time of 30s

Add cache headers to errors

---

assets/components/headers/simpleHeader/simpleHeader.scss
assets/stylesheets/gu-sass/layout.scss

There were some issues with the layout of the simple header, mainly paddings. This adjusts those paddings. It also moves some code out of the shared `layout.scss` file and into the sass file for the simple header, as it's unlikely to be shareable between different headers.
[**Trello Card**](https://trello.com/c/kVzFOSqn/535-header-tweaks)
- Made the padding above the header 6px and below 12px.
- Reworked the way the heights and paddings are handled, some of them were displaying things incorrectly.
- Moved header paddings out of the shared layout file.
cc: @superfrank
**Narrow:**
**Medium:**
**Wide:**

Simple Header Tweaks

---

assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/components/WaysOfSupport.jsx
assets/pages/bundles-landing/helpers/queryParameter.js
assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/reducers.js

We want to be able to propagate the INTCMP (internal campaign code) through the different links in the bundle landing page.
[**Trello Card**](https://trello.com/c/X9DH7Kzl/536-ways-of-support-passes-through-correct-intcmp)
* Add the INTCMP to the state.
* WaysOfSupport and Bundles components are able to understand intcmp state.

Campaign code logic

---

.eslintignore
.flowconfig
.gitignore
assets/components/gridImage/gridImage.jsx
assets/components/gridPicture/gridPicture.jsx
assets/helpers/__tests__/theGridTest.js
assets/helpers/__tests__/utilitiesTest.js
assets/helpers/theGrid.js
assets/helpers/utilities.js
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/WayOfSupport.jsx
assets/pages/bundles-landing/components/WaysOfSupport.jsx
assets/pages/bundles-landing/components/WhySupport.jsx
assets/pages/hello-world/helloWorld.jsx

We'd like to display images from the Grid on the site, and we'd like them to be responsive because it's 2017! The focus of this PR is the addition of two new React components, and `theGrid` helper module, to achieve this:
A responsive image tag with `srcset` and `sizes`. Example:
```html
<img
srcset="https://media.guim.co.uk/grid_id/200.jpg 200w"
sizes="(max-width: 480px) 100vw, 50vw"
src="https://media.guim.co.uk/grid_id/500.jpg"
alt="description"
>
```
A responsive picture tag, supporting multiple `<source>` elements and a fallback `src`. Example:
```html
<picture>
<source
srcset="https://media.guim.co.uk/grid_id_1/200.jpg 200w"
sizes="(max-width: 480px) 100vw, 50vw"
media="(max-width: 980px)"
>
<source
srcset="https://media.guim.co.uk/grid_id_2/1000.jpg 1000w, …
```

Add Image Components

---

assets/components/gridImage/gridImage.jsx
assets/components/svg/svg.jsx
assets/components/video/video.jsx
assets/components/video/video.scss
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/WhySupport.jsx
assets/stylesheets/gu-sass/layout.scss
assets/stylesheets/main.scss

This adds a video component to allow the embedding of youtube videos on the site. It's fairly minimal at the moment, simply creating a standard iframe embed, as we're still thinking about what the final design for videos will be (whether they will include a poster, whether to use the yellow/black styling from dotcom, etc). I've included some basic functionality for adding a poster, but it may require some tweaking (particularly the styling).
[**Trello Card**](https://trello.com/c/qXeCj16v/530-add-videos-to-new-site)
cc: @superfrank
- Made `GridImg` available as a type to other components.
- Added a `Video` component to embed youtube videos.
- Added a video to the bundles landing page.
- Tweaked the content margins for very narrow (sub `mobile` breakpoints).

Add Video Component

---

app/views/main.scala.html

We would like our site to work in older browsers. This adds the polyfill service with the [default bundle](https://polyfill.io/v2/docs/features/#default-sets) plus [`Array.prototype.find`](https://polyfill.io/v2/docs/features/#Array_prototype_find).
This is an initial implementation so that we can go live. As with a few other things, we will probably come back to this later with a view to improving performance (e.g. [async loading](https://polyfill.io/v2/docs/examples#feature-detection)).
[**Trello Card**](https://trello.com/c/U8UJfmkI/485-add-polyfill-for-old-browsers)
cc: @janua
- Added script tag for the polyfill service to the main template, loading before the rest of the scripts on the page.
The polyfill download sizes relative to our own (non-gzipped) js bundle on the landing page. …

Add Polyfills

---

app/wiring/AppComponents.scala
conf/routes

The existing live bundles landing page is served from /uk, so the new one needs to as well so that it is a drop in replacement.  I've added a redirect from '/' for convenience.

Move bundles landing page to /uk to for backwards compatibility

---

assets/pages/bundles-landing/components/Bundles.jsx

We haven’t built the backend in support.theguardian.com.  This change means we can release the frontend before the backend.

Use membership for recurring contributions

---

assets/pages/bundles-landing/bundlesLanding.scss
assets/stylesheets/gu-sass/typography.scss
assets/stylesheets/gu-sass/webfonts.scss
assets/stylesheets/main.scss

So far I've come up with **four** options for applying fonts to support-frontend, in order of increasing complexity:
- Add `guss-webfonts` to the project via bower.
- Copy-paste the code from `guss-webfonts` into the project, and tweak it for our needs.
- Rewrite `guss-webfonts` to pull the fonts from dotcom rather than `pasteup.guim.co.uk`.
- Create an iframe-based script hosted by dotcom, which will retrieve the fonts from `localStorage`/ajax them in, and send them across via `postMessage`.
There are pros and cons to each option, which are probably a bit involved to get into for this PR description, but, in short, I've gone for the second option (but please have a word with me if you want to go into the details). I've taken the code from …

Add Pasteup/Guss Webfonts

---

build.sbt

This stops the scala sources being recompiled every time you make a frontend change, making development more pleasant

Exclude Play generated files from scalariform

---

assets/components/ctaLink/ctaLink.jsx
assets/components/ctaLink/ctaLink.scss
assets/components/doubleHeading/doubleHeading.scss
assets/components/featureList/featureList.scss
assets/components/numberInput/numberInput.scss
assets/components/radioToggle/radioToggle.jsx
assets/pages/bundles-landing/actions/__tests__/bundlesLandingActionsTest.js
assets/pages/bundles-landing/actions/bundlesLandingActions.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundle.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/components/ContribAmounts.jsx
assets/pages/bundles-landing/components/Introduction.jsx
assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/__tests__/reducersTest.js
assets/pages/bundles-landing/reducers/reducers.js

a) The bundles on the landing page need some styling applied to them.
b) There are some updated designs for the bundles, which are applied here.
This is mostly heavy on the CSS, to apply styling to the bundles across the breakpoints, and there a couple of React/JSX tweaks to go with this. The layouts at narrower breakpoints don't quite match what this page looks like in membership-frontend, because some of our breakpoints and margins don't quite match up.
There are still a couple of bugs in IE10 and Safari 8 (sigh), which can be fixed in a later PR when we're sure that we won't be making more design changes before going live.
[**Trello Card**](https://trello.com/c/52DEBiP3/573-style-the-bundles-section-of-the-landing-page), and [another](https://trello.com/c/zpuu7hjY/550-change-the-become- …

Style The Bundles On The Landing Page, And Apply Design Changes

---

app/config/ConfigImplicits.scala
app/config/Configuration.scala
app/config/Stages.scala
app/monitoring/SentryLogging.scala
app/wiring/AppComponents.scala
build.sbt
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf

So that we receive notifications of server-side errors on support-frontend
[**Trello Card**](https://trello.com/c/zVixRLyG/525-add-sentry-logging-to-support-frontend-server-side)

Add server-side sentry logging

---

webpack.config.js

If the default font is not 16 px we want to be able to render everything correctly. Therefore, we change all the `px` values to `rem` values in compiling time.
* webpack conf.

Px to Rem fixed

---

app/views/react.scala.html

Currently, the users that don't js in their browser see an white page. In this PR we add a default message asking them to turn on javascript. 
The style of this message is in line because we don't want to mix it with the style that is generated via sass.
[**Trello Card**](https://trello.com/c/UQTJvBGz/509-add-a-no-javascript-message)
* Add a no js message in the react template.

No js message

---

assets/components/headers/simpleHeader/simpleHeader.jsx
assets/components/svg/svg.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/ContribAmounts.jsx

We want the bundles landing page to work in old browsers from which we still get reasonable amounts of traffic, specifically Internet Explorer 10+ and Safari 8.
[**Trello Card**](https://trello.com/c/no7qELSS/580-fix-ie-and-safari-8-graphical-bugs)
- Fixed an issue in IE where SVGs weren't aligning correctly. They're still a little wonky (the header appears on the left instead of the right), but they're no longer appearing in the middle of text as before.
- Reworked the use of flexbox in contribution amounts, so that it looks alright (not perfect) in Safari 8.
- Fixed an alignment issue in the introduction copy.
- Made the logo a link back to dotcom.
**IE10**:
**Safari 8**:

Bundles Landing Page - Fixes For Old Browsers

---

README.md
build.sbt
docs/development.md
docs/setup.md
nginx/README.md
nginx/setup.sh
nginx/support.conf
package.json
webpack.config.js
yarn.lock

1. Working with HTTPS in dev means we're more likely to catch browser-security related issues early
2. Using Nginx gives us a common domain of `.thegulocal.com`, which means Identity cookies etc are shared correctly, CORS issues are more realistic, etc.
The Nginx config is mostly copied from `membership-frontend`:
https://github.com/guardian/membership-frontend/tree/cf07a5791/nginx
...with a few redundant or obsolete ssl settings removed from the Nginx config.
It's necessary to pass `--public sup.thegulocal.com:9111` to the `webpack-dev-server`, otherwise I got a plain "Invalid Host header" response on hitting https://sup.thegulocal.com/uk . The update of `webpack-dev-server` is due to various related-sounding security bugs:
* https://github.com/webpack/webpack-dev-server/issues/882#issuec …

Ensure we're using HTTPS in dev so we catch related browser security problems

---

assets/pages/bundles-landing/components/WaysOfSupport.jsx
yarn.lock

I noticed a small copy error; this change corrects it.
* Fix typo, using original copy from: https://membership.theguardian.com/patrons
* Note that this seems to have made some changes to yarn.lock, even though I haven't amended any dependencies.
Before:
After:
cc @svillafe

Fix typo on new landing page

---

app/wiring/AppComponents.scala
build.sbt

Smaller file sizes costs us and our users less in bandwidth.  Also loads faster.
[**Trello Card**](https://trello.com/c/ecVxSQj7/579-enable-gzip-for-support-frontend)

Gzip non-image responses

---

assets/helpers/abtest.js
assets/helpers/ga.js
assets/pages/bundles-landing/bundlesLanding.jsx

We would like to track the experience of the user in GA, therefore we set the variants of the A/B tests in the experience dimension.
[**Trello Card**](https://trello.com/c/5H9yXN3H/560-send-a%2Fb-test-results-to-ga)
* Added `setDimension` method to `ga.js`.
* Added method to transform participation to string.

Adding ga reporting for ab test framework

---

assets/components/ctaCircle/ctaCircle.jsx
assets/helpers/abtest.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/components/WayOfSupport.jsx
assets/pages/bundles-landing/components/WaysOfSupport.jsx
assets/pages/bundles-landing/helpers/abtest.js
assets/pages/bundles-landing/reducers/__tests__/reducersTest.js
package.json

We set up an example test in order to test the abacus stack for support frontend. In order to send an Ophan event when we click the link, I had to replace the `href` attribute from the `ctaCircle` component and pass an `onClick` function instead.
* control
* variantA
[**Trello Card**](https://trello.com/c/LgEpY7Ok/559-send-a%2Fb-test-results-to-ophan)

Record events with ophan

---

assets/components/textInput/textInput.jsx
assets/helpers/url.js
assets/helpers/utilities.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/monthly-contributions/actions/monthlyContributionsActions.js
assets/pages/monthly-contributions/components/nameForm.jsx
assets/pages/monthly-contributions/components/paymentMethods.jsx
assets/pages/monthly-contributions/helpers/validation.js
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/monthlyContributions.scss
assets/pages/monthly-contributions/reducers/reducers.js
assets/stylesheets/main.scss
conf/routes
webpack.config.js

To generate the boilerplate for the recurring contributions checkout page. There will be later PRs to add in design/style changes, and hook up Stripe/PayPal and the POST endpoint, but this is going to happen in parts, to avoid stale branches and massive PRs.
[**Trello Card**](https://trello.com/c/K9zMv1FJ/595-create-outline-of-monthly-contrib-checkout)
- Created a shared `textInput` component, with an optional label.
- Moved the `getQueryParameter` helper function out into shared helpers, since it's useful across multiple pages.
- Added a utility to round numbers to x.d.p., because apparently that's not straightforward in JavaScript.
- Added the new page to the routes file and webpack.
- Created a `monthly-contributions` page, consisting of the following:
+ The main page in …

Recurring Contribution Checkout

---

app/codecs/CirceDecoders.scala
app/codecs/Codec.scala
app/controllers/MonthlyContributions.scala
app/lib/PlayImplicits.scala
app/lib/aws/package.scala
app/lib/stepfunctions/MonthlyContributionsClient.scala
build.sbt

So that we can trace logging data from support-frontend through each support-worker lambda execution
(needs new release of support-models)

Add request id to support workers requests

---

.gitignore
app/wiring/AppComponents.scala
conf/routes
package.json
public/robots.txt
webpack.config.js

We would like a `robots.txt` file for all the robots.
Although the diff is fairly minimal, there are some changes here to how we handle our public assets:
- From now on, the `public` directory is version controlled, and can contain files like `robots.txt`.
- Webpack now builds to the `compiled-assets` subdirectory in public.
- Play will now serve anything on the url `/assets` from the `compiled-assets` directory, and will attempt to serve any other unmatched path from `public`.
[**Trello Card**](https://trello.com/c/MG3B00EU/600-we-need-a-robots.txt)
- Ignored the `compiled-assets` directory.
- Tweaked the `/assets` route so that it serves from `compiled-assets`.
- Added a new `/*file` route that attempts to serve from `public`.
- Set up webpack to output to `public/compiled-assets`, and …

Add Robots.txt (And Mix Up Public Assets Handling)

---

app/views/main.scala.html
app/views/react.scala.html
assets/components/stripePopUpButton/stripePopUpButton.jsx
assets/helpers/stripeCheckout/stripeCheckout.js
assets/helpers/stripeCheckout/stripeCheckoutActions.js
assets/helpers/stripeCheckout/stripeCheckoutReducer.js
assets/pages/monthly-contributions/actions/monthlyContributionsActions.js
assets/pages/monthly-contributions/components/paymentMethods.jsx
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/reducers/reducers.js
package.json
yarn.lock

We want to be able to charge our readers with Stripe.
There are two ways of implementing Stripe,  using Stripe Checkout (Stripe's pop up box) and using Stripe Elements (custom implementation). This PR, implements the Stripe Checkout version. In order to achieve it, we created a stripeCheckout module which is in charge of injecting the script tag to load the Stripe checkout script. In addition, we created the presentational component called StripePopUpButton which is using the StripeCheckout module. 
In order to be able to interact with the rest of the application, StripeCheckout also defines the StripeCheckout reducer and StripeCheckout Actions. The page that wants to include a `StripePopUpButton` has to import that element and add to the redux state the `stripeCheckoutReducer`.
[**Trello …

Implementation of Stripe Checkout in the monthly contribution page

---

build.sbt
cloud-formation/cfn.yaml
conf/riff-raff.yaml

With the old project name of 'frontend', there was the potential for confusion with DotCom frontend :)
This gives us two improvements, one on the sbt console, where the prompt now says `support-frontend` rather than `frontend`:
```
$ sbt
[info] Loading global plugins from /home/roberto/.sbt/0.13/plugins
[info] Loading project definition from /home/roberto/development/support-frontend/project
[info] Set current project to support-frontend (in build file:/home/roberto/development/support-frontend/)
[support-frontend] $
```
The other improvement is with IntelliJ, which will give a more meaningful name for the project under 'Open Recent'.

Make sbt project name more distinct: 'support-frontend' vs 'frontend'

---

build.sbt
cloud-formation/cfn.yaml
conf/riff-raff.yaml

Setting `riffRaffPackageName := "frontend"` is a better solution than changing the RiffRaff deployment name from `frontend` to `support-frontend` which I unwisely did in a0f1f98 as part of #77. The ELB ended up being called `support-PROD-support-frontend` - awful repetition of 'support', yuck!
This commit also includes an improving RiffRaff config change suggested in passing by Simon Hildrew: `amiTags` are a valid parameter for [`cloud-formation`](https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation) types, so you don't need a separate `ami-cloudformation-parameter` entry - thus saving several lines of config!

Go back to using 'frontend' as the AWS App tag name

---

assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/reducers.js

The preselected amount on the [contributions site](https://contribute.theguardian.com/uk) is £50, we should make it the same on support.
[**Trello Card**](https://trello.com/c/FLZ4gFH5/625-highlight-50-instead-of-20-on-supporttheguardian)
- Set default one-off contribution state to have a value of £50.

Change Default One-Off Contrib To 50

---

cloud-formation/cfn.yaml
cloud-formation/validate.sh

And add a validation script for the CloudFormation template
To enable support-frontend to discover the support-workers step function and trigger an execution.
[**Trello Card**](https://trello.com/c/uyoRAM2L/643-add-necessary-policies-to-support-frontend-to-allow-it-to-call-support-workers)

Add CloudFormation policy to allow access to the support-workers state machine

---

assets/helpers/abtest.js
assets/helpers/storage.js
assets/helpers/utilities.js

In Private Browsing mode, Safari does weird things to localStorage. It's still available on the window object, but it has a quota of 0 (meaning 0 space to store things in, rather than the default 5MB). This was breaking our JavaScript, since we assumed up until now that if it was available then it was usable.
The code making use of localStorage was in the `abtest` module. This PR adds a utility function to check for a functioning implementation of localStorage, and only attempts to use it in the abtests module if it exists.
I think our abtests should still work fine in this case, thoughts @svillafe?
[**Trello Card**](https://trello.com/c/riIg2iXz/627-safari-private-browsing-localstorage-fallback)
- Added utility function to check for functioning localStorage.
- Only use localStorage in …

Fix Safari LocalStorage Bug

---

assets/components/displayName/displayName.jsx
assets/components/stripePopUpButton/stripePopUpButton.jsx
assets/helpers/user.js
assets/helpers/user/userActions.js
assets/helpers/user/userReducer.js
assets/pages/monthly-contributions/actions/monthlyContributionsActions.js
assets/pages/monthly-contributions/components/nameForm.jsx
assets/pages/monthly-contributions/components/paymentMethods.jsx
assets/pages/monthly-contributions/helpers/ajax.js
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/reducers/reducers.js

Where possible, we'd like to consolidate our state in the redux store. This turns the user object into a reusable state object in the store, and moves management of first and last name under the same object.
This will hopefully make more of our user-related code reusable across pages.
[**Trello Card**](https://trello.com/c/k3rPcOZR/611-create-a-user-reducer-to-populate-user-data-from-play-backend)
- Hooked `displayName` and `paymentMethods` up to redux store, to read from the user state object.
- Built out actions and a reducer for the user state in the `user` module. Set initial state from the guardian window object.
- Moved `firstName` and `lastName` update management out of `monthlyContributions` and into the `user` modules.
- Wired up the rest of monthly contributions (`nameForm.jsx`, …

User Reducer

---

cloud-formation/cfn.yaml
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf
conf/application.conf
docs/setup.md

Currently support-workers and support-frontend both have a private conf file called support.private.conf which means that it is difficult to work on them both locally as the conf files either overwrite each other or have to be merged
[Trello card here](https://trello.com/c/kMjYGnXa/649-rename-private-conf-file-for-support-projects-to-allow-local-development-on-both-projects)

Rename the private conf file

---

assets/components/featureList/featureList.jsx
assets/pages/bundles-landing/components/Bundles.jsx

The bundles used to be defined in a huge object, now we created types so it is easier to specify the return values of different functions.

Types definition for bundles

---

app/config/Configuration.scala
app/controllers/MonthlyContributions.scala
app/services/MembersDataService.scala
app/wiring/AppComponents.scala
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf
conf/routes
test/controllers/MonthlyContributionsTest.scala

So that existing recurring contributors can't make another recurring contribution
[**Trello Card**](https://trello.com/c/MKT0NGtF/608-implement-the-redirect-mechanism-for-handling-existing-contributors)

Redirect users who are already recurring to existing-contributor page

---

assets/components/infoSection/infoSection.jsx
assets/components/textInput/textInput.jsx
assets/pages/monthly-contributions/components/nameForm.jsx
assets/pages/monthly-contributions/components/paymentMethods.jsx

The monthly contributions checkout page is authenticated, which means that user credentials are available, which means that we can pre-fill the two form fields (first name and last name). However, we need to allow users to update this, in case the information they entered when they signed up is not appropriate for taking payments. This opens up the possibility of those fields becoming empty, which is not acceptable when the information is posted to the backend.
One solution to this would be to run validation when the payment button is clicked, and prevent payment if it fails. However, this will only work for the Stripe button. We don't have control over the PayPal button that is soon to be added to this page, and so we cannot go with this approach.
Instead, what this PR does is check the …

Validate Monthly Contrib

---

assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/ctaLink/ctaLink.scss
assets/components/doubleHeading/doubleHeading.jsx
assets/helpers/abtest.js
assets/helpers/utilities.js
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundle.jsx
assets/pages/bundles-landing/components/Bundles.jsx

This PR implements the first A/B Test. It is intended not only test the proposed change, but also the entire A/B test framework.
[**Trello Card**](https://trello.com/c/OcvCFZw9/645-implement-a-simple-title-ab-test)
Line added to contribute section of support.theguardian.com (bundle landing page).
**SupportFrontEndContribution** 
> By adding a sentence to persuade users to the contributions section we can increase click through to contribute with credit/ debit card 
| Control | VariantA |
|---------|----------|
|   <img width="316" alt="picture 285" src="https://user-images.githubusercontent.com/825398/27481946-3bdcc6f0-5817-11e7-8dc4-ccf0d4d7212c.png">  |    <img width="313" alt="picture 284" src="https://user-images.githubusercontent.com/825398/27481958-47967fea-5817-11e7-989e-2cd534aca53 …

Contribution A/B test

---

assets/helpers/abtest.js
assets/pages/bundles-landing/components/Bundles.jsx

We need to wait to run this test.
* Turning off the Contribution test
* Only tracking conversion if you are in a variant.
N/A

Turning off the contribution test.

---

app/views/react.scala.html
assets/stylesheets/gu-sass/layout.scss

Classic problem. For pages that are shorter than the viewport there's a bunch of whitespace below the footer. This forces the footer to the bottom using flexbox (and actually works in IE!). Inspiration [here](https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3).
[**Trello Card**](https://trello.com/c/vPF3XIzw/650-sort-the-support-footer-out)
- Created a new class for the wrapping main element (the one that we inject our React into).
- Applied `100%` height to the `html` and `body` tags, and the `gu-content-margin` class.
**Before:**
**After:**

Sticky Support Footer

---

assets/pages/bundles-landing/components/Bundles.jsx

On the bundles landing page we have the option of entering a user-defined amount. There are restrictions on this amount, and we display an error message if the value entered is not allowed.
This PR blocks the CTA if an error occurs.
[**Trello Card**](https://trello.com/c/3eGhPY7R/606-stop-other-amount-contribution-flow-from-giving-error-400-bad-request)
- In the CTA onClick callback, if there is an error in user input, don't run the tracking code or redirect the user.

Fix Error On Incorrect 'Other Amount' for Contributions

---

assets/pages/monthly-contributions-existing/monthlyContributionsExisting.jsx
assets/pages/monthly-contributions-existing/monthlyContributionsExisting.scss
assets/stylesheets/main.scss
conf/routes
webpack.config.js

Users cannot become recurring contributors twice. If they arrive on the checkout page and they are already a contributor, we want to redirect them to a page explaining the situation. The redirect logic was implemented in #95, directing them to `monthly-contributions/existing-contributor` on the server-side.
This PR adds a new page to sit on this URL, with some copy that I've made up and a link to one-off contributions. There's some new copy coming down the pipeline that we'll add in a future PR.
[**Trello Card**](https://trello.com/c/CP9COwnQ/609-create-an-existing-contributor-page)
- Added a page and stylesheet for existing contributions.
- Added a route and webpack config entry for the new page.

Existing Contributor Page

---

app/views/authenticatedFullUserReactTemplate.scala.html
assets/pages/monthly-contributions-thankyou/monthlyContributionsThankyou.jsx
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/stylesheets/gu-sass/layout.scss

The first attempt at doing this, in #103, resulted in some issues, the worst of which was Safari 8:
In brief, the implementation of flexbox in Safari 8 is terrible. It also looked a little wonky in modern Safari and Chrome (although fine in Firefox for some reason):
This PR tweaks the implementation, and uses the `@supports` CSS rule to apply flexbox only if it is supported. In practice, because the `@supports` rule itself is not supported on the oldest browsers (IE and Safari 8), flexbox is turned off for all of these (even though it was actually ok in IE in this case). In summary, the sticky footer works in Firefox, Chrome, Edge and Safari 9+, and falls back to not being sticky in anything older.
[**Trello Card**](https://trello.com/c/0XbFCzkt/661-fix-support-footer-on-safari-8)
- …

Sticky Support Footer - Part 2

---

assets/components/doubleHeading/doubleHeading.scss
assets/components/featureList/featureList.scss
assets/components/numberInput/numberInput.scss
assets/components/termsPrivacy/termsPrivacy.scss
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/components/Introduction.jsx

To make the bundles landing page look good before we go live with the baseline test. This PR only modifies the introduction and bundles sections.
[**Trello Card**](https://trello.com/c/uE8jYPo2/671-style-changes-on-shopfront-page)
cc: @superfrank
- Made the print bundles white with blue highlights.
- Made the contributions bundle yellow and black, dropped the orange.
- Tweaked the layout and copy for the introduction text.
- Made the introduction blue with a bleed into the bundles section.
- Miscellaneous other style tweaks.
**Desktop:**
**Tablet:**
**Mobile:**

Modernise Bundles Landing Page

---

app/config/Configuration.scala
app/config/TouchpointConfigProvider.scala
app/controllers/Application.scala
app/controllers/MonthlyContributions.scala
app/views/monthlyContributions.scala.html
app/wiring/AppComponents.scala
assets/helpers/stripeCheckout/stripeCheckout.js
conf/DEV.public.conf
test/controllers/MonthlyContributionsTest.scala

Currently Stripe is hardcoded to run with the test public key, but we want to use the production one in PROD. This PR selects the appropriate key based upon stage (DEV/UAT/PROD), and makes it available on the guardian window object. It stores the key in the private config in S3.
We have three stages, DEV, UAT and PROD. Stripe has two, Test and Production. These line up as follows:
- In **DEV** we use **Stripe Test**.
- In **UAT** we use **Stripe Test**.
- In **PROD** we use **Stripe Production**.
This PR also sets the DEV stage back to DEV in the config, it was temporarily set to CODE a little while ago to allow a developer running locally to still hit the CODE step functions. Instead we've tweaked things in `AppComponents` so that even if the stage is DEV, we're still hitting the CODE …

Add Production Stripe

---

assets/components/doubleHeading/doubleHeading.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/reducers.js

Follow-up to #108, this makes another couple of tweaks to the designs:
1. Made the CTA for paper+digital blue instead of white.
2. Hide the 'from £5/month' subheading on the contributions bundle when the user selects one-off contribution.
3. Make £10 the default recurring contribution.
cc: @Elvis-Rimdap
- Made the doubleHeading component still render an h2 even when there is no subheading.
- Make the empty subheading the same height to stop jumping.
- Made the paper+digital cat blue with white highlights, darkens on hover.
- Passed through an empty subheading for one-off contributions.
- Made £10 the default recurring contrib in the reducer initial state.
**One-off subheading:**
**Blue CTA:**
**£10 Recurring:**

Bundles Landing - Minor Design Tweaks

---

assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/radioToggle/radioToggle.scss
assets/helpers/utilities.js
assets/pages/bundles-landing/bundlesLanding.scss

We need the bundle landing page to as accessible as possible. Therefore, in this PR we fix the tab flow of the page and additionally we add the onKeyBehaviour for the links that are using onClick functions.
[**Trello Card**](https://trello.com/c/IyG06KgO/654-accessibility-issue-not-possible-to-navigate-properly-on-supporttheguardiancom-without-a-mouse)

Fix bundles landing accessibility

---

assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/subscriptionsLinks.js

When we're running tests on dotcom that drive traffic to the bundles landing page (e.g. the [re-baseline test](https://github.com/guardian/frontend/pull/17376)), we are given an INTCMP code as a query parameter. This parameter is then passed on in the links on that page, to keep track of onward journeys to other sites.
Unfortunately, in the case of subs, this parameter is not preserved all the way through the journey, either in the URL or in the data lake, which means we cannot track conversions with it. Therefore we need to use custom promo codes that will be set whenever a user arrives on the bundles landing page in a test.
This PR adds a module to handle this.
- Created a helper module for creating the subscriptions CTA links. This maps test INTCMP codes to custom test promo codes, and …

Use Custom Subs Promo Codes For Tests

---

build.sbt

To fix `[NoSuchMethodError: play.api.mvc.BodyParsers$.parse()Lplay/api/mvc/BodyParsers$parse$;]` when `POST`ing to `/monthly-contributions/create`.
* Upgrade to Play 2.6 version of play-circe

Update circe plugin to Play 2.6 version

---

assets/components/headers/simpleHeader/simpleHeader.jsx
assets/components/headers/simpleHeader/simpleHeader.scss

To keep @superfrank happy.
*or*
The logo in the header is stuck on the left in IE, but appears on the right in all other browsers. It should be on the right. It's a quick fix, simply moved the float to the enclosing link instead of applying it directly to the SVG. If only all CSS/IE issues were this straightforward.
**Note:** The logo now appears slightly smaller than it should on IE (looks fine in other browsers).
[**Trello Card**](https://trello.com/c/CEPJp5Lv/670-fix-logo-on-ie-to-make-frank-happy-size)
- Move the `float: right` to the enclosing anchor tag, because IE doesn't like SVGs.
**Before:**
**After:**

Fix Header Logo on IE

---

assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/numberInput/numberInput.jsx
assets/helpers/utilities.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/components/ContribAmounts.jsx
assets/stylesheets/main.scss

In order to improve the a11y of our site, we add the behaviour of the click on the button when the user press enter or spacebar on the input field.
[**Trello Card**](https://trello.com/c/IyG06KgO/654-accessibility-issue-not-possible-to-navigate-properly-on-supporttheguardiancom-without-a-mouse)

A11y input field 

---

assets/components/stripePopUpButton/stripePopUpButton.scss

The credit card inside the Stripe button was not rendering correctly. This PR fix that across different browsers that detail.
| Chrome | IE 10 | Safari | Firefox |
|--------|-------|--------|---------|
| <img width="561" alt="picture 313" src="https://user-images.githubusercontent.com/825398/28122341-d6e203ec-6715-11e7-9acb-2e7f72476a06.png"> |    <img width="541" alt="picture 316" src="https://user-images.githubusercontent.com/825398/28124587-fa87e770-671b-11e7-8284-315b92bfc06e.png">   | <img width="568" alt="picture 314" src="https://user-images.githubusercontent.com/825398/28122406-0bc28ab4-6716-11e7-8909-06e4e9d1a35b.png">  |   <img width="546" alt="picture 315" src="https://user-images.githubusercontent.com/825398/28122483-3974a596-6716-11e7-8f0c-d65944e7d767.png">     |
| Chrome | …

Credit card SVG renders correctly across different browsers 

---

assets/components/ctaLink/ctaLink.jsx
assets/helpers/abtest.js
assets/pages/bundles-landing/components/Bundles.jsx

Removing the AB test introduced in #97. We're not going to run it any more, and this simplifies the codebase for some changes I want to make for Q2 - Test 2.
- Removed the test details from the `abtest` module.
- Removed the variant code from the bundles page.
- Pulled the three bundles out into mini React components, hopefully makes things more readable.

Remove Contribute AB Test

---

assets/components/payPalExpressButton/payPalExpressButton.jsx
assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
assets/helpers/payPalExpressCheckout/payPalExpressCheckoutActions.js
assets/helpers/stripeCheckout/stripeCheckoutActions.js
assets/pages/monthly-contributions/components/paymentMethods.jsx
assets/pages/monthly-contributions/helpers/ajax.js

In https://github.com/guardian/support-frontend/pull/129 there is a lot of similar code between PayPal and Stripe's checkout flows. This PR tries to merge the shared behaviour.
[**Trello Card**](https://trello.com/c/bOff46wP/726-refactor-paypal)
* The last step of the PayPal process was removed from `PayPalExpressCheckoutActions`, in this way we can reuse in the future the PayPal button for other flows, not only the ~~monthly~~ **recurring** contribution flow.
* Removed an unused Stripe's action.
* The `postCheckout` function in `ajax.js`, now works for Stripe and PayPal.

Paypal refactor

---

cloud-formation/cfn.yaml

1) the system is not multi-user so changing the permissions on this file seems a bit pointless
2) the permissions are being changed after the app launches
3) the user `${App}` (frontend) does not exist, so these lines fail anyway.  The app runs as support-frontend.

Do not chown/chmod the private config

---

conf/CODE.public.conf

Allow CODE environment JS to connect to contributions CODE (contentSecurityPolicy was disallowing this)

Fix contribute domain in CODE

---

assets/helpers/abtest.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/contributions-landing/reducers/reducers.js

For Test 2 (looking at the value of adding recurring contributions in the UK), we're driving traffic to support-frontend and dropping users into an AB test when they arrive there. This AB test will show two versions of the contributions landing page:
- **Control:** One-off contributions only.
- **Variant:** One-off and monthly contributions.
This PR introduces this test, and applies the changes needed to show these two variants of the page.
**Note:** Don't know if the places I have applied some of these changes are the best, we haven't really settled on a convention for this yet.
[**Trello Card**](https://trello.com/c/7NhmhzZX/734-q2-test-2-create-ab-test-in-support-frontend)
- Added a new test for 100% of the audience, switched off for now.
- Changed the copy on the contributions landing …

Contributions Landing AB Test

---

assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingUK.jsx

Tweak for the work done in #143. Normally you would only make changes for users who are in the variant of an AB test, so control and notintest see the same thing. In this case that would be one-off contributions only.
However, the notintest view for this page is actually supposed to include both one-off and monthly, as this is what e.g. apps are expecting when they drive traffic to this page. It's only the control group in this test who should see one-off only. This PR updates the check to reflect that.
[**Trello Card**](https://trello.com/c/VIKQsLn0/743-show-both-one-off-and-monthly-if-notintest)
- Renamed flag for showing monthly content to `showMonthly`.
- Hide monthly content only for people who are in the control of this test.
**Control:**
**Variant & Notintest:**

Contributions Landing Test - Only Hide Monthly For Control

---

assets/pages/monthly-contributions/helpers/ajax.js
assets/pages/oneoff-contributions/helpers/ajax.js

Bug in the payment flow fixed for recurring and one off contributions. The bug consisted of the error message being displayed before going to the next page.
[**Trello Card**](https://trello.com/c/VHzbSw0d/758-in-the-process-of-submitting-the-monthly-contributions-the-error-message-flashes-up)

Added two missing return statements.

---

assets/components/paymentMethods/paymentMethods.jsx
assets/helpers/user/userReducer.js
assets/pages/monthly-contributions/components/paymentMethodsContainer.jsx
assets/pages/oneoff-contributions/components/paymentMethodsContainer.jsx

For the one-off and monthly contributions checkouts, if mandatory fields are not filled in then the payment buttons should be hidden. This was happening for monthly but not for one-off. The reason is that the payment methods component was hard-coded to checking for first and last name, whereas one-off uses full name and email.
This PR pulls the validation check out of the payment methods component, doing it at the page level and then passing in a `hide` prop determining whether the payment buttons should be visible or not.
[**Trello Card**](https://trello.com/c/1wIBXPHU/760-one-off-checkout-hide-payment-broken)
- Added a `hide` prop to the `paymentMethods` component, to hide the buttons.
- Set monthly contributions to check for first and last name.
- Set one-off contributions to check for …

Fix Hide Payments On Empty Form

---

build.sbt

1) we aren’t using it
2) akka are deprecating it so we shouldn’t start using it

Remove akka-agent dependency

---

assets/components/legal/contribLegal/contribLegal.jsx
assets/components/legal/contribLegal/contribLegal.scss
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/components/contributionsIntroduction.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUK.jsx

To make the contributions landing page look fancier before we go live with the recurring contributions test. Also, to make sure we move the text around the page as much as possible at different breakpoints, because that's a key feature of this page 🙈.
[**Trello Card**](https://trello.com/c/nVhp7sX5/762-contributions-landing-page-tweaks)
cc: @amohkhan
- Made the contributions legal copy a single blob of text, no paragraphs here.
- Added a custom chunk of introduction text, and made sure the words do something new and exciting with every breakpoint we support.
- Moved the contribution card up to the right on wider breakpoints.
- Dropped a rogue comma!

Contributions Landing Design Updates

---

assets/pages/oneoff-contributions/helpers/ajax.js

So that the contributions 6month cookie is dropped when users oneoff-contribute from support.theguardian.com.  Dependant on https://github.com/guardian/contributions-frontend/pull/317.  Do not merge until contributions is deployed.
[**Trello Card**](https://trello.com/c/CKfct7nX/754-figure-out-how-the-contributions-6month-cookie-is-dropped-and-drop-in-for-one-off-contributions-in-support)

Allow contribute.theguardian.com to set cookies

---

assets/pages/oneoff-contributions/helpers/ajax.js

Visual indication of failure (rather than just a message in the console) so that users know what has happened if contributions-frontend is down/rejects their payment
[**Trello Card**](https://trello.com/c/HoNu0JLS/733-error-handling-for-one-off-contributions-post)

Display friendly error message if oneoff-contributions post fails

---

app/controllers/OneOffContributions.scala
test/controllers/OneOffContributionsTest.scala

Fixes bug:
There seems to be some odd behaviour on the checkout page when pulling signed in data for the first name, it shows 'Mario Mario' like it's repeating the first name

Fix autofill firstName lastName

---

conf/DEV.public.conf

For the rational, or if you are wondering if this will cause conflicts with Dotcom Identity Frontend, please see the following pull request:
https://github.com/guardian/identity-platform/pull/170
Please note that [Identity Frontend](https://github.com/guardian/identity-frontend) should now be accessible in DEV at 
```
profile.thegulocal.com
```
instead of 
```
profile-origin.thegulocal.com
```
May I ask you please to fresh pull `identity-frontend` and `identity-platform` and update your bookmarks to point to the new domain. You may also wish to remove profile-origin from `/etc/hosts`
Also reload Nginx config with
```
sudo nginx -s reload
```
cc @mario-galic

Update identity url in DEV

---

app/config/Configuration.scala
app/controllers/OneOffContributions.scala
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
app/wiring/Controllers.scala
assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/components/paymentMethods/paymentMethods.jsx
assets/helpers/payPalContributionsCheckout/__tests__/__snapshots__/payPalContributionsCheckoutReducerTests.js.snap
assets/helpers/payPalContributionsCheckout/__tests__/payPalContributionsCheckoutActionsTests.js
assets/helpers/payPalContributionsCheckout/__tests__/payPalContributionsCheckoutReducerTests.js
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckoutActions.js
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckoutReducer.js
assets/pages/monthly-contributions/actions/monthlyContributionsActions.js
assets/pages/monthly-contributions/components/paymentMethodsContainer.jsx
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/reducers/reducers.js
assets/pages/oneoff-contributions/actions/oneoffContributionsActions.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/reducers/reducers.js
conf/routes

We would like to have PayPal button in one off contributions.
[**Trello Card**](https://trello.com/c/YIRjPpFe/765-spike-add-paypal-to-the-one-off-contribution)
In a future PR, design changes will be introduced to improve the current button. 
https://github.com/guardian/contributions-frontend/pull/323

PayPal Contributions Integration

---

test/controllers/OneOffContributionsTest.scala

During https://github.com/guardian/support-frontend/pull/163 I broke the Scala tests, this PR fix them.

Fix scala tests for one-off contributions.

---

assets/components/inlinePaymentLogos/inlinePaymentLogos.scss

Fix payment logos for IE and Safari

[svg-fix-for-IE] Fix Visa Logo

---

app/controllers/MonthlyContributions.scala

So that real users can use support.theguardian.com to become recurring contributors
[**Trello Card**](https://trello.com/c/LZvTv3a0/658-q2-test-2-make-monthly-contributions-available-for-real-users)

Allow non-test users to access monthly contributions

---

assets/components/paymentAmount/paymentAmount.jsx
assets/components/paymentAmount/paymentAmount.scss
assets/pages/monthly-contributions/monthlyContributions.jsx

We used to handle correctly the amount between £1 - £99. This PR adds the more cases.

Fix the payment amount width for several type of numbers.

---

assets/pages/contributions-landing/contributionsLanding.scss

To offer a better user experience in mobile.
* Vertical spacing for contribution landing page in mobile.
| **Before** | **After** |
|--------|-------|
| ![oldmobile](https://user-images.githubusercontent.com/825398/29216296-2147528c-7ea6-11e7-8139-19c6dc3b9c70.png)    |    ![newmobile](https://user-images.githubusercontent.com/825398/29216299-25cb2054-7ea6-11e7-8520-110c996e6c4c.png)   |

Modified vertical spacing for mobile view

---

assets/helpers/url.js

We want to pick up query params even if they are in lowercase.
* Update URL helper.

Retrieve Query Params in lowercase.

---

assets/components/paymentAmount/paymentAmount.jsx
assets/helpers/contributions.js
assets/helpers/csrf/csrfReducer.js
assets/helpers/internationalisation/country.js
assets/helpers/internationalisation/currency.js
assets/helpers/payPalExpressCheckout/__tests__/__snapshots__/payPalExpressReducersTest.js.snap
assets/helpers/payPalExpressCheckout/__tests__/payPalExpressCheckoutActionsTest.js
assets/helpers/payPalExpressCheckout/__tests__/payPalExpressReducersTest.js
assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
assets/helpers/payPalExpressCheckout/payPalExpressCheckoutActions.js
assets/helpers/payPalExpressCheckout/payPalExpressCheckoutReducer.js
assets/helpers/stripeCheckout/stripeCheckoutActions.js
assets/helpers/stripeCheckout/stripeCheckoutReducer.js
assets/helpers/user/userReducer.js
assets/pages/monthly-contributions/actions/monthlyContributionsActions.js
assets/pages/monthly-contributions/helpers/ajax.js
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/reducers/reducers.js
assets/pages/oneoff-contributions/actions/oneoffContributionsActions.js
assets/pages/oneoff-contributions/helpers/ajax.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/reducers/reducers.js

To allow US users to make recurring contributions
Follow-up PR needed to add a "State" field since Zuora insist on this for US/Canada customs for tax reasons.
[**Trello Card**](https://trello.com/c/t4L9DPtI/699-test-3-us-recurring-update-frontend-for-dollars)

Add support for US dollars

---

conf/routes

The routes for our project are becoming inconsistent, both semantically and in terms of code cleanliness (we have a duplicate entry, probably left over from a rebase). We're also getting to the point where we're looking at internationalisation and thinking a bit more about the structure of our site. These changes tidy up the routes file, and attempt to semantically structure it in accordance with our probable future site layout:
```
/$country                            -> bundles landing page
/$country/contribute                 -> contributions landing page
/contribute/one-off                  -> one-off contrib checkout
/contribute/one-off/thankyou         -> one-off contrib thank you
/contribute/one-off/test-user        -> one-off contrib test users
/contribute/one-off/autofill …
```

Refactor Routes

---

app/controllers/MonthlyContributions.scala
assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
assets/helpers/routes.js
assets/helpers/url.js
assets/helpers/user/user.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/monthly-contributions-existing/monthlyContributionsExisting.jsx
assets/pages/monthly-contributions/helpers/ajax.js
assets/pages/oneoff-contributions/helpers/ajax.js
public/robots.txt
test/controllers/MonthlyContributionsTest.scala

In #176 the routes were updated to follow a more structured pattern. This PR updates the client-side code to make use of these new routes. It also takes the hardcoded URLs scattered across multiple files and consolidates them into a single `routes` helper.
[**Trello Card**](https://trello.com/c/nywxMPr4/725-tidy-up-our-routes)
- Created a `routes` helper.
- Updated the monthly contributions controller to use the new existing contributor route.
- Replaced hardcoded urls across multiple javascript files with lookups on the new routes object.

Tidy Routes - JavaScript

---

conf/routes
public/robots.txt
test/controllers/MonthlyContributionsTest.scala
test/controllers/OneOffContributionsTest.scala

Final instalment of the journey that began with #176, and continued with #180. This deletes the deprecated routes from the `routes` file and the `robots.txt`. It also updates some test descriptions to better reflect the new routes.
[**Trello Card**](https://trello.com/c/nywxMPr4/725-tidy-up-our-routes)
- Removed deprecated routes.
- Removed deprecated routes from `robots.txt`.
- Updated test descriptions.

Tidy Routes - Remove Deprecated

---

assets/pages/bundles-landing/components/Bundles.jsx

Up until now the bundles landing page has been sending contributions traffic out to membership and contributions. We did this because support-frontend wasn't yet ready to handle taking payments. But now it is 🎉!
This element now sends people to the recurring and one-off contributions checkouts in support-frontend.
[**Trello Card**](https://trello.com/c/ttSbANME/809-switch-bundles-landing-links-to-supporttheguardiancom)
- Updated recurring and one-off links to remain within support.theguardian.com.
- Both these checkouts use the same parameter for the amount, so we don't need to switch between `contributionValue` for membership and `amount` for contributions any more.

Switch Bundles Landing Page to Sending Contributions Traffic to support-frontend

---

assets/components/ctaLink/ctaLink.jsx
assets/components/stripePopUpButton/stripePopUpButton.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-thankyou/monthlyContributionsThankyou.jsx
build.sbt
conf/DEV.public.conf
test/selenium/ContributorSpec.scala
test/selenium/pages/ContributionsLanding.scala
test/selenium/pages/MonthlyContribution.scala
test/selenium/pages/Register.scala
test/selenium/pages/ThankYou.scala
test/selenium/util/Browser.scala
test/selenium/util/Config.scala
test/selenium/util/Dependencies.scala
test/selenium/util/Driver.scala
test/selenium/util/TestUser.scala

On membership/subscriptions/contributions frontend, we run some end-to-end browser-driven tests after every deployment. These run against production servers to confirm that the most critical flows have not been regressed by new changes.
This approach has many benefits, and therefore we would like to replicate this setup on support-frontend, at least in the short term. That said, having these type of tests introduces another maintenance burden, so all developers working on this project should be happy with this before we merge this PR. 
As for the PR itself - it's already getting bigger than I'd like, so I would like to get this code in as a first step. It adds the Selenium boilerplate and a single test. It means any developer in the team should be able to run these browser driven tests …

Add first browser-driven test

---

assets/components/contribAmounts/contribAmounts.jsx
assets/components/radioToggle/radioToggle.jsx
assets/helpers/internationalisation/country.js
assets/helpers/isoCountry.js
assets/helpers/user/userActions.js
assets/helpers/user/userReducer.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUS.jsx
assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/contributions-landing/reducers/reducers.js
assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/oneoff-contributions/oneoffContributions.jsx
conf/routes
public/robots.txt
webpack.config.js

We're going to have to accept US dollars for an up-coming test. Here, we're beginning to make use of the support code that came along in the `dollars` branch, from the UI's perspective.
Specifically, we're going to set the `isoCountry` page state property to `US` for the US contributions page, which will use existing shared components that are themselves able to change their appearance to confirm to US-centric expectations. To this end, we also set `isoCountry` to `GB` for the UK contribution page to ensure the same components work for the UK audience.
We'll expose the ~currency~ `isoCountry` value as a parameter to pages downstream from the landing page (primarily checkouts), and they can perform their own UI adaptations as a result.
Some of this will look _remarkably_ similar to the …

Initial application of US contribution page

---

assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx

For Q2 Test 2 we were going to run an AB test on the contributions landing page as described in #143 and #147. This test would hide monthly contributions for the variant and show it for the control. We subsequently changed the parameters of that test, and didn't use this code. It's possible we might want to run a similar test in the future, but this test code is currently just hanging around and is starting to get duplicated for other versions of this page (see #185). Therefore, this PR removes it.
[**Trello Card**](https://trello.com/c/Ij2K9Wsz/821-remove-old-test-2-source-code-from-support-frontend)
- Stopped using the `showMonthly` prop to hide and show content.
- Removed the CSS used to hide monthly contributions.

Purge Contributions Landing AB Test

---

.prout.json

We added a post-deployment test in https://github.com/guardian/support-frontend/pull/184, and then made it configurable, such that it could be run locally by developers, or by Travis (see https://github.com/guardian/support-frontend/pull/186).
I've tried triggering the tests in Travis using the API - [in order to replicate the behaviour of Prout](https://github.com/guardian/prout/blob/master/app/lib/travis/TravisApiClient.scala#L86) - and everything worked (after a bit of trial and error).
So now we can allow Prout to trigger the test automatically after every release!
Note that this will currently only run a single test - sign-up for monthly contributions with Stripe.
[**Trello Card**](https://trello.com/c/BwKkbrMA/455-post-deployment-tests-for-monthly-contributions-support-frontend)
* …

Configure Prout to run post-deployment tests

---

assets/pages/bundles-landing/helpers/subscriptionsLinks.js

Setup the logic for setting up the promo codes for test 4.
| Channel | Campaign Code |
|---------|---------------|
| **Engagement Banner** | gdnwb_copts_memco_sandc_support_baseline_support_banner  |
| **Epic**  | gdnwb_copts_memco_sandc_support_baseline_support_epic |
| **Liveblog** | gdnwb_copts_memco_sandc_support_baseline_support_liveblog |
| Channel | Promo Code |
|---------|---------------|
| **Digital** | DJ6CCJZLL
| **Paper + Digital**| NJ6CCSVMC|
| **Paper** | NJ6CCQLD4|
https://github.com/guardian/frontend/pull/17650

Added campaign codes for test 4

---

assets/pages/oneoff-contributions/components/formFields.jsx

This isn't required for one-off, and we want to have as few fields as possible on the checkouts. However, the rest of the code managing US state is used for recurring contributions as of #189, so this PR just modifies the component that displays it for the one-off checkout.
[**Trello Card**](https://trello.com/c/c175orpo/827-remove-state-for-one-off-contributions)
- Removed state for one-off contributions form fields.
**Before (US):**
**After (US):**

Remove State For One-Off Contributions

---

app/controllers/MonthlyContributions.scala
app/services/stepfunctions/MonthlyContributionsClient.scala
app/services/stepfunctions/StateWrapper.scala
assets/components/selectInput/selectInput.jsx
assets/components/selectInput/selectInput.scss
assets/components/textInput/textInput.scss
assets/helpers/internationalisation/country.js
assets/helpers/internationalisation/legal.js
assets/pages/monthly-contributions/components/formFields.jsx
assets/pages/monthly-contributions/helpers/ajax.js
assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/monthlyContributions.scss
assets/stylesheets/main.scss
build.sbt

A requirement for having recurring contributions in the US is the addition of a state field. This PR adds the server-side code needed to send this field through to support-workers, and the client-side work that adds this field to the US version of the recurring contributions checkout. It also flips the terms and conditions back and forth between the US and UK.
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/Rqfs2OJi/798-test-3-add-support-for-us-states)
- Added `state` to the user fields sent through to Zuora.
- Updated the `support-models` library and fixed bugs caused by new version.
- Added a `selectInput` shared component for the state dropdown.
- Dropped redundant CSS rule from `textInput`.
- Added list of US states to the country helper and refactored to use the export …

Add State for US

---

assets/pages/oneoff-contributions/oneoffContributions.jsx

The contributions terms for the US are different and sit on a different URL. This changes the link on the one-off contributions checkout page based upon country.
[**Trello Card**](https://trello.com/c/Y3N3ePg2/824-flip-flop-one-off-terms-for-us)
- Flipped contributions terms link based on country.

Flip-Flop One-Off Terms For US

---

assets/pages/monthly-contributions/monthlyContributions.jsx
assets/pages/monthly-contributions/monthlyContributions.scss
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/oneoffContributions.scss

The legal copy on the checkouts was too wide. This narrows it and changes the background to white. It also reworks the use of `gu-content-filler` as introduced in #133.
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/4CBfzocI/763-contributions-legal-copy)
- Narrowed the contributions legal copy.
- Made the legal copy background white.
- Properly applied `gu-content-filler`.
**One-Off Desktop:**
**One-Off Tablet:**
**One-Off Mobile:**
**Recurring Desktop:**
**Recurring Tablet:**
**Recurring Mobile:**

Checkout Legal Copy Design Tweaks

---

app/controllers/Application.scala
app/views/contributionsLanding.scala.html
app/wiring/Controllers.scala
assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/components/paymentMethods/paymentMethods.jsx
assets/helpers/internationalisation/country.js
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckout.js
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckoutActions.js
assets/pages/contributions-landing/actions/contributionsLandingActions.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx
assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/contributions-landing/reducers/reducers.js
assets/pages/oneoff-contributions/components/paymentMethodsContainer.jsx
conf/routes
test/controllers/ApplicationTest.scala

Primarily for the up-coming US test (test 3) and for one-off contributions only. PayPal is popular with US readers, and eliminating an unnecessary trip to a checkout page will likely help boost conversions.
Trello: [**re-jig-payment-ctas-on-contributions-landing-page**](https://trello.com/c/WFb6grJY/816-re-jig-payment-ctas-on-contributions-landing-page)
cc @Ap0c @svillafe

Re-jig payment CTAs on contribution landing page

---

assets/helpers/utilities.js
assets/pages/contributions-landing/actions/contributionsLandingActions.js
assets/pages/contributions-landing/components/contributionsBundleContent.jsx
assets/pages/contributions-landing/components/contributionsContext.jsx
assets/pages/contributions-landing/components/contributionsContextIntro.jsx
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx
assets/pages/contributions-landing/helpers/context.js
assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/contributions-landing/reducers/reducers.js

The Epic has some context (paragraphs of copy) for why you might want to support the guardian/make a contribution. The engagement banner doesn't, so contributions use an alternate landing page that includes this copy. We're going to do the same. It could be argued that we should show this page for header traffic as well, as there's no context there either.
I've done this by adding a query parameter to the URL called `context`, which can be either true or false (or missing, 3VL all the way!). This will trigger the context version of the page with extra copy (see screenshots below). This applies to both the UK and US versions of the page.
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/d0jVHDB1/815-engagement-banner-header-version-of-contributions-landing-page)
- Added a utility …

Add Context Version Of Contributions Landing

---

assets/helpers/internationalisation/country.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx

**DO NOT MERGE**
When we go live in the US we want to be able to properly detect country ('GB' *or* 'US'), rather than hardcoding everything to 'GB' as we're doing at the moment. This is the last thing to change when we're ready to go live with Test 3.
This also switches to recording the country in a cookie, for use on the checkout pages, rather than passing it through as a query param.
[**Trello Card**](https://trello.com/c/jyV8afjI/856-turn-off-gb-default)
- Removed hard-coding of 'GB' in country detection.
- Created new `setCountry` helper to set the country cookie.
- Stopped passing country through to checkouts as query param.
- Applied country cookie to contributions landing and bundles landing pages.

Stop Hardcoding 'GB' For Country Detection

---

README.md
docs/development.md

I added end-to-end tests (and some new command-aliases) in https://github.com/guardian/support-frontend/pull/184.
This PR documents the new tests and the commands required to run them.
[**Trello Card**](https://trello.com/c/BwKkbrMA/455-post-deployment-tests-for-monthly-contributions-support-frontend)
* Add documentation
* Update links
N/A

Add testing documentation to development guide

---

assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/components/paymentMethods/paymentMethods.jsx
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckout.js
assets/helpers/refpvid.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx
assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/contributions-landing/reducers/reducers.js
assets/pages/oneoff-contributions/components/paymentMethodsContainer.jsx
assets/pages/oneoff-contributions/helpers/ajax.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/reducers/reducers.js

Contributions use this for their data analysis, and we already pass it through from dotcom to our landing pages (as a query parameter). This PR passes this through from the contributions landing page to the checkout pages. It also updates the POST requests to contributions for Stripe and PayPal, to include the REFPVID if it is present.
[**Trello Card**](https://trello.com/c/NmghNCjy/681-pass-through-refpvid-to-contributions-from-bundles-landing-page)
- Created a shared reducer for REFPVID.
- Captured REFPVID from a query param on both versions of the contributions landing page.
- Sent it through in the PayPal POST request.
- Sent it through in the Stripe POST request.

Pass Through REFPVID

---

assets/pages/oneoff-contributions/components/formFields.jsx

The country was being pulled from an incorrect location in the Redux state. This led to the checkout displaying 'Postcode' for US instead of Zip code.
- Added the correct location to the state mapping.
**Before:**
**After:**

Fix Country Being Passed Through Incorrectly To One-Off Checkout

---

app/controllers/TestUsersManagement.scala
app/views/testUsers.scala.html

Cookie needs to NOT be http only so that JS can send to contribute.theguardian.com

Fix test_username cookie

---

cloud-formation/cfn.yaml

So that in-browser payment failure notification works

Allow instance to access state machine execution history

---

assets/components/selectInput/selectInput.jsx
assets/pages/monthly-contributions/components/formFields.jsx
test/selenium/ContributorSpec.scala
test/selenium/conf/selenium-test.conf
test/selenium/pages/ContributionsLanding.scala
test/selenium/pages/MonthlyContribution.scala
test/selenium/util/Browser.scala
test/selenium/util/Config.scala

We don't currently have an automated test which signs up for a monthly contribution with PayPal. I consider this to be a critical flow, so this PR adds the missing test. 
I've configured the test to run against the US form to get coverage of that too.
[**Trello Card**](https://trello.com/c/BwKkbrMA/455-post-deployment-tests-for-monthly-contributions-support-frontend)
* Adds id to state-dropdown in order to make it easier to test this component with Selenium.
* Adds new methods required for PayPal test
* Adds PayPal scenario
* Configures Stripe test to run against the UK flow, and the PayPal test to run against the US flow, for better coverage.
_Note: to run these tests locally you will need to grab the latest support-frontend.private.conf, which includes test credentials for the PayPal …

Add PayPal test for monthly contributions

---

app/controllers/Application.scala
app/views/contributionsRedirect.scala.html
conf/routes

Payment failure sends uk and us to /monthly-contributions which doesn’t
exist anymore. This reinstates it, redirecting US and UK contributors
to the correct place.  We should replace this workaround with separate
failure emails for UK and US so that we don’t need to rely on
geolocation

Workaround for payment failure email

---

app/wiring/AppComponents.scala

This line was accidentally dropped during a merge, so we haven't been sending our errors to Sentry. The sentry.dsn also needs to be defined in the private conf file before this will start working.
* Configure Sentry logging if 'sentry.dsn' is defined in the private conf file.
N/A

Re-configure Sentry

---

app/controllers/TestUsersManagement.scala
app/wiring/Controllers.scala

Avoid manual step of creating cookie on contribute.theguardian.com by changing support.theguardian.com cookie scope to .theguardian.com
* Add cookie domain so that test_user is visible on contribute.theguardian.com

Improving paypal testing developer experience

---

assets/helpers/internationalisation/country.js
assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
assets/helpers/page/__tests__/pageTest.js
assets/helpers/page/page.js
assets/helpers/page/pageActions.js
assets/helpers/tracking/guTracking.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/subscriptionsLinks.js
assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap
assets/pages/bundles-landing/reducers/__tests__/reducersTest.js
assets/pages/bundles-landing/reducers/reducers.js

With the rollout of Tests 2, 3 and 4 we've generated a lot of tech debt in how we handle page initialisation. We currently setup the store in various different ways on multiple pages:
- Hydrating from an object (probably wrong).
- Initial state using higher-order reducer (probably the correct option, but confusing to parse).
- Post-creation actions (reasonable, but semantically debatable if they're never going to change after first render).
This PR simplifies page setup by pulling it into a `page.js` shared helper. This module takes on the initialisation previously handled in `pageStartup`, and creates a 'common' reducer for handling state that is likely to exist in multiple pages. It also handles creation of the redux store.
The 'common' state includes tracking information such as …

Redux Setup Refactor - Part 1

---

assets/components/contribAmounts/contribAmounts.jsx
assets/components/radioToggle/radioToggle.jsx
assets/helpers/abtest.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx

Currently the annual payment option for regular contributions is hidden behind a query string parameter. This PR makes it available through a variant in the `annualContributions` ab test.
[**Trello Card**](https://trello.com/c/mxWzhDt2/882-update-support-frontend-to-allow-users-to-make-annual-regular-contributions)
* Introduce a new AB test `annualContributions` with 2 variants; control and variant. This test is currently inactive.
* Assign all visitors to the UK bundles landing page to a variant and track that variant in Ophan.
See: https://github.com/guardian/support-frontend/pull/211

Annual contributions ab test

---

assets/pages/bundles-landing/components/Bundles.jsx

It currently says 'from £22.06/month' which is weird. It should be £10.79 to match the lowest figure on https://subscribe.theguardian.com/collection/paper
Trello card: [**update-pricing-on-3-offer-landing-page**](https://trello.com/c/65dKaumX/869-update-pricing-on-3-offer-landing-page-to-provide-accurate-sensible-wording-pricing-of-subs)
Before:
After:

Change paper subs price to read 'from £10.79/month'

---

test/selenium/util/Driver.scala

The post-deployment tests are failing in Saucelabs. This is generated because Saucelabs updated its chrome to version 61 but it is not compatible with its chromedriver. This PR fixes the version to 60.

[fix-browser-version] Fix chrome version to 60

---

assets/pages/contributions-thankyou/monthlyContributionsPending.jsx
test/selenium/pages/RecurringContributionThankYou.scala

Currently, we are accepting as a valid execution only the ones which are process during the session. This is not always the case since there are executions that returns a pending status and we shouldn't flag this execution as errors since they aren't. This PR adds the logic to consider the pending thank you page in the recurring flow as a valid end step in a post-deploy test.
* Post deploy test.

Pending thank you page is a valid end step for a test

---

test/selenium/util/Config.scala

The current timeout for showing the *pending* thank you page is 30 seconds. Therefore, after at most (approximately) 33 seconds, we should be able to see the pending thank you page. Nevertheless, using a timeout of 40 seconds for waiting for this page to load when the test is running in Saucelabs, it seems it is not enough. Therefore, this PR increase the timeout to 45 seconds. After running, the tests against Sauelabs PROD, it seems a prudent amount of time to wait.

Increased the timeout for PostDeploy test

---

.flowconfig
assets/components/bundle/bundle.jsx
assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/doubleHeading/doubleHeading.jsx
assets/components/infoSection/infoSection.jsx
assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/components/textInput/textInput.jsx
assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
assets/helpers/stripeCheckout/stripeCheckout.js
package.json
yarn.lock

We were a few versions old, and lots of improvements have been made, particularly where handling React types is concerned (v0.53). The changelog is [here](https://github.com/facebook/flow/blob/master/Changelog.md). I came across what I think is a bug in some code I'm working on for the landing page, so I figured it was time to update.
**P.S.:** Thanks @gustavpursche for helping out when flow was being super-demanding around promise types 🐰.
- Update flow to `0.54.1` from `0.49.1`.
- Update our type definitions to meet the more rigorous current flow spec.
- Ignore preact in flow typing because there are some errors against the current version of flow.

Update Flow to v0.54.1

---

assets/pages/regular-contributions-existing/regularContributionsExisting.scss
assets/pages/regular-contributions/regularContributions.jsx

Couple of fixes following #229, sorts out a couple of style problems on the regular contributions and existing contributor pages.
- Updated some classnames and ids.
**Before - Checkout:**
**Before - Existing:**
**After - Checkout:**
**After - Existing:**

Monthly to Regular Fixes

---

assets/helpers/__tests__/abtestTest.js
assets/helpers/abtest.js
assets/helpers/page/page.js
assets/pages/contributions-landing/__tests__/__snapshots__/contributionsLandingReducersTest.js.snap
assets/pages/contributions-landing/__tests__/contributionsLandingReducersTest.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/components/contributionsBundleContent.jsx
assets/pages/contributions-landing/contributionsLandingReducers.js
assets/pages/regular-contributions/components/formFields.jsx

This PR adds the notion of a country to the ABTest framework.
[**Trello Card**](https://trello.com/c/l0fEidly/897-add-country-to-the-abtest-framework)
* Added country to the Audiences type.
```jsx
type Audiences = {
[IsoCountry]: {
offset: number,
size: number,
}
};
```
* Added tests for abTest helper.
* Removed the AbTestReducer since it was not being used since: https://github.com/guardian/support-frontend/pull/215
* Removed combine reducers from Contributions Landing page. (change chained from the point above)
N/A

Country for ABTest framework

---

assets/helpers/page/page.js
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/regular-contributions/regularContributions.jsx

Changes made in #215 involved moving creation of the Redux store to `page.js`, and introduced the concept of a common state, which was populated automatically. The process for manually overwriting individual elements of this common state, however, was not great. It made use of Redux's `preloadedState`, but this would overwrite the entire 'common' section of the state (as flagged [here](https://github.com/guardian/support-frontend/pull/223#discussion_r138906706)).
This PR alters the method for overwriting the common state, allowing for only a subset of the fields to be updated. Instead of using the Redux `preloadedState`, it uses Object.assign to overwrite individual `initialState` fields.
[**Trello Card**](https://trello.com/c/GOcdh5k9/912-do-a-better-job-of-overriding-common-state)
- …

Override Common State Fields Individually

---

assets/pages/paypal-error/payPalError.jsx
assets/pages/paypal-error/payPalError.scss

The PayPal return and cancel pages were created ages ago and not updated with the new flexbox-based sticky footer. Consequently they look a bit broken. This PR fixes this.
[**Trello Card**](https://trello.com/c/g5590PzH/911-tidy-up-wonky-paypal-error-pages)
- Made use of the filler class to push the short page down.
- Fixed the hover state of the CTA.
**Before**
**After**

Fix PayPal Pages CSS

---

assets/components/checkboxInput/checkboxInput.jsx
assets/components/checkboxInput/checkboxInput.scss
assets/helpers/user/userActions.js
assets/helpers/user/userReducer.js
assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/oneoff-contributions/helpers/ajax.js
assets/pages/oneoff-contributions/oneOffContributionsReducers.js
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/stylesheets/main.scss

We were not sending that flag. Now we are sending it.
[**Trello Card**](https://trello.com/c/3h9aGfck/872-permissions-parity-with-contributionstheguardiancom)
* Created checkbox component.
* Added GNMmarketing to user object.
* Sending mkt perms to contribute.

Sending GNM permissions to Contribute

---

webpack.config.js

We weren't minifying CSS before, now we are (only for PROD). Related docs [here](https://github.com/webpack-contrib/css-loader).
* `webpack.config.js`

Minifying CSS in PROD.

---

assets/pages/oneoff-contributions/helpers/ajax.js

For one-off contributions, for both Stripe and PayPal, we POST the information to contributions-frontend and allow it to handle the payment. In order to correctly keep track of users in various tests we should be passing INTCMP through as well. However, until this point we've only been passing this through for PayPal, which has affected the results of some AB tests (notably tests 3 and 4).
This PR fixes the problem by passing the INTCMP through for Stripe as well.
cc: @jranks123 
- Made `intcmp` a compulsory maybe type, instead of an optional string type.
- Included `intcmp` in the Stripe POST to contributions.

Pass INTCMP To Contributions For Stripe

---

assets/pages/bundles-landing/components/WaysOfSupport.jsx

The campaign code we pass through for the Patrons and Events links on the bundles landing page was being passed through as `undefined`. I think this probably happened in #215, when I refactored the redux store to use the common state. This PR switches to using that common state to look up the `intCmp`.
- Switched to using common state to look up `intCmp` in state-props mapping.

Fix Ways Of Support INTCMP

---

assets/pages/bundles-landing/components/Bundles.jsx

We are not possible to fulfil that promise.

Delete "a up to 10 devices" line

---

assets/helpers/user/__tests__/userActionsTest.js

This PR completes the refactor/adding tests started [here](https://github.com/guardian/support-frontend/pull/126#discussion_r127266482). Now the `user` helper has tests for all the components (reducer and actions).
* Added user actions tests.

Added user actions tests.

---

assets/helpers/url.js

Our `getQueryParameter` utility function currently lowercases everything in the querystring. This was implemented to handle the fact that the `INTCMP` param can turn up in different formats (lowercased as 'intcmp' for example). However, it's started to cause problems in cases where querystring values aren't necessarily lowercase, e.g. [here](https://github.com/guardian/support-frontend/pull/211#discussion_r137788368), and for the [new acquisition data](https://github.com/guardian/frontend/pull/17840).
This PR stops this behaviour, but tries to do as much as possible by falling back to checking for uppercase and lowercase versions of a parameter. However, we really shouldn't be using multiple formats of a given query parameter, we should standardise on, for example, `INTCMP`. As it is, it …

Stop Lowercasing Query Params

---

app/views/main.scala.html
assets/components/accessibility/accessibility.scss
assets/components/headers/simpleHeader/simpleHeader.jsx
assets/stylesheets/gu-sass/accessibility.scss
assets/stylesheets/main.scss

Accessibility tests highlighted some issues. Let's patch 'em up.
Normally, we'd have a trello card-to-PR ratio of 1:1 but these were so tiny that I rolled two into one. Sorry.
[**Card 1 (no language):**](https://trello.com/c/YGDAllz6/931-accessibility-specify-language-in-document)
[**Card 2 (no text in header link):**](https://trello.com/c/nFcYhOop/932-accessibility-the-guardian-header-link-contains-no-text)
If I've done this right, there will be no differences visually, but from the reporting site:
**Before**
**After**

Improve accessibility

---

assets/helpers/abtest.js
assets/helpers/storage.js
assets/helpers/tracking/googleTagManager.js

To extend the `storage` module in order to provide wrappers for `sessionStorage` in addition to `localStorage`. This avoids a [bug](https://bugs.webkit.org/show_bug.cgi?id=157010) that exists in older versions of webkit.
[**Trello Card**](https://trello.com/c/Z05AK8SU/942-provide-better-storage-module-to-wrap-calls-to-sessionstorage-and-localstorage)
- Updated `storage` module to wrap `sessionStorage`, allowing a check to see if it's available.
- Updated storage usages across the codebase to make use of this.
- Added flow checking to `googleTagManager`.

Better Storage Wrapping

---

assets/helpers/__tests__/utilitiesTest.js
assets/helpers/utilities.js

The utilities module didn't have full test coverage. Now it does. Also, I deleted a `titleCase` function that wasn't being used anywhere. In addition, believing I'd be able to use JavaScript's type system for `deserialiseJsonObject` was a fool's hope...
[**Trello Card**](https://trello.com/c/FjrpCO4i/943-add-tests-for-utilities)
- Added tests for:
+ `roundDp`
+ `generateClassName`
+ `clickSubstituteKeyPressHandler`
+ `parseBoolean`
+ `deserialiseJson`
- Removed unused `titleCase` function.
- Added `getMockedKeypress` helper to mock keypress events.
- Stopped checking for 'object' type in `deserialiseJsonObject`, renamed it to `deserialiseJson`.

Expand Utilities Tests

---

app/controllers/OneOffContributions.scala
app/controllers/RegularContributions.scala
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
assets/helpers/stripeCheckout/stripeCheckout.js
assets/helpers/stripeCheckout/stripeCheckoutActions.js
assets/helpers/stripeCheckout/stripeCheckoutReducer.js
assets/helpers/user/user.js
conf/routes

Kill testuser endpoint and mimic the behaviour of the paypal functionality to handle testusers for one-off stripe
[**Trello Card**](https://trello.com/c/13sOboZJ/928-stripe-payment-kill-testuser-endpoint-and-mimic-the-behaviour-of-the-paypal-functionality-to-handle-testusers)

Remove test endpoint for stripe

---

assets/components/displayName/displayName.jsx
assets/components/displayName/displayName.scss
assets/components/infoSection/infoSection.jsx
assets/components/signout/signout.jsx
assets/components/signout/signout.scss
assets/helpers/url.js
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributions.scss
assets/stylesheets/main.scss

To allow users to sign out on the regular contributions checkout, in case they are signed in with the wrong account.
Clicking 'sign out' sends you to the identity sign-up page, which returns you to the same checkout page once you've signed-up/signed-in.
[**Trello Card**](https://trello.com/c/8s9BzPmO/947-allow-people-to-sign-out)
cc: @elvisr
- Fixed a wonky IE10 workaround in `displayName`.
- Allowed passing React components into the heading part of `infoSection`.
- Added a signout component.
- Added a url helper function to retrieve the correct domain for the env (DEV, CODE, PROD).
- Added signout to the regular contributions checkout.
**Desktop:**
**Mobile:**

Allow Signout

---

assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx

The PayPal contributions button currently uses 'contribute' where it should use 'pay', and the casing is incorrect (it doesn't match its surroundings). This changes the default copy to say 'Pay with PayPal', and allows the copy to be overridden. It's overridden on the contributions landing page to say 'Contribute with PayPal'.
[**Trello Card**](https://trello.com/c/CAP2KK22/950-change-copy-on-paypal-contributions-button)
- Set default props on the PayPal button.
- Overrode button copy on contributions landing page.
**One-Off Checkout Page:**
**Contributions Landing Page:**

Change Copy On PayPal Button

---

app/services/stepfunctions/StateWrapper.scala
app/wiring/Services.scala
build.sbt

To support this PR https://github.com/guardian/support-workers/pull/62
"To make it easier to switch encryption on and off without a risk of support-frontend and support-workers getting out of sync, this PR moves the setting which determines whether a request is encrypted or not into the request state rather than the config setting.
This means that support-frontend is now the only place where we need to update the encryption setting and support-workers will handle whatever it is sent. This would also allow us to send a mix of encrypted and unencrypted requests if for instance we wanted to keep test user requests unencrypted"

Add the encryption parameter to the support workers request

---

assets/pages/bundles-landing/components/Bundles.jsx

If there is not INTCMP when the user clicks contribute from the landing page, a `'null'` is store in the session. Then that `'null'` is spread to the subs sites and the contributions tracking system. By avoiding to put `null` as a query param if there is no campaign code, we sort out this problem.

Remove null INTCMP

---

assets/pages/bundles-landing/components/Bundles.jsx

The new copy is more accurate.
- Changed the contributions bundle copy.
**Before:**
**After:**

Tweak Contributions Bundle Copy

---

assets/pages/bundles-landing/bundlesLanding.scss

I accidentally broke it in #269, applying a CSS rule to the contributions bundle that affected the new tagline *and* the error message. This updates the CSS to only touch the tagline.
- Applied CSS to only the tagline.
**Before:**
**After:**

Fixed Font On Contributions Error Message

---

assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckout.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/helpers/ajax.js

To correctly track, using the acquisition/contributions backend, the one-off contributions with PayPal.
The scala class in Contributions:
```
case class AuthRequest private (
countryGroup: CountryGroup,
amount: BigDecimal,
cmp: Option[String],
intCmp: Option[String],
refererPageviewId: Option[String],
refererUrl: Option[String],
ophanPageviewId: Option[String],
ophanBrowserId: Option[String],
ophanVisitId: Option[String],
supportRedirect: Option[Boolean],
componentId: Option[String],
componentType: Option[ComponentType],
source: Option[AcquisitionSource],
abTest: Option[AbTest], // Deprecated,
refererAbTest: Option[AbTest],
nativeAbTests: Option[Set[AbTest]]
)
```
[**Trello Card**](https://trello.com/c/59xhYpwY/960-adding-acquisition-tracking-for-one-off-with-paypal)

Acquisition tracking for one-off contributions with PayPal

---

app/controllers/Application.scala
conf/routes

So that links outside our control are more consistent with the /uk pattern already established

Add redirect from /us to /us/contribute

---

assets/pages/contributions-landing/contributionsLanding.scss

To make the style consistent with the bundle landing page.
|--------|-------|
| <img width="329" alt="picture 424" src="https://user-images.githubusercontent.com/825398/31710427-e91d8d0a-b3ec-11e7-8bb3-9758da28fe4b.png"> | <img width="324" alt="picture 423" src="https://user-images.githubusercontent.com/825398/31710405-d3926c44-b3ec-11e7-8511-c9ddd7d84ba0.png"> |

New font-family for the contribute bundle

---

assets/helpers/page/page.js
assets/helpers/tracking/acquisitions.js
assets/helpers/url.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/externalLinks.js
build.sbt

There are number of query params which are passed into the site by off platform marketing channels which allow us to measure their effectiveness, currently we are not passing these through to subscriptions if the user chooses that option.
This PR retains any incoming query params in the ReferrerAcquisitionData object and passes them on to subscriptions.
[**Trello Card**](https://trello.com/c/GQW0IYsC/1004-implement-off-platform-tracking-codes)
Before (the subs destination url does not include the incoming query params):
After (the subs destination url includes the incoming query params):

Pass incoming query params on to Subscriptions

---

public/robots.txt

To allow the search engine to find the US contribute page

Removing US contribute from robots.txt

---

assets/helpers/__tests__/abtestTest.js
assets/helpers/abtest.js
package.json
yarn.lock

This allows the randomness of test allocation between tests to be independent of each other which in theory should all us to run multiple a/b tests on the same audience segment

Add "independence" option for ab tests

---

app/controllers/RegularContributions.scala
app/services/MembersDataService.scala

Currently we have a timeout of 1 second. Since the Members Data API access Zuora this timeout is not enough. Therefore in this PR we are increasing the timeout to two seconds (enough for the 95% of the members data api requests) and we are also recovering in case of a timeout so we don't show an error to the end user.
https://sentry.io/the-guardian/support/issues/364543311/
* Increase members data api timeout.
* Recover in case of failed request.
N/a

Adding extra timeout and recovering request.

---

assets/helpers/page/page.js
assets/helpers/tracking/ga.js

There are two off-platform tracking params that we are currently not doing anything with. These need to be sent to GA in the same way that Membership and Subscriptions do.
[**Trello Card**](https://trello.com/c/GQW0IYsC/1004-implement-off-platform-tracking-codes)

Send off-platform campaign codes to GA

---

.babelrc

Been meaning to do this for ages, but now there's a specific reason in #277. Previously babel was handling our ES6 `import`s and `export`s. Now webpack handles them. This allows us to take advantage of tree shaking, as first introduced by [rollup](https://rollupjs.org/#tree-shaking) and made available since [webpack 2](https://webpack.js.org/guides/tree-shaking/).
The main reason for doing this? Smaller bundle sizes:
Page                   | Size Before | Size After | Saving
-----------------------|-------------|------------|-------
Regular Contributions  | 140 kB      | 132 kB     | 8 kB
One-off Contributions  | 136 kB      | 128 kB     | 8 kB
Bundles Landing        | 139 kB      | 132 kB     | 7 kB
Contributions Landing  | 135 kB      | 128 kB     | 7 kB
Thank You Pages        | 102 kB …

Webpack Tree Shaking

---

assets/pages/contributions-landing/contributionsLanding.scss

Couple of small CSS fixes here.
First, in Firefox, the 'from $5 a month' text wraps on the `desktop` and `leftCol` breakpoints, because the bundle is narrower and it seems to conflict with the payment logos. Adding a tiny bit of padding fixes this.
Second, switching between the two contribution types ('monthly' and 'one-off') causes the whole bundle to jump up and down, because the 'from $5 a month' text is dropped for one-off. Setting a fixed height for this element regardless of whether there's any text stops this from happening.
[**Trello Card**](https://trello.com/c/p3pg3MZz/1013-wrapping-on-contributions-landing-page)
- Added a tiny bit of padding when the bundle is narrow, to prevent text wrapping.
- Set a fixed height on the bundle subheading, to stop the bundle jumping around. …

Fix Contributions Landing Pricing Wrap And Jump

---

build.sbt
test/selenium/util/Driver.scala

The post-deployment tests are unstable, so I'm updating the relevant libraries and removing a line which hardcodes an older version of Chrome in the PROD config.
Note that I'm not sure exactly how much impact this will have, but it seems like a sensible place to start.
I've confirmed that these changes work with our SauceLabs config.
[**Trello Card**](https://trello.com/c/hMA6lSdY/927-sort-out-selenium-test-flakiness)
* Update Selenium library
* Update WebDriver library
* Undo hardcoding of Chrome version - see https://github.com/guardian/support-frontend/pull/225
Surely my luck is going to run out:

Update selenium-test libraries and allow for use of latest ChromeDriver

---

assets/helpers/url.js

There is a very specific version of IE11 on Windows 10 that doesn't support `window.location.origin` natively, and which isn't handled by polyfill.io. It's a [bug](https://connect.microsoft.com/IE/feedback/details/1763802/location-origin-is-undefined-in-ie-11-on-windows-10-but-works-on-windows-7) that was fixed in later versions.
This adds a polyfill for our usage, scope to a single function, so it should only get included when used (thanks tree-shaking) and shouldn't bloat every bundle.
This likely affects a tiny fraction of users, but I can't see a straightforward way of testing that it solves the problem, as getting access to a specific very old version of IE11 is tricky. Question is, is it worth merging this at all?
- Added inline polyfill for `window.location.origin`.

Polyfill window.location.origin

---

assets/helpers/page/page.js
assets/helpers/tracking/googleTagManager.js

To be able to track GTM's tags correctly. The problem that we are fixing here is the fact that sometimes we override the array defined by GTM. Now we are checking if it is not defined before and in that case, we populate the array instead of overriding.

Fixing the initialisation of GTM

---

app/actions/CustomActionBuilders.scala
app/actions/NoCacheAction.scala
app/actions/NoCacheActionBuilder.scala
app/controllers/Application.scala
app/utils/RequestCountry.scala
conf/routes

Our impending acquisition piece about our 750,000 supporters will contain a single link which needs to send people to the following sites depending on their location:
UK -> UK new proposition
US -> US new proposition
Everywhere else -> Become a supporter page
This PR adds this functionality, behind the path `/geo-redirect`
The action is a non-cached action, as to accurately get the geolocation from Fastly, we can't use a cached result. As this will only be from one article, and will only get any traffic for the next week or so, so this should be fine

Add route for 750,000 supporters campaign

---

app/controllers/SiteMap.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
conf/routes
public/robots.txt

Sitemaps are useful for search engines to know about the organization of a site. Search engine web crawlers like Googlebot read this file to more intelligently crawl your site.
Sitemap's protocol: https://www.sitemaps.org/protocol.html
This PR is inspired by @rtyley's PR in membership: https://github.com/guardian/membership-frontend/pull/1351
[**Trello Card**](https://trello.com/c/FiEiovzZ/974-add-sitemap)
* Added `/sitemap.xml`
```xml
 <urlset xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
      <loc>https://support.thegulocal.com/uk</loc>
<xhtml:link rel="alternate" hreflang="en-us"    href="https://support.thegulocal.com/us/contribute"/>
<xhtml:link rel="alternate" hreflang="en" href="https://support.thegulocal.com/uk"/>
  …
```

Adding a sitemap to improve SEO

---

app/controllers/Application.scala
conf/routes

According to webmaster tools, we are getting crawls errors because the robot is trying to access `/events/archive` and `events/:idOfEvent`.  Therefore, I looked through the codebase and I was not able to find the place where these links are being set up. Additionally, webtools says that source which links this URL are other events in support platform (we don't have events in support). Therefore in this PR I am setting a redirect from support events to membership events and avoid these eventual crawls errors.
[**Trello Card**](https://trello.com/c/p8dtuArF/975-investigate-crawl-errors-which-are-linking-events)
* Added two new routes.

Events redirect

---

assets/components/svg/svg.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/mothershipNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

This is the next instalment of the support landing page, following on from #299. It deals specifically with the hero image at the top of the page, as seen in the screenshots below.
- The 'contribute' section.
- Fixes for older browsers (IE10 and Safari 8).
- Links on the call-to-actions.
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/6wAnJ1bf/1031-support-landing-mothership)
- Added an SVG displaying yellow particles floating around.
- Added a new component for the mothership section.
- Styled it across the breakpoints.
A selection of breakpoints:
wide | desktop | phablet | mobileMedium
-----|---------|---------|----------------

Support Landing Page - Part 2 - Mothership

---

assets/pages/oneoff-contributions/helpers/ajax.js

cc @guardian/contributions 
See [#368](https://github.com/guardian/contributions-frontend/pull/368) in contributions-frontend.
There is no need to update the `/paypal/auth` endpoint in contributions as the `supportRedirect` field can be used to infer whether the request is coming from the support platform.

Include isSupport field in one-off contribution request.

---

assets/helpers/abtest.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx

To compare the performance of contributions in the US when either one-off or recurring is  selected as the default option.
* adds a new A/B test
* changes the logic to determine `contribType` in `ContributionsBundle`

Add US recurring vs one-off A/B test

---

assets/components/contribAmounts/contribAmounts.jsx
assets/components/radioToggle/radioToggle.jsx

I'm going to make use of this component for the landing page changes, and I thought it would be good to give it some TLC. I'm doing it in a separate PR because I would like to minimise the impact of changes to other parts of the site in the main Support Landing PRs.
This is a refactor to (hopefully) make it easier to read the code. I've also pulled the `showAnnual` prop out (it's a shared component, ideally it shouldn't know anything about contributions), and replaced it with `modifierClass`, pushing the `with-annual`/`without-annual` choice further up the component tree.
**Note:** It may be easier to just look at the file, rather than read the diff, in places.
- Refactored the component, pulling some of the code out into functions.
- Replaced `showAnnual` prop with `modifierClass`, …

Tidy Up Radio Toggle

---

.travis.yml
build.sbt
docs/development.md
test/selenium/ContributorSpec.scala
test/selenium/util/SeleniumTag.scala

So that the selenium tests run.  Include/exclude tags do not work quite the way we want to instead we're now running selenium tests with a separate test config.  To run selenium tests `sbt selenium:test`.  All tests starting with ‘selenium’ will be run.  To run the non selenium tests `sbt test`

Run selenium tests

---

docs/setup.md
package.json

To avoid this message in TeamCity:
` warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.`
* Updated `package.json`

Avoid using -- in package.json's scripts

---

test/selenium/util/Driver.scala

I can't run the tests locally, because without specifying a region, the current re-direct behaviour send me to membership.theguardian.com.
* Add region to Support URL so tests will run locally.

Fix selenium tests (locally)

---

assets/helpers/__tests__/abtestTest.js
assets/helpers/abtest.js
assets/helpers/abtestDefinitions.js
assets/helpers/abtests.js
assets/pages/bundles-landing/bundlesLanding.jsx
docs/development.md

This required a little reworking of some of the A/B test types, mainly
removing the hardcoded enum and instead using `$Keys<T>`
(https://flow.org/en/docs/types/utilities/) from the A/B
definition (which is now an object keyed by test ID rather than an
array).
The result of this is hopefully a simpler process for adding A/B tests:
just add them to abtests.js and they'll be fired to Ophan automatically.
There's no need to add the IDs as enum values anymore, as `TestId` 
is derived from the keys in the `tests` object. 
To simplify creating new tests and avoid a situation where Ophan impressions aren't registered because someone forgets to explicitly do that for their test.

Refactor abtest.js to automatically submit A/B impressions to Ophan

---

cloud-formation/cfn.yaml

To ensure that all the outgoing connections from our EC2 instances are under `https`
[**Trello Card**](https://trello.com/c/05jyLRpI/1015-check-that-all-outgoing-connections-from-support-frontend-and-membership-frontend-use-https-or-other-encrypted-connection)
* Add an egress policy to `cfn.yaml`

Restrict egress traffic to allow only https

---

assets/helpers/__tests__/abtestTest.js
assets/helpers/abtest.js
package.json
yarn.lock

To reduce the bundle size.
[**Trello Card**](https://trello.com/c/G5CyJpH3/1059-replace-the-sha-256-library-used-in-support-frontend-with-something-lighter-weight)

Use seeded random number instead of ha-256 for independent a/b

---

assets/components/ctaLink/ctaLink.jsx

To simplify our markup for the circles work.
- Stopped wrapping CtaLink in a div.
- Put the accessibility hint inside the `a` tag.

Stop Wrapping CtaLink In A Div

---

assets/components/ctaLink/ctaLink.jsx
assets/helpers/abtestDefinitions.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/externalLinks.js

This PR adds a new test to support frontend. 
People in the control, when they click the "Start free trial" option, go to the following page, as normal:
Those in the variant will skip this step and proceed directly to this page:
In order to track participants in the test, we will look at clicks on the button from people in either test variant. To be able to do this, I have added the `data-link-name` attribute to the button html, which means that clicks will be tracked through ophan. We can then look at the test participation of people who clicked on the button to get the true participation of the test. 

Add digipack flow optimisation test

---

assets/components/contribAmounts/contribAmounts.jsx
assets/components/contribAmounts/contribAmounts.scss
assets/components/numberInput/numberInput.jsx
assets/components/numberInput/numberInput.scss
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/contributions-landing/contributionsLanding.scss

To allow the number input component to have an overlay label, primarily to show currencies. This is best understood with pictures 🖼, please check out the screenshots below.
cc: @Amohkhan
- Wrapped the `NumberInput` component in a div, and added an optional span for the overlay.
- Added a `labelText` prop to `NumberInput`.
- Stopped showing the currency in the placeholder.
- Passed through currencies from the files where `NumberInput` is used.
- Updated a bunch of styles to make it look ok across browsers.
| | Before | After
-|-|-
Bundles Landing | ![bundlanding-before](https://user-images.githubusercontent.com/5131341/32561978-75fe540c-c4a5-11e7-8c60-4c20106b4e81.png) | ![bundlanding-after](https://user-images.githubusercontent.com/5131341/32561987-7cab758c-c4a5-11e7-872e-16fea1b57808.png) …

Currency On Number Input

---

assets/helpers/tracking/acquisitions.js
assets/pages/bundles-landing/helpers/externalLinks.js

To track the Just One Pound banner test.
This PR also clears up some old, unused promo codes

Add promo codes for just one banner test

---

assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx

Somewhere along the way, form validation on the one-off checkout was broken. It should prevent the user from opening the Stripe overlay if they've not entered their name and email address. However, currently it doesn't, which is bad because this information is needed by the contributions backend. The request actually fails if the email address is missing!
It looks like the prop that needs to be passed to `StripePopUpButton`, `canOpen`, has been named incorrectly in `oneOffContributionsPayment`. I've updated this and it looks like it's validating correctly again.
- Changed `isValid` to `canOpen`.

Fix Form Validation On One-Off Checkout With Stripe

---

assets/components/contribAmounts/contribAmounts.jsx
assets/helpers/contributions.js

For Circles we need to be able to re-use the contributions error messages. In the spirit of trying not to touch other parts of the site in the main Circles PRs, this is another side-PR. It pulls the error messages out into the `contributions` shared helper.
- Extract contributions error messages out into a function in the `contributions` helper.
- Applied the function in `contribAmounts`.

Shared Contributions Error Message

---

project/plugins.sbt

I am evaluating the snyk cli as an alternative way to manage our dependencies through snyk.
This enables more options such as testing dev dependencies for vulnerabilities.
To run the Snyk cli on sbt dependencies you need thethe sbt-dependency-graph plugin to be present in the project.

Add sbt dependency graph plugin so that we can run snyk cli

---

assets/pages/bundles-landing/bundlesLanding.scss

To fix overlapping with the PayPal button, on the bundles landing page, when there's a contribution error. The error messages when the user makes use of the 'other amount' field vary a bit in length, and line wrapping pushes the PayPal button down.
[**Trello Card**](https://trello.com/c/sEmVxXbu/1078-fix-paypal-button-with-long-error-message)
- Made the bundles a bit taller on desktop to leave room for the error message.
- Tweaked the PayPal button positioning across the breakpoints to put it in the right place.
- Tweaked the card CTA positioning to work with the new PayPal button.
| | Before | After
--|--------|-----
Desktop | ![paypal-broken](https://user-images.githubusercontent.com/5131341/32669969-31e1f062-c63a-11e7-9030-febe79049515.png) | …

Fix PayPal Error Message Overlap

---

.babelrc
package.json
yarn.lock

Because now `babel-preset-env` is prefered over `babel-preset-2015` et all. https://babeljs.io/env/
[**Trello Card**](https://trello.com/c/Ni39QrTf/1046-look-at-moving-from-babel-preset-es2015-to-babel-preset-env)

Upgrade to babel-preset-env

---

assets/helpers/page/page.js
assets/helpers/tracking/acquisitions.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/externalLinks.js

. Renames `ReferrerAcquisitionData` to `AcquisitionData`
. Adds a new attribute `abTests` to the `AcquisitionData` type. 
.When creating the initial state, we populate this new `abTests` attribute with a combination of the the referrer AB test (if one exists) and all the native AB tests
. When creating the links for subs, we no longer pass through the acquisitionsData parameter directly from the url. Rather, we read the data from the state, where it has already been parsed
. The subs links now have both `abTest` and `abTests` attributes within the `acquisitionData` attribute

Add abtests to subs links

---

assets/helpers/tracking/googleTagManager.js

Reverts guardian/support-frontend#360
It turns out that this wasn't needed after all, Krux can extract this information without an explicit data layer

Revert "Add two new fields to the data layer to help with Krux targeting"

---

assets/components/ctaLink/ctaLink.jsx
assets/components/trackedComponent/trackedComponent.jsx
assets/pages/contributions-thankyou/oneoffContributionsThankyou.jsx

This adds `acquisitionsData` parameter in the outbound link on the thank you page component.
Here is an example of the link
```
https://support.thegulocal.com/contribute/recurring?contributionValue=5&contribType=MONTHLY&currency=GBP&INTCMP=oneoff-thankyou-page-recurring-upsell&acquisitionData=%7B%22campaignCode%22%3A%22oneoff-thankyou-page-recurring-upsell%22%2C%22componentId%22%3A%22oneoff-thankyou-page-recurring-upsell%22%2C%22componentType%22%3A%22ACQUISITIONS_OTHER%22%2C%22source%22%3A%22GUARDIAN_WEB%22%7D
```
and in `json`
```
{
"campaignCode":"oneoff-thankyou-page-recurring-upsell",
"componentId":"oneoff-thankyou-page-recurring-upsell",
"componentType":"ACQUISITIONS_OTHER",
"source":"GUARDIAN_WEB"
}
```

Add referrer data to landing page upsell cta

---

assets/components/trackedComponent/trackedComponent.jsx

This fixes type collision in the current the master build.
https://teamcity-aws.gutools.co.uk/viewLog.html?buildId=99569&buildTypeId=memsub_Support_SupportFrontend&tab=buildLog
This was caused by conflicts between #369 and #365

Adding missed type

---

assets/pages/bundles-landing/support-landing-ab-test/components/contributeNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/readyNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/whySupportNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

Couple things with the links on the page that aren't part of the contribute or subscribe sections. We're removing the 'find out more' links because there's nowhere really for them to point to. Also, the 'see supporter options' internal link at the bottom of the page now jumps to the contribute section, rather than to the top.
[**Trello Card**](https://trello.com/c/VvfDFmtn/1091-support-landing-update-the-links)
cc: @Amohkhan
- Gave contribute section an `id` for the internal link to jump to, and updated that link.
- Removed the 'find out more' CtaCircles and their corresponding styles.
- Added some spacing where the 'find out more' links used to be.

Support Landing Page - Part 4 - Tweak Links

---

assets/pages/bundles-landing/helpers/externalLinks.js
assets/pages/bundles-landing/support-landing-ab-test/components/subscribeNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/subscriptionBundleNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/helpers/subscriptionFeatures.js
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

The subscribe section was only half-finished before, missing the correct copy and links etc. This brings it in line with the functionality of the subscribe bundles on the current landing page.
[**Trello Card**](https://trello.com/c/pADcFz7O/1093-support-landing-subscribe-tweaks)
cc: @Amohkhan
- Connected it to redux to retrieve all the information that needs to be passed through to the subs site in the URL.
- Updated the copy of the bundles to display lists of features, with ticks!
- Updated the CTA labels.
- Added the links on the CTAs, with the same functionality as the current bundles page, i.e. promo codes, acquisition data etc.
- Created a helper to manage the lists of subs bundle features.
- Added a background colour to differentiate from the contribute section in #366.
- Tweaked …

Support Landing Page - Part 5 - Subscribe Tweaks

---

assets/pages/bundles-landing/helpers/externalLinks.js

The query string parameter `acquisitionsData` should be `aquisitionData` in order for the subs site to read it correctly

Fix incorrectly named acquisitionsData

---

assets/components/errorMessage/errorMessage.scss
assets/components/svg/svg.jsx
assets/helpers/__tests__/contributionsTest.js
assets/helpers/contributions.js
assets/pages/bundles-landing/__tests__/__snapshots__/bundlesLandingReducersTest.js.snap
assets/pages/bundles-landing/__tests__/bundlesLandingReducersTest.js
assets/pages/bundles-landing/bundlesLandingActions.js
assets/pages/bundles-landing/bundlesLandingReducers.js
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/contributeNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/contributionSelectionNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/graveErrorNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/helpers/contributionAmounts.js
assets/pages/bundles-landing/support-landing-ab-test/helpers/contributionLinks.js
assets/pages/bundles-landing/support-landing-ab-test/helpers/contributionTypes.js
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

This is the next instalment of the support landing page, following on from #299 and #312. This time I'm adding the contribute section, the last major component to go in. It takes a lot of functionality from the existing contribute component in the current bundles landing page (actions, reducers etc.).
[**Trello Card**](https://trello.com/c/UNAXgpkS/1030-support-landing-contribute-bundle)
cc: @Amohkhan
- Fixed an incorrectly named svg (`svg-exclamation`).
- Added a new `cross` svg.
- Added spoken versions of the max and min contributions, for a11y.
- Switched the `contributions` helper to the new export format.
- Added new function for retrieving contribution types in camelCase.
- Created new piece of state on the bundles landing page for handling a PayPal error, because we have the PayPal …

Support Landing Page - Part 3 - Contribute

---

assets/pages/bundles-landing/bundlesLanding.scss

On the bundles landing page, the PayPal button arrow doesn't match the other CTA. This brings it in line.
- Tweaked the arrow svg size and position.
|**Before**| **After** |
|--------|-------|
| ![paypal-before](https://user-images.githubusercontent.com/5131341/32945273-ac0c0ba2-cb8a-11e7-88ea-212a8047f67e.png)     |      ![paypal-after](https://user-images.githubusercontent.com/5131341/32945285-b2c3afcc-cb8a-11e7-8c49-5a9856b70cae.png) |

Tweak PayPal Button Arrow Size

---

app/views/bundleLanding.scala.html
app/views/contributionsLanding.scala.html
app/views/main.scala.html
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
app/views/react.scala.html

To load the important scripts as soon as possible, currently supported in Chrome, Opera and Safari. ([preload spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content))
* Added preload tag for the main scripts
Page | Before | After |
|-----|--------|-------|
Bundle Landing Page|   <img width="1256" alt="picture 450" src="https://user-images.githubusercontent.com/825398/32946543-d93dcf2a-cb8f-11e7-898e-d8f7953cfb06.png">|    <img width="1243" alt="picture 452" src="https://user-images.githubusercontent.com/825398/32946504-b506d05c-cb8f-11e7-9d2b-51574538ef13.png">  |
Contribution Landing Page|  <img width="1255" alt="picture 451" src="https://user-images.githubusercontent.com/825398/32946561-f77dccc4-cb8f-11e7-861f-193a76c56eba.png">|  <img width="1242" alt="picture 453" …

Adding preload

---

assets/components/ctaCircle/ctaCircle.scss
assets/pages/bundles-landing/support-landing-ab-test/components/otherWaysCardNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/otherWaysNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/readyNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

In the world where we switch over to support entirely, we still need a route to those products on membership that we plan to keep: patrons and events. This adds a section to the bottom of the support landing page showing these products.
[**Trello Card**](https://trello.com/c/K2kWxYLG/1101-support-landing-other-ways)
cc: @Amohkhan
- Added an `OtherWays` component to show information about other ways of support.
- Added an `OtherWaysCard` component to show the individual cards in the other ways section.
- Styled the new component.
- Added `cursor: pointer` to the `CtaCircle` component.
**Desktop:**
**Tablet:**
**Mobile:**
**In The Page:**

Support Landing Page - Part 7 - Other Ways

---

assets/components/contribAmounts/contribAmounts.jsx
assets/helpers/abtestDefinitions.js
assets/helpers/amountsTest.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx

This PR is a combination of 2 tests which tests different suggested amounts for US and UK recurring contributions.
The UK has the following amount variants:
Control: 5, 10, 20
Lower: 2, 5, 10
Wildcard: 5, 7 20
The US has the following variants:
Control: 5, 10, 20
Lower: 2, 5, 10
Higher: 7, 15, 30
@guardian/contributions 
Screenshots:
Control UK
Lower UK:
Wildcard UK:
Control US:
Lower US:
Higher US:

UK and US Recurring amounts tests

---

app/controllers/Application.scala
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss
conf/routes
webpack.config.js

By including the entire circles page in the bundles landing page script, we've increased its size. However, as the test isn't running yet, we're essentially shipping a bunch of dead code to users. This PR pulls the support landing page (also known as 'circles') out into a separate bundle, and switches to it server-side using the same query param as before (`newDesigns=true`).
This has reduced the size of the bundles landing page javascript bundle by 18kB.
|| Before | After
-|-|-
Bundles Landing | 195kB | 177kB
Support Landing | N/A | 175kB
I have no idea whether this is the best solution as far as the Scala/Play code goes, so if anyone has a suggestion for a better way of doing it please let me know!
**Note:** This is not really 2000 lines changed! The CSS diff is messed up and the change …

Put Circles Script In A Different Bundle

---

assets/components/ctaLink/ctaLink.jsx
assets/helpers/abtestDefinitions.js
assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/components/Introduction.jsx
assets/pages/bundles-landing/helpers/externalLinks.js
assets/pages/bundles-landing/support-landing-ab-test/components/subscribeNewDesign.jsx

This PR removes 2 UK landing page tests. 
1) The digipack flow test (https://github.com/guardian/support-frontend/pull/349). This test tried cutting out the second step from the digipack flow. It didn't succeed
2) The header copy test (https://github.com/guardian/support-frontend/pull/362). It tried 2 variants, one that added some explainer copy to the header, and one that changed the copy headline to a line about the number of supporters we have. Both variants failed to beat the control significantly. 
It also removed a test definition for an `addAnnualContributions` test, which is not active.

remove digipack test and remove header copy test

---

assets/helpers/abTests/__tests__/abtestTest.js
assets/helpers/abTests/abtest.js
assets/helpers/abTests/abtestDefinitions.js

After https://github.com/guardian/support-frontend/pull/345 we split the `independence` field into two fields. `independent` and `seed`.
* Updated `abtests.js`
* Updated test definitions
N/A

Refactor ab test framework logic

---

assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/bundles-landing/helpers/blackFriday.js
assets/pages/bundles-landing/helpers/externalLinks.js

To provide new copy and promocodes for the 'Black Friday' promotion which runs from the 24th November to the 3rd December 2017
[**Trello Card**](https://trello.com/c/q2BGAVpY/1102-black-friday-promotions)
Normal page copy:
During the 'Black Friday' period:

New copy and promocodes for the 'Black Friday' promotion

---

app/services/stepfunctions/Client.scala
app/services/stepfunctions/RegularContributionsClient.scala
app/services/stepfunctions/StateWrapper.scala
build.sbt

The support-workers project now expects a RequestInfo object to be passed into new executions., this PR adds it.
[**Trello Card**](https://trello.com/c/woFAILTI/1090-make-it-easier-to-spot-failures-in-the-monthly-contributions-step-function-executions)
Depends on https://github.com/guardian/support-workers/pull/77

Send the new RequestInfo object to the step functions

---

assets/pages/contributions-landing/contributionsLanding.scss

Just noticed that some of the font colours on the contributions landing page are in true black rather than `neutral-1`.
cc: @Amohkhan
- Changed font colour from true black to `neutral-1`.
**Before:**
**After:**

Changed Font Colour From Black To neutral-1

---

assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/bundlesGBStructureTest.jsx

Adding the T&Cs to the contribute bundle, in part to solve the whitespace issue. This also moves the contribution toggles and CTAs back to the right. It also makes the bundle slightly taller to fit a longer version of the error message.
- Made the contribution amounts narrower again, so they fit into the right column.
- Added the terms and conditions to the contribution bundle in the variant.
- Made the bundle slightly taller to fit the long error message.
**Desktop:**
**Mobile:**

Structure Test - With T&Cs

---

assets/pages/bundles-landing/bundlesLanding.jsx
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/components/Bundles.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss

It's important that we're clear about the terms and conditions on pages where people are able to make payments. This tweaks a couple of the contribute bundles where the direct link to PayPal payment is available, and adds some additional copy to a footer.
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/DyC89q1D/1106-add-tcs-where-we-have-direct-paypal-button)
- Added a disclaimer to the footer on the bundles landing page.
- Added T&Cs to the contribute bundle on the bundles landing page.
- Added T&Cs to the contribute bundle on the contributions landing page.
**Bundles Landing - Monthly:**
**Bundles Landing - One-off:**
**US:**
**Bundles Landing - Footer:**

Add T&Cs To Pages With Payment Options

---

assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/contributions-landing/contributionsLanding.scss

On input elements, other browsers seem to inherit the placeholder colour from the main text colour. Safari doesn't, which causes a legibility problem (see screenshots below). This PR addresses that.
cc: @Amohkhan
- Fix the placeholder colour of the 'other amount' input on the bundles landing page.
- Fix the placeholder colour of the 'other amount' input on the contributions landing page.
**Before - Bundles Landing:**
**After - Bundles Landing:**
**Before - Contributions Landing:**
**After - Contributions Landing:**

Fix Placeholder Colour Weirdness In Safari

---

assets/helpers/contributions.js
assets/pages/bundles-landing/support-landing-ab-test/components/subscribeNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/subscriptionBundleNewDesign.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss

Tidying up the designs for this page, because it's become a little messy with some of the tweaks we've been making.
cc: @Amohkhan
- Shorted the error message for contributing too much, to stop it line-wrapping (note this will also change it on the existing bundles landing page).
- Tweaked colours and hover states on CTAs.
- Changed 'paper & digital' to 'paper + digital'.
- Stopped making the price on the subscription bundles vary in size.
- Made sure the subscription headings work across all breakpoints.
- Tweaked some of the borders to make them more consistent, at 1px.
- Tweaked the padding in the contribute and subscribe sections.
- Tweaked fonts and colours to make them more consistent …

Support Landing Page - Part 10 - Little Tweaks

---

assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/components/stripePopUpButton/stripePopUpButton.jsx
assets/helpers/page/page.js
assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
assets/helpers/tracking/googleTagManager.js

Partly to help debug discrepancies in the conversion numbers between the DataLake and GA and partly because it may be useful to be able to segment by payment method in GA.
[**Trello Card**](https://trello.com/c/LRUMUypi/1109-investigate-ga-tracking-issue)
* Store the payment method that a user chooses in session storage
* Populate the payment method to the data layer

Add the payment method to DataLayer object for tracking

---

app/views/contributionsLanding.scala.html

To fix a bug introduced in : https://github.com/guardian/support-frontend/pull/376
The js script was included twice for the contributions landing pages (UK and US), which cause a double execution of the init function and therefore a double tracking.

Deleting a double counting ophan.

---

assets/pages/bundles-landing/components/bundles.jsx
assets/pages/bundles-landing/components/stackedBundle.jsx

So that users know that they can contribute using PayPal.  NB - this bug was introduced before Garnett
**Before**
**After**

Button should say "or PayPal" for recurring contributions

---

.prout.json
prout/seen.md

Reverts guardian/support-frontend#416
This repo is public again, so we don't need this message (or the support-tests repo) any more.

Revert "Show a custom message when Prout sees new builds in production"

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/bundles-landing/bundlesLanding.jsx

https://github.com/guardian/support-frontend/pull/428 showed that the lower half of the page adds no value to the page for people hitting support.theguardian.com (in the UK, off the banner and epic). 
Therefore, we are going to default to the version without the lower half of the page. 
The page previously would have looked like this for UK Epic and Banner readers:
Now it will look like this:

Drop the lower half of the page for users from the banner

---

cloud-formation/cfn.yaml

I noticed that there was quite a long lag between a spike in 500s and us receiving an alert for this project. I think this is (at least partly) because of the number of evaluation periods being used. Currently support-frontend is pretty stable, so I think this alarm will be more useful if we make it more sensitive.
More info here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Statistic
> Not only can you specify the period over which the comparison is made, but you can also specify how many evaluation periods are used to arrive at a conclusion. For example, if you specify three evaluation periods, CloudWatch compares a window of three data points. CloudWatch only notifies you if the oldest data point is breaching and the others are breaching or …

Alert on high 500 rate sooner

---

assets/helpers/abTests/__tests__/abtestTest.js
assets/helpers/abTests/abtest.js
test/selenium/ContributorSpec.scala
test/selenium/util/Driver.scala
test/selenium/util/TestUser.scala

The post-deployment tests should be excluded from any AB tests running on support. The purpose of these tests is to check that core functionality is working after a deployment. They rely on a specific version of the flow, and are not designed to cope with multiple variants. We also don't want automated test runs to be counted in our results (although the numbers are going to be tiny, so I doubt it actually matters much).
Also, these tests always fail at the moment, because the default amounts have been changed (and they currently rely on an expected default in order to validate that we're charging the user the correct amount).
* Use existing '_post_deploy_user' cookie to exclude test runs from AB tests (and add a test for this new aspect of test allocation)
* Amend default amounts in test …

Exclude automated post-deployment test runs from AB tests

---

app/controllers/IdentityController.scala
app/controllers/OneOffContributions.scala
app/services/IdentityService.scala
app/views/thankYou.scala.html
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
assets/components/checkboxInput/checkboxInput.jsx
assets/components/checkboxInput/checkboxInput.scss
assets/helpers/routes.js
assets/helpers/user/user.js
assets/helpers/user/userActions.js
assets/pages/contributions-thankyou/__tests__/__snapshots__/contributionsThankYouReducersTest.js.snap
assets/pages/contributions-thankyou/__tests__/contributionsThankYouActionsTest.js
assets/pages/contributions-thankyou/__tests__/contributionsThankYouReducersTest.js
assets/pages/contributions-thankyou/components/marketingConsent.jsx
assets/pages/contributions-thankyou/components/questionsAndSocial.jsx
assets/pages/contributions-thankyou/components/thankYouIntroduction.jsx
assets/pages/contributions-thankyou/contributionsMarketingConfirm.jsx
assets/pages/contributions-thankyou/contributionsThankYouActions.js
assets/pages/contributions-thankyou/contributionsThankYouReducer.js
assets/pages/contributions-thankyou/contributionsThankyou.scss
assets/pages/contributions-thankyou/helpers/consent-api.js
assets/pages/contributions-thankyou/oneoffContributionsThankyou.jsx
assets/pages/contributions-thankyou/regularContributionsPending.jsx
assets/pages/contributions-thankyou/regularContributionsThankyou.jsx
assets/pages/oneoff-contributions/components/formFields.jsx
build.sbt
conf/routes
webpack.config.js

The same as https://github.com/guardian/support-frontend/pull/435, except we don't use the Identity Model import to get the string "supporter", as this was causing issues in PROD

Add new email consent for One Off Contributions[2]

---

app/config/Configuration.scala
app/controllers/DirectDebit.scala
app/models/DirectDebitData.scala
app/models/DirectDebitDetails.scala
app/services/GoCardlessService.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
app/wiring/Services.scala
assets/components/directDebit/__tests__/__snapshots__/directDebitReducerTest.js.snap
assets/components/directDebit/__tests__/directDebitActionsTest.js
assets/components/directDebit/__tests__/directDebitReducerTest.js
assets/components/directDebit/directDebitActions.js
assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
assets/components/directDebit/directDebitReducer.js
assets/components/directDebit/helpers/ajax.js
assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/helpers/routes.js
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/helpers/ajax.js
build.sbt
conf/routes
test/codecs/CirceDecodersTest.scala
test/controllers/RegularContributionsTest.scala

This PR adds the Direct Debit (phase 2) functionality to support frontend.
The different phases are:
1.- Added DirectDebit components to support-frontend (https://github.com/guardian/support-frontend/pull/448)
2.- Connect support-frontend with gocardless (https://github.com/guardian/support-frontend/pull/456)
3.- Integrate direct debit with step-functions/Zuora
4.- Implement a GoCardLess provider.
5.- Apply styles to support frontend.
6.- Build an A/B Test
* Creation and wiring of the DirectDebitController
* First approach of the GoCardLess Service (this will change in the 4th phase)
* Added formError to the state of the directDebit Component
* Added more action and reducers tests

Direct debit phase 2/6

---

assets/components/footer/footer.scss
assets/pages/bundles-landing/bundlesLanding.scss

To make the footer fit the garnett palette.
- Made the default footer background colour `garnett-neutral-1`.
- Stopped overriding the footer colour in the bundles landing page.

Garnett The Footer

---

app/controllers/Application.scala
assets/components/circlesIntroduction/circlesIntroduction.jsx
assets/components/circlesIntroduction/circlesIntroduction.scss
assets/components/ctaLink/ctaLink.jsx
assets/components/doubleHeading/doubleHeading.scss
assets/components/featureList/featureList.jsx
assets/components/featureList/featureList.scss
assets/components/pageSection/pageSection.jsx
assets/components/pageSection/pageSection.scss
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/components/threeSubscriptions/threeSubscriptions.scss
assets/components/whySupport/whySupport.jsx
assets/components/whySupport/whySupport.scss
assets/pages/bundles-landing/bundlesLanding.scss
assets/pages/bundles-landing/support-landing-ab-test/supportLandingOld.jsx
assets/pages/bundles-landing/support-landing-ab-test/supportLandingOld.scss
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/support-landing/supportLanding.jsx
assets/stylesheets/main.scss
conf/routes
webpack.config.js

Firstly, I would like to apologise for this PR. I suddenly realised that my changes were spiralling into a refactor, and that if I didn't merge some of them in soon things would get really out of hand. Therefore this isn't the most coherent PR, but I'll try to explain the changes below. There is a long-term plan!
cc: @Amohkhan
The Garnett Circles page is intended to be a modular redesign, so that we can iterate rapidly in multiple territories. Therefore I've created a completely new page (again!), which is called the 'Support Landing Page'. The interim (read: pre-Garnett) circles page I have renamed the 'Old' Support Landing Page. I would delete it, but I need it around to refer to while …

Rebuild The Circles Page - Part I

---

assets/components/otherProduct/otherProduct.jsx
assets/components/patronsEvents/patronsEvents.jsx
assets/components/patronsEvents/patronsEvents.scss
assets/helpers/theGrid.js
assets/pages/support-landing/supportLanding.jsx
assets/stylesheets/main.scss

Creates a component for the Patrons and Events section, and adds it to the Support Landing Page.
**Note:** I've opened this PR against the branch used in #459, so that the diff makes sense, but once that goes in I'll switch to PRing this against master.
[**Trello Card**](https://trello.com/c/Zanpiip9/1175-support-circles)
- Created an OtherProduct component, to show the cards for Patrons and Events.
- Created a PatronsEvents component, to drop into any page as a self-contained section.
- Added the Patrons image (the one used [on the Patrons page](https://membership.theguardian.com/patrons) from the Grid.
- Added the new PatronsEvents component to the Support Landing page.

Rebuild The Circles Page - Part II - Patrons And Events

---

assets/components/headers/simpleHeader/simpleHeader.scss
assets/stylesheets/gu-sass/helpers.scss

This brings the multilines to support-frontend, to bring it inline with dotcom. The technique I've applied here is a lightly modified version of the one used in frontend, which uses a [mixin](https://github.com/guardian/frontend/blob/a3a1559c870c5f7b16985b8513159f72d1db958a/static/src/stylesheets/_mixins.scss#L278) for the lines. This applies to the header across the site.
- Created a SASS mixin for the multilines.
- Flattened the header CSS (the diff is confusing, but I've just moved the nested styles out into their own rules).
- Added the multilines to the header.
**Before:**
**After:**
**US Landing Page:**

Garnett - The Header Lines

---

assets/components/patronsEvents/patronsEvents.scss
assets/components/readyToSupport/readyToSupport.jsx
assets/components/readyToSupport/readyToSupport.scss
assets/pages/support-landing/supportLanding.jsx
assets/stylesheets/main.scss

Creates a component for the "Ready To Support?" section, and adds it to the Support Landing Page.
[**Trello Card**](https://trello.com/c/Zanpiip9/1175-support-circles)
- Added a multiline to the top of the Patrons and Events section.
- Created a ReadyToSupport shared component.
- Dropped the component into the support landing page.
**Desktop:**
**Mobile:**

Rebuild The Circles Page - Part III - Ready To Support

---

app/codecs/CirceDecoders.scala
app/models/DirectDebitDetails.scala
app/services/stepfunctions/RegularContributionsClient.scala
assets/components/directDebit/directDebitActions.js
assets/components/directDebit/helpers/ajax.js
assets/pages/regular-contributions/helpers/ajax.js
build.sbt
test/codecs/CirceDecodersTest.scala

This PR adds the Direct Debit (phase 3) functionality to support frontend.
The different phases are:
1.- Added DirectDebit components to support-frontend (#448)
2.- Connect support-frontend with gocardless (#456)
3.- Integrate direct debit with step-functions/Zuora (#460, https://github.com/guardian/support-models/pull/29, https://github.com/guardian/support-models/pull/28 and https://github.com/guardian/support-workers/pull/91)
4.- Implement a GoCardLess provider.
5.- Apply styles to support frontend.
6.- Build an A/B Test
[**Trello Card**](https://trello.com/c/nOdfGQgS/254-direct-debit-as-a-payment-mechanism)

Direct debit phase 3/6

---

assets/pages/bundles-landing/components/stackedBundle.jsx
assets/pages/bundles-landing/helpers/externalLinks.js
assets/pages/bundles-landing/helpers/flashSale.js

Marketing want to run another 'Flash sale' to coincide with the launch of the tabloid format.
This PR contains the new dates, promo codes and copy for the sale.
I've also refactored the code slightly to make it easier to deal with sales where not all products are included.
[**Trello Card**](https://trello.com/c/FLWKXsML/1248-january-flash-sale-on-subs-support)

Add new dates and promo codes for the January flash sale

---

.eslintrc
assets/components/directDebit/directDebitActions.js
assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/directDebit/directDebitForm/directDebitForm.scss
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
assets/stylesheets/main.scss

To improve the UX and UI of the direct debit form. **This is not the final design of the form**. There should be a design/UX iteration before the final release. 
[**Trello Card**](https://trello.com/c/nOdfGQgS/254-direct-debit-as-a-payment-mechanism)
* Modify a11y label-for linting rule. Before it required both nesting and id link, now it only requires one of those.
* Come up with more meaningful codes for errors
* Added CSS✨ to improve the PopUp Form and the Direct debit form.

Added basic styling to Direct Debit and improved error handling

---

assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/errorMessage/errorMessage.jsx
assets/components/errorMessage/errorMessage.scss
assets/pages/bundles-landing/support-landing-ab-test/components/contributionSelectionNewDesign.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-thankyou/components/marketingConsent.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/regular-contributions/components/regularContributionsPayment.jsx

Every time we use the `ErrorMessage` component we write a bunch of boilerplate to check whether it should be shown or not. Why not let the component do that for you? This concept came out of our codebase best practices meeting the other day.
- Rewrote the `ErrorMessage` component to now show based upon whether there is a message. Also contains an additional prop that can be used to hide it (for example, if the message is static and you're deciding whether to show it based on another condition).
- Updated the following places to use the new format:
+ `ContributionSelection` component.
+ The one-off contributions bundle.
+ `MarketingConsent` component.
+ The one-off contribution checkout page.
+ The regular contribution checkout page.
- Tweaked the `ContributionSelection` …

Better Error Messages

---

assets/pages/regular-contributions/__tests__/ajaxTest.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/helpers/ajax.js

The `paymentFields` logic is quite fragile and payment errors would appear if we do not handle correctly the three cases. In this PR I am adding some unit tests to be sure that we always generate what the backend expects, depending on the payment method chosen. 
* Added a test file
* Exported the `getPaymentField` function so we are able to import it into the test file.
N/A

Adding test for recurring request

---

app/config/Configuration.scala
app/controllers/DirectDebit.scala
app/services/GoCardlessConfigProvider.scala
app/services/GoCardlessService.scala
app/services/GoCardlessServiceProvider.scala
app/wiring/Controllers.scala
app/wiring/Services.scala

To be able to hit go cardless sandbox environment when you use a test user in PROD.
We need to update config files before merging.
1.- Added DirectDebit components to support-frontend (#448)
2.- Connect support-frontend with gocardless (#456)
3.- Integrate direct debit with step-functions/Zuora (#460, https://github.com/guardian/support-models/pull/29, https://github.com/guardian/support-models/pull/28 and https://github.com/guardian/support-workers/pull/91)
4.- Implement a GoCardLess provider (#473)
5.- Apply styles to support frontend.
6.- Build an A/B Test

Direct debit phase 4/6 - Create a GoCardless service provider 

---

assets/components/bundle/bundle.jsx
assets/components/secure/secure.jsx
assets/pages/contributions-landing/contributionsLanding.scss

Our preference is for styles to exist in the stylesheet rather than inline on the JSX component. This was added [here](https://github.com/guardian/support-frontend/pull/424#discussion_r158332011) initially with regards to making sure style rules only apply to a specific instance of the component. However, in the case of the contributions landing page (where this `style` prop is used) the styles will only be scoped to that page, due to the convention we have for wrapping page styles in id tags.
That said, this will not always be the case, for example in pages where a component is used twice. The reason I've come across this is that I've hit an instance of exactly that in one of the circles designs. In these cases I think it would be good to apply a convention of passing through an optional …

Secure Component - Styles in Stylesheet

---

app/actions/CachedActionBuilder.scala
app/actions/CustomActionBuilders.scala
app/actions/HttpHeaders.scala
app/actions/NoCacheAction.scala
app/actions/NoCacheActionBuilder.scala
app/controllers/Application.scala
app/utils/BrowserCheck.scala
conf/routes

We're moving the unsupported browser intercept code to Fastly. From there it'll redirect trapped browsers to a specific page, and for that we need a route into the application.
We'll continue to log the user agents that are sent here to make sure the regex in Fastly is working as it should.
Once we've proved this is reliable, we can also record additional data such as the destination page etc.
[**Trello Card**](https://trello.com/c/ZGxOC5xb/1259-add-samsung-browser-trap-to-fastly)
Here's a bonus snippet from the logs too;
```2018-01-31 16:20:18,981 [application-akka.actor.default-dispatcher-501] WARN utils.BrowserCheck$ - Unsupported user agent: SamsungBrowser/2.0 but its really Justin pretending```

Add a distinct route for unsupported browsers

---

docs/development.md

Seeing as we are soon to move the one-off endpoints to the new API, it's probably not worth making the companion diagram for Stripe, but I think this is still worth uploading for now. 
The image is hosted on tinypic, if this is an issue let me know

Add paypal diagram to README

---

assets/components/headers/simpleHeader/simpleHeader.scss
assets/stylesheets/gu-sass/colours.scss

Dotcom doesn't put a multiline directly under the header, so we don't either. We use a single ruled line instead.
- Added the nav rule colour from dotcom.
- Swapped in a single rule for the multiline on the header.
**Before:**
**After:**

No Multiline On The Header

---

assets/helpers/__tests__/utilitiesTest.js
assets/helpers/utilities.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx

There are a couple of scenarios where users can currently attempt to make a recurring contribution, even though the attempt will never succeed:
1. User populates first and/or last name fields with a space.
2. User has no first or last name in identity, and therefore tries to proceed when these fields are undefined.
Currently, in the first case the user will always see the pending thank you page, but the Step Function execution will eventually time out.
In the second case, the user gets a generic and unhelpful error ("There was an error processing your payment. Please try again later"). This doesn't help them to fix the problem, and is likely to slightly lower our conversion rate.
[**Trello Card**](https://trello.com/c/nFKiCfTn/1226-users-can-attempt-to-sign-up-without-a-last-name-but-they- …

Tighten up validation on name fields

---

cloud-formation/cfn.yaml

To notify all the reader revenue devs when something goes wrong.
* `cfn.yaml`
N/A

Updated the alarms to point reader-revenue-dev sns

---

assets/pages/contributions-landing/__tests__/contributionsLandingReducersTest.js
assets/pages/contributions-landing/contributionsLandingAU.jsx
assets/pages/contributions-landing/contributionsLandingEU.jsx
assets/pages/contributions-landing/contributionsLandingReducers.js
assets/pages/contributions-landing/contributionsLandingUK.jsx
assets/pages/contributions-landing/contributionsLandingUS.jsx

The initial state of each contribution landing page is different. Therefore in this PR, I am creating a reducer factory which receives the bit of state that differs in each landing page.
This PR fixes the initial state bug in AU and EU.
* Create a reducer factor for contributions landing page.
|      | Before | After |
|------|--------|-------|
| 🇪🇺 |   ![eu-before](https://user-images.githubusercontent.com/825398/35987442-96e9983e-0cf3-11e8-98e3-0bf73f919156.png)     |  ![eu-after](https://user-images.githubusercontent.com/825398/35987488-b3954550-0cf3-11e8-9626-b6ea14b32df4.png)     |
| 🇦🇺 |       ![au-before](https://user-images.githubusercontent.com/825398/35987620-17a6f714-0cf4-11e8-9b38-08915a3f6943.png) |    ![au-after](https://user-images.githubusercontent.com/825398/35987629-1cced …

Initial state for AU EU

---

assets/pages/contributions-landing/components/contributionsBundle.jsx

In preparation for the implementation of the upsell test.
Changes:
- the Guardian => The Guardian
- `-` => `&ndash;`

content text tweaks before implementing upsell test

---

docs/development.md

To match the docs with the behaviour.
```
function randomNumber(mvtId: number, independent: boolean, seed: number): number {
if (!independent) {
return mvtId;
}
const rng = seedrandom(mvtId + seed);
return Math.abs(rng.int32());
}
```
* **independent**: Expresses whether the algorithm uses the mvtId (`independent: false`) or a random number (`independent: true`) to assign a user to a variant.   
* **seed**: It is used only when `independent` is equal to **`true`**. It is useful to sync different tests. In other words, the user will be in the same variant across different tests. For example, two tests with two 
variants (`control` and `variantA`) and the **same seed**, will cause that the user will be in `control` for both tests or `variantA` for both tests. Use this functionality …

Fixing AB test docs

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss

To try and increase the proportion of readers who sign-up to recurring contributions (vs one-off contributions).
__[Trello card](https://trello.com/c/gcc8Ipi4/68-us-landing-page-test)__
- change `the Guardian` to `The Guardian` in the default content text of GBP one-off contributions (house-keeping)
- implement the Upsell Recurring Contributions test
__control__
__benefits of both__
__shorter control__

Upsell recurring contributions test

---

assets/helpers/__tests__/urlTest.js
assets/helpers/url.js

There's a few places where we have to add multiple query params to URL, and it's a bit laborious. This adds a helper to handle that. There are also some tests to check that it works.
**Note:** Why aren't we using the `URL()` constructor? You have to supply it with an absolute URL unfortunately, which we don't always want.
- Created a helper for adding multiple query params to a URL.
- Added some corresponding tests.

Add Multiple Query Params To A URL

---

conf/logback.xml

This is a small improvement on https://github.com/guardian/support-frontend/pull/494
After that PR the application.log file started to contain both the original and sanitized versions of error messages (unnecessary duplication). This PR filters out the sanitized error messages.
* Add filter to file appender in logback.xml.

Exclude log messages intended for Sentry from log file on disk

---

docs/development.md

To clarify some of the changes made to introduce shared components that can be containerised. This documentation covers techniques introduced in #482, #501 and #506.
- Added a subsection to the 'Project Structure' section of the docs.

Document Containerisable Components

---

assets/helpers/legal.js

To show the correct year in the copyright notice. I thought this would be easier than doing a PR every time this changes (because we'll forget, as evidenced by the fact that it's February 2018 now). Technically this could show the wrong year if a user's clock is messed up. Thoughts?
cc @JustinPinner @CPKING
- Auto-update the copyright notice by year.

Show The Current Year In Copyright

---

assets/containerisableComponents/contributionSelection/__tests__/contributionSelectionReducerTest.js
assets/containerisableComponents/contributionSelection/contributionSelectionReducer.js

@CPKING discovered a subtle bug lurking in the custom amount selection (circles only).
When the user enters a custom amount, we validate it according to certain conditions: is it a valid number, and does it fall within the boundaries accepted for the given contribution type (e.g. maximum one-off amount, minimum monthly amount)? The conditions are different depending on whether one-off or monthly (or annual) is selected, as there are different maximum and minimum amounts.
If the user enters a custom amount for one contribution type, then the validation runs for that contributions type. However, if they then switch contribution types with the custom amount still selected, the validation doesn't re-run on the entered value, allowing them to continue with an invalid amount for the new type of …

Circles Rebuild - Part XIII - Custom Contribution Amount Validation Bug-fix

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/contributionPaymentCtas/contributionPaymentCtas.scss
assets/pages/contributions-landing-uk/contributionsLandingUK.jsx
assets/pages/support-landing/supportLanding.jsx

We need legal copy about contributions on the contributions landing page.
[**Trello Card**](https://trello.com/c/9NFMIjmb/1304-contribute-tcs)
- Added TermsPrivacy component to the payment CTAs component.
- Added disclaimer to the contributions landing and support landing footers.
- Styled the terms and privacy component.
**Desktop - Contributions Landing:**
**Mobile - Contributions Landing:**
**Desktop - Support Landing:**

Circles Rebuild - Part XII - Contribute Terms and Privacy

---

app/controllers/Application.scala

Based on discussion [here](https://github.com/guardian/support-frontend/pull/510#discussion_r169093621), this tidies up the query param selection for Circles.
[**Trello Card**](https://trello.com/c/bWdBL0R2/1315-refactor-circles-query-param)
- Added a method for selecting circles vs non-circles version of the page.
- Updated the various Application methods to use this helper.

Circles - Refactor The Query Param

---

assets/helpers/__tests__/contributionsTest.js
assets/helpers/contributions.js
assets/pages/bundles-landing/components/stackedBundle.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/contributeNewDesign.jsx
assets/pages/contributions-landing/components/contributionsBundle.jsx

To make the contributions landing CTAs consistent with those on the bundles landing page.
[**Trello Card**](https://trello.com/c/exBI9PIc/1316-ensure-consistency-across-cta-copy-for-all-support-pages)
cc @JustinPinner @ionamckendrick @CPKING 
- Changed 'Contribute with debit/credit card' to 'Contribute with card'.
- Added the amount to the CTA.
- Renamed `contribCamelCase` to `getContribKey`.
x | Monthly | One-Off
-|-|-
Before | ![cta-monthly-before](https://user-images.githubusercontent.com/5131341/36427816-1515b5ac-1646-11e8-879f-cb3a6fc23bbf.png) | ![cta-oneoff-before](https://user-images.githubusercontent.com/5131341/36427866-3305d6c8-1646-11e8-9999-a359ee4e9223.png)
After | ![cta-monthly-after](https://user-images.githubusercontent.com/5131341/36427884-404d7048-1646-11e8-9a9e-1eeda988 …

Make Payment CTAs Consistent

---

assets/containerisableComponents/contributionSelection/__tests__/contributionSelectionReducerTest.js
assets/containerisableComponents/contributionSelection/contributionSelectionReducer.js
assets/helpers/contributions.js

@CPKING has found another one.
When the user had entered an invalid custom amount, and then switched to a contribution type where it was a valid amount, the error still showed until they clicked the custom amount field, at which point it was re-parsed.
Rework the parsing mechanism to always store custom amounts if they are valid numbers, even if they aren't within the bounds of the given contribution type. This has the side-benefit of showing the entered amount in the payment button, even if it doesn't fit in the bounds, instead of resetting it to a default.
[**Trello Card**](https://trello.com/c/asGbLr0v/1314-bug-validation-on-us-page)
- Simplified the parsing of custom amounts by adding a new parsing function. The old one now just exists for the old contributions …

Circles Rebuild - Part XIV - Another Contribution Amount Validation Bug-fix

---

app/controllers/RegularContributions.scala

A user reported an issue and I was unable to debug it because our logging is currently too sparse. 
* Log when we fail to display the regular contributions form due to errors from Identity
* Clarify existing logging
* Downgrade errors from members-data-api to warn level
* Handle failed futures when calling members-data-api within _isMonthlyContributor_ instead of _displayForm_.

Add clearer logging to Regular Contributions controller

---

assets/components/headers/countrySwitcherHeader/countrySwitcherHeader.scss

To add padding to the country switcher box element.
* Up to tablet 10px.
* From tablet 20px.

Adding padding to the country switcher

---

assets/helpers/internationalisation/__tests__/countryGroupTest.js
assets/helpers/internationalisation/countryGroup.js

The `fromCountry` function in the `countryGroup` module isn't working as expected. This is causing the checkout pages to break when the query param is missing, as the next fallback to the cookie fails, and the default of 'GBPCountries' is set instead. This hides the 'state' field for the US, which in turn causes Zuora to complain.
Noticed this running Circles, as the Circles landing pages don't pass through the Country Group as a query param.
[**Trello Card**](https://trello.com/c/gIzgGn4H/1338-fix-fromcountry)
- Switched to using `Array.find`, because you can't return from `forEach`.
- Added tests.

Fix fromCountry

---

assets/components/contribute/contribute.jsx
assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/contributionPaymentCtas/contributionPaymentCtas.scss
assets/components/numberInput/numberInput.scss
assets/containerisableComponents/contributionSelection/contributionSelection.scss
assets/pages/contributions-landing-uk/contributionsLandingUK.jsx
assets/pages/contributions-landing-us/contributionsLandingUS.jsx
assets/pages/support-landing/supportLanding.jsx

To polish off all (hopefully!) the outstanding copy, design and UX issues.
[**Trello Card**](https://trello.com/c/GZlf4GYX/1308-copy-design-and-legal-review), and [**the other one**](https://trello.com/c/QfVTS2iW/1318-implement-uxd-tweaks-to-other-amount-on-circles-lp).
cc @JustinPinner @jonathan-nobbs
- Allowed custom copy on the contribute component, and updated the copy.
- Set up a disabled state for the payment CTAs when there's an error.
- Got rid of the unwanted red error glow on the number input (for all instances, not just Circles).
- Tidied up padding and margins on contribute component.
- Updated error styling on custom amount input.
**Desktop US Landing**
**Desktop UK Landing**
More to follow.
**Desktop One-off**
**Error States**
**Mobile**

Circles Rebuild - Part XVI - Copy and Design and UX Review

---

app/controllers/Application.scala
conf/routes

We want to AB test circles. The AB test itself will actually be set up (and the user will be bucketed) on dotcom. Therefore we need a way of showing the user Circles or not-Circles based upon whether they are in a test variant on dotcom.
To actually display the user the circles pages is a bit more complicated than just tweaking a couple of components client-side, because the pages themselves are entirely separate from the control versions (different js file). Up to now they've been viewable using a query param: `newDesigns`. However, since we're now using `INTCMP` to define the test, I've updated the server-side code to serve circles pages depending on whether they have a campaign code that says they should see Circles. This has the added benefit that it *just works* for the thank you …

Circles Rebuild - Part XV - AB Test

---

conf/riff-raff.yaml

This helps us to fulfil our GDPR obligations, as it means that any personal data in our log files, or secrets in our conf files are stored on an encrypted volume.
I've tested a deployment and a couple of sign-up journeys in CODE.
* Tell riff-raff to use an [encrypted copy of the xenial-membership AMI](https://amigo.gutools.co.uk/recipes/xenial-membership) (from our AWS account).

Use an encrypted AMI

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.scss
assets/components/dotcomCta/dotcomCta.scss
assets/components/svg/svg.jsx

There are a couple of bugs @michaelwmcnamara and I discovered doing cross-browser testing. This fixes them.
This is to do with the way an SVG's viewbox interacts with the viewport it's being displayed in. The circles background is meant to overflow the heading container, with any cropped parts hidden. This was working in Firefox but not in other browsers (Chrome, Safari).
The solution is to apply `slice` to the `preserveAspectRatio` `meetOrSlice` [parameter](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio), which controls this viewbox/viewport interaction. I'm not sure whether this is due to my misunderstanding of the spec, a bug in Firefox, or a bug in the other browsers. Anyway, it's now fixed:
[**Trello …

Circles Rebuild - Part XVII - Cross-Browser Fixes

---

assets/helpers/url.js

On some older browsers we've had a problem passing through the contribution amount to our checkout pages. For some reason, these browsers weren't picking up the amount from the query param in the URL, and were showing the default amount as a result. This was one of the issues dealt with in #465 for the Samsung Browser. It has subsequently shown up in older versions of Firefox.
This was an interesting one to track down. This screenshot explains the problem:
The `URLSearchParams` constructor doesn't handle querystrings that include the leading question mark `?`. This is a problem because that's what `window.location.search` returns, which is what we happen to be using in our `getQueryParameter` helper.
It seems like the spec wasn't specific as to what should happen here, and was …

Fix - Checkout Amount Querystring Bug

---

assets/components/contribAmounts/contribAmounts.jsx
assets/containerisableComponents/contributionSelection/helpers.js
assets/pages/bundles-landing/support-landing-ab-test/helpers/contributionAmounts.js
assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLandingEU.jsx

We need to update the monthly prices for EUR. As a side note, there is massive duplication around this logic, I created a card to address this problem [here](https://trello.com/c/1ClmvL8e/1348-delete-duplication-around-contributions-amounts). 
[**Trello Card**](https://trello.com/c/M1AkspCf/6-technical-work-launch-of-the-aus-and-eu-supporter-pages)
* Updated values of different pages.

Update EUR prices

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/contributions-landing/components/contributionsBundle.jsx

The test is done, the results were not conclusive but we decide to keep the `benefitsOfBoth` variant
[**Trello Card**](https://trello.com/c/L9zmjWqK/138-remove-finished-tests-on-support-frontend)
* Removed an old test

Removing upsellRecurringContributions test

---

assets/pages/contributions-landing/components/contributionsBundle.jsx
assets/pages/contributions-landing/contributionsLanding.scss

To have the correct copy set up for EUR  and AUS test.
[**Trello Card**](https://trello.com/c/M1AkspCf/6-technical-work-launch-of-the-aus-and-eu-supporter-pages)
* Updated some copy

Updated EUR and AUS copy

---

README.md
docs/development.md

Following on from the excellent work around browser support (#541), I wanted to make it clear that we **can** now use flexbox - with a few IE11-related caveats.
This is also an argument for making IE11 the priority to be dropped when we next do a review of browser support
@davidfurey @Ap0c @JustinPinner @rupertbates @jranks123 @Mullefa

Add note about flexbox to readme

---

docs/development.md

Redux recently updated their docs and broke all the links 😕. This fixes them.
cc @JustinPinner

Fix Redux Docs Links

---

assets/pages/bundles-landing/components/countrySwitcherHeaderContainer.jsx
assets/pages/contributions-landing/components/countrySwitcherHeaderContainer.jsx

To add EUR  to the contributions EU country switcher.
[**Trello Card**](https://trello.com/c/M1AkspCf/6-technical-work-launch-of-the-aus-and-eu-supporter-pages)
* Eu contributions page

Adding EURCountries to the country switcher

---

docs/supported-browsers.md
package.json
yarn.lock

Upgrading `autoprefixer` to version 8. Since version 8 autoprefixier uses browserslist, a tool already used by preset-env. The [suggested way of specifying](https://github.com/ai/browserslist#queries) which browser a project supports for browserslits is stating that in `package.json`.  Our current coverage is [here](https://goo.gl/KnaeBn)
[**Trello Card**](https://trello.com/c/HDwP2FhE/1350-setup-correctly-autoprefixier)
* Upgrade autoprefixier
* Introduced browserslist's browsers
* Added a second category of supported browsers
| Page                     | Screen capture |
|--------------------------|----------------|
| Bundles Landing          |   ![picture 582](https://user-images.githubusercontent.com/825398/37032753-808461c6-213b-11e8-90ca-7c85c7f70c46.png)  |
| US Contributions …

Upgrade autoprefixer to version 8 and update supported browser list

---

assets/helpers/abTests/abtestDefinitions.js

The test was successful in that it had no negative impact on conversion. So we are switching it off until we are ready for a 100% rollout.

Switch the DD test off

---

assets/pages/contributions-landing/components/contributionsBundleContent.jsx
assets/pages/contributions-landing/components/contributionsIntroduction.jsx

The Australian landing page should mention Australia.
* contributions landing

Add aus modifications

---

.eslintrc
assets/helpers/internationalisation/__tests__/countryGroupTest.js
assets/helpers/internationalisation/__tests__/countryTest.js
assets/helpers/internationalisation/countryGroup.js
jestEnvironment.js
package.json

To be able to test the entire logic of CountryGroup and Country helpers.
* Introduced a jest environment to expose `jsdom` to the global environment and allow us to change window properties.
* Added a complete set of tests for the `countryGroup` helper.
* Added a complete set of tests for the `country` helper.
* Stop exporting an internal method.

Refactor internationalisation tests

---

app/controllers/SiteMap.scala
test/controllers/SiteMapTest.scala

We recently started getting 500s from the sitemap endpoint.
The `SiteMap` controller uses reverse-routing to lookup the US landing page, and the routes changed for this page in #510. Previously there was a generic `Application.contributionsLanding` method, which was called with the id and JavaScript bundle for each regionalised landing page. However, the changes made in the above PR switched to using a more specific `Application.contributionsLandingUS` method, which no longer requires these parameters passed through. This resulted in a match error in the auto-generated `ReverseRoutes` file, as `SiteMap` was still using the old controller method for the US.
Switch the `SiteMap` controller across to using the new US route. I've also added a test to catch any errors thrown from the `sitemap` …

Fix The Sitemap

---

assets/pages/bundles-landing/components/countrySwitcherHeaderContainer.jsx
assets/pages/contributions-landing/components/countrySwitcherHeaderContainer.jsx

To be able to switch countries from the `AUDcountries` landing page and to the `AUDcountries` landing page.
* Country switcher

Adding AUDCountries to the country group switcher

---

.babelrc

To only transform for the browsers we care about.
[**Trello Card**](https://trello.com/c/X4tr2Agj/1139-setup-correctly-babel-preset-env)
* `.babelrc`

 Specify target browsers in .babelrc

---

app/controllers/Application.scala
app/controllers/SiteMap.scala
conf/routes

To serve the contributions landing pages (US/UK) and the regular contributions thank you page with Circles as default.
[**Trello Card**](https://trello.com/c/Hb7b3hXR/1353-tbc-from-test-results-put-circles-live)
- Removed the circles check from the regular thank you page.
- Deleted the custom controller methods for the US and UK contributions landing pages, they're now back to using the `contributionsLanding` method.
- Deleted an unused method for the regular contributions pending page (the route has used the thank you page for a while).
- Updated the site map to handle the US contributions landing (and added a helper method to reduce code duplication).
- Updated the routes file to match the controller method changes.

Circles As Default

---

assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/pages/bundles-landing/components/stackedBundle.jsx
assets/pages/bundles-landing/support-landing-ab-test/components/subscribeNewDesign.jsx

When we release the new Saturday only product, it will be the cheapest subscription option we offer so we need to update the 'from £X.XX' text on the landing pages.
[**Trello Card**](https://trello.com/c/NMU6RjLd/1325-update-pricing-copy-support)

Update minimum prices to take account of the new Saturday product - Do Not Merge

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/thankYouIntroduction/thankYouIntroduction.jsx
assets/helpers/contributions.js

The Circles pages are complete rebuilds, so don't contain the QA ids on key elements. This reintroduces those ids.
- Added a QA id to the contribute CTA.
- Added a QA id to the thank you page.
- Added a QA id to the one-off toggle.

Fix Post-Deploy Tests For Circles

---

assets/pages/contributions-landing-us/contributionsLandingUS.jsx

The world's smallest PR. the previous copy change had the phrase 'long-term' in it. This should be 'long term'.

Remove hyphen in long-term

---

cloud-formation/cfn.yaml

We should only open ports that are necessary.  Since we've moved from NTP to AWS time sync service this port can be clsoed.
> The Amazon Time Sync Service is available through NTP at the 169.254.169.123 IP address for any instance running in a VPC. Your instance does not require access to the internet, and you do not have to configure your security group rules or your network ACL rules to allow access. Use the following procedures to configure the Amazon Time Sync Service on your instance using the chrony client.
From https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

Remove UDP 123 for NTP

---

app/controllers/Application.scala
conf/routes

To create a `/contribute` geolocated endpoint to handle the contribute product pages.

Contribute endpoint

---

assets/helpers/contributions.js
assets/helpers/internationalisation/country.js
assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js
assets/pages/regular-contributions/components/formFields.jsx
conf/routes

To add an international version of our contributions landing page. 
* Added international contributions value.
* Modified country helper to check international case and set a default for that case (We need to define the default with data).
* Abstracted `FormField`'s method to be used either with EUR countries or international countries.

International contributions landing page

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/pages/bundles-landing/components/stackedBundle.jsx
assets/pages/contributions-landing-au/components/contributionsBundle.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx

We currently can't process paypal one-off contributions, so we remove the button. 
* Change 1
* Change 2

Disable paypal button

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/pages/bundles-landing/components/stackedBundle.jsx
assets/pages/contributions-landing-au/components/contributionsBundle.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx

Reverts guardian/support-frontend#581
This has to be merge when our one-off PayPal account is working again.

Revert "Disable paypal button"

---

webpack.dev.js

There appears to be an issue with the [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin), which results in CSS not being recompiled by webpack-dev-server (issue 23 on their GitHub page). This is a problem for local development, and the simplest solution that @rupertbates and I can find so far is to disable the cache for incremental builds. This slows down development, but at least it works again.
- Disable cache in dev.

Temporarily Disable Webpack Cache In Dev

---

assets/components/directDebit/directDebitForm/directDebitForm.scss
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
yarn.lock

The current Direct Debit payment details popup doesn't scale correctly on small devices, this PR fixes it.
[**Trello Card**](https://trello.com/c/TM07aW3k/1409-fix-scrolling-on-direct-debit-details-form-for-small-screens)
* Make the popup scrollable when the content is higher than the screen
* Adjust the width to match the smaller layout

Fix layout issues on small screen devices

---

assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js

We don't want to drive traffic to NZ page yet. Therefore we remove it from the country switcher.
* Removed from landing country-switcher

Removed NZ from country switcher.

---

app/actions/CustomActionBuilders.scala
app/controllers/OneOffContributions.scala
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
assets/components/displayName/displayName.jsx
assets/components/signout/signout.jsx
assets/helpers/user/__tests__/__snapshots__/userReducerTest.js.snap
assets/helpers/user/__tests__/userActionsTest.js
assets/helpers/user/user.js
assets/helpers/user/userActions.js
assets/helpers/user/userReducer.js
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/components/emailFormField.jsx
assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/oneoff-contributions/components/nameFormField.jsx
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap

We already have an email address for signed in users, and now that we are using identity accounts to link users to their contribution, we don't want users to supply a different email address if they are signed in. 
As part of this PR, I have added a `isSignedIn` property to the user state object. The reason for it is that the user state object gets populated via different sources, either from identity or from form fields. Therefore it makes using the existence of the user state object as a proxy for being signed in useless, which is problematic here where we want to hide the email field if a user is signed in. 
[NOTE: I have not yet made the tests pass]
@guardian/contributions 
Signed in users:
Non signed in users:

Don't ask signed in one-off contributors for their email

---

assets/helpers/internationalisation/country.js
assets/pages/regular-contributions/components/formFields.jsx

In guardian/support-internationalization the United Kingdom (a.k.a. `GBPCountries`) and Australia (a.k.a. `AUDCountries`) are two country groups containing more countries. Additionally, Zuora requires us to set up the country from which the user is making the transaction from. Since we are basing the logic for redirects in country groups, we need to bubble up this decision to the end user as we do in Europe and ROW cases.
Bear in mind the current logic will default the country via geoLocalization and if it can't be done it will set up the top contribution country for each country group. Therefore, the user should not interact with this component.
* Small refactor in the country.js helper.
* Adding country dropdown to `GBPCountries` and `AUDCountries` …

Dropdown for GBP countries

---

assets/pages/support-landing/components/countrySwitcherHeaderContainer.js
assets/pages/support-landing/supportLanding.jsx

The switch to the support landing page in #605 didn't bring the country switcher header with it. This reinstates it.
- Use the country switcher header in place of the simple header.
**Before**
**After**

Reinstate Country Switcher Header On Support Landing

---

assets/components/trackedComponent/trackedComponent.jsx
assets/helpers/page/page.js
assets/helpers/tracking/acquisitions.js
assets/helpers/url.js
assets/pages/oneoff-contributions/helpers/ajax.js
build.sbt

We want to track any query parameters associated with an acquisition so that we can track off platform properly. This PR adds the query parameters to acquisition model, and once it is merged, 
we will be sending query parameters from the client to the various backend routes. 

Add query parameter to the acquisition tracking

---

test/selenium/OneOffContributionsSpec.scala
test/selenium/RecurringContributionsSpec.scala
test/selenium/util/PayPalCheckout.scala

This change allows tests to work even if paypal splits the signup flow into 2 subsequent windows.
Currently end-to-end tests are failing on paypal payments due to a change in paypal sign in flow.
Instead of both username and password appearing on the same page, with the new flow, the user must enter username on first page then click "next" button to get to second form.
To make things really awkward, it seems to be inconsistent as to which type of payment sign-in window you are going to get, so the test needs to be able to handle both.
Changed the "fill in" function for paypal so that it fills in the email then checks to see if a next button is present. If it is, it clicks this and then waits for a login button to be present before entering password and logging in. If no next button is …

Tests can deal with new version of Paypal payment sign-in windows

---

app/controllers/IdentityController.scala
app/views/thankYou.scala.html

As of the 20th March, we had frequently been sending the string "undefined" as the users email address to the Identity Consent API.
The bug was caused in [this PR](https://github.com/guardian/support-frontend/pull/575/files), which changed the way we instantiated `window.guardain.email ` in the window. This change set this to be the string "undefined" if there was no email in the flash session, which only persists on the fiest request.
This meant that if the page reloaded, `window.guardian.email` would be set to undefined, meaning that the `user.email` field in the state would be set to "undefined". The tickbox was set up to show if the `user.email` in the state was a string - as "undefined" is indeed a string, it was still showing the box.
By mapping on the email when creating the window …

Fix issue where we were sending "undefined" as the email address to the identity Consent API

---

assets/components/bundle/bundle.jsx
assets/components/contribAmounts/contribAmounts.jsx
assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/ctaCircle/ctaCircle.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/doubleHeading/doubleHeading.jsx
assets/components/featureList/featureList.jsx
assets/components/numberInput/numberInput.jsx
assets/components/otherProduct/otherProduct.jsx
assets/components/pageSection/pageSection.jsx
assets/components/radioToggle/radioToggle.jsx
assets/components/secure/secure.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/containerisableComponents/contributionSelection/contributionSelection.jsx
assets/containerisableComponents/payPalContributionButton/payPalContributionButton.jsx
assets/helpers/__tests__/utilitiesTest.js
assets/helpers/utilities.js

In a discussion [here](https://github.com/guardian/support-frontend/pull/381#discussion_r152587640) we decided that it would be useful to have `generateClassName` take an array of modifiers. There are situations with [BEM](http://getbem.com/) where you may want multiple modifiers on an element. I've also used this opportunity to make the function name a bit more explicit.
The result is a new function, `classNameWithModifiers`, which takes an array of modifiers and applies them to a base `className`. Filters out `null`, `undefined` and `''` (empty string).
[**Trello Card**](https://trello.com/c/vo3iRyuE/1108-generateclassname-should-receive-an-array-of-modifiers)
**Note:** The `Boolean` function is used here to keep [Flow …

Refactor generateClassName

---

assets/components/paymentAmount/paymentAmount.scss
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributions.scss

To go live with Circles we've agreed to make some minor changes to the checkout pages, to keep the user journeys consistent. This PR updates the one-off and regular contribution checkouts with some Circles branding.
This is a first pass to get Circles live. We'd like to give these pages a more thorough treatment in the near future, to improve the design, sort out the CSS problems, and use some of the newer components that exist on the other Circles pages.
[**Trello Card**](https://trello.com/c/2vlrnKh1/1220-recurring-contribution-page) and [**this one**](https://trello.com/c/QcBiRp0w/1221-one-off-contribution-page).
cc @JustinPinner @CPKING
- Brought the regular contributions checkout page styling in-line with the other Circles pages.
- Brought the one-off contributions checkout page …

Circles On The Checkout

---

assets/pages/regular-contributions/__tests__/ajaxTest.js
assets/pages/regular-contributions/helpers/ajax.js
build.sbt

Currently when a user signs up with a credit card we send their Identity ID to Stripe when creating the Stripe customer record. For GDPR reasons we need to stop doing this.
I have tested this on code.
[**Trello Card**](https://trello.com/c/rNWSgTCY/1363-investigate-data-sent-to-stripe)

Don't send Identity ids in the Stripe payment details

---

assets/helpers/internationalisation/country.js
assets/pages/regular-contributions/components/formFields.jsx

We need to ask the reader in which country he/she is, in order to send this data to Zuora.
[**Trello Card**](https://trello.com/c/ybJt4X7R/265-add-a-country-dropdown-for-audcountries)
* Treating `AUDCountries` as a country group with several countries inside.
* Adding Country dropdown for AUD checkout

Adding AUDCountries dropdown in checkout page

---

app/controllers/Application.scala
assets/components/headers/countrySwitcherHeader/countrySwitcherHeaderContainer.js
assets/pages/contributions-landing-au/components/countrySwitcherHeaderContainer.jsx

To drive traffic to the Australian version of Support Frontend.
* Added redirects for the Australian case
* Added Australian to the country switcher

Driving traffic to Australian support frontend

---

assets/pages/contributions-landing/contributionsLanding.scss

The footer wasn't being pushed down in AUS, now it is.
- Add the `gu-content-filler` mixin to the AU contributions landing page.
**Before**
**After**

Push Footer Down In AU

---

assets/helpers/tracking/acquisitions.js

`contributionValue`, `contribType` and `currency` were sneaking into the query parameters field in the acquisition tracking. We don't want this, so this PR adds them to the list of exclusions

Add exclusions to query parameters

---

assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/directDebit/directDebitForm/directDebitForm.scss
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
assets/pages/regular-contributions/regularContributions.scss

To make the DD form more like the original design
[**Trello Card**](https://trello.com/c/mXudFgVh/1399-direct-debit-visual-tweaks)
**The DD details form**
**Align the buttons better**

DD form visual tweaks

---

.eslintrc
assets/components/directDebit/directDebitForm/directDebitGuarantee.jsx
assets/pages/regular-contributions/regularContributions.jsx

Because 100 characters really isn't very much and 
```javascript
const onClick = props.isDDGuaranteeOpen ? props.closeDDGuaranteeClicked : props.openDDGuaranteeClicked;
```
is easier to read than 
```javascript
let onClick = props.openDDGuaranteeClicked;
if(props.isDDGuaranteeOpen){
onClick = props.closeDDGuaranteeClicked;
}
```

Increase max line length to 120

---

assets/containerisableComponents/contributionSelection/__tests__/contributionSelectionReducerTest.js
assets/containerisableComponents/contributionSelection/contributionSelection.jsx
assets/containerisableComponents/contributionSelection/contributionSelectionReducer.js
assets/helpers/__tests__/contributionsTests.js
assets/helpers/checkouts.js
assets/helpers/contributions.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/regular-contributions/helpers/ajax.js
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributionsActions.js
assets/pages/regular-contributions/regularContributionsReducers.js

This PR covers two issues:
1. We have two very similar functions for parsing contributions:
- `parse`, which is used on the checkouts.
- `circlesParse`, which is used on the landing pages.
2. If a user arrives on the checkout without a contribution value set, they will be defaulted to an amount that may be higher than their original choice.
The proposed solutions are as follows:
1. Share parsing functionality between the checkouts and the landing pages. The result is actually still two functions, but they now do different things, rather than the same thing in different ways:
- `parseContribution`, which reads a contribution from a string and converts it to a monetary value.
- `validateContribution`, which checks that a contribution is within the accepted limits.
2. Get the checkouts to …

Review Checkout Defaults

---

assets/components/legal/termsPrivacy/termsPrivacy.jsx
assets/helpers/legal.js

New standards for GDPR require copy changes around the privacy policy.
[**Trello Card**](https://trello.com/c/BZ5HMG0g/1448-update-copy-for-tscs-and-privacy-policy)
* Copy change for privacy policy in the footer. 
Current privacy policy copy 
Footer with ⭐️ new ⭐️  privacy policy copy

Update privacy policy copy in the footer.

---

assets/components/footer/footer.jsx
assets/components/footer/footer.scss

New standards for GDPR require copy changes around the privacy policy.
https://github.com/guardian/support-frontend/pull/639 just updated the privacy policy copy for the confirmation page for a contribution but this needs to be updated in the footer as well. 
[**Trello Card**](https://trello.com/c/BZ5HMG0g/1448-update-copy-for-tscs-and-privacy-policy)
* Add required privacy policy copy to the footer. 
Old footer 
Footer with updated copy

Actually update privacy policy copy in the footer.

---

assets/pages/regular-contributions/components/regularContributionsPage.jsx

It's gone missing, possibly in #619. This puts it back.
- Put the footer back.
**Before**
**After**

Put The Footer Back - Regular Contributions Checkout

---

app/lib/CustomHttpErrorHandler.scala
assets/pages/error/components/errorPage.jsx
assets/pages/error/error.scss
assets/pages/error/error404.jsx
assets/pages/error/error500.jsx
assets/stylesheets/main.scss
webpack.common.js

To improve performance. Far less unused CSS downloaded and parsed.
_ | Before | After
-|-|-
Error Styles | 76.5 KiB | 14.8 KiB
Main Styles | 76.5 KiB | 71.7 KiB
[**Trello Card**](https://trello.com/c/uJ8T9Nmp/1493-split-error-page-css)
- Made `error.scss` the main stylesheet for the error pages.
- Deleted some content from `main.scss`.
- Renamed `errorContent` to `errorPage`.

Split Error Page CSS

---

cloud-formation/cfn.yaml

We were using an ACM certificate with a CODE contributions domain, which seemed like a rather strange/precarious position to be in. This PR updates the CFN to use a new certificate for each stage.
* Update to use new ACM certificates for PROD and CODE

Use sensible ACM certificates

---

app/controllers/OneOffContributions.scala
app/controllers/RegularContributions.scala
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/__tests__/oneoffContributionsActionsTest.js
assets/pages/oneoff-contributions/__tests__/oneoffContributionsReducersTest.js
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/oneOffContributionsReducers.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/oneoff-contributions/oneoffContributionsActions.js
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/__tests__/regularContributionsActionsTest.js
assets/pages/regular-contributions/__tests__/regularContributionsReducersTest.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributionsActions.js
assets/pages/regular-contributions/regularContributionsReducers.js
conf/routes
test/controllers/RegularContributionsTest.scala

This query param was originally used to hide the PayPal Express Checkout button for the apps, as this integration was buggy in webviews. However, the apps no longer direct traffic to our site in webviews, and the query param doesn't seem to work now in any case.
**Note:** This problem only occurred for the regular contributions checkout (where we use the Express Checkout integration). The query param was introduced for one-off in #163, to make the button visible only to developers while it was still under construction. We kept the logic around for a while because of a potential test, but it seems that test never happened and the logic has since been broken.
- Removed the query param logic from Play.
- Removed the state from the one-off and regular checkouts, and deleted …

Remove PayPal Button Query Param

---

app/views/oneOffContributions.scala.html

The marketing preferences request made on the one-off thank you page has been consistently failing. It turns out that this is because the CSRF token was missing. I *think* this probably happened in #631, when the thank you page became part of the one-off contributions checkout. At this point the thank you page template, which had the CSRF token, was replaced by the one-off checkout template, which hadn't needed this token up to that point.
This wasn't being picked up by our logging until #635 was merged, as errors weren't being correctly reported until this point. However, from the point when Sentry started working again there is a clear spike in errors showing this problem.
- Added token into template.

Added CSRF Token To One-Off Template

---

assets/pages/regular-contributions-existing/regularContributionsExisting.jsx
assets/pages/regular-contributions-existing/regularContributionsExisting.scss

When someone is already a recurring contributor, if they try to contribute again, they get directed to an error page inviting them to make a one-off contribution.
This should page should look like the rest of the site.
As a part of this card, we are also going to invite them to go to manage my account and change the recurring contribution instead, but I'm going to do this in two PRs because I'm looking to do the smallest change possible first. 
[**Trello Card**](https://trello.com/c/TWCHaftV/1469-existing-contributor)
* Update the existing contribution page based on the thank-you page. 
existing page
page based on thank-you page

Make existing contribution page more circles

---

assets/components/patronsEvents/patronsEvents.scss
assets/components/threeSubscriptions/threeSubscriptions.scss

The arrow alignment was a bit off in the CTA buttons on the support landing page

Fix the placement of arrows on the subscriptions ctas

---

assets/pages/support-landing/components/contributionPaymentCtasContainer.js
assets/pages/support-landing/components/payPalContributionButtonContainer.js

Fixes a bug caused by the payment logos AB test whereby the payment logos on the support landing test are against the wrong ctas

Swap the order of the payment ctas on the support landing page

---

assets/components/threeSubscriptions/threeSubscriptions.jsx

The word 'from' was accidentally dropped from the price descriptions in the May 2018 flash sale. This puts it back.

Add 'from' into the price descriptions for Paper and Paper+Digital

---

app/controllers/Application.scala
app/controllers/Subscriptions.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
conf/routes

The generic Application file is started to grow, and we will soon be adding more routes for the digipack so now seems like a good time to split the subs routes into a separate file.

Move subscribe routes into separate controller

---

cloud-formation/cfn.yaml

The default SSM policy is too open, we should be able to reuse a more restrictive version.
Done as part of [**This Trello card**](https://trello.com/c/kizmbanA/1494-use-ssm-instead-of-github-for-ssh-access)
* Modify `cfn.yaml` to use `guardian-ec2-role-for-ssm`
* Updated the description of the AMI section to say why the ID may not match any existing AMI
N/A: Proof will be the ability to `ssm ssh` to a code instance after this is cloud-formed 
Well, that's a bit harsh

Use a more restrictive SSM policy

---

app/config/Configuration.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
app/wiring/Services.scala
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf
test/selenium/conf/selenium-test.conf
test/selenium/util/Config.scala
test/selenium/util/Dependencies.scala
test/selenium/util/DriverConfig.scala

> `contributions-frontend`is gone. Long live `support-frontend`.
To remove contribution-frontend's references from the project.
[**Trello Card**](https://trello.com/c/3MQOcUp0/398-clean-up-support-frontend-after-paypal-and-stripe-prs)
* Removed contributions reference from config files and controllers
* Renamed payPalService to show the fact that is the NVP integration.
N/A

Post contributions clean up

---

test/selenium/OneOffContributionsSpec.scala
test/selenium/RecurringContributionsSpec.scala
test/selenium/util/Browser.scala
test/selenium/util/PayPalCheckout.scala

Post production tests are failing on Paypal payments.
This is because paypal have introduced a new guest checkout page.
Unfortunately, unlike Stripe, the functionality does not exist to mock the paypal process so we must continue running through the payment flow.
This change checks whether a guest checkout page has opened, and if it has it navigates to the express checkout page so that payment flow can begin.
This work was done in response to a retrospective action tracked in trello card:
https://trello.com/c/DQUOaoW7/1491-stub-paypal-in-end-to-end-tests

Handle the new paypal sandbox guest checkout page

---

assets/helpers/__tests__/urlTest.js
assets/helpers/payPalContributionsCheckout/payPalContributionsCheckout.js
assets/helpers/url.js
assets/pages/oneoff-contributions/helpers/ajax.js

To fix test users in production for one-off Stripe.
* Add logic for test users in Stripe production environment.
* Changed `addQueryParamsToURL` to accept `null` and `undefined`. 
N/A

Fix one-off Stripe test users in production

---

build.sbt

Guava is a direct and transitive dependency for support-frontend. I've tested the flows and test user pages (it's a dependency of some oauth libraries) and everything seems ok.
That said, I could also bump some of our other dependencies to reduce the risk of incompatibility errors if necessary.
[**Trello Card**](https://trello.com/c/q5JmiVzz/1572-ensure-that-snyk-has-zero-issues-on-all-sc-projects-support-frontend-scala)
- Bump Guava to v25.0.

Bump Google Guava

---

assets/helpers/__tests__/urlTest.js
assets/helpers/url.js

Sentry is reporting quite a lot of users hitting errors with `URLSearchParams.entries()` on older versions of Firefox. Technically we only support FF 44 and up (which is when this [was introduced](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/entries#Browser_compatibility), and polyfill.io doesn't seem to provide a polyfill). However, it's a straightforward fix and it's one of our most common errors so I've just done it. Will probably add some tests before merging since we don't have any at the moment.
- Added new function to get all query params as an array of type `Array<[string, string]>`.
- Used new function for `getAllQueryParamsWithExclusions`.
- Added corresponding tests.

Different Method For getAllQueryParamsWithExclusions For Old FF

---

assets/components/numberInput/numberInput.jsx
test/selenium/OneOffContributionsSpec.scala
test/selenium/pages/ContributionsLanding.scala
test/selenium/pages/OneOffContributionForm.scala

Currently we have a stripe end to end test for monthly contributions, but none for one off payments.
Once this is merged we will have a stripe and paypal test each for one-off and regular contributions.
This change adds the test steps and also adds the flow for catering to the one-off enter details form.
Work tracked by trello card: https://trello.com/c/RzYa6bG9/1579-add-post-deployment-test-for-one-off-stripe-payments

add stripe one-off contribution test

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.scss
assets/containerisableComponents/payPalContributionButton/payPalContributionButton.scss
assets/pages/contributions-landing/contributionsLanding.scss
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/support-landing/supportLanding.scss

The payment buttons on the one-off checkout are being flipped. This PR also makes the styles more consistent across the different places these buttons are used.
- Flipped buttons on one-off checkout.
- Made credit/debit button white on checkout.
- Made hover, colour, sizing and padding consistent across the buttons on the landing pages and one-off checkout.
**One-Off Checkout Before**
**One-Off Checkout After**
**Contribute Before**
**Contribute After**

Flip One-Off Payment Buttons

---

assets/pages/contributions-landing/contributionsLanding.jsx

To set up the same header in all regions for the variant of the test.
N/A

Applying variant header copy to all regions

---

.travis.yml

Very occasionally selenium tests are failing randomly and then working again on retry.
This can be the result of things like timeouts or selenium issues which don't reflect on the code being tested.
This change will force a failing test to be retried 3 times before the developer is alerted. 
The aim of this is to minimise false alarms and guarantee that if the developer is to be alerted - there is something worthy of attention.
documentation on this command can be found here: https://docs.travis-ci.com/user/common-build-problems/

Adding "travis_retry" wrapper to selenium test step. 

---

app/lib/CustomHttpErrorHandler.scala

We accidentally dropped the error logging when we introduced Circles-branded 500 pages. Re-instating this makes it easier to debug production issues.
* Log server errors when we throw a 500

Re-instate 500 error logging

---

app/controllers/OneOffContributions.scala
app/controllers/RegularContributions.scala
app/views/monthlyContributions.scala.html
app/views/oneOffContributions.scala.html
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/regular-contributions/regularContributions.scss
assets/stylesheets/main.scss
webpack.common.js

To reduce the amount of CSS we serve to the checkouts.
| Stylesheet | Size Before | Size After
|-|-|-
regular | 73.4 KiB | 33 KiB
one-off | 73.4 KiB  | 32 KiB
styles | 73.4 KiB  | 61 KiB
[**Trello Card**](https://trello.com/c/u96YNgNV/1466-apply-css-optimisation-changes)
**Note:** I got fed up using `../../` everywhere so I've started taking advantage of `sass-loader`'s ability to use the [webpack resolver](https://github.com/webpack-contrib/sass-loader#imports). We resolve our assets in webpack from the `assets/` directory, so we can use `~` on imports to specify them relative to that path.
- Create page-specific stylesheets for the one-off and regular checkouts.
- Remove the checkouts and thank you pages from the main styles bundle.

Split CSS On Checkouts

---

assets/pages/contributions-landing/contributionsLanding.jsx

* One-time only for US 🇺🇸
* One-off for the rest
[**Trello Card**](https://trello.com/c/JeqvHqj5/469-update-one-off-in-us)
* Updated copy of the contributions landing pages

Updated one-time one-off copy for US

---

assets/pages/paypal-error/payPalError.jsx
assets/pages/paypal-error/payPalError.scss

These are really out of date, this applies newer branding. It also reduces the usage of some legacy components and styles, that will now hopefully move closer to deletion.
[**Trello Card**](https://trello.com/c/Rud2TjYy/1605-paypal-error-pages-refresh)
- Used more off-the-shelf components for the PayPal error pages.
- Brought the styling more inline with current brand.
- Set the URL on the CTA to `/`, as `/uk` was too country-specific.
**Before**
**After**

Circles Brand PayPal Error

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx

Change the recurring CTA on the landing page from "Contribute <amount> with card or Paypal" to "<amount> a month" 
This has been requested by UX as it isn't even accurate any more: we also have direct debit in the UK, and the logos already convey that we provide card and paypal
|---------|--------|
|![paypl](https://user-images.githubusercontent.com/2844554/40727268-70d552e0-641f-11e8-980e-5a8c960cfca2.png)|![5 a month](https://user-images.githubusercontent.com/2844554/40727252-6754eaa0-641f-11e8-8905-7ee87d41e8f8.png)|

Change "with card or Paypal" to "a month"

---

assets/helpers/abTests/__tests__/abtestTest.js
assets/helpers/abTests/abtest.js

To be able to specify breakpoints to the audience segment of the AB test framework. If no breakpoint is defined by default the user will be in the test.
[**Trello Card**](https://trello.com/c/ot7uM3CU/444-add-breakpoints-in-ab-test-framework)
* Created `Audience` type
* Created `Breakpoint` type.
* Added the check `userInBreakpoint` to the `userInTest` function
* Defined `breakpoints` object in `abTest` helper
* Refactor validation to reconsider the case of `mvtId` equal to 0.
N/A

Adding breakpoints to the AB Test framework

---

app/controllers/Subscriptions.scala
assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx
assets/components/headers/countrySwitcherHeader/countrySwitcherHeader.jsx
assets/components/headers/countrySwitcherHeader/countrySwitcherHeaderContainer.js
assets/helpers/internationalisation/countryGroup.js
assets/pages/contributions-landing/contributionsLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
assets/pages/support-landing/supportLanding.jsx
conf/routes
public/robots.txt
webpack.common.js

This creates the skeleton of a page for the digital subscription. This will be filled in with a few independent sections.
[**Trello Card**](https://trello.com/c/P4kYc7Av/1451-product-page-uk)
- Added new controller method for the page, which puts in behind a query param while in dev.
- Updated the `CountryGroupSwitcher` and `CountrySwitcherHeader` to be more generic, so we can use them for any internationalised URL. Now takes a `subPath` and a list of countries, and returns a connected component.
- Created a new method `stringToCountryGroup`.
- Added a new JSX entry point for the digital subscription page.
- Added routes for the new, internationalised digital sub page.
- Put the new routes in `robots.txt` for now.

Digital Subscription Skeleton

---

app/monitoring/Logging.scala
app/monitoring/SentryLogging.scala
app/wiring/AppComponents.scala
assets/helpers/logger.js
assets/pages/regular-contributions-existing/regularContributionsExisting.jsx
build.sbt
conf/logback.xml

We scrubbed PII here:  https://github.com/guardian/support-frontend/pull/494
As we stop sending PII, to sentry, we are also deleting old sentry projects and starting anew. 
Both support and support-client-side shall point to new projects in conjunction with this PR. 
* Pointing to the DSN of the new project for support-client-side
* Update the DSN configured in the config for the new sentry project for support
* Move to using sentry-logback (raven-logback is deprecated)
* Wrap Sentry.init in a try 
TODO:
Pre-merge
Post-merge
[**Trello Card**](https://trello.com/c/LiojyKYR/1555-delete-all-projects-which-contain-pii-from-sentry-and-replace-with-a-clean-project)
[Scrub PII from logs sent to sentry]( https://github.com/guardian/support-frontend/pull/494)

Fresh Sentry projects

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/contributionPaymentCtas/contributionPaymentCtas.scss
assets/components/ctaLink/ctaLink.jsx
assets/components/ctaLink/ctaLink.scss
assets/components/dotcomCta/dotcomCta.scss
assets/components/patronsEvents/patronsEvents.scss
assets/components/readyToSupport/readyToSupport.jsx
assets/components/readyToSupport/readyToSupport.scss
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/components/threeSubscriptions/threeSubscriptions.scss
assets/containerisableComponents/marketingConsent/marketingConsent.jsx
assets/containerisableComponents/marketingConsent/marketingConsent.scss
assets/containerisableComponents/payPalContributionButton/payPalContributionButton.scss
assets/pages/error/components/errorPage.jsx
assets/pages/error/error.scss
assets/pages/paypal-error/payPalError.scss
assets/pages/regular-contributions-existing/regularContributionsExisting.jsx
assets/pages/regular-contributions-existing/regularContributionsExisting.scss
assets/stylesheets/gu-sass/layout.scss

The CtaLink component had very similar styles applied to it in multiple different places. This de-dupes these styles.
- Decoupled `CtaLink` modifier classes from the id used for component tracking.
- Standardised and simplified the `CtaLink` styles.
- Deleted duplicate styles.
- Allowed border styles with `component-cta-link--border`.
- Brought the `PayPalContributionButton` in line with the `CtaLink` styles.
- Removed `$cta-width`, since the width isn't as standardised as the height now.

Tidy Up CtaLink

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx
assets/components/switchable/switchable.jsx
assets/containerisableComponents/payPalContributionButton/payPalContributionButton.jsx
assets/helpers/page/page.js
assets/helpers/switch.js
assets/pages/contributions-landing/containers/payPalContributionButtonContainer.js
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/support-landing/components/payPalContributionButtonContainer.js

To be able to change one line in the source-code, re-deploy and disable a payment flow.
After the brilliant work done by @Ap0c with the switchable component, I am adding a helper with the default switches and pushing them into the common state. Then I am reading these switches from the common state whenever is necessary. 
This work almost concludes the client side work required for the switchboard, next steps are deciding a place where to save the switches and reading them in the `switch.js` from that place, this logic should be located in the init function (which currently return the default switches). 
* Define default switches
* Push the switches to the common state
* Read the switches status form the common state and passing it to the different …

Adding default switch file

---

app/monitoring/SentryLogging.scala
conf/logback.xml

As part of https://github.com/guardian/support-frontend/pull/699/files, we upgraded to sentry-logback 1.7.5 and opted to configure the Sentry appender and so also the filters in the logback.xml as seen in the migration guide. However, if we have a custom filter (as we do now with the PiiFilter), then in DEV mode only, the logback.xml references this class before it's loaded and gives an ugly error message to the console (see screenshot below). We are returning to the previous approach to creating and configuring the sentry appenders and filters to resolve this issue.
[**Trello Card**](https://trello.com/c/LiojyKYR/1555-delete-all-projects-which-contain-pii-from-sentry-and-replace-with-a-clean-project)
* Create SentryAppender and SentryFilters in the SentryLogging object and add the …

Configure the Sentry appender and the filters in the code again

---

.eslintrc
assets/components/contribute/contribute.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/gridImage/gridImage.jsx
assets/components/gridPicture/gridPicture.jsx
assets/components/highlights/highlights.jsx
assets/components/introduction/circlesIntroduction.jsx
assets/components/introduction/squaresIntroduction.jsx
assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx
assets/components/secure/secure.jsx
assets/components/switchable/errorComponents/paymentError.jsx
assets/components/switchable/switchable.jsx
assets/containerisableComponents/payPalContributionButton/payPalContributionButton.jsx
assets/pages/contributions-landing/contributionsLanding.jsx
assets/pages/support-landing/supportLanding.jsx

Everywhere that we used `modifiers`, we now use `modifierClasses`. Also, the `react/default-props-match-prop-types` ESLint rule was conflicting with flow. This tweaks it, rather than manually disabling it all over the place. Follow-up from #697.
- Replace prop name `modifiers` with `modifierClasses`.
- Updated `react/default-props-match-prop-types` to ignore default props for required `PropTypes`. Flow wants props with defaults to be required.

More Descriptive Modifier Class and Update ESLint Default Props Rule

---

assets/components/leftMarginSection/leftMarginSection.jsx
assets/components/leftMarginSection/leftMarginSection.scss
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

We need a new type of page section for the digital subscription landing page. The new component added here will wrap each of the sections on the new page, and grow/shrink the size of the content and margins accordingly.
[**Trello Card**](https://trello.com/c/xIIEXAmC/1606-digital-product-page-containers)
- Added a `LeftMarginSection` component.
- Created placeholders for the sections on the digital sub landing page.

Left Margin Section For Digital Sub Landing

---

assets/components/priceCta/priceCta.jsx
assets/components/priceCta/priceCta.scss
assets/helpers/subscriptions.js
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

The CTA on the digital subscription landing page is consistent across all sections, a good case for a component. This creates that reusable component and drops it into the page.
[**Trello Card**](https://trello.com/c/xIIEXAmC/1606-digital-product-page-containers)
- Added a `PriceCta` component.
- Added a container for the `PriceCta` on the digital landing page.
- Added a new `subscriptions` helper, the equal of the existing `contributions` helper.
**CTA Desktop - AU**
**CTA Tablet - US**
**CTA Mobile - UK**

Digital Subscription CTA

---

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
conf/routes

The PR to add a skeleton page for digital subscription (https://github.com/guardian/support-frontend/pull/691) already added a country picker that updated the price on the page. However, while we resolve questions about the Australia product page, we shall remove it from the country picker. It will be readded in the future. 
[**Trello Card**](https://trello.com/c/IrhfApmz/1456-product-pages-for-other-regions)
* Removes Australia from the country picker of the digital subscription product page

Remove Australia from the country picker for the digital subscription product page

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/ctaLink/ctaLink.jsx
assets/components/dotcomCta/dotcomCta.jsx
assets/components/otherProduct/otherProduct.jsx
assets/components/patronsEvents/patronsEvents.jsx
assets/components/readyToSupport/readyToSupport.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/containerisableComponents/marketingConsent/marketingConsent.jsx
assets/pages/error/components/errorPage.jsx
assets/pages/paypal-error/payPalError.jsx
assets/pages/regular-contributions-existing/regularContributionsExisting.jsx

This isn't used anywhere in the codebase, I'm removing it from `CtaLink` for now to simplify the code.
- Removed component event tracking from `CtaLink`.
- Stopped passing through `ctaId` across the codebase.

Remove Component Events From CtaLink

---

assets/components/featureList/featureList.jsx
assets/components/heading/heading.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/svgs/pennyFarthingCircles.jsx
assets/helpers/theGrid.js
assets/pages/digital-subscription-landing/components/productBlock.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

This adds the "product block" (i.e. the second section) to the digital sub landing page.
[**Trello Card**](https://trello.com/c/8UBqJMTP/1532-product-block)
- Tweaked the `FeatureList` component to take a React `Node` as a heading, rather than just a `string`.
- Added a new `Heading` component to abstract creation of `h1-6` elements. This is used so that the `FeatureList` headings make semantic sense in the context of the page where they are used; good for a11y.
- Added two new images from the Grid, and a new circles-themed SVG.
- Created a new "product block" component for the digital sub landing page.
Breakpoint | Screenshot
-|-
LeftCol/Wide | ![product-leftcol](https://user-images.githubusercontent.com/5131341/41180387-03723f76-6b66-11e8-9f49-e219dba45039.jpg)
Desktop …

Digital Subscription Product Page - Product Block

---

app/controllers/Subscriptions.scala
conf/routes

So that we can use geolocation to pass users on to the correct version of the page.
[**Trello Card**](https://trello.com/c/t8yzHmmG/1604-geo-redirect-subscribe-digital)
- Added `Subscriptions` controller method to handle the redirect.
- Added new route at `/subscribe/digital` for redirection.

Geo Redirect Digital Product Page

---

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

On a slow connection the digital subscription landing page jumps severely when images are loaded into the header. If we specify a height of the container element upfront, we can prevent that jump from happening.
[Trello card](https://trello.com/c/Sg1o3Kfo/1738-prevent-digital-subs-landing-page-jump-when-loading-header-images)

Specify a height on the header image container to prevent page jump

---

assets/helpers/externalLinks.js
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx

We want the CTAs on the digital product page to link to the checkout on subs for now.
[**Trello Card**](https://trello.com/c/re8kTdtQ/1730-where-does-the-digipack-page-link-to)
- Added new function to build the digital pack URL.
- Mapped the digital checkout URL to the digital product CTA.
- Updated `externalLinks` and `flashSale` to handle promo codes as just the code, and transform them into a URL later as needed.

Link Digital Product Page To Subs Checkout

---

assets/containerisableComponents/contributionsThankYou/contributionsThankYouPage.jsx
assets/pages/oneoff-contributions/components/oneOffContributionsPage.jsx
assets/pages/regular-contributions-existing/regularContributionsExisting.jsx
assets/pages/regular-contributions/components/regularContributionsPage.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

The font size on the subsequant pages from the landing page in the contributions flow was larger than that of the landing page. This PR fixes this issue
Landing Page (no change, just including to compare to other pages below):
Before | After
|-------|------|
|![page 1](https://user-images.githubusercontent.com/2844554/41539152-f326bfd8-7304-11e8-890a-4515fcc416d9.png)| ![page 1](https://user-images.githubusercontent.com/2844554/41539291-4ffe8574-7305-11e8-93ef-e0296e66c316.png) 
One-off payment page
Before | After
|-------|------|
|![page2old](https://user-images.githubusercontent.com/2844554/41539162-f8f919d8-7304-11e8-9bdf-413880aa9189.png)| ![page2new](https://user-images.githubusercontent.com/2844554/41539296-54d94d04-7305-11e8-8488-30f99201ca0f.png) |
Thank you page
Before | After …

Make heading font size consistent across pages

---

assets/components/stripeInlineForm/stripeInlineForm.jsx
assets/helpers/abTests/abtestDefinitions.js
assets/pages/oneoff-contributions/components/oneoffInlineContributionsPayment.jsx
assets/pages/regular-contributions/components/regularInlineContributionsPayment.jsx

Before we were not able to see the use who made payment in stripe dashboard, now we can.
* Passing the email as the name in `stripe.createToken` function.
N/A

Re-enabling stripe elements

---

assets/helpers/externalLinks.js
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx

The digital pack checkout on subs takes a `countryGroup` query param to determine what version of the form to show. This passes through that query param from the product page.
[**Trello Card**](https://trello.com/c/YlDLscXN/1740-digital-pack-checkout-country-group)
- Passed the `countryGroup` query param to subs on the product page.

Pass Country Group To Subs Checkout

---

assets/helpers/abTests/abtest.js

`Number(null)` returns 0, which makes a user always land in the same variant if he or she has not visited the gu site before. This PR fixes that.
* abTest framework
N/A

Fixing Ab test framework for non gu traffic

---

assets/components/gridPicture/gridPicture.jsx
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx

We're seeing 404s when requesting the fallback image for the digi subs landing page header. That's because I somehow got a bad property name past the type checker. This fixes it.
Introduced in https://github.com/guardian/support-frontend/pull/719
[**Trello Card**](https://trello.com/c/ZJeu2J1a/1741-fix-incorrect-property-name-for-fallback-image-in-digital-subscription-landing-page)

Fix a typo in a prop name that I managed to sneak past the type checker

---

README.md

To access the switch file wiki from the Readme.
* Readme
N/A

Adding link to the switch file from the readme

---

app/actions/CustomActionBuilders.scala
app/controllers/RegularContributions.scala
assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/helpers/abTests/abtestDefinitions.js
assets/pages/contributions-landing/containers/contributionPaymentCtasContainer.js
assets/pages/support-landing/components/contributionPaymentCtasContainer.js
conf/routes
test/controllers/RegularContributionsTest.scala

An A/B test that tests Identity's new (and as yet unfinished) flow. 
Half of the non-signed in users who choose to try and make a recurring contribution will go to the old flow (https://profile.theguardian.com/register) and half to the new (https://profile.theguardian.com/signin/start)
The test is currently set to inactive, we will flip it to active when identity is ready.

Test the new sign-in flow for recurring contributors

---

assets/helpers/tracking/googleTagManager.js

Since we released this PR: https://github.com/guardian/support-frontend/pull/727 the number of errors in Sentry went up. I have two theories about this, the first is we are not handling the rejected case of the promise, the second in old browsers Promise is not available and therefore, returns an error.
As a solution, I added a "PromisedRejected" case and "PromiseNotSupported" case to the tracking.
N/A

Handling rejected case of PaymentRequest's promise 

---

assets/helpers/tracking/googleTagManager.js

LoggingError receives a string, we were passing the error object.
N/A

Only logging the error message not the Object

---

assets/helpers/logger.js
assets/helpers/tracking/googleTagManager.js

To reduce the noise in Sentry.
At the moment we are logging several "Payment Request API" errors as Errors but we shouldn't. We are trying out the payment API in production, and we would like to know the reason for its failure, but we are not going to fix it. Therefore, to reduce the noise in Sentry, I am passing those logs from exception to info. In the place where the previous exceptions took place, we handle them correctly, so the behaviour for the end user should be the same.
* Created `logInfo`
* Replace `logException` with `logInfo` in Payment Api flow
N/A

Logging payment API request errors using info level

---

assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.scss
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/components/oneoffInlineContributionsPayment.jsx
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/regular-contributions/regularContributions.scss

One-off contributors who have already selected to pay by card were being asked again to pick a payment method: card or paypal. We should remove paypal as an option if they have already selected to pay by card. 
[**Trello Card**](https://trello.com/c/n9x8uawR/1747-remove-paypal-button-from-pay-with-card-page-for-one-off-contributions)
* Removed the button to pay by paypal on the page shown when a user has indicated they will make a one-off contribution by card
* Removed the button to pay by paypal for the [inline stripe test](https://github.com/guardian/support-frontend/pull/728), too
|        | **With paypal button removed**           | **Current behaviour**   |
| ------------- |:-------------:| -----|
| **Pop-up stripe checkout**     | …

After already picking pay by card don't suggest paying by paypal

---

app/controllers/DirectDebit.scala
app/controllers/PayPalRegular.scala
app/controllers/RegularContributions.scala
test/actions/ActionRefinerTest.scala

Identity Frontend is not ready to receive the new client ID, as it was previously inserting some custom "Support the Guardian" text for the `members` clientId, which it is not set up to do for the new `recurringContributions` client Id.
This PR ensures that the `members` clientId is always sent to identity frontend, as it was previously

Revert to sending "members" identity clientID

---

app/switchboard/Switches.scala
app/views/main.scala.html
app/views/optimizeScript.scala.html
app/views/switchesScript.scala.html
app/wiring/ApplicationConfiguration.scala
assets/helpers/tracking/optimize.js
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf
test/controllers/RegularContributionsTest.scala
webpack.common.js

Depends on: https://github.com/guardian/support-frontend/pull/757
To enable us to switch off Google Optimize if we decide to, either for performance reasons or if it causes any unexpected issues. It also switches Optimize off by default in DEV to avoid confusion during development.
[**Trello Card**](https://trello.com/c/BZjieC3Q/1753-make-optimize-configurable-by-the-switchboard)
* Add an `optimize` switch to the Switches object and stage configs.
* Move the Google Optimize tag into a separate Twirl fragment and js file and only include these in the page when `optimize=On`.

Optimize switch

---

assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
assets/helpers/page/__tests__/pageTest.js
assets/helpers/page/page.js

In https://github.com/guardian/support-frontend/pull/751 I introduced a bug, where we are updating the state incorrectly. To fix the setCountry action from page.js
* Page Actions
N/A

Fix setCountry action

---

assets/helpers/contributions.js

This used to be $16000 on https://contribute.theguardian.com, and it is in the Payment API

Increase Australia one-off limit to 16000

---

assets/components/ctaLink/ctaLink.jsx
assets/helpers/url.js

We have deprecated `addQueryParamToURL` in favour of `addQueryParamsToURL`; this removes it. It also turned out that `acquisitionData` wasn't being passed to `CtaLink` anywhere so I've removed it from the file.
[**Trello Card**](https://trello.com/c/NenDn1H8/1300-replace-addqueryparamtourl)
- Removed the `acquisitionData` prop from `CtaLink`.
- Deleted `addQueryParamToURL`.

Delete Old Query Param Function

---

assets/helpers/abTests/abtestDefinitions.js

We've got an issue where some customers paying via Stripe are being charged multiple times. These issues started about the time the inline Stripe test (#728) went out, and the inline variant is disproportionately represented in cases where multiple payments happened. This makes us suspect the test is to blame.

Turn off inline Stripe payment test

---

app/controllers/Subscriptions.scala
assets/helpers/externalLinks.js
assets/helpers/tracking/optimize.js

To A/B test the new Digital Pack product page against the old (subscribe.theguardian.com) one.
[**Trello Card**](https://trello.com/c/4JrlMG26/1502-a-b-test)
* Remove the need to add `digiSub=true` to the product page url
* Change the digi pack destination url from the `/subscribe` & `/uk` page to the new page - the A/B split is handled by Google Optimize

Switch on product test

---

app/actions/CustomActionBuilders.scala
app/controllers/RegularContributions.scala
assets/helpers/abTests/abtestDefinitions.js

This PR does 2 things:
1) Send new client ID to identity. To see the effects of the new `recurringContributions` clientID, check out [this PR](https://github.com/guardian/identity-frontend/pull/427) on `identity-frontend`.
2) Turn on the 2 step sign in test. To see the effects of this test, see [this PR](https://github.com/guardian/support-frontend/pull/739) in `support-frontend`.
@guardian/contributions 
If you merge this, you should check:
a) that hitting identity with the `recurringContributions` clientId results in exactly the behaviour described in the PR
b) that the control in the test boots you to `/register` and that the variant boots you to `/signin/start`. You should sit down with Katya and test it on CODE to validate that it is working correctly for all paths

Turn on 2 step sign in test, and send new client id to identity

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/footer/footer.jsx
assets/components/legal/contribLegal/contribLegal.jsx
assets/components/legal/legalSection/legalSection.jsx
assets/components/legal/legalSection/legalSectionContainer.js
assets/components/legal/termsPrivacy/termsPrivacy.jsx
assets/components/questionsContact/questionsContact.jsx
assets/helpers/internationalisation/countryGroup.js
assets/helpers/legal.js
assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
assets/pages/error/components/errorPage.jsx

So `/au` pages have an Australia specific contact email. This PR changes the email in the footer on the contribution landing page only. 
[**Trello Card**](https://trello.com/c/GUZ8HYhH/606-australian-footer-link-update)
The contact email appears in the `contribLegal`,`QuestionsContact`, `LegalNotice`, and `ReportLink` components. 
Its value is now set to vary by optional prop CountryGroupId, with a default of `GBPCountries`. 
The default (GBPCountries) is used in all function calls (no props are passed) except on the support landing page where the internationalisation group is passed as an argument. So far, only `AUDCountries` has a distinct email. 
The terms link, in `TermsPrivacy` component, is now set by `countryGroupId` (previously this was determined by country and so broken for any …

internationalisation of contact email and terms

---

assets/helpers/tracking/googleTagManager.js

To track internal campaign codes in GA which will make it possible to segment traffic from the banner and epic.
[**Trello Card**](https://trello.com/c/42TRdjiX/1758-track-intcmp-code-in-ga)

Send the INTCMP code to GA

---

app/codecs/CirceDecoders.scala
app/views/ViewHelpers.scala
app/views/switchesScript.scala.html

DRY - it's much better to just update the switch code in one place rather than having to remember to update the Js version as well.

Derive the Js switches from the Scala ones automagically

---

app/switchboard/Switches.scala

Fixes a mistake in #778, not visible in the actual PR because the mistake was in the Scala code that's used to generate the JS

Fix oneOffPaymentMethods spelling

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/helpers/abTests/abtestDefinitions.js
assets/pages/contributions-landing/containers/contributionPaymentCtasContainer.js
assets/pages/support-landing/components/contributionPaymentCtasContainer.js

Due to a bug in identity for one of the variants, the data we have thus far collected is invalid and we need to restart the test. The simplest way to do this is to rename the test, which is what this PR does

Rename sign in test

---

app/controllers/Subscriptions.scala
app/switchboard/Switches.scala
assets/components/customerService/customerService.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
conf/routes

To create the Australian version of the Digital Pack page and then to set the correct price and customer service details on it.
**Trello Cards:** [Here](https://trello.com/c/sO5QICtf/1729-update-price-for-aus) and [here](https://trello.com/c/cjygywqe/1739-customer-service-details-for-aus)

Add the AU digipack page

---

assets/components/contributionsCheckout/contributionsCheckout.jsx
assets/components/displayName/displayName.jsx
assets/components/yourDetails/yourDetails.jsx
assets/pages/oneoff-contributions/components/contributionsCheckoutContainer.jsx
assets/pages/regular-contributions/components/contributionsCheckoutContainer.jsx

`DisplayName` is a shared component and therefore shouldn't be connected to Redux.
[**Trello Card**](https://trello.com/c/fQQkzyUR/1453-disconnect-displayname)
- Removed the Redux `connect`ion from `DisplayName`.
- Passed the `name` and `isSignedIn` props down from the checkout.

Disconnect DisplayName

---

assets/components/stripeInlineForm/stripeInlineForm.jsx

The inline stripe button is now live; we need to add the relevant id so the selenium tests know where to click! 
The selenium tests are now passing locally.

update stripe button

---

assets/components/contributionsCheckout/contributionsCheckout.scss
assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx
assets/components/countryGroupSwitcher/countryGroupSwitcher.scss
assets/components/selectInput/selectInput.jsx
assets/components/selectInput/selectInput.scss
assets/components/textInput/textInput.jsx
assets/components/textInput/textInput.scss
assets/components/yourDetails/yourDetails.jsx
assets/components/yourDetails/yourDetails.scss
assets/pages/oneoff-contributions/components/emailFormField.jsx
assets/pages/oneoff-contributions/components/nameFormField.jsx
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/regular-contributions/components/formFields.jsx
assets/pages/regular-contributions/regularContributions.scss
assets/pages/support-landing/supportLanding.scss
assets/stylesheets/gu-sass/accessibility.scss

It provides a better user experience and is important for accessibility (particularly screen readers). This affects the form fields on the contributions checkouts (regular and one-off), and the country group switcher.
**Note:** There aren't that many lines altered in this PR, but it's quite dense in terms of the number of changes (see below).
[**Trello Card**](https://trello.com/c/7XvdNj67/1475-ensure-form-elements-have-an-associated-label)
- Moved 'All fields are required' to the bottom of the form on the contributions checkout, and tweaked where the CSS lives.
- Tweaked the country group switcher to apply styles to the existing `SelectInput` classes, rather than passing through its own class name.
- Updated the way `SelectInput` and `TextInput` handle default props to …

Form Elements Should Have Labels

---

assets/pages/regular-contributions/components/formFields.jsx

They're provinces/territories in Canada.
- Use the word 'state' for the US, 'province/territory' for Canada.
**Canada**
**US**

Canada Uses Province/Territory

---

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

Follow up to #787, the country selector is missing some styles.
- Added `selectInput` stylesheet to the digital product page.

Fix Country Selector Styles On Digital Product Page

---

app/controllers/PayPalOneOff.scala
app/services/PaymentAPIService.scala

Update method names in `PaymentAPIService` to more accurately reflect what they're doing. As it stands, they are a potential source of confusion e.g. in #786 we have modelled Stripe and Paypal API errors whereas actually only the Paypal API error is necessary.

more accurate method names

---

app/codecs/CirceDecoders.scala
app/services/PaymentAPIService.scala
build.sbt

Currently there are a significant number of payment attempts that seem to be duplicated. 
We suspect this is caused by the contributors browser sending the execute payment command twice - perhaps because the response from the first attempt did not reach the browser.
When this happens, Paypal processes the payment on receipt of the first the execute command and then responds to the second execute command with a "PAYMENT_ALREADY_DONE" error.
This means that from the contributors perspective it looks like the payment has failed and this risks them making a second payment if they re-attempt it.
As we have updated Payment API to send the error details of any payment error back to support frontend, this change will inspect the contents of any error and if the error is a PAYMENT_ALREADY_DONE …

Show paypal payment with "PAYMENT_ALREADY_DONE" as successful

---

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

We've picked up some side-scrolling on mobile on the digital product page. Can't quite figure out why `overflow-x: hidden` isn't dealing with this, so I've moved the image to the left a bit.
- Tweaked the `left` property to stop side-scroll.

Fix Digital Product Side Scroll

---

assets/components/doubleHeading/doubleHeading.jsx
assets/components/doubleHeading/doubleHeading.scss
assets/components/featureList/featureList.jsx
assets/components/heading/heading.jsx
assets/components/highlights/highlights.jsx
assets/components/introduction/circlesIntroduction.jsx
assets/components/introduction/squaresIntroduction.jsx
assets/components/readyToSupport/readyToSupport.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/components/whySupport/whySupport.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx
assets/pages/support-landing/supportLanding.jsx

Because there should only be one `<h1>` on a page. The showcase page contained nine!
[**Trello Card**](https://trello.com/c/2lLVUOPz/1786-only-one-h1-per-page)
* Leave the main page title alone, it's an `<h1>` with multiple spans inside
* Change all other `<h1>` elements to `<h2>` or `<h3>` depending where they sit within the page hierarchy
**Before**
**After**
Note: You shouldn't have seen any differences between those screen captures!

Replace h1 elements for h2 or h3 where applicable

---

app/controllers/Application.scala
conf/routes

Currently if a user types in a url of `/uk/` we serve a 404. This PR changes that behaviour so that we redirect them to `/uk` instead.

Strip trailing slashes from paths

---

build.sbt
project/plugins.sbt

This change bumps Play to a later version and Akka to its latest version.
This change is to remove the huge amount of "invalid user-agent" warning messages in the support-frontend logs. These were so numerous as to render the logs almost unreadable.
See https://github.com/guardian/grid/pull/2129 for similar change for same reason.
A fix to this issue became available in Play 2.6.13: https://discuss.lightbend.com/t/play-2-6-13-released/629

Remove noisy akka user agent warnings

---

assets/components/gridPicture/gridPicture.jsx
assets/helpers/theGrid.js
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/components/productBlock.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

Image and copy changes for the AU version of the digital product page.
[**Trello Card**](https://trello.com/c/8SpzwrWd/1727-product-block-aus) and [also](https://trello.com/c/8xwxpoJb/1728-header-block-aus).
- Refactored the `GridPicture` types to split up the image and the slot on the page that it goes into.
- Added AU images from the Grid.
- Updated the digital product header to allow internationalised versions of the image, and added AU version.
- Updated the product block to allow internationalised versions of the app image and copy, and added AU version.
- Tweaked the product block column wrapping to accomodate new copy.
### Tablet
### Mobile

Digital Product Page AU Tweaks

---

app/controllers/Application.scala
app/controllers/SiteMap.scala
app/controllers/Subscriptions.scala
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
conf/routes
webpack.common.js

Create a placeholder page for Digital Pack checkout and put it behind an Identity check so that only signed in users can access it.
[**Trello Card**](https://trello.com/c/68lxjHGr/1504-sign-in-sign-up-identity)

Add a placeholder checkout page for digital pack

---

app/controllers/PayPalOneOff.scala

Small tweak to the logs to include a message when paypal one-off payments are successful.

add paypal payment success message to logs

---

app/services/stepfunctions/RegularContributionsClient.scala

The polling logic is currently broken (it always shows the pending thank you page, rather than the thank you page).
This logic relies on parsing the ContributionCompleted state in order to recognise the successful completion of the checkout process. However, since support-workers and support-frontend are using a different version of the schema at the moment (see https://github.com/guardian/support-workers/pull/124/files, https://github.com/guardian/support-frontend/blob/master/build.sbt#L66, https://github.com/guardian/support-models/pull/12) we never acknowledge that an execution has completed successfully.
I've simplified the approach taken in support-workers: https://github.com/guardian/support-workers/pull/131. This PR allows us to understand the new state machine logic.
* Look for …

Simplify polling

---

assets/pages/subscriptions-landing/components/splitSubscriptionsTest.jsx

Adding an 's', `subscription` -> `subscriptions`.
- Changed ophan events to `split_subscriptions_test` from `split_subscription_test`.

Split Subscriptions Is Plural

---

assets/components/payPalContributionButton/payPalContributionButton.jsx
assets/helpers/paymentIntegrations/payPalPaymentAPICheckout.js
assets/helpers/routes.js
assets/helpers/url.js
assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
assets/pages/support-landing/supportLanding.jsx

In the PayPal REST integration, the cancel URL is used whenever a user cancels their payment in the PayPal UI. This should send users back to where they were on our site, rather than to an error page.
- Added a new method to get current URL.
- Updated the one-off cancel URL to be the current URL or, if that fails, the origin.

Update PayPal REST Cancel URL

---

app/services/stepfunctions/RegularContributionsClient.scala

This PR allows us to start providing faster feedback when a payment failure occurs during the checkout process.
Companion PR here: https://github.com/guardian/support-workers/pull/133
[**Trello Card**](https://trello.com/c/KTqKRJ44/1826-fix-polling-functionality-to-improve-checkout-experience)
* Re-factor polling logic and recognise new CheckoutFailure state (https://github.com/guardian/support-workers/pull/133/files#diff-dfd6eb6e38897b10b523498706e43f59)
* Do NOT tell the client that the checkout was a failure if the overall Step Function execution fails (https://github.com/guardian/support-frontend/compare/jw-understand-failures?expand=1#diff-ecaf18660141161c28efec09643d39a4L126), since it's possible that the execution could fail after we've taken the user's money. In cases where we …

Show users an error when the checkout process fails (due a payment failure)

---

app/controllers/PayPalOneOff.scala

Currently we log any payment cancellations from paypal as an error.
This seems incorrect.
This change will log payment cancellations as info - avoiding sentry alerts for something that is not actually an error.

a user selecting to cancel their payment should not be logged as an error

---

assets/helpers/contributions.js

Epic round 6 – promoting recurring contributions requires the ability to donate $5 in NZ and AU in monthly. 
@ionamckendrick 
[**Trello Card**](https://trello.com/c/45nLkEc6/674-change-minimum-recurring-amount-in-aus-nz-to-5)
NOW
BEFORE

update au and nz min montly values to 5

---

assets/components/contributionsCheckout/contributionsCheckout.scss
assets/components/emailFormField/emailFormField.jsx
assets/components/textInput/textInput.jsx
assets/helpers/user/userReducer.js
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/__tests__/oneoffContributionsReducersTest.js
assets/pages/oneoff-contributions/components/emailFormFieldContainer.jsx
assets/pages/oneoff-contributions/oneOffContributionsReducer.js
assets/pages/oneoff-contributions/oneoffContributions.scss
assets/pages/oneoff-contributions/oneoffContributionsActions.js
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/__tests__/regularContributionsReducersTest.js
assets/pages/regular-contributions/components/emailFormFieldContainer.jsx
assets/pages/regular-contributions/regularContributions.scss
assets/pages/regular-contributions/regularContributionsActions.js
assets/pages/regular-contributions/regularContributionsReducer.js

Previously, if the email address entered by the user was invalid, the payment buttons would be disabled, but the only indication as to why was the "All fields required" text. This PR adds some instant validation to the email field which fires in the `onChange` event on the input, but only once `onBlur` has been fired once, to make sure that we don't show an error message on the users first attempt to write in their email (as whilst they are typing their email for the first time, it will be in an invalid state until they get to the first character after the first period after the `@` sign)
| ----- | ------- |
|![oldemail](https://user-images.githubusercontent.com/2844554/43536365-55984e44-95b4-11e8-9dd4-277992c68350.gif)|![newemail](https://user-images.githubusercontent.c …

Improve validation on email form (recurring + one off)

---

app/controllers/RegularContributions.scala
app/cookies/RecurringContributionCookie.scala
app/wiring/Controllers.scala
test/controllers/RegularContributionsTest.scala

As not all recurring contributors will sign in with guest checkout, we need to drop a cookie so that frontend can recognise recurring contributors and push them to sign in
Here is an example of the cookie (one for monthly, one for annual)
`gu.contributions.recurring.contrib-timestamp.Monthly` : `2018-08-03T11:05:38Z`
`gu.contributions.recurring.contrib-timestamp.Annual` : `2018-08-03T11:05:38Z`

Drop cookie for recurring contributions

---

assets/helpers/tracking/googleTagManager.js

There are a couple of issues with the [original implementation of ecommerce tracking](https://github.com/guardian/support-frontend/pull/813)
* Currency code is not being set correctly
* The product type is missing for one off contributions which have checked out via PayPal.
This PR sets the currency at the root of the ecommerce tag object which looks like the correct approach according to [this doc](https://developers.google.com/tag-manager/enhanced-ecommerce) although it's far from explicit.
It also sets the product type to `one_off_contribution` when it is missing.

Fixes for ecommerce tracking

---

app/controllers/PayPalOneOff.scala
app/services/PaymentAPIService.scala

Currently the only information we log for payment failures in support frontend is the fact that they have failed.
This change takes advantage of the increased information we have available to us to give more detail on the nature of the payment failures.

Add more detailed logs for paypal payment failures

---

assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/components/oneoffInlineContributionsPayment.jsx

There was a bug whereby the `isFormEmpty` prop for the `oneOffContributionsPayment` component (and the inline version of the page) was being incorrectly set, if the user isn't signed in. This is because the check to see if the name field is empty was `state.page.user.fullName === ''`. But if the user isn't signed in, `state.page.user.fullName` doesn't get set until the user types something into the name field, so `state.page.user.fullName` returns `undefined`. 
This fix changes the check to `!state.page.user.fullName`, and names the varaible `isFormEmpty` to `areAnyRequiredFieldsEmpty`, which better describes the field.

Fix form validation error on One Off Contributions checkout page

---

app/controllers/Subscriptions.scala
app/switchboard/Switches.scala
assets/components/digitalSubscriptions/digitalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.scss
assets/components/internationalSubscriptions/internationalSubscriptionsContainer.js
assets/components/paperSubscriptions/paperSubscriptions.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/helpers/externalLinks.js
assets/helpers/flashSale.js
assets/helpers/subscriptions.js
assets/helpers/theGrid.js
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx
assets/pages/subscriptions-landing/components/splitSubscriptionsTest.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.scss
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf
conf/routes
test/controllers/RegularContributionsTest.scala

To add subscribe landing pages for the US, Australia and the rest of the world.
* Created new routes for the international versions of the subscribe landing page - these are behind a switch
* Added a `countryGroupId` parameter to the subscription components which are valid outside the UK (not Paper or Paper+Digital)
* Added a new type `SubscriptionProduct` to the subscriptions.js helper file - we had a number of different types scattered around various files, all of which represented a subscription product. To tidy this up I've created a new type and migrated all of the old code over to use it. 
* Added all prices into subscriptions.js and integrated these with the discounting code in flashSale.js so that it is simpler to get hold of the correct price …

International subscribe pages

---

app/codecs/CirceDecoders.scala
app/views/ViewHelpers.scala

To enforce encoding rules across different formats is a dangerous game, as I learned recently 😒  
For instance, the hocon syntax (a superset of json) in the configuration files is very lenient when it comes to strings: they may contain spaces and key may contain dashes. So 
```
my-key: look at me I contain spaces and I don't even care
```
is valid, but not in JSON. Circe pretty-printers normally take care of that:
```
"my-key": "look at me I contain spaces and I don't even care"
```
but all the double-quotes are stripped off in the Twirl template. This PR removes that.
Now:

Fix JSON rendering

---

assets/pages/oneoff-contributions/oneoffContributions.jsx

When we deprecated `contributions-frontend`, one thing we didn't port over was the dropping of a cookie when a user makes a one-off contribution, which stops users on the site seeing contributions ads for a limited time. 
This PR re-implements this behaviour. 
An example of the cookie dropped is: 
`gu.contributions.contrib-timestamp`: `Wed Aug 08 2018 15:41:08 GMT+0100 (British Summer Time)`

Drop cookie when user hits one off contribution thank you page

---

assets/helpers/flashSale.js
assets/helpers/subscriptions.js
assets/helpers/utilities.js

A usage of `Number.isInteger` was introduced in #835. This isn't supported in IE, so this PR adds a cross-browser compatible version.
[**Trello Card**](https://trello.com/c/yWCYO1ER/1849-fix-internet-explorer-isinteger-bug)
- Added an `isInteger` utility function.
- Applied some type annotations.

Fix IE Integer Bug

---

assets/helpers/abTests/abtestDefinitions.js

We want to restart the test in the near future with some improvements, so for now we are going to turn it off

Temporarily turn off recurring guest checkout test

---

assets/pages/support-landing/supportLanding.jsx

The showcase page used to say 'Contribute', now it does again.
- Add the heading 'Contribute' to the showcase page.
### After

Add Contribute Heading

---

app/cookies/RecurringContributionCookie.scala
assets/pages/oneoff-contributions/oneoffContributions.jsx

Whitespace and colons are not allowed in cookie values (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives). These are causing cookie parsing in Identity to break, preventing Google sign-in for anyone who has a contributions timestamp cookie.
This has also highlighted the fact that we were actually using two different time formats in the recurring and one-off timestamp cookies (ISO 8601 and the JS-specific format like "Tue Aug 19 1975 23:15:30 GMT+0200 (CEST)", respectively)
So I've set them both to Unix epoch milliseconds

Use epoch milliseconds for contributions timestamps

---

app/controllers/Subscriptions.scala
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

* Missed the `/subscribe` route in https://github.com/guardian/support-frontend/pull/835
* Fix the 'See supporter options' button on international pages

Routes for international subscribe pages

---

conf/PROD.public.conf

To enable international subscribe landing pages
[**Trello Card**](https://trello.com/c/DXoVZpgW/1853-switch-on-international-subscribe-ab-test)

Switch on the international landing pages

---

assets/helpers/tracking/conversions.js
assets/helpers/tracking/ophanComponentEventTracking.js
assets/pages/oneoff-contributions/helpers/ajax.js
assets/pages/regular-contributions/helpers/ajax.js

Previously we weren't tracking an Ophan pageview on the recurring `thankyou` page, only on the `pending` page. This PR moves the tracking for both into a single function to reduce the chance of this happening anywhere else

Conversion tracking fix

---

app/views/newPaymentFlow.scala.html
public/assets-new-ui/styles.css

Because it looks great.
[**Trello Card**](https://trello.com/c/J07ANBRj/712-npf-add-country-selector)
Positioning on the grid is not final so I haven't done too much with that, which is why the selector is stuck to the top of the viewport.

Payment Flow: Styling the country selector

---

app/views/newMain.scala.html

So that it's easier for people outside the department to see the results of this ongoing redesign.
I'm not cleaning up the config as it will come in handy when we're ready to launch the 50% test.

Payment Flow: Remove participation test

---

assets/components/headers/countrySwitcherHeader/countrySwitcherHeader.scss
assets/components/headers/simpleHeader/simpleHeader.scss
assets/components/introduction/introduction.scss
assets/stylesheets/fallback-pages/unsupportedBrowser.scss
assets/stylesheets/gu-sass/colours.scss

To bring them in line with dotcom.
- `nav-background-colour` -> `nav-faded`
- `nav-rule` -> `nav-dark`

Update Nav Colours

---

app/views/main.scala.html

I noticed our font preload links are giving some errors:
And that the browser seems to be fetching the fonts twice:
The issue is that fonts are loaded using anonymous mode CORS, even when they're on the same domain: https://drafts.csswg.org/css-fonts/#font-fetching-requirements
Adding a `crossorigin` attribute fixes the issue. I also added `type="font/woff2"` for good measure though I'm not sure if it makes any difference.
Now fonts are just loaded once:

Fix preload links

---

assets/components/digitalSubscriptions/digitalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.scss
assets/components/paperSubscriptions/paperSubscriptions.jsx
assets/helpers/externalLinks.js
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

The new US landing page has been doing very badly compared to the control so we've decided to make some changes and retest.
[**Trello Card**](https://trello.com/c/ZrJn8ZH8/1859-updates-to-us-subscription-landing-page)
* Remove prices
* Add free trial text
* Remove Patrons link
* Correct the itunes url
*Original:*
*New:*

Changes for the US subscribe landing page

---

assets/helpers/tracking/googleTagManager.js

Remove paymentRequestApi error logging.
Currently when google tag manager cannot access paymentRequestApi in a browser, it is sending a message to Sentry.
This message is being treated as an error and the wording of it makes it look like a problem with the payment api to the uninitiated.
This change will remove this logging as we won't take any action in response to it anyway.

Stop logging PaymentRequestApi errors to Sentry

---

assets/helpers/page/page.js
assets/helpers/page/pageActions.js

Prep for some other work I'm doing. This tidies up the page helper.
- Removed `PreloadedState` because it's unused.
- Removed `SET_COUNTRY_GROUP` because it's unused (it can be re-introduced if we need it).
- Switched to object spread in `commonReducer`.

Refactor Page Helper

---

assets/components/customerService/customerService.jsx

Add the correct contact number for the Australian digital pack product page so that customers can reach us if they need to! 
[**Trello Card**](https://trello.com/c/Tg4kTE1c/1858-update-phone-number-on-au-digital-pack-page)
* Add the correct contact number for the Australian digital pack product page
Current footer with incorrect number
With the number corrected (after this change is merged)

Update contact number for digital pack page for Australia

---

app/actions/CustomActionBuilders.scala

The old identity sign in endpoint, `/signin/start`, now redirects to `/signin` at the fastly level. This doesn't work locally, and `/signin` is the new, approved endpoint, so it makes sense to switch over now

Update identity sign in endpoint

---

assets/components/contributionsCheckout/contributionsCheckout.scss

Previosuly, if an error message went over 2 lines, the text struggled to fit in the box. This PR makes the box taller so that it can accomodate 2 lines. 
| Checkout Error Before | Checkout Error After |
|-----|------|
|![old](https://user-images.githubusercontent.com/2844554/44351329-8d289a00-a499-11e8-89ee-a1829e2b16d5.png)|![new](https://user-images.githubusercontent.com/2844554/44351327-8d289a00-a499-11e8-8a72-a8c257a2bea4.png)|
| Form Error Before | Form Error After |
|-----|------|
|![emailold](https://user-images.githubusercontent.com/2844554/44351476-dd9ff780-a499-11e8-9b2a-ab4e07de4b2d.png)|![newemail](https://user-images.githubusercontent.com/2844554/44351477-dd9ff780-a499-11e8-9448-835140c37732.png)|

Fix styling bug on error messages

---

assets/helpers/externalLinks.js
assets/helpers/flashSale.js

During a flash sale, it is useful to be able to set a custom value for the internal campaign code to more easily track the promotion in GA.
This adds that capability.
This does mean that there is a map of intcmp values that are valid during the flash sale that needs to be manually updated whenever we set up another flash sale if we are going to use a specific intcmp value for tracking.
The particular intcmp values specified in this PR relate to this flash sale: https://github.com/guardian/support-frontend/pull/850
[**Trello Card**](https://trello.com/c/3wVpGbeA/1751-voucher-home-delivery-flash-sale-updates)
* Particular products during a flash sale can now have a specific intcmp value. If there is one specified, it is used if the flash sale is live, otherwise the default value is used.

Custom intcmp values that are valid during a flash sale

---

assets/components/digitalSubscriptions/digitalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/components/paperSubscriptions/paperSubscriptions.jsx
assets/components/threeSubscriptions/threeSubscriptions.jsx
assets/helpers/externalLinks.js

Previously we have been losing any query params passed to the support site when we send the user on to subscribe. This is particularly problematic for 'utm' parameters which are used by marketing to attribute conversions to particular acquisition channels.
[**Trello Card**](https://trello.com/c/Qmg8Ml52/1865-utm-tracking-codes-are-not-passed-to-the-subscribe-site)
* Remove an unused `otherQueryParams` function parameter.
* Use URLSearchParams to pass on any query params we receive to the subs site.

Keep utm params

---

assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
assets/helpers/page/__tests__/pageTest.js
assets/helpers/page/page.js
assets/helpers/tracking/__tests__/acquisitionsTest.js
assets/helpers/tracking/acquisitions.js

This is in preparation for the pull request which will track Optimizie experiments in the data lake. When looking through this part of the code base with @Ap0c, we saw that support-frontend AB tests were getting added to the AB tests field of the referrer acquisition data ([reference](https://github.com/guardian/support-frontend/blob/master/assets/helpers/tracking/acquisitions.js#L185)). However, they are also passed down the component hierarchy and used to build the POST data requests for the various payment endpoints ([one-off Stripe](https://github.com/guardian/support-frontend/blob/master/assets/helpers/tracking/acquisitions.js#L216); [one-off Paypal](https://github.com/guardian/support-frontend/blob/master/assets/helpers/paymentIntegrations/payPalPaymentAPICheckout.js#L49); …

Acquisition data tidy up

---

assets/pages/contributions-landing/ContributionState.jsx
assets/pages/contributions-landing/newContributionsLanding.jsx

Moves the `Select your state` field into a separate component, so that it can be later hydrated with properties from the Redux store.
The state is static right now, as I'll address the wiring for everything at once.
[**Trello Card**](https://trello.com/c/Uq7ugIu1/782-npf-create-a-state-us-ca-component)

Payment Flow: Add `ContributionState`

---

assets/helpers/user/__tests__/__snapshots__/userReducerTest.js.snap
assets/helpers/user/__tests__/userReducerTest.js
assets/helpers/user/userReducer.js
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/__tests__/oneoffContributionsReducersTest.js
assets/pages/oneoff-contributions/oneOffContributionsReducer.js
assets/pages/oneoff-contributions/oneoffContributions.jsx
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/__tests__/regularContributionsReducersTest.js
assets/pages/regular-contributions/components/formFields.jsx
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributionsReducer.js

The user reducer starts off with its default state/province field blank, but when it's used on the checkouts we always set a default state anyway. This PR consolidates this initial state creation in the user reducer itself, which is where the other initial state values are set.
- Created a higher-order reducer for user. It now takes a country group and generates an initial state/province from that.
- Updated the one-off and recurring contribution checkouts to handle this change.
- Brought the tests into line and added a couple to cover this new functionality.

User Reducer Sets Default State

---

package.json

Updating the browser list read by Babel and PostCSS/autoprefixer to reflect our new [supported browser list](https://github.com/guardian/support-frontend/wiki/Supported-Browsers).
- Bumped `browserslist` in `package.json`.

Updated Supported Browser Versions

---

.prout.json
prout/seen.md

To raise awareness of the post deployment test code / results.
This should add a message to Prout's 'seen' PR comment. 
Here's an example of this on frontend: https://github.com/guardian/frontend/pull/20272#issuecomment-418347245
Feel free to edit seen.md directly within this PR if you want to customise the message further.
* Edit Prout config
* Add seen.md

Add post-deployment test links to Prout message

---

assets/components/gridImage/gridImage.jsx
assets/components/svgs/contributionsBgDesktop.jsx
assets/components/svgs/contributionsBgMobile.jsx
assets/pages/new-contributions-landing/contributionsLanding.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/new-thank-you/thankYou.jsx

The new design has a background with images inset into circles. We wanted these images to respect the user's device constraints, something SVG does not provide with the `image` element. There are two solutions for this:
- in CSS, using `image-set` (the syntax is similar to the `srcset` attribute)
- in HTML, using `<img srcset="...">` elements
I went for the latter because there is existing infrastructure; but ideally this should be moved into the CSS. Anyway, images are in the DOM and are set centred in the canvas, then offset either left or right using a translation.
At the moment I am using the same image all the time, but the ones provided by @Amohkhan should be inserted into the grid and used here, with appropriate sizes (the ones I used are random).
[**Trello …

Payment Flow: Positioning images in bubbles

---

app/controllers/OneOffContributions.scala
assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/contributionSelection/contributionSelection.jsx
assets/components/contributionsCheckout/contributionsCheckout.jsx
assets/components/yourContribution/yourContribution.jsx
assets/helpers/abTests/abtestDefinitions.js
assets/helpers/contributions.js
assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
assets/pages/oneoff-contributions/components/contributionsCheckoutContainer/contributionsCheckoutContainer.js

To make copy consistent prior to running another copy test. 
[**Trello Card**](https://trello.com/c/LbebbpdQ/723-change-one-off-one-time-to-single-globally-on-landing-pages)
* Removes two ab tests: US copy test and ROW copy test.
```
oneOffSingleOneTimeTestVariant: 'control' | 'single' | 'once' | 'oneTime' | 'notintest',
usOneOffSingleOneTimeTestVariant: 'control' | 'single' | 'once' | 'oneOff' | 'notintest',
```
* Sets copy language to  'single'. NB that code still refers to 'one-off'. 
@ionamckendrick 
 

one-off --> single

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/contributions-landing/containers/contributionPaymentCtasContainer.js
assets/pages/support-landing/components/contributionPaymentCtasContainer.js

This PR creates a test that sends half of the audience to the [(newly improved](https://github.com/guardian/support-frontend/pull/919)) guest checkout flow.
This is a rehash of [this test ](https://github.com/guardian/support-frontend/pull/826), with the better flow implemented

Turn on recurring guest checkout round two

---

assets/pages/new-contributions-landing/components/ContributionPayment.jsx
assets/pages/new-contributions-landing/components/ContributionState.jsx
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/components/ContributionType.jsx
assets/pages/new-contributions-landing/contributionsLandingReducer.js

I had delayed dealing with this until now, thinking it would require substantial changes, but I was wrong 😆 
- @ionamckendrick asked me to reverse the order of payment methods in anticipation of the paypal button change and set the default method to Stripe
- there is no need to store the selected state outside of the form itself
[**Trello Card**](https://trello.com/c/5oregpb2/833-npf-state-and-payment-method-selection)

New Payment Flow: payment method and state

---

assets/pages/oneoff-contributions/components/contributionsCheckoutContainer.js
assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/oneoff-contributions/components/marketingConsentContainer.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/helpers/checkoutForm/checkoutFormFieldsSelector.js
assets/pages/oneoff-contributions/oneOffContributionsReducer.js

There were some confusingly named types and some old practices being used in this file. The companion to #906.
- Renamed types for consistency with the rest of the codebase.
- Switched to object spread syntax.

Tidy up One-Off Contributions Reducer

---

assets/components/digitalSubscriptions/digitalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/components/paperSubscriptions/paperSubscriptions.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

We've shut down the tests, so all traffic now passes through the new landing pages. This PR eliminates the need for `clickEvents` used to record test participation.
[**Trello Card**](https://trello.com/c/yaceoeDS/1887-switching-subs-landing-pages-live)
N/A

Remove clickEvents from subs landing page

---

assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/regular-contributions/components/formFields.jsx

When we removed the email form field container in [this refactor ](https://github.com/guardian/support-frontend/pull/907), the logic to not show the email field if the user is singed in wasn't ported over. 
This PR reinstates that logic.

Don't show email field if user is signed in

---

assets/components/whySupport/whySupport.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

Adding an id to the why support section so that it becomes accessible via a fragment url `#why-support`.
[**Trello Card**](https://trello.com/c/vIDUGyxt/1910-add-why-support-anchor)
- Allowed pass-through props on "Why Support" section.
- Passed through id from subs landing page.

Added Id To Why Support Section On Subs Landing Page

---

assets/pages/oneoff-contributions/components/formFields.jsx

The firing of the `onBlur` event causes an issue when the event that fires the `onBlur` is the clicking of the stripe button Stripe button, as the dispatching of the `setShouldValidate` functions that we call in the `onBlur` causes a refresh of the page, and the `onClick` event of the Stripe button is lost, meaning the the user has to double click the button. We thought we had got around it by intercepting the event that causes the `onBlur`, and not dispatching the actions if it was the clicking of the Stripe button, but sadly this didn't work on Firefox and Safari. 
This PR removes the onBlur event for the one-off contributions, as the only reason we really needed it anyway was for the recurring contributions checkout and it's (soon to be deprecated) greyed-out buttons solution for …

Remove on blur from one off contributions stripe button

---

app/admin/Segment.scala
app/codecs/CirceDecoders.scala
test/codecs/CirceDecodersTest.scala

The Circe decoders for `Segment` and `SwitchState` (both sealed traits modelling an enum type) were never implemented correctly. We've gotten away with this because we only encode JSON from those types and don't decode it. But in the upcoming work to fetch settings from an external JSON file (on disk or in S3), we need to decode too.
So this implements the decoding correctly and adds some tests.

Fix Circe decoders for Segment and SwitchState

---

assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.scss
assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx
assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.scss
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.scss
assets/components/textInput/textInput.jsx
assets/helpers/checkoutForm/checkoutForm.js
assets/helpers/paymentIntegrations/payPalExpressCheckout.js
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/components/formFields.jsx
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/helpers/checkoutForm/__tests__/__snapshots__/checkoutFormReducerTest.js.snap
assets/pages/oneoff-contributions/helpers/checkoutForm/__tests__/checkoutFormActionsTest.js
assets/pages/oneoff-contributions/helpers/checkoutForm/__tests__/checkoutFormReducerTest.js
assets/pages/oneoff-contributions/helpers/checkoutForm/checkoutFormActions.js
assets/pages/oneoff-contributions/helpers/checkoutForm/checkoutFormFieldsSelector.js
assets/pages/oneoff-contributions/helpers/checkoutForm/checkoutFormReducer.js
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/components/contributionsGuestCheckoutContainer.jsx
assets/pages/regular-contributions/components/formFields.jsx
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/helpers/checkoutForm/__tests__/__snapshots__/checkoutFormReducerTest.js.snap
assets/pages/regular-contributions/helpers/checkoutForm/__tests__/checkoutFormActionsTest.js
assets/pages/regular-contributions/helpers/checkoutForm/__tests__/checkoutFormReducerTest.js
assets/pages/regular-contributions/helpers/checkoutForm/checkoutFormActions.js
assets/pages/regular-contributions/helpers/checkoutForm/checkoutFormFieldsSelector.js
assets/pages/regular-contributions/helpers/checkoutForm/checkoutFormReducer.js
assets/pages/regular-contributions/regularContributions.jsx
assets/pages/regular-contributions/regularContributions.scss

We had previously thought that we couldn't intercept the onClick events of the PayPal Express button, so we couldn't fire client-side validation on the click of the button. This lead to some rather horrible greyed out button validation on the recurring checkout, and lead to us implementing an overly complicated validation system.
That turned out to be incorrect, you can in fact intercept the onClick events of the PayPal Express button. 
Due to Regis' upcoming test, it almost seems pointless implementing this now, but for one reason. The  old validation fired the `setShouldValidate` functions for the form fields on the `blur` of the field, which was causing a weird bug where you had to click on the payment button twice. As we now can intercept the click of the paypal button, we can fire …

Use DOM validation on all checkout forms and remove greyed-out button validation

---

app/wiring/AppLoader.scala

If errors occur on app startup that prevent Play from starting, we don't see them in CloudWatch. That makes them very hard to debug.
This should let see these errors in CloudWatch so we can more easily debug failed deploys
We did something similar in the Payment API: https://github.com/guardian/payment-api/blob/master/src/main/scala/MyApplicationLoader.scala#L25-L33

Log errors on app startup

---

app/admin/Settings.scala
app/config/Configuration.scala
app/services/aws/AwsS3Client.scala
app/wiring/ApplicationConfiguration.scala
build.sbt
cloud-formation/cfn.yaml
conf/CODE.public.conf
conf/DEV.public.conf
conf/PROD.public.conf

Following on from #922 and #937
`switches` should no longer be set inside the Play config. Instead, the Play config must specify at least one of these (example values given):
```
adminSettingsSource.s3 {
bucket="support-frontend-admin-console"
key= "DEV/settings.json"
}
```
```
adminSettingsSource.local.path="~/.gu/support-frontend-admin-console/settings.json"
```
It will look for the `adminSettingsSource.local.path` config first. If not present, it will expect both `adminSettingsSource.s3.bucket` and `adminSettingsSource.s3.key`. If these aren't present, the app will not start up. Similarly the app will not start up if it's unable to fetch and decode the settings from the specified location.

Settings from file or s3

---

assets/pages/oneoff-contributions/helpers/ajax.js

Currently we are getting a spurious error after payment success in the dev-tools console and in Sentry
(Note: the user is taken to the thank-you page regardless and this error is not visible to the user unless they have their debugging tools open).
This change will stop us sending that error and also fix up the error handling so it is firing and logging correctly
This is an improved version of https://github.com/guardian/support-frontend/pull/920 that uses @Ap0c's branch instead.

Fix Sentry error reporting to remove spurious error and handle actual errors correctly

---

assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx

We have no need to set the disabled state on the buttons, as we are dealing with the clicks in the `onClick` handler. 
This was actually causing a bug whereby the stripe one-off button was loading is a disabled state, as on the first pageload there are no DOM elements to check the validity for, so `props.canOpen()`, which in this case looks in the DOM for the form and checks its validity, evaluates to false.

Don't set disabled state of buttons 

---

assets/pages/digital-subscription-landing/components/independentJournalismSection.scss

[**Trello Card**](https://trello.com/c/Gtgr11Kd/1920-cta-is-half-broken)

Fix a broken CTA on the digipack page

---

assets/components/paymentFailureMessage/paymentFailureMessage.jsx
assets/components/paymentFailureMessage/paymentFailureMessage.scss
assets/helpers/checkoutErrors.js
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/oneoff-contributions/__tests__/oneoffContributionsActionsTest.js
assets/pages/oneoff-contributions/__tests__/oneoffContributionsReducersTest.js
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/oneOffContributionsReducer.js
assets/pages/oneoff-contributions/oneoffContributionsActions.js
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap
assets/pages/regular-contributions/__tests__/regularContributionsActionsTest.js
assets/pages/regular-contributions/__tests__/regularContributionsReducersTest.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/helpers/ajax.js
assets/pages/regular-contributions/regularContributionsActions.js
assets/pages/regular-contributions/regularContributionsReducer.js

So that users who experience problems whilst attempting to sign up for a recurring contribution are given helpful advice, which is specific to their payment error (see also: #856 and #939).
There will be a follow up PR for one-off contributions, as this requires a corresponding change to the payment-api. For one-off, I've temporarily hardcoded a failure reason, regardless of the contents of the error.
[**Trello Card**](https://trello.com/c/aMt99CR2/1885-return-specific-errors-based-on-payment-failure-reason-client-side-work)
* Simplify logic for displaying payment failure error
* Rename a poorly named CSS class (which I missed in #939)
* Add mapping between checkout failure reasons and user-friendly error messages
* Store the checkout failure reason in the state, (hopefully) following the …

Show more helpful errors on failed checkout (recurring contributions)

---

app/controllers/PayPalOneOff.scala
app/services/PaymentAPIService.scala

Update so that we don't have to encode different errors in a nested data type i.e. `Option[Either[A, B]]`

Use EitherT and PaymentAPIResponseError for handling errors

---

assets/components/digitalSubscriptions/digitalSubscriptions.jsx
assets/components/internationalSubscriptions/internationalSubscriptions.jsx
assets/components/subscriptionBundle/subscriptionBundle.jsx
assets/components/subscriptionsByCountryGroup/subscriptionsByCountryGroup.jsx
assets/helpers/tracking/googleTagManager.js

We want to monitor the performance of the app store CTAs during the September marketing campaign
[**Trello Card**](https://trello.com/c/32QGic1Z/1876-add-app-nexus-for-september-campaign)
* Adds a new GTM event `AppStoreCtaClick` (note: it's the same event and tracking id for all the digipack app CTAs)
* Wires up the CTAs to fire the event on click
N/A

Apply click events for app store buttons

---

assets/pages/new-contributions-landing/components/ContributionTextInput.jsx

We don't currently need the option of displaying in input without an icon, and the ternary statement was cluttering up the code, so let's remove it.

Clean up Contributions Text Input component

---

assets/pages/new-contributions-landing/components/ContributionAmount.jsx
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionTextInput.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

Currently, we hold off on showing an error message on a form field until it has been blurred. This PR replaces this rule with a new rule that says that we can't show an error message until the form has been submitted once. This basically means that there is no live validation until the form has been submitted for the first time. 
The extra complexity (and boilerplate to maintain) that we get from having to store the blurred state of each field in the state is quite sizable, and arguably not an improvement on what this is PR is proposing. It is a simple form, let's simplify things.

[NPF] show errors on submit of form rather than on blur of fields

---

assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
assets/pages/new-contributions-landing/contributionsLanding.scss

Pointer cursor on submit and close buttons

---

app/admin/SettingsProvider.scala

For whatever reason, passing the underlying error as a second arg to `RuntimeException` means we don't get the message from it displayed (and, I assume, logged).
There may be a nicer way to do this - if so, let me know

Log the reason config could not be fetched

---

assets/pages/new-contributions-landing/components/ContributionForm.jsx

Previously, if as user was signed in, deleted the value of a form field, then clicked submit, the form would re-render with the original value of the form field back in place.
This was due to this bit of logic (I'll use first name as an example):
```firstName: state.page.form.formData.firstName || state.page.user.firstName,```
Because `state.page.form.formData.firstName` was evaluating to false when it was an empty string, it was defaulting back to the value from the user state. We now only default to the user state if the field is `null`,  which is what it is initialised as. 
This was only a problem for the text input fields, as it is not possible to set the State box to an empty value anyway, so that has remained unchanged.
We can also get rid of the `maybeDispatch` function, as it …

Fix form fields bug

---

assets/helpers/paymentIntegrations/readerRevenueApis.js
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

In order to create a password on the thank you page, we need to read the guestAccountRegistrationToken from the response from the call to `/contribute/recurring/create` and store it in the state. 
[This PR](https://github.com/guardian/support-frontend/pull/962) did the same thing for the old payment flow, this implements the same logic for the NPF. 
@regiskuckaertz @joelochlann @tsop14 @Mullefa

[NPF] Read and propagate guest account registration token to thank you page for NPF

---

assets/components/directDebit/directDebitActions.js
assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx
assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx
assets/helpers/checkouts.js
assets/helpers/paymentIntegrations/newStripeCheckout.js
assets/helpers/paymentIntegrations/payPalExpressCheckout.js
assets/helpers/paymentIntegrations/readerRevenueApis.js
assets/helpers/paymentIntegrations/stripeCheckout.js
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionPayment.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
assets/pages/oneoff-contributions/helpers/ajax.js
assets/pages/regular-contributions/__tests__/ajaxTest.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx
assets/pages/regular-contributions/helpers/ajax.js

This replaces `RegularCheckoutCallback`:
```javascript
export type RegularCheckoutCallback = (	
token?: string,	
accountNumber?: string,	
sortCode?: string,	
accountHolderName?: string	
) => Promise<*>
```
with `PaymentAuthorisation => void`. `PaymentAuthorisation` is a union type which looks like this:
```javascript
export type StripeAuthorisation = {| paymentMethod: 'Stripe', token: string |};
export type PayPalAuthorisation = {| paymentMethod: 'PayPal', token: string |};
export type DirectDebitAuthorisation = {|
paymentMethod: 'DirectDebit',
accountHolderName: string,
sortCode: string,
accountNumber: string
|};
export type PaymentAuthorisation = StripeAuthorisation | PayPalAuthorisation | DirectDebitAuthorisation;
```
This is because the new payment flow uses the `PaymentAuthorisation …

Standardise and clarify payment callbacks

---

app/controllers/Application.scala
app/controllers/IdentityController.scala
app/controllers/OneOffContributions.scala
app/controllers/PayPalOneOff.scala
app/controllers/RegularContributions.scala
app/models/identity/UserIdWithGuestAccountToken.scala
app/models/identity/requests/CreateGuestAccountRequestBody.scala
app/models/identity/responses/GuestRegistrationResponse.scala
app/models/identity/responses/UserResponse.scala
app/services/HttpIdentityService.scala
app/services/StubIdentityService.scala
app/wiring/Services.scala
test/controllers/ApplicationTest.scala
test/controllers/OneOffContributionsTest.scala
test/controllers/RegularContributionsTest.scala

As part of the work to set the password for guest accounts in support frontend, I needed to create some case classes to model the responses from the API. `HttpIdentityService.scala` was the previous dumping ground for these models, and rather than add to it I decided to refactor it a bit to put the models in their own files. So as not to clutter up that PR with too many changes, I'm making this change in a separate PR. 
Note: this is just moving things around, not implementing anything new, so any concerns about the functionality etc will be noted and potentially raised in another PR, but not addressed in this one.
| New file structure |
|---------|
|![image](https://user-images.githubusercontent.com/2844554/45955959-46364300-c009-11e8-9383-05fa0be13ea1.png)|

Refactor identity service models

---

test/selenium/util/Config.scala
test/selenium/util/DriverConfig.scala

These are small changes to facilitate the moving of our post deploy automated tests to Browserstack.

Move tests to browserstack

---

assets/helpers/__tests__/checkoutsTest.js
assets/helpers/checkouts.js
assets/helpers/settings.js
assets/pages/new-contributions-landing/components/ContributionPayment.jsx
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/contributionsLanding.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js
assets/pages/regular-contributions/helpers/ajax.js
assets/pages/regular-contributions/regularContributions.jsx

If a payment method is switched off, we need to make sure we do 3 things:
1) Hide that payment option somehow (not part of this PR)
2) Ensure that the next preferred payment option's radio button is selected 
3) Ensure that the payment button is set up to the correct payment method
Previously, we were initialising the `paymentMethod` state to `Stripe`. For starters, we have different preferred payment methods depending on the Region and Payment Type (DD is prefferred for UK recurring, for example), so this was never going to be correct for all cases anyway. 
Therefore, this PR introduces an init function which is called after the `store` is created in `contributionsLanding.jsx`. In this function, we look at the state of the switches, and set the appropriate payment method (this will …

Select the correct initial payment method depending on state of payment method switches

---

app/views/main.scala.html
assets/helpers/tracking/googleTagManagerScript.js

Currently we have a server side 'do not track' check, this probably will not behave correctly for pages that are cached so this PR moves the check to the client side.
[**Trello Card**](https://trello.com/c/XOMsQJKV/1903-fix-tracking-move-gtm-do-not-track-check-client-side)

Client side do not track check to avoid problems with cached pages

---

assets/helpers/tracking/googleTagManager.js

I am updating our tracking to use Ophan's browser ID as the [GA User Id](https://support.google.com/analytics/answer/3123663) which will make it easier to join up our view of the user across support-frontend, subscribe-frontend and server side conversion tracking.
In doing this I'm following the [advice for Google Tag Manager](https://support.google.com/tagmanager/answer/4565987?hl=en) to set this from a cookie. This means that we can also set the custom dimension that we previously set from the datalayer directly from the cookie as well and so this line is no longer needed.
[**Trello Card**](https://trello.com/c/AfmLDoqa)

Set `ophanBrowserId` directly from the cookie

---

assets/components/priceCta/priceCta.jsx
assets/components/priceCta/priceCta.scss
assets/pages/digital-subscription-landing/components/ctaSwitch.jsx
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
assets/pages/digital-subscription-landing/helpers/promotions.js

Puts the digital pack price in large copy section at the top of the digital product page. Also applies some minor design tweaks for consistency.
[**Trello Card**](https://trello.com/c/HT1d8JwT/1936-add-pricing-and-cancellation-info-back-into-digital-pack-product-page)
- `PriceCta` allows optional secondary copy, which includes cancellation info on digital product page.
- Tweaked copy on CTA and adjusted size to match.
- Aligned some colours with the palette.
- Updated heading copy to include trial and price information.
- Flipped the "Digital Pack" copy to an `<h1>`.

Put Price In Digital Page And Tidy Up

---

assets/helpers/checkouts.js
assets/pages/new-contributions-landing/components/ContributionPayment.jsx

So users do not see invalid payment methods. 
As we are hiding radio buttons for invalid payment methods, rather than displaying a fallback element, we do not need to use the switchable wrapper.
TODO: When all payment methods are switched off we need to surface a messgae to the user. Currently, when a payment methods is switched off the radio button still shows, so this PR is an improvement despite this todo. 
[**Trello Card**](https://trello.com/c/A3xl1tTo/891-npf-buttons-should-be-switch-controlled)
* Uses `getValidPaymentMethods` function to map over and render payment method buttons. This function filters out switched off buttons, ensuring these are not shown to the user. 
* No longer exports `getPaymentMethods` as this is no longer used outside checkout.js

uses valid payments methods for rendering

---

assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

If the user is signed in, we want to initialise the email, first name and last name of the form data with the values from the user state. This PR fixes a bug whereby the fields were being filled from the user state but the form state wasn't being set with these values, meaning that payments weren't working for signed in users.

Initialise form data from user state

---

app/codecs/CirceDecoders.scala
app/controllers/IdentityController.scala
app/models/identity/CookieResponse.scala
app/services/HttpIdentityService.scala
app/services/StubIdentityService.scala
conf/routes

Currently I'm working on adding the ability for users to set a password post-recurring payment in the guest checkout flow. I'm approaching the Regis way, getting this work out bit by bit rather than in one huge PR, so this PR just deals with the backend.

Add /contribute/set-password-guest endpoint 

---

assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionTextInput.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

From the Trello card: _"On the old flow, we didn't allow signed in users to change their email address. We need to implement the same thing on the new flow, else we will end up in a world of trouble."_
[**Trello Card**](https://trello.com/c/V5fLc8jq/894-npf-dont-allow-signed-in-users-to-change-their-email-address)

Prevent logged in users from changing their email address

---

app/models/identity/CookieResponse.scala
app/services/HttpIdentityService.scala

Turns out that `withHttpHeaders` replaces the headers in the request, meaning that the Authentication header was being overridden . We want `addHttpHeaders`
also a small formatting bug fix

[NPF] Fix authentication bug in set-password endpoint

---

assets/components/featuredDigitalPack/featuredDigitalPack.jsx
assets/components/subscriptionsByCountryGroup/components/digitalPack.jsx
assets/components/subscriptionsByCountryGroup/components/digitalSection.jsx
assets/components/subscriptionsByCountryGroup/components/featuredProductTest.jsx
assets/components/subscriptionsByCountryGroup/components/paperSection.jsx
assets/components/subscriptionsByCountryGroup/components/weekly.jsx
assets/components/subscriptionsByCountryGroup/subscriptionsByCountryGroup.jsx
assets/helpers/externalLinks.js
assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
assets/helpers/page/__tests__/pageTest.js
assets/helpers/subscriptions.js
assets/helpers/theGrid.js
assets/helpers/tracking/__tests__/__snapshots__/acquisitionsTest.js.snap
assets/helpers/tracking/__tests__/acquisitionsTest.js
assets/helpers/tracking/acquisitions.js
assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx
assets/pages/premium-tier-landing/components/priceCtaContainer.jsx
assets/pages/support-landing/components/subscriptionsSection.jsx

To support the changes in #980, we need to make sure AB test information is correctly being recorded.
Also brings the `ReferrerAcquisitionData` type into line with how it's defined in other places. It now has an `abTests: ?AcquisitionABTest[]` field instead of an `abTest: ?AcquisitionABTest` field. Dotcom still only has a single `abTest` field AFAIK (@jranks123 @Mullefa ?), so support-frontend will now translate that into an array. It should also handle any `sessionStorage` copies of `ReferrerAcquisitionData` through the same mechanism.
[**Trello Card**](https://trello.com/c/1Z71dBIk/1925-reinstate-click-events-and-add-optimize-participations-for-subs)
- Changed `ReferrerAcquisitionData` to have an `abTests` field.
- Reinstated Ophan and GA click events for products on the subs landing …

Click Events And Optimize Participations

---

assets/helpers/__tests__/checkoutsTest.js
assets/helpers/checkouts.js
assets/pages/new-contributions-landing/components/ContributionType.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

Previously, if you changed the contribution type, for example from `Monthly` to `Single`, the payment type didn't change. 
Allow me to illustrate with an example. If you were on the UK page and `Direct Debit` was selected on the `Monthly` tab and then you changed to `Single`, the payment button would still be the `Direct Debit` button and none of the radio buttons would be selected (as Direct Debit isn't a valid payment option for Single contributions), when in fact the button should be the `Stripe` payment button and the credit card radio button should be selected.
This PR fixes this issue. 
@joelochlann @regiskuckaertz

When changing contribution type, select the correct payment type 

---

assets/components/otherProduct/otherProduct.jsx
assets/components/patronsEvents/patronsEvents.jsx
assets/components/patronsEvents/patronsEvents.scss
assets/helpers/externalLinks.js
assets/helpers/theGrid.js

**Do not merge until updated patrons link is available**
Keeping the [UK landing page](https://support.theguardian.com/uk) up to date 😎 
[**Trello Card**](https://trello.com/c/JPU3c6Zj/1868-update-patrons-link-copy-and-image-on-showcase-page-to-reflect-new-patrons-scheme)
On the UK landing page, patrons section
* Update the CTA link
* Update the copy
* Update image
| **mobile**  | **tablet**           | **web**   |
| ------------- |:-------------:| -----------|
| <img src="https://user-images.githubusercontent.com/3072877/46356112-f800ef80-c659-11e8-8f10-1067ea1a73c1.png" alt="updates for, mobile" height="200"/>  | <img src="https://user-images.githubusercontent.com/3072877/46356030-d6076d00-c659-11e8-87c7-393b7baa55c1.png" alt="updates for, tablet" height="200"/>  | <img …

Update patrons image, link and copy

---

assets/helpers/page/page.js
assets/helpers/tracking/awin.js

Now that we are redirecting subscribe traffic to the support site, the affiliate tracking is getting lost which will lead to errors in attribution. This PR makes sure that we store the referrer in a cookie readable on subs when users first arrive on our site.
[**Trello Card**](https://trello.com/c/vEW5B56Q/1905-add-awin-to-support-frontend)

Drop a cookie to track Awin affiliate referrals

---

assets/helpers/__tests__/formValidation.js
assets/helpers/formValidation.js
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/SetPassword/SetPassword.jsx
assets/pages/new-contributions-landing/formValidation.js

To surface an error when the payment amount is invalid. Currently amounts with more than two decimals prevent a user from proceeding to the next step in the payment flow but doesn't warn them that the Other amount field is the badun. 
[**Trello Card**](https://trello.com/c/iJoiL98o/13-nfp-validation-on-other-amount-field)
* Adds custom verification on Other payment amount to check that no more than two decimals are used.

Em decimal check

---

assets/components/subscriptionBundles/appCtaTracking.js
assets/components/subscriptionBundles/dailyEdition.jsx
assets/components/subscriptionBundles/premiumTier.jsx
assets/components/subscriptionsByCountryGroup/components/digitalSection.jsx

We need two different tracking events to occur when app store links are clicked:
1. Standard Google Analytics CTA click tracking which allows us to analyse the proportion of clicks to each CTA.
2. AppNexus pixel tracking to allow us to track the success of programmatic campaigns across Subscriptions and Support.
Previously we only had the second of these on our app store CTAs, this PR adds the first as well.
[**Trello Card**](https://trello.com/c/aXN0q1Da/2000-reinstate-click-tracking-for-app-clicks-on-subscriptions-landing-pages)
Wrap the two tracking calls in a wrapper method and call this from the Premium tier and Daily Edition CTAs

Merge appstore link tracking

---

assets/helpers/theGrid.js

Making sure that the GW packshot is up to date. 
[**Trello Card**](https://trello.com/c/foFBaXcd/1985-update-guardian-weekly-image-on-support-based-on-switch-status)
* Updates the GW packshot on the subs pages.

GW packshot update

---

assets/components/paymentFailureMessage/paymentFailureMessage.scss
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

Deal with error responses from Payment API by exiting "Processing Transaction" state and displaying payment error message. 
[**Trello Card**](https://trello.com/c/WCt3abmA/15-npf-error-responses-from-payment-api-are-not-handled-page-hangs-in-processing-transaction-state)
* Adds and initialises paymentError in reducer
* Updates actions to also set `isWaiting` to false when a payment error is returned. 
* Moves `paymentErrorMessage` component to above the payment button.
* Updates CSS to remove width when component appears in NPF.

Em payment error

---

webpack.common.js

Webpack doesn't accept `false` as a plugin, this switches to spreading with an empty array instead.
- Switched to array spread syntax with empty array instead of false.

Fix CSS Minification In Dev

---

assets/components/subscriptionBundles/weekly.jsx

Because it's a glorious magazine now, not a newspaper.
[**Trello Card**](https://trello.com/c/S7PAob3t/2010-update-product-copy-for-gw-on-all-subscriptions-landing-pages)
* See that word 'newspaper' on the Guardian Weekly copy? That's 'magazine' now, thank you very much. End of.
**Before:**
**After:**

Update newspaper -> magazine for Weekly

---

assets/helpers/contributions.js
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionPayment.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js

Unfortunately two missing `...`s broke the recurring payment methods: https://github.com/guardian/support-frontend/blob/master/assets/pages/new-contributions-landing/components/ContributionForm.jsx#L187-L188. The empty functions in the base handlers were not being overridden so we got a silent failure! Bad.
Using exact types for `PaymentMethodMap`, `ContributionTypeMap` and `RegularContributionTypeMap` would've been enough to catch this. But it's made me decide that it's clearer to just be explicit about what we're declaring in each one and not mix in`baseHandlers`. It's a bit more repetitive but it means you can see at a glance what it's doing in each case rather than figuring out what's overriding what etc.
**Note:** we need to use spread syntax rather than an intersection type when …

Exact types for PaymentMatrix and no more baseHandlers

---

assets/components/subscriptionBundles/dailyEdition.jsx
assets/components/subscriptionBundles/premiumTier.jsx
assets/components/subscriptionsByCountryGroup/components/digitalSection.jsx
assets/components/subscriptionsByCountryGroup/components/internationalSection.jsx
assets/helpers/__tests__/externalLinksTest.js
assets/helpers/externalLinks.js
assets/pages/digital-subscription-checkout/components/appsSection.jsx
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx

Apple's app store defaults to US, and therefore US dollars, unless given a hint at the user's location. We can pass that through (after translating it into one of Apple's known values).
[**Trello Card**](https://trello.com/c/fX63xBuy/2005-add-region-country-into-ios-app-store-link)

Use ideal country code in Apple app store links where possible

---

assets/components/introduction/investIntroduction.scss

Reducing the height of the top highlight on the subs landing page.
- Reduced the padding and the corresponding `top` gaps.
### After

Reduce Highlight Size

---

assets/pages/regular-contributions/components/formFields.jsx

Brings it in line with the country dropdown.
[**Trello Card**](https://trello.com/c/WoeHpIVT/1890-make-state-dropdowns-controlled-inputs)
- Passed state field into form and used it to set `selected` on the state `<options>`.

Make State Dropdown A Controlled Input

---

assets/pages/new-contributions-landing/contributionsLandingActions.js

When the one-off paypal contribution form is submitted, it briefly and incorrectly displays an error message before navigating to paypal.
[**Trello Card**](https://trello.com/c/jkv5OUHs/97-npf-an-error-message-is-always-briefly-displayed-when-submitting-the-on-off-payment-form)

Stop showing error message after successful paypal payment creation

---

build.sbt

https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31507
We are pulling in old versions of jackson-databind primarily via aws-sdks. It's suggested here that overriding jackson-databind shouldn't be a breaking change. Indeed, when running the project locally after the version bump, that seems to be the case.
We are also pulling in an old version of jackson-databind to support sign in.
I bumped the version, signed in with a test user, then signed up for a recurring contribution and saw it in zuora and that worked fine running locally. 
Any other suggested checks?
[**Trello Card**](https://trello.com) // none. Inspired by Snyk.
* Bumped jackson-databind and jackson-annotations to 2.9.7
n/a; just needs to preserve existing behaviour.

Bump jackson-databind and jackson-annotations to 2.9.7

---

app/views/oneOffContributions.scala.html

In order to display marketing permissions on the thank you page for paypal one off contributions, we need to read the email from the flash session.

Read email from flash session 

---

assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

We want to guarantee that the email will be available on the thank you page, so that we can use it to set marketing permissions. 
This PR:
. sets a session cookie as the user is typing in their email
. Initialises `state.page.form.formData.email` with the value from the session, if available
This means that even if the user refreshes the thank you page, or if they had to get there via the one off paypal site, the email will be available in the state.

Ensure that the email is available in the state on the new thank you page 

---

assets/helpers/checkouts.js
assets/helpers/contributions.js
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionPayment.jsx
assets/pages/new-contributions-landing/components/PaymentMethodSelector.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

So the NPF works for Stripe one-off. 
[**Trello Card**](https://trello.com/c/41e5ijeC/76-npf-stripe-does-not-switch-between-recurring-one-off-keys-when-changing-tabs-this-means-stripe-one-off-is-broken)
* Renames `paymentHandlers` to `thirdPartyPaymentLibraries` because that is what they are! 
* Adds extra dimension to thirdPartyPaymentLibraries as Stripe one-off is different from recurring. Uses PaymentMatrix to ensure all combinations are covered! 
* Moves initialization of these libraries out of the render function and in to `contributionsLandingInit`.
* Initialises all libraries on page load (rather than when the tab / payment option is selected)
* No longer initialises with the matrix as the majority of combinations did not require action, instead uses a humble if statement to …

initialise third party payment libraries

---

assets/components/svgs/subscribed.jsx
assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/components/marketingConsent.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/new-contributions-landing/contributionsLandingReducer.js
assets/stylesheets/gu-sass/colours.scss

Enables the 'Sign me up' button on the new thank you page.
Uses the same `confirmOptIn` state as the existing implementation, but in a new scope.
[**Trello Card**](https://trello.com/c/vKWRd715/11-npf-thank-you-page-wire-up-marketing-permissions)

Enable marketing subscription on the new thank you page

---

assets/helpers/tracking/googleTagManager.js

To prevent a type error. 
If `doNotTrack` is set on `navigator` or `window`, e.g. in Firefox private session, then [googleTagManager init](https://github.com/guardian/support-frontend/blob/master/assets/helpers/page/page.js#L72) is not called. This means that `window.googleTagManagerDataLayer` is undefined. 
When a user clicks on ctas it triggers `gaEvent`, e.g. clicking on 'Find Out More' for the Digital pack. This pushes details to `window.googleTagManagerDataLayer` which results in a type error if `window.googleTagManagerDataLayer` is undefined. 
We've had 2.2k sentry errors since October due to `Cannot read property 'push' of undefined`.  This should prevent some of them. 
* Checks `window.googleTagManagerDataLayer` exists before trying to push to it.

checks array is defined before pushing

---

assets/pages/new-contributions-landing/components/SetPassword/SetPasswordForm.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

If there is a server-side error after a user enters a password, it needs to display an error message in the same page.
[**Trello Card**](https://trello.com/c/Rl2eyHuG/103-npf-show-error-message-if-set-password-fails)

Display error message if signup fails

---

assets/components/countdown/countdown.jsx
assets/components/flashSaleCountdown/flashSaleCountdown.jsx
assets/components/flashSaleCountdown/flashSaleCountdown.scss

Adds a styled component for the flash sale countdown. It's not implemented anywhere on the site yet, this is just the styles in isolation.
There's also a small fix in `Countdown.jsx` to render `00` instead of `0`
[**Trello Card**](https://trello.com/c/OPrDKDBQ/2027-countdown-timer-for-flash-sales)

Styled flash sale countdown component

---

assets/helpers/details.js

To fix the country selector in browsers that do not support `<details>`, such as IE 11, Edge 17, and older versions of FF. (note, supported browsers are listed in the [wiki](https://github.com/guardian/support-frontend/wiki/Supported-Browsers)). 
Currently, the polyfill checks `instanceOf HTMLDetailsElement` which results in a typeError and prevents `toggleDetailsState` being successfully called. 
* Check parent is a details tag by using name.
I've tested this on Edge and Firefox using BrowserStack Local but I cannot get local version running on IE inside BrowserStack.

removes instanceOf check in details polyfill

---

assets/pages/new-contributions-landing/components/ButtonWithRightArrow.jsx
assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

* Fix link to the Gu on thank you page. 
* Uses `CtaLink` for link on thank you page
* Removes optional url from `ButtonWithRightArrow`. This elem is used twice on the password setting thank you page. One submits the form if a password is being added, the other uses the onclick function passed through to redirect to the next thank you page. As neither use `url`, this property can be removed.

thank you button fix

---

assets/pages/new-contributions-landing/contributionsLanding.scss

So an IE user can click on the downward arrow and open the country selector (expected behaviour).
Currently the details will open if you click around the svg but not on it... 
* Use css trick from [here](https://stackoverflow.com/questions/24078524/svg-click-events-not-firing-bubbling-when-using-use-element).  Which says:
> The element is never the target of mouse events; however, mouse events may target its descendant elements if those descendants have pointer-events set to some other value. In these circumstances, mouse events will trigger event listeners on this parent element as appropriate on their way to/from the descendant during the event capture/bubble phases.

fix click on country selector svg

---

assets/components/featuredDigitalPack/flashSaleDigitalPack.jsx
assets/components/subscriptionsByCountryGroup/subscriptionsByCountryGroup.jsx
assets/pages/subscriptions-landing/subscriptionsLanding.jsx

SHows the header in all regions, makes the currency match
[**Trello Card**](https://trello.com/c/RslWVV0m/2030-add-featured-product-section-with-flash-sale-info-to-international-subs-landing-pages)

Show ✨flash sale✨ header on all regions of the DP page

---

assets/pages/subscriptions-landing/subscriptionsLanding.jsx

The "Ready to Support" link on the subs landing page is broken. This updates it to point to the top of the page.
- Updated link to point to `#top`.

Subs Landing Ready To Support Link Points To Top

---

assets/components/directDebit/directDebitForm/directDebitForm.jsx
assets/helpers/page/page.js
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
package.json
yarn.lock

Keeping flow up-to-date and fixing errors.
- Bumped flow to 0.83.0.
- Explicitly returned `null` from components in places where `undefined` was being implicitly returned.
- Stopped trying to annotate `storeEnhancer` function, allowing flow to do it implicitly now.
- Removed some props in `ContributionSubmit` that weren't being used (@joelochlann @jranks123 ESLint thinks they aren't and I think it's right, can you confirm?).

Bump Flow to 0.83.0

---

assets/pages/digital-subscription-landing/components/productBlock.jsx

To make it clear that the Daily Edition is the UK newspaper so that customers in regions other than the UK understand that they won't be getting localised content.
[**Trello Card**](https://trello.com/c/wafP19z3/2036-tiny-copy-update-for-international-digital-pack-product-pages)

Different Digital Pack product copy for non-UK markets

---

assets/components/contributionSelection/contributionSelection.jsx
assets/helpers/abTests/abtestDefinitions.js
assets/helpers/abTests/helpers/annualContributions.js
assets/helpers/contributions.js
assets/pages/contributions-landing/containers/contributionSelectionContainer.js
assets/pages/contributions-landing/contributionsLanding.jsx
assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
assets/pages/new-contributions-landing/components/ContributionAmount.jsx
assets/pages/new-contributions-landing/contributionsLandingReducer.js
assets/pages/support-landing/components/contributionSelectionContainer.js
assets/pages/support-landing/supportLanding.jsx

A third test for annual contribution amounts.
All users will see the annual contribution option. There are 2 variants.
Some of the code in `annualContributions.js` is quite hacky to support the old payments flow, which we will hopefully remove soon.
In future we will build a tool to make these tests much easier to configure.
[**Trello Card**](https://trello.com/c/gQMjG2Om/92-amounts-test-annual-contribs-round-3-ad-hoc)

Annual contribution amounts test 3

---

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

I noticed we have a wrapping problem on the US digipack page, this fixes it:

Fix the wrapping of the title on the Digital Pack US page

---

assets/components/featuredDigitalPack/flashSaleDigitalPack.scss

it looks wrong right now in prod
This is the fixed one:

Add back padding on mobile hero for DP sale

---

assets/pages/new-contributions-landing/components/ContributionBackground.jsx

There was a visual bug whereby the circles were getting in the way of the copy in the header on mobile. To keep things simple (and for expediency), we are going to remove the circles from the header for now.
Before:
After:
This affects all the pages of the thank you flow (set password and thank you)

Remove circles svg from mobile on thank you page

---

test/selenium/OneOffContributionsSpec.scala
test/selenium/util/PayPalCheckout.scala

This test is very unreliable and it wastes a lot of time. 
It fails so regularly that it undermines confidence in the post-deployment tests in general.
We already have fairly sensitive alerting for this functionality (https://github.com/guardian/payment-api/blob/master/src/main/resources/cloud-formation.yaml#L430-L447), so I don't think we introduce too much risk by deleting this test.
We may need to delete the recurring PayPal test too (for the same reasons), but apparently this test is the most flakey, so let's try getting rid of it first.
[**Trello Card**](https://trello.com/c/JXk7kxGp/2021-delete-paypal-one-off-acceptance-test)
* Delete unreliable test
* Delete unused PayPal method
* Fix name of remaining one-off scenario

Delete unreliable post-deployment test

---

assets/components/featuredDigitalPack/flashSaleDigitalPack.jsx
assets/helpers/flashSale.js
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

So we can ab test the countdown timer on pages.
[**Trello Card**](https://trello.com/c/CqQGZXfR/2029-setup-a-b-test-for-countdown-timer-vs-no-countdown-timer)
* add a `?ab_timer=variant` parameter to both pages

Make the countdown test a redirect test

---

assets/components/directDebit/directDebitForm/sortCodeInput.jsx

So that you get the keyboard with just numbers on your phone! Will quadruple our mobile conversion rate, obvs...
| Before  | After |
| ![img_9c9c52d74002-1](https://user-images.githubusercontent.com/5122968/47534704-4d729a00-d8b0-11e8-8508-24699cb6ccfa.jpeg)  | ![img_0035](https://user-images.githubusercontent.com/5122968/47518192-2a30f600-d882-11e8-86b6-cec8f2e31cbd.PNG)  |

Treat sort code as numeric in browser form

---

assets/components/featuredDigitalPack/flashSaleDigitalPack.scss

Fixes a couple display issues related to the timer band being too long

Fix the countdown timer

---

assets/helpers/abTests/abtest.js
assets/helpers/abTests/helpers/annualContributions.js
assets/helpers/contributions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js

Currently the default annual amount is initialised with the control values.
This change updates the selected annual amount once the variant name is known
control:
variant:

Set default annual value in new payment flow

---

assets/pages/new-contributions-landing/contributionsLanding.scss

This PR hides the header background `div` on mobile, meaning that the body is brought up to the text.
This also makes the header block yellow on mobile, for landing and thank you pages. 
@ionamckendrick what do you think?
|Landing page Before| Landing page after |
|------|------------|
|![image](https://user-images.githubusercontent.com/2844554/47516354-29e22c00-d87d-11e8-982b-ceb6122f7c66.png)|![image](https://user-images.githubusercontent.com/2844554/47665189-79d03400-db98-11e8-96e1-9baf50e406ae.png)|
|Thank you page before| Thank you page after |
|------|----------|
|![image](https://user-images.githubusercontent.com/2844554/47516647-e5a35b80-d87d-11e8-893d-9dde27e9c455.png))|![image](https://user-images.githubusercontent.com/2844554/47517157-38c9de00-d87f-11e8-9638-b2e787eef55c.png)|

Rejig the circle-less header on mobile

---

assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

So the user sees the correct thank you message when using PayPal (and if they refresh the thank you page). 
[**Trello Card**](https://trello.com/c/K3kS9w2E/125-npf-bug-after-paypal-one-off-conversion-the-thank-you-page-says-thank-you-for-your-direct-debit)
PayPal flow redirects away from the site. When it routes to the thank you page the contribution type and payment method are incorrect as they default to Direct Debit and monthly. This is also true if you refresh the page.
* sets `paymentMethod` and `contributionType` in session storage on update action. 
* sets initial `contributionType` value (in reducer) from session if available. 
* sets initial `paymentMethod` value (in landing init) from session if available and a valid payment method. 
Example of PayPal one-off contribution: …

Set paymentMethod and contributionType in session storage & use to determine correct Thank You message

---

assets/helpers/checkoutForm/__tests__/checkoutFormTest.js
assets/helpers/checkoutForm/checkoutForm.js
assets/helpers/formValidation.js

Our email regex wasn't actually working. For example, the email `test@guuuuuuuuuu` was coming back as valid. We did have a test for `test@gu` but for the regex to fail there had to be 3 or more letters after the `@`.
I searched the play docs for the email regex that we supposedly were copying from (the link was broken) and found it and re-copied and pasted it in, and wrote a test that was failing before but now works

Fix email regex

---

app/controllers/Application.scala
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionFormFields.jsx
assets/pages/new-contributions-landing/components/MustSignIn.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
conf/routes

- remove dummy endpoint
- use new identity endpoint 
- Check email is valid before calling identity API
- Don't submit form unless email doesn't have a password (all recurring payment types bar paypal) 
- Don't block one-off contributions 
- Call identity API on init 
- Don't show error message until form has been submitted

Check email is valid before calling identity API, and don't submit form unless email doesn't have a password

---

assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/contributionsLandingReducer.js

What it says on the tin, plus I renamed `hasSeenDirectDebitThankYouPageCopy` to `hasSeenDirectDebitThankYouPageCopy` to keep it consistent with what we call the prop in the thank you page component

Add compliant DD copy to thank you page

---

assets/components/otherProduct/otherProduct.jsx

Only use 500 and 140 width crops as some images (specifically the patron image) do not have 1000 width crops and so the request 404s and the image renders as the alt text.

update Grid crop sizes

---

assets/helpers/checkoutForm/checkoutForm.js
assets/helpers/identityApis.js
assets/helpers/paymentIntegrations/newPaymentFlow/payPalRecurringCheckout.js
assets/pages/new-contributions-landing/components/ContributionAmount.jsx
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionFormFields.jsx
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/components/MustSignIn.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js

This PR enables/disables the PayPal button according to the validity of form and the type of account belonging to the email address entered by the user. 
There is only one edge case bug _i think_. This is where the user goes from typing a valid email that doesn't have a password, then clicks directly onto the payment button. In this instance, the user has to double click. But this is unexpected behaviour due to the order of the buttons, and is something we are begrudgingly willing to accept.

Paypal button enables/disables correctly according to validity of form and the User Type

---

assets/components/featuredProductHero/featuredProductHero.jsx
assets/components/featuredProductHero/featuredProductHero.scss
assets/pages/subscriptions-landing/components/featuredProductAb.jsx
assets/pages/subscriptions-landing/components/featuredProducts.jsx
assets/pages/subscriptions-landing/components/flashSaleDigitalPack.jsx

Continues #1101 . This sets up a component to render the three possible variants for the featured product AB test in `FeaturedProductHero` and makes it change text colours based on the product.
We are missing images & final copy but adding those should be a super minor PR compared to this which is the major code-related work
There are no user-facing changes as the component is not rendered from anywhere (Plan is for it to replace the flash sale hero currently in place) but to throw in a quick visual this is how the current state (missing final copy & images & a designer to go over the colours) looks like for GW if it were to be rendered:

Featured product test AB setup

---

assets/helpers/abTests/abtest.js
assets/helpers/abTests/abtestDefinitions.js

So users are assigned to the correct variant for npf test. 
For previous ab tests, we determine a user's test variant client side. Because the new payment flow is running as a server side test, users have already been allocated to a variant and we need to ensure this value is respected. 
The variant value is:
* Set in local storage
* Used for ophan tracking
* We plan to set a  [`gu.serverside.ab.test`](https://github.com/guardian/support-frontend/blob/2125cedfec1176e39ee744d5837fe74bffb15cb7/app/cookies/ServersideAbTestCookie.scala) to ensure users remain in the same variant once allocated.
* We can use this cookie value to set the correct `newPaymentFlow`. Note `getParticipations` will still assign a variant, as this loops over all tests currently defined. However, this value is then …

use NFP test variant from server 

---

assets/helpers/paymentIntegrations/newPaymentFlow/payPalRecurringCheckout.js
assets/helpers/paymentIntegrations/payPalExpressCheckout.js

Out of the blue and unannounced, the PayPal express checkout button decided to change into 2 buttons, one for normal PayPal and one for PayPal credit. 
So it now looks like this:
| erguh |
|------|
|![image](https://user-images.githubusercontent.com/2844554/47787410-c0dc3780-dd06-11e8-8ca8-cb7227800f0c.png)|
Kindly, their docs have been [updated](https://developer.paypal.com/docs/checkout/how-to/customize-button/#multiple-button-layout) and there is now some config you can set around the multiple button layout. 
For now, we just want what we had before, so we are disabling the CREDIT option. It now looks like this again:
| aaaaah |
|-------|
|![image](https://user-images.githubusercontent.com/2844554/47787467-ef5a1280-dd06-11e8-9213-4b450a4dbbe5.png)|

Turn off paypal credit

---

assets/pages/new-contributions-landing/components/ContributionFormFields.jsx
assets/pages/new-contributions-landing/components/MustSignIn.jsx
assets/pages/regular-contributions/components/formFields.jsx

Populates the identity frontend form with the email, so that the user doesn't have to type it in again
see https://github.com/guardian/identity-frontend/pull/486/files
Goes direct to:

Populate the email field when requiring sign in

---

assets/pages/regular-contributions/components/mustSignIn.jsx

If a user needs to sign in from the old payment flow, populate the email field to save them from having to type it in again
Goes direct to:

Populate email field if sign-in required from old payment flow

---

assets/pages/new-contributions-landing/contributionsLanding.scss

The input fields in the NCF weren't getting their blue focus state until the mouse was outside of them, which I suspect is a bug and in my criteria looked a bit confusing and took away a lot of the satisfaction of clicking down on the input field.
Luckily the [components cheatsheet](https://interactive.guim.co.uk/embed/article-embeds/HiZef/embed.html) keeps the bright focus ring on hover too, so I can just change the ncf behaviour to match the cheatsheet and be happy about it! 😸

NCF: Make input focus ring persist on hover

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx

This switches the old payment flow to guest checkout in preparation for the New Payment Flow test

Switch OPF to guest checkout for recurring contributions

---

app/controllers/Application.scala
assets/helpers/__tests__/checkoutsTest.js
assets/helpers/abTests/__tests__/abtestTest.js
assets/helpers/abTests/abtest.js
assets/helpers/abTests/abtestDefinitions.js
assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
assets/helpers/page/__tests__/pageTest.js
assets/helpers/page/page.js
assets/helpers/settings.js
conf/DEV.public.conf
test/codecs/CirceDecodersTest.scala

Fixes a bug whereby even if the serverside test was switched off in `settings.json`, the server would still set a cookie and the client would still set an A/B test participations (although thankfully it only ever served the existing page!).
So I've
- renamed the test from  `newPaymentFlow` -> `newFlow` so we don't get derailed by the dud data we've been pumping in for a few days
- removed the `newFlow` test from `abtestDefinitions.js` because this was misleading (none of the settings in there, not even `isActive`, actually had any effect on test since this was all determined serverside)
- made sure the client takes account of the serverside switch when figuring out A/B test participation
- made sure the server only drops a cookie if the test switch is on

Do not set cookie if test switched off

---

app/controllers/PayPalOneOff.scala
app/monitoring/Tip.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
app/wiring/Monitoring.scala
build.sbt
conf/tip.yaml

This PR adds production monitoring for one-off contributions, using the [TiP library](https://github.com/guardian/tip#testing-in-production-tip---). As a first pass (to see if this is useful), I've only implemented this for one-off PayPal contributions. 
After each deploy, a dashboard is automatically generated. This dashboard is updated (based on real user behaviour) to show which critical journeys have been completed:
Obviously this dashboard looks a bit sparse when we're only tracking 3 events, but hopefully it provides a reasonable demonstration of how this would work for us.
Thanks to @michaelwmcnamara, who spiked adding this library here: https://github.com/guardian/support-frontend/pull/1004. This PR is largely based on his work.
* Add TiP library, basic configuration and wiring
* …

Implement monitoring for one-off PayPal payments using TiP

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx

It appears that something is wrong with guest checkout on the old flow. 
This PR reverts the old flow to use non-guest checkout

Revert "Switch OPF to guest checkout for recurring contributions"

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/pages/regular-contributions/helpers/ajax.js

and turn guest checkout back on
This sessionId is required by the backend when trying to create a guest account for a new email address. We supply it in the new flow but forgot to send it for the old flow

Send session id on old flow

---

assets/pages/weekly-subscription-landing/components/weeklyContentBlock.scss
assets/pages/weekly-subscription-landing/components/weeklyCta.jsx
assets/pages/weekly-subscription-landing/components/weeklyCta.scss
assets/pages/weekly-subscription-landing/components/weeklyFeatureList.scss
assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
assets/pages/weekly-subscription-landing/components/weeklyForm.scss
assets/pages/weekly-subscription-landing/components/weeklyFormLabel.jsx
assets/pages/weekly-subscription-landing/components/weeklyFormLabel.scss
assets/pages/weekly-subscription-landing/components/weeklyHero.jsx
assets/pages/weekly-subscription-landing/components/weeklyHero.scss
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingActions.js
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js
assets/stylesheets/gu-sass/colours.scss

To get the GW page closer to a shippable state
[**Trello Card**](https://trello.com/c/Q4l0D1pR/2062-gw-page-redux-store)
- Redux store for the chosen pack
- Many CSS/A11y niceties
- Responsive components

Redux on GW page

---

cloud-formation/cfn.yaml

To handle any increase in traffic during the US midterms
Since we made the `contribute` routes uncacheable (they now vary by user login cookie), we're being extra cautious

Scale up to 6 instances

---

assets/helpers/abTests/abtestDefinitions.js

I had started to remove all the code, but then realised how much there was and thought it seemed unnecessary when we are very likely to resume amounts testing as soon as the NPF test is complete.

Turn off annual test

---

assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

The basic problem here is that `<button>` elements cannot be flex containers. https://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-or-fieldset-elements
This fixes it for the homepage submit button, which is the most important. But there are buttons on the thank you page which use duplicated CSS and different components. I suggest that in a separate PR, we try and rationalise the button components for the new flow - one component, one set of CSS rules. And in the process, fix the thank you page buttons too.
Based on GA, this fix will affect at least 5% of our site visitors
| Before  | After |
| <img width="430" alt="picture 325" src="https://user-images.githubusercontent.com/5122968/48087992-bf27dd80-e1f8-11e8-9060-e1171d3837c1.png"> …

Add span flex container within button

---

assets/components/radioToggle/radioToggle.jsx
assets/helpers/checkoutForm/checkoutForm.js
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/pages/new-contributions-landing/components/ContributionAmount.jsx
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionType.jsx
assets/pages/regular-contributions/components/contributionsGuestCheckoutContainer.jsx

We have been seeing an unexpectedly high rate of form errors on the new payment flow. This PR does a few things around this:
- Adds the form validation error tracking to the old flow so we can see if this is a new issue we've created
- Adds the reasons for the form validation error to the event
and example of what the form validation error event looks like: 
`blocked-because-form-not-valid-contributionEmail-pattern-mismatch-contributionFirstName-value-missing-contributionLastName-value-missing-contributionState-value-missing`
Yes it's rather unwieldy, but it gets the job done.
It also adds click tracking on the amounts and contribution type selections on the new and oldflow
Examples of the events:
NPF change amount: `npf-contribution-amount-toggle-GBPCountries-MONTHLY-10`
NPF change …

NPF: Add extra form validation and amounts selection tracking + couple of tracking fixes

---

assets/helpers/tracking/conversions.js
assets/helpers/tracking/googleTagManager.js

GA conversion tracking is now done server-side by support-workers and payment-api.

Remove client-side GA conversion tracking

---

test/selenium/RecurringContributionsSpec.scala
test/selenium/pages/RecurringContributionForm.scala

We need to write tests for the old flow, but for now, I've fixed the ones we broke before.
Annoyingly, the second time around, the email field autofills and won't clear. I looked into it and it's something to do with `autocomplete` being on which Selenium has trouble with ( [see here](https://www.google.co.uk/search?q=selenium+webelement+clear+not+working&rlz=1C5CHFA_enGB806GB806&oq=selenium+webelement+clear+not+working&aqs=chrome..69i57.9175j0j7&sourceid=chrome&ie=UTF-8) ) But for now, the second time around we just don't fill in the email and it still works with the test email generated the first time round!

Fix recurring selenium test for old payment flow

---

test/selenium/RecurringContributionsSpec.scala
test/selenium/pages/RegisterPageOne.scala

Amends one of the selenium recurring tests to go through the flow as an authenticated user, to give us more coverage.

Add authenticated case to OPF recurring guest checkout test

---

assets/helpers/tracking/conversions.js
assets/helpers/tracking/googleTagManager.js

undo https://github.com/guardian/support-frontend/pull/1155
apparently this data is still needed
* Change 1
* Change 2

Revert removal of client-side GA conversions

---

test/selenium/pages/ContributionsLanding.scala

This got missed in the PR to move to NPF. Causes selenium tests to fail

Fix selenium test - remove old url

---

assets/components/productPage/productPageContentBlock/productPageContentBlock.jsx
assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
assets/components/productPage/productPageContentBlock/productPageContentBlockOutset.jsx
assets/components/productPage/productPageHero/productPageHero.jsx
assets/components/productPage/productPageHero/productPageHero.scss
assets/components/productPage/productPageTextBlock/productPageTextBlock.jsx
assets/components/productPage/productPageTextBlock/productPageTextBlock.scss
assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss

This page layout will be reused across all new pages (Including paper subs - due for this week) so it makes sense to extract it into reusable chunks sooner than later.
Right now they live in `components/productPage/*` and there is some further optimisation we can make (there's already a `productHero` for checkouts but integrating that felt like a separate task.
There'se even more to split out but this is a solid starting point to kick this split off
[**Trello Card**](https://trello.com/c/lbXVrZWt/1955-new-guardian-weekly-product-page)

Extract out GW page components into reusable `productPage` components

---

app/admin/Settings.scala
app/controllers/Subscriptions.scala
test/codecs/CirceDecodersTest.scala
test/controllers/RegularContributionsTest.scala

When we first implemented the international subscribe pages they were behind a switch in case we wanted to turn them off again. This is no longer needed so I've removed it.
This has been tested on CODE with both the old settings file and the new updated one and works fine so the deployment order should be: Merge this PR, wait till it deploys then remove the switch from `settings.json`
[**Trello Card**](https://trello.com/c/1YNXWVNb/2056-remove-old-international-non-uk-subs-landing-page-redirection)

Remove the `internationalSubscribePages` switch

---

test/selenium/contributions/old/OneOffContributionsSpec.scala
test/selenium/contributions/old/RecurringContributionsSpec.scala
test/selenium/contributions/old/pages/ContributionsLanding.scala
test/selenium/contributions/old/pages/OneOffContributionForm.scala
test/selenium/contributions/old/pages/OneOffContributionThankYou.scala
test/selenium/contributions/old/pages/RecurringContributionForm.scala
test/selenium/contributions/old/pages/RecurringContributionThankYou.scala
test/selenium/contributions/old/pages/RegisterPageOne.scala
test/selenium/contributions/old/pages/RegisterPageTwo.scala

The selenium tests are currently failing because we've removed the routes to the old payment flow.
Now the only way to use the old payment flow is to visit /uk.
- Commit 1 - moves these old selenium tests into `/contributions/old`
- Commit 2 - fixes them (can now only use old flow for UK).
New selenium tests for the new payment flow will follow asap

Fix old contributions tests

---

assets/components/headers/countrySwitcherHeader/countrySwitcherHeaderContainerWithTracking.js
assets/pages/weekly-subscription-landing/components/weeklyCta.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingActions.js

So we can assess the performance of the new page
[**Trello Card**](https://trello.com/c/agMdXNa7/1995-analytics-for-new-gw-product-page)
* Added a `countrySwitcherHeaderContainerWithTracking` that adds tracking to the country switcher
* Added a `trackingOnClick` function to `weeklyCta` that allows to specify a custom tracking function that runs alongside a normal click handler and doesn't alter the current behaviour of using an anchor for links and a button for buttons

Add GA/Ophan tracking to Guardian Weekly page

---

assets/components/headers/countrySwitcherHeader/countrySwitcherHeaderContainerWithTracking.js
assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/components/ContributionThankYouPasswordSet.jsx
assets/pages/new-contributions-landing/components/ContributionsSurvey.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

We need to show the survey on the new payment flow thank you pages
Users will not be shown the button if we ask them to sign up (but on the next page they will see it)

Show survey on NPF thank you pages

---

.flowconfig
app/lib/CustomHttpErrorHandler.scala
assets/pages/error/components/errorPage.jsx
webpack.common.js

The motivation behind this is to make our components truly standalone, just import the Preact component and the styles come with it.
This means you don't have to remember to add the relevant `@import ~foo/bar` in your page's stylesheet.
In essence, [this step](https://github.com/guardian/support-frontend/wiki/Quickstart:-Adding-a-new-route#assetspagesguardian-forthnightlyguardianforthnightlyscss) now becomes obsolete.
Making this change on 404 and 500 pages to start as its fairly low risk.
n/a

import styles within component

---

assets/helpers/externalLinks.js
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js

To start sending traffic to the new Guardian Weekly page from the subs landing page.
This will also make 6 for 6 the default payment option

Switch on Guardian Weekly page

---

app/controllers/Subscriptions.scala
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.scss
conf/routes
public/robots.txt
webpack.common.js

Create an empty page for paper subs to begin work on it
- `/subscribe/paper` (redirects to collection)
- `/subscribe/paper/delivery`
- `/subscribe/paper/collection`
[**Trello Card**](https://trello.com/c/Rjq5SmCR/2057-print-product-page-v0)

Paper subs route

---

app/controllers/PayPalOneOff.scala

Currently when sending data to payment-api, the gaId value is always `1` - get the `_ga` cookie value instead.

Fix paypal one-off GA events

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/new-contributions-landing/contributionsLanding.scss

This is so that we get the correct header on subsequent pageviews which don't have the componentType in the URL, e.g. thank you page after PayPal one-off, or after changing country dropdown.
also fixes this:
| old | new |
| --- | ---- |
| ![picture 364](https://user-images.githubusercontent.com/5122968/48634645-f008cf00-e9bd-11e8-8d21-9b69e56855fb.png) | ![picture 363](https://user-images.githubusercontent.com/5122968/48634657-f72fdd00-e9bd-11e8-93c3-1668fd5a7960.png) |
| old | new |
| --- | ---- |
| ![picture 362](https://user-images.githubusercontent.com/5122968/48634673-0151db80-e9be-11e8-9e0d-7f757846cff4.png) | ![picture 361](https://user-images.githubusercontent.com/5122968/48634686-0747bc80-e9be-11e8-978b-0187437e4e01.png) |

Check session storage too for consistent banner experience

---

app/controllers/PayPalOneOff.scala
app/services/PaymentAPIService.scala

I'm still not seeing paypal one-offs in GA. Perhaps it's because Play is currently sending `AHC/2.0` for the user-agent

Send user-agent to payment-api

---

app/controllers/PayPalOneOff.scala
conf/tip.yaml

This is currently causing lots of `ERROR` logs in cloudwatch
e.g.
```
ERROR com.gu.tip.PathsActor - Unrecognized path name. Available paths: US One-off PayPal contribution,GB One-off PayPal contribution,AU One-off PayPal contribution
ERROR com.gu.tip.TipFactory$$anon$1 - Unrecognized path name: int One-off PayPal contribution
```

Fix TiP for paypal

---

assets/pages/subscriptions-landing/components/featuredProducts.jsx

Our PM expected Digital Pack to be promoted to US users during the flash sale. That wasn't happening.
[**Trello Card**](https://trello.com/c/ewib2bNI/2087-show-digital-pack-as-promoted-product-to-us-users-during-november-flash-sale)

Make digital pack the featured product during flash sale outside of the UK

---

assets/pages/new-contributions-landing/components/SetPassword/SetPasswordForm.jsx

Making the password rules consistent with [identity-api](https://github.com/guardian/identity/blob/master/identity-api/src/main/scala/com/gu/identity/api/postgres/PostgresPasswordHashRepository.scala#L20)
Invalid password entry has been the cause of _some_ of the 500 errors on support-frontend lately - it's not surprising that some users try it repeatedly given that the message is incorrect here.
For the record, these are logged by support-frontend as:
```
Failed to set password using guest account registration token...
{ "status": "error", "errors": [ { "message": "Invalid password", "description": "The password provided is invalid" } ] }
```

Lower password max-length to 20

---

assets/components/headingBlock/headingBlock.scss
assets/components/leftMarginSection/leftMarginSection.scss
assets/components/productPage/productPageButton/productPageButton.scss
assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
assets/components/productPage/productPageFeatures/productPageFeatures.scss
assets/components/productPage/productPagePeriodForm/productPagePeriodForm.scss
assets/components/productPage/productPagePeriodForm/productPagePeriodFormLabel.scss
assets/components/productPage/productPageTextBlock/productPageTextBlock.scss
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
assets/stylesheets/gu-sass/layout.scss
assets/stylesheets/gu-sass/typography.scss

This PR has two goals - First of all, implement @Joshua-David's grid template more closely. Second of all, codify a set of responsive type sizes, and a column size mixin that will serve as the source of truth for all product pages moving forward. This will help us be more consistent with font-sizes and widths across the board 
* Add `gu-span()` mixin (copying frontend's `gs-span()`
* Tweak the left margin section sizing a bit to better conform to the column grid
* Add semantic `gu-fontset-*` mixins to define common text styles (family + sizing) such as body, title, standfirst, etc.
* Remove `gu-font()` mixin (nothing was using it) in lieu of a simpler `gu-typeface` one with the new pairs and less parameters (it's just family, size, and line height now)
* Implement the new font sizes, …

Refine grid+type on new product pages css

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/referrerComponent.js
assets/pages/new-contributions-landing/contributionsLanding.jsx

Following [this test ](https://github.com/guardian/support-frontend/pull/1193), we are going to default to the winning variant, `shrink_no-blurb_no-header`, on mobile for those coming from the epic and banner. 
This PR also sets up a new test, which is the same as the test before, but for everyone that didn't come from the epic or banner. 
| `shrink_no-blurb_no-header` | `shrink_no-blurb` | `shrink` | `control` |
| ------------ | ----------------| -----| -----|
| ![support thegulocal com_uk_contribute iphone 5_se 4](https://user-images.githubusercontent.com/5122968/48582980-edef3380-e91d-11e8-93ef-33d809c86872.png) | ![support thegulocal com_uk_contribute iphone 5_se 3](https://user-images.githubusercontent.com/5122968/48582984-f182ba80-e91d-11e8-83f8-e9227b9b1c35.png) | ![support …

Make the shrink_no-blurb_no-header variant from the smallMobileHeader test the control (EPIC and BANNER) only

---

app/controllers/Subscriptions.scala
app/views/main.scala.html
assets/components/marketingConsentNew/marketingConsent.jsx
assets/pages/digital-subscription-checkout/__tests__/digitalSubscriptionCheckoutReducerTest.js
assets/pages/digital-subscription-checkout/components/MarketingConsentContainer.jsx
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/components/thankYouContent.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/components/ContributionThankYouPasswordSet.jsx
assets/pages/new-contributions-landing/components/MarketingConsentContainer.jsx

This PR replaces this one: https://github.com/guardian/support-frontend/pull/1174
First, some background. When the work to separate out this component started the new payment flow for contributions was a test. Between then and now, it has gone live but all the original code was left behind in that transition, so we now have a mess that needs to be cleaned up. Sadly that's going to be compounded by this batch of changes.
This PR creates a shared marketing preferences component for these specific areas *only*:
* Contributions 'new payment flow' thank you page UI
* New digital pack checkout thank you page
It does *not* change:
* Contributions 'old payment flow' thank you page UI   
* Marketing preferences component used by the 'old payment flow'
[**Trello …

Make marketing consent a shared component (using new design)

---

assets/pages/new-contributions-landing/contributionsLanding.jsx
assets/pages/new-contributions-landing/contributionsLandingInit.js

Previously, we were setting the one-off contribution cookie (that `gu.com` uses to prevent displaying the epic or banner) for recurring contributors hitting the thank you page. There is an equivalent recurring contributions cookie, which is set server side, so we don't need to set anything here for recurring contributors. 
The impact of this bug is that everyone who has given a recurring contribution in the past few weeks will have both cookies. There's nothing we can really do about this, other than fix it going forwards

Only set one-off contribution cookie for one-off contributions

---

app/services/stepfunctions/RegularContributionsClient.scala
test/services/stepfunctions/RegularContributionsClientTest.scala

If the step functions reach the `FailState`:
then the user is not told that something failed - they are instead redirected to the thank you page.
This change ensures that the standard error is displayed.
This was discovered because a user managed to submit a US contribution with no state selected.

Handle 'FailState' result from step functions

---

assets/components/forms/formHOCs/withError.jsx
assets/helpers/subscriptionsForms/__tests__/validationTest.js
assets/helpers/subscriptionsForms/validation.js
assets/helpers/types/__tests__/optionTest.js
assets/helpers/types/option.js
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

To apply validation rules to the digital subscription checkout, and to make the validation code generic enough to use on other checkouts.
This introduces a new `validate` function, which takes a list of rules and corresponding error messages. It then returns a series of error messages based on these rules. Also included is a `FormError` type that combines a form field with an error message, which can be used in conjunction with this validation framework (or not, any error message format should work). The resultant error messages are then used in combination with the `withError` HOC to display error messages on the page (see the screenshot below).
[**Trello Card**](https://trello.com/c/yH3GBpu7/1782-mandatory-fields-incomplete-error-messaging)
- Tweaked `withError` to use …

Digital Subscription Checkout Validation

---

app/controllers/Subscriptions.scala
conf/routes
public/robots.txt

it's more consistent with all other routes, this page is unlaunched so there are no user-facing consequences to doing this

move /subscribe/paper to /uk/subscribe/paper

---

assets/helpers/user/user.js

This ensures that only those with the cookie set to `true` will be blocked

Fix recurring cookie logic

---

assets/helpers/page/page.js
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

To simplify building the Redux state type, to reduce boilerplate and hopefully make it easier to understand the types in each reducer file. If this works well for the digital checkout it can be rolled out to the other reducer files.
- Added new parameterised `ReduxState` type.
- Used the new type on the digital checkout.

Simpler Redux State Type

---

package.json
webpack.common.js

`cssnano` was running before sass meaning a lot of the optimisations (especially around removing suplicates) weren't happening. This uses `optimize-css-assets-webpack-plugin` to put minification at the last step.

Minimize css a bit more

---

cloud-formation/cfn.yaml

Reverts guardian/support-frontend#1145
I noticed that we're still scaled up, is this intentional @joelochlann @johnduffell?

Revert "Scale up to 6 instances"

---

assets/helpers/__tests__/formValidation.js
assets/helpers/checkoutForm/checkoutForm.js
assets/helpers/contributions.js
assets/helpers/formValidation.js
assets/pages/new-contributions-landing/components/ContributionAmount.jsx
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

Using the Constraint Validation API to determine whether the form is valid was causing us some issues. There was a race condition error whereby if you change the amount to other, the change to the DOM doesn't happen in time for the correct valid state to be determined. This was currently only an issue for the PayPal button, as the rest of the payment methods evaluated the form on submit, rather than on form change, but that is changing in [this PR](https://github.com/guardian/support-frontend/pull/1209).  
It was also always the plan to move to state-based form validation anyway because that's what we use to decide whether to show an error or not, and having 2 different validation systems was always going to (and has already) cause problems. 
So we need to switch to state-based form …

Don't use the Constraint Validation API to determine whether to submit the form or not

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/otherProduct/otherProduct.jsx
assets/components/patronsEvents/patronsEvents.jsx
assets/components/readyToSupport/readyToSupport.jsx
assets/components/subscriptionBundles/digitalPack.jsx
assets/components/subscriptionBundles/paper.jsx
assets/components/subscriptionBundles/paperDigital.jsx
assets/helpers/subscriptions.js
assets/helpers/tracking/clickTracking.js
assets/pages/support-landing/components/subscriptionsSection.jsx
assets/pages/support-landing/supportLanding.jsx

We want to know how people are engaging with the showcase page, and to do that we'll need to know a bit more of the context behind the clicks.
This change prefixes the GA tracked label with some information about which page the button was on when it was clicked, and adds a couple of new event calls for elements that previously had none.
We can measure engagement with these controls via the labels applied in the GA events as follows;
* Supporter Options
* `support-landing-page-supporter_options_cta`
* Subscribe
* Digi-pack
* `support-landing-page-digipack_cta`
* Paper
* `support-landing-page-paper_cta`
* Paper+Digital
* `support-landing-page-paper_digital_cta`
* Contribute
* One-off
* `support-landing-page-one_off_cta`
* Recurring
* `support-landing-page-regular_cta`
* Patrons
* …

Add some contextualised click tracking primarily for the showcase page

---

assets/helpers/internationalisation/contributions.js
assets/helpers/tracking/acquisitions.js
assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

If a user is referred by a US campaign epic, display a different message on the /contribute page. This means users who come from the control epic will see the old copy.
[**Trello Card**](https://trello.com/c/yTsOtQOQ/216-update-copy-on-us-landing-page)
* Adds function `isUsCampaignTest`, which uses the `abTest` provided in the query string to decide which copy to show. This will be used for other design changes later.
* Make the text below the headline optional

US campaign copy on /contribute page

---

assets/components/checkoutCopy/checkoutCopy.jsx
assets/components/checkoutCopy/checkoutCopy.scss
assets/components/checkoutHeading/checkoutHeading.jsx
assets/components/checkoutHeading/checkoutHeading.scss
assets/components/forms/customFields/radioInput.scss
assets/components/forms/formHOCs/withArrow.jsx
assets/components/forms/formHOCs/withArrow.scss
assets/components/forms/formHOCs/withError.scss
assets/components/forms/standardFields/button.scss
assets/components/forms/standardFields/input.scss
assets/components/forms/standardFields/select.scss
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

Adding payment frequency and payment method radio buttons to the checkout. Also applying styling to the checkout page as a whole.
[**Trello Card**](https://trello.com/c/04Ln5TWR/1506-select-subscription-frequency)
- Added `CheckoutCopy` and `CheckoutHeading` components for sections with shared styling.
- Updated `RadioInput` to use a custom radio visual.
- Created a `withArrow` HOC to add the right arrow SVG to buttons and links.
- Tweaked the styling of some of the form components (e.g. added a chevron to the `Select` component).
- Added headings to the checkout form; added payment frequency and payment method sections.
- Added heading and free trial copy.
- Refactored some imports.
- Added reducer/action logic and types to handle payment frequency and payment method.
| …

Digital Checkout Payment Frequency, Method and Styling

---

assets/pages/new-contributions-landing/components/ContributionFormFields.jsx

[This PR](https://github.com/guardian/support-frontend/pull/1209) changed the updateState function in ContributionFormFields, and introduced a bug whereby we weren't setting the state in the redux store properly. This PR fixes the bug. All praise the selenium tests that caught this

Fix updateState function

---

assets/components/featuredProductHero/featuredProductHero.jsx
assets/components/flashSaleCountdown/flashSaleCountdown.scss
assets/pages/subscriptions-landing/components/featuredProductAb.jsx

Making the countdown timer look more prominent and rolling it out as default for the featured product header - Digital Pack (US, AU, RoW only).
[**Trello Card**](https://trello.com/c/R64yrpsc)
**Before:**
**After:**
**Before:**
**After:**

Rolling out countdown timer for Digital Pack & Featured product

---

assets/helpers/abTests/abtestDefinitions.js

We have an epic test that might interfere with this test, so we need to turn it off. At hack day, so just flicking the switch for now

Turn off US contributions type test

---

assets/pages/subscriptions-landing/components/featuredProductAb.jsx

We should show a flash sale countdown timer in the featured product header  for any product which is in the flash sale, not just Digital Pack as we were doing previously

Show the countdown timer for any product which is in the flash sale

---

assets/pages/subscriptions-landing/components/featuredProducts.jsx

We have an issue of product images not appearing in the featured product hero on mobile (both iOS and android). This is due to a long standing bug that is causing the wrong images (=wrong sizes) to display on mobile and desktop (we display 500 on desktop and 1000 on mobile; in the case of the featured product image - the 1000 wide image doesn't even exist).
This PR is a quick fix that will make the product shots appear correctly on mobile (the bug will still need to be addressed though) thanks Akash!
upd. Just tested on code and it seem to have fixed the issue - https://support.code.dev-theguardian.com/us/subscribe .
**Before**
**After**

Quick fix to display the featured product image on mobile

---

assets/components/productPage/productPageContentBlock/productPageContentBlock.jsx
assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
assets/components/productPage/productPageHero/productPageHero.scss
assets/components/productPage/productPageTextBlock/productPageTextBlock.scss
assets/helpers/theGrid.js
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.scss

They are needed for launch. This PR depends on #1228 for final tweaks as there is no 2 tab structure on master yet to place both content images on. This PR brings a generic-ish slot for them that will hold either.

Images in paper subs page

---

app/controllers/RegularContributions.scala
app/monitoring/Tip.scala
app/wiring/Controllers.scala
conf/tip.yaml
test/controllers/RegularContributionsTest.scala

This is a follow up to https://github.com/guardian/support-frontend/pull/1123 and https://github.com/guardian/support-frontend/pull/1160. It allows us to track important recurring contributions flows and updates a [TiP dashboard](https://github.com/guardian/tip#testing-in-production-tip---) accordingly. 
This should make it easier to spot broken permutations of the checkout flow in production (based on real user data).
Note that there will be a follow up PR which swaps us over to using a centrally hosted TiP service before this dashboard is properly shareable.
* Add recurring paths to TiP config
* Verify relevant paths once successful form submission is confirmed
* Refactor response handling (and minor logging changes) to remove duplication

Add recurring paths to TiP

---

assets/components/subscriptionsByCountryGroup/components/digitalSection.jsx

Adding a heading for "Digital Subscriptions" to the subs landing page (UK only).
[**Trello Card**](https://trello.com/c/f31qOfGL/2090-put-digital-subscriptions-title-back-into-the-uk-subs-landing-page)
- Added heading text.
### Before

Digital Subscriptions Heading

---

assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx
assets/helpers/paymentIntegrations/newPaymentFlow/payPalRecurringCheckout.js
assets/helpers/paymentIntegrations/payPalExpressCheckout.js
assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
assets/pages/new-contributions-landing/components/PayPalRecurringButton.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/regular-contributions/components/regularContributionsPayment.jsx

Annual contributors see "Guardian Monthly Contributor" in the PayPal popup
It's not a massive thing because you have to click a little box at the top right of the PayPal popup to see the monthly details (see screenshot). But this may have been affecting Annual Contributions numbers
[**Trello Card**](https://trello.com/c/ApWr8xuW/85-npf-follow-up-bug-affects-existing-flow-too-we-send-monthly-billing-period-to-paypal-even-for-annual)
* Passes through contribution type and uses to set correct billing period for PayPal recurring checkout.

Correct paypal recurring billing period

---

devrun.sh
fetch-config.sh
setup.sh

This is to make the project slightly easier to setup and run, ideally to empower the our ux+d and product colleagues to make changes. Essentially, scripting [these instructions](https://github.com/guardian/support-frontend/wiki/Install).
Ideally the process is:
- clone repo
- run `setup.sh`
- run `fetch-config.sh`
- run `devrun.sh`
Then, going forward, `devrun.sh` is all that's needed to run the project. 🤞
Inspired by https://github.com/guardian/frontend/blob/master/setup.sh.
TODO:

scripts to make setup easier

---

setup.sh

Relative symlinks are bad because they're relative to the destination 😄.

fix location of nginx conf symlnk

---

app/controllers/IdentityController.scala
app/services/aws/AwsCloudwatchMetricPut.scala
app/wiring/Controllers.scala
build.sbt
cloud-formation/cfn.yaml

Currently we have a lot of alerts for stuff that shouldn't happen, but isn't as severe as all that.
At the moment we can either shout loudly that something is broken, or hide it completely.
It would be better to have a category for alerts that don't need immediate attention but should be planned in to a sprint.
This PR adds a warning count in cloudwatch and makes it alert when guest password or email sing up don't work.
These are chosen because they don't affect conversion, however they reflect failures that would influence business metrics.
I'm keen to add an alarm into the cloudformation for PROD, but I would want us to decide on a suitable threshold and also wording to make it clear this is an alert to be planned into a sprint rather than an something is on fire one.
[**Trello …

warn when something bad happens that doesn't affect conversion

---

assets/components/marketingConsent/helpers.js
assets/components/marketingConsent/marketingConsentActions.js
assets/components/marketingConsent/marketingConsentReducer.js
assets/components/marketingConsentNew/marketingConsent.jsx
assets/pages/new-contributions-landing/components/MarketingConsentContainer.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap
assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap

Sometimes when network issues happened, we were getting multiple duplicate requests for the sign up to the emails button.
This was because when they clicked the button it wasn't actually disabled and the visual appearance didn't change, so during slow network conditions they would click it quite a few times.
This PR changes the button to be disabled when they click, until the resonse comes in.
It also changes the button to look different so people know their click was registered.
[**Trello Card**](https://trello.com/c/IC361x2a/198-investigate-500-errors-should-they-be-500s)
before clicking (no change)
new - while loading (used to be the same as before clicking)
after complete (no change)
after error (no change)
@jranks123 for tech review and @ionamckendrick for behaviour review please

Change email signup to disabled after clicking

---

app/controllers/IdentityController.scala
cloud-formation/cfn.yaml

The [previous PR](https://github.com/guardian/support-frontend/pull/1259) added code to push metrics to cloudwatch when a non critical event happened (look at next sprint)  However I forgot that I would need to also give IAM permission for the instances to access cloudwatch.
This time I have actually done an end to end test in CODE to make sure the alert email actually arrives.  However I have turned the alarm off in CODE.
[**Trello Card**](https://trello.com/c/IC361x2a/198-investigate-500-errors-should-they-be-500s)

actually allow permission to push metrics to cloudwatch

---

assets/helpers/internationalisation/countryGroup.js
assets/helpers/subscriptions.js
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

Display prices on the digital checkout.
[**Trello Card**](https://trello.com/c/04Ln5TWR/1506-select-subscription-frequency)
- Exported `fromCountry` from the `countryGroup` helper.
- Configured digital subscription prices and created a helper to retrieve them.
- Moved digital billing period type in `subscriptions` helper.
- Displayed prices in the payment frequency section of the checkout.
|UK|US|AU|None|
|-|-|-|-
|![price-uk](https://user-images.githubusercontent.com/5131341/49513759-f1753b00-f889-11e8-859b-0e26b2ac6703.png)|![price-us](https://user-images.githubusercontent.com/5131341/49513768-f934df80-f889-11e8-9a6b-88290d2a3da9.png)|![price-au](https://user-images.githubusercontent.com/5131341/49513776-ffc35700-f889-11e8-9ce4-35eb42693351.png)|![price-none](https://user-images.githubus …

Digital Checkout Internationalise Prices

---

assets/helpers/internationalisation/currency.js
assets/helpers/internationalisation/price.js
assets/helpers/subscriptions.js
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx

Adding a type to handle prices, contains the amount and currency. To be used on the digital checkout.
- Tidied up the currency helper, and added helper functions to retrieve the glyphs for a given `IsoCurrency`.
- Added a new `Price` type and corresponding helper file, with helpers to create a `Price` for a given currency and one to display the price as a string.
- Updated the digital subscriptions prices to use the new `Price` type.

Price Type

---

assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx

_"It's been raised by the CS team at Teleperformance that on this page, the links for the standard and promotional terms and conditions are in fact switched, you can actually see the difference in the links at the bottom of the page."_
* Switching links for the standard and promo Ts&Sc on the Guardian Weekly page.

Fixing links for Ts&Cs on the GW page

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/new-contributions-landing/components/ContributionBackground.jsx
assets/pages/new-contributions-landing/contributionsLanding.jsx

Adds logic for ab testing the US background image. Currently **everyone in the US be allocated to the variant displaying the background image** but this change means we can easily make it so that only those in the US _and_ in the test will see the new background by adding a control, and also quickly turn off the background by setting the test activity to false. 
* Adds a test and passes variant to background component to determine if should show the custom background. 
This PR doesn't add the image but for context here is what it looks like:

add test to background image

---

app/controllers/Subscriptions.scala
assets/components/productPage/productPagePlanForm/productPagePlanForm.jsx
assets/helpers/subscriptions.js
assets/pages/paper-subscription-landing/components/form.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js

Replaces the dataset+zuora fetching with hardcoded ones in our JS. Since we are hardcoding them for checkout this makes more sense

Harcode paper prices

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/tracking/acquisitions.js
assets/pages/new-contributions-landing/components/ContributionBackground.jsx
assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
assets/pages/new-contributions-landing/components/ContributionUsTicker.jsx
assets/pages/new-contributions-landing/contributionsLanding.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss

Adds an ab test for the new us EOY campaign features. 
* Set the ticker and background image as variants in a us-only ab test. These will only appear to desktop users.
* The campaign copy is set as the control - everyone in the US sees the campaign copy on desktop and mobile (unless they are also in a `ab-smallMobileHeaderNotEpicOrBanner` variant which does not display it).
* Removes referral logic given everyone sees the campaign copy. 
Current (not referred from epic / banner)
| campaignCopy  | copyAndTicker | copyAndTickerAndBackgroundImage |
| ------------- | ------------- |------------- |
| ![screen shot 2018-12-10 at 15 53 46](https://user-images.githubusercontent.com/8484757/49744777-78b11d00-fc95-11e8-95a0-6b89ccf7f1bd.jpg) | ![screen shot 2018-12-10 at 16 36 …

us campaign desktop tests

---

app/config/StringsConfig.scala
app/controllers/Subscriptions.scala
assets/helpers/routes.js
assets/pages/paper-subscription-landing/components/content.jsx
assets/pages/paper-subscription-landing/components/tabs.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPageActions.js
conf/routes
conf/strings.conf
public/robots.txt

- Adds the proper canonical URL
- Adds a meta description
- Replaces the title with the proper one
- Adds tracking to the tabs
- Switch the urls to `uk/subscribe/paper` (collection) & `uk/subscribe/paper/delivery` (delivery)
- Removes paper pages from `robots.txt`

Add missing SEO tags & tracking in paper subs page

---

assets/pages/new-contributions-landing/contributionsLanding.scss

The main cta on a page should be solid for usability reasons.  The supplementary ones should generally be hollow.  In the thank you page the Share your thoughts is the main one, although the sign up to email one is also kind of main so can remain solid.
[**Trello Card**](https://trello.com/c/8y47X6If/224-correct-colours-of-the-ctas-on-our-thank-you-pages)
Before:
After:
@ionamckendrick I think I covered the things you described, please let me know if I forgot any of the tweaks!

Make primary CTA on thank you page solid

---

assets/pages/showcase/showcase.scss

this also fixes the logo's padding in the header of the showcase page
Before
After

remove unnecessary imports

---

app/controllers/RegularContributions.scala

At the moment, if the `createContributorAndUser` method returns an `InternalServerError`, rather than a `StatusResponse`, we don't return the GuestAccountRegistrationToken. This PR adds a comment explaining the consequences of this (we could fix it but it's too small an edge case to justify working on it right now)

Add useful comment to RegularContributions.scala

---

assets/helpers/optimize/optimize.js
assets/helpers/tracking/acquisitions.js

When I switched our Optimize tracking to use the Javascript api [here](https://github.com/guardian/support-frontend/pull/1156), I didn't realise that the api only returns variant data for AB tests, not redirect tests. This means that information about redirect tests does not end up in the data lake.
This PR fixes the problem.
[**Trello Card**](https://trello.com/c/cufbYZRz/2097-add-data-lake-tracking-to-support-for-redirect-tests)

Store experiment ids which are in the query string from redirect tests

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/new-contributions-landing/checkoutFormIsSubmittableActions.js
assets/pages/new-contributions-landing/components/ContributionFormFields.jsx

We don't use the first and last name for one offs, but we insist on them being entered.  This PR tests what hpapens if we remove them.
[**Trello Card**](https://trello.com/c/vU7sj6vJ/227-remove-name-fields-test-single-contributions)
BEFORE::
AFTER:
@jranks123

test hiding the name for 50% of users on one off

---

test/selenium/contributions/new_flow/OneOffContributionsSpec.scala
test/selenium/contributions/new_flow/RecurringContributionsSpec.scala
test/selenium/contributions/new_flow/pages/ContributionsLanding.scala

In the [AB test for no firstname/lastname](https://github.com/guardian/support-frontend/pull/1299) the tests broke, because they expect the fields.
This just makes the fields optional if the tests are in the one off flow.
Other alternative would be to force the tests into the control bucket, but I thought it's better to make the tests check whatever they are given.
@jranks123

make the selenium tests handle no names AB test

---

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx
assets/components/contributionsCheckout/contributionsCheckout.jsx
assets/components/legal/legalSection/legalSection.jsx
assets/components/legal/legalSection/legalSection.scss
assets/components/legal/legalSection/legalSectionContainer.js
assets/components/legal/termsPrivacy/termsPrivacy.jsx
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
assets/pages/regular-contributions/components/contributionsGuestCheckout.jsx

New T&C are required in california to clarify cancellation and frequency, so we might as well add them everywhere as it makes things clearer.
[**Trello Card**](https://trello.com/c/Tbv8uop2/226-update-in-line-terms-conditions)
[Main checkout flow](https://support.theguardian.com/uk/contribute)
BEFORE:
AFTER:
---
[old checkout flow](https://support.theguardian.com/contribute/recurring-guest?contributionValue=5&contribType=MONTHLY&currency=GBP)
BEFORE:
AFTER:
@ionamckendrick does that look about right?  Those are the only two pages I could find on support-frontend, but there is subscribe-frontend where there are other T&C for the print&digital products

add extra Ts and Cs for the landing pages

---

assets/helpers/externalLinks.js

Opening while I test locally...
We're sending people to the wrong checkout
To follow

Send everyday voucher print subs to correct checkout endpoint

---

app/views/digitalSubscription.scala.html
assets/helpers/internationalisation/__tests__/countryTest.js
assets/helpers/internationalisation/country.js
assets/pages/digital-subscription-checkout/__tests__/digitalSubscriptionCheckoutReducerTest.js
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/helpers/__tests__/userTest.js
assets/pages/digital-subscription-checkout/helpers/user.js

We should make it as easy as possible for users to sign up for a digital pack. So let's pre-select their country, and allow them to change it if they need.
If we know their country based on what's stored in identity, we preselect that. Otherwise, we select based on their countryGroupId. 
(Using the detect function here: https://github.com/guardian/support-frontend/blob/master/assets/helpers/internationalisation/country.js#L522)
[**Trello Card**](https://trello.com/c/sJDnpz0S/2093-pre-populate-checkout-fields)
* Also saves country in the window
* Pre-selects country in the digital pack checkout based on the country stored in identity, or failing that, what we know based on their countryGroupId/path/cookie/query param
Just like the digital pack checkout form, but the country is pre-selected …

pre-select country in the digital pack checkout

---

assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx

We want to call out gifting options for quarterly and annual GW subs.
This PR updates the copy. I'll open another tomorrow to add and style the SVGs.
[**Trello Card**](https://trello.com/c/oWQe33mN/2119-gifting-copy-updates-for-gw-product-page)
**Before**
**After**
(updated - was given duff information re. copy in the customer service section)

Copy change for gifting messaging

---

app/controllers/RegularContributions.scala
app/controllers/SupportWorkersStatus.scala
app/monitoring/StateMachineMonitor.scala
app/services/stepfunctions/SupportWorkersClient.scala
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
app/wiring/Services.scala
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/regular-contributions/helpers/ajax.js
conf/routes
test/controllers/RegularContributionsTest.scala
test/services/stepfunctions/SupportWorkersClientTest.scala

As a first step in wiring up the new Digital Pack checkout to support-workers I'm refactoring a few things in preparation:
* Rename the `RegularContributionsClient` to `SupportWorkersClient` as this class will handle interactions with support-workers for all product types
* Move the `/status` endpoint which is polled for the state of support-workers executions into its own controller as it is not specific to recurring contributions
* Rename `contribution` to `product` in the json payload which is sent to the recurring contributions `create` endpoint, to prepare for sending other products 
[**Trello Card**](https://trello.com/c/5N8LQ5yU/2060-be-able-to-trigger-the-creation-of-a-digital-pack-subscription-via-support-frontend)
I've successfully tested Stripe, PayPal and DD in both …

Digipack support workers

---

assets/helpers/theGrid.js
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss

Keeping things up to date and tidy. 
* Update header image
* Remove headline from the product page hero
* GridImage -> Grid Picture
* Update the T&C link copy
(compare to current state of the page here: https://support.theguardian.com/uk/subscribe/weekly)
| mobile        | tablet           | big wide web screen  |
| ------------- |-------------| -----|
| <img src="https://user-images.githubusercontent.com/3072877/50010286-e53b5d00-ffb0-11e8-8023-a8089950f710.png" height=200>    | <img src="https://user-images.githubusercontent.com/3072877/50010346-10be4780-ffb1-11e8-9043-aa59dbe63757.png" height=200> | <img src="https://user-images.githubusercontent.com/3072877/50010371-2e8bac80-ffb1-11e8-83a8-4ea17c0b0163.png" height=200> |

Update header and T&C links on weekly page

---

app/admin/Settings.scala
app/admin/SettingsProvider.scala
conf/DEV.public.conf

Currently to use local settings with support-frontend you need to uncomment a line in DEV.public.conf. This is not ideal because it means that you then have an uncommitted change before you do anything else and you need to remember to revert it before committing.
Also I prefer to use local settings all the time as it means you can work on large parts of the site (including all of the subs product pages) without Janus credentials (the only reason you need them is to load settings from S3 which are not needed in DEV)
This PR changes the settings loading behaviour so that the app will load from local settings by default in DEV but will fall back to S3 if the local settings file doesn't exist.

Use a local settings file if it exists

---

cloud-formation/cfn.yaml

The alarm went off on a one minute outage.
We expect it to need 2 before it actually alarms, but it would be missing data the rest of the time.  It last went off in september
[According to AWS](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data) it looks backwards if there's missing data and we need more samples.  But in this case there are no such thing as an OK sample, a missing sample is OK.  So we need to treat missing samples as OK.

prevent alarming on a 1 minute glitch in the state machine

---

assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx
assets/helpers/paymentIntegrations/newPaymentFlow/oneOffContributions.js
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/helpers/paymentIntegrations/newPaymentFlow/stripeCheckout.js
assets/pages/new-contributions-landing/components/ContributionForm.jsx
assets/pages/new-contributions-landing/components/StripePaymentRequestButton.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js

Previously, we were tracking Apple Pay payments as Stripe payments. This PR adds an extra bit of metadata to `StripeChargeData`,  `stripePaymentMethod`, so that the `payment-api` can track it separately. 
Soon we will be adding Stripe Payment Request Button payments, so this PR also provisions for that future scenario. 
[Corresponding payment api PR](https://github.com/guardian/payment-api/compare/jr-add-apple-pay?expand=1)

Track Stripe Apple Pay Payments 

---

assets/helpers/paymentIntegrations/newPaymentFlow/oneOffContributions.js
assets/pages/new-contributions-landing/contributionsLandingActions.js

A typo in the `StripeChargeData` meant that the payment api wasn't able to read the `stripePaymentMethod` field. 
Thus, all Apple Pay transactions were logged as normal Stripe transactions (the pre-exisiting behaviour).
This PR fixes it

Fix apple pay tracking

---

test/selenium/subscriptions/LandingPagesSpec.scala
test/selenium/subscriptions/pages/PaperSubs.scala
test/selenium/subscriptions/pages/WeeklySubs.scala

Test that the subs landing pages are not completely broken post-deploy
[**Trello Card**](https://trello.com/c/sYEQ9kbt/2084-post-deploy-test-for-landing-pages)

Add selenium tests for subs

---

assets/helpers/externalLinks.js
assets/helpers/subscriptions.js
assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingActions.js

_Edited_: updated screen grabs
We want to activate the 10ANNUAL Guardian Weekly promo from support frontend. This was never brought forward from subscriptions-frontend, so it's a bit of a just-get-it-working approach at the moment.
Caveats:
It may not play nicely alongside flash sales - I haven't tested that yet. We don't have any GW flash sales running (AFAIK) but maybe it'd be better to define this as a long-running/open-ended sale for the weekly product?
It'll need a code change and deploy to remove it again if/when the time comes.
[**Trello Card**](https://trello.com/c/wAe1CS6S/2101-add-10-off-annual-back-into-gw-product-page)
* Always use the 10ANNUAL code on weekly annual subs for ALL territories
**UK**
**US**
Yes

Add 10% promo to GW annual subs

---

app/actions/CustomActionBuilders.scala
app/controllers/CanonicalLinks.scala
app/controllers/DigitalPack.scala
app/controllers/DigitalSubscription.scala
app/controllers/GeoRedirect.scala
app/controllers/RegularContributions.scala
app/controllers/Subscriptions.scala
app/services/stepfunctions/SupportWorkersClient.scala
app/views/digitalSubscription.scala.html
app/wiring/AppComponents.scala
app/wiring/Controllers.scala
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/helpers/routes.js
assets/pages/digital-subscription-checkout/__tests__/digitalSubscriptionCheckoutReducerTest.js
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js
assets/pages/new-contributions-landing/contributionsLandingActions.js
conf/routes
test/controllers/SubscriptionsTest.scala

This is part 3 of the work to hook support-frontend up to support-workers for Digital Pack creation.
The main part of this PR is the new endpoint for the checkout form to post to to create a state machine execution, but to make sure that this works I've also added basic code to post to it from the checkout form. 
This means we can now actually create a Digital Pack subscription end to end from support-frontend!
See the checklist below for next steps.
[**Trello Card**](https://trello.com/c/5N8LQ5yU/2060-be-able-to-trigger-the-creation-of-a-digital-pack-subscription-via-support-frontend)
* Create a new controller for digital subscriptions as the `Subscriptions` one was getting pretty big
* Factor out some behaviour from the Subscriptions controller into a trait so that it can be mixed into …

Digipack support workers3

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/internationalisation/contributions.js
assets/pages/new-contributions-landing/components/ContributionBackground.jsx
assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
assets/pages/new-contributions-landing/components/ContributionTicker.jsx
assets/pages/new-contributions-landing/contributionsLanding.jsx
assets/pages/new-contributions-landing/contributionsLanding.scss
public/ticker.json

Also makes `ContributionUsTicker` into `ContributionTicker` parameterised on `tickerJsonUrl`, allowing us to put **all** country-specific rendering info into `assets/helpers/internationalisation/contributions.js` 
US page now looks like this for everyone.

Remove US landing page test, keeping ticker & copy

---

app/views/digitalSubscription.scala.html
assets/helpers/billingPeriods.js
assets/helpers/contributions.js
assets/helpers/externalLinks.js
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/helpers/paymentIntegrations/newPaymentFlow/stripeCheckout.js
assets/helpers/subscriptions.js
assets/helpers/user/user.js
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js
assets/pages/regular-contributions/helpers/ajax.js
assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingActions.js
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js

This is the next step in wiring up the Digital Pack checkout.
Most of this PR is taken up with a refactor of the way that billing periods are represented in support frontend. Previously we've had 2 separate types representing billing periods; one for contributions and one for subscriptions, this limits code reuse, is different to the back end where there is only one type and is generally a bad idea!
I have now consolidated the `BillingPeriod` types and values in a new file billingPeriod.js and used these throughout the codebase. I will probably do the same for payment methods next as this is similarly fragmented.
This PR also removes hard coded dummy values from the Digital Pack checkout and replaces them with the correct values.
[**Trello …

Digital subscription checkout

---

assets/pages/new-contributions-landing/contributionsLandingInit.js

[This PR](https://github.com/guardian/support-frontend/pull/1335/files) broke recurring Stripe payments, as it broke the mechanism for loading the stripe library into the redux store. 
Essentially, we were trying to store the Stripe library into `thirdPartyPaymentLibraries.STRIPE.REGULAR`, which doesn't exist in our state definition, when really we want to put the regular library into both `thirdPartyPaymentLibraries.STRIPE.MONTHLY` and `thirdPartyPaymentLibraries.STRIPE.ANNUAL`.  
This PR fixes it. I've also added types to the parameters for `initialiseStripeCheckout`, which would have prevented this bug in the first place.

Fix stripe recurring payments

---

assets/helpers/flashSale.js

The end date we had for the Digital Pack flash sale was incorrect, we had 0:00 on the 3rd of Jan, whereas it should be 0:00 on the 4th.

Change the end date for the digipack flash sale

---

assets/pages/new-contributions-landing/components/ContributionThankYou.jsx
assets/pages/new-contributions-landing/components/ContributionThankYouPasswordSet.jsx

To make the marketing preferences button more prominent

Move survey below marketing in thank you page

---

assets/components/subscriptionBundles/paper.jsx
assets/components/subscriptionBundles/paperDigital.jsx
assets/helpers/flashSale.js

Existing flash sale work means we just need to add in a new flash sale and it automagically works on `/uk` and `/uk/subscribe`. Yay!
The upcoming print flash sale will require changes `/uk/subscribe/paper` (to follow) and those changes can bump the flash sale date to be valid so that the flash sale doesn't appear on `/uk` and `/uk/subscribe` but not `/uk/subscribe/paper`
So, this is just the part where we add the flash sale to flashSale.js and confirm that the changes don't make anything look wacky on  `/uk` and `/uk/subscribe`.
To support the flash sale.
[**Trello Card**](https://trello.com/c/AMzW3SFV/2110-print-sale-updates)
* Adds the paper and paper+ flash sale to flashSale.js
Below all with flash sale active
(just to show: the flash sale copy changes haven't introduced glaring CSS …

Add in print and print+ flash sale: part 1

---

assets/helpers/externalLinks.js
assets/helpers/flashSale.js
assets/helpers/subscriptions.js
assets/pages/paper-subscription-landing/components/content.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx

To support the print flash sale. 
[**Trello Card**](https://trello.com/c/AMzW3SFV/2110-print-sale-updates)
During a flash sale
* Updated heading 
* Updated prices displayed
* Once the user selects a plan, we send them to the appropriate checkout page on subs-frontend with the promo code applied
* Details of "Offer is for the first year. Standard subscription rates apply thereafter." added below the plans. 
note: paired with @jacobwinch 
Compare to when flash sale is not on: https://support.theguardian.com/uk/subscribe/paper
`/uk/subscribe/paper`
| mobile-ish        | tablet-ish           | big desktop screen  |
| ------------- |-------------| -----|
| <img src="https://user-images.githubusercontent.com/3072877/50653104-5a7eca00-0f80-11e9-82b1-2ecc8be97862.png" height=400>   | <img …

Updates to the print product page for the print flash sale.

---

assets/pages/subscriptions-landing/components/featuredProductAb.jsx

https://github.com/guardian/support-frontend/pull/1346
⬆️ There is a print flash sale starting today, but we'd like the countdown timer to appear later on. TBD if we will raise a PR just to add it back in whenever we want it, or some kind of feature to enable it x days before the end of the sale. Regardless, we should disable it for now. 
[**Trello Card**](https://trello.com/c/NyBumRDL/2134-countdown-timer-should-only-appear-during-the-last-week-of-the-sale)
* Disable the countdown timer. There is a trello card about enabling it linked above. 
| timer on (before this PR)  | timer back off (after this PR)       |
| ------------- |-------------| 
| <img src="https://user-images.githubusercontent.com/3072877/50689488-d3822e00-1021-11e9-8ce8-5497f1e447fb.png" height=400>   | <img …

Disable the countdown timer.

---

assets/helpers/internationalisation/contributions.js
assets/pages/new-contributions-landing/contributionsLanding.scss

The campaign is over, we want to go back to the default landing page

Remove US end-of-year campaign from landing page

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/checkouts.js
assets/helpers/contributions.js
assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
assets/pages/new-contributions-landing/contributionsLandingInit.js

Serves customised versions of the site based on two URL parameters:
- `contributionTypes`: this is a comma-separated list of contribution types (must be `one_off`, `annual`, or `monthly`)
- `defaultContributionType`: this a contribution type (`one_off`, `annual` or `monthly`) which must be in the available contributionTypes, if limited by the URL
e.g.
- https://support.theguardian.com/uk/contribute?defaultContributionType=annual&contributionTypes=one_off,annual

Set contribution types through URL parameters

---

app/controllers/DigitalSubscription.scala

I noticed that this log level was incorrect (Sentry emailed me about it whilst I was testing).

Use correct log level for success messages

---

assets/components/productPage/productPageHero/productPageHero.jsx
assets/components/productPage/productPageHero/productPageHero.scss

This prop added a very specific style of headline (`Become a Guardian Weekly subscriber`) that has since gone fallen out of use. It also didn't support different background colours. Even if we were to incorporate this in the future it makes more sense to put it as a child of that particular hero rather than globally.

Remove headline prop from productPagehero

---

assets/components/productPage/productPageButton/productPageButton.scss
assets/pages/showcase/showcase.scss

Tiny fix for an issue where the svg would overlap the button., adds z-indexes so the button is always on "top" of the svg.
While I was here I also fixed the button sizing because they were slightly too large on this page and it's been bugging me for ages.

Fix contributions link on showcase page on mobile

---

assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss

Updates the thank you page header to match the one from the main checkout, this solves an issue with how it displays on mobile and is more closely aligned with the original design:

Fix header on checkout thank you page

---

assets/components/marketingConsentNew/marketingConsent.jsx
assets/components/ui/uiButton/uiButton.jsx

Earlier today in #1366 I refactored `uiButton` so in the event of it not having an `href` or `onClick` it would render as a div, under the assumption a button with neigher of these elements would always be presentational and not do anything (similar to disabled)
Boy did that backfire, i forgort, forms can have `<button type=submit">` which automatically becomes a form submit button and doesn't need any behaviour.  that PR accidentally turned all of those into divs, making forms impossible to submit. needless to say that was very bad.

fix uibutton

---

assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js

`POST /subscribe/digital/create `
and 
`POST /contribute/recurring/create`
accept the same request body and both start the process of creating a recurring payment via support-workers. So, `postRegularPaymentRequest()` is used by both the recurring contributions and digital pack checkout. 
Both create endpoints currently may return a 500, but when that happens, this happens:
(and the page hangs)
Try it out: 
- force a 500 response
- go through the checkout in `https://support.thegulocal.com/uk/contribute` 
(the same applies to https://support.thegulocal.com/uk/subscribe/digital/checkout?displayCheckout=true)
then checkout this branch and instead see an error
[**Trello Card**](https://trello.com) - there isn't one
* When calling `POST /subscribe/digital/create ` or `POST …

Handle 500s on calls to endpoints that create subscriptions

---

cloud-formation/cfn.yaml

We have decided that email should only be used for alarms that need an instant response.  The warnings will be analysed at the end of the previous sprint through a new Cloudwatch Dashboard in AWS.  We can then plan into a sprint.
@joelochlann @tomrf1 @jranks123

remove warnings alarm - this will come from a dashboard in future

---

app/controllers/DigitalSubscription.scala
assets/components/adFreeSection/adFreeSection.jsx
assets/components/adFreeSection/adFreeSection.scss
assets/components/optimizeExperimentWrapper/optimizeExperimentWrapper.jsx
assets/components/priceCta/priceCta.jsx
assets/components/priceCta/priceCta.scss
assets/components/ui/uiButton/uiButton.jsx
assets/helpers/externalLinks.js
assets/pages/digital-subscription-landing/components/ctaAbTestWrapper.jsx
assets/pages/digital-subscription-landing/components/ctaSwitch.jsx
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/components/form.jsx
assets/pages/digital-subscription-landing/components/independentJournalismSection.scss
assets/pages/digital-subscription-landing/components/promotionPopUp.jsx
assets/pages/digital-subscription-landing/components/promotionPopUpReducer.js
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
assets/pages/digital-subscription-landing/digitalSubscriptionLandingActions.js
assets/pages/digital-subscription-landing/digitalSubscriptionLandingReducer.js
assets/pages/digital-subscription-landing/helpers/ctaTypeAb.js

Sorry for the massive PR,  this updates the DP page to accommodate the AB test about choosing frequency on the page itself. ([trello](https://trello.com/c/vavDkdpk/1983-show-monthly-and-annual-pricing-options-on-dp-product-page)) Doing this comes with some caveats:
- The redux store's shape has been changed to allow for the selected pack to be stored
- The design has been tweaked all over for both variants in terms of fonts and sizes to match the new templates. (thanks @jesseyuen !!!)
- The ad-free block is white now so as to not outshine the payment options block, which makes it a bit weird on the original variant.
- I've tweaked the optimize component to be able to pass a `force_optimize_ab_variant` parameter to enrol yourself in a variant id in testing, this only applies if there's no …

Digipack landing buttons AB test

---

app/controllers/DigitalSubscription.scala

In the digital pack checkout, we want to add some server side validation in case the client side validation doesn't run for some reason. 
Currently, if the first name or last name comes through as an empty string in the request, we wish to just short circuit and return an error because it's not even worth trying to create a digital subscription. Some basic request body validation was added here: https://github.com/guardian/support-frontend/pull/1367
But if the validation fails, we should return a 400 rather than a 500.
That way, we can display a more useful error message to the user, prompting them to check the details they gave us in the form, rather than the default "Sorry, something has gone wrong." message. 
That's what this PR is about. 
[**Trello …

return a bad request if we know the request to /subscribe/digital/create is missing information

---

app/utils/SimpleValidator.scala
test/utils/SimpleValidatorTest.scala

On calls to `POST /subscribe/digital/create`, we may know based on the request body that there is no point in triggering the call to create a digital subscription. 
https://github.com/guardian/support-frontend/pull/1367 (and others) added validation so that if firstName or lastName are empty, we return an error (and display an error to the user).
We should also get the user to check their details if they select Canada or the US, but they do not select a state, so this PR adds that check. Also added is that payment details received by `POST /subscribe/digital/create` are not empty strings. 
Note that even if country is left unselected, we default it to the UK here: https://github.com/guardian/support-frontend/blob/master/assets/pages/digital-subscription-checkout/helpers/paymentProviders.js …

Check state and that payment fields are nonempty in server side validation for the digital pack checkout

---

build.sbt
project/plugins.sbt

Scalariform and scalastyle contradict each other. One of them has to go.
The problematic case I have discovered is where the line is too long for scalastyle, but scalariform doesn't allow you to split it across 2 lines.

Remove scalariform

---

assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js

Because people in those countries cant use it
[**Trello Card**](https://trello.com/c/Xaq1bzCy/2175-hide-direct-debit-payment-option-if-country-other-than-uk-is-selected)
* Always payment method to Stripe if country doesn't support DD
* Reset payment method to Stripe if country switches and the country doesn't support DD
* Hide form if country doesn't support DD

DIsable direct debit if country doesn't support it

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/checkouts.js
assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
assets/pages/new-contributions-landing/contributionsLandingInit.js

As a follow up to https://github.com/guardian/support-frontend/pull/1207/files, we want to run a global contributions types test. Although we ran this already in the US, we will rerun it to give us further confidence in the results. 
We will analyse the test from 2 perspectives, US and non-US (combining GB, AU and ROW)
The variants are: 
|Control|
|-------|
|![image](https://user-images.githubusercontent.com/2844554/51542737-d8cdde00-1e53-11e9-846f-d730b3ab43b1.png)|
|Default Annual|
|-------|
|![image](https://user-images.githubusercontent.com/2844554/51542765-ea16ea80-1e53-11e9-9994-42aa128f46e1.png)|
|Default Annual no monthly|
|-------|
|![image](https://user-images.githubusercontent.com/2844554/51542793-fe5ae780-1e53-11e9-8f25-8cc103370d28.png)|

Global Contribution Types test

---

app/admin/SettingsProvider.scala
app/controllers/DigitalSubscription.scala
assets/components/checkoutExpander/checkoutExpander.jsx
assets/components/checkoutExpander/checkoutExpander.scss
assets/components/forms/formHOCs/withFooter.jsx
assets/components/forms/formHOCs/withFooter.scss
assets/components/forms/standardFields/formFields.scss
assets/helpers/externalLinks.js
assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
webpack.common.js

Add a 'ghost' email field to the checkout page and two links to get help changing the feld or signing out
[**Trello Card**](https://trello.com/c/vz1dS1Vb/2091-add-email-play-back-and-signout-option-to-digital-pack-checkout)

Add email play back and signout option to Digital Pack checkout

---

assets/helpers/page/commonReducer.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js

Solves a bug where stripe was picking up the page's internationalisation instead of the selected country.
We previously spoke about removing urls with the country on them but it has dawned on me we do still want to pass the country to preserve the selection from the landing page. For now i've just done nothing on this as a result
Haha so turns out the checkout form was sharing an action name (`SET_COUNTRY`) with the common reducer. I don't believe this was desired behaviour but this fix takes advantage of that to round up the `SET_COUNTRY` method and set the users country in that area. I believe a fully cooked solution for this bug should use that approach (the way I see it, setting the country in the form should dispatch this second `SET_COUNTRY` action rather than just relying on the …

The user should pay in the currency we allowed them to select

---

assets/pages/digital-subscription-landing/components/form.jsx

There was a accuracy update required based on incorrect design assets.
[**Trello Card**](https://trello.com/c/YkggErle/2177-update-incorrect-info-on-annual-option-for-dp-test)
* Copy update to sale savings
* Removed rounding part of the `showDiscount` function

Removed rounding and update saving amount

---

app/controllers/DigitalSubscription.scala
app/services/stepfunctions/SupportWorkersClient.scala
app/utils/SimpleValidator.scala
assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js
assets/pages/new-contributions-landing/contributionsLandingActions.js
build.sbt
test/utils/SimpleValidatorTest.scala

As of https://github.com/guardian/support-workers/pull/170, we can include a telephone number in the request to support-workers to create a digital pack, and it will get added to the salesforce contact. 
So, if someone in the checkout provides us with the telephone number, we should send it with the request so that it's added to the salesforce contact. 
[**Trello Card**](https://trello.com/c/zcaNKssy/2156-make-sure-telephone-number-if-provided-makes-its-way-to-salesforce)
* Use latest version of support-models
* Include telephone number in the request to `/subscribe/digital/create` so that it will be included in the request to support-workers to create a digital pack, and added to the salesforce contact.
⬇️ 
🎉 
related PRs:
https://github.com/guardian/support-workers/pull/170 …

If we collect a telephone number, send it with the request to create a digital pack. 

---

assets/helpers/__tests__/promiseTest.js

This test is unstable and has broken the build several times. 
The polling functionality is still being tested here https://github.com/guardian/support-frontend/blob/master/assets/helpers/__tests__/promiseTest.js#L58-L71 (pollUntilPromise calls sleepPromise) so I think this is superfluous anyway.
* Remove unstable test

Remove an unstable test

---

assets/helpers/abTests/abtestDefinitions.js
assets/helpers/checkouts.js
assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
assets/pages/new-contributions-landing/contributionsLandingInit.js

It was taking a hit in terms of AV (not In Year Revenue, but never mind that for now), so we are removing the variant. This will also mean we get the results for the Default Annual variant quicker.

Turn off default annual no monthly variant of Contributions Types test

---

assets/components/button/button.scss
assets/components/forms/customFields/radioInput.scss
assets/stylesheets/gu-sass/colours.scss

We were missing a couple, now you can tab through the whole form and know where you are:
It also introduces a ✨ new shade of green ✨ bespokedly designed just for us because we are worth it
[**Trello Card**](https://trello.com/c/lndiPTMX/2184-make-sure-all-form-components-have-clear-focus-states)
* Outline button hover & focus aligned with @zeftilldeath's design library
* Radio button hover & focus aligned with @zeftilldeath's design library

Add focus and hover states to checkout form widgets

---

assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

If the user lands on an intl checkout they will have direct debit preselected as their payment option

default to stripe if country does not support dd

---

assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/components/form.jsx
assets/pages/digital-subscription-landing/components/productBlock.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss

I missed some copy updates on this card the fist time around and a safari layout issue was noticed whilst updating this page. 
[**Trello Card**](https://trello.com/c/YkggErle/2177-update-incorrect-info-on-annual-option-for-dp-testhttps://trello.com/c/YkggErle/2177-update-incorrect-info-on-annual-option-for-dp-test)
* Copy updates
* Remove some fixed height css in `class="digital-subscription-landing-header__wrapper"` 
* Added a wrapper around h2 to which spans full width whilst maintaining a max width of the text within 
* Added css to maintain layout in Safari 11.1.2
^ broken
Fixed!

Copy update, small layout update a safari fix

---

assets/components/signout/signout.jsx
assets/helpers/externalLinks.js
assets/helpers/routes.js
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js

Currently the sign out link on the new Digital Pack Checkout flow is broken (results in 404). 
This change allows us to sign users out > drop them into the sign-in flow > back into Digital Pack Checkout.
* Reuse function which does this for contributions page
* Remove logout URL

Fix signout link

---

assets/helpers/abTests/abtestDefinitions.js
assets/pages/new-contributions-landing/contributionsLandingInit.js

Following [this test](https://github.com/guardian/support-frontend/pull/1382), we have decided to default to annual contributions, globally.

Default to annual contributions

---

assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.scss

As part of the Print Page optimisation task we are added a more prominent hover style to the `component-product-page-plan-form__item` card.
[**Trello Card**](https://trello.com/c/ecK4Jpqq/2146-print-product-page-optimisation)
* Added a background colour change to the hover and focus style

Additional hover affordance added

---

app/services/stepfunctions/SupportWorkersClient.scala

This client is now used to create Digital Pack subs (and will soon support other subscriptions products), so the logging should not reference contributions.
* Improve log messages
N/A

Don't reference recurring contributions in SupportWorkersClient

---

assets/components/productPage/productPageContentBlock/productPageContentBlock.jsx
assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
assets/components/productPage/productPageTabs/productPageTabs.scss
assets/pages/paper-subscription-landing/components/content.jsx
assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
assets/stylesheets/gu-sass/typography.scss

The tab component in S&C needed visual alignment with .com.
It's not yet as tidy as it can be and will be revisited before it goes into Storybook but will do for now!
[**Trello Card**](https://trello.com/c/ecK4Jpqq/2146-print-product-page-optimisation)
* Style updates to tab component

Aligning S&C tabs with theguardian.com style

---

assets/components/button/button.scss

I mean look at them:
before:
after:

Fix hollow buttons showing up as grey in safari & ffx

---

assets/pages/new-contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
assets/pages/new-contributions-landing/contributionsLandingActions.js
assets/pages/new-contributions-landing/contributionsLandingReducer.js

Now that the Stripe contract has been updated to take Google Pay into account, we (almost) can allow the Payment Request Button to be used to take one off payments. Woohoo!
| The Stripe Payment Request Button in all it's glory |
|------------|
|![stripe](https://user-images.githubusercontent.com/2844554/51924617-42666300-23e5-11e9-911f-e00996421801.gif)|

Add Stripe Payment Request Button support

---

assets/helpers/flashSale.js

🎵 It's the most wonderful time of the year
Time for a print flash sale (again)
Immediately following the current print flash sale, we shall run another, this time 50% off for 3 months. 
This PR assumes the current version of the print product page. @walaura @jesseyuen if I've caused chaos with the print page changes to follow, let me know if I can help.
[**Trello Card**](https://trello.com/c/VrGs0HFv/2157-print-flash-sale-update-4th-feb)
* Add in flash sales for print and print+
* This is the first time we have reason to have two flash sales in the list for the same product. Throughout `flashSale.js` we were getting the list of sales for a given product and country group and then just taking the head of the list. But when we have a back to back sale, then we may fetch details for the …

Feb print flash 2

---

app/utils/SimpleValidator.scala
test/utils/SimpleValidatorTest.scala

The client side logic is supposed to update the currency displayed to the user whenever the billing country is updated. If the server receives a request where the country and currency combination is not standard, it is likely that something has gone wrong client side (e.g. we showed the user one price/currency, but will charge them in another). 
In such cases, I think it's better to fail the validation than allow the request to be processed by support-workers.
Obviously there is still some client-side work required to fix the bug which is currently allowing this to happen, but this validation should alert us if we introduce this type of problem again.
[**Trello Card**](https://trello.com/c/GMQmzcBp/2196-investigate-bug-which-allows-users-to-create-digital-pack-subs-with-invalid-country-cur …

Ensure that currency and country combination are supported when validating requests

---

assets/pages/paper-subscription-landing/components/hero/hero.jsx

The offer roundel on the updated Print product page is incorrect - it states the discount is 52% off for 3 months, but it is actually 52% off for a year.
[**Trello Card**](https://trello.com/c/ecK4Jpqq) 
* Updated copy for "For 3 months" to "for a year" in the offer roundel
Current:
New:

Update offer roundel from "for 3 months" to "for a year" on Print product page

---

assets/pages/paper-subscription-landing/components/content/collectionTab.jsx

There's a rogue ? in the title "How to use our vouchers" on the Print product page, so I've removed it.
[**Trello Card**](https://trello.com/c/ecK4Jpqq)
* Remove the ? from "how to use our vouchers"
Current:
New:

Remove ? from title in vouchers tab on Print product page

---

assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx

The copy and link to offer terms and conditions on the Print product page are incorrect and need to be updated to relate to the 25% off for 12 months offer.
[**Trello Card**](https://trello.com/c/fvlfJSdm)
* Remove reference to "6 for 6" promotion. This means that the copy won't need to be updated in future because it refers generically to "promotion terms and conditions"
* Update Ts&Cs link from 6 for 6 to https://subscribe.theguardian.com/p/GCB80X/terms?country=GB (Ts&Cs page for 25% off for 12 months offer)
Current:
New:

Update Print product page Ts&Cs copy + link

---

assets/helpers/subscriptions.js
assets/pages/paper-subscription-landing/components/content/form.jsx

Better highlight the valuer provided
[**Trello Card**](https://trello.com/c/AYwIzZ8R/2191-update-prices-on-cards-for-paper-product)

Show regular paper prices during flash sale

---

assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx

Because there's a sentence that doesn't agree grammatically!
[**Trello Card**](https://trello.com/c/ecK4Jpqq)
* Remove "y" to make the sentence "we can't delivery" work
Current:
New:

Remove y from "delivery"

---

assets/pages/paper-subscription-landing/components/content/collectionTab.jsx

Some of the copy updates to the Print product page were missed. This is one in a series of teeny tiny PRs to clean them up.
[**Trello Card**](https://trello.com/c/MKj2vchm)
* Change "heading away" to "going on holiday"
Current:
New:

Copy update: "going on holiday"

---

assets/components/button/_sharedButton.jsx
assets/components/dialog/dialog.jsx
assets/components/dialog/dialog.scss
stories/dialog.jsx

Implement some of @SiAdcock's suggestions (the easy high api layer impact ones) in the dialog component #1416  
* Don't handle browser focus if it supports `<dialog>`
* Remove `modal` prop
* Add new `styled` prop that adds a modal-like appearance (this was previously tangled together with modal-ness. Most appearances will be custom but this makes it more satisfying to implement. (instant dialogs!)
* New default is for dialogs to not dismiss themselves when clicking out – to make implementers think about adding a close button (needed for keyboard users). the prop for this is now called `blocking` for simplicity
* Got carried away writing stories for this!

Dialog tweaks

---

cloud-formation/cfn.yaml

The app needs permission to access the catalog.json file in S3. This changes the cloud formation template to allow it.

Allow the app to access the catalog.json in S3

---

assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx

This is the second PR to update copy on the Print product page in line with the copy document. 
[**Trello Card**](https://trello.com/c/MKj2vchm)
* Update: "If you live in Greater London (within the M25), you can use The Guardian’s home delivery service. Don’t worry if you live outside this area you can still subscribe using our voucher scheme." to "If you live in Greater London (within the M25), you can use The Guardian’s home delivery service. If you don't, you can still subscribe using our voucher scheme." 
* Update: "Your subscribing deliveries will begin as quickly as five days from you subscribing" to "You'll receive your first newspaper as quickly as five days from you subscribing"
Current:
New:

Copy updates: home delivery details

---

assets/components/promotionSummary/__tests__/promotionSummaryTests.js
assets/components/promotionSummary/promotionSummary.jsx

There were some small bugs with the way that the `PromotionSummary` component handled various promotions. This fixes them and adds tests.
[**Trello Card**](https://trello.com/c/YDhuWZgm/2194-add-jest-test-for-promotion-summaries)

Fix annual promotion summary and add tests

---

assets/helpers/flashSale.js

To make a push for Digital Pack acquisition targets. 💰 
[**Trello Card**](https://trello.com/c/yV5FjLXB/2159-uk-dp-flash-sale-18th-feb)
* Adds in the UK Digital Pack flash sale from mid Feb to end of quarter
* Copy fix for the subheading of the currently running AU Digital Pack flash sale
Note: countdown timer will not appear after https://github.com/guardian/support-frontend/pull/1455 is merged

add mid Feb UK digital pack flash sale

---

assets/helpers/__tests__/flashSaleTest.js
assets/helpers/flashSale.js
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx

doesn't look terribly urgent
[**Trello Card**](https://trello.com/c/NyBumRDL/2134-countdown-timer-should-only-appear-during-the-last-week-of-the-print-sale)
* Adds a function that determines if the now is x days from the end of the sale so that we can use it to determine if we should show the countdown timer
* Use this new function to only show the countdown timer 7 days before the end of the digital pack flash sale
This is just changing the conditions by which we show the countdown timer or not, so n/a I think

Show countdown timer for last 7 days on the DP product page during a flash sale. 

---

assets/helpers/paymentIntegrations/newPaymentFlow/stripeCheckout.js

This PR fixes an issue which causes us to display the wrong price in Stripe Checkout (see screenshots), presumably because:
```
19.99 * 100
1998.9999999999998
```
* Round to nearest penny/cent before passing amount to Stripe.
Before fix:
After fix:

Fix rounding error

---

assets/helpers/abTests/__tests__/abtestTest.js
assets/helpers/abTests/abtest.js
assets/helpers/abTests/abtestDefinitions.js
assets/helpers/abTests/annualAmountsTest.js
assets/helpers/abTests/helpers.js
assets/helpers/page/page.js

Amounts are configured using an s3 file (soon to be managed from Support Admin Console).
We also need the ability to run amounts tests which override the configured defaults.
For now, test amounts will be configured in the code (client-side).
Note - we are running a new annual amounts test this week, but have not decided on the exact config yet. I'll update assets/helpers/abTests/annualAmountsTest.js when this has been decided.
[**Trello Card**](https://trello.com/c/dWLgtddF/339-enable-amounts-tests-to-override-sac-configured-amounts)

Enable amounts tests

---

assets/helpers/externalLinks.js

These minor changes are required to set up the redirect test for the Digital Pack checkout.
[**Trello Card**](https://trello.com/c/HoZPd10P/1514-a-b-test-on-digital-pack-checkout-flow)
* Use correct environment for subs links (CODE digital pack landing page will now redirect to CODE checkouts).
* Set annual query param (where appropriate), so that the correct billing period is [preselected](https://github.com/guardian/support-frontend/blob/master/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js#L193-L197) when users are redirected to the new flow.

Add query param to pre-select billing plan and use correct subs URL based on environment

---

assets/helpers/flashSale.js

There are a few rounding errors and inconsistencies between the landing and checkout pages. This eliminates those inconsistencies.
Note that in some cases we will charge a user one cent or pence _less_ than advertised, but this is better than the current situation (where we are charging users slightly more than the price displayed).
* Fix landing page pricing

Fix flash sale pricing issues

---

assets/helpers/abTests/abtest.js
assets/helpers/page/page.js
assets/helpers/tracking/acquisitions.js
assets/helpers/tracking/ophanComponentEventTracking.js

Up until now we haven't been sending Optimize experiments to the Ophan pageview tracking. This has made it impossible to do things like funnel analysis in the Data Lake for Optimize tests.
This PR changes the app so that we now send any Optimize test information which is stored in session storage to Ophan along with the native AB tests. Because of the way that Optimize tests on the current page are loaded however, there is also now a callback which is fired when a new test is found.
[**Trello Card**](https://trello.com/c/4kEtf6ia/2181-ab-test-tracking)

Send Optimize experiments to the Ophan pageview tracking

---

assets/helpers/paymentIntegrations/newPaymentFlow/readerRevenueApis.js
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/components/thankYouPendingContent.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/helpers/paymentProviders.js

AS A customer
I WANT you to tell me that my payment is still pending of it's not instantly processed
SO THAT I know my order may not have been processed yet
[**Trello Card**](https://trello.com/c/k1YYFvXn/2124-version-of-the-dp-checkout-thank-you-page-for-order-timeout-scenarios)
* new `{| paymentStatus: 'success', isPending: true |}` payment result (i dont like it help)
* new `thankyou-pending` stage

Version of the DP checkout thank you page for order timeout scenarios

---

assets/helpers/tracking/acquisitions.js

In certain circumstances it is possible for ab tests to be included in referrer acquisition data multiple times. This prevents that from happening

Deduplicate ab tests before sending them in referrer acquisition data

---

assets/components/directDebit/directDebitForm/directDebitForm.scss

Fixed error message showing over the of the legal copy on the payment pop up
* added one line of CSS
TO

style: show error

---

app/actions/CustomActionBuilders.scala
app/controllers/DigitalSubscription.scala

We are currently using the wrong identity client id as part of the new Digital Pack checkout flow. Notably, we display the following text (which doesn't make sense in the context of this flow):
> To complete your contribution, please sign in to your Guardian account or quickly create one.
> 
> This will help you manage future payments. Staying signed in means you’ll no longer see the “since you’re here” messages asking you to support our journalism.
This PR fixes the problem by using our very own client id.
* Use correct client id
Before:
After:

Use subscriptions client id

---

assets/helpers/optimize/optimizeScript.js

Up until now we have been checking two Optimize containers for tests, this is unnecessary because one of them is never used, so I have removed it.
I have also removed the page hiding snippet as it makes the site appear slow for users with ad blockers or in some incognito modes. I've run quite a few tests with different connection speeds and the flicker behaviour actually appears no worse than before, however it is something that we will need to keep an eye on when setting up AB tests.

Remove page hiding snippet and extra container id

---

assets/components/featuredProductHero/featuredProductHero.scss
assets/components/subscriptionsByCountryGroup/components/internationalSection.jsx
assets/components/threeSubscriptions/threeSubscriptions.scss
assets/stylesheets/skeleton/html.scss

The subs landing page layout looked a bit broken after the new nav was added. The subs landing is not on the new template so the fixes will be enough to make the layout feel more _coherent_ whilst avoiding a significant refractor. I've tried to be unobtrusive as possible so hopefully haven't broken anything else  
It's still not quite perfect but looks a lot better and I think it will help until we eventually redesign and move this page onto the new template.
P.S. - I'm only interested in fixing alignment in the **UK banner** at this stage. 
P.P.S - My commit messages are a bit vaguer than I wanted them to be, sorry. 
[**Trello Card**](https://trello.com/c/hvM44uZc/2220-subs-landing-layout-needs-adjustment)
* Padding/width changes to the subs landing her panel
* Type updates on the …

Subs landing banner and layout tweaks

---

assets/components/forms/standardFields/error.scss

We weirdly missed this in #1504's merge (I recall changing these to the right ones??) 😿

Make the form errors red again

---

app/controllers/Application.scala
app/controllers/CanonicalLinks.scala
app/wiring/Controllers.scala
test/controllers/ApplicationTest.scala

We were missing this for seo reqs
[**Trello Card**](https://trello.com/b/emHrtNJX/support-platform-health)

Add canonical link to support page

---

app/controllers/DigitalSubscription.scala
app/controllers/GeoRedirect.scala
assets/components/gridImage/gridImage.jsx
assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
assets/pages/digital-subscription-landing/components/productBlock.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
conf/routes

This will allow urls with the European country symbol to show Euros as the currency, on the digi pack product page.
[**internationalise-digital-pack-product-page** Trello Card](https://trello.com/c/ZfGLlSyQ/2186-internationalise-digital-pack-product-page)
* I have made changes to the Play routes to allow eu/subscribe/digital to work
* The product-block and associated css has been updated to include EURCountries
eu url 
eu pricing

Internationalize digi pack product page

---

assets/helpers/url.js
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/components/thankYou/appsSection.jsx
assets/pages/digital-subscription-checkout/components/thankYou/marketingConsentContainer.jsx
assets/pages/digital-subscription-checkout/components/thankYouAlreadyLiveContent.jsx
assets/pages/digital-subscription-checkout/components/thankYouContent.jsx
assets/pages/digital-subscription-checkout/components/thankYouExistingContent.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
conf/routes

AS A customer I WANT to be shown a message when I'm trying to buy Digital Pack but already have it SO THAT I don't end up buying it twice in error.
This PR includes a new stage for the checkout, accessible at `subscribe/digital/checkout/existing` should we do a server side redirect.
[**Trello Card**](https://trello.com/c/06A5kQwD/2226-message-for-customers-who-have-signed-in-to-get-into-checkout-but-already-have-digital-pack-ty-page)

Message for customers who have signed in to get into checkout but already have Digital Pack - Front

---

assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js

Because journalism is in crisis
[**Trello Card**](https://trello.com/c/nWZR6loN/2202-remove-6-for-6-from-gw-product-page)
* Remove the 6for6 price tier
* Default to Quarterly (@SarahLaughton !)
* Rename `billingPeriods` to `displayBillingPeriods` so as to imply that this may be a subset of the periods – we are keeping 6for6 in the data model for a bit longer than this removal so we can't eviscerate all of it just yet.

Remove 6for6 from GW page

---

app/controllers/DigitalSubscription.scala
app/services/MembersDataService.scala
app/wiring/Controllers.scala
assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
assets/pages/digital-subscription-checkout/components/thankYou/hero.jsx
assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
assets/pages/digital-subscription-checkout/thankYouExisting.jsx
conf/routes
test/controllers/SubscriptionsTest.scala
webpack.common.js

Second bit of #1506 
Fun stuff: we had to create this page its own route in both scala and react because otherwise it was weirdly entangled with the checkout code.
**Do not merge yet** we are writing tests
[**Trello Card**](https://trello.com/c/06A5kQwD/2226-message-for-customers-who-have-signed-in-to-get-into-checkout-but-already-have-digital-pack-ty-page)

TY page if the user has a DP

---

.flowconfig
assets/components/pageSection/pageSection.jsx
assets/components/pageSection/pageSection.scss
assets/helpers/render.js
assets/pages/error/components/errorPage.jsx

Right now, if we get a runtime error inside the react app everything goes like *sploosh*! *kaboom*! *shebang*! and loads a white page. This is not ideal for several reasons.
This PR adds a try/catch to load a grotesquely ugly error page instead. (we have a separate card to overhaul these) – It's async so it only loads the error page code after things go awry.

Graceful-er failures

---

assets/pages/paper-subscription-landing/components/hero/hero.jsx

The print roundel still states the flash sale saving. It should now state 31%.
* Updated roundel to say 31% saving

Update print hero roundel.jsx

---

assets/pages/paper-subscription-landing/components/hero/hero.jsx

There's no time limit on the "save up to 31%" message, so I've removed "for 3 months" from the roundel, and the saving is actually 37% now because the newsstand price has gone up since we last had BAU pricing on the site.
* removed "for 3 months" from the roundel
* updated % saving to 37% in the roundel and in the header copy
⬇️

Update print roundel v2.jsx

---

assets/helpers/flashSale.js
assets/helpers/productPrice/productPrices.js

So people down there know there's a sale going!
This also updates the prices to display the country dollars are from as it was getting confusing. @SarahLaughton 
[**Trello Card**](https://trello.com/c/sAZTOf67/2235-dp-flash-sale-pricing-not-reflected-on-ca-nz-or-eu-pages)

Add DP sale details for EU/NZ/CA

---

assets/pages/digital-subscription-landing/components/form.jsx

The fancy new system for reflecting pricing on product pages means we've temporarily lost wording that makes it clear that the price we're showing is the offer price that customers will pay for a set period of time. This PR covers adding some hard-coded wording that help to make that clearer while we figure out how promo codes should be automatically reflected on product pages in future.
[**Trello Card**](https://trello.com/c/mArnucUy)
* Added "for the first 12 months" to the monthly pricing card
* Replaced "every 12 months" with "for the first year" in the annual pricing card
Current: 
New:

Temporary offer wording for DP flash sale.jsx

---

assets/stylesheets/skeleton/reset-src.scss

because safari makes them grey otherwise. look at this :(

Transparent <button>s on the css reset
