- app/utils/QueryStringUtils.scala
fix: added variant to query string - when the query string is randomly created, it will now be created with “control” or “variant” e.g. formDesignTest=control
because analytics only works with "control" and "variant" at the moment it is using "on" or "off"
> fix: added variant to query string

- app/controllers/Application.scala
- app/utils/QueryStringUtils.scala
We are taking a gamble and assuming that the new design test isn't any worse than the existing design, so we are putting the control down to 20%. 
There is a risk that the variant is worse, which we will still learn if this is the case, just a bit slower. 
If our assumption is correct, then we can earn now and learn later.
> Change form design test to 20%

- app/utils/SimpleValidator.scala
I noticed a non-exhaustive match which would have thrown an exception when requests to create Digital Packs with PayPal were received.
* Ensure that BAID is not empty if the user tries to buy a Digital Pack with PayPal
> Add basic validation for PayPal

- app/controllers/CreateSubscription.scala
- app/controllers/DigitalSubscription.scala
- app/controllers/PaperSubscription.scala
- app/services/stepfunctions/SupportWorkersClient.scala
- app/wiring/AppComponents.scala
- app/wiring/Controllers.scala
- assets/helpers/routes.js
- conf/routes
- test/controllers/SubscriptionsTest.scala
- test/utils/SimpleValidatorTest.scala
We are in the process of migrating the creation of all subscriptions products to use support-frontend/workers. Since the call to create a subscription is going to be very similar for all subscriptions products, this PR refactors the existing code to remove any Digital Pack specifics.
As far as I can tell, the main difference we'll need to take into account when creating different products will be the validation rules that we use, so I've also tried to suggest an approach which allows the validation to be made product-specific.
This PR also adds an optional firstDeliveryDate to the CreateSupportWorkersRequest model, in preparation for https://trello.com/c/oRCVNC3s/2248-print-checkout-component-with-a-list-of-start-dates. Note that this PR doesn't wire that date through to the backend yet - …
> Refactor to use a generic endpoint for creating subscriptions

- yarn.lock
Snyk was unhappy about the version of `lodash` being pulled in by `fast-sass-loader`:
`Introduced through: support-frontend@1.0.0 › fast-sass-loader@1.4.7 › async@2.6.1 › lodash@4.17.10`
I've removed (`yarn remove fast-sass-loader`) and re-installed (`yarn add fast-sass-loader`) this dependency in an attempt to upgrade beyond the problematic `lodash` version.
> Snyk updates

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
After this pr: https://github.com/guardian/support-frontend/pull/1551
It turned out I had not included notintest in the handled cases.  This wouldn't usually happen because everyone is in the test, however the post deploy user is always forced to be not in the test, so it was crashing with a horrible error.  The type checker doesn't really have the ability to check that at present.
---
Unfortunately there was no stack trace so I had to just work out by trial and error what was wrong.  I'm not sure if there is a thing swallowing JS errors that we need to update as well?
The console errors for the browser just showing a generic error (copy and pastable version below)
```
console.js:35 Fatal error rendering a page id:new-contributions-landing-page-uk
e.(anonymous function) @ console.js:35
i …
```
> add notintest to the ab test

- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
Futher to https://github.com/guardian/support-frontend/pull/1555
I actually didn't look carefully enough.  I needed to also add the notintest into the if statement, as without it it wouldn't show the contribute button at all.
This does make me wonder if we should have put the if statement at all, as it was only needed to keep the type checker happy.
Before:
After:
@jranks123
> add notintest to the ab test part 2

- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreatePaymentMethodState.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreateSalesforceContactState.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreateZuoraSubscriptionState.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
When clients start sending a first delivery date to `/subscribe/create`, this will need to be wired through to the CreateZuoraSubscription lambda so that paper/magazine fulfilment can be set up correctly.
* Pass (optional) first delivery date through to CreateZuoraSubscription lambda
> Wire up first delivery date

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/BadRequestException.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
As of, https://github.com/guardian/support-frontend/pull/1560 requests to create a subscription can send an optional firstDeliveryDate.
This PR uses firstDeliveryDate to create a paper subscription.
The first delivery date is required for paper subscriptions, but irrelevant to digital pack subscriptions. I have added to the validation on `/subscribe/create` so that hopefully we won't end up in that state, but as long as firstDeliveryDate is an option, there's always the possibility it will be a None. 
[**Trello Card**](https://trello.com/c/9YE6DIdo/1959-update-support-workers-to-enable-it-to-create-print-subscriptions)
* uses firstDeliveryDate to create a paper subscription.
n/a
> Use first delivery date when creating a paper sub.

- support-frontend/app/views/test.scala.html
There was a change to the Animated Dots component that wasn't reflected in the placeholder CSS. This PR fixes it
> Fix animated dots

- support-frontend/scripts/css.js
- support-frontend/webpack.common.js
Enables us to use `*.module.scss` files like Create-React-App does to get scoped classnames rather than type them ourselves. This is opt-in and only affects `.module.scss` files. I'm keen to try this for some things.
The classnames get compiled by webpack to a BEM-like scoped human readable form based on the folder they are in, with a couple extra rules.
- `.root` should be the top level style for a component and won't show up 
- `/components` and `/pages` become singular
```jsx
import styles from './test.module.scss';
const InputWithButton = ({ onClick, ...props }) => (
<div className={styles.root}>
<div className={styles.header}>Test</div>
</div>
```
```css
.root {
color: red;
}
.header {
color: blue;
}
```
results in
```html
<div className="component-test">
<div …
```
> Support CSS modules

- support-frontend/assets/components/headers/roundelHeader/header.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
feat: changed Guardian logo form the round logo to the full text logo
Update to stlying
Changed Logo from the round logo to the long text logo
- New Logo
- Previous Logo
> feat: changed Guardian logo

- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Added css hover state to payment frequency tabs and amount buttons with custom colour matching the 'Contribute...' button.
We think that some users don't realise that they can change the payment frequency and that the hover state will provide a clearer affordance.
We want to track how may users read the required fields explainer.
[**Trello Card for hover**](https://trello.com/c/oZEVCAot/328-implement-hover-states-for-product-type-and-amount-buttons)
[**Trello Card for tracking**](https://trello.com/c/148LzjFX/330-put-tracking-code-in-place-for-expandable-required-fields)
> Added click tracking to the required for fields explainer details.

- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
So in https://github.com/guardian/support-frontend/pull/1563 I horribly broke the thank you page by not realising it shared a lot of the main styling.  So this pr basically adds in the cruicial parts that were lost.
---
---
@jranks123
> add back some of the styling needed for the thank you page

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
We're updating copy on the Weekly subs landing page to remove references to 6 for 6.
* Copy update
> Copy update to remove 6 for 6 references

- package.json
- support-frontend/package.json
- support-frontend/webpack.common.js
- support-frontend/yarn.lock
I lifted this from `identity-frontend`
What this exactly does is twofold – first, it makes webpack output a json with all the compilation stats, then adds a tool to turn that json into a more actionable viz of what's in each bundle.
> use `yarn stat` to generate a js bundle size chart for your enjoyment

- support-frontend/app/views/newContributions.scala.html
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
In the [previous PR](https://github.com/guardian/support-frontend/pull/1577) I added back some of the styling needed for the thank you page, but some of the new styling I had to move off to avoid affecting it.  I moved it to the gu-content__content-contributions class but forgot to add that class to the original non thank you page.  That meant the width wasn't limited at higher breakpoints
This PR fixes that.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/7304387/53635230-5e436b80-3c14-11e9-8040-d0c263b136b8.png)|![image](https://user-images.githubusercontent.com/7304387/53635245-67343d00-3c14-11e9-945f-830f018fbbad.png)|
320
480
740 (this looks a bit squashed but it doesn't seem to be worse than before)
1250
2560
[**Trello …
> Fix styling on contribute page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
The Frequency tabs ordering test was underwhelming, so we are dropping it in favour of this "Drop monthly" test.
|Control|Variant|
|---|---|
|![image](https://user-images.githubusercontent.com/2844554/53652499-f1929600-3c40-11e9-9b4d-79a7a4c6bedd.png)|![variant](https://user-images.githubusercontent.com/2844554/53652510-f9523a80-3c40-11e9-8f5f-84df5c43b37c.png)|
(Note: just look at the differences in Contribution Types, not the copy or amounts, those are separate tests that happen to be running)
> Drop monthly contributions test (and remove frequency tabs ordering test)

- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/pages/digital-subscription-checkout/helpers/paymentProviders.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/paper-subscription-checkout/helpers/paymentProviders.js
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
So that using the paper checkout will result in the ajax call `POST /subscribe/create`, which will in turn create a paper subscription via `support-workers`
[**Trello Card**](https://trello.com/c/s3bTXdKj/2281-get-the-paper-checkout-to-call-the-create-endpoint-to-create-paper-subs)
* `onPaymentAuthorised` now makes a regular payment request 
Note: currently copies the same address as both billing and delivery address.
> Get the paper checkout to call the create endpoint to create paper subs.

- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
I accidently put PayPal live for Digital Pack subscriptions, this switches it off again until we're ready to AB test.
> Hide PayPal

- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
We sometimes only want to allow one-off contributions. In this case, there is no need to show the contribution type tabs.
Only one-off:
Others:
> Hide contribution type tabs if only one-off is available

- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Somehow the spacing of the set password screen was a bit wide.  I thought it was caused by removing the new styling test (as that caused a lot of styling issues!) but actually it turned out it was present in the commit before hand.  But I'm still assuming it wasn't intentional even in that commit!
Rather than searching back throughout all history, I just played around with the CSS until it looked better.
|broken:|in commit `3839783fc10845d40e92da88368ce028c8cc4d86`|after fix|
|---|---|---|
|![image](https://user-images.githubusercontent.com/7304387/53872447-31b59800-3ff6-11e9-8d91-1314fd0648fc.png)|![image](https://user-images.githubusercontent.com/7304387/53872564-74777000-3ff6-11e9-8fea-7ece8c69ca7a.png)|![image](https://user-images.githubusercontent.com/7304387/53872662-996be300-3ff6-11 …
> improve spacing of set password form

- support-frontend/assets/pages/new-contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
This change makes it possible to add a message at the top of the form component.
This will be used for the upcoming AU campaign, but for now nothing uses this feature
**With contribution type tabs:**
**Without contribution type tabs:**
> Allow optional form message

- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLandingActions.js
- support-frontend/assets/pages/premium-tier-landing/components/priceCtaContainer.jsx
We want to switch over to sending 100% of traffic to the new Digital Pack checkout.
[**Trello Card**](https://trello.com/c/SvHHTplZ/2273-end-dp-checkout-ab-test-and-roll-new-dp-checkout-out-to-100-of-traffic)
> Switch off the Digital Pack checkout test

- support-frontend/assets/helpers/flashSale.js
Requested by our colleagues in Marketing. 
[**Trello Card**](https://trello.com/c/Llu1Cu0m/2284-end-the-dp-sale-on-the-17th-of-march)
* Remove the paper flash sales that have come and gone
* Change the international and UK digital pack flash sales to end (earlier) on 17 March
> Get digital pack flash sales to end on 17 March.

- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
We want to test the effect of adding PayPal as a payment method to the Digital Pack checkout.
The design for this is identical to the one on the contributions landing page; a radio button for payment methods which swaps in the PayPal button when PayPal is selected.
[**Trello Card**](https://trello.com/c/ioIGXQRK/2239-ab-test-for-paypal-on-dp-checkout)
[**Test is here**](https://optimize.google.com/optimize/home/?hl=en-GB#/accounts/1368065808/containers/6827913/experiments/329)
> AB test for PayPal

- support-frontend/app/views/newContributions.scala.html
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
Looks like this has a pretty big impact on Time To Interactive, while leaving FCP and FMP unchanged (as we'd expect)
> Query params to omit PayPal and Stripe checkout JS

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/internationalisation/country.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/pages/digital-subscription-checkout/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutActions.js
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
- support-frontend/assets/pages/digital-subscription-checkout/helpers/validation.js
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
There were a number of bugs with the address section of the Digital Pack checkout
* Postcode should be 'Zip code' in the US
* Postcode should be optional in countries other than US, UK, AU & CA
* AU should have a mandatory state list
Other changes:
* We have decided that we don't need the county field (it was optional and not actually being saved to Zuora) so I have removed it.
* I have moved all the validation code out of `/digitalSubscriptionCheckoutReducer.js` into its own file.
[**Trello Card**](https://trello.com/c/m8N722T3/2282-bugs-in-the-us-digital-pack-checkout)
> Address form fixes

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
If someone manages to submit the Digital Pack checkout form with a name like ''Anker PowerLine+ Lightning Cable (6ft) Durable and Fast Charging Cable [Double Braided Nylon] for iPhone iPad", we should not invoke the Step Function. (Yes, this really did happen).
[**Trello Card**](https://trello.com/c/Znjwl1F8/2289-improve-server-side-validation-for-name-fields)
* Add server side validation for first/last name field length, based on Salesforce limits:
> Tighten up first/last name field validation

- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
This logging is no longer required. 
For context: a year or so ago I was investigating an issue with this lambda and I thought the number of processors might be relevant. I don't think anyone cares about this anymore.
> Remove debug statement

- support-frontend/assets/helpers/logger.js
We noticed that the raven library was in the bundle and taking up 39K (13K gzipped).  The rest of the bundle is 280kb (80kb gzipped).  This is about 15% which is something that is non critical to painting the page.
It seems to be working OK locally, just letting the promise run and discarding the result.  I'm not sure whether that is good practice though?  In case the bundle doesn't download, we might not realise.
[**Trello Card**](https://trello.com/c/E5XA4fqR/356-js-raven-load-on-demand)
|PROD|CODE|
|---|---|
|![image](https://user-images.githubusercontent.com/7304387/53975290-66ac1280-40fc-11e9-901d-a2c8016bf7d9.png)|![image](https://user-images.githubusercontent.com/7304387/53975325-788db580-40fc-11e9-9853-0efc797718f5.png)|
|![image](https://user-images.githubusercontent.com/7304387/5 …
> load raven library on demand rather than bundling it

- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.scss
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
We are reviving the ticker for an upcoming AU campaign
1. Updated ticker styling
2. Ticker can be enabled by adding `ticker=true` in the url query string
3. Adding `frontline-campaign=true` to the url query string adds custom campaign to the form (below the ticker)
> Enable ticker for AU

- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/app/controllers/PayPalOneOff.scala
- support-frontend/app/controllers/PayPalRegular.scala
- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/app/lib/CustomHttpErrorHandler.scala
- support-frontend/app/views/main.scala.html
- support-frontend/app/views/newContributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
We are trying to make perf improvements to help people access the page quicker.  This means they are less likely to leave the page before it loads so they are more likely to contribute.
I noticed that with a slow network connection "Fast 3G in chrome", the JS takes 1.9 seconds to download.  Then there is a constant amount of time to get the form on the screen.  See the diagram:
However if we inline all the JS the connection just gets a clear run from when the main body starts downloading until all the JS is loaded, meaning that there is little contention.
As you can see the js is fully downloaded 1 second earlier when it's inlined.
Lighthouse difference is small
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/7304387/53894027-42323680-4027-11e9-9f95-ef233fe25d6 …
> inline Javascript into the page

- support-workers/cloud-formation/src/templates/cfn-template.yaml
Support Workers is now responsible for setting up: Monthly Contributions, Annual Contributions, Digital Pack.
And soon it will be responsible for setting up: Print and Guardian Weekly subscriptions.
Consequently I'm trying to remove misleading / specific references to Monthly Contributions. 
The Step Function itself needs to be renamed too, but that's a bit more complex (I think the ARN will change and support-frontend depends on this) so I'm going to tackle that in a separate PR (probably not on a Friday either).
[**Trello Card**](https://trello.com/c/oHntu1hG/2290-update-names-descriptions-for-support-workers-alarms)
* Update alarm names/descriptions
> Update alarm names and descriptions

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
I was actually looking at what errors got displayed when the server side validation failed and I noticed a couple things
- We require a billing address for digital pack, and both a billing address and a delivery address for paper, but this isn't reflected in the server side validation
- If the user doesn't select a start date and manages to submit the form (there is client side validation that prevents this, but if it fails...), this sends the date as an empty string, it gets parsed as `Some("")` and then `POST /subscribe/create` returns a 500. Setting an initial value of null allows our server side validation to catch a missing start date and return a 400 instead. 
[**Trello Card**](https://trello.com/c/9qGNJFwU/2259-client-side-error-handling-for-failed-attempts-to-create-a-hd-voucher-su …
> Add address line 1 and city to the server side validation and fix initial value of start date. 

- support-frontend/assets/components/productPage/productPageHero/productPageHero.scss
- support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
This commit addresses the stuff that got missed in Fridays merge conflict bonanza. 
[**Trello Card**](https://trello.com/c/J0X4PCRe/2278-digital-pack-hero-panel-design)
* Remove commented css
* Add max height ONLY to the standard banner
* Remove display none on the Digital Pack images in the banner.
> jy banner update fixes

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
Marketing supplied a link to a valid promo T&C page for Weekly. I updated one last week but missed the second instance.
* Update link
> Jy promo link fix

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
After a test on a real device I realised a `srcset` image path was broken for mobile. For good measure I also updated alt text 
[**Trello Card**](https://trello.com/c/J0X4PCRe/2278-digital-pack-hero-panel-designdev)
* Fix `srcset` path
* Add alt text
I didn't get a screenshot of the broken layout sorry.
> Update alt text and fix 404 image

- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLandingActions.js
Small fix for https://github.com/guardian/support-frontend/pull/1607
Pass the selected payment frequency through to the checkout page.
> DP checkout url fix

- support-workers/cloud-formation/src/templates/cfn-template.yaml
The support-workers project still creates a Step Function called `MonthlyContributions-{random string}`, even though it is now responsible for setting up multiple products. 
There are several steps involved because renaming = creating a brand new Step Function and deleting the old one.
> Rename Step Function

- support-frontend/.flowconfig
- support-frontend/assets/components/checkoutForm/checkoutForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/addressFields.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/postcodeFinder.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-ty/thankYou.jsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/paymentProviders.js
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
A few changes for the paper subs checkout:
* Update wording on the postcode lookup button
* Hide the billing address fields unless the user tells us that it is different from the delivery address
* Add a postcode field into the main address form as well as the postcode finder field
* Add links to manage subscription and edit profile to the thank you page
**Address form now looks like this:**
**Thank you text now looks like this:**
[**Trello Card**](https://trello.com/c/kpRzL7zH/2288-checkout-ux-paper-cuts)
> Paper checkout form tweaks

- support-frontend/assets/helpers/tracking/acquisitions.js
We have a special landing page for the Frontline campaign. It's important to accurately record contributions for this campaign. Rather than rely on referrers being consistent with their campaignCodes, hardcode it here to `thefrontline`
So visiting /uk/contribute?frontline-campaign=true causes the POST to include:
```
referrerAcquisitionData {
campaignCode: thefrontline
...
}
```
> Use special campaign code for the Frontline campaign

- support-frontend/setup.sh
The setup script fails if the Nginx sites-enabled doesn't exist. With this change the directory would be created if it doesn't exist
> small fix for setup script

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
There are few copy changes we need to make on the Digital Pack product page to make the messaging clearer.
[**Trello Card**](https://trello.com/c/upwHBvin)
* Updated CTA copy
* Updated header copy for for sale and BAU
Current:
New:
> Copy updates to DP product page

- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
My last PR caused a bug on the Australia campaign landing page as I removed the `.bold` class
This PR adds it back in
> Re-add bold class 

- support-frontend/.eslintrc
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/helpers/productPrice/productOptions.js
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/helpers/subscriptions.js
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
- support-frontend/assets/pages/paper-subscription-landing/components/content/content.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/tabs.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPageActions.js
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js
To be able to go from the paper landing page to the checkout page we need to pass the selected product and fulfilment options in the url.
This has required quite a large refactor of the paper landing page to make it work with the new `ProductPrices` objects from the catalog but has allowed me to delete quite a bit of the old pricing code from `subscriptions.js`
* Load prices from the product catalog on the paper landing page rather than using the old hard coded values
* Update components to use the catalog types
* Generate links to the new paper checkout page when the `displayCheckout=true` query param is present
[**Trello Card**](https://trello.com/c/3FHVlJbc/2297-pass-paper-product-choices-from-landing-page-to-checkout-page)
> Paper checkout links

- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
Just acting on a thought I had, fairly late into the evening!
We're not checking the available contribution types before we initialise third-party libs. Most wastefully, we're loading PayPal recurring JS even on pages which only have one-off available (e.g. the current Australia campaign page). This will definitely have an impact on performance.
We're also running through some unnecessary Stripe logic on pages where particular payment methods are disabled (such as non-UK/US right now). We still have to actually load the main Stripe libs, since Stripe is used on all contribution types, but we shouldn't try and configure the Stripe libs for contribution types which aren't available (though admittedly this probably won't improve performance).
> Do not load unnecessary payment JS

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
Removes this sentence:
If we exceed our fundraising goal, The Guardian will allocate the additional funds toward its core operations that fund our in-depth environmental reporting
> Remove sentence about exceeding goal

- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
The print checkout makes use of existing client side error handing, but I went through to see that it worked as expected 
|  Scenario |  Expected behaviour | Screenshot  | Code change required? |
|---|---|---|---|
| On `POST /subscribe/create`, the server side validation fails  | Tell the user to check their personal details  | <img src="https://user-images.githubusercontent.com/3072877/54301064-1fb79480-45b6-11e9-8ec7-e0c2b60a3475.png" width=300>  | no |
| `POST /subscribe/create`, returns an internal server error  | Tell the user the default error message  |  <img src="https://user-images.githubusercontent.com/3072877/54301184-5ee5e580-45b6-11e9-8e16-9bc1c6e98afd.png" width=300> | no |
| `GET  /support-workers/status` is returning internal server error  | Keep polling and up on the …
> A couple client side error handling tweaks. 

- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
#1660 Added the countdown timer to the Digital Pack landing page, but @jesseyuen noticed that it didn't look right at smaller breakpoints, this PR fixes that.
**Before:**
**After:**
> Tweak for the layout of the countdown timer on smaller breakpoints

- build.sbt
To fix the support-workers integration tests.
> Add support-workers integration test dependency to build.sbt

- support-frontend/assets/components/ctaLink/ctaLink.scss
- support-frontend/assets/components/threeSubscriptions/threeSubscriptions.scss
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/showcase/showcase.scss
We are now using the same fonts as `.com`.  This had resulted in some instances of type missing correct styling on our pages. 
* Include font-family: "Guardian Text Egyptian Web", Georgia, serif; and correct weights where needed
* Remove references to 'font weight 400' and revert to 300 
Look at "Masterclasses & Live Events" as an example. 
**Before**
**After**
> S&C typography audit after font updates 

- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
@twrichards noticed that the email copy for a user who pays annually & has a 12-month discount is misleading e.g.
I think this is due to a problem with Zuora, but until I've had chance to prove/disprove this, I've put some temporary copy in place (it's not great but better than the current misleading copy IMO).
> Add workaround for incomplete Zuora response

- support-frontend/assets/helpers/paymentIntegrations/payPalRecurringCheckout.js
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionSubmit.jsx
#1596 introduced a bug whereby PayPal would always be passed the contribution amount which was set on page load, not the amount which the user selected subsequently. 
This PR fixes that by reintroducing the original version of the function which was used to call PayPal, this is not the ideal solution but it is the quickest way to fix the bug, we can tidy up afterwards.
> Pass the correct amounts to PayPal for recurring contributions

- support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx
As we near the end of the quarter, we would prefer to stop promoting Digital Pack
💰 
[**Trello Card**](https://trello.com/c/o2YsnqAl/2283-subs-page-march-april-updates-1st-15th-march-31st-march)
* Get the featured product hero to always feature Guardian Weekly, unless there is a digital pack flash sale on 
for  /<uk|us|au|eu|int|nz|ca>/subscribe
> Make featured product hero always Guardian Weekly.

- support-frontend/assets/helpers/fontLoader.js
- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/pages/digital-subscription-checkout/__tests__/digitalSubscriptionCheckoutReducerTest.js
- support-frontend/package.json
fontLoader (npm package) is written in ES6 without a dist version which was causing problems with IE11 (£500-£1000/day). This PR is a bandaid that puts it in our helpers directory (with edits to make it Flow compat) and ensures it gets transpiled properly and runs in IE11.
[**Trello Card**](https://trello.com/b/eDZKuUvg/making-it-easier-to-contribute)
* New file: `helpers/fontLoader`
* New import of above in `page.js`
> fontLoader from node package to local library (using flow)

- support-frontend/assets/helpers/tracking/__tests__/thirdPartyTrackingConsentTest.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
- support-frontend/assets/helpers/tracking/thirdPartyTrackingConsent.js
We want to respect any preference our users have set with regard to third party tracking. 
This PR adds code to read and process the cookie where this information is stored and send the preference to Google Tag Manager where we can use it to determine whether to fire tags or not.
[**Trello Card**](https://trello.com/c/Q6fM1gvZ/1-supporttheguardiancom)
> Third party tracking consent

- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
The text in the roundel needed to be editable. This PR makes it editable and removes the legacy sale text that I had originally included in the png asset.
* Remove text from image asset and include the text via markup instead.
> Update digital banner to make text editable

- support-frontend/app/views/main.scala.html
`async` interrupts HTML/CSS parsing to interpret the JS as soon as it's downloaded, `defer` will still download the file asynchronously but not interpret it until the DOM, CSSOM, and previous JS have been parsed. This is not an improvement for users with slow connections (as they will have parsed the DOM/CSSOM anyway by the time this is loaded) but will fix the behavior we want for users with very fast connections (when downloads are faster than their processor)
[**Trello Card**](https://trello.com/c/Fs4QxCir/354-js-load-googletagmanagerscript-after-main-js)
changed the word `async` to `defer` in scala template :)
> switched googletagmanager to from async to defer

- support-frontend/assets/components/consentBanner/consentBanner.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx
The new consent banner introduced in #1677 is causing problems with the post deploy tests, this PR prevents it from showing during them.
> Don't show the consent banner during post deploy tests

- support-frontend/assets/components/customerService/customerService.jsx
- support-frontend/assets/components/customerService/customerService.scss
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
I noticed that in the footer of the paper checkout, that we are directing users to contact digitalpack@theguardian.com 
The checkout on subscribe.theguardian directs users who have selected vouchers to vouchersubs@theguardian.com and those who have selected home delivery to homedelivery@theguardian.com so this changes aims to do the same. 
[**Trello Card**](https://trello.com/c/QronTsE0/2306-footer-should-have-correct-contact-email)
* The footer now directs users to appropriate contact emails in the paper checkout
> Display paper specific contact emails in the paper footer.

- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
Clicking back from the /thankyou page takes you back to the page before the /contribute page.
This is actually preferable, because otherwise client-side routing would kick in and, based on the redux state, decide to go back to /thankyou again. Returning the user to /contribute could also get messy given the state they are now in.
This change makes this intention clearer but does not change the behaviour.
[**Trello Card**](https://trello.com/c/pvbHBgU2/121-npf-follow-up-bug-back-button-broken-by-clientside-routing-need-to-do-a-historypushstate)
> Make it explicit that clicking back from thankyou page does not take you back to landing page

- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx
The difference between importing from these 2 modules caused some confusion earlier, it turns out [there's no difference](https://github.com/ReactTraining/react-router/issues/4648#issuecomment-284479720) so I'm just tidying things up.
> Use react-router-dom over react-router

- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/app/services/stepfunctions/StateWrapper.scala
- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/main/scala/com/gu/support/workers/RequestInfo.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
model a new object for 'paymentFields' (which contains 'billingAccountId' to represent existing payment method) PLUS an `accountExists` boolean in the non-encrypted `requestInfo` so that step function can branch accordingly in future
As prerequisite for https://github.com/guardian/support-frontend/pull/1673 we must ensure that `support-models` can handle a new object value for `paymentFields` (for **existing** payment details) and to expose that the Zuora account already exists with an non-encrypted flag so that step function can branch accordingly in future (see ADD PR ONCE CREATED)
* model a new object for `paymentFields` (which contains `billingAccountId` to represent existing payment method)
* PLUS an `accountExists` boolean in the non-encrypted `requestInfo` so that step function can …
> model a new object for 'paymentFields' (which contains 'billingAccountId' to represent existing payment method)

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionAmount.jsx
The weekly variant has been the best variant so far in the [editorialise amounts test](https://github.com/guardian/support-frontend/pull/1661), beating the control significantly in terms of £IYR, but not yet significantly in terms of £AV. 
We want to get that significant £AV result, but we also want to iterate, so we are adding a daily variant to the test, which tests breaking down the annual amount into days. 
In the UK, if the amount is less than £1, we switch to using `xp` rather than `£0.x`
| Daily variant in GB | Daily variant not in GB |
|---|---|
|![UK](https://user-images.githubusercontent.com/2844554/54756023-3cb81d00-4bdf-11e9-9a65-583b00747fd8.png)|![US](https://user-images.githubusercontent.com/2844554/54756024-3cb81d00-4bdf-11e9-8e40-5af4826c903b.png)|
> Drop monthly and average amount variants from editorialise amounts test, add in daily variant

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Using a test to update to the styles for tabs on mobile devices for 50% of users (vertical instead of horizontal below 440px) - Trello card attached
[**Trello Card**](https://trello.com/c/PVwwQgzt/332-implement-on-mobile-stack-frequency-types)
* Stacking the contribution tabs below the 440px breakpoint
Control:
Variant:
> Added test for updated styles on mobile contribution type tabs

- support-workers/cloud-formation/src/templates/cfn-template.yaml
More people need to see these alarms
> Make support-workers alarms go to reader-revenue-dev

- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
The styling was broken for tablets. This file still requires a refactor/overhaul but this bugfix is an incremental step in the right direction IMO.
[**Trello Card**](https://trello.com/c/vHssPxtl/370-fix-tablet-break-point-layout-and-others)
|Before (ipad):|After (ipad):|
|---|---|
|![tabletBreakpoint_before](https://user-images.githubusercontent.com/3300789/54768117-734d6200-4bf6-11e9-8071-685c8cb7fe0a.png)|![tabletBreakpoint_after](https://user-images.githubusercontent.com/3300789/54768141-7cd6ca00-4bf6-11e9-9a73-189234248bec.png)|
|Before (ipad pro):|After (ipad pro):|
|---|---|
|![tabletBreakpoint_before2](https://user-images.githubusercontent.com/3300789/54768185-92e48a80-4bf6-11e9-94c7-177d37f2f7ec.png)|![tabletBreakpoint_after2](https://user-images.githubusercontent.com/3300789/5476 …
> Bugfix: Breakpoints on contributions landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
This fixes a bug whereby noone was actually being assigned to the daily breakdown variant in the editorialise amounts test
> Add daily variant

- support-internationalisation/version.sbt
- support-models/build.sbt
...to include SwG PaymentProvider
This is to allow payment-api to set `Acquisition` data to `paymentProvider=ophan.thrift.event.PaymentProvider.SubscribeWithGoogle`
[JIRA ticket](https://contribute.atlassian.net/browse/CWG-94)
* Bump acquisition-event-producer-play26 version to 4.0.18
n/a
> Bump acquisition-event-producer-play26 version to 4.0.18

- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
I worked with @walaura on this
Acquisition events for the paper checkout would currently just be sending that it is some kind of print subscription, but we also need to know voucher|HD and everyday|sixday|etc. That way we can understand our users better and be able to make AV calculations on print acquisitions. 
[**Trello Card**](https://trello.com/c/ENjN34vd/2264-analytics)
* Send print options in acquisition events.
> Send print options in acquisition events

- support-frontend/app/controllers/CreateSubscription.scala
Just wanted to make it a little easier to look at the logs and see subscription signups, and for which product. 👀 
We are currently just logging billing period.
[**Trello Card**](https://trello.com) - none
> Add a little info to logging when a support-workers execution is started for a subscription

- README.md
- build.sbt
- support-config/README.md
- support-frontend/README.md
- support-models/README.md
- support-models/build.sbt
- support-models/version.sbt
- support-services/README.md
To make the library projects releasable, they have not worked since the move to the mono repo but it turns out we do still need to sometimes release them separately because the payment api depends on support-models.
> Release support models 62

- support-frontend/assets/components/ticker/contributionTicker.jsx
- support-frontend/assets/components/ticker/contributionTicker.scss
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
- support-frontend/stories/_index.js
- support-frontend/stories/contributionTicker.jsx
Also
- moves it into a general components directory (`components/ticker`)
- includes CSS directly with ES6 import
In sum: makes the ticker more reusable
> Add ticker to storybook

- support-frontend/cloud-formation/cfn.yaml
Preparing for 2019-2020 reservations.
https://aws.amazon.com/ec2/instance-types/t3/
[**Trello Card**](https://trello.com/c/ihXGzPyy/2313-work-to-support-aws-instance-reservations)
* Use t3.small instead of t2.small
> Use t3.small instances

- support-workers/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
While debugging changes to the step functions I find it hard to read the decoded states so I added some formatting to it.
so when running decode.sh '[ENCODED STATE]'  the response will change from : 
```
{"requestId":"25489eb6-fab2-4b46-8730-9925d46d4519","user":{"id":"9999999","primaryEmailAddress":"yjcysqxfcqqytuzupjc@gu.com","firstName":"test","lastName":"user","billingAddress":{"lineOne":null,"lineTwo":null,"city":null,"state":null,"postCode":null,"country":"GB"},"deliveryAddress":null,"telephoneNumber":null,"allowMembershipMail":false,"allowThirdPartyMail":false,"allowGURelatedMail":false,"isTestUser":false},"product":{"amount":5,"currency":"GBP","billingPeriod":"Monthly"},"paymentMethod":{"TokenId":"card_EdajV2eXkZPrVV","SecondTokenId":"cus_EdajoRmjUSlef9","CreditCardNumber":"4242"," …
```
> pretty print decoded states

- support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx
- support-frontend/assets/components/menu/menu.jsx
- support-frontend/assets/components/menu/menu.module.scss
- support-frontend/stories/_index.js
- support-frontend/stories/dialog.jsx
- support-frontend/stories/menu.jsx
The last menu item from #1724 was hard to use on my iPhone X as safari tries to open the bottom bar when you click it, this adds generous padding to make up for it.
I've also added stories because this is quite a useful component to have documented
> Fix <Menu> on phones and add stories

- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
We temporarily removed the monthly option for some regions - this adds it back.
Monthly will also now be the default for all regions.
>  Add monthly contribution type back 

- support-frontend/assets/helpers/__tests__/checkoutsTest.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/helpers/globals.js
- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/helpers/settings.js
- support-frontend/assets/helpers/subscriptions.js
- support-frontend/assets/pages/digital-subscription-landing/components/form.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLandingReducer.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js
Adds a new set of helpers (copied from [gu.com](https://github.com/guardian/frontend/blob/master/static/src/javascripts/lib/config.js)) to load globals in a nullable and type-safer way. This allows pages to be rendered without having access to the `window.guardian` object.
This PR doesn't replace all calls or makes everything nullable (Namely, conbtribution amounts are giving me trouble when trying to render contributions without window.guardian) but it's a start.
> Global helper

- support-models/build.sbt
To release this Thrift enum update: https://github.com/guardian/acquisition-event-producer/pull/48
@johnduffell am I right in thinking this the only version bump needed to ensure that this makes its way into support-workers?
> acquisition-event-producer 4.0.18 => 4.0.19

- support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
Note: to be merged morning of April 1
https://github.com/guardian/support-frontend/pull/1510/files removed six for six but now we want it back 
[**Trello Card**](https://trello.com/c/OyMrOMzD/2286-subs-page-march-april-updates-1st-april)
* Put back six for six on the weekly landing page
* Update copy to reference six for six in the featured product hero on the subs landing page
**/subscribe/weekly**
here are a couple examples: (this is not new functionality; it is just reinstating https://github.com/guardian/support-frontend/pull/1510/files)
|  eu  |  us |
|---|---|
|  <img src="https://user-images.githubusercontent.com/3072877/55071064-89887180-507f-11e9-8634-7fd3c5b7ae57.png" height=300> | <img src="https://user-images.githubusercontent.com/3072877/55071163-bf2d5a80-507f-11e9-8c59-f37efe …
> Put back six for six

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Vertical mobile tabs test variant was not performing better than control, so UX decided we should remove before the What If? work. This undoes this PR [here](https://github.com/guardian/support-frontend/pull/1697/)
* removed vertical mobile tabs test JS and styles
> removed vertical mobile tabs test

- support-workers/README.md
This link was broken. It used to link [here](https://github.com/guardian/support-workers/pull/184/files#diff-e02f7b5eb279990ed19ab57010bb36f6). Both of the workarounds mentioned have already been removed, so this is redundant.
> Remove old section from readme

- support-frontend/assets/pages/showcase/components/hero.scss
I forgot that we moved the animation form a transition to a keyframe based approach. This PR cancels out the keyframe animation if _reduced motion_ is selected.
> Cancel keyframe animation in motion query

- support-frontend/assets/helpers/productPrice/productPrices.js
The `hasPromotion` function used by the `PriceLabel` component was only checking for null when trying to determine whether a promo code is a discount. Actually it should have been checking for `undefined`.
> Correct the check for discounted price

- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
Retention have highlighted that the money back guarantee messaging we have in the checkout sisn't true in all cases, so I've removed it.
* Remove "Money Back Guarantee. If you wish to cancel your subscription, we will send you a refund of the unexpired part of your subscription."
Current (DP example): 
New (DP example):
> Remove money back guarantee messaging from checkouts

- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
The change I just made in this PR > (https://github.com/guardian/support-frontend/pull/1748) only removed the money back copy from the print checkout (eye roll). This PR is to remove it from the DP checkout.
* Remove money back guarantee messaging from DP checkout
Current (DP example): 
New (DP example):
> Remove money back messaging for DP checkout

- support-frontend/app/wiring/Controllers.scala
- support-frontend/build.sbt
- support-frontend/cloud-formation/cfn.yaml
- support-services/build.sbt
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricPut.scala
- support-services/src/main/scala/com/gu/support/catalog/CatalogService.scala
- support-services/src/test/scala/com/gu/aws/AwsCloudWatchMetricPutSpec.scala
If the Zuora catalog fails to load on app start this is a big problem for subs because pricing information will be unavailable, this PR adds a CloudWatch alarm so that we will get notified if that happens.
[**Trello Card**](https://trello.com/c/RLwKIy8d/2218-handle-catalog-load-failures-gracefully)
* Send an event to CloudWatch to record catalog load failures in PROD
* Add a CloudWatch alarm to fire on failure
> Catalog warnings

- support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.jsx
- support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
- support-frontend/assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
Previously the payment button on the Direct Debit pop up form was hard coded to say 'Contribute with Direct Debit' even for subscriptions checkouts. This PR makes the text configurable and sets it to 'Subscribe with Direct Debit' for subs checkouts.
[**Trello Card**](https://trello.com/c/9SlcwuMT/2328-update-dd-cta-wording-and-fix-close-button-direct-debit-pop-up-on-new-checkouts)
> Make the text on the DD payment button configurable

- support-frontend/assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx
- support-frontend/assets/components/subscriptionCheckouts/cancellationSection.jsx
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
When changing the Direct Debit button text I noticed some duplication between the paper and DP checkout forms so I've refactored it out.
> Remove duplication in checkout forms

- support-frontend/app/admin/settings/Settings.scala
- support-frontend/app/admin/settings/SettingsProvider.scala
- support-frontend/app/config/Configuration.scala
- support-frontend/conf/CODE.public.conf
- support-frontend/conf/DEV.public.conf
- support-frontend/conf/PROD.public.conf
I'm about to add another settings type (for contributionTypes).
All of these settings files are going to have very similar bucket/key values (e.g. `support-admin-console/CODE/amounts.json`), so this PR simplifies the configuration of this
> Simplify configuration of settingsSource

- support-frontend/app/admin/settings/ContributionTypes.scala
- support-frontend/app/admin/settings/Settings.scala
- support-frontend/app/admin/settings/SettingsProvider.scala
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/helpers/contributions.js
- support-frontend/assets/helpers/globals.js
- support-frontend/assets/helpers/settings.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingReducer.js
- support-frontend/conf/DEV.public.conf
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-models/src/main/scala/com/gu/support/encoding/JsonHelpers.scala
Contribution types (aka frequencies) are now configurable from the Support Admin Console.
This lets us configure which contributionTypes are available in each region, and which is the default.
This change gets the contributionTypes settings from s3 (currently they're in the javascript) and sends them to the client.
* Server gets the settings from `contributionTypes.json` (along with switches and amounts settings)
* Client uses the settings in window.guardian.settings
> Make contribution types configurable

- support-frontend/assets/components/checkoutForm/checkoutForm.jsx
- support-frontend/assets/components/checkoutForm/checkoutForm.scss
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/components/subscriptionCheckouts/subscriptionSubmitButtons.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
This is work detailed in [**Trello Card**](https://trello.com/c/zWp8H655/2342-remove-border-above-button-and-standardise-vertical-spacing)
* Remove line in paper checkout
* Remove line and adjust spacing in digital checkout
> Removes line above continue to payment button inb subs checkout

- support-frontend/assets/components/text/text.scss
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
This is work detailed in this [**Trello Card**](https://trello.com/c/h7RzWj8t/2348-vertical-spacing-below-form-ui)
* Adds space (hopefully as required - @jesseyuen, please confirm is this looks okay)
> Add vertical space to text under sub start radio chonkies

- support-frontend/assets/components/forms/customFields/error.scss
- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/postcodeFinderStore.js
This work is detailed in [**Trello Card**](https://trello.com/c/u5tKFLWP/2345-find-your-postcode-error-messages)
* Change error message from 'Couldn't find your postcode' to 'We couldn't find this postcode, please check and try again or enter your address below.'
* Increase space above error message
* Manage line turnover to match design
> Fix postcode error messaging

- support-frontend/assets/pages/paper-subscription-checkout/components-ty/thankYou.jsx
To improve the English of the confirmation message on the thank you page.
* Update confirmation copy to say "You have now subscribed..."
Current:
New:
I can't screenshot this
> Update thankYou page copy.jsx

- support-frontend/assets/components/button/button.scss
- support-frontend/assets/components/marketingConsentNew/marketingConsent.scss
- support-frontend/assets/components/socialShare/socialShare.jsx
- support-frontend/assets/components/socialShare/socialShare.scss
- support-frontend/assets/components/spreadTheWord/spreadTheWord.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.scss
- support-frontend/assets/pages/new-contributions-landing/components/SetPasswordForm.jsx
We released the new Thank You page designs knowing we had a few things left to be done. The most major thing to be done was releasing the social share buttons, which this PR addresses. This PR also addresses one minor concern which was that we were using a non-standard button. 
[**Trello Card**](https://trello.com/c/oo2MNCqE/959-thank-you-page-redesign-ft-social-share-v2)
* Releasing Social Share buttons on "thank you" page and "password set" page
* Using standard `button` component across thank you pages
Thank you page with share buttons:
Password set page with share buttons:
Facebook share window:
Twitter share window:
Linkedin share window
email share window (w default email set to gmail):
> Social share and button update on thank you pages

- support-frontend/assets/pages/new-contributions-landing/components/ContributionSurvey/ContributionSurvey.scss
- support-frontend/assets/pages/new-contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
We are running a survey for our contributors with separate links for one-offs and recurring, respectively.
[**Trello Card**](https://trello.com/c/yu5QLGBG/1012-implement-survey-button-on-new-thank-you-page)
* Rewrite of the survey component
* Adding survey link component to thank you page and password set page
Thank you page:
Password set page:
> Adding survey to thank you page flow

- support-frontend/assets/components/productPage/productPageHero/productPageHero.scss
I noticed a bug in Chrome where sometimes the subscriptions landing hero image wasn't displaying (yet it was being fetched correctly). It wasn't a consistent bug but would most commonly be replicated if you toggled between the subs landing and another page.
* Removing the height on the parent container seems to fix it (🤷‍♂️) The CSS around this component also feels a bit like a remnant of something being absolutely positioned there in the past? Regardless, the styles aren't needed now!
> Subs landing hero image bug

- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/GetPaymentMethod.scala
Logging the product type into the RequestInfo object will make it easier to see quickly which team needs to investigate when a step function execution fails.
> Log the product type in the RequestInfo object to make triaging failed executions easier

- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
See the following [**Trello Card**](https://trello.com/c/Bo8QcH71/2369-remove-pre-selection-of-payment-method-in-all-checkouts-when-there-is-more-than-one-option-available)
The initial state has changed so it checks whether the country supports direct debit (hence there is a choice in the checkout) in which case it doesn't set either payment type. If there is no choice, it selects Stripe (Credit/Debit card).
> Adjusts paper checkout payment selector so no radio button is selected

- support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckoutReducer.js
The work is detailed in this [**Trello Card**](https://trello.com/c/yptRgLHj/2368-remove-pre-selection-of-is-billing-address-the-same-as-delivery-address-in-print-checkout)
* Removes the preselected 'yes' to the question 'Is the billing address the same as the delivery address?'
* Adds an error if the user does not select an option, asking them to pick
> Update print checkout so no radio button is selected for billing address y / n

- support-frontend/package.json
According to Github, version 3.1.5 of webpack-dev-server is affected by CVE-2018-14732. And that warning at the top of the repo is freaking me out.
As far as I can tell this is only used for local development so I think we're good?
> Bump webpack-dev-server to 3.1.11

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
We want to test defaulting to annual against defaulting to monthly (= control), but also want to see what effect putting the weekly breakdown on monthly has when monthly is the default and is therefore immediately on the page when people arrive
@jessewilkins
> New test for weekly breakdown

- support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js
- support-frontend/assets/pages/digital-subscription-checkout/__tests__/digitalSubscriptionCheckoutReducerTest.js
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutActions.js
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
We want to track what payment methods users are selecting on the Digital Pack checkout page so that we can analyse drop off rates for each method.
> Send tracking events when a user selects a payment method

- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
Updating the headline on the print product page in line with the new campaign messaging.
* Update copy in headline to "subscribe to the joy print"
Current:
New:
> Update headline copy on Print product page

- support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
The hero banner requires updates to match campaign branding updates
* Update styles for heading size and colour and roundel bg/text colour 
**Before**
**After**
> Colour and heading updates to accommodate campaign branding updates

- support-frontend/assets/pages/new-contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
The current survey has finished running, but it will run again in the future so I've added an option to configure the viewability of the component rather than removing it entirely - this better approach suggested by @tomrf1 
[**Trello Card**](https://trello.com/c/pB4N050G/1053-remove-user-survey-post-contribution)
*  Made survey component's rendering configurable with an `isRunning:boolean` prop
> Renderable survey component

- support-frontend/assets/components/headers/header/header.jsx
- support-frontend/assets/components/headers/header/header.scss
- support-frontend/assets/components/headers/header/padlock.svg
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouExisting.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
- support-frontend/stories/header.jsx
The aim here is to add the word 'Checkout' to the navbar for digital and paper checkouts, in a range of different formats for different screens.
The work is details in this [**Trello Card**](https://trello.com/c/rkxkI6rA/2341-checkout-header)
* Mobile version of navbar in checkout
* Tablet version of navbar in checkout
* Desktop version of navbar in checkout
> Adds a version of navbar for checkout pages

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
This variant is losing us money (19% behind control after a week's worth of data), so let's get rid of it
cc @jessewilkins
> Remove default annual variant

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
Each product page has two banner options Default and Campaign. The campaign banner was confusingingly called SaleHeader even though it was not related to a _sales_ as such. 
The Campaign Banner also had not been updated to include flash sale text.
* Rename SaleHeader to CampaignHeader because it makes more sense
* Introduce flash sale text to CampaignHeader
> SaleHeader updates

- support-frontend/assets/components/forms/customFields/checkbox.jsx
- support-frontend/assets/components/forms/customFields/checkbox.scss
- support-frontend/assets/components/forms/customFields/radioInput.scss
- support-frontend/assets/stylesheets/gu-sass/layout.scss
- support-frontend/stories/form.jsx
The GW checkout includes a custom checkbox which we hadn't built... UNTIL NOW. I also took the opportunity to tweak the custom radio buttons hover states as they were missing the css transition that our other form UI has.
Pull this branch to view the [Storybook example](https://support-ui.thegulocal.com/?selectedKind=Forms&selectedStory=Forms&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).
* Add custom checkbox component
* Add hover states to custom radio button
**Default**
**Checked**
> Add custom checkbox component

- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
The PayPal test has concluded now and we are switching it on for 100% of traffic to the Digital Pack page. We still need to leave it switched off for paper for the time being because the work hasn't been done to support it yet.
> Show PayPal to everyone on the Digital Pack checkout

- support-frontend/assets/components/ticker/contributionTicker.jsx
- support-frontend/assets/components/ticker/contributionTicker.scss
- support-frontend/assets/helpers/url.js
- support-frontend/assets/pages/new-contributions-landing/campaigns.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingReducer.js
- support-frontend/stories/contributionTicker.jsx
Campaign tickers can "end" with either a "hardstop" or an "unlimited" configuration, so the React component to reflect these variations. This was done in a way to reflect the move to centralize the configuration into `campaigns.jsx`
[**Trello Card**](https://trello.com/c/9ZJcIjsB/1036-refactor-campaign-ticker-add-configurable-hard-stop-and-unlimited-types)
* Added the configuration option to `campaigns.jsx`
* Updated the component to reflect the styles of the different configurations
* Moved campaign name out of shared state
In progress:
"Hardstop" ending:
"Unlimited" ending:
> Configurable Ticker Types 

- support-frontend/cloud-formation/cfn.yaml
As part of reconfiguring the Membership VPC to have public & private subnets, I'm going to placing load balancers in the public subnet and instances in the private subnet, as per best security practices. (The original motivation for this was to give [lambdas access to the internet as well as entities within the VPC](https://aws.amazon.com/premiumsupport/knowledge-center/internet-access-lambda-function/), but having a subnet which is unreachable from the internet has other security benefits too, and is in fact how the Subscriptions VPC is set up.)
As a first step for this, I need to separate out these params in CloudFormation for all of our apps. I'll need to manually upload the new CloudFormation in the console because I need to supply values for these params. When I do this, I'll leave …
> Separate public/private subnets

- support-frontend/package.json
Upgrading webpack-dev-server to 3.1.11 causes constant console logging due to new security features. The current best supported work around is to add the `--disable-host-check` flag to the 
script in `package.json`
Please see webpack-dev-server's documentation of this issue [**here**](https://github.com/webpack/webpack-dev-server/issues/1604)
**TBD**: check to see if this flag is still necessary next time we upgrade webpack-dev-server
> Bugfix for webpack-dev-server 3.1.11

- support-models/src/main/scala/com/gu/support/zuora/api/PreviewSubscribeRequest.scala
Due to what appears to be a really nasty Zuora bug, despite being in **preview mode** Zuora was creating a customer and mandate in GoCardless...
Fortunately not double payments, but likely [TBC] creating duplicate direct debit entries in customers online banking etc (one for the real subscription, and another which is 'never used').
_(after lots of trial and error)_ removed `PaymentMethod` and forced `AutoPay` to `false` in the `PreviewSubscribeRequest` call
> FIXED PreviewSubscribeRequest from creating duplicate customers & mandates in GoCardless

- support-models/src/main/scala/com/gu/support/workers/states/PreparePaymentMethodForReuseState.scala
- support-workers/cloud-formation/src/templates/state-machine.yaml
- support-workers/cloud-formation/src/view.yaml
- support-workers/riff-raff.yaml
- support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PaymentMethodExtensions.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
There was a long delay before I merged https://github.com/guardian/support-frontend/pull/1772 and another PR snuck in with a pattern match on `PaymentMethod`, which then became non-exhaustive when I finally merged https://github.com/guardian/support-frontend/pull/1772.
_NOTE, this only affects re-use of Direct Debit payment methods for contributions (for signed in users with existing products) but this was **already disabled** because of the support switches. Once this PR is merged and tested, hopefully we can turn this on._
Unfortunately it's not possible to make SBT error on **only** non-exhaustive pattern matches (it's either make all warnings into errors or none - which is a real shame) - this would've caught this in the merge build (i.e. failed and therefore wouldn't be deployable) …
> existing-payment-options: tweaks to Direct Debit cloning

- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.js
I've noticed a bug whilst doing some refactoring work:
* User selects PayPal as a payment method and then submits the form without filling in their address
* The PayPal button is disabled to prevent submission because the form is invalid 
* Even if the address is then filled in correctly the button is never re-enabled so the user will not be able to submit the form unless they use another payment method or refresh the page
This PR fixes the problem
> Enable PayPal button when address fields are valid

- support-frontend/assets/helpers/user/user.js
If you make a stripe payment while logged in but also have the `_test_username` cookie set then it causes an alarm. This is because the client uses the stripe test token, but the backend (support-workers) uses it in live mode if the identity cookie is present.
This change prevents the client from using the stripe test token if you're logged in.
[**Trello Card**](https://trello.com/c/n6sD0Xv6/1054-fix-intermittent-stripe-test-live-mode-crossover-errors-in-step-functions)
> Do not use test stripe token if logged in

- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/helpers/contributions.js
- support-frontend/assets/helpers/internationalisation/countryGroup.js
- support-frontend/assets/helpers/page/commonActions.js
- support-frontend/assets/helpers/page/commonReducer.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
In the past we used the `contributionTypes` query parameter to limit a campaign to one-offs only.
This change adds an optional `contributionTypes` field to the `Campaign` model, which overrides whatever is in the settings provided by the server.
It's still possible to do this from query parameters.
We already store the contributionTypes settings for all regions in `state.common.settings.contributionTypes`. This is initialised to the value from `window.guardian.settings`, but it is now overridden by `contributionsLandingInit.js` if there is a campaign.
[**Trello Card**](https://trello.com/c/SOyNM6vg/1074-make-contribution-types-configurable-from-campaign-settings)
> Make contributionTypes configurable for campaigns

- support-frontend/app/views/newContributions.scala.html
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Removing legacy design stuff in the SSR template and cleaning up the markup to make it more readable
> Remove legacy landing page circles from SSR template

- support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
There is going to be 2 GoCardless maintenance periods over the weekend so we are temporarily removing the direct debit payment method.
[**Trello Card**](https://trello.com/c/q1EZ6694/2402-investigate-gocardless-downtime-implications)
> Temporarily remove direct debit payment method

- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou/thankYou.jsx
The print (voucher) checkout thank you page current states "here's a reminder of how the voucher scheme works" but has no link. It's also a bit late / too early to do this because they've just purchased but won't be able to start using their vouchers for a few weeks. I've therefore removed the line.
* Remove extraneous copy "here's a reminder of how the voucher scheme works" from print checkout thank you page (voucher)
> Remove reference to 'here's how vouchers work' from print thank you page

- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou/thankYou.jsx
The current thank you page for the print checkout states "your first issue will arrive on [insert date]" which makes sense for HD, but not vouchers. Given that we're not currently selling HD, I've updated the copy to make sense for voucher and have raised a card to make that message dynamic in future.
* Change "your first issue will arrive on" to "you can start using your vouchers from".
> Update first issue availability message on print checkout thank you page

- support-frontend/assets/helpers/contributions.js
- support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
[This PR](https://github.com/guardian/support-frontend/pull/1805/files) broke the paypal button for monthly + annual (not single). This is because `contributionTypes[countryGroupId]` now has an array of objects not strings.
> Fix paypal

- support-frontend/assets/components/ticker/contributionTicker.jsx
- support-frontend/assets/helpers/campaigns.jsx
The ticker wasn't displaying when the amount was zero (falsey in JS). This hasn't been a problem previously because we've always had an initial amount. (Also apologies to reviewers for shoe-horning in a small copy change on this branch)
> Jtl ticker fix

- support-frontend/assets/components/ticker/contributionTicker.jsx
The goal on the ticker was not being populated by a local currency symbol automatically so I added the currency manually, as it's done for the current count. We should discuss if this is desirable in the future - if manual is desirable, the symbol could be moved to the campaign config
> Add currency to ticker (manually) - longer term strategy to be discussed

- support-frontend/assets/components/ticker/contributionTicker.jsx
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/stories/contributionTicker.jsx
All campaign-specific configuration should be abstracted to `campaigns.jsx` file. We identified that the local currency of the campaign is something that should be changed on a per-campaign basis and is currently being manually configured in the component. This PR moves the configuration to the configuration file, where it should be.
> Configure campaign currency

- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricPut.scala
- support-workers/cloud-formation/src/templates/cfn-template.yaml
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
Currently we have alarms to warn us if we have had no one-off contributions for an hour (in payment-api), but not for recurring.
This branch changes the `SendAcquisitionEvent` step to write cloudwatch metrics with name `PaymentSuccess`, and with the `PaymentProvider` and `ProductType` values as dimensions. 
The new cloudwatch alarms are for contributions only, but it would be easy to add more.
[**Trello Card**](https://trello.com/c/JEM3mVdt/1086-add-alarms-to-repeat-contributions)
> Cloudwatch alarms for contributions

- support-frontend/app/lib/CustomHttpErrorHandler.scala
- support-frontend/app/lib/ErrorController.scala
- support-frontend/app/wiring/AppComponents.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/conf/routes
I want to make sentry flag every time a real person hits a 500 error.  The first problem was testing it, so I have added a new route so we can see the 500 error page in dev easily.
Normally it would show a stack trace, and running in runProd mode doesn't have hot reloading or the ability to quit play without killing sbt.
[**Trello Card**](https://trello.com/c/ecHp74BG/2356-spike-investigate-what-we-can-do-with-putting-error-page-alerts-into-sentry-to-make-it-obvious-that-something-is-a-p1-issue-incl)
> add a new route to render the prod 500 error page in dev

- support-frontend/app/wiring/AppComponents.scala
After shipping https://github.com/guardian/support-frontend/pull/1823 we had a lot of actual 500 errors, this is because the error handler was coming back as null, due to the old favourite initialisation order issue in the class loader.
I didn't notice that because I was just trying the page I expected to intentionally show a 500 error, not realising that if I hit any other error page e/g. 404 it would also error with an actual 500 error!
I have changed it to a lazy val and 404 errors are now working
> make cyclical dependency be a lazy val to avoid NPE

- support-frontend/app/controllers/Subscriptions.scala
Passing a promo code into the pricing lookup on the Guardian Weekly landing page is causing it to respond very slowly so we are going to stop passing them in while we investigate.
> Don't pass a promocode into the pricing lookup 

- support-frontend/assets/components/ticker/contributionTicker.jsx
- support-frontend/assets/components/ticker/contributionTicker.scss
- support-frontend/public/ticker.json
The position of the progress bar relative to the marker is currently incorrect when we exceed the goal.
This PR fixes it, following the original logic in frontend introduced here https://github.com/guardian/frontend/pull/20874/files
I've had to make the marker a `div` rather than an `after` so that it can be transformed.
I've also fixed it so that it displays the current amount instead of the goal.
Before fix, for a very small amount above the goal it would exceed the marker by too much:
Above goal:
Below goal:
> Fix ticker behaviour when it exceeds goal

- support-frontend/assets/components/ticker/contributionTicker.jsx
The ticker gets stuck if its initial value is below 100 (it's initialised by `totalContributed * 0.8`).
This change makes it jump straight to `totalContributed` if that's the case.
> Fix ticker counter for low amounts

- support-workers/cloud-formation/src/templates/cfn-template.yaml
Make the alarm less noisy - we do sometimes go 2 hours without any gocardless contributions
Also simplified the period configuration a bit
> Increase gocardless missing data alarm to 10 hours

- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/test/fixtures/TestCSRFComponents.scala
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/encoding/JsonHelpers.scala
- support-models/src/main/scala/com/gu/support/promotions/Benefit.scala
- support-models/src/main/scala/com/gu/support/promotions/Promotion.scala
- support-models/src/test/scala/com/gu/support/promotions/Fixtures.scala
- support-models/src/test/scala/com/gu/support/promotions/SerialisationSpec.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummary.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/ServicesFixtures.scala
We want to use promotions to implement 6 for 6 rather than a lot of custom code because it allows a lot more flexibility for adding new prices and periods (n for n promotions) and would also mean that we could use them for other products. 
This is a first step towards that, it adds a new `IntroductoryPrice` type of promotion which describes n for n type promotions and hard codes an instance of this type (6 for 6) which applies to Guardian Weekly Quarterly pricing. The reason for hard coding this at this point is to avoid having to build the tooling to handle the new type in the membership promo codes tool.
The next step is to update the various React components to work with this new promotion type.
[**Trello Card**](https://trello.com/c/Jz30fbFH/2411-guardian-weekly-6-for-6-frontend)
> Introductory promotions

- support-frontend/assets/components/page/page.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
- support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx
UX design changes requested by @ionamckendrick to indicate that the user isn't on the 'final' thank you page they will see, but still in part of the flow.
[**Trello Card**](https://trello.com/c/b7e7Lhue/1105-visual-design-and-implementation-for-set-password-sign-up-screens)
* Removing page-level class for thank you set password screen
* Introducing component-level class granularity to make these screens more customizable in the future (as might be the case with forthcoming updates to the flow)
> Thank you 'set password' screen UX updates

- support-frontend/app/controllers/PayPalOneOff.scala
- support-frontend/app/services/PaymentAPIService.scala
- support-frontend/assets/helpers/routes.js
- support-frontend/conf/routes
Some long-awaited cleanup of routes no longer used in the new payment flow world.
We don't need a specific route for `cancelURL` even though PayPal does accept one as a parameter with `create-payment` requests, since we just send users back to the contributions page if they cancel.
We do need a specific route for errors, since we need to tell the user their payment has failed. Confusingly, we're the ones who redirect users to this page, not PayPal, because we find this out when we make the `execute-payment` request after the user has completed the PayPal flow.
> Clean up legacy routes

- support-frontend/assets/helpers/routes.js
This is needed to escape any URL-special characters email may contain (e.g. `+`!)
> URI encode the email in PayPal return URL

- support-frontend/assets/components/subscriptionCheckouts/billingPeriodSelector.jsx
- support-frontend/assets/helpers/billingPeriods.js
- support-frontend/assets/helpers/internationalisation/currency.js
- support-frontend/assets/helpers/productPrice/__tests__/priceDescriptionsTests.js
- support-frontend/assets/helpers/productPrice/__tests__/weeklyProductPrice.js
- support-frontend/assets/helpers/productPrice/priceDescriptions.js
- support-frontend/assets/helpers/productPrice/productPrices.js
- support-frontend/assets/helpers/productPrice/weeklyProductPrice.js
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
We have a lot of different places where pricing related copy is defined in the app, this leads to inconsistencies and makes it hard to make changes. This PR tries to centralise all pricing related copy in a new `priceDescription` module and makes that module aware of promotions, particularly introductory price type promotions which are used to model 6 for 6.
I have also created a new component `BillingPeriodSelector` which handles the display of available billing periods and their prices in the DP & GW checkout forms.
[**Trello Card**](https://trello.com/c/Jz30fbFH/2411-guardian-weekly-6-for-6-frontend)
> Billing period component

- support-frontend/assets/components/button/_sharedButton.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.jsx
- support-frontend/conf/DEV.public.conf
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
The post-deployment test was expecting a button with a certain selector to be present in order to confirm the page loaded. The selector changed on an earlier PR (https://github.com/guardian/support-frontend/pull/1851) so this test needs to be updated correspondingly. It is running and passing locally.
> Post-deployment test false positive fix

- support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
This is the client-side work required for retrieving the guest account creation token and adding in the "set password" screen for one-off contributions from cohort 5 (email not recognised, no password) using Stripe
[**Trello Card**](https://trello.com/c/3Go4Ramh/1088-add-password-setting-thank-you-page-for-one-off)
Flow, screen one:
Flow, screen two:
Flow, screen three:
Testing that sign in works for the account created on code:
> Client work for one-off Stripe payment guest account creation

- support-frontend/cloud-formation/cfn.yaml
Two reasons:
1. Following the outage on fri 24th may, we didn't actually get an alarm when the instances were sick.  This is because latency skyrocketed and the ELB was throwing 5xx errors, however our alarm is only on instance 5xx errors.  (in any case, 5xx errors were being thrown around that time due to another issue that hadn't been rolled back)
This PR adds both alarms above, and defines them as high severity in the [alerts doc.](https://docs.google.com/document/d/1_3El3cly9d7u_jPgTcRjLxmdG2e919zCLvmcFCLOYAk/edit)
2. I have also taken the opportunity to move away from a technical notation of the alerts and more towards and action and impact based notation.
The essence is that every alarm name is of the form
`HIGH severity - <service> <what is happening>`
and every description is of …
> add latency/5xx alarms and improve descriptions

- support-frontend/assets/pages/contributions-landing/components/SetPasswordForm.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
UI changes from @ionamckendrick 
[**Trello Card**](https://trello.com/c/zVwQx1QB/1139-colour-tweaks-to-footer-and-buttons-across-pages)
Landing page with navy footer:
Set password with black CTA:
> Contributions UI changes

- support-frontend/assets/components/headers/roundelHeader/header.jsx
- support-frontend/assets/helpers/fontLoader.js
We were getting Sentry errors, proclaiming that `Object.values is not a function`. 
Object.values is not supported by all browsers,  [see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values)
Luckily, we only use it twice, so we can just replace them with a slightly more verbose `Object.keys` then `map`
> Remove Object.values

- support-frontend/assets/components/forms/customFields/checkbox.scss
- support-frontend/assets/components/subscriptionCheckouts/billingPeriodSelector.jsx
- support-frontend/assets/components/subscriptionCheckouts/cancellationSection.jsx
- support-frontend/assets/components/subscriptionCheckouts/personalDetails.jsx
- support-frontend/assets/components/subscriptionCheckouts/personalDetailsGift.jsx
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/rules.js
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
The intention is that users can give Guardian Weekly as a gift, and specify this in the checkout.
There are a number of assumptions underpinning the changes, which are listed in the [**Trello Card**](https://trello.com/c/JwbDPHwv/2412-gifting-in-gw-checkout-frontend)
* There's a checkbox that users can select that indicates the order is a gift
* Users who select 6 for 6 won't see the gifting option
* Users who select the gifting option won't see 6 for 6 as an alternative option further down in the checkout
* When the user checks the gifting box, additional fields appear asking for the gift recipient's details and a form for the recipient's address (aka the delivery address). There's still a section asking if billing is the same as delivery address, but the wording is slightly different to …
> Add gifting to Weekly checkout

- support-frontend/assets/components/marketingConsentNew/marketingConsent.jsx
Grammar police 🚓 
Also an observation: we're using different messaging here to the standard supporter marketing consent - but the guidance is generally to be as consistent as possible, because there is a legal requirement to know what text was shown to a user when they consented.
Added a comma.
> Missing comma on thank you page

- support-frontend/cloud-formation/cfn.yaml
I shipped https://github.com/guardian/support-frontend/pull/1854 but the latency alarm wasn't showing data, because I copied it from an ELB one and forgot to change the type.  This PR fixes that!
correct one is this metric:
and this is the one in the alarm
> support latency metric should be on ApplicationELB not ELB

- support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js
It's coming through sometimes as `(not set)` in GA, which I'm 90% certain is when we pass an empty string.... but I want to be 100% certain
> Be explicit when string is empty

- support-frontend/assets/pages/contributions-landing/components/ContributionState.jsx
Until we understand why/when our polyfill isn't working, we're going to be defensive about our use of `Object.entries` and `Object.values` which are the ones throwing Sentry errors.
There are other uses of `Object.entries` in the codebase, but they're in storybook or build pipeline code, not code executed in users' browsers
> Replace Object.entries with Object.keys

- support-frontend/app/views/main.scala.html
- support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We're seeing about 6 cases per half an hour where, even after the polyfill script loads, `Object.values` and `Object.entries` are not available. Extrapolating to a day, this accounts for the number of sentry errors we were seeing for `Object.values is not a function` (approx 250 - 350 per day)
I noticed v3 is actually the latest version. So I thought I'd try that and see if the problematic cases go away.
I've renamed the events so we can clearly distinguish ones from browser using the v3 polyfill
> Try polyfill v3

- support-services/build.sbt
- support-services/src/main/scala/com/gu/support/promotions/PromotionCache.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionCollection.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionCacheSpec.scala
To lookup promo codes we currently need to do a full scan of the Dynamo DB table where they are stored. This is because the promo code itself is within a Json blob that needs to be deserialised before we can search against it. 
This causes scalability issues on uncached pages, so to prevent these we want to cache the deserialised promotions in memory and search against those rather than hitting Dynamo every time.
To avoid threading issues I am using [Scala-STM](https://nbronson.github.io/scala-stm/) to manage the cached promotions and initially I am caching the promotions for 1 minute.
> Cache list of promotions in memory

- support-frontend/assets/components/subscriptionsByCountryGroup/subscriptionsByCountryGroup.jsx
- support-frontend/build.sbt
- support-frontend/test/selenium/subscriptions/LandingPagesSpec.scala
- support-frontend/test/selenium/subscriptions/pages/DigitalPackSubs.scala
- support-frontend/test/selenium/subscriptions/pages/PaperSubs.scala
- support-frontend/test/selenium/subscriptions/pages/ProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/SubsLandingPage.scala
- support-frontend/test/selenium/util/DriverConfig.scala
We already have post deployment tests for the paper and Guardian Weekly product pages, this adds equivalent tests for the Digital Pack page and the subscriptions landing page.
> Subs landing page post deployment test

- support-frontend/cloud-formation/cfn.yaml
@jfsoul suggested it, and I thought it was a nice idea https://github.com/guardian/support-frontend/pull/1854#pullrequestreview-245907984
The real reason is there could be an issue preventing instances coming into service.  Instances could also be silently cycling in and out of service.  It would be good to realise this because the site goes down completely, if it's in working hours.  This alarm is unlikely to have many false alarms so it should be valuable.  It is not indicating an actual issue affecting users immediately, so it doesn't have to be as urgent as the other urgent alarms?
[**Trello Card**](https://trello.com/c/mIRQe53c/2416-add-alert-for-less-than-required-instances-of-support-frontend-for-10-min-period)
Tested in CODE: yes
> add reduced healthy instances alarm

- support-frontend/assets/components/subscriptionsByCountryGroup/subscriptionsByCountryGroup.jsx
- support-frontend/assets/helpers/formValidation.js
Landing page was breaking on local and code after one-off contributions because object was undefined. I added checks to make sure the object exists before we try to pull values from it. Larger analysis required to understand what changes were made that were caused this problem and why it only seems to affect local and code.
* Added checks for object existing
* Linted code base
> bugfix: added defensiveness around object checking in `checkAmountOrOtherAmount`

- support-frontend/app/views/main.scala.html
- support-frontend/assets/helpers/tracking/ophan.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We're putting through over 100,000 of the "debug" events per day right now (since we fire 3 per pageview). I'm a bit worried about GA costs.
Conclusions so far:
- 30 to 40 script loading errors per day, in a variety of countries & browsers (probably connectivity issues, nothing we can do here)
- 100 to 150 sessions per day where `Object.values` and `Object.entries` are unavailable after polyfill. 98% of these are in France on one specific version of chrome. weird!
- 0 cases where only one of `Object.values` or `Object.entries` was available before or after polyfill (either both or neither)
All we really need to track is the failure cases. I also don't think we're ever going to use the data lake to analyse this data. So I've just got GA tracking:
- when `Object.values` is unavailable after …
> Only fire events on polyfill failures

- support-frontend/assets/helpers/subscriptionsForms/submit.js
DD voucher checkout is breaking with an error 
```
Uncaught TypeError: Cannot read property 'Monthly' of undefined
at m (productPrices.js:110)
at E (submit.js:132)
at formActions.js:98
```
This is because this param doesnt go thrugh to getProductPrices, it should be the last param
so when it arrives it is undefined at the moment, causing an empty results
The structure of the productPrices object is like this:
> add product option into the guardian delivery price lookup

- support-frontend/assets/components/progressMessage/progressMessage.jsx
- support-frontend/assets/components/progressMessage/progressMessage.scss
When a user is in the GW checkout and has entered payment details and pressed 'Pay £6', they see a processing state in the modal, then the modal closes and they should see the checkout page with a darker overlay over the page and a message that says 'Processing transaction, please wait' and some loading dots. When the processing is complete, they are moved on to the thank you page.
The work involved was to apply the correct styling to this (already existing) payment state. 
Applies the styling that was already in existence but not attached to the component.
(You can see the text, unstyled, at the bottom left)
> Adds styling for processing overlay in weekly checkout

- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductRatePlan.scala
- support-models/src/main/scala/com/gu/support/zuora/api/SubscriptionData.scala
- support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionApplicator.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
We want to be able to create 6 for 6 subscriptions to Guardian Weekly
I have implemented 6 for 6 slightly differently to the way that it was done in the old site, it is now a promotion of the type `IntroductoryPrice` which has a price and a duration (£6 & 6 weeks). This will allow us to do 'n for n' promotions in the future but there will still be a bit of work needed to support that.
The website should now pass in `Quarterly` as the billing period, which is the subscription that the user will move onto after the introductory period, rather than `SixWeekly` as in the old site.
I've also had to add `productRatePlanChargeIds` for the GW `SixWeekly` billing period as this is used in setting up the introductory pricing period.
I have tested this on code against the old site and the …
> 6 for 6 Guardian Weekly promotions

- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
The checkout post deployment tests are failing in PROD because geolocation is putting the test client into the US version of the checkout whereas the tests are written to work with the UK version.
This change makes the client go to the UK version of the landing page before the checkout to force it into the correct country.
> Make sure that post deploy subs checkouts are on the UK version of the page

- support-frontend/nginx/Brewfile
- support-frontend/nginx/README.md
- support-frontend/nginx/setup.sh
- support-frontend/nginx/support.conf
- support-frontend/setup.sh
dev-nginx contains a number of generic useful scripts to:
- issue certs locally (and automatically trust them)
- edit hosts file
- symlink nginx configs
- restart nginx
Using dev-nginx means:
- we're creating certificates locally, valid only to a single machine
- we do not need to update certs every year as they expire (https://github.com/guardian/support-frontend/pull/1355), we just need to re-run the script when certs expire
- we do not need an S3 bucket holding certs for local dev
Depends on:
- https://github.com/guardian/dev-nginx/pull/5
- https://github.com/guardian/homebrew-devtools/pull/35
- https://github.com/guardian/dev-nginx/pull/7
We probably could move to using [`setup-app`](https://github.com/guardian/dev-nginx/blob/master/README.md#setup-app) too, removing the …
> use dev-nginx for setting up nginx in DEV

- support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.jsx
- support-frontend/assets/components/directDebit/directDebitForm/sortCodeInput.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
- support-frontend/test/selenium/subscriptions/pages/DirectDebitForm.scala
We want to have a post deployment test which checks that Direct Debit is still working correctly so that we can tell immediately if we break it.
This PR adds Direct Debit as a payment method to the subs checkouts Selenium tests and uses it on the paper checkout. This means that we are now testing
* UK Digital Pack checkout with Stripe
* Paper checkout with Direct Debit
[**Trello Card**](https://trello.com/c/tOADTOUP/2425-add-post-deploy-tests-for-the-subs-checkouts)
> Add a post deployment test for Direct Debit

- support-frontend/app/wiring/AppLoader.scala
Otherwise it can't find credentials when running locally
> Pass CredentialsProvider to simple configuration

- support-frontend/assets/helpers/logger.js
- support-frontend/package.json
- support-frontend/yarn.lock
The [old official Raven library](https://docs.sentry.io/clients/javascript/) is deprecated, the new one is called [Sentry](https://docs.sentry.io/error-reporting/quickstart/?platform=browser).
[**Trello Card**](https://trello.com/c/ckxSy7oV/2427-update-raven-to-sentry-library)
I got it working locally
> update sentry client side lib to the new one

- support-frontend/app/services/HttpIdentityService.scala
Inexplicably (there may well have been a reason once, but it's weird), we were explicitly not sending a "validate your email address" email to people who set a password in the thank you flow (but we were telling people that we were sending them one). 
This PR fixes this.  
> Actually send validation email for those who have just set a password

- support-frontend/assets/components/marketingConsentNew/marketingConsent.jsx
- support-frontend/assets/components/spreadTheWord/spreadTheWord.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.scss
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
We want as many people to sign in as possible. This is a tracked link with copy to go to profile.theguardian.com with email prefilled that renders for people who are not signed in. Hopefully this will up our number of people we can recognize on site after they've contributed.
[**Trello Card**](https://trello.com/c/dxrQCGzW/1186-thank-you-page-for-cohorts-34-sign-in)
> Generic sign in on thank you page

- support-frontend/test/selenium/conf/selenium-test.conf
#1897 broke local selenium tests because it stopped the local private config loading by default, this PR loads it in the selenium-test.conf so that it is available to the tests.
> Fix local Selenium tests

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
"weekly breakdown monthly as well" is marginally ahead, and the test has been running for ages.
original test PR: https://github.com/guardian/support-frontend/pull/1776
> Remove editorialiseAmountsRoundTwo test

- support-frontend/assets/components/button/trackableAnchorButton.jsx
- support-frontend/assets/components/button/trackableButton.jsx
- support-frontend/assets/helpers/tracking/ophan.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/SetPasswordForm.jsx
1. We need to get numbers for how many users are seeing the "sign in" button to get a sense of the percentage that are 'converting' to signed in
2. It makes sense to track the 'decline to set password' across the same dimension (contribution type) that we are now tracking those who do set a password
[**Trello Card**](https://trello.com/b/QVWhizic/contributions)
* Added a tracking event to `ophan.js` for components loading
* Made trackable versions of the reusable button component using the `componentDidMount` lifecycle hook
* Integrated new tracking event and trackable button on the thank you page
* Updated the tracking on 'decline to set password' link to include contribution type
> Update analytics for cohorts 3, 4, 5

- support-frontend/assets/helpers/subscriptionsForms/deliveryDays.js
- support-frontend/assets/pages/paper-subscription-checkout/helpers/__tests__/deliveryDays.js
- support-frontend/assets/pages/paper-subscription-checkout/helpers/deliveryDays.js
- support-frontend/assets/pages/paper-subscription-checkout/helpers/options.js
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.js
There are a couple of issues with our fulfilment delay calculation for vouchers:
- We are only applying a delay of 2-3 weeks rather than 3-4 weeks, which puts us out of step with subscriptions-frontend and unable to fulfil some subscriptions.
- We are currently calculating lead time based on whether the current day is after a Weds (correct) *AND* whether the current day is after the delivery day of the product (incorrect).  For example, an Everyday sub taken out on a Monday or Tuesday should have the same first delivery day - but at the moment the Tuesday one is pushed a week because Tuesday falls after the delivery day (Monday) of the product.
The latter issue above is resolved by now using a different rule:
- Find the date of the delivery day of the product in the _current_ week
- Add 3 …
> Increase fulfilment delay for voucher subs

- support-frontend/assets/helpers/subscriptionsForms/submit.js
There was a bug in the way we were passing promo codes to the backend for Guardian Weekly - Quarterly subs were using the 6 for 6 promo code. This fixes that.
> Fix promo code handling for 6 for 6 & Quarterly

- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
- support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/GuardianWeeklyEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperFieldsGenerator.scala
- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
When a user purchases a Guardian Weekly subscription we want to send them an email confirming what they have purchased.
Changes:
* Pass the promo code through to the `SendThankYouEmail` lambda so that we can tell when a subscription is 6 for 6.
* Add a `GuardianWeeklyEmailFields` case class to generate the necessary data for the email
* Update the `SubscriptionEmailFieldHelpers.describe` method to cope with 6 for 6
[**Trello Card**](https://trello.com/c/uTIjJqm5/2336-guardian-weekly-thank-you-email)
> Guardian Weekly thank you email

- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
- support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/GuardianWeeklyEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperFieldsGenerator.scala
- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
Reverts guardian/support-frontend#1931 and fixes the bug which caused the need to revert.
The bug was caused by an inexhaustive match here:
https://github.com/guardian/support-frontend/pull/1934/files#diff-70fe76ca8499c5f480387ae9c0077934R27
and caused contribution emails to fail because the app couldn't find the correct product rate plan id
> Revert "Revert "Guardian Weekly thank you email""

- support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.jsx
We're loading a full size crop of one the images on the digipack product page (variant only).  Reducing that down to a more reasonable 1000px width, which reduces the weight significantly.
To be honest I'm not entirely clear what `sizes="(min-width: 480px) 100%, (max-width: 660px) 100%, 100%"` is trying to achieve.  To me that is saying at any width of viewport set the width of the image to 100% 😕 
* Change 1
* Change 2
Before (1.2MB):
After (161KB):
> Use smaller image size for premium app

- support-frontend/assets/components/subscriptionCheckouts/billingPeriodSelector.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
The idea is to make the GW checkout as straightforward as possible, so no matter which billing period the user selects, we show gifting in the checkout, and we show 6 for 6 even if they selected quarterly or annual on the landing page. Based on this [**Trello Card**](https://trello.com/b/TjUElW0B/simple-and-coherent-product-supporting-the-guardian)
* Removes the code that hides gifting if the user selects 6 for 6 
* Removes the code that hides 6 for 6 if the user selects gifting
> Include 6 for 6 and gifting

- support-frontend/assets/helpers/campaigns.jsx
Toxic America is no longer running. When launching this campaign, we simplified the routing such that the name for a campaign can just be removed from the code base to end a campaign.
[**Trello Card**](https://trello.com/c/uWCnyMVS/1194-toxic-america-shut-down-to-do-list)
* Remove the campaign name
> Disable Toxic America

- support-workers/cloud-formation/src/templates/cfn-template.yaml
We've recently had an outage where paper checkout was down for 11am one day to 17h the next day. We've been wanting to add a cloud watch alarm that goes off when acquisition flatlines for a while now, but after that outage this was bumped in priority.
[**Trello Card**](https://trello.com/c/5vAIlA4j/2419-add-alarms-for-no-conversions-within-x-hours-days-to-all-variants)
* Adds two alarms NoPaperAcquisitionInOneDayAlarm and NoDigipackAcquisitionInEightHoursAlarm. So that's 24h and 8h for paper and digipack respectively.
* The general idea is to use a calculate metric that sums all the individual payment type metrics. This allows us to have a global alert, on all acquisition, rather than independent alerts per payment type. The implementation is slightly obscure, if anyone knows of a clearer …
> Add alerts for DigiPack and Paper checkout flows

- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
- support-models/build.sbt
- support-models/src/main/scala/com/gu/support/workers/states/SendAcquisitionEventState.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
Some additional tracking for Guardian Weekly acquisitions:
* Add a label to record whether a subscription is 6 for 6 - this reproduces existing functionality
* Add a label to record whether a subscription is a gift this is represented as a custom dimension in GA and a label in the Data Lake.
* Update the acquisitions-event-producer library to work with these new labels
* Change the click tracking on the GW landing page CTAs to include the billing period in the id, otherwise this information never makes it into the Data Lake.
[**Trello Card**](https://trello.com/c/Q33ZsM7n/2390-analytics)
> Analytics for Guardian Weekly

- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/assets/helpers/globals.js
- support-frontend/assets/helpers/render.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
To launch GW checkout we need to update the landing page so that it goes to the new checkout. We will then run a test in Optimize to send a proportion of our traffic to the new flow for testing.
* Update url generation code to switch between the old an new checkout based on experiment variant
* Update the copy around gifting on the GW landing page
* Remove Google auth from the new checkout page
* There are quite a few small changes which have been made automatically by Eslint
[**Trello Card**](https://trello.com/c/Wjqqlnrp/2436-phased-rollout-gw) & [also]( https://trello.com/c/t9d6wXyW/2428-remove-google-auth-from-gw-checkout-just-before-go-live)
> Weekly landing page

- support-workers/src/main/scala/com/gu/emailservices/GuardianWeeklyEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperFieldsGenerator.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
For subscriptions that have been bought as gifts we want to reflect that fact in the thank you email. To do this we need to send the giftee's first and last name to membership workflow which actually sends the email
> Add giftee name fields to the emails

- support-frontend/assets/helpers/optimize/optimize.js
- support-frontend/assets/helpers/optimize/optimizeScript.js
- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/package.json
After launching the digital pack landing page (which was an A/B test between the first and second screenshot), we noticed that sometimes people would be shown the original page, while being identified to Optimize (the A/B testing platform) as being part of the Variant sample, this meant the results for the test are invalid as we could not be sure which view the user was seeing 
- add mapState to digital pack landing page, to allow the page to re-render when there is a change to the redux store
- change LandingPage component to a class Component, in order to as state to facilitate a re-render
- added an anti flicker function to control when the page is shown
- removed a call to optimize.js, so optimize.js it only called once 
- add polling to …
> WIP feat: add mapState to digi pack landing page

- support-workers/src/main/scala/com/gu/emailservices/FailedGuardianWeeklyEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
We are currently getting errors in the failure handler because of unimplemented function stubs, this PR adds some placeholder code to prevent the errors until a proper implementation can be put in place.
> Put some placeholders in for subs failure emails

- support-frontend/app/assets/AssetsResolver.scala
- support-frontend/test/fixtures/DisplayFormMocks.scala
We pre-render some of our pages at build-time. At runtime we load the html from file and insert it into the twirl template.
The contributions landing page [will soon use pre-rendering](https://github.com/guardian/support-frontend/pull/1928). We'll be serving a lot of requests with pre-rendered content, so it makes sense to have it in memory.
> Cache pre-rendered html in memory

- support-frontend/cloud-formation/cfn.yaml
These are in the private subnet now so a public IP address is useless
> No public IP address for instances

- support-workers/scripts/show-failed.sh
- support-workers/scripts/show-successful.sh
Add 2 scripts to make it easy to check the outcome of support-workers executions from the command line:
* `show-successful.sh n` will show the request info from the last `n` successful executions to make it easy to see the results of those executions. 
Eg. `./show-successful.sh 3` returns:
``` json
{
"encrypted": true,
"testUser": true,
"failed": false,
"messages": [
"Payment method is DirectDebit",
"Product is Paper-Collection-Everyday"
],
"accountExists": false
}
{
"encrypted": true,
"testUser": true,
"failed": false,
"messages": [
"Payment method is Stripe",
"Product is Monthly-DigitalPack-GBP"
],
"accountExists": false
}
{
"encrypted": true,
"testUser": true,
"failed": false,
"messages": [
"Payment method is Stripe",
"Product is Annual-Contribution-USD-50"
],
"accountExists": false
} …
```
> Show executions scripts

- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
We want to switch over to using the new Guardian Weekly checkout for all traffic.
[**Trello Card**](https://trello.com/c/Gw0EzkE0/2451-launch-gw)
> Switch to using the new GW checkout for all traffic

- support-frontend/assets/helpers/user/__tests__/__snapshots__/userReducerTest.js.snap
- support-frontend/assets/helpers/user/__tests__/userTest.js
- support-frontend/assets/helpers/user/defaultUserActionFunctions.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/helpers/user/userActions.js
- support-frontend/assets/helpers/user/userReducer.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
If the user is logged in then the `GU_U` cookie has the `emailValidated` field. This means we know whether to tell the user to validate (aka verify) their email before getting the benefits of being signed in.
This also includes CTA for signed in, unverified users to click. The CTA loading is being tracked (loading) `sign-into-the-guardian-link-loaded-{payment-type}` (clicked) `sign-into-the-guardian-link-{payment-type}`
> Get emailValidated from cookie

- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/GeoRedirect.scala
- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/app/lib/RedirectWithEncodedQueryString.scala
Extending @tomrf1 's work here: https://github.com/guardian/support-frontend/pull/1884
Which will eliminate 500 errors when users come to the site from a URL which includes a dash in the query parameters
Tested the offending urls: 
https://support.thegulocal.com/contribute?INTCMP=side_menu_support_contribute&acquisitionData=%7B&quo.%E2%80%99
https://support.thegulocal.com/subscribe?INTCMP=side_menu_support_contribute&acquisitionData=%7B&quo.%E2%80%99
> Redirect with encoded query string on application and subscription controllers

- support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.jsx
- support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.scss
- support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx
- support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
- support-frontend/assets/helpers/user/__tests__/userTest.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
- support-frontend/assets/pages/paper-subscription-checkout/_legacyImports.scss
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
The Direct Debit form on the Guardian Weekly checkout is missing its styling. To fix this I've changed the DD components to include their own styling rather than relying on the page css to import it for them, then I've removed the page level imports from Paper and Digital Pack.
**Before**
**After**
> Make the DD form components include their own styling

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
During campaigns we link readers to e.g. `/us/contribute/toxicamerica`.
Validation of the campaign code at the end of the url path is done client-side.
This change ensures that if a campaign code is invalid or discontinued then we redirect to `/us/contribute`. Note that it's a client-side routing redirect rather than a proper redirect, but the url in the browser will be updated.
> Redirect if campaign code is invalid

- support-frontend/assets/components/button/anchorButton.jsx
- support-frontend/assets/components/button/button.jsx
- support-frontend/assets/components/consentBanner/consentBanner.jsx
- support-frontend/assets/components/forms/customFields/checkbox.jsx
- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.jsx
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeFinder.jsx
- support-frontend/assets/components/subscriptionCheckouts/personalDetails.jsx
- support-frontend/assets/components/subscriptionCheckouts/subscriptionSubmitButtons.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/showcase/components/ctaContribute.jsx
- support-frontend/assets/pages/showcase/components/ctaSubscribe.jsx
- support-frontend/assets/pages/showcase/components/otherProduct.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx
- support-frontend/stories/button.jsx
- support-frontend/stories/dialog.jsx
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
- support-frontend/test/selenium/subscriptions/pages/DigitalPackProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyCheckout.scala
- support-frontend/test/selenium/subscriptions/pages/PaperProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/WeeklyProductPage.scala
Now that the Guardian Weekly checkout is live we want a post deployment test to check that it is working correctly.
I have also standardised the naming of tests related to the product pages as we had a mixture of 'landing page' and 'product page' previously 
[**Trello Card**](https://trello.com/c/8mnN8u2s/2459-add-post-deploy-test-for-guardian-weekly)
> GW post deploy test

- support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyCheckout.scala
Running the Guardian Weekly post deploy test is causing step function failures because the currency is being passed through incorrectly. This _seems_ impossible to do as a normal user but we will keep an eye on it to see if it does occur IRL. 
In the meantime the fix is to set the billing country in the test script.
> Explicitly set the billing country

- support-frontend/assets/helpers/externalLinks.js
At present it goes to a 404 but it should go to https://www.theguardian.com/help/2017/dec/11/help-with-delivery#nav1
> fix help url on GW thank you page

- support-frontend/assets/components/button/_sharedButton.jsx
- support-frontend/assets/pages/showcase/components/ctaContribute.jsx
- support-frontend/assets/pages/showcase/components/ctaSubscribe.jsx
The aim is to improve visibility of clicks on support page call-to-action buttons.
[**Trello Card**](https://trello.com/c/AZktsdvl/2454-dev-add-ga-tracking-to-subscribe-and-contribute-cta-buttons-in-why-support-page)
> Adds tracking for support page CTAs

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
Arriving at the thank you page without the correct state in local storage will cause a recurring payment message to appear. This is because it defaults to monthly. We've had reports of users seeing this and it causes confusion if they've made a one-off contribution.
This change ensures the message is only displayed if `paymentComplete` is true.
[**Trello Card**](https://trello.com/c/b7bxzu6R/1183-ensure-that-the-default-thank-you-page-copy-does-not-reference-contribution-type)
Default view:
After recurring payment:
> Do not show recurring message on default thank you page

- support-workers/docs/triggered-send-in-exact-target.md
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/PaperFieldsGenerator.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
We no longer need to send the SubscriberKey field in the email JSON as this was an ExactTarget thing and now we use Braze, it is not needed.
This PR: https://github.com/guardian/membership-workflow/pull/194 removed it from membership-workflow
> Remove the SubscriberKey from email fields

- support-frontend/assets/helpers/legal.js
Because the current print checkout has terms and conditions that apply to GW. This updates the link to the print T&C.
[**Trello Card**](https://trello.com/c/3wn616jG/2444-tc-link-on-print-only-checkout-pointing-to-gw-terms)
> Fix the terms and conditions link for print checkout

- .gitignore
When I do a "yarn build-prod" I always get a file that should proably be ignored.
`/conf/assets.map`
it contains this:
```json
{
"main.css": "stylesheets/main.css",
"main.js": "main.3ca69c0ccd35ca697315.bundle.js",
"runtime~main.js": "runtime~main.3ca69c0ccd35ca697315.bundle.js",
"vendors~main.js": "vendors~main.3ca69c0ccd35ca697315.bundle.js",
"3.3ca69c0ccd35ca697315.bundle.js": "3.3ca69c0ccd35ca697315.bundle.js",
"iframe.html": "iframe.html",
"stats.json": "stats.json"
}
```
> ignore assets file in the root

- support-frontend/assets/components/headers/links/links.jsx
- support-frontend/assets/pages/showcase/components/ctaContribute.jsx
- support-frontend/assets/pages/showcase/components/ctaSubscribe.jsx
- support-frontend/assets/pages/showcase/showcase.jsx
To make sure that we have GA tracking and Ophan data collection set up for the why support page CTAs and also for the support header navbar.
[**Trello Card**](https://trello.com/c/FjJI3VaI/2455-tracking-audit-implement-tags-to-allow-reporting-from-datalake)
> Add ophan tracking to why support page and header nav

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/GeoRedirect.scala
- support-frontend/app/models/GeoData.scala
- support-frontend/app/utils/FastlyGEOIP.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/internationalisation/country.js
- support-frontend/assets/helpers/subscriptionsForms/subscriptionCheckoutReducer.js
- support-frontend/assets/helpers/user/__tests__/userReducerTest.js
- support-frontend/assets/helpers/user/__tests__/userTest.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/helpers/user/userActions.js
- support-frontend/assets/helpers/user/userReducer.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
- support-frontend/assets/pages/contributions-landing/setUserStateActions.js
- support-frontend/test/actions/CachedActionTest.scala
- support-internationalisation/src/main/scala/com/gu/i18n/Country.scala
Pre-fills the US State and Canada Province value on the Contributions flow, defaulting to the user's billing account or GEO-IP value.
There are thousands of recurring contributions assigned to the Alaska state due to people just picking the first item of the list, and a historical bug which set the state to Alaska back when the field was not required.
https://trello.com/c/ZexwHuvs
- Check caching settings, if we're varying the checkout by country, we may cache state codes
- The new header needs adding to Fastly (tested on CODE as the header passes through from the browser)
> Prefill the US/CA state code in the Contributions checkout form

- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
- support-frontend/test/selenium/contributions/RecurringContributionsSpec.scala
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
- support-frontend/test/selenium/subscriptions/pages/Register.scala
- support-frontend/test/selenium/util/PostDeployTestUser.scala
The current post-deployment tests bypass the 3rd party payment inputs.
But we should be verifying that stripe + paypal actually appear when you hit the contribute button.
In the past we've found writing selenium tests for the 3rd party checkout flows unreliable as we do not control the code, so these new tests just check that the stripe popup + paypal page appear.
[**Trello Card**](https://trello.com/c/1SYbMnNz/1124-make-post-deployment-test-click-on-paypal-direct-debit-buttons-confirm-at-least-that-popup-appears)
> Post-deploy tests: check that Stripe popup and PayPal page appear (contributions)

- support-frontend/cloud-formation/CODE-deploy.sh
- support-frontend/cloud-formation/cfn.yaml
When a deploy is happening, there are new instances coming into service as well as old ones which haven't been killed yet.  The requests are distributed between all healthy instances.
For each build, we serve assets with a different URL.  This is the hash in the URL which is introduced to make sure the cache is busted.  Anyone fetching the newly deployed page would request a fresh copy of the assets on the new url in a separate request.
There is currently a problem when a deploy goes out since the main html request and the assets request could be send to different servers running different versions.  This would result in the server returning a 404 as it doesn't understand that version.  The client would then end up with either a blank page or an unstyled page.
The plan is fix this by …
> feat: added cloudformation S3 bucket creation

- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.js
- support-frontend/assets/helpers/page/commonActions.js
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
We have found a bug in the GW checkout:
- go to the subscription page with a non-AU/NZ region selected
- enter a delivery address in AU or NZ
- change the Is the billing address same as delivery to "Yes"
- Press the Buy button
- After entering the card details, the checkout will fail with an error in the step function because it uses the wrong Stripe key to obtain a token.
[**Trello Card**](https://trello.com/c/VyjhhAyX/2480-aud-gw-bug)
> Fix problem with incorrect currency on GW checkout

- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/helpers/tracking/doNotTrack.js
- support-frontend/assets/helpers/tracking/googleTagManagerScript.js
I have spotted that we are firing two Ophan page views per page with different viewIds. 
This is down to the way that Ophan is triggered just by importing it into a file: Because the googleTagManagerScript.js file imported the `doNotTrack` function from page.js (which fires the first page view) it meant that it was being fired twice.
[**Trello Card**](https://trello.com/c/pGaBYCf5/2483-investigate-double-counting-in-ophan-page-views)
> Stop two separate Ophan pageviews being fired per page load

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
We want to test the performance (on singles and AV) of reminding people that giving small donations is appreciated and welcome
[**Trello Card**](https://trello.com/c/Ieir5ArE/1206-test-adding-line-all-contributions-big-and-small-on-landing-page)
* Defined abtest
* Integrated into contributions landing page
Control and 'Not in Test':
Variant (named 'allContributions'):
> Landing page copy test

- support-frontend/assets/helpers/user/__tests__/__snapshots__/userReducerTest.js.snap
- support-frontend/assets/helpers/user/__tests__/userActionsTest.js
- support-frontend/assets/helpers/user/__tests__/userReducerTest.js
- support-frontend/assets/helpers/user/defaultUserActionFunctions.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/helpers/user/userActions.js
- support-frontend/assets/helpers/user/userReducer.js
We want to know if a user has given a single contribution before so we can customize messaging on the landing and thank you pages. This is the first step to enable this work - we will probably also want to request information contribution history for returning contributors.
[**Trello Card**](https://trello.com/c/gnO74GFW/1270-recognize-single-contributors-on-landing-page-using-cookie)
* Testing presence of cookie and adding to state using Redux
* Expanding user reducer and actions tests
> Reading single contributor cookie and putting in state

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
This is a revision of https://github.com/guardian/support-frontend/pull/1974
Having spoken with UX about some concerns I had about this currently running test, we decided to halt and redeploy to ensure we know what we're testing.
[**Trello Card**](https://trello.com/c/Ieir5ArE/1206-test-adding-line-all-contributions-big-and-small-on-landing-page)
Control: 
Variant:
> Landing page copy test revision

- support-frontend/assets/helpers/page/page.js
- support-frontend/package.json
- support-frontend/yarn.lock
To avoid a recurrence of the double page view bug which was fixed in #1976 I have changed ophan-tracker-js to require an explicit `init()` function call to trigger a page view (see https://github.com/guardian/ophan/pull/3378).
This PR upgrades to the latest version of ophan-tracker-js and calls `init()` in page.js `analyticsInitialisation()`.
[**Trello Card**](https://trello.com/c/pGaBYCf5/2483-investigate-double-counting-in-ophan-page-views)
> Upgrade ophan-tracker-js to 1.3.17

- support-frontend/assets/components/generalErrorMessage/generalErrorMessage.jsx
- support-frontend/assets/components/generalErrorMessage/generalErrorMessage.scss
This is a production bug on the payment failure message in GW checkout - the styling of the payment failure message was missing in the component. Details are in this [**Trello Card**](https://trello.com/c/WhIfBnYZ/2472-design-broken-on-payment-failure-on-gw-checkout).
> Reinstates styles on payment failure message in GW checkout

- support-frontend/assets/components/headers/links/links.jsx
- support-frontend/assets/components/radioToggle/radioToggle.jsx
- support-frontend/assets/components/socialShare/socialShare.jsx
- support-frontend/assets/components/subscriptionCheckouts/thankYou/marketingConsentContainer.jsx
- support-frontend/assets/helpers/checkoutForm/onFormSubmit.js
- support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js
- support-frontend/assets/helpers/optimize/optimizeScript.js
- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/tracking/behaviour.js
- support-frontend/assets/helpers/tracking/conversions.js
- support-frontend/assets/helpers/tracking/doNotTrack.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
- support-frontend/assets/helpers/tracking/googleTagManagerScript.js
- support-frontend/assets/helpers/tracking/ophan.js
- support-frontend/assets/helpers/user/__tests__/userActionsTest.js
- support-frontend/assets/helpers/user/defaultUserActionFunctions.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/jsconfig.json
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/ExistingRecurringContributorErrorMessage.jsx
- support-frontend/assets/pages/contributions-landing/components/MarketingConsentContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/MustSignIn.jsx
- support-frontend/assets/pages/contributions-landing/components/SetPasswordForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/showcase/components/ctaContribute.jsx
- support-frontend/assets/pages/showcase/components/ctaSubscribe.jsx
Our tracking has got a bit messy as it has grown, for instance we respect consent settings and do not track headers in most places but not all, we will need to fix this as part of the upcoming consent work, and this PR makes that easier.
Also we have quite a lot of 'behavioural' tracking (tracking related to a user's behaviour on the site such as button clicks) and are about to add more to cover checkouts. This was all in the Ophan module even though it tracks through GA as well as Ophan. I've moved it into its own module 'behaviour' to make it cleaner. 
[**Trello Card**](https://trello.com/c/3gQHLqpZ/2467-consent-phase-2-dev-work)
* Respect do not track header in all tracking
* Move all behavioural tracking to a separate module.
> Tracking improvements

- support-frontend/assets/helpers/checkoutForm/onFormSubmit.js
- support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/helpers/tracking/behaviour.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
We want to track the payment method that a user chooses to checkout with so that we can evaluate the drop out rate of each method.
This PR fires the `trackCheckoutSubmitAttempt` function when a user clicks the 'Proceed to payment' button tracking the product type and payment method. 
We are also now setting the paymentMethod custom dimension on the `trackCheckoutSubmitAttempt` and `trackPaymentMethodSelected` events as this makes some analyses easier. 
[**Trello Card**](https://trello.com/c/nCpd0NnR/2447-dev-add-tracking-to-digital-pack-checkout)
> Checkout tracking

- support-frontend/assets/components/subscriptionCheckouts/headerWrapper.jsx
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.jsx
The Subs checkouts thank you pages should have a navbar with only the logo, not the lock logo and the word checkout. The checkout stage wasn't getting passed into this component, which meant it wasn't displaying the expected state.
[**Trello Card**](https://trello.com/c/evXvstC2/2493-remove-checkout-and-checkout-styling-from-navbar-in-thank-you-page)
This has now been fixed so all three checkouts (digital, print and GW) have the correct navbar in the thank you page.
> Fix checkouts thankyou page navbar

- support-frontend/assets/helpers/globals.js
This PR is all about turning Home Delivery back on, which has been switched off due to off line fulfilment issues, these issues have been resolved so Home Delivery can now be turned back on
[**Trello Card**](https://trello.com/c/XlcAd6cH/2434-turn-home-delivery-back-on-nb-fulfillment-delays-need-fixing)
* fixed getGlobal so the switches could be obtained from the window object
> fix: fixed getGlobal for the switches

- support-frontend/assets/helpers/tracking/__tests__/googleTagManagerTest.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
A lot of the tracking events we send to GA includes the payment method, however we currently send the values associated with our `PaymentMethod` type. 
This does not match up with the values sent in acquisition events from the acquisition-event-producer library as these are the types defined by Ophan https://github.com/guardian/ophan/blob/master/event-model/src/main/thrift/acquisition.thrift#L25
This makes it hard to do end to end analysis of payment methods so this PR changes the GA support-frontend behaviour to send the Ophan type.
> Send Ophan paymentMethods to GA

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/user/user.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
We have chosen to AB test this: We want to recognize returning single contributors on the landing page and deliver custom content that will hopefully encourage them to contribute now and again in the future.
[**Trello Card**](https://trello.com/c/RO2yF9l3/1279-thank-you-message-on-landing-page-for-single-returning-contributors)
* Introduced a test for copy changes for RSC
* Removed previous landing page copy test, defaulting to new copy
Test variant: 
Test control:
Not in test (same as control):
> Test for updating landing page copy for returning singles

- support-frontend/app/actions/AsyncAuthenticatedBuilder.scala
- support-frontend/app/services/AuthenticationService.scala
- support-frontend/build.sbt
Follow up to #1984. Don't log failure to authenticate with level ERROR if it's because the user isn't signed in.
Also in this PR, I've interpolated the exception in the error message string, rather than including it as a separate argument, since the exception would be sent as a separate log entry to cloud watch. It's seems that interpolating the exception as part of the error message is common practice for this code base anyway.
> log level INFO for failed authentication if user not signed in

- support-frontend/assets/helpers/user/__tests__/userActionsTest.js
- support-frontend/assets/helpers/user/defaultUserActionFunctions.js
- support-frontend/assets/helpers/user/user.js
We want to start tracking our RSC landing page views and conversions.
> Send ophan view event on landing page when cookie present

- support-frontend/assets/helpers/cookie.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
The `gu.contributions.contrib-timestamp` is currently used to prevent users seeing epic/banner for 6 months.
However, the expiry is currently [defaulting to 5 months](https://github.com/guardian/support-frontend/blob/master/support-frontend/assets/helpers/cookie.js#L44).
> Increase cookie expiry

- support-frontend/assets/components/forms/customFields/checkbox.scss
Yesterday it was observed that a checkbox label spanning multiple lines was causing issues with display of the custom checkbox component. 
* Teeny minor style updates to ensure more robust custom checkbox
**Before**
**After**
Multiline
Single line
> Added support for custom checkbox label to span over multiple lines

- support-frontend/app/services/AuthenticationService.scala
- support-frontend/build.sbt
@jfsoul remarked that in a few instances, #1984 had introduced a sign-in loop. This was due to a failure to deserialise a user response from identity API due to an unexpected date time format. The new library versions that's being imported can handle the date time format that was causing the issue. See [#1581](https://github.com/guardian/identity/pull/1581) in identity for more context.
> bump version of identity-auth-play

- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
PayPal payments work differently to the other payment methods because PayPal provides its own button so it's a bit more tricky to track click events.
This PR adds PayPal button click tracking into the Digital Pack page which is the only one that currently has PayPal. If/when we add PayPal to the other products then we will have to add similar tracking to the other checkout forms.
[**Trello Card**](https://trello.com/c/nCpd0NnR/2447-dev-add-tracking-to-digital-pack-checkout)
> Track PayPal subs form submissions

- support-frontend/assets/components/button/_sharedButton.jsx
- support-frontend/assets/components/button/button.scss
- support-frontend/assets/components/forms/customFields/checkbox.jsx
- support-frontend/assets/components/marketingConsent/marketingConsent.jsx
- support-frontend/assets/components/marketingConsent/marketingConsent.scss
- support-frontend/assets/components/marketingConsent/marketingConsentWithCheckbox.jsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/MarketingConsentContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/MarketingConsentControlContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/MarketingConsentVariantContainer.jsx
We have a design for a new marketing component and this needs to be 'QA tested' alongside our current marketing component. We aren't looking for anything scientific in this test, just want to watch the two alongside each other for a couple days to make sure we are getting opt-ins through both. Then we will be able to switch over to the 'newer' component (with checkbox).
Doing this as an A/B test was unexpectedly complicated and involved touching a lot of files that I didn't expect to need to touch. I have added inline documentation to help with removing this as a test when that time comes.
* Created new marketing option as `MarketingComponentWithCheckbox`
* Implemented it across contributions thank you pages as an AB test against the current …
> QA Test for New Marketing Component

- support-frontend/assets/helpers/checkoutForm/onFormSubmit.js
- support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/helpers/tracking/behaviour.js
- support-models/build.sbt
Add a `productCheckout` custom dimension to the GA tracking to allow us to distinguish between different checkouts in analyses.
Related PR here: https://github.com/guardian/acquisition-event-producer/pull/51
[**Trello Card**](https://trello.com/c/nCpd0NnR/2447-dev-add-tracking-to-digital-pack-checkout)
> Add additional tracking for the product checkout

- .prout.json
Increase the 'Overdue on prod' time in Prout
This is neeeded because it's taking about 15 minutes due to the new spot instances having some cache issues.  This isn't going to get fixed imminently so in the mean time it makes sense to increase this a bit.
> Increase the 'Overdue on prod' time

- support-frontend/assets/pages/paper-subscription-checkout/helpers/__tests__/deliveryDays.js
- support-frontend/assets/pages/paper-subscription-checkout/helpers/deliveryDays.js
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/__tests__/deliveryDays.js
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.js
Fixes 2 issues with fulfilment delays for vouchers and Guardian Weekly, namely:
- Sunday was being considered as the first day of the week (day 0) when calculating the additional delay based on cutoff (e.g. extra week if it's after the fulfilment file is generated on a Wednesday for vouchers).
- The condition for the extra delay for vouchers was incorrect, the hour of day should only be considered when it's a Wednesday.
* Change 1
* Change 2
> Fix 2 fulfilment delay issues

- support-frontend/assets/helpers/render.js
Pre-rendering has been silently breaking since [this PR](https://github.com/guardian/support-frontend/pull/1932/files#diff-7c13c67470551a3cc3256ad71218daf5R23)
This is because node does not have `fetch` available.
I've checked that this functionality still works in the browser by confirming the request was sent
> Fix pre-rendering at build time

- support-frontend/assets/components/productOption/productOption.jsx
- support-frontend/assets/components/productOption/productOption.scss
- support-frontend/assets/components/productPage/productPageHero/productPageHero.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/stories/cards.jsx
We are adding a new experiment, which is to test if a change to the copy on the product option cards will improve conversion rates
[**Trello Card**](https://trello.com/c/Tm2rzQ30/2513-updates-to-cards-for-next-ab-test)
* product option button card copy
* product option card size
* added optimize experiments to product option cards
> feat: optimize test for product cards

- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/util/Browser.scala
This test periodically fails. I can't be certain, but I think it might be because there is always more than one stripe checkout element. So when it checks if the element is visible, it needs to be check each one.
I also want to find out why there's more than one of these elements...
> Post-deploy test: check all instances of Stripe element

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
The terms and conditions link was wrong on the Guardian Weekly product page
[**Trello Card**](https://trello.com/c/IrpvbRbb/2516-change-gw-tcs-link)
> Update Guardian Weekly T&Cs link

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/abTestContributionsLandingChoiceArchitecture.scss
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We want to test the performance of adding labels to the contributions form. We will measure the performance of this test by looking at 
[**Trello Card**](https://trello.com/c/oNMxdCjp/1242-choice-architecture-r1-add-field-labels)
* Added the test (basically was able to complete using SCSS only)
* Updated the legend on the form - applicable for both variants in this test. This change should improve accessibility even when the legend is not visible.
Control: 
Variant:
> Choice architecture test round 1 (labels test)

- support-frontend/assets/helpers/render.js
- support-frontend/assets/helpers/subscriptionsForms/__tests__/subscriptionCheckoutReducerTest.js
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/helpers/tracking/behaviour.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.js
In order to get an accurate conversion rate for our checkouts we need a client side success event otherwise the conversion rates will appear better than they are because of consent settings and ad blockers.
This PR also removes the client side ecommerce tracking code as this is now managed server side.
[**Trello Card**](https://trello.com/c/cpyidHc0/2521-add-a-client-side-conversion-metric)
> Thank you page tracking

- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
We need to update the language on the page -- in particular, the labels for contribution types -- in accordance with which test participation a user is in. This change makes it so those who see a form that is labelled with questions have answers that make semantic sense.
Control:
Variant:
> Update contribution type labels for choice architecture abtest round 1 (labels test)

- support-frontend/assets/components/productOption/productOption.scss
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss
This PR fixes the break in the sales copy on the option-card shown in the screenshots
* remove break in sales-copy
> feat: remove break in sales-copy

- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We'd like to be able to see if our contributors give again within a 12 month period as part of our new asking strategy
[**Trello Card**](https://trello.com/c/tgid0Gqh/1337-extend-contribution-cookie-to-1-year)
> Increase cookie TTL (again)

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/contributions-landing/abTestContributionsLandingChoiceArchitecture.scss
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
The previous version of this test introduced labels above the contribution type and amounts selectors. This has had a negative impact.
This change removes the labels and adjusts the margins.
[**Trello Card**](https://trello.com/c/WYtS686A/1346-implement-choice-architecture-round-1b)
control:
variant:
> Landing page choice architecture R1b

- support-workers/src/it/resources/logback-test.xml
- support-workers/src/main/scala/com/gu/FutureLogging.scala
- support-workers/src/main/scala/com/gu/support/workers/GetSubscriptionWithCurrentRequestId.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraService.scala
- support-workers/src/test/resources/logback.xml
- support-workers/src/test/scala/com/gu/support/workers/EndToEndSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraSpec.scala
I tried to run the `it:test` in support workers and I was getting 8 failures within these classes
```
[error] 	com.gu.zuora.ZuoraSpec
[error] 	com.gu.support.workers.integration.PreparePaymentMethodForReuseSpec
[error] 	com.gu.support.workers.integration.CreateZuoraSubscriptionSpec
[error] 	com.gu.support.workers.EndToEndSpec
```
I managed to fix some with changes in zuora UAT and DEV, but some I needed to edit the code as well.  Judging by the history I think they have been broke for a good few months, but I don't know if we can automate them easily.
EndToEnd was the hardest one, and it was caused by a change I made nearly a year ago.  It checked first for existing contributions against a hard coded identity id by querying them one by one, then it creates a new contribution against the …
> fix support-workers it tests and make more logging

- support-frontend/assets/components/subscriptionBundles/weekly.jsx
- support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
- support-frontend/conf/strings.conf
Apparently delivery of the Guardian Weekly is not free, instead it is factored into the price, so we need to remove this erroneous claim. Marketing also snuck in some other copy changes on the GW product page.
[**Trello Card**](https://trello.com/c/mz1Uw6d4/2511-update-copy-on-gw-product-page)
* Guardian weekly product page: updated copy for reasons to buy, remove free delivery and instead say delivery cost included.
* Subs landing page: removal of two mentions of free delivery and an additional one from the metadata.
> Remove mentions of free delivery

- support-frontend-static/cfn.yaml
- support-frontend/conf/riff-raff.yaml
This follows on from https://github.com/guardian/support-frontend/pull/2016
I just noticed a few tidyup things that need doing.
- we don't need directory listings enabled
- we aren't actually useing the S3 website functionality, we're just using the standard public HTTP interface
- riffraff does a warning if you specify something to be the default value
I have recloudformed the bucket and it seems to be creating the right bucket, I will deploy to CODE and check the warning has gone and it seems to work still
> tidy up for s3 bucket for assets

- support-frontend/assets/components/forms/customFields/radioInput.scss
The flow of the offer text in the DP checkout was janky, as detailed in the [**Trello Card**](https://trello.com/c/rFrvkNJy/2462-dp-checkout-fix-post-offer-copy)
* Text in [Memsub](https://memsub-promotions.gutools.co.uk/#/promotion/d809d7ca-ba4f-4e3f-9fbf-a313c503be07) has been updated from 'Enjoy your digital pack free for 14 days' to 'Enjoy your digital pack free for 14 days, then' 
* Remove bold from offer text so the text looks cohesive on the page
* Small css tweak for desktop view
> Fix post offer copy

- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
This adds missing marketing copy updates in the following [**Trello Card**](https://trello.com/c/mz1Uw6d4/2511-update-copy-on-gw-product-page)
* Page hero text
* Page headline
* First paragraph title
* First paragraph copy
> Update marketing copy on GW product page

- build.sbt
- support-services/src/main/scala/com/gu/helpers/WebServiceHelper.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/MockWebServerCreator.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala
A while ago I was investigatng a step function that timed out after 24 hours.  It turned out there was a 4xx error occurring in one of the backends, i.e. client error.  I think something was missing (I forget the exact details).
It should have aborted straight away, but the step functions were turning any error when doing an http request as a Helper error, which was turning into a RetryUnlimited (i.e. 24 hours).
This PR separates out client errors (4xx) from general explosions, so that 4xx are always aborted and any other failure is retried.
Tested locally via it testing and remotely in CODE (GW 6 for 6 and contribution)
> handle 4xx errors specifically in calls from service workers

- support-frontend/assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap
- support-frontend/assets/helpers/page/__tests__/pageTest.js
- support-frontend/assets/helpers/page/commonActions.js
- support-frontend/assets/helpers/page/commonReducer.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
This issue is explained in this [**Trello Card**](https://trello.com/c/p8mDfVJT/2542-bug-editing-delivery-address-changes-currency).
In the Guardian Weekly checkout, a user who enters
- a billing country with one currency, and 
- a delivery country with another
Should see a price that is:
- calculated for the cost of delivery to the delivery country, and
- in the currency of the billing country
The customer should be able to use the payment options of the billing country (eg if the billing country is UK, they can use direct debit or a credit/debit card).
There was a problem occurring where a user who entered a billing address that was in the UK and then entered a delivery address that was in Australia, and would experience a payment failure when paying by credit card.
The cause of the …
> Fix currency passed to payment method

- support-frontend/assets/components/forms/customFields/error.scss
- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.js
- support-frontend/assets/components/subscriptionCheckouts/subscriptionSubmitButton.scss
- support-frontend/assets/components/subscriptionCheckouts/subscriptionSubmitButtons.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx
To improve clarity for checkout users, who may wonder why nothing happens when they click the 'Continue to payment' button. More information in this [**Trello Card**](https://trello.com/c/NyB2MIQ0/2498-error-summary-for-checkout-errors)
Instead of the button flashing orange and the page otherwise staying the same, now a summary of the invalid fields appears:
There is [a design for this in Zeplin](https://app.zeplin.io/project/5c3c9a2881e8042985ba9cbe/screen/5d5c097d4d1a189b7e86e8b8).
> Add an error summary to digital pack checkout

- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/assets/stylesheets/gu-sass/helpers.scss
Keyboard only and screen reader users we're unable to:
- Select/change the custom styled radio buttons
- Read the form group legends (Screen reader) 
Semi related to this but not really: [**Trello Card**](https://trello.com/c/XcLbdC4p/1295-implement-the-choice-architecture-r2-flip-order#comment-5d5d520b6184f08ae92a33ef)
* Update custom radio buttons to `position: absolute, opacity: 0` 
* Added accessibility hint to form legend to ensure they remain visible hidden yet accessible by assistive technology
* I also updated the accessibility hint css to reflect a more modern approach which doesn't involve positioning DOM objects (REALLY) far outside the viewport.
> Radio button and form legend accessibility updates

- project/LibraryVersions.scala
- support-frontend/build.sbt
- support-workers/build.sbt
https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450917
Extra security patches mean that jackson-databind versioning is out of sync with other jackson libraries
> Bump jackson version

- support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
Because the paper product page will now offer Home Delivery, the checkout copy has been updated to reflect Home Delivery status 
* update: added switch between voucher and delivery copy
Switch between home delivery and vouchers
> Make print checkout copy dynamic to account for home delivery

- support-frontend/assets/pages/showcase/components/ctaContribute.jsx
Small copy change on the showcase page
[**Trello Card**](https://trello.com/c/g78eAUPC/1371-update-the-contribution-text-on-the-why-support-page-to-put-the-right-currency-instead-of-everywhere)
Before:
After:
> Update contributions copy on showcase page

- project/plugins.sbt
- support-frontend/build.sbt
The latest Play 2.6.*
The current version triggers a snyk error relating to an older version of akka:
https://app.snyk.io/vuln/SNYK-JAVA-COMTYPESAFEAKKA-451679
The latest `identity-auth-play` also brings in the newer version of play
> Bump Play to 2.6.23

- support-frontend/assets/helpers/page/page.js
The build-time rendering is currently broken (since https://github.com/guardian/support-frontend/pull/2025 was merged). This is because the `overrideAmountsForParticipations` function is being passed an `AmountsRegions` with `undefined` value.
This PR just avoids calling the function if it's undefined.
Follow-up tasks:
1. Make the build fail if build-time rendering fails! Currently it's very easy to miss.
2. I noticed that several pages on the site receive settings that are only required for the contributions landing page (e.g. amounts settings). Only the contributions controller should pass these settings into the `main.scala.html` template.
3. Consider whether we can avoid calling `init` in `page.js` for build-time rendering, as this is where it's trying to setup this state. For the …
> Fix amounts override logic

- support-frontend/build.sbt
A recent Play update has caused warnings in the logs because now the akka-agent dependency is behind:
`Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using`
Also, akka-agent is deprecated but can be replaced by https://github.com/guardian/box, but I'm not doing this now
> Bump akka-agent version

- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
We want to match the style guide and CTA contribute button so we are changing the hover state from a murky yellow to 'highlight-dark' (or if you prefer, orange-yellow or *Golden Tainoi* )
[**Trello Card**](https://trello.com/c/WIOeY16Q/1317-correct-hover-states-on-the-landing-page)
> Updated hover states on contribution form buttons

- support-frontend/build-tc
Currently if we break build-time rendering then it logs the error but the build goes ahead regardless. This means we don't actually notice.
Now, if the `yarn run build-ssr` command fails then the entire script fails:
Separate PR [here](https://github.com/guardian/support-frontend/pull/2050) to actually fix `build-ssr`
> Fail build if any of the build script commands fails

- support-frontend/assets/helpers/deliveryCheck.js
There are some missing postcodes on the current home delivery M25_POSTCODE_PREFIXES list. This PR adds the missing postcodes
[**Trello Card**](https://trello.com/c/cXb40KLN/2583-update-postcodes-in-postcode-checker)
* Updated the postcodes
N/A
> fix: added missing postcodes

- support-frontend/app/monitoring/Tip.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-workers/src/main/scala/com/gu/stripe/StripeService.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/AddressLineTransformerTest.scala
- support-workers/src/test/scala/com/gu/support/workers/EndToEndSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
We want to support the new SCA so that we can still take payments from customers after 14th Sep.
Stripe has a set of great instructions to show to be SCA ready here: https://stripe.com/docs/payments/cards/saving-cards
This PR implements step 5.
At the moment we just take a card token from stripe, and push it into the create customer step in order to be able to charge them multiple times.
The new world requires us to use a payment_method instead of a card token (source).
This change keeps the old functionality so that we don't break existing code, but also means that when someone submits the field from the client side with a paymentMethod instead, it will try to use the SCA method instead.
A small concern is how Zuora will deal with things, as we will have a payment method id and a …
> SCA: support stripe PaymentMethod field

- support-frontend/app/controllers/Application.scala
- support-frontend/conf/routes
We recently added regional versions of the "Why Support" page at `/au/support` and `/uk/support`, but we hadn't yet changed the redirection from defaulting to `/uk/support`.  This does that so that when you navigate using the nav from Aus/US you should end up on the region-specific page.
[**Trello Card**](https://trello.com/c/DEsu2DM8/2586-why-support-redirect-support-always-goes-to-uk-version)
> Redirect /support to regional versions

- support-frontend/cloud-formation/cfn.yaml
We planned to serve the assets from an S3 bucket so that there couldn't be a mistmatch between the deployed instances on separate requests as this would cause a blank or unstyled page.
Originally we planned to have an S3 bucket per env and upload to that, but riffraff doesn't support a per env bucket when it uploads the files as part of the deploy.
In the end we went for a single bucket in a separate cfn, so this original background work is no longer needed.
previous PR with explanation: https://github.com/guardian/support-frontend/pull/2016
> remove static asset S3 buckets from support frontend

- support-frontend/assets/components/headers/header/header.scss
- support-frontend/assets/components/headers/links/links.jsx
- support-frontend/assets/components/headers/mobileMenu/mobileMenu.scss
- support-frontend/assets/helpers/deliveryCheck.js
As part of the traffic drivers for subscriptions, the mobile header cta now links to subscriptions, this means that getting to contributions (where the previous mobile header cta linked to) will need to be accessed from subscriptions. This PR puts a link to contributions in the mobile menu
[**Trello Card**](https://trello.com/c/aXNyBKDt/2587-add-contributions-to-the-mobile-nav-on-support-frontend)
* feat: add contributions to the mobile menu
> feat: add contributions to the mobile menu

- support-frontend/assets/helpers/abTests/abtest.js
Sometimes it's useful to try out a new test in PROD without opting users into the test.
It means we can integration test with e.g. our Stripe production account before putting it live to users.
Previously `urlParticipations` was only being used to set a local storage value, so if the ab test was switch off then it had no effect.
This change means that even if an ab test is switched off, if you set `#ab-<test-name>=<variant-name>` in the url than you'll be in the ab test.
> Support viewing of an A/B test using the url, even if the test is off

- support-config/src/main/resources/touchpoint.PROD.conf
- support-config/src/main/resources/touchpoint.SANDBOX.conf
- support-config/src/main/resources/touchpoint.UAT.conf
- support-config/src/main/scala/com/gu/support/config/StripeConfig.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js
- support-frontend/assets/helpers/paymentIntegrations/stripeCheckout.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/test/controllers/SubscriptionsTest.scala
Reverts guardian/support-frontend#2064, re-enabling, now that support-workers configs have been properly set:
Modifications to enable a third US-based Stripe account. Main changes are that the public key is chosen based on the page's country not the transacting currency. Also that the public key needs to be transmitted along with the payment and analytics information over to the Payment API so that it can be completely sure which account the token is generated from, and doesn't duplicate the based-on-country algorithm.
Use of the new key is controlled by a new 'Payment Method' feature switch which I need to add to the [admin console](https://github.com/guardian/support-admin-console).
To enable Discover and Diners Club cards to be used by USA customers. Also to move less money around in …
> Modifications to enable a third US-based Stripe account

- support-frontend/app/views/main.scala.html
Small patch to allow React bundle to be loaded in asynchronously, which means it does not block the DOM from continuing to load while the script is being evaluated
> Tf stripe elements jtl mod

- support-frontend/app/controllers/CreateSubscription.scala
- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-frontend/assets/components/forms/textArea.jsx
- support-frontend/assets/components/forms/textArea.scss
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/User.scala
- support-models/src/main/scala/com/gu/support/zuora/api/ContactDetails.scala
- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
People purchasing a paper for home delivery should be able to provide delivery instructions to help the delivery company make the delivery successfully.
[**Trello Card**](https://trello.com/c/haACqe66/2590-add-delivery-instructions-to-hd)
* Add a `TextArea` component
* Add a delivery instructions field into the HD form
* Pass these instructions through the stack and into Zuora in the 'Sold to' contact
* I've also renamed the two `checkoutForm.jsx` files used by the DP and Paper checkouts to `digitalCheckoutForm.jsx` and `paperCheckoutForm.jsx` to match the `weeklyCheckoutForm.jsx` used in the weekly checkout
> Add a delivery instructions field to paper home delivery

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
We are implementing a new survey to be seen by the US audience only. 
[**Trello Card**](https://trello.com/c/Blum7pOP/1393-survey-on-preferred-payment-methods-in-the-us)
* Implement the survey with geo-restriction
* Bump survey component above marketing component
US thank you page:
Everywhere else thank you page:
> survey implemented

- support-frontend/assets/helpers/errorReasons.js
This is used by the new SCA-compliant contributions flow. If the user's bank authorisation fails then this message is displayed
> Update 3DS authorisation error message

- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
The SCA/stripe elements change is being run as an a/b test.
But we also want the ability to enable/disable quickly from the support-admin-console
> Put Stripe Elements test behind feature switch

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
A minor style change, to make the placeholder text colour match that of the other fields in the page
> Fix stripe elements placeholder font colour

- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
We are currently running an A/B test where one variant uses Stripe Checkout, the other Stripe Elements.
This post-deployment test fails if the user is in the Stripe Elements variant.
We need a new post-deploy test, but for now I'm just removing it so we can continue running the test
> Remove Stripe Checkout popup test

- support-frontend/conf/DEV.public.conf
- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
We're currently running an A/B test on the one-off contributions page, with Stripe Elements.
This breaks these post-deploy tests.
This is a temporary fix to force the browser into the control variant (with stripe checkout). I've also reinstated the "Check Stripe pop-up appears" test.
TODO - rewrite tests for stripe elements
> Fix one-off contributions deployment tests

- support-config/src/main/resources/touchpoint.PROD.conf
Enabling use of a US Stripe account on the Single Contributions checkout in PROD. Feature is currently behind a feature switch, and will be off till we've done some e2e testing with Finance team.
[**Trello Card**](https://trello.com/c/dUczXjoJ)
> We now have a PROD Stripe public key!

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
To be consistent with other fields in the form
Selected, no error:
Not selected, error:
Selected, error:
> Show red border for errors in stripe elements inputs

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
Disabling the SCA test in order to show Stripe Support the problem with the fonts downloading once for every element
> SCA font fix -- to be reverted

- .travis.yml
- build.sbt
- project/build.properties
two new updates are out
Sbt 1.3 https://github.com/sbt/sbt/releases/tag/v1.3.0
scala 2.12.10 https://github.com/scala/scala/releases/tag/v2.12.10
SBT has a new turbo mode that keeps the libraryDependencies warm in a classloader so that if you keep running `test` or `run` in the same sbt session it will start much quicker and the usual JIT benefits over time.  It is experiemental though, and seems to cause the support-workers build to hang, so I have removed it again.  It does make things a lot quicker if you keep running `test` locally.
[**Trello Card**](https://trello.com/c/dMbnejd3/2596-try-sbt-130-poss-big-compile-test-performance-improvement)
> use sbt 1.3 and scala 2.12.10

- support-models/src/main/scala/com/gu/support/zuora/api/PaymentGateway.scala
Now people have stripe paymentintents card details in zuora, after @twrichards updates last week
However it is possible for people to reuse card details, which means that the step functions must pick up the correct gateway together with the card details when fetching the existing account.
Some of this work is already done, to pass through the gatway correctly rather than just assuming the standard stripe gateway (otherwise it would have written incorrect data silently!), however the actual work to add the new gatway names was not present.  This means that when it tried to read the account from zuora, the gatway name was not understood and the lambda threw an error.
This change adds the new payment gateway names so that the step functions can proxy the gateway through for reuse.
> add new paymentintents gateway to allow reuse

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
The payments survey has finished gotten enough responses and needs to be taken down.
[**Trello Card**](https://trello.com/c/uTrL1wXK/1441-turn-off-the-payment-survey)
> Take down US survey

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
We are running a final choice architecture test, informed by earlier tests run this quarter, to see what impact we can have by running larger sets of amounts that remain static across products.
* Introduce the amounts
* Come up with a universal style solution with flexbox
Control, desktop
Set one, desktop
Set two, desktop
Set three, desktop
Control, mobile
Set one, mobile
Set two, mobile
Set three, mobile
> Choice architecture round three (product first, static amounts, more options)

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/assets/helpers/flashSale.js
In order for the upcoming Digital Pack sale to work correctly we need to ensure that the landing page is using the correct promo code to fetch prices and also that it passes that promo code on to the checkout page.
[**Trello Card**](https://trello.com/c/1Acz8BH2/2628-set-up-digital-pack-pages-to-use-the-correct-promo-codes-for-the-september-sale)
> Add promo code for the Sept 2019 DP sale

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/main.scala.html
We'd like to make our shared content more compelling by using an image. In order to make that happen, we had to slightly refactor the twirl templates as there is a maximum number of parameters that be used in a given template (22).
[**Trello Card**](https://trello.com/c/nSR1mo9D/1477-implement-general-social-share-image)
[**Related Trello Card**](https://trello.com/c/qTfXo0B1/1424-moment-social-sharing)
* implemented the open graph tags
* refactored the twirl template to accept a new parameter
**screenshots to come - this needs to go live first so we can tell facebook and twitter to purge their current information about the site and use this new header to construct their cards**
> Implement open graph image for share links

- support-frontend/assets/components/productOption/productOption.jsx
- support-frontend/assets/components/productOption/productOption.scss
- support-frontend/assets/components/productPage/productPageHero/productPageHero.scss
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/__tests__/paymentSelectionTests.js
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss
- support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.scss
- support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
This PR updates the pricing card style, adds a roundel and makes the pricing cards aware of applied promotions.
[**Trello Card**](https://trello.com/c/ZnyA5qp2/2601-brand-campaign-update-the-current-dp-page-checkout-with-new-pricing-option-for-23rd-sep)
* Add roundel
* Update pricing card style
**Cards - Before**
**Cards - After**
**No roundel**
**Now with roundel**
> Restructure product cards

- support-frontend/assets/components/customerService/customerService.jsx
- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
The Digital Pack Landing page needs to show a link to the terms and conditions of the current promotion when there is one running.
[**Trello Card**](https://trello.com/c/GINUZJaK/2626-add-promotion-terms-copy-to-dp-and-print-landing-pages)
**Page footer with no active promotion:**
**Page footer during the sale period:**
> DP promotion T&Cs link

- support-frontend/assets/components/threeSubscriptions/threeSubscriptions.scss
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.js
These are some small changes requested by Elena and Chris.
* Change to text of main marketing message so text reads: 'Save up to 52% for a year on The Guardian and The Observer'
* Fix indentation of highlighted message on subs landing page
Following screenshot shows the problem:
> Small fixes for the print campaign

- support-frontend/assets/components/checkoutForm/checkoutForm.scss
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
Up until now the error message component which is used when a payment failure occurs was inside the `PaymentMethodSelector` component. This was a problem when there is only one available payment method as it means that the error message is not visible.
This PR moves the error message out of `PaymentMethodSelector` and directly into the form.
[**Trello Card**](https://trello.com/c/BHpPtXww/2639-investigate-gw-australia-failures)
> Move payment failure error message out of PaymentMethodSelector.jsx

- project/plugins.sbt
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/test/scala/com/gu/support/workers/PaymentMethodIdTest.scala
- support-workers/src/main/scala/com/gu/stripe/Stripe.scala
- support-workers/src/main/scala/com/gu/stripe/StripeBrand.scala
- support-workers/src/main/scala/com/gu/stripe/StripeService.scala
- support-workers/src/main/scala/com/gu/stripe/createCustomerFromPaymentMethod.scala
- support-workers/src/main/scala/com/gu/stripe/createCustomerFromToken.scala
- support-workers/src/main/scala/com/gu/stripe/getPaymentMethod.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
This PR is part of a series to make our stuff SCA compatible using setupintents/paymentintents. Previous PR https://github.com/guardian/support-frontend/pull/2063
This means we can still take payments after banks start using SCA.  This is split up into smaller tasks.  This one follows on from the one that creates a customer from a payment method id.
Previously we created the customer from the token, which returned the card token/id and the card details e.g. brand, last 4, etc.  We then write those to Zuora.
With creating a customer from a payment method id, we write that id to zuora instead, but we need to call get payment method separately to get the card details.
[**Trello Card**](https://trello.com/c/3EXrocav/2589-make-support-workers-write-to-zuora-in-sca-mode)
This is tested in CODE …
> support workers read details from stripe in SCA mode if requested

- project/build.properties
After https://github.com/guardian/support-frontend/pull/2082 there is a new version out: https://github.com/sbt/sbt/releases
I know some people had memory issues, and issues getting out of ./devrun.sh script, but I don't think either of those issues will be fixed by this.
However it's a good idea to keep up to date, as it's not much effort, and being on an old version has risks.
> use latest sbt version

- support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx
We only want to show the Digital Pack in the hero position for the UK, people in US, CA, AU, NZ & ROW should still see Guardian Weekly as the hero.
[**Trello Card**](https://trello.com/c/t0AJxCgF/2644-showcase-hero-product)
> Subs showcase page hero product

- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-models/src/main/scala/com/gu/support/workers/states/CreatePaymentMethodState.scala
We have had a few more checkout failures for GW, where people are getting a ROW stripe token and submitting with AUD currency.
We don't really understand why this happens, but pushing the whole redux state to the server might help us to correlate together the steps to reproduce.
This PR just gathers all the action history and pushes it on one big string.  Then we can look at it later and try to reproduce.
We did try putting it into the support workers state, but the encryption only handles 4096KB so we could end up with failures due to the debugging, which would be ironically bad.
this is the post request from client to server
this is the support-frontend log
```
2019-10-01 17:17:15,567 [application-akka.actor.default-dispatcher-3] INFO  com.gu.monitoring.SafeLogger$ - …
```
> send redux event history to support-frontend and log it

- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
It was decided that it would be better to make the single payment 'contribute' button always-enabled for consistency with the other tabs.
[**Trello Card**](https://trello.com/c/f3mIxwTq)
> Re-enable contribute button for single payment flow

- support-frontend/assets/components/packshots/feature-packshot.jsx
- support-frontend/assets/components/packshots/full-guardian-weekly-packshot.jsx
- support-frontend/assets/components/packshots/guardian-weekly-packshot.jsx
- support-frontend/assets/components/packshots/int-feature-packshot.jsx
- support-frontend/assets/components/packshots/paper-and-digital-packshot.jsx
- support-frontend/assets/components/packshots/paper-packshot.jsx
- support-frontend/assets/components/packshots/premium-app-packshot.jsx
- support-frontend/assets/components/subscriptionsProductDescription/subscriptionsProductDescription.jsx
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/helpers/subscriptions.js
- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/subscriptions-landing/components/featureHeader.jsx
- support-frontend/assets/pages/subscriptions-landing/components/subscriptionsLandingContent.jsx
- support-frontend/assets/pages/subscriptions-landing/components/subscriptionsProduct.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
Reverts guardian/support-frontend#2108
Reapplies https://github.com/guardian/support-frontend/pull/2092
This relaunches the new subscription showcase page with pricing that takes account of flash sales.
> Revert "Revert "New subs showcase page 2""

- support-frontend/assets/pages/subscriptions-landing/components/subscriptionsLandingContent.jsx
- support-frontend/test/selenium/subscriptions/pages/SubsLandingPage.scala
#2109 broke the post deployment test for the subscriptions showcase page because it removed an element from the page which Selenium was looking for to check that the page has loaded correctly. This PR changes the css selector to an element which does exist.
> Change the selenium css selector used by the subscriptions landing page

- support-frontend/assets/helpers/flashSale.js
The Digital Pack flash sale copy data in flashSale.js did not include the correct prices for non-UK countries meaning that the price shown on the subscriptions landing page was wrong (it was the UK price). Prices were correct on the DP landing page and in the checkout and all customers would have been charged the correct price.
[**Trello Card**](https://trello.com/c/V4BOSGgD/2661-incorrect-digital-pack-international-pricing-for-subs-showcase-page)
> Add the correct non-uk prices for DP flash sale

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
When we replaced the old Stripe popup with the new Stripe elements form we couldn't get the post deploy test to pass so we commented out. This PR uncomments the test and fixes it. 
[**Trello Card**](https://trello.com/c/i5euSGE1/2630-reintroduce-post-deploy-test-for-stripe-checkout)
> Fix and re-add the Stripe post deployment test

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js
- support-frontend/assets/helpers/stripe.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
In the past we have used Stripe Checkout for contributions.
We have been running an A/B test to compare Stripe Checkout vs Stripe Elements + Payment Intents API.
This is for SCA compliance. Currently it is for single contributions only.
From the test we have found that the change does not impact revenue, and so are switching to 100% Stripe Elements + Payment Intents API.
This PR removes Stripe Checkout for single contributions. Recurring will be migrated later (it requires some separate backend work)
> Remove Stripe Checkout for single contributions

- build.sbt
- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/assets/components/subscriptionCheckouts/personalDetailsGift.jsx
- support-frontend/assets/helpers/formValidation.js
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/rules.js
- support-frontend/assets/helpers/subscriptionsForms/validation.js
- support-models/src/test/scala/com/gu/support/SerialisationTestHelpers.scala
- support-models/src/test/scala/com/gu/support/encoding/PaymentMethodEncoderSpec.scala
Fixing a SalesForce bug where step functions are failing as part of the weekly checkout flow because we do not validate gift recipient email addresses. This causes an infinite loop on the step function which ends up re-submitting the checkout request every time it fails. We now validate against malformed emails at submission time, while still allowing for gift recipients where no email address is specified.
[**Trello Card**](https://trello.com/c/ONmjZVen/2565-clientside-validate-checkout-fields-to-avoid-salesforce-errors)
* Added a function to validate optional email addresses
* Added a reducer and a validation rule against the gift recipient email address on the weekly checkout flow.
* Fix Scala warning against using deprecated implicit collection conversions, favouring new API based on …
> 2565 gift email and postcode validation

- build.sbt
- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.js
- support-frontend/assets/components/subscriptionCheckouts/personalDetailsGift.jsx
- support-frontend/assets/helpers/formValidation.js
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/rules.js
- support-frontend/assets/helpers/subscriptionsForms/validation.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-models/src/test/scala/com/gu/support/SerialisationTestHelpers.scala
- support-models/src/test/scala/com/gu/support/encoding/PaymentMethodEncoderSpec.scala
Support workers experience issues submitting subscriptions to Salesforce where the postcode length is over 20 characters. This is also likely to be accidental user input, and we need to protect against it with a character limit in the postcode field.
[**Trello Card**](https://trello.com/c/ONmjZVen/2565-clientside-validate-checkout-fields-to-avoid-salesforce-errors)
* Added postcode maximum length rule for billing and delivery postcode.
> Postcode length restriction on delivery and billing

- support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
[This PR](https://github.com/guardian/support-frontend/pull/2114) removed support for Stripe Checkout for single contributions.
However, it also broke the Payment Request button because it uses shared code from the Stripe Checkout flow. This PR adds some of this logic back in.
I've tested Payment Request button and normal Stripe payments locally + in CODE.
TODO - we badly need tests/post-deploy testing/alarms for Payment Requests. Currently we have no visibility when things go wrong
> Fix payment request button

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/helpers/legal.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/assets/pages/contributions-landing/contributionsLandingClimateMoment.scss
The moment has been officially named: 'Climate Pledge 2019' so I'm getting rid of all old references to the 'environment pledge'.
There have also been some changes to the Terms and Conditions that I'm including in this PR for the reason that these all fit into the same category of 'fit and finish' changes and aren't features that need their own PR
[**Trello Card**](https://trello.com/c/PledEggW/1504-moment-philo-patrons-asks)
* Update url name and codebase name to refer to the 'climate moment'
* Add some logic to make the terms and conditions dynamic, update copy and links
UK:
ROW:
> update moment naming in code base and url, update terms and conditions copy

- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/campaigns.jsx
We have a requirement to display the campaign landing page for all users for the duration of the campaign. This is different to previous campaigns, where we've had it behind a special url.
This PR is a proposal for enabling this from a switch, which will be in the admin console.
This means we can easily turn it on/off.
I think this is simpler than using redirects
> Switch to enable campaign for all contributions landing page views

- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
To show the 6 for 6 offer on the subscribe page and also to change the name for Guardian Weekly to 'The Guardian Weekly'
[**Trello Card**](https://trello.com/c/XVjlH3iL/2638-add-introductory-offer-to-weekly-on-subs-showcase-page)
> Highlight the 6 for 6 offer on the subscriptions landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/helpers/page/page.js
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
To test using the native AB test framework to allocate users to variants in Optimize tests.
**What I've done:**
- Created a test in Optimize
- Added it into the native ab test list in `abTestDefinitions.js` so the user will get automatically allocated to a variant by the framework
- Added some code to the digi pack landing page to fire a GA event with the `experimentId` and `experimentVariant` datalayer variables set so that the user is assigned to the correct cohort in GA/Optimize
There is quite a bit of scope to improve on this implementation but I want to test that it works before refining the approach any further
[**Trello Card**](https://trello.com/c/PsimymUQ/2674-optmize-rework)
> Add Optimize test into native AB test participations

- support-frontend/assets/helpers/externalLinks.js
The link to the promotion terms and conditions page on subscribe was wrong, this fixes it.
> Correct the link to the promotion terms and conditions page

- build.sbt
- support-frontend/build.sbt
[**Trello Card**](https://trello.com/c/SUwE8N6a/2665-intelij-add-sbt-plugin-to-mark-assets-as-sources-root-automatically)
* Added another SBT sources directory not directly managed by SBT under the sub-project `build.sbt` definition.
* Add a name and module name for the root project so it's easier to know what's what in InteliJ.
> Ide settings

- support-frontend/assets/helpers/abTests/abtest.js
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
This PR adds two new capabilities to the AB test framework
It is now possible to set an optional `targetPage` field on AB tests which specifies which page they should load on. This is to stop users who never visit a particular page from being included in the cohort for tests running on that page. This field should contain a regex containing a path which will be matched against the current page path when evaluating whether to run the test, eg. `'/(uk|us|eu|au|ca|nz|int)/subscribe/digital$'`. 
It is now possible to add an `optimizeId` field to AB tests which allows the linking of a test set up through the native test framework to an experiment running in Optimize. When a test with an optimizeId is initialised we send a GA event to set the appropriate experiment and variant data for the …
> AB test improvements

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/main.scala.html
- support-frontend/assets/components/socialShare/socialShare.jsx
- support-frontend/assets/components/spreadTheWord/spreadTheWord.jsx
The Moment requires a new og:image and social share copy.
[**Trello Card**](https://trello.com/c/qTfXo0B1)
* Change og:image link to new climate crisis design
* Change copy on Thank you page
* Change copy in:
- Twitter
- Email
* LinkedIn does not use the copy - it uses the landing page description - so I removed the copy from the link to avoid confusion
* Facebook does not use copy - uses og:image
Join me in supporting The Guardian’s pledge to be a truthful voice on the climate crisis
> Update social sharing links and copy

- support-frontend/assets/components/packshots/paper-and-digital-packshot.jsx
- support-frontend/assets/components/packshots/subscription-daily-packshot.jsx
- support-frontend/assets/components/subscriptionBundles/digitalPack.jsx
- support-frontend/assets/components/subscriptionBundles/paperDigital.jsx
- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouExisting.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
- support-frontend/assets/pages/digital-subscription-landing/componentsB/promotionPopUp.jsx
- support-frontend/assets/pages/showcase/components/ctaSubscribe.jsx
- support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
Due to the launch of a new version of "iPad daily editions" which has been renamed as "The Guardian Daily" 
This PR makes changes to all product names and copy which currently has the name "Digital Pack" and changes it to "Digital Subscription" and change "iPad Daily editions"
Also the packshot images have been changed to new packshots that show "The Guardian Daily" images
[**Trello Card**](https://trello.com/c/13SO4QUn/2652-update-product-names-copy-and-packshots-for-16-10-ok-for-14th-oct)
* Name and copy changes
* Image changes
N/A
> Ds daily editions product name, copy and packshot updates

- support-config/src/main/scala/com/gu/support/config/StripeConfig.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
- support-frontend/package.json
- support-frontend/yarn.lock
Enable the Payment Request button work for recurring contributions checkout page, and also confirm the payment frequency in its title.
The payment method in Zuora looks identical to if the card was tokenised via Stripe Checkout so there should be no downstream issue for the customer, other than when the button does eventually be used for Apple Pay, that won't be available in the manage-my-account portal.
I have made 3 trade-off decisions as part of this change:
1) I have added the requirement that we request the contributor's name via the Payment Request button. This means if they don't have a name set up in their system then the button won't show. I'm 99% sure this should have a negligible impact on the Apple Pay button showing up when single contribution is the default.
2) As browsers …
> Make the Payment Request button work for recurring contributions

- support-frontend/assets/components/content/content.scss
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/components/productBlock.jsx
To fix some wonky alignment in the relaunched digital subs page.
[**Trello Card**](https://trello.com/c/gE2y7vNm/2686-design-tweaks-to-new-product-page)
* Update left padding in the terms section at wider breakpoints
* Update left padding in faqs
* Add aria-hidden attribute to dropdown panels
> Design tweaks for digital subs landing page

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
These are small changes to address issues found in browserstack testing for the relaunched digital subscriptions landing page.
[**Trello Card**](https://trello.com/c/cUBIYyVf/2688-dp-page-test-plan)
Removed the 100% - 10px calculation for the call to action section of the page.
> Digital subs landing page browserstack testing

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/conf/strings.conf
To update the sharing tags for the relaunch of the Daily and premium app.
[**Trello Card**](https://trello.com/c/qptba6gj/2690-update-digital-subs-sharing-tags)
* Update page title
* Update page description
> Update sharing tags for daily and app relaunch

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
We want users of the promo code tool to be able to add paragraphs into the body copy of the GW landing page. Currently this is disallowed because `p` is not in the list of allowed markdown tags, this PR adds it.
> Add the p tag to the list of allowed Markdown tags

- support-frontend/app/controllers/Promotions.scala
- support-frontend/assets/helpers/externalLinks.js
- support-frontend/assets/helpers/productPrice/promotions.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
- support-frontend/conf/routes
This PR has a number of enhancements to the Guardian Weekly product page promotion functionalily.
* Add a new endpoint `/p/[promocode]` which immediately redirects to the appropriate product landing page. This is a convenience for the marketing team.
* Carry any promo code which is present on the Guardian Weekly product page over to the checkout when users click through.
* If there is a promo code in effect on the GW product page, link to the T&Cs for that promotion in the promotions section, otherwise link to 10ANNUAL
[**Trello Card**](https://trello.com/c/T0iKX0XW/2697-gw-promotions-landing-page-fixes)
> Promopage fixes

- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
There have been a series of issues in the GW checkout that relate to the billing country of the order. Some of these have been fixed in [previous work](https://github.com/guardian/support-frontend/pull/2112) - @rupertbates is this the correct link? - but there were remaining issues, as detailed in this [Trello Card](https://trello.com/c/Jb5tJnMz/2617-fix-bug-eur-is-not-supported-currency-for-the-bank-transferdirectdebituk-payment-method)
* The billing address radio button in the form is now set to default to 'yes, the billing address is the same as the delivery address'
* When the radio buttons are switched, the billing country is updated to be the same as the delivery country, whether the answer is yes or no, which make the behaviour more consistent and predictable.
> Fix GW checkout bugs by changing the way we manage billing address state

- support-rest/src/main/scala/com/gu/stripe/StripeError.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
This fixes a regression introduced by https://github.com/guardian/support-frontend/pull/2111/files#diff-5df451c12e7db07da6bff1cd98c456f5L35
We have had an increase in support-workers failure alerts because it has been incorrectly ending up in the `FailState` state rather than the `CheckoutFailure` state. Specifically, for stripe payment errors (e.g. wrong cvc code) it should end in the `CheckoutFailure` state and therefore not trigger an alarm.
The `CreatePaymentMethod` step function may return a `StripeError` when it fails.
This becomes the input to `FailureHandler`, which attempts to decode it to a `StripeError`.
But in `CreatePaymentMethod`, the conversion to a `RetryException` currently incorrectly calls `getMessage`, which produces a semi-colon separated string. It should actually …
> Fix encoding of stripe errors in support-workers

- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
There's been an issue with the subs showcase page where it takes you to the GW page when you change currencies. The aim is to fix this so it stays on the same page and just changes currencies.
We'll need to retro-check that the currency detection is still working correctly post-fix. However, I have tested this locally and it still seems to be working. On local it seems to detect 'int' as the location and it's still reverting to this when I switch tabs.
[**Trello Card**](https://trello.com/c/9eUIEpZe/2647-fix-currency-switcher-bug-from-going-to-gw-as-default)
Remove weekly from path in currency switcher on subs showcase page.
> Remove weekly from subscribe currency switcher path

- support-lambdas/stripe-intent/cfn.yaml
In safari the recurring contributions page is failing to send the request to create a stripe Setup Intent.
The error is:
`Request header field Content-Type is not allowed by Access-Control-Allow-Headers`
I'm not sure why the wildcard doesn't work here, or why it's working in other browsers, but this does fix it (tested in CODE before and after).
> Set Content-Type in AllowHeaders

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
I've noticed a few error logs in sentry caused by failure to request a new Payment Method from Stripe. The error logging is currently not very helpful though:
`Error creating Payment Method: [object Object]`
> Stripe Payment Method creation errors: stringify error object in log

- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
We only have one heading tag `<h1>` on our page.
The majority of screen reader users use heading tags to navigate a page. (https://webaim.org/projects/screenreadersurvey8/#heading)
[**Trello Card**](https://trello.com/c/IDfyFJMs)
* Include a hidden `<h2>` tag at the top of the form the form 'Make a contribution'
* Include hidden `<h3>` for 'Your details'
* Include `<h3>` tag inside the `<legend>` tags for each section
> Add a11y headings to form

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
We will soon support the Payment Request button for recurring contributions.
This PR is to get the user's state/province if they are in the US/Canada - this is required by support-workers.
Note - it gets the state from the user's billing address associated with the chosen payment method.
If for some reason the state is not available then it fails with a general error ([it's not customisable](https://stripe.com/docs/stripe-js/reference#payment-response-object)). I tested this by using a UK address on the US landing page:
> Payment request button: get user's state

- support-frontend/assets/helpers/campaigns.jsx
The moment is over!
[**Trello Card**](https://trello.com/c/YJHfRi2W/1619-turn-off-the-landing-page-version-for-the-moment)
* Removed the camaign name
* TBD: turn off 'force campaign' switch in support-admin-console
> Take down moment landing page

- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/helpers/contributions.js
Best practice is to use `kebab-case` instead of `camelCase` for URLs. Also, allowing for the new `single` terminology to be used instead of `one_off`
[**Trello Card**](https://trello.com/c/yd5RqBQQ/1594-landing-page-ab-test-one-product-only-single)
> Tweak contribution type query parameter

- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
- support-frontend/test/selenium/subscriptions/pages/DigitalPackCheckout.scala
[**Trello Card**](https://trello.com/c/p5IsHsZn/2579-connect-stripe-elements-to-intent-client-secret-for-client-side)
* Add stripe elements frontend API integration in addition to payment token API now deprecated.
* Add stripe intent token lambda API integration.
* Enabling SCA payments for next generation secure Stripe API usage.
* Upgraded front end client logic to enable SCA payments.
* Added a feature flag to allow switching between `StripeCheckout` and `StripeElements` API with payment intent/SCA payments usage.
> SCA Stripe API payments integration for support frontend

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss
Marketing can now edit some of the copy on the GW product page via the promo tool, however paragraphs in the copy they add are not styled correctly meaning that it ends up looking like a single block of text. This PR fixes that.
**Before**
**After**
> Add a little bit of margin to the top of paragraphs in the GW promotion description section

- support-frontend/app/controllers/Application.scala
[**Trello Card**](https://trello.com/c/2WKwb3o3/2600-root-geo-redirect-still-goes-to-contribute-for-au-and-us-even-though-we-have-why-support-page-for-them)
* Changed redirect on `/` to go to support showcase page for `US` and `AU`
> Fix root redirect

- support-frontend/assets/components/headers/links/links.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
[**Trello Card**](https://trello.com/c/ZS6DcZpX/2486-refactor-navbar-geolocator-involvement)
* Added a function to infer currency code from `CountryGroupId`.
* Added a modified to navigation links to differentiate external and internal links. External links do not need prefixing with currency code/geo-location.
> Fixing link rendering

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
This is just to allow testing of the recurring Payment Request button in PROD. This feature is currently disabled in PROD, but we need to test apple pay in PROD.
Can be removed after it goes live
> Opt in for recurring payment request button

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We are amending the test to display the secure transaction indicator to 100% of the audience in the UK to benefit from its good performance so far. The grey background is also performing well and will appear to 100% of the UK audience also.
The test remains the same for the other regions, to allow them to reach significance.
This follows on from this PR: (https://github.com/guardian/support-frontend/pull/2165)
[**Trello Card**](https://trello.com/c/9x3rkdRi)
* Remove UK from payment security design test
* Show secure transaction indicator at top of landing page for UK only
* Show grey background on card details for UK
> Payment security reassurance test amendment

- .snyk
- support-frontend/.snyk
I've run `snyk wizard` to look at all of our client-side packages and create a policy to ignore them for the next 30 days if no upgrade is currently available. There is also an option on a few of them to patch locally, but we should discuss this as a stream before deciding whether or how this would work. It would require some type of process design wherein, when we update the snyk policy to include local patches, we would ask people to run `snyk protect` when they next pull.
I will add all RR devs to this PR
[**Trello Card**](https://trello.com/c/H7FxcQat/1623-snyk-rota-joshua)
> ATTN RR DEVS: Adding and updating Snyk policies for client-side packages

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/faqsAndHelp.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/termsAndConditions.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
Previously the promotion terms and copy text on the DP product page was not showing the correct link if a promo code was present in the url, it was hardcoded to always show the September 2019 promotion. This PR fixes that.
As usual ESLint has made a load of changes so I've highlighted the actual important one
[**Trello Card**](https://trello.com/c/pP1sLPmS/2714-promo-code-tool-support-on-digital-subs-landing-page)
> Fix the promo terms link on the DP landing page

- support-frontend/app/controllers/GetAddress.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeFinderStore.js
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeLookup.js
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
[**Trello Card**](https://trello.com/c/OQhOWhfc/2711-put-the-address-finder-aka-postcode-lookup-behind-a-switch)
[**Address lookup error**](https://trello.com/c/wvgdTwTm/2712-add-distinct-error-message-on-the-address-finder-for-an-internal-server-error)
* Added a switch called `checkoutPostcodeLookup` to enable/disable using the external address service during postcode lookup.
* Change logic to return `Promise.resolve([])` when postcode lookup is disabled, by-passing the API Call. Designed to be used only when external service is unavailable.
* Not sure how to use `getGlobal` convention on this one. @rupertbates please advise.
* Added switches to `DEV`, `CODE`, and `PROD` on Amazon S3. Can be checked here: https://support.gutools.co.uk/switches
* Added a failure handler to return specific …
> Add postcode lookup flag

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
The layout got a bit broken after the A/B test control variant was removed. This work fixes the layout.
[**Trello Card**](https://trello.com/c/7j3xnF69/2726-digital-subscriptions-landing-page-layout-issue)
* Reinstate box-sizing: border-box on the product section of the page
* Remove some duplicate styles
* Prettier went a bit crazy adding spaces
> Fix broken layout on digital subs landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
We've added the Payment Request button for recurring contributions (it was already available for single).
It is currently switched off.
We want to A/B test it to see if it impacts acquisitions.
Control:
Variant:
> A/B test the recurring Payment Request button

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
Variants 1 and 3 are peforming the least well, so we are removing them from the test to allow the other variants to reach significance sooner.
[**Trello Card**](https://trello.com/c/848uxSgV)
* Remove V1_securetop
* Remove V3_securebottom
> Payment security design test - remove variants 1 and 3

- support-frontend/assets/helpers/productPrice/priceDescriptions.js
- support-frontend/assets/helpers/productPrice/promotions.js
- support-services/src/main/scala/com/gu/support/pricing/PriceSummary.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
Currently promotional text for the product page price cards and promotional text on the checkout summary come from the same promotion field (description). We want to be able to provide different text for these two pages so this PR switches to using the `roundel` promotion field for the product page cards.
[**Trello Card**](https://trello.com/c/Wd4tLxUM/2729-use-separate-promotion-fields-for-the-checkout-summary-and-the-product-page-price-cards)
> Product price card promo text

- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
There are several types of Stripe payments in the [ophan model](https://github.com/guardian/ophan/blob/master/event-model/src/main/thrift/acquisition.thrift#L35).
But only one is currently supported by support-workers for recurring/subscriptions.
We need it to also support `STRIPE_APPLE_PAY` and `STRIPE_PAYMENT_REQUEST_BUTTON` for our analytics.
This change makes the client send a new field, `stripePaymentType`, to support-workers for Stripe payments.
In a separate PR I will change support-workers to receive this field and to set the paymentProvider field appropriately in the acquisition event.
This is the payload being sent to the backend, now with the new field:
> Send Stripe payment type to backend for recurring/subscriptions

- support-workers/src/main/scala/com/gu/emailservices/FailedDigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/FailedGuardianWeeklyEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala
This is a 2 in 1 special PR
- Print failure email Trello Card: [**Trello Card**](https://trello.com/c/Jrau1rZr/2271-print-failure-email)
- Guardian weekly failed email: https://trello.com/c/dLmrZO7r/2337-guardian-weekly-failure-email
* Added classes for `GuardianWeeklyFailed` and `PrintFailed` emails.
* Added manual tests to check against live Braze deployment/membership-workflow that they work.
> Failure emails

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
This test, which has been running since August, conflicts with the moment landing page copy changes.
Because of a bunch of fake contributions that made their way into our actual contributions table on 11 September 2019, the test needs to be manually analyzed excluding this date. The big picture when doing this analysis is a global AV uplift of +5% from a very small number of contributors.
> Remove test to recognize people who gave single contributions in the past

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
I talked with Amanda about changing the language we were using to address readers in the US from "US readers" to "readers in the US" (would have made the suggestion to @ionamckendrick but she's not in)
> Small landing page copy change

- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentMethods.scala
- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
There are several types of Stripe payments in the ophan model.
But only one is currently supported by support-workers for recurring/subscriptions.
We need it to also support `STRIPE_APPLE_PAY` and `STRIPE_PAYMENT_REQUEST_BUTTON` for our analytics.
1. receive the new `stripePaymentType` field from the client
2. add it to the `PaymentFields` object
3. send the new types to ophan in the acquisition event
The client already sends a `stripePaymentType` field - https://github.com/guardian/support-frontend/pull/2217
> Send Stripe payment type to ophan for recurring contributions

- support-frontend/assets/pages/contributions-landing/contributionsLandingEOY2019.scss
@tjsilver helpfully pointed out that the current layout for the end of year campaign is not responsive. I found the rule breaking the responsivity of the page, removed it, and re-tested it.
> fixed non-responsive rule in template for EOY campaign

- support-frontend/assets/components/secureTransactionIndicator/secureTransactionIndicator.scss
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We are testing whether showing a secure transaction indicator and grey background on the card fields will improve AV. This test will run everywhere except UK.
The secure transaction indicator will be placed at the top on mobile and in the middle from phablet size onwards.
This follows from: https://github.com/guardian/support-frontend/pull/2165, https://github.com/guardian/support-frontend/pull/2192 and https://github.com/guardian/support-frontend/pull/2211.
[**Trello Card**](https://trello.com/c/etJkZP08)
* Control - white background
* V1_securemiddlegrey
> Payment security test 1B secure transaction indicator with grey background (non-UK)

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/paymentIntegrations/stripeCheckout.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
We have been running an A/B test to compare Stripe Elements for recurring contributions vs the old Stripe Checkout (popup) implementation.
Stripe Elements has performed better, and so Stripe Checkout can now be removed.
Note - Stripe Checkout is still used by the Payment Request button (though it doesn't use the popup). This is the last thing to be migrated to the SCA-compliant Stripe integration. Then we can clean up any remaining Stripe Checkout code.
I've tested card and Payment Request button payments.
> Remove Stripe Checkout for recurring contributions

- support-frontend/app/controllers/Application.scala
- support-frontend/assets/components/socialShare/socialShare.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
We forgot to revert the links and image to the standard share links and the new, general share image following the moment. This commit fixes that.
> Contributions social share - reverted text, added new image

- support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyCheckout.scala
#2188 removed gifting options from the GW checkout but the post deploy test was still looking for them so failed. This fixes it.
> Remove gifting from GW post deploy test

- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
It's too close to December to keep collecting email reminders for December! Onto March!
[**Trello Card**](https://trello.com/c/0DxkULlO/1664-light-update-the-poc-copy-only)
> Remind me in "March" instead of December, new general copy

- support-frontend/assets/helpers/checkouts.js
The contributions landing page currently doesn't get your selected contribution type from local storage. This fix makes the key name consistent with other places in the codebase
> Fix session storage selectedContributionType key

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
Requested test for the US landing page
[**Trello Card**](https://trello.com/c/lRxnsHth/1662-flip-the-amounts-ordering-on-the-us-landing-page-ab-test)
Control amounts annual:
Control amounts monthly:
Control amounts single:
Reversed amounts annual:
Reversed amounts monthly:
Reversed amounts single:
> Reverse amounts testing

- .gitignore
- project/LibraryVersions.scala
- support-frontend/app/views/ViewHelpers.scala
- support-lambdas/stripe-intent/build.sbt
- support-models/build.sbt
- support-workers/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
- support-workers/src/test/scala/com/gu/salesforce/SerialisationSpec.scala
Using latest version of acquisition event producer library so that we can use the new component type for the subscriptions banner.
There was a transitive dependency bump for circe, so to make things easier I have bumped here too.
* Change 1
* Change 2
> Bump acquisition event producer for new component type

- support-frontend/assets/pages/digital-subscription-landing/components/productBlock.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
It is confusing for Australians to see 'The newspaper' and 'The Guardian Daily' so we're changing the text to be  'The UK newspaper' and 'The UK Guardian Daily' when the country selected is Australia.
[**Trello Card**](https://trello.com/c/1hsBY1Bl/2753-aus-digital-subs-amends-showcase-and-landing)
> Regionalise DP landing page and showcase WRT daily for Australia

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
We are currently linking to the non-gift promotion T&Cs page from the GW gift promo page. This fixes that.
[**Trello Card**](https://trello.com/c/xh3l1Jjd/2762-gift-promo-tcs-link)
> Go to the correct promo T&Cs page for gifts

- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
There was a bug with the code which shows promotional copy on the Guardian Weekly product page when there is a valid promotion active. The copy was not being updated in the EU or ROW region for promotions which are only valid in those regions.
The reason for this is that the way that the promo code tool specifies that a promotion is valid in a given region is by setting it as valid for every country in that region (not the region itself). On the product pages we were using the default country for the region to check if a promo code was valid. This was fine for UK, US, AUS, NZ & CA which have a default country but EUR and ROW do not so the check was always failing and the promo code was flagged as invalid.
This PR changes the product page to just pick any country from the region when …
> Fix eu promo copy

- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
We are currently running a test for the Payment Request button (and apple pay button) for recurring contributions.
The control does not see the button.
Only some users are able to see the button because it depends on their browser and if they have payments set up. So for the test analysis we need the ability to filter both the control and the variant for only people who can see the button.
This change ensures that the Stripe button is initialised, even if the user is in the control and will not actually see it. This is so that we send an ophan event to indicate that they _could_ see it.
This cannot be done at the time that they're assigned to the test, because we do not know until later on if their browser supports the button.
> Always fire Stripe Payment Request button event

- support-models/src/main/scala/com/gu/support/encoding/JsonHelpers.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/main/scala/com/gu/support/workers/states/FailureHandlerState.scala
- support-models/src/main/scala/com/gu/support/workers/states/SendAcquisitionEventState.scala
- support-models/src/test/scala/com/gu/support/workers/SerialisationSpec.scala
- support-workers/elasticsearch/cloudWatchToElasticSearchLambda.js
- support-workers/elasticsearch/readme.md
- support-workers/src/main/scala/com/gu/monitoring/LambdaExecutionResult.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
- support-workers/src/test/scala/com/gu/monitoring/LambdaExecutionResultFixtures.scala
- support-workers/src/test/scala/com/gu/monitoring/LambdaExecutionResultSpec.scala
As part of our health OKR for this quarter we want to start logging all step functions executions to Elasticsearch so that we can do analysis of them more easily.
The way that this works is 
* We log the result of each lambda execution to CloudWatch as Json
* A CloudWatch subscription sends all log messages matching a particular filter to Elasticsearch (via the LogsToElasticsearch_support-elk-domain lambda) 
* Elasticsearch has a pipeline set up which extracts the Json into separate fields
[**Trello Card**](https://trello.com/c/99hEG7T9/2637-failure-reporting-tool)
* Create a `LambdaExecutionResult` class to capture the data we are interested in
* Log results from the `FailureHandler` and `SendAcquisitionEvent` lambdas - these are the two exit points for the step function
> Log lambda execution results to Elasticsearch

- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/assets/components/headingBlock/headingBlock.scss
- support-frontend/assets/components/packshots/print-feature-packshot.jsx
- support-frontend/assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.jsx
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/helpers/subscriptions.js
- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
These changes are for the upcoming General Election, which involve change the print subscription banner and adding the 25% off sales copy to the print subscription page and showcase page
[**Trello Card**](https://trello.com/c/5AGabLoV/2709-voucher-hd-25-off-annual-marketing-campaign-29-11-15-12-around-election)
* Print section moved to the top of the showcase page, with sale price shown
* Print Subscription banner changed
* Sale prices on price cards for Vouchers
* Sale prices on price cards for HomeDelivery
> Print Subscription sale changes, for general election

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
We want to run a test on product ordering on the subscriptions showcase page to find out how much difference the top slot makes to conversion rates.
[**Trello Card**](https://trello.com/c/ojG2xzlb/2783-a-b-test-showcase-page-reordering-test)
[**Link to test spec document**](https://docs.google.com/presentation/d/1kMByVvBYrCXI2x5WL2IQaUxKz-JAab9KnAETSgOIWlE/edit#slide=id.g6b9e270345_0_4)
> Showcase page ordering test

- support-frontend/assets/pages/showcase/components/hero.jsx
- support-frontend/assets/pages/showcase/components/hero.scss
Because it's broken.
[**Trello Card**](https://trello.com/c/NAtisKoO/2787-display-issue-on-why-support-page-in-firefox)
Fixed on Firefox:
Still looking nice on Chrome:
> Fix image display on support page header

- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
- support-frontend/test/selenium/subscriptions/pages/DigitalPackProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyGiftCheckout.scala
- support-frontend/test/selenium/subscriptions/pages/PaperProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/ProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/SubsLandingPage.scala
- support-frontend/test/selenium/subscriptions/pages/WeeklyGiftProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/WeeklyProductPage.scala
We now have a separate product page and checkout for Guardian Weekly gifts so we want to have post production tests in place for these to give us confidence that they are working correctly after every change to master
[**Trello Card**](https://trello.com/c/X2uBAVTZ/2765-gw-gifting-add-post-deployment-tests-for-gifting-checkout-and-landing-page)
> Weekly gift tests

- support-frontend/assets/components/productHero/productHero.jsx
Because circles are sooooo yesterday.
[**Trello Card**](https://trello.com/c/YmTB0pSx/2677-remove-circles-design-from-digital-pack-thank-you-page)
> Remove circles from digital subs thank you page

- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx
It didn't look quite right.
[**Trello Card**](https://trello.com/c/2Zl6IW2m/2766-gw-gifting-header-text-on-gift-landing-page-desktop-only)
> Fix header for gifting landing page

- support-frontend/assets/pages/contributions-landing/newTemplate.scss
There was an unnecessary stylesheet being imported into the stylesheet for the new landing page. This was causing a CSS reset to happen after much intentional CSS had been applied. This PR removes that import and fixes the bug.
Fixed form:
> Landing page font fix

- support-frontend/assets/components/packshots/print-feature-packshot.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
The position of the image for the print feature had drifted up away from the bottom edge of the blue feature box. This work is meant to keep the image neatly at the edge.
[**Trello Card**](https://trello.com/c/HqXD3q73/2790-image-fix-on-showcase-page)
> Adjust position of image for print feature card on showcase

- support-frontend/assets/pages/weekly-subscription-checkout/helpers/__tests__/deliveryDays.js
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.js
There is no Guardian Weekly issue on December the 27th so we shouldn't offer this as a potential delivery date.
[**Trello Card**](https://trello.com/c/pxFZq1ZM/2798-exclude-the-27th-of-dec-from-list-of-delivery-dates-for-guardian-weekly)
> Don't offer 27th of Dec as a delivery date for GW

- support-frontend/package.json
- support-frontend/yarn.lock
This [snyk issue](https://app.snyk.io/org/the-guardian-cuu/project/4945d58e-89a9-4577-9acf-4831f0e0231a#issue-SNYK-JS-JSYAML-174129) suggests updating js-yaml, which is a sub-dependency of cssnano.
It turns out that js-yaml is a sub-dependency of a number of node modules, so there are various places where it might need to be updated.
It wasn't updated in every case - in some places there seems to be a dependency on a specific version of it.
> Update js-yaml to address snyk issue

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/newTemplate.scss
The landing page template test isn't going very well so we are releasing a second round with less variance from the first.
[**Trello Card**](https://trello.com/c/rKzsjt5X/1704-new-round-of-testing-on-the-lp-including-header-and-font-changes)
* Changed header to the control version and adapted accordingly to the new layout
* Changed typography to match control version
* Changed colour scheme to match control version
* Adapted footer to fit the new layout
For comprehensive screenshots, see the previous PR: https://github.com/guardian/support-frontend/pull/2220
Updates reflected below:
> Landing page template test, round 2

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
The test has run its course and shown no difference based on the order of amounts in the context of the US
[**Trello Card**](https://trello.com/c/mEypbQmM/1707-end-landingpagereverseamounts-test)
> Disabled reverse amounts test

- build.sbt
- support-config/src/test/scala/com/gu/support/config/PromotionsConfigSpec.scala
- support-frontend/build.sbt
- support-internationalisation/src/test/scala/com/gu/i18n/CountryGroupTest.scala
- support-lambdas/stripe-intent/src/test/scala/com/gu/stripeIntent/HandlerITSpec.scala
- support-lambdas/stripe-intent/src/test/scala/com/gu/stripeIntent/HandlerSpec.scala
- support-models/src/test/scala/com/gu/support/SerialisationTestHelpers.scala
- support-models/src/test/scala/com/gu/support/catalog/SerialisationSpec.scala
- support-models/src/test/scala/com/gu/support/encoding/EncoderSpec.scala
- support-models/src/test/scala/com/gu/support/encoding/JsonHelpersSpec.scala
- support-models/src/test/scala/com/gu/support/encoding/PaymentMethodEncoderSpec.scala
- support-models/src/test/scala/com/gu/support/promotions/SerialisationSpec.scala
- support-models/src/test/scala/com/gu/support/workers/PaymentMethodIdTest.scala
- support-models/src/test/scala/com/gu/support/workers/ProductTypeDecoderTest.scala
- support-models/src/test/scala/com/gu/support/workers/ProductTypeRatePlansSpec.scala
- support-models/src/test/scala/com/gu/support/workers/SerialisationSpec.scala
- support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
- support-services/src/test/scala/com/gu/aws/AwsCloudWatchMetricPutSpec.scala
- support-services/src/test/scala/com/gu/support/catalog/CatalogServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/catalog/CatalogServiceSpec.scala
- support-services/src/test/scala/com/gu/support/getaddressio/GetAddressIOServiceSpec.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionApplicatorSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionCacheSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionTermsSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionValidatorSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/dynamo/DynamoServiceSpec.scala
#2137 upgraded scalatest in support-frontend to 3.2.0-M1 but all the other projects were still using 3.0.8. 
This was causing `NoClassDefFoundError` when using the `SerialisationTestHelpers` class from `support-models` in other projects so I have upgraded all the projects to use version 3.2.0-M1
[**Trello Card**](https://trello.com/c/AAgmcmce/2809-upgrade-scalatest-in-support-frontend)
> Use scalatest version 3.2.0-M1 in all projects

- support-frontend/assets/pages/contributions-landing/newTemplate.scss
This template does not use the grid system but still was being affected by it. I'm not sure why it only caused a visible bug on the US landing page but it did. This change fixes the symptom, not the problem, which will take more work.
US LP Wide:
UK LP Wide:
> Bugfix on the new landing page template

- support-logs/retention-lambda/Makefile
- support-logs/retention-lambda/cfn.yaml
- support-logs/retention-lambda/configure
- support-logs/retention-lambda/lambda_function.py
- support-logs/retention-lambda/riff-raff.yaml
Now that we have [serious logs](https://github.com/guardian/support-frontend/pull/2251) being streamed to kibana, it's important to have a retention policy applied to the data.
Kibana has a "turn key" solution for this called [Index Lifecycle Policies](https://www.elastic.co/guide/en/kibana/current/index-lifecycle-policies.html), which is unfortunately not available in AWS's elasticsearch service. Reason being that aws uses the open-source version of elasticsearch, and ILP is an x-pack feature available [on the Basic plan and above](https://www.elastic.co/subscriptions).
Luckily,  [amazon's documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/curator.html) sketches out a solution to this using lambda and the elasticsearch python library (specifically a …
> Elasticsearch retention policy lambda

- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/assets/components/headingBlock/headingBlock.scss
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
- yarn.lock
The election changes for the print landing page were temporary and these changes restore the page to its former state.
**These changes are due to be updated on 16 Dec. Do not merge until then!**
[Trello Card](https://trello.com/c/bzPERL3G/2734-switch-off-print-sale-needed-to-be-switched-off-on-16th-morning)
* Heading is back to yellow banner
* Maximum discount is restored to 37% in roundel and headings
* Product cards returned to state without offer text
> Restore print landing page to pre-election state

- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/pages/promotion-terms/DigitalPackTerms.jsx
- support-frontend/assets/pages/promotion-terms/legalTerms.jsx
- support-frontend/assets/pages/promotion-terms/promotionTermsReducer.js
- support-frontend/assets/pages/subscriptions-landing/components/subscriptionsLandingContent.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLandingReducer.js
This PR does a couple of things because they are closely linked.
Firstly it removes the additional Redux store initialisation which was happening in subscriptionsCopy.jsx. The store is already being initialised in subscriptionsLanding.jsx so initialising it twice was causing duplicate analytics events. It also breaks the pattern of the page loading its state and then passing that down to connected components.
Secondly I have used the opportunity of this refactor to take the pricing information shown on this page from the Zuora catalog and any promo codes which are active. This means that this page no longer needs to use flashSale.js and all that is required to set up a new flash sale is to set default promo codes in the `Subscriptions` controller.
[**Trello …
> Showcase promotions

- support-frontend/assets/components/packshots/digital-packshot.jsx
- support-frontend/assets/helpers/theGrid.js
This fixes the mobile (non-feature) digital subs packshot on the subs landing page.
[**Trello Card**](https://trello.com/c/bjPb3rd8/2774-fix-digital-subs-showcase-page-mobile-image)
> Update mobile image for non-feature digital subs

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
[This line](https://github.com/guardian/support-frontend/pull/2254/files#diff-4d1709d642d3327cb582515d95827c21R16) got removed by the merge commit, presumably because another change had removed it
> Fix ab test

- support-frontend/app/controllers/Promotions.scala
- support-frontend/assets/helpers/productPrice/promotions.js
- support-frontend/assets/pages/promotion-terms/promoDetails.jsx
- support-services/src/main/scala/com/gu/support/promotions/PromotionTerms.scala
We have a feature on the site where people can go to the url `/p/[any promo code]` and then be redirected to the product page for the promoted product. We want this endpoint to be aware of gift promotions so that if the promo code is a Guardian Weekly gift offer then the user will be redirected to the gift version of the product page.
I have also updated the promotion terms page so that for gift promotions the 'Get this offer' button goes directly to the gift version of the product page
[**Trello Card**](https://trello.com/c/uo6uhzY2/2770-redirect-gift-promotions-to-the-gifting-page)
> Send gift promo codes to the gift version of the GW product page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
We've been 0% testing in PROD.
All working and ready to show to 50% of US single contributors.
Can still be switched off from the admin console switchboard if something is wrong.
> Enable amazon pay a/b test

- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayWallet.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
We display our own error messages in the usual place, but amazon's wallet widget can also display error messages.
In order to do this, we have to re-create the widget, passing in the same orderReferenceId.
Here we can see both our message and amazon's message about card info:
> Display amazon's error message in the widget if InvalidPaymentMethod

- support-models/version.sbt
doing this manually because I had to comment out the `pushChanges` step to get it to release, see https://github.com/guardian/support-frontend/pull/2293
> Update version to 0.67-SNAPSHOT

- support-frontend/assets/components/headingBlock/headingBlock.jsx
- support-frontend/assets/components/headingBlock/headingBlock.scss
- support-frontend/assets/components/productPage/productPageHero/productPageHero.jsx
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
The way that we've been managing the line breaks on the landing pages standfirst (the main heading in the black banner) no longer seems the best approach as it was causing one heading to wrap onto three lines. 
So rather that relying on css to manage this, I've updated it to be controlled by line breaks instead, and can thus be handled on a case by case basis.
This has had some knock-on effects to other landing pages (Paper and regular Guardian Weekly) so I have managed the line breaks for these standfirsts also.
[**Trello Card**](https://trello.com/c/dkhRjTXe/2817-standfirst-should-not-wrap-on-gifting-landing-page-on-wide)
> Remove css controlling banner widths and use line-breaks instead

- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
The typeface of the page heading was looking quite odd on mobile.
[**Trello Card**](https://trello.com/c/ZU5OemXO/2819-typography-fix-change-on-mobile-for-subs-landing-page)
> Fix typeface for mobile view of subs heading

- support-frontend/app/controllers/Subscriptions.scala
#2292 Changed the showcase page to use promotional copy in the product cards, however it was using a different field for paper to the one used for GW and DS. This is complicated to explain to users and also resulted in a bug because the field used by DS was not specified.
This PR switches the behaviour to use the description field (the same field as used by the checkout summary) for all products. This is simpler to explain and as it is a mandatory field will not result in the bug mentioned above.
[**Trello Card**](https://trello.com/c/ryP1Isc2/2823-change-the-promotion-copy-field-used-on-the-showcase-page)
> Use promotion discount text on the showcase page for simplicity

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
This reverts commit bd577a4a69fdfc014a0ec85ac7250001772a7243.
We want to run this test again for EOY in US
> Revert "disabled reverse amounts test (#2282)"

- support-frontend/app/admin/settings/Settings.scala
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
This PR rolls out Apple Pay and the Stripe Payment Request Button to 100% for Recurring Contributions, and puts them behind a feature switch.
Apple Pay test variant yielded 300% increase over the control! PRB made no significant difference.
[**Trello Card**](https://trello.com/c/cXTbe8wQ)
* Removed A/B test for Apple Pay / Stripe Payment Request Button for recurring contributions.
* Added Apple Pay and the Stripe Payment Request Button between 4 independent feature switches - 2 switches for single and 2 for recurring.
[I'll add these after the fact as it's hard to get my iPhone into the test variant!]
**Do not deploy this to PROD till 10am on Friday 27th**
> Roll out Apple Pay to 100% for Recurring Contributions!

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
#1104  Why are you doing this?
We've been asked to disable the losing Amazon Pay test for the biggest days of the year (which are now). To be reversed on Thursday.
> To be reversed on Thursday: temporarily disabling amazon pay test

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPay.scss
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayLoginButton.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
Reinstate Amazon Pay A/B test with a different test name and seed, and added an extra component loaded event to show that the button was there to select.
[**Trello Card**](https://trello.com/c/I7FvdqNu)
Amazon Pay shows when in the test variant:
And the component event action="VIEW" beacon fires:
> Reinstate Amazon Pay A/B test with a different test name and seed

- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionState.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTextInput.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
According to the new [Source Design System](https://zeroheight.com/2a1e5182b/p/35ba96) it is preferable to remove the 'required' label from form fields and display an 'optional' label where applicable instead. 'Required' fields add unnecessary noise for screen readers.
[**Trello Card**](https://trello.com/c/t9D8oECp)
* Remove `showRequiredLabel` prop from ContributionTextInput and ContributionState components
* Change function to show 'optional' label instead of 'required' in ContributionTextInput component (it seemed pointless to do this for the ContributionState component as it's only used in one place and is required, but can implement if better practice to do so).
> Accessibility: remove 'required' fields from contribution form

- support-frontend/app/controllers/ReminderController.scala
- support-frontend/app/services/RemindMeService.scala
- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.scss
- support-frontend/test/services/RemindMeServiceSpec.scala
In support of our KR on reminders, we are expanding the post-contribution reminder feature.
[**Trello Card**](https://trello.com/c/2B3RQXRA/1634-update-the-post-contribution-reminder-to-offer-different-frequencies)
Frontend: Adding form elements from support-ui, wiring them to update the request we are sending to the backend
Backend: modifying the event being sent to the lambda to be backwards compatible -- to support the two different lambdas, one of which is in code and one of which is in prod ( cc: @JoemG )
> Expanded options on the post contribution reminder

- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
UX came up with an additional solution for pre-selected radio buttons following the release of this feature. This PR will update the feature with the new pre-selected options.
[**Trello Card**](https://trello.com/c/Lnan3eec/1759-randomising-pre-selected-option-on-radio-buttons-on-post-contribution-reminder)
> Added random pre-selection to radio button feature

- support-frontend/assets/helpers/render.js
- support-frontend/assets/helpers/userAgent.js
Axe (dev dependency library that warns about accessibility issues) was preventing us from demoing and testing the support site locally. I've added a new helper file to detect the user agent (specifically to detect if it is safari) and re-route the render accordingly.
> Regex to detect Safari and prevent it from using Axe to render locally

- support-frontend/assets/components/marketingConsent/marketingConsentWithCheckbox.jsx
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayLoginButton.jsx
- support-frontend/assets/pages/contributions-landing/components/MarketingConsentContainer.jsx
We cannot show the "receive a weekly newsletter" copy alongside the opt in on the thank you page to single contributors, since we only send this to recurring contributors. 
This PR updates the title text for all single contributors and recurring US/Aus contributors "... receive occasional emails...", plus removal of 'from the week' from the message body.
The remaining recurring contributors continue to see the existing "... receive a weekly email..." copy.
[**Trello Card**](https://trello.com/c/wYeQmMhY)
* Change copy for all single contributors and US/Aus returning contributors.
> Update marketing opt in copy for single contributors (thank you page)

- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
The June date had a typo making it a March date.
The 1st of March date will need to be changed in the DB to 1st June after this has been deployed
[**Trello Card**](https://trello.com/c/trKq1BFj/1780-update-the-timestamp-of-the-june-reminder)
* Change 1
* Change 2
> correcting typo in date

- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
The privacy terms do not pass a colour contrast test, which causes visibility issues for many users. I have not increased the text size for now, although this was recommended, so we might want to consider doing this too.
[**Trello Card**](https://trello.com/c/cksSem2d)
* Use darker colour for text and links
> increase contrast on privacy terms

- support-logs/cfn.yaml
- support-logs/riff-raff.yaml
I've been investigating why KibanaProxy was running an out of date ami, and realised the riff raff yaml was misconfigured. It had `amiEncrypted` set to true, which is not the case for the `ubuntu-xenial-with-nginx`
In the process of debugging this I actually ended up simplifying the set up slightly, so I kept those changes as well.
I should also add that I added a scheduled deployment to the project so the ami doesn't get stale. [I've set it to weekly](https://riffraff.gutools.co.uk/deployment/schedule/fd7ed3b5-d93a-4c95-95ca-8f9057d0a140/edit)
> Fix deployment of KibanaProxy

- support-models/src/main/scala/com/gu/salesforce/Salesforce.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala
In light of an upcoming Salesforce maintenance window (where SF will go into ReadOnly mode), we anticipate errors when trying to create contact (during `support-workers` step function) and hence we want to treat the error code **`INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE`** as a **`RetryUnlimited`** scenario (i.e. keep retrying with existing back-off strategy until the request succeeds - at which point customer will get success confirmation email).
_Note `RetryUnlimited` will timeout after 24 hours - at which point customer will get failure email and we will be alerted (via alarm) - however we don't expect this to happen for this upcoming maintenance window._
[**Trello Card**](https://trello.com/c/ivg3G0JE)
> handle Salesforce maintenance errors with RetryUnlimited behaviour

- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
Product wants to know what event is preselected as well as which is eventually selected for the post-contribution reminder
[**Trello Card**](https://trello.com/c/kMukIefU/1802-analytics-for)
> Additional analytics to show which date is preselected for the reminder

- support-frontend/app/services/stepfunctions/StateWrapper.scala
- support-models/src/main/scala/com/gu/support/workers/JsonWrapper.scala
- support-models/src/main/scala/com/gu/support/workers/RequestInfo.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreateZuoraSubscriptionState.scala
- support-workers/src/main/scala/com/gu/support/workers/encoding/Encoding.scala
- support-workers/src/main/scala/com/gu/support/workers/encoding/Wrapper.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
As a follow up to #2335 we now want to remove the base 64 encoding from the state machine json as it is no longer needed.
This PR introduces a new flag `base64Encoded` which is hard coded to false but will default to true if it is missing from the payload. This is to cope with mismatches between support-workers and support-frontend during deployment and can be removed once the two systems are in sync.
This PR doesn't quite get us to where we want to be because the json document we end up with still has the `state` field as a json string rather than a json object but that is going to be a lot harder to migrate to so this is the first step.
[**Trello Card**](https://trello.com/c/ZPylvrLf/2791-remove-encryption-from-support-workers)
> Add a switch for base 64 Encoding

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
I repeat; this is NOT a test.
We need to use a new experiment in Optimize to run a live subs banner test for real (the current one is polluted with our successful attempts to test participation. This should be merged before Monday 3rd and then the experiment set live at the same time as the A/B test on dotcom.
* Change 1
* Change 2
> Update optimize test ID for live subs banner test

- support-frontend/assets/helpers/productPrice/__tests__/productPricesTests.js
- support-frontend/assets/helpers/productPrice/paperProductPrices.js
- support-frontend/assets/helpers/productPrice/productPrices.js
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/campaignHeader.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/heroPicture.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-models/src/main/scala/com/gu/support/catalog/Catalog.scala
- support-models/src/main/scala/com/gu/support/catalog/Pricelist.scala
- support-services/src/main/scala/com/gu/support/catalog/CatalogService.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummary.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
- support-services/src/test/scala/com/gu/support/catalog/CatalogServiceSpec.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
The paper product page has various pieces of copy which show the savings a subscriber would make vs the retail price of the paper. These are currently set in code unlike the prices themselves which are stored in Zuora. This means that if we change the prices we also need to deploy a code change to update this copy.
It would be much easier if we specified the saving vs retail in Zuora as well so that we can change all price information in one place and have the site pick it up without a PR/deploy.
[**Trello Card**](https://trello.com/c/cGKePEXi/2858-implement-print-price-rises-for-new-users-on-print)
> Paper savings

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
The payment request button has a bug when used with recurring. It currently uses the country from the page(uri) instead of from the card address. This causes an error in Zuora as we can end up with invalid combinations of province/country mixing Canada and US.
This change is to send the country from the billing address of the card in the authentication response from stripe. As we send the state from the same place, in theory they will always match up in Zuora and prevent invalid combinations.
[**Trello Card**](https://trello.com/c/L4G6cyzc/1572-payment-requests-button-send-state-to-backend-for-us-canada)
> Updating country sent to support-workers 

- support-frontend/build.sbt
This bumps identity-auth-play to propagate a bump to http4s which has a ConnectionPool leak - see guardian/identity#1682 for more information
* Change 1
* Change 2
> Bumping identity-auth-play

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss
On the 17 February, the Awareness team are activating a marketing campaign localised to Berlin, during the same time, Guardian Weekly will be refreshing much of it's off-platform marketing. To align with both strands of activity and maintain a coherent customer journey, the headlines on regional landing pages for GW have been updated.
[**Trello Card**](https://trello.com/c/VkNuKVGG/2851-customise-copy-on-non-uk-gw-landing-pages-copy-change-only)
* Copy change for GW headline
Note from Lucy: I have updated the line-break for tablet plus view as reequesteed by @cloerose 
Old Copy
New Copy
> Gw landing copy

- .travis.yml
- support-frontend/scripts/post_test_results_to_chat.sh
On the retro for our last incident we decided to try raising the visibility of when post deployment tests fail by posting it to the chat room (see https://docs.google.com/document/d/1OIiEfgEJ3Xw3_rnUt-kCIG0lFkLHBIJ7QqxtoGnXf9o/edit)
This is a PR to do just that! I found an easy way to do it on the travis side (rather than having to change prout, for instance), as there's a hook to run a bash script when a build fails.
I've also started writing a runbook alongside which is a total WIP https://github.com/guardian/support-frontend/wiki/Post-deployment-test-runbook
> Post message to chat when post deployment tests fail

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouBlurb.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
We want to see if there is a correlation between "next steps" taken by a user and our personalisation of the thank you page
[**Trello Card**](https://trello.com/c/uShml0nz/1803-implement-a-more-personalised-thank-you-message-on-the-ty-page)
Control:
With personalisation:
> Landing page personalised copy test

- support-frontend/assets/helpers/subscriptions.js
Paper+Digital pricing information is still hard coded in the site rather than being fetched from the catalog so as the subs prices have now changed, we need to update the minimum price copy on the subs landing page.
[**Trello Card**](https://trello.com/c/vya1IuWF/2827-implement-print-price-rises-for-new-users-on-printdigital)
> Update minimum pricing copy for paper+digital

- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.scss
We want to know if we will increase our post-contribution reminder sign ups by saying for instance "three months (June)" or just "June" -- this test will require manual analysis at the end of the March
[**Trello Card**](https://trello.com/c/n0z8UcQs/1858-post-contribution-reminder-update-phase-3a)
Control:
Extended:
> Copy test for post contribution reminders test

- support-frontend/build.sbt
- support-frontend/webpack.common.js
- support-frontend/webpack.dev.js
Over the last 5 months the dev team has experienced unusually slow rebuild of assets e.g. changing one word in a string would result in a 30 second reload as apposed to a 2 second reload.
The problem was the the play app would recompile with every asset change, this is unnecessary because all the assets are served from the node.js `webpack-dev-server`. The reload would wait for the recompile of the play app which would take 30 seconds or so, then the page could render
The reason for the recompile, was a line which referred to `unmanagedSourceDirectories` instructing sbt that the **assets** folder was a source director, this meant that every time a file in the assets folder changed the *play app* would see that change and trigger an auto-reload. 
When the browser requested the new files …
> Ds slow build investigation

- support-frontend/devrun.sh
I keep accidentally not switching the version of node before running this script. This will prevent that from happening, assuming everyone uses nvm to manage their node versions.
> make sure the right version of node is running in devrun.sh

- support-frontend/assets/helpers/errorReasons.js
- support-frontend/assets/helpers/internationalisation/__tests__/countryTest.js
- support-frontend/assets/helpers/internationalisation/country.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
We receive at around one AWS alarm per day where the value provided in the State field is incorrect, either in terms of what Zuora can understand (2-letter code or full name), and in the set that matches the provided country (e.g. providing Ontario when country is United States).
This change includes a better lookup function in `country.js` called `stateProvinceFromString` that will search for a state based on a provided string of 2-characters, the full state name, or a 3-letter code (which isn't a validly structured code in USA and CA but is in Australia). The function also ensures that it looks up in the correct set of states, respective to the provided country. If there is no match, it returns null.
I also updated the logic which determines whether a state code is required by Zuora. …
> Only send valid state codes down to Step Function

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/package.json
- support-frontend/yarn.lock
This is round 2 of the choice cards test, where we implement only the rectangular variant and the updated design with hover state. The circular amount variant was been removed as it didn't perform as well. 
[**Trello Card**](https://trello.com/c/NaAsLE0h/1867-choice-cards-implement-round-2)
* Update test definitions
* Update choice cards to latest design with hover state and new background colour
> Choice cards round 2 test

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/app/controllers/Promotions.scala
- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/app/views/main.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/conf/routes
When subscription landing pages are shared on facebook/twitter etc we'd like the shared item to include a relevant image to market ourselves a bit more effectively.
While I was there, I noticed that we don't even provide twitter with a card type to use, so I've added that which should be a start for meaningful twitter shares.
I also did a little code reshuffle - moving GW routes into the GW controller which is more consistent with paper and digital.
[**Trello Card**](https://trello.com/c/nYyzs11c/2384-open-graph-tag-optimisation)
* Add specific open graph images to product pages
* Refactor controller methods (move for consistency)
> Add social images for subscription landing pages

- .prout.json
Selenium tests have been breaking due to networking problems : -( travis_retry is a commandline thing available in the travis environment that will retry a failed command up to 3 times.
See https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies
The down side is that if there's a real failure, it will have to run the tests 3 times until it sounds the alarm, which takes quite a bit of time
> Make travis retry the selenium tests up to 3 times

- .github/PULL_REQUEST_TEMPLATE.md
At the most recent accessibility champions meeting, we discussed ways to prompt ourselves to check our code is accessible. Having a list of prompts in the pull request template seems like a good place to add this sort of prompt. This list is copied from the frontend PR template.
Adds a list of accessibility prompts to the PR template.
> Adds accessibility prompt checklist to PR template

- support-frontend/assets/helpers/abTests/abtest.js
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/package.json
This PR is connected to [ds-remove-subs-banner-ab-test](https://github.com/guardian/frontend/pull/22368) PR on `frontend`, this required we remove the ab-test object `SubsBannerNewYearCopyTest`
[**Trello Card**](https://trello.com/c/fSvMOs3M/2891-turn-off-subs-banner-ab-test)
* remove ab-test object
N/A
> Ds remove subs banner ab test

- support-workers/src/main/scala/com/gu/salesforce/SalesforceService.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreateSalesforceContactDecoderSpec.scala
This PR is a fix for the following bug:
* User signs up for a Guardian Weekly subscription (or any sub with a delivery address)
* User subsequently signs up for digital subscription with a different billing address to the previous subscription's delivery address
* The first line of the user's delivery address will be overwritten by the new billing address potentially rendering it useless
[**Trello Card**](https://trello.com/c/V8ZDHGWq/2885-spike-replicate-potential-bug-when-user-has-a-print-product-and-buys-a-subsequent-digital-product)
> Salesforce Address Overwrite Fix

- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/package.json
- support-frontend/yarn.lock
There was an issue on Chrome and Edge where clicking on a card with the mouse caused the tab highlight to appear and persist until another click was made. The tab highlight should only show for keyboard navigation on tabbing. This PR fixes that issue.
* Fix tab highlight issue
> Fix tab highlight issue

- support-workers/cloud-formation/src/templates/cfn-template.yaml
The `no paper acqusitions` alarm went off yesterday and while investigating why that might've been we noticed that we had neglected to add paypal to the metrics behind the alarm since that was added to the paper checkout.
Note: I feel like we also need an alarm like this for GW acquisitions - I'll make a card.
* Include paypal metric in the summed metrics for this alarm
N/A
N/A
> Add paypal to paper acquisition alarm

- support-frontend/assets/helpers/formValidation.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
This change fixes 3 bugs and has 1 refactor:
1) A mismatch between the state and country when the user's billing data is sent to Zuora. Before, when somebody chose not to transact in USD, CAD or GBP, but was based in USA or CA (where a state is required), we would read their billing country from their GEO-IP, but then we'd have no state to add alongside the country, as the form for the other currencies do not have a state drop-down, and would submit a blank state which would error in Zuora. This solution also reads the state value from GEO-IP. It's not a perfect solution as the GEO-IP read may fail. A full solution would be to include a billing country and optional state drop-down on all checkouts. That may be a later PR if we still get some of these 'on holiday' errors. This was not …
> Fix state mismatch and console logging bugs

- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
This change fixes a bug introduced by https://github.com/guardian/support-frontend/pull/2378 where we used a different billing country than the page's Direct Debit payment method supports.
[**Trello Card**](https://trello.com/c/qNyxy3in)
> Fixed a bug where we used a different billing country than the page's Direct Debit payment method supports

- support-models/src/main/scala/com/gu/support/workers/PaymentMethods.scala
- support-models/src/main/scala/com/gu/support/zuora/api/PaymentGateway.scala
- support-models/src/main/scala/com/gu/support/zuora/api/response/Responses.scala
- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
There were two reasons for the occasional failures with `PreparePaymentMethodForReuse` step of `support-workers`...
- Some users had missing `creditCardType` on their Zuora `PaymentMethod`s and so we were seeing Decoding failures as this was `String` rather than `Option[String]` (this field type also had to be updated on `CreditCardReferenceTransaction` as posting empty string produces a different error)
_I discovered some of these were creeping in on Amex cards updated via MMA, since the SCA changes - https://github.com/guardian/manage-frontend/pull/371 and https://github.com/guardian/membership-common/pull/606 will fix/prevent the creation of anymore of those_
- For some users their DirectDebit has Zuora payment gateway `GoCardless - Zuora Instance` rather than the main `GoCardless` …
> [support-workers] fix intermittent issues with PreparePaymentMethodForReuse step

- support-frontend/.flowconfig
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/choiceCardStyles.jsx
We want to learn whether yellow works better due to 1) brand association / consistency with where they have come from, i.e. the banner; 2) our’s is a plain landing page, do users respond to the key parts of our payment flow if they stand out more (yellow).
[**Trello Card**](https://trello.com/c/mKdWOgVb/1889-implement-choice-cards-round-3)
* Make blue choice cards the control
* Variant is yellow choice cards 
Control: 
Variant: Yellow choice cards
> Choice cards test round 3

- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
This is a fix for https://github.com/guardian/support-frontend/pull/2393 where the yellow variant was being rendered when 'Other' selected in the control.
> Fix error with css override on Other card

- support-frontend/.babelrc
- support-frontend/.flowconfig
- support-frontend/package.json
- support-frontend/yarn.lock
Based on my learnings from the design system spike, this is the config that we'll need to work with emotion with minimal friction.
Related to [this trello card](https://trello.com/c/8TS2w2yb/2884-spike-timeboxed-2-days-guardian-design-system-foundations).
* Add emotion presets to .babelrc
* Add following npm packages:
@emotion/babel-preset-css-prop
@emotion/cache
emotion-theming
* Add .*node_modules/@emotion/babel-preset-css-prop.* to untyped list in .flowconfig
> Add groundwork for using emotion

- support-frontend/assets/pages/contributions-landing/components/choiceCardStyles.jsx
The text colour for the yellow variant was a dark blue instead of black. This is a follow-on from https://github.com/guardian/support-frontend/pull/2393.
* Change yellow variant text colour to black (#121212)
> Change text colour to black on yellow variant

- support-workers/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
Recently we had some support-workers failures caused by Zuora rate limiting [retro here](
https://docs.google.com/document/d/18SNixCPb13Ja0RDNpVfGNsZQwZVI8xGoxEHPIVlT1TA/edit)
One action from this was to change our error handling to retry (with the appropriate backoff) in the event of a rate limiting error.
[**Trello Card**](https://trello.com/c/mmvhzSkb/2899-retry-on-zuora-rate-limiting-errors)
> Make step function retry on 429 rate limit responses

- support-frontend/devrun.sh
Properly sourcing `nvm` in the context of the script -- a fix for https://github.com/guardian/support-frontend/pull/2373:
I keep accidentally not switching the version of node before running this script. This will prevent that from happening, assuming everyone uses nvm to manage their node versions.
> fixed: make sure the right version of node is running in devrun.sh

- support-frontend/assets/helpers/internationalisation/country.js
- support-frontend/assets/pages/contributions-landing/setUserStateActions.js
This change fixes how the new compulsory AU State Field (introduced in https://github.com/guardian/support-frontend/pull/2396) gets pre-populated by GEO-IP on page load. The new solution is much simpler, not requiring the `fromCountryGroup` function that should not return AU country for AUDCountries group, because multiple countries in our model use AUD.
I'm making this change because there has been a small reduction in recurring contribution AV from Australia since the introduction of the field on Friday. It also makes everything consistent with the 3 checkout 'country groups' that require a state.
> Prefill AU State / Province with GEO-IP value on Recurring Contribution checkout

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
There have been some issues with the errors in stripe, and this aims to improve them. However there is a [larger piece of work to be done](https://trello.com/c/ES2XbqvY/2911-clean-up-stripe-checkout-validation-and-form-submission-process) to separate the validation and authentication errors and the submit process with the stripeForm element.
This work just tidies up a smaller and more immediate problem with the error messaging. The [trello card](https://trello.com/c/lGEPixmv/2767-gw-gifting-add-spacing-between-error-messages-such-as-payment-failures-and-blue-footer) for this work indicates a spacing problem that I was not able to replicate. 
* Pass three errors into function to get back a user-facing error message and render it.
> Improve error messaging in stripe

- support-frontend/app/controllers/RegularContributions.scala
- support-frontend/app/models/identity/requests/CreateGuestAccountRequestBody.scala
- support-frontend/app/services/HttpIdentityService.scala
- support-frontend/app/views/testUsers.scala.html
- support-frontend/test/models/identity/requests/CreateGuestAccountRequestBodyTest.scala
Recently Identity made some changes to make it less likely people would reveal personal information as part of their profile.  The significant part of that was to make it so if we create a guest user with a displayName, the displayName is ignored and returned as "user".  This means we don't detect the user as a test user, and instead process the subscription using prod databases (which fails in support-workers).
Now we are supposed to create with the firstName set to a testUser string, and then read from the username field, which will match if it's a test user.
This PR updates the code to write both first and second/last name to identity on guest checkout.  Then the returned username is used to decide if they are a test user.  The email address is ignored, so people can feel free to use …
> Use firstname rather than displayname for test users

- support-logs/cfn.yaml
It's still unclear if we're going to reserve instances for Kibana, but in any case it's the only setup in our estate that uses a t2 instance. Everything else uses t3, so this brings it more inline with our standard infrastructure.
> Change instance type of nginx proxy to t3

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
#1104  
We had an error where a first name was not getting set due to insufficient whitespace handling on the data we get when a user uses the payment request or apple pay button. This fixes that problem.
Before:
"     jean   claude   van     damme     " => `["","","","", "jean","",...etc ]`
After:
"     jean   claude   van      damme     " => `["jean","claude","van","damme"]`
> BUGFIX: Remove whitespace in and around a name for payment request button

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/components/content/content.jsx
- support-frontend/assets/components/content/content.scss
- support-frontend/assets/components/customerService/customerService.jsx
- support-frontend/assets/components/footer/footer.jsx
- support-frontend/assets/components/legal/contribLegal/contribLegal.jsx
- support-frontend/assets/components/questionsContact/questionsContact.jsx
- support-frontend/assets/helpers/dotcomContactPage.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/components/faqsAndHelp.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-services/src/test/scala/com/gu/support/catalog/CatalogServiceIntegrationSpec.scala
During the Corona virus outbreak we may need to change our contact details at short notice. 
this PR uses a new switch `useDotcomContactPage' which when enabled will change all the contact us information to point to a single page on dotcom which can be easily updated by central production.
[**Trello Card**](https://trello.com/c/dwy3Ir7I/2925-update-contact-us-details-to-point-to-a-webpage-in-event-of-customer-service-outage)
> Dotcom contact page

- .prout.json
We recently added retry logic to the post deployment test execution to mitigate false negatives. See #2377 
This has reduced the number of false negatives, but it's had the side effect of greatly increasing the latency between the PR being merged and the alert being raised. It's taking about 30 minutes now. This both increases the impact of issues in production, but is also a source of confusion as it severs the immediate cause and effect relationship between merging and getting an alert.   
Instead of using travis_retry, which is built in but is hardcoded to 3 retries ([literally hardcoded](https://github.com/travis-ci/travis-build/blob/75dba2e42e50811827a9f8691b1d4f55eefe268d/lib/travis/build/bash/travis_retry.bash#L4)), this PR implements basic retry logic by using the bash OR operator …
> Only retry once

- support-frontend/assets/pages/digital-subscription-landing/components/faqsAndHelp.jsx
- support-frontend/test/selenium/subscriptions/pages/DigitalPackProductPage.scala
#2407 broke the Digital Subscription product page selenium test by removing a footer class, this PR fixes it by adding a qa id onto the footer component.
> Fix DigitalPackProductPage selenium test

- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
After refreshing a Salesforce sandbox we don't have the old contacts that the tests refer to. As a result this was making the zuora sync have errors.
Now the test user will have linked subscriptions in Salesforce and will stop the sync errors occuring.
[**Trello Card**](https://trello.com/c/iB6mlpSp/987-sub-sync-between-dev-zuora-and-dev-salesforce-working-reliably)
* Change 1
* Change 2
> Change Salesforce contact used in tests

- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
This change ensure the captcha (introduced in https://github.com/guardian/support-frontend/pull/2392) only applies when using the Stripe payment method.
> Ensure the captcha only applies to Card payment methods

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
We currently have a big First impression take over on the front that drives people directly to the digital subs landing page in UK and ROW (yay).
The issue is that there is a big, abrupt jump from the message on the banner, which is all about trust and support, and the landing page where it's very product-oriented.
As a quick fix we are going to adjust the language on the page header (the yellow thing below) to be "The digital subscription. Support The Guardian and enjoy two innovative apps and ad-free"
> Add 'Support The Guardian' to the digitalSubscriptionLandingHeader

- support-frontend/assets/components/contributionsReminder/__tests__/contributionsReminderTest.js
- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
- support-frontend/assets/components/contributionsReminder/contributionsReminderAutomation.js
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
New month.... now we don't need to update the postcontribution reminder every month!
This feature will automatically update the postcontribution reminder to give options 3, 6, 9, and 12 months out from the current month.
We are also ending the current test as we ran it long enough to have confidence the copy was not affecting outcomes, so we are ending it with individual preference for the longer, editorialised copy.
[**Trello Card**](https://trello.com/c/2BZWwUm3/1929-update-the-post-contribution-reminder)
> Turn off postcontribution reminder test and add feature to automate postcontribution reminder dates + tests

- support-frontend/assets/components/headers/header/header.jsx
- support-frontend/assets/components/headers/header/headerWithCountrySwitcher.jsx
- support-frontend/assets/components/subscriptionCheckouts/headerWrapper.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouExisting.jsx
- support-frontend/assets/pages/error/components/errorPage.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
- support-frontend/assets/pages/paypal-error/payPalError.jsx
- support-frontend/assets/pages/promotion-terms/promotionTerms.jsx
- support-frontend/stories/header.jsx
The header component needs a `countryGroupId` or the links it renders do not have the country in them and go via the geolocation endpoint. In DEV this results in /int/ urls which can be annoying.
However the `countryGroupId` was not required and so several pages including the paper landing page were not passing a value in meaning it defaulted to null.
This PR makes the prop required and passes in a value everywhere the component is used.
[**Trello Card**](https://trello.com/c/oDbZ8P9l/2944-fix-missing-countrygroupid-on-paper-landing-page)
> Make countryGroupId required on subs header

- support-models/src/test/scala/com/gu/support/workers/Fixtures.scala
- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
I'm moving the tests to point at the new test contacts in Salesforce Dev to reduce the Zuora sync issues.
[**Trello Card**](https://trello.com/c/iB6mlpSp/987-sub-sync-between-dev-zuora-and-dev-salesforce-working-reliably)
* Change 1
* Change 2
> Change fixtures to a new test account

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
- support-lambdas/stripe-intent/cfn.yaml
Inline the request to generate a SetupIntent token when the Contribute button is pressed.
Fraudsters are using the generated SetupIntent to do card testing.
> Inline the request to generate a SetupIntent token when the Contribute button is pressed

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouBlurb.jsx
We didn't see any significant difference (small, statistically insignificant changes only) in running the personalisation on the thank you page, but have a preference for the personalised option. 
Analysis can be found here: https://docs.google.com/spreadsheets/d/1e9rOENi_cFE8FyLpT7awdxakZU2SMer8scvTYIgZ6Qg/edit?usp=drive_web&ouid=106205001663870675496
[**Trello Card**](https://trello.com/c/4tjZkEER/1949-turn-off-the-ab-test-on-the-thank-you-page)
> Removed personalised thank you page test, defaulting to personalised variant

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
Victoria requested ~~to institute the old UI~~ to institute the blue choice cards to 100% of the audience until we are ready to test the full design system form
This PR removes choice cards from the UI for the time being
[**Trello Card**](https://trello.com/c/hlQECVG3/1938-remove-choice-cards-test-and-institute-pre-choice-card-ui-on-landing-page)
> Blue choice cards to 100% on landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
[**Trello Card**](https://trello.com/c/Pze5mYAc/1957-implement-an-amount-test-on-the-uk-landing-page)
Add an amounts test for higher and lower amounts in the UK only with the given scheme: 
* V1: 'lower'
* V2: 'higher'
> Add UK amounts test

- support-frontend/assets/components/subscriptionCheckouts/orderSummary/orderSummaryStyles.js
Fixing a problem in some browsers where the order summary image was getting stretched.
The issue was introduced in this PR: https://github.com/guardian/support-frontend/pull/2417
> Fix image issue in safari

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
We are seeing stripe set up failing because a function `elements` is missing from the stripe object, however there is a function called `_elements` which does seem to work so try calling this if `elements` is not available.
> cope with missing stripe.elements()

- support-frontend/assets/helpers/stripe.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
When the user clicks Contribute but has not completed the Stripe card form, it should block the action using the `formComplete` in the redux store.
This is currently broken because of some old logic from when the Stripe card form was first introduced (for one-offs only, as an a/b test)
> Fix Stripe form validation check

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/assets/components/subscriptionsProductDescription/subscriptionsProductDescription.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
- support-frontend/webpack.dev.js
We are introducing a new introductory offer for purchasers of monthly digital subscriptions.
[**Trello Card**](https://trello.com/c/5B4X1GVc/2960-digital-pack-new-monthly-offer)
* Change the default monthly promotion to 'one for one'
* The product card on digisub page was using the wrong field for promotional copy
* Flip the ordering of the promotion price and regular price on the showcase page so that the offer comes first
> New digisub monthly offer

- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
This is a change to the promised delivery time due to unprecedented demand for home delivery. It gives the providers a bit more time to get all those papers delivered.
[**Trello Card**](https://trello.com/c/EIfl3jde/2948-update-delivery-times-on-hd-checkout)
> HD: update 7am delivery time to 8am

- support-frontend/assets/components/forms/customFields/error.scss
- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.js
- support-frontend/assets/components/subscriptionCheckouts/submitFormErrorSummary.jsx
During the COVID-19 crisis, the customer service centre is getting a lot of calls, so we are removing the number from our postcode lookup form error.
[**Trello Card**](https://trello.com/c/YFxWjmc8/2953-remove-contact-centre-phone-number-from-error-message-update-error-copy)
> Update HD postcode delivery error - remove customer service phone number

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
we previously had an ophan event for when the token is ready. Also added an event for when our backend verifies it.
> Recaptcha result tracking

- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
The old api-gateway endpoint is about to be removed.
This changes it to use a new endpoint on the Play backend.
https://trello.com/c/1nR0l7gx/1947-improve-security-of-stripe-setup-intent-creation-1
> Change subscriptions to use the new Stripe Setup Intents endpoint

- project/build.properties
- support-models/build.sbt
We are using a vulnerable libthrift via acquisition event producer and thrift serialiser.
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHETHRIFT-474610
This PR bumps the library that bumps the library that pulls in the right code!
> bump event producer to get updated libthrift

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
We are removing the UK amounts test and will replace the default amount with the winning variant (higher amounts).
[**Trello Card**](https://trello.com/c/AEACCigx/1974-uk-default-amounts-test-make-the-higher-variant-the-default-and-remove-test)
* Remove ukAmountsTest
> Remove UK amounts test

- support-frontend/app/config/Configuration.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
- support-frontend/conf/CODE.public.conf
- support-frontend/conf/DEV.public.conf
- support-frontend/conf/PROD.public.conf
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
A follow up to [this PR](https://github.com/guardian/support-frontend/pull/2439) which changed the endpoint for creating Setup Intents.
Removes unused config, does not pass the path through from the controller, and shares the same value as the Contributions form (`routes.stripeSetupIntent`)
> Tidy up stripeSetupIntentEndpoint configuration in subs

- support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
The paper product page has been missing a terms and conditions section since the last flash sale finished, this PR adds it back in.
[**Trello Card**](https://trello.com/c/Bcmb1GRU/2908-tc-missing-from-print-landing-page-footer)
> Add t&cs to print page

- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/stripe.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
We want to see if the Payment Request Button really is worth using or not. It may be that its presence is a net detractor. Apple Pay remains fully rolled out if it's available on the browser.
* This change sets up a new A/B test for the Payment Request Button across both checkouts. To simplify things, it also fully enables the SCA variant of the Payment Request Button as that variant is performing equally as well as the non-SCA version.
> New A/B test for Payment Request Button

- support-frontend/assets/components/forms/customFields/error.jsx
This is a fix for an error introduced by a previous PR: https://github.com/guardian/support-frontend/pull/2434
[**Trello Card**](https://trello.com/c/u9mWQrXG/2967-postcode-lookup-error-message-broken-arising-from-the-change-to-the-message-for-the-error-summary)
> Fix broken error message in postcode lookup

- support-frontend/app/controllers/StripeController.scala
- support-frontend/app/wiring/Controllers.scala
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricPut.scala
Adding a CloudWatch metric to track the number of requests to the setup intent endpoints. Also added a tiny bit of validation to the recaptcha version to ensure the client actually passes a token value.
So we can see the volume of traffic using these endpoints.
[**Trello Card**](https://trello.com/c/1nR0l7gx)
> Adding a CloudWatch metric to track the number of requests to the setup intent endpoints

- support-frontend/app/controllers/StripeController.scala
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
- support-frontend/conf/routes
We are putting the setup intent creation behind auth on subs to protect the endpoint from being exploited.
[**Trello Card**](https://trello.com/c/bpGeqnyZ/1970-improve-security-of-stripe-setup-intent-creation-follow-up)
> Moving subscriptions to a new stripe intent endpoint behind auth

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.scss
[**Trello Card**](https://trello.com/c/FGxNlXZd/1967-add-patrons-to-the-tcs-on-recurring-only)
* Add patron info to T&Cs on recurring
> Add patron info after T&Cs

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
URL fix requested by Victoria Raspaldo
* Changes URL in patrons "Find out more today" link to include additional tracking params
N/A
> update patrons "Find out more today" url in T&Cs

- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
Temporary fix for post deploy tests by not making them need to go through recaptcha
> Jg post deploy

- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
We have some special handling for Apple Pay one-off contributions so no token required, see https://github.com/guardian/payment-api/pull/195
> Fix Apple Pay for single contributions

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/services/PayPalNvpService.scala
- support-frontend/build.sbt
Snyk is reporting a vulnerability in spray-json, a dependency of scala-uri:
`com.netaporter:scala-uri_2.12@0.4.16 › io.spray:spray-json_2.12@1.3.2`
Newer versions of scala-uri do not depend on spray-json.
> Update scala-uri dependency

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/app/controllers/StripeController.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/components/checkoutForm/checkoutForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/recaptcha.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.scss
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/helpers/subscriptionsForms/formFields.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
- support-frontend/conf/routes
- support-frontend/test/controllers/SubscriptionsTest.scala
Since adding recaptcha to contributions the card testers have moved to the subscriptions endpoint. 
This PR adds the google recaptcha to subs checkout (see below) and deprecates the authorised endpoint on the backend.
> Adding recaptcha to Subscription Endpoint & deprecating authorised endpoint

- support-workers/cloud-formation/src/templates/cfn-template.yaml
**Current situation**: An alarm shoots if there are no new digipack subscriptions in the last 12h.
**Potential problem**: An error in the morning would fire an alarm only in the evening.
**Why is the change possible**: New traffic pattern seems to suggest it is reasonable to expect new digipack subscriptions in a shorter period of time (see screenshot below for data of last week, one data point per hour).
**Proposed change**: Reduce evaluation period of alarm to 3h.
**Expected benefit**: An error in the morning can be caught within the same day.
[Link to AWS metric used for screenshot
](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2:graph=~(metrics~(~(~(id~'e1~expression~'SUM*28*5bFILL*28m1*2c0*29*2cFILL*28m2*2c0*29*2cFILL*28m3*2c0*29*5d*29~label~'AllDi …
> Reduce period of no digipack alarm from 12 to 3h

- support-frontend/assets/components/recaptcha/recaptcha.jsx
Make the recaptcha policy links open a new tab instead of replacing the checkout and the user losing their card details if they click on one of them. 
[**Trello Card**](https://trello.com/c/3f9Kn7ls)
No change.
> Make the recaptcha policy links open a new tab

- support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
Direct Debit is currently broken
> Remove Direct Debit from payment methods

- support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
Reverts guardian/support-frontend#2471
Direct debit is working, it was an issue at gocardless, @paulbrown1982 has tested and it's working okay for recurring contributions.  So enable for subs.
> reinstate Direct Debit to subs payment methods

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
UI bug:
1 complete recaptcha on recurring
2 switch to single
3 enter card details but do not complete recaptcha
4 click Contribute
It correctly does not try to create the payment, but it also doesn't display
an error message to the user
https://trello.com/c/u2P8tZLJ/2002-recaptcha-fix-edge-case
> Recaptcha error message does not always display

- support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/hero.jsx
The digital subscriptions image was changed on the showcase page, when this change was made it had different dimensions to the previous image, because this image also appeared on the thank you page the dimensions needed to be changed on the thank you page, unfortunately they were missed, which resulted in the image link being broken on the thank you page
This PR updates those dimensions and fixes the broken image
[**Trello Card**](https://trello.com/c/QUO8RmZI/3000-thank-you-page-image-for-digi-subs-broken)
* Changed image dimensions
> fix: hero image on thank-you page

- support-frontend/assets/components/svgs/dropdownArrow.jsx
This error shows in the console 
```
Error: <svg> attribute preserveAspectRatio: Unrecognized enumerated value, "true".
```
This appears because preserveAspectRatio has no attribute for one of the svg's which preact defaults to true as though it is a jsx parameter
This PR adds a default attribute
* Add a default attribute to preserveAspectRatio
> fix: remove svg error

- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
100% discounts are currently rendering incorrectly on the site. This is because 
of a boolean check we do to see whether there is a promotional price or not:
```javascript
const promotionalPrice = promotion && promotion.discountedPrice ? promotion.discountedPrice : null;
```
for a 100% discount `promotion.discountedPrice` 0 and so is falsey meaning we end up with no promotion applied. 
[**Trello Card**](https://trello.com/c/vC7yyXnz/3002-fix-100-discounts)
> Fix the check for discounted prices to take account of 0

- .travis.yml
`travis_retry` does not take an argument, so manually triggering a build in travis fails. This could be fixed by removing the argument, but actually I think the desired behaviour is for builds triggered by prout and builds triggered manually to run the exact same command. See #2409
> Synchronise travis and prout

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
We have had several failed checkouts recently caused by a user entering either a city name or delivery instructions which are too long and cause validation errors in Salesforce. 
This PR adds a `maxlength` attribute to both of those fields.
[**Trello Card**](https://trello.com/c/SvZwZrTB/2936-billing-city-delivery-instructions-length-restrictions)
> Extra validation

- support-frontend/assets/helpers/abTests/abtest.js
**WIP**
The aim is to indicate in Ophan/Data Lake whether a request was served locally in Frontend or by a remote epic (from the new Contributions Service).
This is a temporary solution while we validate and migrate the Contributions Service, at which point it will no longer be needed.
https://trello.com/c/VLxYd8go/115-full-variants-test-only-on-frontend
To do this, we pass an `isRemote` flag in the query param and then convert that into a fake `ContributionsService` test.
> Introduce artificial ContributionsService test

- support-frontend/assets/components/subscriptionCheckouts/cancellationPolicy.jsx
- support-frontend/assets/components/subscriptionCheckouts/paymentTerms.jsx
The cancellation policy should not show on gifting this commit fixes that
* hide cancellation policy on gifting
* Change 2
> fix: fix the cancellation policy showing on gifting

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
Replaces contact mailto address in USA philanthropic ask. Now uses "us.philanthropy@theguardian.com".
> replaces contact mailto address in philanthropic ask

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/app/controllers/StripeController.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
We want to be able to disable recaptcha quickly in order to reduce dependency on external partners.
This change allows us to have a feature switch to disable recaptcha when necessary.
https://trello.com/c/uaO1tOSE/2012-add-recaptcha-feature-switch-in-the-support-admin-console
https://github.com/guardian/support-admin-console/pull/117
https://github.com/guardian/payment-api/pull/200
Note both switches must be on for recaptcha to work correctly! The backend should always be turned off first to allow any in flight users through the system.
> Recaptcha Feature Switch

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
We do not want to show the security checkbox copy when recaptcha is disabled.
OLD (Showing copy even though recaptcha is hidden)
NEW - disabled (Copy is hidden too)
Enabled - copy is displayed
> hide copy for recaptcha when disabled

- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/main/scala/com/gu/support/workers/PreviewPaymentSchedule.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/PreviewPaymentScheduleSpec.scala
We have two issues with the thank you email at the moment:
Because the payment schedule we get back from Zuora uses doubles for the price, sometimes we get rounding issues where a charge will be £52.9900000001 per month for the first few months and then £52.99 thereafter. 
This then causes the code which generates the pricing copy in the email to conclude that the first price is an introductory period and come up with the copy "£52.99 for 4 months, then £52.99 every month". To fix this we just need to round the charge amount to 2 decimal places.
The wording of the pricing summary is ambiguous even without the previous bug: "£5.99 for 3 months, then £11.99 every month" could be taken to mean that £5.99 is the total price for the first 3 months. To fix this the copy should read "£5.99 every …
> Fix thank you email wording

- support-models/build.sbt
to get the latest ophan models, for APPLE_NEWS and GOOGLE_AMP as acquisition sources
https://github.com/guardian/acquisition-event-producer/pull/60
> Bump acquisition-event-producer to 4.0.27

- support-frontend/assets/components/content/content.scss
- support-frontend/assets/components/subscriptionCheckouts/directDebitTerms.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalPaymentTerms.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/endSummary/endSummaryMobile.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/endSummary/endSummaryStyles.js
This is picking up some aspects of the end summary and other mobile design tweaks that were previously missed.
[**Trello Card**](https://trello.com/c/HMDFH839/3026-review-design-of-end-summary-mobile-direct-debit)
* Grey background for end summary and direct debit terms
* Shorter top border for dd terms
* Font size for dd terms 
* Fix bullet dot colour in end summary
> End summary mobile design tweaks

- support-models/build.sbt
Despite us setting a Jackson version of 2.10.1 in most of the projects within support-frontend, this wasn't actually being used (I tested this by by running `sbt evicted`).
Forcing support-models to use version 2.10.1 fixes the issue.
> Make support-models use v 2.10.1 of Jackson

- support-models/build.sbt
Forcing the app to use a newer version of `jackson-datatype-jsr310` to fix a [security vulnerability](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATATYPE-173759)
> Version bump for jackson-datatype-jsr310

- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/zuora/ProductSubscriptionBuildersSpec.scala
This is a hangover from when we were releasing GW gifting, it is no longer needed
> Remove the unused `allowFixedTermSubs` flag

- support-frontend/assets/pages/digital-subscription-checkout/components/orderSummary/orderSummaryStyles.js
This corrects some outstanding issues with the order summary for the digital checkout, mostly relating to the mobile view.
[**Trello Card**](https://trello.com/c/tHNFw8NC/2978-top-order-summary-design-tweaks)
* Add a line at the top of the order summary
* Fix the price info text font
* Add a drop shadow to the box 
* Fix the background colour in the image container
* Reduce space between content and bottom of box (where drop shadow is)
> Order summary mobile: design review changes

- support-frontend/app/controllers/PaperSubscription.scala
- support-models/src/main/scala/com/gu/support/promotions/PromoError.scala
- support-services/src/main/scala/com/gu/support/promotions/ProductPromotionCopy.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionTerms.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/ServicesFixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ProductSubscriptionBuildersSpec.scala
As part of the one for one retro we wanted to prevent duplicate promo codes from being used.  This PR is a quick fix to block anyone from subscribing if the code is on muliple promotions.
It also fails on any other promo error rather than continue without.
[**Trello Card**](https://trello.com/c/BHWF8wW3/3056-enforce-promo-code-uniqueness-in-support-workers)
support workers will fail with the following:
```
{
"error": "com.gu.support.workers.exceptions.RetryNone",
"cause": {
"errorMessage": "DuplicateCode(PromotionWithCode(DUPLICATED,Promotion(duplicate1,duplicate promo code for testing,AppliesTo(Set(2c92c0f855c9f4b20155d9f1d3d4512a),Set(Country(GB,United Kingdom,Map()))),C_KA8K8Z0X,Map(Channel 0 -> Set(DUPLICATED)),2020-05-15T00:00:00.000+01:00,None,Some(DiscountBenefit(10.0,Some(P2M))),No …
```
> Prevent duplicated promocodes being used

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
Our trial period with Loqate has finished and the test was inconclusive so we are turning it off.
> Switch off Loqate test

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
Replaces `<hr>` tag with the correct `<br>` tag on contributions landing page
> replaces <hr> with correct <br> tag on landing page

- build.sbt
- project/LibraryVersions.scala
- support-frontend/build.sbt
- support-models/build.sbt
- support-workers/build.sbt
See https://github.com/guardian/acquisition-event-producer/pull/62
[**Trello Card**](https://trello.com/c/PXslLgrv/3060-split-up-acquisition-event-producer-to-reduce-jar-sizes)
> use separated event model/event client

- support-models/version.sbt
This gives us APPLE_NEWS and GOOGLE_AMP as sources
https://github.com/guardian/support-frontend/pull/2496
> bump models version

- build.sbt
- support-redemptiondb/build.sbt
- support-redemptiondb/cfn.yaml
- support-redemptiondb/riff-raff.yaml
For various forms of redemption e.g. gifting/corporate we want a db to store the codes so we can keep track of which codes exist (and possibly other data such as which product and how many licences in total.
The tables have the code as the primary key, and can have further data as needed, probably total available redemptions, and possibly a cache of active code usage from zuora (so we can still check whether any codes are available independently of zuora being up)
[**Trello Card**](https://trello.com/c/lZcb6e4F/3049-create-data-store-for-corporate-codes)
> Redemption code db tables

- support-frontend/assets/components/content/content.scss
- support-frontend/assets/components/footer/footer.scss
- support-frontend/assets/components/subscriptionFaq/subscriptionFaq.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/components/faqsAndHelp.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.scss
This fixes some small issues with the indentation of a shared FAQs section in the digital subscriptions landing page and checkout, and reinstates general terms and conditions and privacy info on the landing page.
I've also fixed the incorrect text wrapping mentioned in the footer audit (see link in [trello card](https://trello.com/c/W784hkRq/2979-fix-position-of-faqs-on-desktop-for-product-and-checkout-pages-add-back-tc-privacy-copy-digital)).
* Fix broken indentation on DS landing page
* Add general T&Cs and privacy info on DS landing page
* Fix text wrap in print landing page footer
> Fix indent of faqs and reinstate terms on DS landing page

- support-frontend/cloud-formation/cfn.yaml
- support-frontend/conf/logback.xml
The cloudwatch logs don't have the millis part, so often sometimes the log messages are out of order.  Seems cloudwatch can mostly make sense of the timestamp apart from that, and assumes UTC.
This PR makes sure it's all explicit including the millis.
> get milliseconds into cloudwatch logs

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.js
- support-frontend/assets/helpers/abTests/abtest.js
This is a fix for https://github.com/guardian/support-frontend/pull/2480.
The actual query param (once JSONified) looks like:
`{..."isRemote":true}`
> Fix isRemote handling - is a boolean

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/main.scala.html
- support-frontend/public/robots.txt
The tweet site preview was broken due to some changes in the way twitter works.
https://trello.com/c/7bR9ExNI/2088-enable-displaying-the-guardian-image-when-sharing-https-supporttheguardiancom-contribute-page-on-twitter
* Image loaded from i.guim domain as this is accessible for twitter bots to read from
* Using large format card
> Twitter Preview Card

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
This follows from this PR https://github.com/guardian/support-frontend/pull/2515. The design system style error was rendering on the control as well as the DS variant. This fixes that.
* Add function to render DS error on variant
* Revert function for control to original error style
> Fix ui bug on landing page recapcha error

- support-frontend/Brewfile.lock.json
- support-frontend/assets/components/page/page.jsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/yarn.lock
This PR sets-up an A/B test for use during the Aus moment. The variant shows Aus moment colours on the background of the contribs landing page. Please see [this Trello card](https://trello.com/c/xxSSnIp8) for more details.
**Tablet**
<br>
**13" Laptop**
<br>
*Top*
<br>
*Bottom*
> Mj landing page aus moment ab test

- support-frontend/Brewfile.lock.json
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/components/spreadTheWord/ausMomentSpreadTheWord.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
Adds Aus moment styling and copy to post-contribution thank you page, as per [this Trello card](https://trello.com/c/UET0gZue). See screenshots below.
This PR also introduces a switch to enable toggling all Aus moment features on/off from the admin console.
<br>
<h2>Tablet</h2>
<br>
<h2>13" Laptop</h2>
<strong>Top</strong>
<br>
<strong>Bottom</strong>
> Mj aus moment thank you page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
A tiny change to automatically tie the on/off state of the Aus moment landing page A/B test to the state of the master switch for the moment.
> aus moment landing page ab test is active if ausMomentEnabled

- support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/components/form.jsx
- support-frontend/assets/components/forms/customFields/error.jsx
- support-frontend/assets/components/forms/customFields/validated.jsx
- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.jsx
- support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.jsx
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeFinderStore.js
- support-frontend/assets/components/subscriptionCheckouts/addressSearch/addressComponentStore.jsx
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/components/subscriptionCheckouts/personalDetails.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/submitFormErrorSummary.jsx
- support-frontend/assets/helpers/subscriptionsForms/validation.js
- support-frontend/assets/hocs/withValidation.jsx
- support-frontend/assets/pages/subscriptions-redemption/components/redemptionForm.jsx
This PR change the `error` component used on the subs checkouts to use the `InlineError` component from [Source](https://github.com/guardian/source) which provides us with the correct icon and styling.
It also moves the error message above the form field with the error in line with design system guidelines.
Finally I have refactored to remove the 'Temporary Covid message' hack which we had in place.
> Error tidy up

- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
This PR updates the "Premium App" copy on subscriptions landing page, as requested: https://trello.com/c/hvGtnhya/3099-update-premium-app-reference-copy-on-showcase-pag
> Update "Premium App" copy on subscriptions landing page

- support-frontend/app/controllers/DigitalSubscriptionController.scala
- support-frontend/app/controllers/Promotions.scala
- support-frontend/app/controllers/RedemptionController.scala
- support-frontend/app/controllers/UserDigitalSubscription.scala
- support-frontend/app/services/MembersDataService.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/helpers/errorReasons.js
- support-frontend/assets/pages/subscriptions-redemption/api.js
- support-frontend/assets/pages/subscriptions-redemption/components/stage.jsx
- support-frontend/assets/pages/subscriptions-redemption/subscriptionsRedemptionReducer.js
- support-frontend/conf/routes
- support-frontend/test/controllers/SubscriptionsTest.scala
We want to prevent users who already have a live Digital Subscription from also signing up for a corporate subscription. 
This PR takes the same approach as a regular digisub which is to redirect the user to this page:
We may want to do something more tailored to redemptions at some point but this is what we have agreed on for the proof of concept.
[**Trello Card**](https://trello.com/c/DH2PVZ9U/3097-handle-users-with-existing-digital-subscriptions)
> Prevent users with an existing Digital Subscription signing up for a corporate subscription

- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/zuora/ProductSubscriptionBuildersSpec.scala
The subscription builders are using implicit classes and traits which adds boilerplate and difficulty in navigating outside of an IDE.  This PR turns them into normal functions, and injects the date rather than depending on it directly, to make the code more testable.
precursor to https://github.com/guardian/support-frontend/pull/2526
> make product subscription builders into normal functions

- support-frontend/package.json
- support-frontend/scripts/orphans.js
- support-frontend/webpack.common.js
- support-frontend/webpack.entryPoints.js
- support-frontend/webpack.ssr.js
- support-frontend/yarn.lock
Whilst working on the repo I've come across some modules which are present in the code, but aren't dependencies of any other modules (and they also aren't entry points for the generated bundles). They were probably depended upon once but are no longer in use now. 
It's not great developer experience to keep these in the codebase as these modules create additional noise when searching through the code, and developers then have to spend time working out if and how they're used. It also leaves us maintaining redundant code.
I've therefore written a little script using the follow NPM module https://www.npmjs.com/package/madge
`madge` is a developer tool that traverses a dependency tree and can do neat things like produce a dependency map, identify circular dependencies and [identify orphan …
> Script for identifying "orphan" .js/.jsx/.scss modules

- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
[This Identity PR](https://github.com/guardian/identity-frontend/pull/593) has broken the subscriptions checkout post-deployment tests because it introduces a captcha into the register flow. Discussions are ongoing about how to resolve this but in the meantime we should prevent the failing tests from running as it is just creating noise.
> Ignore subs checkouts selenium tests

- support-frontend/app/controllers/Application.scala
The OG image will be displayed to users in Australia during the Aus moment. The image will be displayed in social share links.
Australia during Aus moment
Rest of world/original image
[**Trello Card**](https://trello.com/c/AilQGrjm/2114-update-the-ogimage-on-the-aus-thank-youpage)
> Add og:image for Aus moment

- support-workers/src/main/scala/com/gu/support/workers/GetSubscriptionWithCurrentRequestId.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraService.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraSpec.scala
We noticed that joda and java time were mixed in the same codebase.
It makes sense to be consistent.
It would be slightly better to choose java time, as joda time has been superseded from java 8, but that would be a health task for another day.
There are two other places we use java time `ofDays`, but they are to call the test users library
https://github.com/guardian/support-frontend/blob/9cf8941e823860e17f409a1d12577ce7aa770fb4/support-frontend/test/selenium/util/PostDeployTestUser.scala#L15
https://github.com/guardian/support-frontend/blob/f00be2f4a2a495fb87025e34476125357e71984e/support-frontend/app/services/TestUserService.scala#L13
calling this function
https://github.com/guardian/identity-test-users/blob/461286656b7443b8b0e43e10b89426b68138f756/src/main/scala/com/gu/identity/testing …
> use joda time most places for consistency

- support-frontend/app/controllers/Application.scala
We don't think the crawler geo-ip will resolve correctly. 
We decided to use the moment OG image for all users for the duration of the moment.
[**Trello Card**](https://trello.com/c/AilQGrjm/2114-update-the-ogimage-on-the-aus-thank-youpage)
> removing geo check for og image

- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/helpers/tracking/acquisitions.js
We can configure campaign-specific landing pages.
This is done by matching on the path of the url, and in the upcoming moment this will be /au/contribute.
In the past, the `campaignCode` has been set based on the path. Instead, we want to configure the `campaignCode` - in this case it is `Aus_moment_2020`.
Also, the campaign is now enabled based on the `ausMomentEnabled` switch, so no need for commented out code!
Redux store now has correct campaignCode:
> Use correct campaignCode during Aus campaign, use switch

- support-frontend/scripts/orphans.js
It looks like https://www.npmjs.com/package/madge has trouble recognising imports in `.scss` files with a tilde such as `@import ~stylesheets/gu-sass/gu-sass` so any `.scss` file imported this way is being reported as an orphan. 
I'm therefore temporarily stopping `orphans.js` reporting `.scss` orphans until we have the time to look at this.
> Temporarily stop reporting .scss orphans

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
The variant is doing at least as well as the control.
In this change I am simply removing the control. We will remove the test and clean up the old code soon, when we have more time!
> Remove control variant from landing page DS test

- build.sbt
There's an annoying issue where when you run the tests, a load of extra output appears after the tests finish, meaning you have to scroll up to see if they are finished and whether anything went wrong.
This is caused by a bug in SBT https://github.com/sbt/sbt/issues/5245 which somehow loses events after an async ignored/excluded test.  It doesn't look like it is going to be fixed soon.
Adding the -eU parameter makes the tests output raw events as they are produced rather than the nicer looking ones grouped by test.  The reason some of the messages are delayed is because it is waiting for the previos test to "finish" before starting output for the next one.  Eventually it gives up waiting and spits it out anyway.
The test output is a bit less friendly, now it looks more like a sequence of …
> display raw output from test runs

- support-services/src/test/scala/com/gu/support/redemption/SetCodeStatusITSpec.scala
- support-workers/src/main/scala/com/gu/support/workers/GetSubscriptionWithCurrentRequestId.scala
- support-workers/src/main/scala/com/gu/support/workers/PreviewPaymentSchedule.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraService.scala
- support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
This PR adds a more comprehensive test for the create zuora subscription logic, this is in preparation for adding a test that checks the redemption code is correctly marked as used, which would not be possible otherwise without being an IT test.
> add test for CreateZuoraSubscription digipack

- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
Part of corporate subs, we want to make sure once the subscription is created, we mark the code as successfully redeemed.
If there is a failure marking the sub as redeemed, the step will fail and retry, the repeat execution will check the code again and find it's not redeemed, but it should find the existing sub, skipSubscribe, and then successfully mark as redeemed on the retry hopefully.
[**Trello Card**](https://trello.com/c/YHcNJ2yF/3105-mark-corporate-codes-as-redeemed-when-checkout-done)
> mark redemption code as redeemed after sub created

- support-frontend/Brewfile.lock.json
- support-frontend/assets/components/socialShare/socialShare.jsx
<p>This PR updates the pre-populated social share copy, for email and Twitter, coming from the AU thank you page.</p>
<p>We are unable to do this for Facebook or LinkedIn, due to constraints from those platforms.</p>
<p>Please see screenshots below for a demo of how the copy will appear.</p>
<br>
<h2>Twitter</h2>
<br>
<h2>Email (GMail)</h2>
> Mj update aus moment social sharing copy

- support-frontend/assets/components/subscriptionCheckouts/layout.jsx
- support-frontend/assets/components/subscriptionCheckouts/layout.module.scss
I noticed that #2547 introduced a bug where the aside would show on the wrong side of the form in desktop layouts:
This PR fixes it:
I also noticed that the `CheckoutLayout` control is never used without an `aside` so I've made it non-optional as it simplifies the code.
> Fix layout issue in redemption form

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouBlurb.jsx
If the name is really long the container stretches and breaks the design.
[**Trello Card**](https://trello.com/c/bOT4eZUN/2086-fix-thank-you-page-width-error)
> check firstname length

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/subscriptionsForms/formValidation.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
We want to test removing the address fields from Digital Subscriptions to see if it results in an increase in conversion.
Note that this PR removes server side validation of address fields for all digisub checkouts. I think this is acceptable as we are happy to accept subs without an address for those in the 'no address' variant, so it is not a disaster if somehow those in the other variant manage to submit a purchase without a valid address.
[**Trello Card**](https://trello.com/c/x0iBur2v/3090-ab-test-does-removing-address-fields-from-ds-checkout-increase-conversion-rate)
> Ds remove address test

- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
Since the change to DS selenium no longer finds the paypal radio.
```
[info]   Scenario: Check browser navigates to paypal *** FAILED ***
[info]   selenium.util.Browser$MissingPageElementException: Could not find WebElement with locator: .form__radio-group-label[for='paymentMethodSelector-PayPal']
[info]   at selenium.util.Browser.clickOn(Browser.scala:54)
[info]   at selenium.util.Browser.clickOn$(Browser.scala:50)
[info]   at selenium.contributions.pages.ContributionsLanding.clickOn(ContributionsLanding.scala:7)
[info]   at selenium.contributions.pages.ContributionsLanding.selectPayPalPayment(ContributionsLanding.scala:88)
[info]   at selenium.contributions.OneOffContributionsSpec.$anonfun$new$5(OneOffContributionsSpec.scala:102)
[info]   at …
```
> fix for failing test

- support-frontend/assets/pages/paper-subscription-landing/components/hero/campaignHeaderStyles.js
The [print landing page hero refresh](https://github.com/guardian/support-frontend/pull/2570) had a font issue with the roundel. It should have looked like this:
But unfortunately in many cases it was looking like this:
It turns out that the issue was with some css that is supposed to align numbers to a baseline (so they all line up neatly and don't make the spacing ragged). This css prop only works if you are explicitly loading full subset of fonts, which would be around another ~20KB+, and we would prefer not to do this.
The solution was to remove this css and make the alignment work with a more ragged numerical line of text so the visual is consistent.
The PR that introduced this issue is this one: https://github.com/guardian/support-frontend/pull/2570
[**Trello …
> Fix overlapping styles on roundel

- build.sbt
So far we have been using a pre-release version of scalatest.  Now that it's officially released, we should use the proper version.
There is a bug in all versions back to 3.0 at least which there is a PR open to fix it at scalatest repo. I have left a note in our build.sbt to remove our workaround - https://github.com/guardian/support-frontend/pull/2555 - when that is released, perhaps in 3.2.1.
> use released version of scalatest

- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.jsx
- support-frontend/assets/pages/subscriptions-redemption/subscriptionsRedemption.jsx
The digi sub thank you page survey is designed for people who have made a purchase decision, not for corporate recipients.
This PR removes the digi sub survey from anyone who hasn't paid for their subscription at checkout time.
[**Trello Card**](https://trello.com/c/3JbmYsrN/3157-remove-survey-link-from-corporate-thank-you-page)
Tested in DEV on the thankyou, thankyou-pending (not present) and the normal paid thankyou (present)
> remove survey from corp subs thank you pages

- support-frontend/cloud-formation/cfn.yaml
- support-redemptiondb/cfn.yaml
- support-services/src/main/scala/com/gu/support/redemption/RedemptionTable.scala
- support-workers/cloud-formation/src/templates/cfn-template.yaml
We called the redemption tables redemption-codes-((tpstage))-((gustage))
This got a bit silly with redemption-codes-PROD-PROD
So this PR takes out the stage if it's gu:PROD
[**Trello Card**](https://trello.com/c/02NsmWw6/3081-update-redemption-tables-to-not-have-a-code-prod-stage)
When we ship this, we need to manually deploy the tables with riffraff.
Support frontend/workers will be temporarily not working for corporate subs in between the deploys.
The IT tests are broken in this branch until the tables are updated in gu:PROD (as we use the gu:PROD tp:DEV table for the tests)
> don't use PROD in the name of the Redemption tables

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionState.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
We have finished the A/B test for the Design System in the contributions landing page.
The old 'control' rendering can now be removed.
This is tidying up https://github.com/guardian/support-frontend/pull/2515/files
> Remove non-DS rendering of landing page

- support-logs/cfn.yaml
I noticed kibana was always very slow to load on my home internet connection.
This was because there were large JS files that were not gzipped or cacheable that had to be downloaded in full every time.
I checked the main logs.gutools and it doesn't have that issue.
After debugging,I found that the headers were changing before/after nginx, even with gzip disabled in both cases
```
DIRECT
< Content-Length: 11977436
< ETag: "29b3d390d27baf451de74e83a0a9a2e79c56ddf4-/_plugin/kibana/built_assets/dlls/"
VIA NGINX
< Server: nginx/1.10.3 (Ubuntu)
< Transfer-Encoding: chunked
```
and then checking the nginx config, there were lines in there to remove the encoding and cache headers, which I tried removing temporarily, and everything still seemed to work fine.
After checking with AWS support, it …
> remove gzip/substitution parameters from support-logs nginx

- support-frontend/.snyk
- support-frontend/yarn.lock
To fix various dependencies in our js dependencies
```
Tested 348 dependencies for known issues, found 10 issues, 26 vulnerable paths.
Patchable issues:
Patch available for lodash@4.17.10
✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-567746] in lodash@4.17.10
introduced by @emotion/babel-preset-css-prop@10.0.27 > babel-plugin-emotion@10.0.27 > @babel/helper-module-imports@7.0.0 > @babel/types@7.0.0 > lodash@4.17.10 and 8 other path(s)
Issues with no direct upgrade or patch:
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ACORN-559469] in acorn@6.3.0
introduced by webpack-bundle-analyzer@3.6.0 > acorn@6.3.0
This issue was fixed in versions: 5.7.4, 6.4.1, 7.1.1
✗ Prototype Pollution [Medium …
```
> Upgrade dependencies with vulnerabilities

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
Compares the current control amounts (configured from the tool) with a variant
> Aus moment amounts test

- support-services/src/test/scala/com/gu/support/redemption/DynamoTableAsyncITSpec.scala
- support-services/src/test/scala/com/gu/support/redemption/IT_testdata.sh
Having update the dynamo tables in https://github.com/guardian/support-frontend/pull/2581
the tables were wiped by being renamed/recreated.
I had to put back all the DEV data again, but it was all created manually.  SO I wrote a quick script to do so in a repeatable way.
I also found an inconsistency in the test data which I fixed in the test.
> tweak Redemption DB IT test and add test data scipt

- support-frontend/assets/helpers/subscriptions.js
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
1) Premium app prices in non-uk countries are out of date (due to app stores changing prices when the exchange rate changes)
2) In EU, Canada, and NZ, the price is not shown, instead a '7 day free trial' message is shown. 
1) remove price from all regions
2) only show trial offer in all regions . ie: '7 day free trial' 
No prices, and only 7 day free trial offer
[**Trello Card**](https://trello.com/c/9959HmKl/3116-update-showcase-page-remove-prices-only-show-trial-offer-consistent-in-all-regions)
> Remove live app price

- support-frontend/assets/helpers/subscriptionsForms/formActions.js
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
Since we moved to using Stripe elements inline we have been initialising the country with the standard internationalisation country from `state.common.internationalisation.countryId`. 
For Guardian Weekly however, we should be using the billing country as this can be different from the internationalisation country and is needed to work out the correct Stripe account to use.
[**Trello Card**](https://trello.com/c/Z5cL7KSf/3177-gw-gifts-sometimes-use-wrong-stripe-account-client-side)
> Stripe country problem

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
When I was fixing the GW country selection error (#2613) I noticed that there is no `GeneralErrorMessage` component on either of the GW checkouts which means that if there is a support-workers failure the user doesn't see an error message but is just dumped back on the checkout with no indication of what went wrong.
This PR adds 
[**Trello Card**](https://trello.com/c/I2faV0m9/3182-guardian-weekly-checkout-has-no-error-summary)
**The checkout now has an error message**
> Add `GeneralErrorMessage` component to GW checkouts

- support-frontend/assets/pages/showcase/showcase.scss
From the tablet breakpoint to screens about 1700px wide, the image in the 'Subscribe' CTA overlaps the text and cuts it off to varying degrees
[**Trello Card**](https://trello.com/c/Pay20ZIg)
* Added a max-width rule for the text in the CTA. I experimented with a couple of other approaches but they all required much more significant overriding of the Content component CSS or creating new components; this was the simplest fix.
**Tablet - Vertical**
**Tablet - Horizontal**
**Mobile (large) - Horizontal**
**Desktop**
> Fix image overlapping text in subscription CTA

- support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
This PR makes paper voucher use the new subscription card email identifier once the switch has been turned on.
Depends on https://github.com/guardian/membership-workflow/pull/266
[**Trello Card**](https://trello.com/c/pEUPHrCF/3171-print-thank-you-email-for-imovo-subs-card)
This means that once the switch is on we will send the new email, meaning that new customers will get information about the subscription card rather than about the old paper voucher.
I will test by shipping the workflow change and then run this PR in DEV with the switch turned on, or at least an if statement
> use new email identifier for imovo thank you email

- support-frontend/assets/helpers/productPrice/fulfilmentOptions.js
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
When the user is buying a digital voucher we have different copy for the 'What's next' bullet points and will no longer show the date the vouchers are valid from.
[**Trello Card**](https://trello.com/c/Bp69nPoG)
* Added the new copy behind the existing useDigitalVoucher switch
* Removed the date if the fulfilment type is collection and useDigitalVoucher is true
**Paper voucher thank you page**
**Digital voucher thank you page**
> Adding new copy for digital voucher thank you page

- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/build.sbt
Update Jackson Databind and Dataformat cbor wherever the AWS S3 SDK is pulled in. Specifically in `it-test-runner` and `stripe-intent`. 
https://github.com/guardian/support-frontend/pull/2627 did not quite cover all scenarios as not all projects overrode Jackson from the AWS SDK.
I copied the `assemblyMergeStrategy` from `stripe-intent` over into `it-test-runner` due to issue with assembling the artifact for RiffRaff.
> Update Jackson Databind wherever the AWS S3 SDK is pulled in

- support-frontend/package.json
- support-frontend/yarn.lock
* lodash issue: https://app.snyk.io/vuln/SNYK-JS-LODASH-567746
* marked issue: https://app.snyk.io/vuln/SNYK-JS-MARKED-584281 
The marked issue requires a major version change, but there are no breaking changes that will affect our usage of it (it's only used in one place, to format additional promotion copy on the Weekly subscription landing page).
> Updating lodash and marked for Snyk issues

- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/main.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
#2308  Why are you doing this?
The Stripe SDK is only needed on the subs and contributions checkout pages, so moving it out of @main.
[**Trello Card**](https://trello.com/c/UC1I10FB)
> Stripe is only needed on the subs and contributions checkout pages

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/subscriptionsForms/formValidation.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
We are finishing the Digital Subscription address test. There is no significant difference in conversion rate between the control and the 'no address' version so we are reverting to the control.
[**Trello Card**](https://trello.com/c/LNJ6clbg/3160-turn-off-ab-test-for-no-address)
> Remove ds address test

- support-workers/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
These two tests are failing and are going to fail until we clean up salesforce data ideally on a regular schedule.
We have a [card to do the proper fix](https://trello.com/c/LKwe8ApH/3241-auto-clean-it-test-data-from-sf-dev), but until then we are ignoring these tests to avoid noisy results.
> Ignore salesforce IT tests which fail due to DEV quota limits

- support-lambdas/it-test-runner/cfn.yaml
The IT tests are putting too many records into SF dev, until this is resolved we will make them run daily instead of hourly
[**Trello Card**](https://trello.com/c/LKwe8ApH/3241-auto-clean-it-test-data-from-sf-dev)
> make the IT tests run daily rather than hourly

- support-lambdas/it-test-runner/cfn.yaml
In https://github.com/guardian/support-frontend/pull/2638
I made the tests run daily
but I should have altered the alarm to suit.
This PR makes the alarm over 25 hours instead of 1.25.
> don't alarm until IT tests don't run for 25 hours

- support-lambdas/it-test-runner/cfn.yaml
I tried to wing it in the previous PR https://github.com/guardian/support-frontend/pull/2640
but "Metrics cannot be checked across more than a day"
https://riffraff.gutools.co.uk/deployment/view/9176b2a8-d2db-44e6-ba12-b43e8746e8f1?verbose=true
I think a day would be ok unless it runs exactly on the hour.  This is only temporary anyway.
> check it test runner over a day

- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/productPrice/productOptions.js
- support-frontend/assets/helpers/productPrice/readerType.js
- support-frontend/assets/pages/subscriptions-redemption/api.js
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductOptions.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductRatePlan.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/test/scala/com/gu/support/workers/ProductTypeRatePlansSpec.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummary.scala
- support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionTerms.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceIntegrationSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/ServicesFixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
- support-workers/src/test/scala/com/gu/zuora/BuildDigitalPackSubscriptionSpec.scala
Up until now [Product Rate Plans](https://knowledgecenter.zuora.com/Central_Platform/API/G_SOAP_API/E1_SOAP_API_Object_Reference/ProductRatePlan) as modelled in the support stack have been made up of `billingPeriod`, `fulfilmentOptions` and `productOptions` where: 
- `fulfilmentOptions` relates to how the product is distributed to the customer (eg. `HomeDelivery` or `Collection` for paper) 
- `productOptions` relates to variations in the product offering (eg. `Weekend` or `EveryDay` for paper).
To model gift subscriptions for Guardian Weekly an additional boolean `fixedTerm` was then added as all the gift rate plans were fixed term.  
After that to support corporate Digital Subscriptions a new `ProductOption` was added - `Corporate` which applied to Digisubs only.
There are a couple of …
> Add ReaderType to ProductRatePlans

- support-frontend/assets/components/paypalExpressButton/PayPalExpressButton.jsx
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
For TCFv2 compliance we must only load these SDKs once the user has shown intent.
So we will now only load them when the user selects the relevant payment method.
This change only affects:
1. PayPal Express, which is only used for recurring,
2. Amazon pay, which is only for single.
Unaffected by this change:
1. PayPal for single, because it does not use an SDK
2. Gocardless
3. Stripe - we are trying a separate solution for this
This may result in a short delay in seeing the button when the user selects the payment method, as we are no longer initialising the SDKs on page load.
I have added a progress 'spinner' for the paypal express button, e.g.:
And we are already using one for the amazon pay button:
Does not affect the 'existing payment method' feature, for when you arrive via MMA:
> Defer loading of paypal + amazon pay

- support-services/src/main/scala/com/gu/support/redemption/generator/GiftCodeGenerator.scala
- support-services/src/test/scala/com/gu/support/redemption/generator/GiftCodeGeneratorSpec.scala
Following a discussion on RR dev channel, we agreed that the apply method behaviour is non-obvious, especially for client side engineers.
This PR removes the places we use it for normal code.
We also use it for case class smart constructors. 
We probably prefer "parse" but you need more tricks (until we update to 2.13 - https://github.com/scala/scala/pull/7702 ) to get rid of the built in `apply` and not defeat the point of the constructor.  Some options:
or
or
or
keep it as apply.
> don't use apply method in gift code generator

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
Add an AB test for having no payment method selected by default - as per [this card.](https://trello.com/c/3yiuecm4/2220-tcfv2-compliance-a-b-test-having-no-preselected-radio-button)
control: 
noDefault - initial:
noDefault - error message:
> Add AB test for having no default payment method selected

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
Remove the philanthropic ask from the contributions LP when a user comes via Apple News or Google AMP as per [this card](https://trello.com).
> Update logic for showing philanthropic ask

- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/test/resources/catalog-prod.json
- support-services/src/test/resources/catalog-prod.json
- support-services/src/test/resources/catalog-sandbox.json
- support-services/src/test/resources/catalog-uat.json
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
We want to add gifting as an option to the Digital Subscription product, the initial offering will be for one year or 3 month fixed term plans and this PR adds new product rate plans for these.
[**Trello Card**](https://trello.com/c/EVYAhPNK/3173-gifting-system-integration-zuora-create-new-limit-term-products)
> Digital Subscription gift plans

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
Add `ccpaEnabled` switch to `Switches.scala` so it gets surfaced on `window.guardian.settings.switches`.
> Add ccpaEnabled switch to Switches.scala

- support-frontend/assets/helpers/page/page.js
Don't show the CCPA CMP if `isPostDeployUser`. We do this for the old-CMP: https://github.com/guardian/support-frontend/blob/master/support-frontend/assets/components/consentBanner/consentBanner.jsx#L37
This is because the CCPA CMP intercepts the click event during the test:
> Don't show CCPA CMP if isPostDeployUser

- support-modules/aws/build.sbt
snyk has flagged this, so we need to override the dependency version
> override jackson-databind version in module-aws

- support-frontend/assets/components/page/page.jsx
- support-frontend/assets/helpers/render.js
- support-frontend/assets/pages/digital-subscription-landing/components/cta.jsx
banner acquisition optimisation team want to be able to link people straight to the CTA once they have read the epic, rather than dropping them at the top of the landing page.  This will prove whether that is why people are dropping off at that stage because they dont know what to click then.
[**Trello Card**](https://trello.com/c/oadRglcp/3240-anchor-text-for-ds-landing-page-epic-test)
This code has been implemented in useEffect.  a requestAnimationFrame is needed to get the scroll to work properly, otherwise it doesn't scroll far enough.
* add id to the container div
* add scroll code to the useEffect of the central page component
see comments below
> scroll to element on page load

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionAmountChoices.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionAmountChoicesChoiceLabel.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionAmountRecurringNotification.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionChoicesHeader.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
Adds the landing page retention A/B test as per [this card](https://trello.com/c/fNGvyJYN/2210-ab-test-to-decrease-the-volume-of-cancelations-coming-from-people-picking-monthly-instead-of-single)
control - mobile
control - desktop
variant 1 - mobile
variant 1 - desktop
variant 2 - mobile
variant 2 - desktop 
variant 3 - mobile
variant 3 - desktop
> Landing page retention A/B test

- support-frontend/assets/pages/contributions-landing/components/ContributionAmountRecurringNotification.jsx
The info icon for the second variant wasn't showing in chrome. This has now been fixed. Additionally, tweaked the alignment to match the design. 
before:
after:
> Fix info icon on chrome (and tweak styles)

- support-frontend/assets/helpers/abTests/abtest.js
Tiny PR that updates the logic for grabbing the ab test variant from url to also decode any special characters. This allows you to use variants with spaces in their names! e.g `#ab-my%20test=my%20variant`
> Decode encoded characters in ab test name/variant

- support-frontend/assets/helpers/tracking/__tests__/thirdPartyTrackingConsentTest.js
- support-frontend/assets/helpers/tracking/googleTagManager.js
- support-frontend/assets/helpers/tracking/thirdPartyTrackingConsent.js
Proposed changes to TCFv2 implementation. We only load Google Tag Manager and Google Analytics if a user has granted consent to both vendors. 
I've updated `onConsentChangeEvent` to take a 2nd parameter `sourcePointVendorIds` that looks something like:
```js
{
foo: '54321'
bar: '12345'
}
```
`onConsentChangeEvent` processes the state returned by `@guardian/consent-management-platform` and looks up whether a user has granted access to each of the vendors in `sourcePointVendorIds`, it builds up an object like:
```js
{
foo: true // user has consented to foo
bar: false // user has not consented to bar
}
```
> Honour vendor consent state with TCFv2

- support-frontend/assets/components/footerCompliant/Footer.jsx
- support-frontend/assets/components/footerCompliant/containers/Content.jsx
- support-frontend/assets/components/footerCompliant/containers/FooterContent.jsx
- support-frontend/assets/components/footerCompliant/footerStyles.js
- support-frontend/assets/pages/paper-subscription-landing/components/content/collectionTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/subsCardTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
- support-frontend/assets/stylesheets/skeleton/reset-src.scss
Adding the new footer to a page with a centred layout, and a page with a left column layout, for design/product review before rolling it out onto other pages.
[**Trello Card**](https://trello.com/c/m1SSOQiq)
* Added the new footer component to subscriptions and print subs landing pages
* Adjusted styling on the footer component to account for existing layout needs
(Upddated 7/8/20)
**Mobile**
**Tablet (vertical)**
**Tablet (horizontal)**
**Desktop**
**Mobile**
**Tablet (vertical)**
**Tablet (horizontal)**
**Desktop**
> New footer added to subscriptions & print subs landing pages

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
Fixes a bug which can occur if:
1. Stripe is the default payment method
2. User switches between monthly and annual
It breaks the form and the user has to refresh before they can complete a payment.
So currently this can affect non-UK users who are not in the `noDefault` test variant.
The issue is that we try to call `grecaptcha.render` again when the user switches between monthly/annual. This happens because the form does not re-create the stripe component when switching between monthly/annual. The error is:
Tested monthly/annual/single/PRB
> Fix Recaptcha error when switching between monthly and annual

- build.sbt
- support-lambdas/it-test-runner/build.sbt
scalatest had a bug in the reporting that meant there was a lot of output happening after the tests completed.  Also some output was missing from the reported tests.
These two bugs have been fixed and released in 3.2.1.
I have bumped to that version and removed the workaround added in https://github.com/guardian/support-frontend/pull/2555
> bump scalatest to fix reporting issue

- support-frontend/assets/pages/aus-moment-map/components/blurb.jsx
The Aus campaign is over and we are no longer updating the supporter count value.
But we do still want to link to this map.
> Hide supporter count on Aus map

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
card https://trello.com/c/EyeJ64OO/2226-react-stripe-elements-console-warning
When the user first clicks on a Stripe Elements field, the following warning message appears in the console:
```breadcrumbs.js:58 Unsupported prop change on Elements: You cannot change the `options` prop after setting the `stripe` prop.```
It doesn't cause any problems.
The solution is to always pass the `options` prop to `Elements`, otherwise you hit [this warning](https://github.com/stripe/react-stripe-js/blob/e13fae556b1a667a5dfa1130c00d5ec4c2bc154e/src/components/Elements.tsx#L125).
All fields in the `options` type are optional: https://stripe.com/docs/js/elements_object/create
> Set options prop on Stripe Elements

- support-internationalisation/version.sbt
Bumping version manually because [0.13](https://repo.maven.apache.org/maven2/com/gu/support-internationalisation_2.13/0.13/) was released via the following closed PR https://github.com/guardian/support-frontend/pull/2676
> Bump support-internationalisation version

- support-frontend/assets/pages/aus-moment-map/ausMomentMap.scss
- support-frontend/assets/pages/contributions-landing/newContributionsLandingTemplate.scss
Because I broke the contributions pages 🤦‍♀️ Setting `box-sizing: border-box;` globally altered sizing and alignment on the landing page, so this restores the old `content-box` setting for both contributions pages.
**Landing page**
**Moment map**
> Restore content-box sizing on contributions pages

- project/plugins.sbt
- support-frontend/test/fixtures/TestCSRFComponents.scala
Play 2.6 is no longer supported. Security updates are now only being released for Play 2.7 and 2.8. Under our cyber essentials obligations we must only use supported software and apply all critical and high severity security updates. Play security is particularly important due to the external facing nature and the duty we have to protect our readers and business.
[**Trello Card**](https://trello.com/c/YMmpPNB3)
- Upgrade Play version and fix breaking API changes
- Unit tests pass
- Selenium tests pass
> Upgrade Play from v2.6.23 to v2.7.5

- project/plugins.sbt
- support-frontend/test/fixtures/TestCSRFComponents.scala
Reverts guardian/support-frontend#2683
There were conflicts with the payment api merging into the mono repo, reverting in order to resolve them at our leisure rather than with a broken main build!
> Revert "Upgrade Play from v2.6.23 to v2.7.5"

- support-frontend/assets/pages/contributions-landing/components/AustraliaMapLink.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
There are 3 CTAs in the thank you page that are not currently tracked:
- ContributionSurvey
- AustraliaMapLink
- Return to The Guardian
This is in preparation for testing against the new thank you page.
I also made the survey link open in a new tab.
> Track all thank you page clicks

- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- safari only
- recurring only
The bug:
1. select card
2. select paypal. It gets stuck on card.
It is caused by recaptcha being loaded twice.
It uses some state called `calledRecaptchaRender` to ensure this doesn't happen, and this works in other browsers but not safari for some reason.
This fix is not ideal, and we should try to understand it better.
But it does at least work, by ensuring the recaptcha div is empty before trying to load it.
> Fix for safari recaptcha bug (recurring contributions)

- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/redemptions/RedemptionData.scala
- support-services/src/main/scala/com/gu/support/redemption/GetCodeStatus.scala
- support-services/src/main/scala/com/gu/support/redemption/generator/GiftCodeGenerator.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilder.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/GuardianWeeklySubscriptionBuilder.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/PaperSubscriptionBuilder.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/GuardianWeeklySubscriptionBuildersSpec.scala
This is the server side work to support purchasing and redeeming Digital Subscription gifts.
Digital Subscription gifts are the first product we have which requires two separate checkouts, one to purchase the gift and one to redeem it. The table below shows the types of checkout which are required by the different reader types (Direct, Gift or Corporate)
|          | Direct | Gift | Corporate |
|----------|--------|------|-----------|
| Purchase |    ✔    |   ✔  (gifter) |           |
| Redemption   |        |   ✔  (giftee) |     ✔      |
Most of this PR focuses on changes to the `DigitalSubscriptionBuilder` class to handle the two different checkout types, there are now two separate methods `buildPurchase` and `buildRedemption` to make the branching in the logic clearer. 
I have …
> Digital Subscription gift checkout - server side work

- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummaryStyles.js
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/subsCardTab.jsx
This is (🤞 ) the last part of the Newspaper subscriptions card work that was outstanding. The images on the landing page and the order summary image needed updating, and the thank you page had a piece of text that needed to be changed.
[**Trello Card**](https://trello.com/c/Fp3BY2yz/3269-corrections-for-subscriptions-card-checkout-post-prod-test)
* Replace paper landing page HD tab to show new campaign image
* Add paper landing page subscriptions card image
* Replace order summary image in checkout with subscriptions card image
* Update thank you page with 'tomorrow' rather than 'today' as the day you can collect your first papers
> Add iMovo campaign images and fix thank you page

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
Small update to clarify the text on the CTAs that take you back and forth between gifted and personal Guardian Weekly subscriptions.
[**Trello Card**](https://trello.com/c/HBAPYBQ7)
* Amended text in the title and CTA buttons of this section on the GW landing page
**Mobile**
**Tablet**
**Desktop**
**Mobile**
**Tablet**
**Desktop**
> Update Weekly gifting-related CTAs

- support-frontend/assets/components/content/content.scss
- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
This fixes a bug where the image is appearing and overlapping text on the tabs on the paper subscriptions landing page, at the tablet breakpoint.
[**Trello Card**](https://trello.com/c/rX0wrtop)
* Have images display from the desktop breakpoint instead of from the tablet breakpoint
* Fix sizes provided for the new home delivery image
**Before**
**After**
> Fix image overlapping text on paper subs page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
Remove default payment test and roll variant out as the default. Also fixes a bug where the paymentMethod was being set to "None" after a one-off contribution with paypal (as it leaves then redirects back to the site).
> Remove default payment ab test

- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
The OneOffContributionsSpec selenium test was not adding the `_post_deploy_user` cookie correctly which was causing the consent banner to interfere with its execution. This PR fixes that.
> Hide consent banner during OneOffContributionsSpec

- support-models/src/main/scala/com/gu/support/zuora/api/response/QueryResponse.scala
- support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraService.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilder.scala
- support-workers/src/test/scala/com/gu/support/workers/DigitalSubscriptionGiftRedemptionSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/DigitalSubscriptionGiftRedemptionIntegrationSpec.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala
We want Digital Subscription gift codes to expire if they haven't been redeemed within one year. This PR does that
* Rename `SubscriptionState` to `SubscriptionRedemptionState`
* introduces a new `Expired` `SubscriptionRedemptionState`
* Update the length of the initial term for gifts to 13 months so that it is longer than the expiry period - this will get set to the correct length upon redemption
> Digital Subscription gift code expiry

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
To add the `enableDigitalSubGifting` switch into the Switches object
Follows on from the admin console PR https://github.com/guardian/support-admin-console/pull/157
> Add `enableDigitalSubGifting` into Switches

- support-lambdas/it-test-runner/cfn.yaml
- support-workers/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
We reduced the frequency of running IT tests because SF DEV was filling up quickly and eventually tests were failing  and it was blocking SX team.  Now that we have a PR to clean it up, we can bring it back to higher frequency. PR here to be merged also: https://github.com/guardian/support-service-lambdas/pull/700
This PR is also reverted in this change set, as these are the tests which were failing: https://github.com/guardian/support-frontend/pull/2636
The changes mean we are likely to find out about breakages within the working day, rather than a subsequent day.  This means we can either fix the tests or find potential issues quickly.
[**Trello Card**](https://trello.com/c/LKwe8ApH/3241-auto-clean-it-test-data-from-sf-dev)
> run IT tests hourly instead of daily

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
We're comparing the conversion rate for each action on the page.
The 'return to the guardian' link tracking was missed on the new page.
_(just to prove it's the same on both now)_
New thankyou page event:
Old thankyou page event:
> Send ophan event for 'return to guardian' link in new thankyou page

- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
Membership workflow lowercases and replaces spaces with _. 
See https://github.com/guardian/membership-workflow/blob/2eea2601b284519e67dbcdb2226ce89b3c81c6cc/app/model/BrazeCampaignTriggerPayload.scala#L11
This is presumably because just the old ET system allowed those and we used them, but braze doesn't, and membership workflow is a convenient place where everything passes through, microservice style.
However it doesn't make sense to retain that intenitonally, as it's just confusing when disucssing things between braze users and devs.
I have only done this for digital pack, because that is the one I'm touching, but it really should be done to them all.  Should I do them at the same time?
I have tested using the manual email tests and it works okay still.
> normalise email key names for braze

- build.sbt
- support-lambdas/stripe-intent/build.sbt
- support-modules/aws/src/main/scala/com/gu/aws/AwsCloudWatchMetricPut.scala
- support-payment-api/build.sbt
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailService.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/test/scala/com/gu/emailservices/DigitalPackEmailFieldsSpec.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
- support-workers/src/test/scala/com/gu/emailservices/JsonToAttributesSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
As part of the DS gifting work, we need to trigger a pair of emails at purchase time (thank you email and giftee notification email) and a separate one at redemption time for the giftee when they redeem.
[**Trello Card**](https://trello.com/c/RvP8A1nw/3192-gifting-email-api-triggers-for-the-gifter-giftee-emails-generated)
* make the email builder return a List rather than a single email
* model the attributes as an ADT rather than building a list of key/value pairs (for Digi sub only at the moment)
* add logic to send the three new emails (as placeholder data only)
> add gifting emails - with dummy data

- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
- support-workers/src/test/scala/com/gu/emailservices/JsonToAttributesSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
Rupert mentioned in https://github.com/guardian/support-frontend/pull/2717#discussion_r494334861 that some of the existing email fields are probably not used.
I have done a check of the DS emails and found 3 fields, which I removed, and the emails still seem to send fine in PROD and TEST.
This PR removes the relevant fields.
This is the PROD email after removing the fields
> remove unused DS email fields

- support-frontend/app/views/subscriptionCheckout.scala.html
To make it obvious whether one is logged in as a test user or not when developing locally (see screenshot below). This builds on #2566.
* The boolean isTestUser is now set in the subscriptionCheckout view
> Enable test user red banner for subs checkouts

- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
this is a followup fix to https://github.com/guardian/support-frontend/pull/2717/files#diff-681c59db0de6db865fe598c3f08c823eR29
Where it was changed to be a List, I should have changed the deserialiser to also use a list.  I didn't expect the result was used anywhere and I forgot to run the IT tests.
This suggests that the IT test runner is not working correctly, as it should have detected this issue.
> email lambda returns a list rather than a single item

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
The new thank you page is performing much better than the old, so this change removes the test.
TODO later - remove all code for the old thank you page.
> remove thank you page test

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
it looks for this class when checking to see if the thankyou page has loaded, so I've added it back in (and removed the styling, as it was for the old page only)
(test was broken here https://github.com/guardian/support-frontend/pull/2731)
Now works locally:
> fix post deploy test for thankyou page

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/test/codecs/CirceDecodersTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
Update the social share url for the environment moment, as per [this card](https://trello.com/c/hMZCsiJp/2301-enviro-moment-replace-the-social-share-image-with-a-campaign-specific). Additionally, add two switches to `Switch` model: `enableContributionsCampaign` and `forceContributionsCampaign`. Before these were both `ExperimentSwitch`es but now we've formalised them as proper switches.
* formalise two contributions campaign switches
* update social share url for campaign
> Update social share url for enviro moment

- support-lambdas/it-test-runner/cfn.yaml
The IT tests are noisy because there are random failures from network issues.  This updates the alarm to be quieter hopefully as it will need two failures in a row.
[**Trello Card**](https://trello.com/c/of5WhYtb/3357-change-ittestfailurealarm-to-trigger-on-failing-tests-if-there-were-also-failing-tests-in-the-previous-run-1u-33)
> alarm when two IT test runs fail in a row

- support-workers/src/test/scala/com/gu/salesforce/Fixtures.scala
The IT tests have been failing since SX team cleaned out all data before 2020-01-01.  This is because we relied on a hard coded contact to be reused when we upserted the user.
I have updated the IDs for the replacement one that was just created.
> make IT tests use new contact ids

- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
The SendThankYouEmailIT was failing but somehow wasn't picked up by the automated IT test runs.
Turned out it was because the runner requires all the test names to end in "Spec" https://github.com/guardian/support-frontend/blob/596a3ed349ed085dcfd13ded6b44a768fd128f41/support-lambdas/it-test-runner/src/main/scala/com/gu/RunITTests.scala#L47
I have renamed the test to suit.
there are 204 that run in the automated run (now 205).  When I run support-workers it:test locally it runs 291 tests.  So we might need to check this a bit more generally.
> make thank you email it test run in the hourly test run

- support-frontend/app/controllers/RedemptionController.scala
- support-frontend/app/views/subscriptionRedemptionForm.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/app/wiring/Services.scala
- support-frontend/assets/pages/subscriptions-redemption/api.js
- support-models/src/main/scala/com/gu/support/redemptions/RedemptionCode.scala
- support-services/src/main/scala/com/gu/support/redemption/corporate/DynamoTableAsync.scala
Some small tidy up stuff following on from #2693 
* Only validate redemption codes with the server when they are of the correct length - this is because we are now validating with Zuora which can be slow and has a rate limit so we don't want to do this any more than we have to. NB. This means that we will now need to ensure that corporate codes are the same length or change this code to take account of the difference.
* Rework the way that dynamo table lookups are managed for test/non-test users to be consistent with the 'ServiceProvider' pattern used for other services.
[**Trello Card**](https://trello.com/c/Eh9zlzCT/3321-giftee-redemption-flow-working-for-gifting)
> rename dynamo lookup types and add pre-zuora gift code validation

- support-lambdas/it-test-runner/cfn.yaml
Having added an IT test that wasn't actually running https://github.com/guardian/support-frontend/pull/2737 , it was failing because it relies on writing to an SQS queue.
This PR adds the relevant permission.
tested in "PROD" with the result: `after: succeeded 208, failed 0, canceled 0, ignored 4, pending 0`
> allow new email ittest to access sqs queue

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYouHeader.jsx
Hide a users name on the thank you page if it's too long (more than 10 characters).
> Hide name if it's too long

- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/subscriptions-redemption/api.js
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
At the moment the debugInfo goes into the logs as one line for each state change.  This makes it hard to find and hard to copy/paste.  E.G.
This PR makes it come in as one log message by indenting the first character on each line
see 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html#agent-configuration-file:~:text=so%20any%20line%20that%20begins%20with,and%20starts%20a%20new%20log%20message.
Also I added placeholder messages for corporate redemption and subscriptions so that we positively know what it is when looking at the logs.
Tested locally Digi sub, plus annual contribution.
> make debugInfo all one message, add placeholders

- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/GiftRecipient.scala
- support-models/src/test/scala/com/gu/support/workers/GiftRecipientSpec.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
This PR adds the gift delivery date field all the way from the client side (as a placeholder) through to the email send.
[**Trello Card**](https://trello.com/c/RvP8A1nw/3192-gifting-email-api-triggers-for-the-gifter-giftee-emails-generated)
> add gift delivery date from client side to email

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYou.jsx
Prevent the header wrapping onto 3 lines. Added a leftCol break point, and made the header slightly wider between desktop and leftCol. 
before 
after
> Tp make header fit on two lines

- support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js
There were squashed (SE through iPhone 8) and missing (iPhone x and up) images on the relaunched digital subscriptions landing page.
Related to [**Trello Card**](https://trello.com/c/H5IACOaE/3290-editions-digital-subs-pages-subs-landing-page-9999)
And a fix for this PR: https://github.com/guardian/support-frontend/pull/2734
The are screenshots of the broken images in the trello card in case you'd like to see them - they were giant when I pasted them into this PR!
* Replace display flex with position absolute for this image
* Remove the 750 image size for mobile as this was awol
> Fix squashed and missing images on iOS for Editions on DS landing page

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYouHeader.jsx
The `firstName` field in the redux state is `string | null`.
The fact that flow didn't catch this is pretty shocking. Let's move to typescript!
Seen in sentry:
> Check name is not null in contributions thank you page

- support-frontend/assets/pages/paper-subscription-landing/components/content/subsCardTab.jsx
The "find your nearest participating retailer" link on https://support.theguardian.com/uk/subscribe/paper takes you off the support site when clicked, it'd be better to open this in a new tab. This PR does this be adding, `target="_blank"` to open the new tab and `rel="noopener noreferrer"` to prevent unsafe linking to cross-origin destinations, as described here: https://web.dev/external-anchors-use-rel-noopener/
> Open "find your nearest participating retailer" link in new tab

- support-frontend/app/controllers/RedemptionController.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/config/Stages.scala
- support-models/src/main/scala/com/gu/support/redemptions/RedemptionCode.scala
- support-models/src/test/scala/com/gu/support/redemptions/RedemptionCodeSpec.scala
- support-models/src/test/scala/com/gu/support/workers/Fixtures.scala
- support-models/src/test/scala/com/gu/support/workers/SerialisationSpec.scala
- support-services/src/test/scala/com/gu/support/redemption/corporate/CorporateCodeValidatorITSpec.scala
- support-services/src/test/scala/com/gu/support/redemption/corporate/CorporateCodeValidatorSpec.scala
- support-services/src/test/scala/com/gu/support/redemption/corporate/IT_testdata.sh
- support-services/src/test/scala/com/gu/support/redemption/corporate/SetCodeStatusITSpec.scala
- support-services/src/test/scala/com/gu/support/redemption/corporate/SetCodeStatusSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala
We currently have inconsistent casing conventions between gift and corporate codes, gift uses lowercase whereas corporate uses uppercase.
This PR changes corporate codes to use lowercase, I have also reintroduced the code length check when constructing a `RedemptionCode`.
[**Trello Card**](https://trello.com/c/vuOwsdwq/3189-make-corporate-sub-codes-lowercase)
> Make corporate redemption codes lower case 

- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
Fixes an issue where we are requesting an image at a size which we do not have a crop for.
* Adjust the requested sizes of the image on the home delivery tab to match the sizes we actually have
> fix list of requestable image sizes on home delivery tab

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Javascript dates run from 0-11, but we want dates that run from 1-12.
> Fix off by one error in the support reminder dates

- support-frontend/app/config/Configuration.scala
- support-frontend/app/config/RecaptchaConfigProvider.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/DigitalSubscriptionController.scala
- support-frontend/app/controllers/PaperSubscription.scala
- support-frontend/app/controllers/StripeController.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala
- support-frontend/test/selenium/contributions/RecurringContributionsSpec.scala
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
* **Problem**: The automated Selenium post-deploy tests used to bypass the No CAPTCHA reCAPTCHA on the Subscriptions Checkouts Stripe form by checking for a `_post_deploy_user` cookie and ignoring the result from the reCAPTCHA verification if the cookie is set. This resulted in a reCAPTCHA-related error being missed by the post-deploy tests and slipping in PROD. See the [Thu 27 Aug 2020 outage retro doc](https://docs.google.com/document/d/1vuBWgmCvp64Mbw5X8Snpg5Gcb_jOkKLw3gRLG5EbRbY/edit?usp=sharing) for more info.
* **Solution**: This PR implements the [recommended way for running automated tests](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do) with a v2 reCAPTCHA. Test users will now see a special No CAPTCHA for testing …
> Use reCAPTCHA special key for test users

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
This test has reached significance.
1. UK should still see the old control
2. Non-UK should see variant 2, which adds 'per month' or 'per year' to the amounts buttons for recurring contributions
Also, I noticed we were using 2 columns for one-off contributions as well, which is unnecessary.
> Remove retention test

- support-frontend/assets/helpers/formValidation.js
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/helpers/subscriptionsForms/submit.js
- support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/datePicker.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouGift.jsx
Following on from #2730 we need to pass two new fields through to the backend when completing a Digital Subscription gift purchase - `giftMessage` and `giftDeliveryDate`.
I have also changed the way that the gift delivery date is formatted in the Redux data store from `dd\MM\yyyy` to `yyyy-MM-dd`. This is consistent with how all other dates are represented in the checkouts and is the expected format for the deserialiser code in the backend.
[**Trello Card**](https://trello.com/c/7N8rZbzM/3396-pass-gift-message-gift-delivery-date-to-server-on-gift-purchase)
> Add new Digital Sub gift purchase fields into the checkout

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/yarn.lock
Per [this ticket](https://trello.com/c/LBpPmGmy), this PR adds some additional conditional logic to the React Router components on the contributions landing page. If a user points their browser directly to `https://support.theguardian.com/uk/thankyou`, they'll be redirected to `https://support.theguardian.com/uk/contribute`. This doesn't affect the post-contribution redirect to the thank you page.
_n.b. for testing purposes etc. we can directly navigate to the thank you page by appending the_ `no-redirect` _param to the query string, eg._ `https://support.theguardian.com/uk/thankyou?no-redirect`.
> prevent direct navigation to contribution thank you page

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Remove the post reminder survey from the thank you page, as per [this card](https://trello.com/c/O4GSUxxM/2355-remove-the-post-contribution-reminder-survey-from-the-ty-page).
> Remove post-reminder survey

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/stripe.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
We want to only load stripe with fraud detection if we have the required user consents (fraud detections drops a couple of cookies) as per [this card](https://trello.com/c/Owz6zkeD/2278-stripefraud-ab-test-remove-the-test-and-make-the-fraud-tool-available-only-when-we-get-the-users-consent).
> Enable stripe fraud detection only if we have required consents

- support-frontend/assets/pages/showcase/showcase.scss
This is a bug fix for an issue where the container for the image in the 'Subscribe' section on the support showcase page was still present in the DOM at mobile breakpoints, even when the image is not being shown, and was overlapping the button and breaking its interactivity.
* Make the image container `display: none` below the tablet breakpoint
> Fix issue with image container overlapping the 'Choose a subscription' button on the support page

- support-frontend/assets/pages/paper-subscription-checkout/components/endSummary/endSummary.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/endSummary/endSummarySelector.js
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
We recently updated the paper subscription checkouts to include the new order/end summary for both home delivery and collection options, but missed a bit of text that needed to be removed for the home delivery option. Also, we needed to include the end summary at the bottom of the page for mobile.
This work is just to update that text so it works for HD, and include the end summary on mobile.
Related to https://trello.com/c/OEI7qsZL/3386-post-subs-card-launch-clean-up-minor-post-launch-tweaks
And https://github.com/guardian/support-frontend/pull/2777
* Change text of second bullet point in end summary for home delivery so it works for this option
* Include end summary for mobile for HD option
> Remove second bullet point in end summary for HD paper checkout

- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
We don't want to send the standard acquisition event when a user redeems a gift subscription. This is because we have already sent this event when the gift was originally bought so to send it again would be a duplication.
[**Trello Card**](https://trello.com/c/FfFZ8IEk/3322-update-sendacquisitionevent-lambda-to-ignore-redemptions-1u-25)
> Don't send an acquisition event for gift redemptions

- support-frontend/assets/pages/digital-subscription-landing/components/australianEditions/productBlockAus.jsx
This adds an additional bullet point to the copy in the accordion about the Australia Weekend edition now that adjustments to the text have been agreed.
[**Trello Card**](https://trello.com/c/MQAxz6mU)
* Add 'Start your weekend informed' bullet point
**Mobile**
**Tablet**
**Desktop**
> Update Australia Weekend copy on digital subs landing page

- support-models/src/main/scala/com/gu/support/workers/PaymentProvider.scala
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
- support-workers/cloud-formation/src/templates/cfn-template.yaml
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
There are a couple of small improvements in this PR
- Add a `name` val to the `PaymentProvider` class rather than relying on `toString` as this is in line with our coding guidelines
- Use this `PaymentProvider` class when firing the `paymentSuccess` Cloudwatch metric rather than the identically named class from Ophan. This allows us to avoid having to deal with an Option and also makes it easier to remove the Thrift dependency in future.
> Two small improvements to the SendAcquisitionEvent lambda

- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
main support-workers build is broken
```
[error] /Users/john_duffell/code/support-frontend/support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala:84:76: value paymentProvider is not a member of com.gu.support.workers.states.SendAcquisitionEventState
[error]     val cloudwatchEvent = paymentSuccessRequest(Configuration.stage, state.paymentProvider, state.product)
```
because of a conflict between #2788 and with this change in #2773  - `paymentProvider` is now grouped with `isGiftPurchase` https://github.com/guardian/support-frontend/pull/2773/files#diff-1f62dcdc137f8cc0b96da16641da83da52faa0b7757b5c7cd4b5df0cb6e41d7eR40
> use new name for paymentProvider field

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Make the default date for post contribution reminders the 15th of the month, as per [this card](https://trello.com/c/ql304o5j/2361-update-the-post-contribution-reminder-date-to-be-the-15th-of-each-month-from-nov-instead-of-the-1st-to-be-able-to-send-the-email)
**FOLLOW UP**
- manually update reminders after from November onwards to be on the 15th (in braze + contribution_reminders) (BUT NOT THE ONES FOR GIVING TUESDAY)
**NB**: I uncovered a bug whilst implementing this that means all reminders set for the last day of the year were actually set to the 1st of December
> Make the default date for reminders the 15th

- support-frontend/assets/helpers/theGrid.js
This is to update the packshot in the hero section on the Subscriptions landing page to more prominently feature the Australia Weekend Edition and lure in Australian readers with the shininess of Scott Morrison's head.
[**Trello Card**](https://trello.com/c/IBmR0tro)
* Exchange the old packshot for the new one
**Mobile**
**Tablet**
**Desktop**
> Update Australia Weekend packshot on subs landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouUsElectionNewsletter.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
Implement the special US election thank you page newsletter sign up as an ab test. As per [this card](https://trello.com/c/e65OkQs6/2365-us-election-special-thank-you-page).
desktop:
mobile:
> Special US election thank you page

- project/build.properties
- project/plugins.sbt
This reverts sbt back to 1.3.13.
Previous PR to update: https://github.com/guardian/support-frontend/pull/2803
Some people were getting  a duplicate compllations error.  It seems to be a common problem online https://github.com/sbt/sbt/issues/5911
It seems that there is a new assertion against more than one compilation start time for a subproject being in the same millisecond,  but this situation can occur (rightly or wrongly) during play compilation.
Reverting until there is a solution either from play or sbt.
> roll back to sbt 1.3.13 due to intermittent dev assertion failure

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouUsElectionNewsletter.jsx
Remove timed wording that now refers to an event in the past.
The Election is over
> Remove timed wording that now refers to an event in the past.

- support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js
- support-frontend/assets/pages/digital-subscription-landing/components/productBlock.jsx
The purpose here is to remove references to Edition Earth from the digital subscriptions landing page.
The end date for Edition Earth is 7 November, which is on Saturday.
> Remove references to Edition Earth from digital subscriptions landing page

- support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/datePickerHelpers.test.js
Supersedes https://github.com/guardian/support-frontend/pull/2806 which used a more fp-centric method rather than mocking.
This PR mocks a specific date for the date range tests so that the tests don't compare two separately acquired dates.
This means they will not fail occasionally due to a millisecond having passed while the test was running.
```
17:09:00
FAIL assets/pages/digital-subscription-checkout/components/datePicker/datePickerHelpers.test.js
17:09:00
● getRange › should be able to get the latest available date from now
17:09:00
17:09:00
expect(received).toEqual(expected) // deep equality
17:09:00
17:09:00
Expected: 2021-01-06T17:08:59.555Z
17:09:00
Received: 2021-01-06T17:08:59.554Z
```
https://trello.com/c/4l2cBx52/3393-fix-non-deterministic-test
Unreliable tests can cause us …
> make range tests use mocked date

- support-frontend/assets/pages/subscriptions-redemption/components/productSummary/productSummary.jsx
[**Trello Card**](https://trello.com/c/qYSOwugn/3428-gifting-redemption-page)
We have new packshots for the Digital Subscription so we need to use these on the redemption form page. Also this page does not have separate copy for AUS/ROW so we need to make the copy that is there work for both.
> Update copy and packshot on the redemption page

- support-frontend/assets/components/footerCompliant/DigitalFooter.jsx
After merging in the new digital gift subs landing page, there was a selenium error, which seems to be due to a missing id that the test is looking for. This was removed inadvertently when we replaced the footer in this page, and thus the FAQs for the page, which contained the id that was being looked for.
I have reinstated this to the new digital footer.
The PR that introduced this error is this one: https://github.com/guardian/support-frontend/pull/2775
> Fix broken selenium test

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Update the support reminder copy on the TY page, as per [this card](https://trello.com/c/VDVEcAbq/2406-update-the-reminders-copy-to-advertise-the-fact-were-going-to-send-up-to-2-emails-from-now)
> Update reminder copy

- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/test/scala/com/gu/emailservices/JsonToAttributesSpec.scala
This PR adds code to handle None Options in the email builder code.
It also adds a test to make sure it is working.
during gifting testing there were errors in the logs if somoene didn't fill in a gift message.
```
coding error: all values should be string or object: gift_personal_message -> object[gifter_first_name -> "n0ZoXIrKEPrtpPjgBvc",gift_personal_message -> null,gift_code -> "gd12-blahblah",last_redemption_date -> "Tuesday, 9 November 2021",duration -> "12 months"]
```
This is because an Option[String] that is None, is treated as null rather than String or Object.
This situation wasn't in any of the tests.
> handle optional fields in emails

- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
There was a 'See gift options button on the subs landing page where there should not be one (yet!)
We are not ready to add this button yet:
> Remove gift button from digital subs card on subs landing page

- support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
- support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
This PR passes the number of months term through from the create subscription step into the email step,  then this is used for the thank you recipient email.
Otherwise it gets the default value of 1 month
> use correct term months for gift recipient thank you email

- support-frontend/app/controllers/RedemptionController.scala
- support-frontend/app/wiring/Controllers.scala
We don't need to limit access to the redemption form to Guardian employees anymore
> Remove Guardian auth from the redemption page

- support-models/src/main/scala/com/gu/support/zuora/api/SubscribeRequest.scala
- support-services/src/main/scala/com/gu/zuora/ZuoraGiftService.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
We want to be able to record the date a gift subscription was redeemed in a custom field in Zuora so that it is available to analysts in the Data Lake. 
This PR updates the `GifteeRedemptionDate` custom field with the current date when a gift code is redeemed.
[**Trello Card**](https://trello.com/c/wSuf5u9V/3453-add-redemption-date-field)
> Add `giftRedemptionDate` to the `UpdateRedemptionDataRequest` class

- support-frontend/app/controllers/Promotions.scala
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/appsSection.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouGift.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js
- support-frontend/assets/pages/digital-subscription-landing/components/heroGift/hero.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/heroGift/heroStyles.js
These are fixes from the [digital gift subscriptions landing page PR](https://github.com/guardian/support-frontend/pull/2775). This pull request needed to be merged because we wanted to begin end-to-end testing, but there were a couple of things that were outstanding from feedback on the PR.
* Remove orderIsAGift param from Promotions.scala
* Make no animations the default behaviour in gifting
* Update the text for the gifting hero (screenshot below)
The details of these fixes are in this [trello Card](https://trello.com/c/ElhMe2AO/3433-digital-subscriptions-gift-landing-page-follow-up-work-90)
In addition, this PR contains fixes for issues that were picked up in end-to-end testing:
* The change link in the gift checkout order summary was pointing to the non-gift landing page
* The copy …
> Gifting: digital subs landing page - fixes

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHearMarketingConsent.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/datePickerHelpers.test.js
Updates the A/B test on the thankyou page heading.
1. Highlights the amount
2. Changes the cta to yellow on the marketing consent component
(also picked up some linting fixes)
> Highlighting on thank you page

- support-frontend/assets/pages/digital-subscription-landing/components/heroGift/heroStyles.js
This is because I broke `prefers-reduced-motion` in this PR: https://github.com/guardian/support-frontend/pull/2828
😳
> Fix styles when user prefers reduced motion

- support-models/src/main/scala/com/gu/support/zuora/api/SubscribeRequest.scala
- support-models/src/main/scala/com/gu/support/zuora/api/response/Responses.scala
- support-models/src/main/scala/com/gu/support/zuora/api/response/SubscriptionsResponse.scala
- support-services/src/main/scala/com/gu/zuora/ZuoraGiftService.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
For Digital Subscription gifts we want a different revenue recognition model than for normal subscriptions. Whereas for normal subs we begin to recognise the revenue from the point of purchase, for gift subscriptions we want to recognise the revenue from the point at which the giftee redeems their gift code.
To do this we have set up a 'Billing Manual' revenue recognition rule which we use in the charge attached to the gift subscription rate plans.
When subscriptions with this rate plan are created a Revenue Schedule is created but all revenue remains ‘Undistributed’ until it is manually distributed either through the Zuora UI or via an api call.
There are more details in [this document](https://docs.google.com/document/d/1yNeaR2l1Ss_unXygntuntmRX-GicDelryuK25vmqToc/edit#heading=h.15hbk4mz …
> Digital Subscription gift revenue recognition

- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
This updates the images on the print checkout to match those from the landing page
[**Trello Card**](https://trello.com/c/EdNj7cj1)
**Subs card**
**Home delivery**
> Update images for print checkout to match the landing page

- support-frontend/yarn.lock
Update yarn.lock to refer to v6.7.4 of CMP library. Linked to https://github.com/guardian/support-frontend/pull/2819.
> Update yarn.lock to refer to v6.7.4 of CMP library

- support-frontend/assets/helpers/tracking/thirdPartyTrackingConsent.js
Now we're using the latest version of `@guardian/consent-management-platform` @ `v6.7.4` we need to check Australian consent state's `personalisedAdvertising` flag if available.
> Honour consent state in personalisedAdvertising flag in Australia

- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
- support-frontend/test/selenium/subscriptions/pages/WeeklyGiftProductPage.scala
- support-frontend/test/selenium/subscriptions/pages/WeeklyProductPage.scala
This adds a page ID and uses that as the selector for the Selenium tests verifying that the Guardian Weekly product pages load in prod, replacing the usage of a class name as a selector now we've mostly migrated the page to Emotion.
> Fix selenium selector for GW product page tests

- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
depends on https://github.com/guardian/membership-workflow/pull/275
This pushes the unmanaged gift start/end date attributes and term length into the membership workflow email queue.
This means they will arrive in braze as user custom attributes once the above is merged.
https://trello.com/c/EZlDR9wB/3429-gifting-braze-custom-data-attribute-5
The marketing and retention teams need to be able to target gift recipients in the days after redemption and before expiry, for onboarding and renewal comms.
Normally they get these dates from the DL subscriptions extract from zuora, but we don't extract those details from zuora into the DL/braze at present.  This is a quick bypass, as the data is write only (you can't aamend a gift redemption at present.)
> send custom attributes to workflow to be inserted into braze

- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
This PR adds a last name field to the email payload for gift recipient notification
In the current gift notification, it says "A gift from John" but nothing about the surname.
We need to it be clear who it came from, so the surname will be needed.
Existing:
Added field to payload: ` "gifter_last_name" : "Mouse"`
```
{
"duration" : "12 months",
"last_redemption_date" : "Wednesday, 14 October 2020",
"gifter_last_name" : "Mouse",
"gift_personal_message" : "gift message",
"gifter_first_name" : "Mickey",
"gift_code" : "gd12-02345678"
}
```
> add last name to gift recipient notification email

- support-frontend/assets/components/productOption/productOption.jsx
- support-frontend/assets/components/productOption/productOption.scss
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
The 'best deal' yellow label had gone missing from the gift price cards. The work done here is to reinstate this feature.
Because it will help users to identify that they would pay less money per month for 12 months worth of a gift subscription than for 3 months.
> Reinstate 'best deal' on gift price cards

- support-frontend/app/wiring/Services.scala
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
- support-services/src/main/scala/com/gu/zuora/ZuoraGiftLookupServiceProvider.scala
- support-services/src/main/scala/com/gu/zuora/ZuoraGiftService.scala
- support-workers/cloud-formation/src/templates/cfn-template.yaml
- support-workers/src/main/scala/com/gu/services/Services.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
Following from #2830 we want to add an alarm when the calls to Zuora to set up revenue distribution fail.
> Add an alarm for failures in the Zuora distribute revenue api call

- support-frontend/assets/pages/subscriptions-redemption/components/redemptionForm.jsx
Some Identity accounts such as those created via the single contributions checkout do not have a first name and last name set on them. This is a problem for gift redemption because these are mandatory fields for creating a subscription.
The longer term solution for this is to add a form to collect these fields for users who don't have them, but for launch we are just going to put an error message in place informing users that they need to set these fields via MMA.
[**Trello Card**](https://trello.com/c/s8bUR3HP/3467-investigate-redemption-errors-for-users-created-through-single-contribution-checkout)
> Add an error message to redemptionForm.jsx if id user names are missing

- support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/hero.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouExisting.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouExistingContent.jsx
You can only have 1 digital sub per identity account. The current message when you try to register a second, is "Your digital subscription is already live". This is not very helpful to the user. This PR updates the main title and first sentence to use clearer messaging.
This PR also fixes a broken packshot image on the same page, currently the packshot image is trying to load a crop of the image which 1825px wide, whilst the maximum available is 1800px.
https://trello.com/c/k88wBrxe/3491-fix-broken-packshot-image-on-digital-subscriptions-thank-you-page
https://trello.com/c/HZ7Jzbi4/3470-improve-copy-for-duplicate-digital-subs-thank-you-page-message
**Before**
**After**
> Copy update and packshot fix on thank you page for existing subscribers

- support-workers/src/main/scala/com/gu/salesforce/SalesforceService.scala
Currently for Digital Subscription gifts we are writing the billing address of the gifter into the giftee's Salesforce contact record. This is because for Guardian Weekly gifts we want to add the delivery address to the contact however for DS gifts this does not apply.
> Only write address details to Salesforce for GW gifts, not DS

- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
To fix a link that was pointing to the incorrect page.
This was an error introduced by: https://github.com/guardian/support-frontend/pull/2847
> Fix link to gift page from subs landing page

- support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/hero.jsx
This PR fixes broken packshot images used by the `hero.jsx` component, specifically linked to `editionsPackshotShort` and `editionsPackshotAusShort`, both images support a limited set of crops in the Grid: 500 x 300, 1000 x 600, 1800 x 1080.
Because our srcSizes contained crop dimensions that weren't on offer we were attempting to render crops that didn't exist, leading to instances of a broken packshot images. This PR switches to using supported crops.
> Correct crops of packshots in Hero Component

- support-frontend/conf/application.conf
This was a recommendation from the security audit of our site.
"The GU_support_csrf (https://support.theguardian.com) was identified as being set without the Secure flag. The Secure flag set forces a browser to only send the cookie in requests to sites protected with SSL (HTTPS sites). The HttpOnly flag forces the cookie to not be accessible via any client-side script (example: JavaScript using document.cookie)."
> Set httpOnly and secure flags on csrf cookie
