guardian/support-frontend

- support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss
- support-frontend/assets/pages/digital-subscription-landing/componentsB/theMoment.scss
I missed the positioning of the rounder in the last PR!
[**Trello Card**](https://trello.com/c/gE2y7vNm/2686-design-tweaks-to-dp-product-page)
* Nudge the roundel a bit
> @ minor tweaks to the roundel in the yellow box

- support-frontend/assets/pages/subscriptions-landing/components/featureHeader.jsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
These are css only design updates for the subscriptions showcase page
[**Trello Card**](https://trello.com/c/YbkDnDcj/2663-design-tweaks-to-the-subs-showcase-page)
* css only design changes
Mobile
Desktop
> feat: design updates

- support-frontend/README.md
This is just a minor adjustment to the README so we can test that prout is working now.
> Trivial change to README

- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeLookup.js
This is adding minor changes to a previous PR, propagating an experiment flag to the subscription checkout pages.
> Add checkout flag to subscription checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
The test is switched off while this is being fixed.
> Fix test control variant name

- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouBlurb.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingEOY2019.scss
- support-frontend/public/ticker.json
New landing page for the new US moment
Landing page:
Thank you 1:
Thank you 2:
> US End of Year landing page

- support-frontend/assets/helpers/__tests__/contributionsTests.js
- support-frontend/assets/helpers/contributions.js
This is the client-side configuration update necessary for the new max contributions in the US during the moment
> Changed max contributions in the US (10k single, 10k per annum, 800 per month)

- support-frontend/Brewfile.lock.json
- support-frontend/yarn.lock
Lock files need to be committed when packages are updated/added
> Commit lock files

- support-frontend/assets/pages/contributions-landing/components/ContributionTextInput.jsx
This has only just become an issue, I think it's related to the preact upgrade which has exposed some faulty logic in this component
> Fix input empty field placeholder bug

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingEOY2019.scss
Next priority for the EOY campaign
[**Trello Card**](https://trello.com/c/eOoUt59E/1642-update-us-landing-page-contribute-another-way)
> New philanthropic ask - "ts and cs"

- package.json
- support-frontend/package.json
- support-frontend/yarn.lock
These are npm updates, suggested by Snyk to deal with security concerns 
* Change 1
* Change 2
> Snyk update

- .gitignore
- project/LibraryVersions.scala
- support-frontend/app/views/ViewHelpers.scala
- support-lambdas/stripe-intent/build.sbt
- support-models/build.sbt
- support-workers/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
- support-workers/src/test/scala/com/gu/salesforce/SerialisationSpec.scala
Reverts guardian/support-frontend#2229
> Revert "Bump acquisition event producer for new component type"

- project/LibraryVersions.scala
- support-frontend/build.sbt
- support-workers/build.sbt
> Bump jackson to 2.10.1

- support-frontend/Brewfile.lock.json
code produced by running `setup.sh` has fallen out of sync with the committed code again
> Brew file update

- support-workers/build.sbt
- support-workers/src/main/scala/com/gu/paypal/PayPalService.scala
Snyk has flagged a dependency of this library.
scala-uri has moved home
> Update scala-uri dependency in support-workers

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
BRR request for the Giving Tuesday mini campaign within the EOY campaign
> Giving Tuesday landing page copy - NB: Please merge 11am on 3 December 2019

- support-frontend/assets/components/headers/slimRoundelHeader/slimRoundelHeader.jsx
- support-frontend/assets/components/headers/slimRoundelHeader/slimRoundelHeader.scss
- support-frontend/assets/components/secureTransactionIndicator/secureTransactionIndicator.scss
- support-frontend/assets/components/svgs/guardianRoundel.jsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/newTemplate.scss
We are testing whether a new design of landing page will provide any uplift.
[**Trello Card**](https://trello.com/c/bv0IWb3W/1562-implement-a-new-template-for-the-landing-page)
* Control - original landing page
* new_template - new landing page
> New landing page template

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
Reverts guardian/support-frontend#2261
> To be merged after Giving Tuesday: Revert "Giving Tuesday landing page copy"

- support-frontend/assets/components/headingBlock/headingBlock.jsx
- support-frontend/assets/components/headingBlock/headingBlock.scss
- support-frontend/assets/components/subscriptionCheckouts/thankYou/optInCopy.jsx
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
- support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.jsx
This is my second try at adding the opt-in text. This version avoids the refactor of the digital thank you pages which seemed to cause some sort of problem in production (though strangely no in dev).
[Trello Card 1](https://trello.com/c/wQsWE83e/2672-marketing-opt-in-additional-wording) and [Trello card 2](https://trello.com/c/Eb56M0fj/2743-thank-you-were-processing-your-payment-page-should-have-marketing-consent-on-it)
This work also fixes some broken overheadings on the thank you pages (they were missing their yellow background).
> Second attempt to add opt-in message on thank you pages

- support-models/build.sbt
incrementing library version to track amazon pay events
* Change 1
* Change 2
> incrementing library version to track amazon pay events

- support-frontend/app/controllers/ReminderController.scala
- support-frontend/app/services/RemindMeService.scala
- support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx
- support-frontend/test/services/RemindMeServiceSpec.scala
https://trello.com/c/nx89EwDJ/1697-back-end-side-of-work-for-the-pre-contribution-reminder
Corresponding platform pr:
https://github.com/guardian/contributions-platform/pull/179/files
* Adding reminder date to clientside, endpoint on play app and outgoing request to lambda
> Jg reminder date

- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayLoginButton.jsx
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayWallet.jsx
Adding tracking events to see if people are clicking to login to amazon pay / track views on the wallet.
> amazon pay tracking for ophan

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
We want the survey to continue but only for readers in certain regions (Europe)
[**Trello Card**](https://trello.com/c/IUcUkHOG/1736-take-down-contributions-testimonials-survey-on-everything-but-europe-tbd-by-us)
> Limit survey to contributors in europe

- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
If Apple Pay/Payment Request button does not provide a state/province, use the one in the form (taken from user's geolocation).
Some US users are unable to pay with Apple Pay because the state is missing.
Also renamed `state` to `stateOrProvince` because state is a very overloaded term!
This error message will now only be displayed if the state is also not in the form:
> Apple Pay/PRB: fall back on state/province in the form 

- support-frontend/assets/helpers/theGrid.js
- support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
These changes are to make the print landing page creative match with an offline campaign.
~~Currently waiting for approval from stakeholders~~
[**Trello Card**](https://trello.com/c/gQfSRVEN/2822-paper-product-page-hero-update-live-11-jan)
* Background and roundel colour changes
* Illustration change
* Headline change ~~(not final)~~ (permanent)
* Roundel text change (permanent)
* H1 text change (permanent)
> Update print landing page for Jan 2020 campaign

- support-workers/cloud-formation/src/templates/cfn-template.yaml
Kibana is now live, so we can add this here for convenience!
> Add kibana link to description

- support-frontend/.snyk
Updated Snyk policy and applied patches where possible.
> Snyk - applied patches and updated policy

- support-frontend/assets/helpers/userAgent.js
Minor change to correctly document/structure a helper file I created yesterday
> correctly document helper file

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
UX is done collecting interviews for the European moment
[**Trello Card**](https://trello.com/c/xmRfpc6a/1812-remove-survey-from-thank-you-page-for-european-readers)
> Removed Europe Survey

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
[**Trello Card**](https://trello.com/c/NU6AYP71/1733-release-amazon-pay-to-100-to-the-audience)
* Change 1
* Change 2
> removing amazon pay test

- support-frontend/assets/components/headingBlock/headingBlock.scss
- support-frontend/assets/helpers/flashSale.js
- support-frontend/assets/pages/paper-subscription-landing/components/hero/campaignHeader.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
- support-frontend/yarn.lock
The Jan 11th print campaign has finished, this PR is to restore the hero background colour, roundel background colour and the image to how they were before the campaign.
* Hero image
* Hero CSS
* ~Hero Copy~ Note from Lucy: I have reinstated the campaign text and have checked with Gus that it's okay to keep this ongoing. He says it is fine.
Old Campaign hero
New Hero
> feat: restored to the old hero

- support-frontend/.flowconfig
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/package.json
- support-frontend/yarn.lock
We would like to test using the new Source Design System choice card components for our product set (contribution type and amount).
This PR includes the installation of Emotion CSS and the Source libraries.
[**Trello Card**](https://trello.com/c/eDaY2yM5/1795-ab-test-the-new-choice-cards-product-set-on-lp)
* Install Source Foundations
* Install Emotion
* Install Choice Cards
* Implement test with 3 variants: 
- Control - no change
- Rectangles - choice cards as they are designed to be used
- Circles - rectangular choice cards for the contribution type, custom CSS round ones for the amounts.
> Product Set Choice Cards Test

- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
Some post-deployment tests failed due to the labels for the AB test components being different.
> Fix selenium tests

- support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
I've set up travis to ping the reader revenue dev channel when a post deployment test fail. I'd like to test it!
Once I got that working, I'll revert this PR.
> Break tests

- support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
Reverts guardian/support-frontend#2363
> Revert "Break tests"

- support-frontend/assets/helpers/campaigns.jsx
Users who arrive on /eu/contribute will see campaign-specific copy.
> Europe moment landing page copy

- support-frontend/devrun.sh
Reverts guardian/support-frontend#2373
> Revert "make sure the right version of node is running in devrun.sh"

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
For the Europe Moment.
Based entirely on https://github.com/guardian/support-frontend/pull/2342/files
> Add EU survey back to thank you page

- support-frontend/package.json
- support-frontend/yarn.lock
The choice card background colour for the selected card was very intense so it has been toned down.
* Changed background colour of selected choice card to less intense colour
> change choice card background colour

- support-frontend/assets/helpers/__tests__/formValidation.js
- support-frontend/assets/helpers/formValidation.js
Fixed a bug introduced by https://github.com/guardian/support-frontend/pull/2396 in line https://github.com/guardian/support-frontend/pull/2396/files#r392357771 which broke AU Single Contribution checkout.
> Fix AU Single Contribution Checkout

- support-frontend/assets/helpers/campaigns.jsx
The Europe campaign is over
[**Trello Card**](https://trello.com/c/g7IZuMPb/1900-turn-off-europe-moment-assets)
> Removed Europe campaign

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
[**Trello Card**](https://trello.com/c/2aouM8Vr/1827-run-an-ab-test-on-the-amounts-on-the-us-landing-page)
**Variant**
**Control**
> adding amounts test for US recurring

- support-frontend/Brewfile.lock.json
- support-frontend/app/config/Configuration.scala
- support-frontend/app/config/RecaptchaConfigProvider.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/RecaptchaController.scala
- support-frontend/app/services/RecaptchaService.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/wiring/AppComponents.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/app/wiring/Services.scala
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/helpers/__tests__/checkoutsTest.js
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/checkouts.js
- support-frontend/assets/helpers/recaptcha.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
- support-frontend/conf/routes
- support-frontend/test/controllers/ApplicationTest.scala
This change implements the Google reCAPTCHA v2 and v3 SDKs behind 2 independent feature switches.
**v3 - stripe disabled**
**v2 - robot checkbox**
> Attempt to stop card testing activity by using the Google reCAPTCHA SDK

- support-frontend/assets/components/subscriptionCheckouts/endSummary/endSummaryStyles.js
- support-frontend/assets/components/subscriptionCheckouts/orderSummary/orderSummaryStyles.js
These were some design tweaks I missed before merging the order summary - these are they.
* Line-heights
* Font-sizes and styles
> Order summary design tweaks

- support-frontend/app/controllers/StripeController.scala
- support-frontend/assets/helpers/recaptcha.js
- support-frontend/assets/helpers/routes.js
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
- support-frontend/conf/routes
- support-frontend/yarn.lock
We need a new endpoint for the latest architecture.
[**Trello Card**](https://trello.com/c/1nR0l7gx/1947-improve-security-of-stripe-setup-intent-creation-1)
* Change 1
* Change 2
> adding new endpoint

- support-frontend/app/controllers/DigitalSubscription.scala
- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/app/controllers/WeeklySubscription.scala
- support-frontend/assets/helpers/abTests/__tests__/abtestTest.js
- support-frontend/assets/helpers/abTests/abtest.js
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala
- support-models/src/main/scala/com/gu/support/promotions/Promotion.scala
- support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionServiceSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionTermsSpec.scala
- support-services/src/test/scala/com/gu/support/promotions/ServicesFixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
- support-workers/src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
We want to run an AB test for monthly digital subscriptions to see which is the more compelling offer: £1 for one month or 50% off for 3 months
[**Trello Card**](https://trello.com/c/nYmj3UaR/2955-digital-pack-new-pricing-offer-request-1-non-us-stage-2-a-b-test)
> Digisub monthly offer test

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
Reverts guardian/support-frontend#2430
> Revert "cope with missing stripe.elements()"

- support-config/src/main/scala/com/gu/support/config/StripeConfig.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
This was removed accidentally.
[**Trello Card**](https://trello.com/c/D0XQxl4P/2005-use-us-stripe-account-for-single-contributions)
> Jg us stripe acc

- support-frontend/app/controllers/Subscriptions.scala
- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
- support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala
The one for one vs 3 months half price has finished now and 3 months won, so I'm switching off the test and reverting to the control
[**Trello Card**](https://trello.com/c/6Jc9u2dO/2990-turn-off-pricing-ab-test)
> Remove the one for one test

- support-frontend/Brewfile.lock.json
- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.scss
Implements styling illustrated in [this Figma board](https://www.figma.com/file/Ap9g2y1aEsZwrubA9ToLtj/Patrons-%2F-Philanthropical-ask), as detailed in [this Trello card](https://trello.com/c/w3B5CKWa). The additional copy will only appear for USA contributions. Please see screenshots below:
**Mac**
**iPad**
**iPhone**
> Support USA giving tuesday

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
A new survey on the thank page, running until:
- 27th May for Australia
- 12th May for global
https://trello.com/c/kDcSUWrs/2040-publish-thank-you-survey-globally-to-help-understand-changing-motivations-since-covid-19-and-start-getting-australian-testimonia
> Testimonial survey link

- support-frontend/assets/pages/contributions-landing/components/ContributionSurvey/ContributionsSurvey.jsx
updates non-Aus survey url to use June 2020 survey
> updates non-Aus survey url to use June 2020 survey

- support-services/src/test/scala/com/gu/support/redemption/SetCodeStatusITSpec.scala
@tomrf1 noticed there was an ITTest failure that I'd merged to master, this fixes it.
> make expectation for SetCodeStatusITSpec correct

- support-frontend/assets/helpers/campaigns.jsx
> Set Aus moment copy

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouBlurb.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
> Aus moment thank you page message

- support-frontend/assets/components/socialShare/socialShare.jsx
We want the subject line repeated in the body
> update copy for aus social share email

- support-frontend/app/actions/AsyncAuthenticatedBuilder.scala
When we use the maybe identity auth function, and there is a failure in the controller (our normal logic) this causes the identity register/signin screen to show.
This PR fixes it so it's only identity failures that cause the login screen.
This will also affect failures in mandatory authed screens, so a 5xx error in the checkout for e.g. GW, will correctly show a 5xx error page rather than redirecting to login. Hopefully we are not relying on that anywhere, but at the moment we could be having 100% 5xx error on any page behind identity , and the 5xx alarm woudln't go off.
optional auth:
> don't show the auth screen on an internal server error

- support-frontend/setup.sh
- Small changes to setup.sh
- Clean up code while [upgrading Storybook](https://github.com/guardian/support-frontend/pull/2578)
> Refactor setup.sh

- support-workers/README.md
We need to test prout to see if the post deploy tests are working
> non-change to readme to trigger prout

- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/build-tc
Fixes an issue with the design system choice cards that led to an overflow at certain screen sizes.
We will make a fix to the design system when we have time and then should be able to remove this.
> Tp support landing page overflow bug fix

- support-frontend/assets/components/socialShare/socialShare.jsx
This PR updates aus moment social share copy, per [this Trello card](https://trello.com/c/IYH3pt0e/2181-update-the-social-share-copy).
> updates aus moment social share copy

- support-frontend/assets/pages/aus-moment-map/ausMomentMap.jsx
- support-frontend/assets/pages/aus-moment-map/ausMomentMap.scss
- support-frontend/assets/pages/aus-moment-map/components/header.jsx
- support-frontend/assets/pages/aus-moment-map/components/map.jsx
- support-frontend/assets/pages/aus-moment-map/components/social-links.jsx
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.jsx
- support-frontend/package.json
- support-frontend/yarn.lock
- add the second testimonial cta for mobile
- add a read more button on mobile
- minor layout/design tweaks
> Tp aus map testimonials

- support-frontend/assets/pages/aus-moment-map/components/blurb.jsx
- support-frontend/assets/pages/aus-moment-map/components/socialLinks.jsx
Now links to /aus-2020-map
Needs testing with facebook/twitter/email
> sharing links

- support-frontend/assets/pages/aus-moment-map/components/map.jsx
- support-frontend/assets/pages/aus-moment-map/components/territories/actSvg.jsx
Make ACT more clickable by adding a clickable rect behind it
> Make ACT more clickable

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
The variant had no effect, but we're using it for the rest of the campaign anyway
> Remove aus moment background a/b test

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/helpers/campaigns.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
- support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.jsx
- support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.jsx
> Change copy when Aus moment goal reached

- support-frontend/assets/components/footerCompliant/footer.jsx
- support-frontend/assets/components/footerCompliant/footerContainer.js
- support-frontend/assets/components/footerCompliant/footerStyles.js
- support-frontend/stories/_index.js
- support-frontend/stories/footer.jsx
This is preparatory work to starting the footer UI development, which we plan to undertake in storybook. This adds a story for the footer component.
I created a new folder for the footer development called footerCompliant, so we can roll out the new one in stages.
Stories can be viewed by running the support-frontend `./devrun.sh` and then going to localhost:9001
[**Trello Card**](https://trello.com/c/Bp69nPoG/3180-print-thank-you-page-for-imovo-subs-card)
> Add a story for the footer component development

- project/LibraryVersions.scala
Updating Jackson and AWS Java SDK for Snyk issue https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-559106
> Updating Jackson and AWS Java SDK for Snyk issue

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/helpers/abTests/data/testAmountsData.js
Update the aus amounts ab test as per [this card](https://trello.com/c/2ZudP1k8/2205-implement-another-round-of-amounts-test-on-the-aus-lp)
> Update aus amounts ab test

- support-frontend/assets/helpers/abTests/abtest.js
- support-frontend/assets/pages/contributions-landing/components/AustraliaMapLink.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
> Link to map on Aus thankyou page 

- support-workers/README.md
Non-change to test Prout, similar to https://github.com/guardian/support-frontend/pull/2580
> non-change to README to test Prout

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYouSupportReminder.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
Update copy and remove expandable section from the support reminder action.
> Update copy and remove expandable section

- support-frontend/app/views/contributions.scala.html
Change in https://github.com/guardian/support-frontend/pull/2711
teamcity status checks are required, but for good security reason we don't build forks
My solution was to merge into a non-main branch (this one) build that, then merge that into main.
> merge Walaura's change into main via a buildable branch

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/new-flow/ContributionThankYouSupportReminder.jsx
Add special reminder option for users during the environment moment, as per [this card](https://trello.com/c/W2v2ecuh/2290-enviro-moment-special-post-contribution-reminder)
> Add special reminder option for environment moment

- support-frontend/app/controllers/Application.scala
> Update env moment sharing image

- support-models/src/main/scala/com/gu/support/catalog/Product.scala
This is to switch on the subscriptions card in support-frontend.
> Switch useDigitalVoucher to true

- support-frontend/test/utils/CheckoutValidationRulesTest.scala
fix undetected merge conflict
https://github.com/guardian/support-frontend/pull/2748#issuecomment-705496126
> fix new test to use valid code

- support-frontend/build-tc
> Upgrade yarn to 1.22.5

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Update the post reminder message to link to a survey, as per [this card](https://trello.com/c/8ONp6Ucc/2304-update-the-post-contribution-reminder-confirmation-message).
> Add post reminder survey

- support-frontend/app/controllers/Application.scala
Update the social share url for the landing page as per [this card](https://trello.com/c/n7mtETMG/2336-replace-the-current-social-share-image-with-the-one-attached).
> Update social share image

- support-frontend/app/controllers/Application.scala
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
Remove the environment moment assets, as per [this card](https://trello.com/c/qQykDywJ/2347-enviro-moment-turn-off-all-the-assets).
* remove article share
* remove special reminder
* remove social share
> Remove environment moment assests

- support-frontend/assets/helpers/stripe.js
- support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
CMP doesn't work for test users
> Fix post-deploy tests

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
Launch the special end of year reminder in the US, as per [this card](https://trello.com/c/MYVtQJmX/2348-release-the-special-post-contribution-reminders-in-the-us-gt-eoy-both).
> Launch the special end of year reminder in the US

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
Update the post contribution reminder survey and hide it 2 weeks from now, as per [this card](https://trello.com/c/ZmqGkf8F/2360-update-the-survey-url-thank-you-page).
> Update survey link and make it hide 2 weeks from now

- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
> Fix contribution cta width on mobile

- support-internationalisation/src/main/scala/com/gu/i18n/Country.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/test/scala/com/gu/salesforce/Fixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
The SF and Zuora DEV environments have been refreshed.  This means the IT tests started failed.
This PR updates them to work again.
Also I have done some cleanup along the way.
> fix the IT tests after the DEV SF-Zuora refresh

- support-frontend/package.json
- support-frontend/yarn.lock
> Update dompurify to 2.2.0

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouUsElectionNewsletter.jsx
Update the copy in the US newsletter sign up action on the thank you page.
> Copy update

- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
Since the recent UAT env refresh, the IT tests have been failing.  This PR fixes them to use some fresh subscriptions.
> fix IT tests that access zuora UAT

- support-frontend/assets/pages/paypal-error/payPalError.jsx
- support-frontend/assets/pages/paypal-error/payPalError.scss
Update the paypal error page as per [this card](https://trello.com/c/0QbiyIo4/2324-implement-paypals-error-page-new-ui).
> Update error page

- support-config/src/main/resources/touchpoint.PROD.conf
- support-config/src/main/resources/touchpoint.UAT.conf
The default config was missing values for `zuora.api.url` in PROD and UAT, this adds them.
> Add zuora.api.url config setting for PROD & UAT

- support-frontend/package.json
Update ophan tracker dependency to latest version.
There should not be a breaking change ([see latest changes](https://github.com/guardian/ophan/blob/master/tracker-js/changes.md)) and [latest PR](https://github.com/guardian/ophan/pull/3964)
Keeping dependencies up-to-date.
> Update ophan tracker js to 1.3.23

- support-frontend/assets/helpers/campaigns.jsx
> Update ticker copy

- support-frontend/app/controllers/RedemptionController.scala
This PR is a follow up to #2851. I noticed that the user information was not being set correctly in `window.guardian.user` by the server so the message was showing for all users.
> Set user details correctly in redemption form

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
This PR adds an AB test showing a special message below the TY page header if the user has donated over a certain amount (250+ one off/yearly, 25+ each month), as per [this card](https://trello.com/c/39klXUdT/2437-a-b-test-the-high-contributor-copy-on-the-thank-you-page).
I also re-ran prettier on the changed files because I think it hadn't been for a while! (It didn't fix _too_ much)
control
variant
> Add US large donation AB test 

- support-payment-api/src/main/resources/cloud-formation.yaml
Update the ssm policy to use a less permissive one, as per [this card](https://trello.com/c/qNgYO8yT/2435-replace-amazonec2roleforssm-with-custom-policy-on-payment-api).
> Use less permissive ssm permissions

- support-frontend/assets/components/footerCompliant/ContributionsFooter.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
Update the footer on the LP page to make more compliant! It also stylistically bring it more inline with the rest of the support site. [Here's the trello link](https://trello.com/c/cu3TkHQG/2453-landing-page-legal-requirements-footer)
> Update contributions LP footer

- support-frontend/assets/components/footerCompliant/ContributionsFooter.jsx
- support-frontend/assets/pages/contributions-landing/contributionsLanding.scss
- support-frontend/assets/pages/contributions-landing/newContributionsLandingTemplate.scss
Tweak the landing page layout based on feedback from Hyuna.
> Tweak LP layout

- project/build.properties
- project/plugins.sbt
Update to SBT 1.4
https://trello.com/c/nQMQUhIM/3506-update-support-frontend-repo-to-sbt-14
Keep things up to date.  Various improvements maade: https://github.com/sbt/sbt/releases
This redoes https://github.com/guardian/support-frontend/pull/2808 which was reverted due to a bug which has now been fixed.
I have compiled everything and I have run devrun, and it seems to work ok.
> update to sbt 1.4.4

- support-frontend/assets/helpers/campaigns.jsx
Update the US LP copy from the 29th onwards.
> Add special 29th and onwards US LP copy

- support-frontend/assets/helpers/campaigns.jsx
update ticker copy on US landing page
> update ticker copy on us landing page

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSocialShare.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/social.js
Remove all the special US EOY appeal components on the TY page:
- reminders
- social share
- survey
> Remove US EOY TY Page

- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/subsCardDays.js
Inexplicably the Stripe form bug fix PR caused a linting issue after merging into `main`. This fixes the problem.
> Fix lint issue arising from stripe form bug fix PR

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouAusMap.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouMarketingConsent.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSignIn.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSignUp.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSocialShare.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
Add view events to components on the TY page so that we can get accurate "conversion rates" for each component.
> Add view events to TY page components 

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/ophan.js
Updating the `usThankyouPageLargeDonationTest` to `globalThankyouPageLargeDonationTest` to increase reach and changing up the thresholds for the amounts (again to increase reach).
UPDATE: we have now have the final amounts.
[**Trello Card**](https://trello.com/c/Gzc7Lq5J/2525-update-large-us-donation-test-to-large-global-donation-test).
> Update large US donation test to large global donation test

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx
See https://github.com/guardian/support-reminders/blob/fe449111af2c66d055e55d39e1d3ac4486df1dfa/src/create-reminder-signup/lambda/models.ts#L25
> Fix REMINDER_PLATFORM

- support-frontend/cloud-formation/cfn.yaml
- support-payment-api/src/main/resources/cloud-formation.yaml
This makes it easier to do reservations and find unused instances
tested in CODE
> add instacne names so we can make sense of AWS console

- .gitignore
Add some of the files generated by vscode to `.gitignore`
> Add metals files to .gitignore

- support-frontend/assets/components/headers/links/links.jsx
- support-frontend/assets/components/subscriptionCheckouts/thankYou/optInCopy.jsx
- support-frontend/assets/helpers/subscriptionsForms/formReducer.js
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/subsCardTab.jsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
- support-frontend/assets/pages/paper-subscription-landing/helpers/products.js
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
Changing some words:
Paper -> Newspaper
Sixday -> Six day
Everyday -> Every day
[**Trello Card**](https://trello.com/c/R0bk2FZM/3515-newspaper-subs-lp-march-campaign-copy-updates)
A print subscription campaign will be launched on 6th March 2021. We will want to make some copy changes to ensure consistency of language across the new newspapers LP, showcase subscriptions page, main nav and checkout flow.
> Newspaper Subs LP - March campaign copy updates

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlock.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlockAus.jsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
This PR sets up the digital subscription 'accordion' AB test. The aim of the test is to see whether having the information accordions open by default will result in an increase in checkout starts.
[**Optimize test**](https://optimize.google.com/optimize/home/#/accounts/1368065808/containers/6827913/experiments/470)
[**Trello Card**](https://trello.com/c/pjBs0cNe/3405-increase-conversion-on-digital-subs-landing-page-by-testing-optimisation-of-accordions)
> Accordion AB test

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
Remove price breakdown test. All variants perfomed the same, so we are removing the breakdown.
> Remove price breakdown test

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouMarketingConsent.jsx
Remove a couple of AB tests that have been running on the TY page for a while.
[**Trello Card**](https://trello.com/c/1nRT3CbT/2608-end-old-ty-page-tests)
> Remove old AB tests

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
Update the SurveyMonkey link on TY page and turn on the survey action. TBC if we need to put in an end date for the survey (currently none).
[**Trello Card**](https://trello.com/c/ZxgaUQW3/2610-surveymonkey-update-on-ty-page)
> update survey link on TY page

- build.sbt
- project/plugins.sbt
- support-frontend/app/wiring/AppLoader.scala
- support-frontend/build.sbt
- support-models/build.sbt
- support-payment-api/build.sbt
- support-workers/build.sbt
Reverts guardian/support-frontend#3016
People are getting problems contacting the EC2 metadata service when running locally.  Needs reverting in order to unblock people.
> Revert "remove references to bintray"

- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroPriceCards.jsx
Actually for real this time fixing the overflow issue with the roundel in the hero CTA A/B test variant.
> Properly fix hero price card overflow

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouMarketingConsent.jsx
Remove the marketing consent copy ab test. There was no significance, but we're rolling out v1 to 100%
> Remove marketing consent ab test

- support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
For some reason #3043 built successfully on the PR branch but then failed when merged into main. This PR fixes it.
> Uncomment DS gift redemptions in UpdateSupporterProductData

- support-frontend/cloud-formation/cfn.yaml
- support-payment-api/src/main/resources/cloud-formation.yaml
in preparation for making it private
- support-frontend
- payment-api
> Deploy bucket policies

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/controllers/PaperSubscriptionController.scala
- support-frontend/app/controllers/Promotions.scala
- support-frontend/app/controllers/SubscriptionsController.scala
- support-frontend/app/controllers/WeeklySubscriptionController.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/conf/routes
- support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala
We are going to run a promotional sale on newspaper subscriptions starting on the 5th of July. During this period we want all customers who purchase a print subscription to do so with the promo code `JUNE21SALE` so this PR adds this promo to the `DefaultPromotions` object and sets is as a default promotion on the paper landing page and the subscriptions landing page.
I have also taken the opportunity to rename several of the subs related controller classes to end in `...Controller` to be more consistent and to make it easier to tell from the class name what their purpose is.
[**Trello Card**](https://trello.com/c/lKZIn0DO/3725-print-campaign-subscriptions-landing-page-display-paper-offer)
> June 21 sale

- support-frontend/assets/helpers/timeBoundedCopy/timeBoundedCopy.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithPriceCards.jsx
This adds an end date for the time-bound special edition copy for G200. I've also removed the copy about the books special edition that we still had hanging around.
[**Trello Card**](https://trello.com/c/ufKmJ3Yj)
> Add 4th June end date for G200 edition copy

- support-frontend/assets/pages/digital-subscription-landing/components/editorialVoice/editorialVoice.jsx
- support-frontend/stories/content.jsx
Fixing a misspelled name.
It's important to spell people's name's correctly. We are the Grauniad, obvs.
> Fix spelling of Katharine Viner

- support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.jsx
co authored with @i-hardy in the mob programming
This PR ads some extra copy to the cards for HD and subs card so that people know what they will pay after the promo.
and
https://trello.com/c/f6MEbgZQ/3706-print-campaign-print-checkout-order-summary-does-not-include-promotion-discount-copy
We are having a june sale which discounts paper for 12 months, but this has never happened before, so we need to update the page to include the extra copy.
> add "and then $blah after" copy to paper promo cards

- support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.jsx
Extending the paper order summary price string to accommodate promotions.
[**Trello Card**](https://trello.com/c/f6MEbgZQ/3706-print-campaign-print-checkout-order-summary-does-not-include-promotion-discount-copy)
To make it possible to accurately describe the price customers will pay during the June sale.
> Update price string to allow promotion text in paper order summary

- support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.jsx
Updating some code to reuse an existing method rather than recreating the wheel.
@i-hardy gave me this feedback in this PR: https://github.com/guardian/support-frontend/pull/3097 but I had pulled the trigger before I saw it.
> Paper order summary - small fix

- support-modules/acquisitions-stream/build.sbt
flagged by snyk
Also bumped the kinesis library version
> Set jackson versions for acquisitions-stream module

- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-lambdas/acquisitions-firehose-transformer/cfn.yaml
- support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJson.scala
- support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/Lambda.scala
- support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJsonSpec.scala
Add av calculation to acquisitions firehose transfromer. This will give us realtime access to AV for use in our article super mode project.
[**Trello Card**](https://trello.com/c/Vm8BRxYZ/2665-super-mode-realtime-av-calculation)
> Add av calculation to firehose

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
Restarting the events test after a false start with the wrong regions targeted and an issue with the Optimize setup.
Relates to: https://github.com/guardian/support-frontend/pull/3147
And also: https://github.com/guardian/support-frontend/pull/3132
> Restart events test

- .github/PULL_REQUEST_TEMPLATE.md
Adding a prompt to the pull request template for AB tests.
We recently had to restart an Optimize test because the setup wasn't correct. This adds a prompt for reviewers to check that Optimize has been set up correctly.
> Add prompt to check the Optimize setup if the PR is an AB test

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
> Aus survey

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.js
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
we only want the Aus survey for now
> Remove survey

- support-frontend/assets/helpers/campaigns/campaigns.jsx
- support-frontend/public/supporters-ticker.json
> Aus 2021 landing page

- support-frontend/assets/pages/aus-moment-map/components/blurb.jsx
- support-frontend/assets/pages/aus-moment-map/components/header.jsx
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.jsx
> enable ticker on aus map

- support-frontend/assets/pages/aus-moment-map/ausMomentMap.scss
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.jsx
> Update aus map testimonial colours

- support-frontend/app/controllers/Application.scala
> Update aus social share images

- support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJson.scala
- support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala
Add referrer url to acquisition event as part of our super mode project
> Add referrer url to acquisition event

- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSocialShare.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/social.js
`mailto:?subject=Join%20me%20in%20supporting%20Guardian%20Australia&body=I%20support%20Guardian%20Australia%20because%20I%20believe%20in%20rigorous,%20independent%20journalism%20that%E2%80%99s%20open%20for%20everyone%20to%20read.%20Join%20me%20by%20making%20a%20contribution%20and%20together%20we%20can%20be%20a%20voice%20for%20change.%20#supportGuardianAustralia%20%0D%
0Ahttps://support.theguardian.com/contribute?INTCMP=component-share-mail-Aus_moment_2021`
> Update social share copy for aus moment

- support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.jsx
> Update aus share cta copy

- support-frontend/assets/helpers/timeBoundedCopy/timeBoundedCopy.jsx
- support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithPriceCards.jsx
This PR updates the current time bound copy with the olympics special edition time bound copy.
[**Trello Card**](https://trello.com/c/jRSKodrj/3803-digi-subs-lp-special-edition-copy-update)
> Digital subs olympics special edition copy update

- support-frontend/assets/__mocks__/imageMock.js
- support-frontend/assets/__mocks__/productInfoMocks.js
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
- support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.test.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.jsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.test.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.test.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.jsx
- support-frontend/package.json
This fixes the issue where we were offering the direct debit payment option in the subscriptions checkouts to users not paying in GBP. I've also done a little clean-up of the logic so we only determine available payment options once, and pass these into the PaymentMethodSelector component, and added some component testing on the checkout forms to verify the logic around when we do and don't offer the direct debit option.
[**Trello Card**](https://trello.com/c/MqGNzD3g)
This issue was previously addressed in #3032 and #3157- the former caused an issue with delivery or billing to the Isle of Man, which uses GBP but does not count as part of GB for payment purposes, and the latter caused an issue with the Guardian Weekly checkout where the price and currency depend on the _delivery_ country, …
> Fix issue where direct debit payment option was shown when delivering outside GB or not paying in GBP

- support-frontend/assets/components/csr/csrBanner.jsx
- support-frontend/assets/components/csr/csrMode.js
This change was supposed to go into #3191 but I merged too quickly!
> Use useEffect to handle CSR sign in

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
the ticker is currently displaying on the landing page for Aus users.
We'd like to AB test its impact
> AB test the ticker

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.scss
Add the guardian help centre link for US landing page
> Add guardian help centre link to US landing page

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
currently no one is being put in the test
> set AB test size to 1

- support-frontend/assets/helpers/tracking/acquisitions.js
Refactored how we establish the page's referrer acquisition data. Mostly renames and functionisation. 
The main difference in logic is a fix where presence of a `&gclid=` value now clears all other referrer acquisition data and sets its own campaign code too.
> Refactored how we establish the page's referrer acquisition data

- support-lambdas/acquisition-events-api/cfn.yaml
- support-lambdas/acquisition-events-api/src/main/scala/com/gu/acquisitionEventsApi/Lambda.scala
Add 4XX and 5XX alarms to app acquisitions Api
> Add alarms to app acquisitions api

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
Include off-platform referrals in philanthropic ask on the US landing page
> Include off-platform referrals in philanthropic ask (US)

- support-frontend/assets/helpers/forms/checkouts.js
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js
to support: `?selected-amount=other`
> Enable 'other' amount from url

- support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
- support-frontend/assets/helpers/abTests/lpPreviousGiving.js
- support-frontend/assets/helpers/utilities/dateFormatting.js
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionsFormBlurbPreviousGiving.jsx
Some new copy below the Contribute CTA, for recurring.
This is for SEPA, but is appropriate for all payment methods.
> Show payment schedule for recurring contributions

- build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
this gives us a newer version of libthrift
> Bump acquisitions-value-calculator-client

- support-frontend/assets/helpers/abTests/abtestDefinitions.js
- support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionAmountChoices.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.jsx
- support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx
- support-frontend/package.json
- support-frontend/yarn.lock
Add product set ab test on the contributions landing page.
[**Trello Card**](https://trello.com/c/EjDpK9iG/2766-product-set-a-b-test)
**mobile, odd number of amounts**
**mobile, even number of amounts**
**desktop, odd number of amounts**
**desktop, even number of amounts**
> Product set AB test

- support-frontend/assets/pages/paper-subscription-checkout/helpers/subsCardDays.js
Fixing issue with payment date calculation for SaturdayPlus Newspaper Subs
> Update to include SaturdayPlus info

- support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.jsx
This pr update the paper pricing card text to match brand name
> Update paper pricing card text to match brand name

- support-frontend/cloud-formation/cfn.yaml
This PR makes the alarm name and desc more accurate
@GHaberis pointed out it is misleading, and he's right
> better name for alarm

- support-frontend/assets/components/tabs/tabs.tsx
- support-frontend/typescript-errors.json
Fixes TS and ESLint errors in `assets/components/tabs/tabs.tsx`.
> Fix TS and ESLint errors in tabs.tsx

- support-frontend/assets/components/ticker/contributionTicker.scss
- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx
Adjust styling to show ticker on mobiles.
> show ticker on mobile landing page

- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/ga/GoogleAnalyticsService.scala
- support-modules/acquisition-events/src/test/scala/com/gu/support/acquisitions/ga/GoogleAnalyticsServiceSpec.scala
This PR fixes the Optimize tracking issue described in [this doc](https://docs.google.com/document/d/1g-hwtdMi1JGSQt4-RBTLad6-cg7SdShZnbtF7bf6RTQ/edit#)
> Fix GA Optimize tracking

- support-frontend/package.json
- support-frontend/yarn.lock
Update dependency `madge` following `dependabot` alert, this was used for the `yarn orphans` command, which I've tested and all is OK.
> Updated dependency madge

- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
We're now using a date that's in the past!
> Update card expiry date for post deploy tests

- support-modules/acquisition-events/build.sbt
Need to bump version of bigquery to fix a Snyk High Priority vulnerability report
> updated google-cloud-bigquery version

- build.sbt
- support-config/build.sbt
- support-frontend/build.sbt
- support-lambdas/acquisition-events-api/build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/build.sbt
- support-payment-api/build.sbt
- support-services/build.sbt
- support-workers/build.sbt
- supporter-product-data/build.sbt
This PR fixes up all the SBT deprecations which caused a wall of warnings when starting the project up
An example of the warnings:
> Fix SBT deprecation warnings

- support-services/src/main/scala/com/gu/support/promotions/PromotionCache.scala
The title says it all really, this log line is filling up the logs and doesn't add any value
> Remove some Scala logging which is unnecessary

- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/pages/DirectDebitForm.scala
- support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyCheckout.scala
- support-frontend/test/selenium/subscriptions/pages/PaperCheckout.scala
- support-frontend/test/selenium/util/Browser.scala
- support-lambdas/stripe-intent/src/main/scala/com/gu/stripeIntent/Handler.scala
- support-lambdas/stripe-intent/src/test/scala/com/gu/stripeIntent/HandlerSpec.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/AcquisitionDataRowMapper.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
- support-modules/rest/src/main/scala/com.gu.okhttp/RequestRunners.scala
- support-payment-api/src/main/scala/MyApplicationLoader.scala
- support-payment-api/src/main/scala/conf/ConfigLoader.scala
- support-payment-api/src/main/scala/model/db/ContributionData.scala
- support-payment-api/src/main/scala/model/paypal/PaypalApiError.scala
- support-payment-api/src/main/scala/model/paypal/PaypalPaymentSuccess.scala
- support-payment-api/src/main/scala/services/PaypalService.scala
- support-payment-api/src/main/scala/services/StripeService.scala
- support-payment-api/src/main/scala/services/SwitchService.scala
- support-services/src/main/scala/com/gu/support/promotions/dynamo/DynamoService.scala
I'm working my way through the huge number of deprecation warnings in the support-frontend Scala to fix them so that we can see what's going on a bit more during builds. I'm breaking the changes up into a few PRs to reduce the risk and the time it takes to review them!
I've tested this PR on CODE by running the post-deploy tests agains it and everything worked as expected.
[**Trello Card**](https://trello.com/c/vs7jhw7Z/294-fix-scala-deprecation-warnings-in-support-frontend)
> Fix deprecations in support-frontend

- support-config/src/main/resources/reference.conf
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
Fixes one integration test and sets another to be ignored
> Fix it tests2

- support-frontend/assets/helpers/images/imageCatalogue.json
Based on [PR for previous campaign](https://github.com/guardian/support-frontend/pull/3413/files)
/au/subscribe/weekly
/subscribe/weekly/checkout
/au/subscribe
/au/subscribe/weekly/gift
> Update GW images

- support-frontend/package.json
this would be useful after a rebase against main
> Run generate-history-csv.sh with yarn ts-errors

- support-frontend/app/controllers/WeeklySubscriptionController.scala
> Get /subscribe/weekly promo copy for AU

- .gitignore
I believe this folder is created by metals whenever I have the project open in VSCode. Adding it to the gitignore as I keep nearly commiting files in there!
> Add metals folder to gitignore

- support-frontend/cloud-formation/cfn.yaml
Follow up to #3593. This PR removes the old (now unused) security group.
> Prepare cfn template for cdk migration - phase 2

- .github/workflows/support-frontend-build.yml
> Rb gh on merge

- support-frontend/assets/pages/aus-moment-map/ausMomentMap.scss
Update Aus map colours for upcoming Aus election moment.
> Update Aus map colours for upcoming Aus election moment.

- .github/workflows/payment-api-build.yml
Following on from #3703 this adds a Github action to build the payment-api. Once this is merged I'll switch off the Teamcity build and switch the required check to the new action.
> Add an action to build the payment-api

- .github/workflows/env.yml
- .github/workflows/scala-steward.yml
We have a github action which should run against PRs from scala steward to make sure that the build is successful and all the tests pass. This is currently being skipped however, so this PR adds a debugging action to try to work out why.
> Debug scala-steward job

- .github/workflows/compressed-size.yml
- .github/workflows/ts-monitor.yml
Temporarily disable compressed size and TS monitor github workflows.
> Temporarily disable github workflows

- .github/workflows/compressed-size.yml
- .github/workflows/ts-monitor.yml
Re-enable the compressed size and TS monitor github workflows.
> Re-enable github workflows

- support-frontend/assets/helpers/__tests__/urlTest.ts
- support-models/src/test/scala/com/gu/support/workers/GiftRecipientSpec.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
We should not use that domain anymore.
> Remove reference to gu.com

- build.sbt
> update scala to latest version

- .github/workflows/scala-steward.yml
- build.sbt
- support-lambdas/acquisition-events-api/build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-workers/build.sbt
> Fix support-workers build

- support-payment-api/build.sbt
Reverts guardian/support-frontend#3753
> Revert "Update scaffeine to 5.2.0"

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.ts
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.test.tsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.test.tsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.test.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.tsx
> Remove DD from subs

- support-frontend/test/selenium/contributions/RecurringContributionsSpec.scala
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
> Disable DD tests

- support-frontend/assets/components/csr/csrMode.ts
- support-frontend/assets/helpers/subscriptionsForms/formActions.ts
~~This PR creates a new Redux Toolkit slice for the state related to 'CSR mode' and integrates it into the existing checkouts.~~
We’ve decided against placing CSR mode state in the store, as the CSR banner is present on pages where we don’t use Redux and therefore the component does not always have access to the store. There is an option to pass the store as a prop to a connected component but as the CSR banner is mainly used to provide a visual indication to a CSR that all is working correctly, it most likely does not need to be in the store.
[**Trello Card**](https://trello.com/c/XZClH0l6/480-%F0%9F%9B%A0-redux-toolkit-migration-refactor-csr-mode-state-%F0%9F%9B%A0)
~~This is part of work to overhaul our usage of Redux and migrate to using Toolkit to simplify and streamline working on …
> Refactor CSR mode related code

- support-frontend/build.sbt
Reverts guardian/support-frontend#3892
> Revert "Update okhttp to 4.10.0"

- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
Fixes the post deploy tests broken by #4045. The recaptcha is now in the second stage of direct debit so we need to update the selenium interactions to handle that.
> Fix post deploy tests

- support-frontend/assets/helpers/forms/paymentIntegrations/amazonPay/types.ts
- support-frontend/assets/helpers/redux/checkout/payment/amazonPay/actions.ts
- support-frontend/assets/helpers/redux/checkout/payment/amazonPay/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/amazonPay/state.ts
- support-frontend/assets/helpers/redux/checkout/payment/contributionsSideEffects.ts
- support-frontend/assets/helpers/redux/checkout/payment/reducer.ts
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.ts
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayCheckout.tsx
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayLoginButton.tsx
- support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayWallet.tsx
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.tsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts
Migrate all of the amazon pay state to a new rtk slice.
[**Trello Card**](https://trello.com/c/QV0tVrre/537-%F0%9F%9B%A0-redux-toolkit-migration-create-amazon-pay-reducer-%F0%9F%9B%A0)
> Migrate Amazon Pay to rtk slice

- support-frontend/assets/pages/promotion-terms/weeklyTerms.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx
This updates various bits of copy for the savings over base retail price of a GW subscription in different regions.
> Update GW savings percent figures

- support-frontend/assets/helpers/forms/formValidation.ts
- support-frontend/assets/helpers/redux/checkout/payment/contributionsSideEffects.ts
- support-frontend/assets/helpers/redux/checkout/payment/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/sepa/actions.ts
- support-frontend/assets/helpers/redux/checkout/payment/sepa/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/sepa/state.ts
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.ts
- support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
- support-frontend/assets/pages/contributions-landing/components/SepaForm.test.tsx
- support-frontend/assets/pages/contributions-landing/components/SepaForm.tsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts
Migrate SEPA to RTK slice.
[**Trello Card**](https://trello.com/c/ZS1YlotU/534-%F0%9F%9B%A0-redux-toolkit-migration-create-sepa-form-reducer-%F0%9F%9B%A0)
> Migrate SEPA to RTK slice

- support-frontend/assets/components/paypalExpressButton/PayPalExpressButton.tsx
- support-frontend/assets/helpers/forms/paymentIntegrations/payPalActions.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts
- support-frontend/assets/helpers/redux/checkout/payment/payPal/actions.ts
- support-frontend/assets/helpers/redux/checkout/payment/payPal/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/payPal/state.ts
- support-frontend/assets/helpers/redux/checkout/payment/reducer.ts
- support-frontend/assets/helpers/subscriptionsForms/formActions.ts
- support-frontend/assets/helpers/subscriptionsForms/formFields.ts
- support-frontend/assets/helpers/subscriptionsForms/formReducer.ts
- support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.ts
- support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
- support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.tsx
- support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
- support-frontend/assets/pages/contributions-landing/contributionsLandingInit.ts
- support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.tsx
- support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.tsx
- support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.tsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx
Migrate PayPay to RTK slice.
[**Trello Card**](https://trello.com/c/cAXRnQw2/538-%F0%9F%9B%A0-redux-toolkit-migration-create-paypal-reducer-%F0%9F%9B%A0)
> Migrate PayPay to RTK slice

- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/ContributionSubscriptionBuilder.scala
Reverts guardian/support-frontend#4070 - just in case!
> Revert "Change the Customer Acceptance Date to tomorrow for Recurring Contributions"

- support-payment-api/src/main/resources/cloud-formation.yaml
We're following the same steps outlined in the [corresponding support-fontend migration](https://github.com/guardian/support-frontend/pull/3593) PR.
>  Prepare cfn template for cdk migration - phase 1

- support-payment-api/src/main/resources/cloud-formation.yaml
We're following the same steps outlined in the [corresponding support-fontend migration](https://github.com/guardian/support-frontend/pull/3593) PR.
>  Prepare cfn template for cdk migration - phase 2

- stripe-patrons-data/src/main/scala/com/gu/patrons/services/StripeSubscriptionsProcessor.scala
#4094 had another bug in it where we wouldn't wait for the `processSubs` method  to complete before recursing, this PR fixes that.
> Wait for sub processing to complete in StripeSubscriptionsProcessor

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Reverts guardian/support-frontend#4112
> Revert "Add test for guardian weekly currency internationalisation"

- support-frontend/assets/components/headers/header/header.tsx
- support-frontend/assets/components/headers/header/headerWithCountrySwitcher.tsx
- support-frontend/assets/components/headers/links/links.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingProps.ts
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.tsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
Remove Digital Subscription from Nav
When V1 launches, we will no longer be selling the digital subscription. However, there are multiple references to it on the support site and these must be removed shortly before launch of the V1 checkout
Released behind the ab-newProduct 0% AB test so they're visible to the variant only. This AB test has already been set-up and is in use for showing changes to the checkout, you can force the AB test to be visible as so: https://support.theguardian.com/uk/contribute#ab-newProduct=variant
[**Trello Card**](https://trello.com/c/qXSZM0bu/568-support-site-remove-digital-subscription-from-nav)
> Pd digital link remove

- support-frontend/test/scriptFile.scala
- support-workers/src/main/scala/com/gu/emailservices/SupporterPlusEmailFields.scala
PR to include the first payment date to the payment methods like Credit card, Amazon Pay and Paypal
[**Trello Card**](https://trello.com/c/3zLebulV/789-supporter-plus-ty-confirmation-email-add-firstpaymentdate)
> Added first payment date to payment methods

- support-frontend/assets/helpers/tracking/quantumMetric.ts
Reverting Quantum Metric's script source as they've found an issue with 1.32.16 which is leading to sessions not initiating.
> Revert QM script src

- support-frontend/assets/pages/supporter-plus-landing/components/landingPageHeading.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
Update heading and body copy to match the confirmed new wording (also used on the contributions checkout).
Just updating the placeholder copy - nothing more than that.
[**Trello Card**](https://trello.com/c/geIfdBxB/806-v2-checkout-update-heading-and-body-copy)
> Update heading and body copy on the new checkout

- support-frontend/assets/components/thankYou/feedback/FeedbackItems.tsx
- support-frontend/assets/components/thankYou/marketingConsent/marketingConsentItems.tsx
- support-frontend/assets/components/thankYou/signIn/signInItems.tsx
- support-frontend/assets/components/thankYou/signUp/signUpItems.tsx
- support-frontend/assets/components/thankYou/supportReminder/supportReminderItems.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouFooter.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
This updates the copy for the modules and footer on the Supporter Plus thank you page. 
Please see [this section](https://docs.google.com/document/d/1YBqE24iC2LZpdY_wfwLepgdN3zObpYe793DmAgdp_Pg/edit?hl=en-GB&forcehl=1#heading=h.3kb9nsnt6q24) of the copy update dock for the required copy combinations. Until we test the live checkout you can view these copy updates [here](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/) in storybook. 
[**Trello Card**](https://trello.com/c/wIJdGCxX/730-show-appropriate-copy-on-thank-you-page-for-v2-checkout)
Please click through the supporter plus thank you page screens in [storybook](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/) to view these updates.
> Update V2 Thank You Page Modules and Footer copy

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/components/personalDetails/personalDetails.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/guardianTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/patronsMessage.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
- support-frontend/stories/screens/SupporterPlusLanding.stories.tsx
This updates the copy for the Supporter Plus checkout page and adds the terms and conditions.
Please see [this section](https://docs.google.com/document/d/1YBqE24iC2LZpdY_wfwLepgdN3zObpYe793DmAgdp_Pg/edit?hl=en-GB&forcehl=1#heading=h.5ru6o3uva75w) of the copy update dock for the required copy combinations. Until we test the live checkout you can view these copy updates [here](https://62e115310aef0868687b2322-wzgwbltymm.chromatic.com/?path=/story/screens-supporter-plus-landing-page--default) in storybook. 
[**Trello Card**](https://trello.com/c/uFGQ1gPs/779-update-v2-checkout-form-copy-based-on-legal-feedback)
[**Trello Card**](https://trello.com/c/6Sog5EUs/698-v2-checkout-build-new-tcs-component)
View the Supporter Plus checkout/landing page [here in …
> Update V2 Checkout copy

- support-frontend/assets/components/paymentFrequencyTabs/paymentFrequencyTabButton.tsx
This adds `cursor: pointer;` to the v2 checkout frequency tabs
> Add cursor pointer to v2 checkout frequency tabs

- support-frontend/assets/helpers/redux/checkout/product/supporterPlus/supporterPlusAmounts.ts
- support-frontend/assets/helpers/redux/utils/setup.ts
- support-frontend/assets/pages/contributions-landing/components/DigiSubBenefits/helpers.ts
This hardcodes the pricing and threshold amounts on the front-end for the Supporter Plus checkout. 
[**Trello Card**](https://trello.com/c/r56jhHIM/600-set-all-pricing-and-threshold-amounts-for-the-new-supporter-plus-product-checkouts)
> Hardcode Supporter Plus pricing and threshold amounts

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Put 100% of the audience in the supporterPlus AB test.
> Put 100% of the audience in the supporterPlus AB test

- support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
A minuscule copy tweak requested by Marketing colleagues.
(before)
(after)
> Minuscule copy tweak for checkouts

- .github/workflows/support-workers-build.yml
- support-workers/cloud-formation/src/templates/lambda.yaml
> use java11 in support-workers

- .github/workflows/support-lambdas-build.yml
- support-lambdas/build-tc
Tested in CODE:
- acquisition-events-api
- acquisitions-firehose-transformer
- stripe-intent
> Migrate support-lambdas to github actions

- .scala-steward.conf
This PR configures Scala Steward dependency update PRs to be batched (multiple dependencies per PR) rather than a separate PR being raised for each update.
It also set the PR frequency to one per day at 10am, this should allow us to then configure this pull request to be merged automatically if it passes tests.
> Batch Scala Steward updates & set their frequency

- support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
This updates the selectors in the contributions Selenium tests to reflect the new structures, IDs and other selectors on the SupporterPlus checkout, and adds a consistent test ID to the payment button(s).
> Amend Selenium tests to work correctly with new checkout

- support-frontend/test/selenium/contributions/pages/ContributionThankYou.scala
Related to #4558, this also updates the selector for the thank you page verification.
> Amend test id for thank you page

- support-frontend/test/selenium/contributions/pages/ContributionThankYou.scala
> Check for thank you page ID, not class name

- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
the tests are failing because of this
> Update card expiry in IT tests

- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
This change allows payment methods to be reused for SupporterPlus products, as they currently are for contributions.
I have verified in CODE that with the change, the step function execution triggered by using an existing payment method succeeds (like [this one](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-CODE:543b9a70-3758-45aa-a8a5-e51a9e578739)), whereas without the change you can still try to use the existing payment method but the step function execution fails ([as here](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-CODE:048d3ad8-eed8-4bff-b065-2f8b51b8eafe)). I …
> Allow payment method reuse for SupporterPlus

- support-frontend/app/controllers/IdentityController.scala
- support-frontend/app/services/HttpIdentityService.scala
Before now, if we got a 4xx error from Identity (for example, if the email address we sent them was invalid), we would return a 500 to the client.
There are two problems with this. The first is that an invalid email address here is not a *server-side* error, so a 500 has the wrong meaning.
The second is that this triggers an alert we have set up to detect 5xx errors. We call this on the digital subscription checkout page when the user moves focus out of the email address input, and don’t show the user the resulting error immediately, so 5xx errors here produce unnecessary alerts.
This change instead returns the 4xx error we got from Identity to the frontend, avoiding alerting and returning a more semantically appropriate error.
> Propagate 4xx errors when getting user type

- support-frontend/app/controllers/Promotions.scala
If the url is https://support.thegulocal.com/p/WINTERSAMPLER
then it becomes:
https://support.thegulocal.com/uk/subscribe/paper?promoCode=WINTERSAMPLER&promoCode=WINTERSAMPLER2
> newspaper promo codes - WINTERSAMPLER

- support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
Copy Change VariantA
From->
"Regular, reliable funding from readers is vital for our future. It protects our independence long term, so we can report with freedom and truth. Support us monthly from just $2."
To->
"Regular, reliable funding from readers is vital for our future. It protects our independence long term, so we can report **freely and without outside influence**. Support us monthly from just $2.
> Nudge variantA copy change

- support-frontend/assets/components/priceCards/priceCards.tsx
I got quite confused by `currentAmountsLen`, `amountOfAmounts` etc - much of this logic is for deciding if the final button is full width
> hideChooseYourAmount refactor

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
- support-payment-api/src/main/scala/services/SupporterProductDataService.scala
- support-services/src/main/scala/com/gu/support/promotions/ProductPromotionCopy.scala
#4684 Didn't include the necessary AWS permissions to allow payment-api to write to the Dynamo datastore, this PR fixes that.
> Add policy for accessing Dynamo

- .scala-steward.conf
This PR configures Scala Steward dependency update PRs to grouped (multiple dependencies per PR) rather than a separate PR being raised for each update.
> Group Scala Steward Dependency updates

- support-frontend/assets/__mocks__/fetchMock.ts
- support-frontend/assets/__mocks__/stripeMock.tsx
- support-frontend/assets/components/button/_sharedButton.tsx
- support-frontend/assets/components/button/button.tsx
- support-frontend/assets/components/button/nonInteractiveButton.tsx
- support-frontend/assets/components/csr/csrBanner.tsx
- support-frontend/assets/components/footerCompliant/BackToTop.tsx
- support-frontend/assets/components/footerCompliant/FooterWithPromoTerms.tsx
This fixes a few of our files with check annotations against them on github
> Fix some files with check annotations

- support-frontend/assets/pages/kindle-subscriber-checkout/components/billingPeriodSelector.tsx
- support-frontend/assets/pages/kindle-subscriber-checkout/components/subscriptionBenefitsListData.tsx
This makes some requested copy changes to the checkout for migrating Kindle subscribers.
> Copy tweaks on Kindle subscriber checkout

- support-frontend/assets/components/checkoutNudge/checkoutNudge.tsx
- support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Nudging component, variant encourages single to modified annual recurring contributions. 
1. make the variant = control (annual)
2. remove ab-test 'singleToRecurringV3'
3. remove monthly nudge keep annual only
[**Trello Card**](https://trello.com/c/1RQ0geGv/1155-ab-test-variant-annual-nudge-100-remove-ab-test)
> Variant annual nudge 100%, Remove AB-test

- support-lambdas/acquisition-events-api/src/main/scala/com/gu/acquisitionEventsApi/Lambda.scala
It can be hard to tell when looking at these logs which messages are from which request. The request ID is mentioned in the start-end-report logs (which I think AWS provides?), but not in our logging in between. Adding the request ID like this will allow us to filter to a specific request more easily, hopefully helping to debug issues.
> Add request ID to acquisition-events-api logs

- .github/workflows/acquisition-events-api.yml
- support-lambdas/acquisition-events-api/src/test/scala/com/gu/acquisitionEventsApi/LambdaSpec.scala
Create  acquisition-events-api Github Actions workflow for CI.
[**Trello Card**](https://trello.com/c/JA5IVmUi/1192-support-acquisition-api-gucdk-migration-step-1)
This is  a precursor to migrating CloudFormation to CDK.
- [x ] No
> Add acquisition-events-api to Github Actions workflow for CI.

- support-lambdas/it-test-runner/cfn.yaml
Allowing IT tests access to CODE emails queue.
> Allowing IT tests access to CODE emails queue

- support-workers/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
#4891 Broke some integration tests, this fixes them.
> Fix it tests broken by removing UAT

- support-workers/cloud-formation/src/templates/cfn-template.yaml
#4884 removed code related to corporate digital subscriptions but I missed some code from the support-workers cloud formation
> Remove some unused code related to corporate subs

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
Add Tote bag to benefits in Australia 
[**Trello Card**](https://trello.com/c/AyN6IYu4/1237-🇦🇺-tote-bag-added-to-benefits-in-australia-engineering)
Copy change on checkout - only in AUS
Copy is:
Limited-edition Guardian Australia tote bag. Offer ends 31 May
Context:
Australia 10 years
- [ x] No
> Add tote bag to benefits in Australia

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
- support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
- support-frontend/assets/components/priceCards/priceCards.tsx
- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
First mobile optimisation test success, make variant the control.
1. make the variant = control (supporterPlusMobileTest1)
2. remove ab-test 'supporterPlusMobileTest1'
3. cleanup default component parameters
[**Trello Card**](https://trello.com/c/VHzUhykn/1271-end-supporterplusmobiletest1-a-b-test-and-put-the-variant-live)
https://github.com/guardian/support-frontend/pull/4791
> Variant mobile optimisation test1 100%, Remove AB-test

- support-payment-api/build.sbt
- support-payment-api/src/main/scala/conf/AmazonPayConfig.scala
> Update enumeratum and enumeratum-circe to 1.7.2

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
Remove emotionalBenefitTest AB test
[**Trello Card**](https://trello.com/c/RSbUi4r4/1324-remove-emotionalbenefittest-ab-test)
The emotionalBenefitTest AB test has reached completion, the results were not statistically significant so we’ll keep the control as is and remove the variant.
> Remove emotionalBenefit AB test

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
This `newspaperPriceCards` test reached completion and returned an un-statistically significant result so we're going to keep the control, and end the test.
> End the newspaperPriceCards AB test

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Enables PR ->  https://github.com/guardian/support-frontend/pull/4853
Build of the single less prominent designs. ab-test name 'singleLessProminent'
- Desktop web - designs below
- Mobile web - re-based on mobile optimisation variantA 
- Initial ONE_OFF only contribution types via URL query parameters or session storage need to be removed from the abtest group (not control or variant).
Variant Features/Assumptions->
1. Support Once entire component clickable (not just arrow).
2. Once clicked, Single tab remains visible (a refresh required to reset).
A ClickableCard component may be a more accessible way to contain multiple elements that can be mouse clicked (or the card itself can be tabbed onto and enter pressed to re-produce mouse-click). A working example of this is shown here (2nd …
> Enable ab-singleLessProminent

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#5054
> Revert "Enable ab-singleLessProminent"

- .gitattributes
- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
This causes some changes to support-frontend and payment-api cloudformation templates, which leads to some resources being recreated.
I've tested in CODE by making single and recurring contributions.
> Upgrade cdk

- support-payment-api/src/main/scala/backend/PaymentBackend.scala
> Enable SOI for single contributors

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
The objective of this PR as to help devs get set-up with VS CODE by offering recommended extensions and IDE settings.
VSCode supports the inclusion of [recommended extension](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)s in your workspace, these are defined in an `extensions.json` file located in the workspace's `.vscode` folder, In this file you can add a list of extension identifiers. I've included this file in this PR with the following recommendations:
```json
{
"recommendations": [
"esbenp.prettier-vscode", // fix prettier issues on save
"dbaeumer.vscode-eslint", // fix lint issues on save
"styled-components.vscode-styled-components", // auto complete style rules in IDE
"wanfu.jump-to-alias-file" // jump to alias imports
]
}
``` …
> Provide recommended extensions and settings for VS CODE

- support-workers/cloud-formation/src/templates/cfn-template.yaml
I forgot to include the “!Sub” when I added the Stage interpolation! :facepalm:
> Fix support-workers failed execution error message

- support-frontend/assets/helpers/tracking/googleTagManager.ts
Removes some information no longer necessary from the support sites Google Tag Manager events. Introduced over 5 years ago this was a dimension introduced to GA so we could report on whether the Payment Request API was available (see: https://github.com/guardian/support-frontend/pull/727), this isn't data we need to record anymore.
Cleaning out unused data from GTM tracking events ahead of a refactor.
> Remove getPaymentAPIStatus logic from Google Tag Manager events

- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
Reverts guardian/support-frontend#5162
This PR fixed a bug in the acquisition-events-api but broke the payment-api: I believe because the latter is an EC2 instance and I’ve closed the client without adding logic to re-open it. Reverting pending a fix, as single contributions are broken until this is fixed.
> Revert "acquisition-events-api: Close JsonStreamWriter and BigQueryWriteClient"

- support-lambdas/acquisition-events-api/src/main/scala/com/gu/acquisitionEventsApi/Lambda.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
In commit fc82dde5c51f863f7c8d1c479592204ba4390389, I began closing resources after each request. However, while the acquisition-events-api can handle this, the payment-api can’t! The former creates a new service on every request, but the latter doesn’t, so on the first request the client was closed and never reopened, causing single contributions to break. (These changes were reverted in commit 6dbcd65e785a0498adbe9d0cc709d6a6fa8760a4).
This commit moves the closing logic so the payment-api doesn’t close the big query client after the first request, while the acquisition-events-api can still close and re-open on every request.
Another option would’ve been to create a new service on every request to the payment api, but the storage write api seems designed to be used in more of a …
> BigQueryService: close resources, test everything

- .scala-steward.conf
- .scalafmt.conf
- project/LibraryVersions.scala
- project/build.properties
- project/plugins.sbt
- stripe-patrons-data/build.sbt
- support-frontend/build.sbt
- support-modules/acquisition-events/build.sbt
- support-payment-api/build.sbt
Reverts guardian/support-frontend#5145
> Revert "Non AWS Scala dependency updates"

- support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
- support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala
Previously, going direct to a checkout page, instead of following a link, would redirect to a URL with an empty `pre-auth-ref` parameter in the query string.
eg. `https://support.theguardian.com/uk/contribute?pre-auth-ref=`
With this change, if the page has no referrer the URL will have no `pre-auth-ref` parameter.
eg. `https://support.theguardian.com/uk/contribute`, as expected.
Referrer reporting to Ophan should be unaffected.
Thanks to @GHaberis for spotting this.
> Omit pre-auth-ref param when page has no referrer

- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
⚠️  Fix issue where the two step variants were displayed to all users inside and outside the test.
> two step checkout ab deployment fix

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Enabling the twoStepCheckout test
> Turn on twoStepCheckout test

- support-lambdas/it-test-runner/cfn.yaml
it's currently failing with error:
`not authorized to perform: events:PutEvents on resource: arn:aws:events:eu-west-1:...:event-bus/acquisitions-bus-CODE`
> Give IT Test runner event bus permission

- support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
- support-frontend/assets/components/stripeCardForm/stripeCardForm.tsx
- support-frontend/assets/components/stripeCardForm/stripeCardFormContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts
- support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
- support-frontend/assets/helpers/tracking/__tests__/__snapshots__/acquisitionsTest.ts.snap
- support-frontend/assets/helpers/tracking/__tests__/acquisitionsTest.ts
- support-frontend/assets/helpers/tracking/acquisitions.ts
When we merged the PR with these changes, we forgot to enable the test! This PR removes the test, accepting the variant.
> Accept variant in mandatoryZipCode AB test

- support-frontend/test/selenium/contributions/RecurringContributionsSpec.scala
- support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
- support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
- support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
Now that the direct debit form has been changed to an expanding form from a two-step form, the post-deployment tests need to be updated to handle the new flow.
> Update post-deployment tests for new DD form

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Make the National Delivery functionality available to everybody via a 100% AB test with only one variant.
> Set nationalDelivery AB test live at 100%

- support-frontend/assets/helpers/tracking/quantumMetric.ts
Quantum Metric flagged an issue with version `1.34.1` of their script and have requested we update the script, this PR implements their change request.
> Update Quantum Metric script

- support-frontend/assets/components/checkoutHeading/checkoutHeading.tsx
- support-frontend/assets/helpers/images/imageCatalogue.json
- support-frontend/assets/pages/supporter-plus-landing/components/landingPageHeading.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepTest/checkoutScaffold.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepTest/firstStepLanding.tsx
Adds new EOY US 2023 image and copy for US users.
[**Trello Card**](https://trello.com/c/IkscfJ9B/1624-us-eoy-checkout-image-copy-change)
> US EOY 2023 checkout image and copy change

- .github/workflows/deploy-fastly-snippets.yaml
Adding more 🐍 _**S**_ 🐍.
To fix my bad spelling.
> fix(typo): deploy-fastly-snippet => deploy-fastly-snippets

- support-frontend/assets/helpers/campaigns/campaigns.ts
Updating the tickerId as there is no `AUS` ticker file in S3.
> fix: make ausTicker2023 tickerId AU

- supporter-product-data/README.md
very basic - Feel free to push some more commits to this PR
> basic readme for supporter-product-data

- support-e2e/tests/gwCheckout.test.ts
Another go at fixing the worlds easiest typo error
> fix import typo

- .github/workflows/support-lambdas-build.yml
- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
- project/plugins.sbt
- stripe-patrons-data/build.sbt
- support-lambdas/acquisition-events-api/build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-lambdas/acquisitions-firehose-transformer/cfn.yaml
- support-lambdas/bigquery-acquisitions-publisher/build.sbt
- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/build.sbt
- support-lambdas/stripe-intent/cfn.yaml
- support-payment-api/build.sbt
- support-workers/build.sbt
- supporter-product-data/build.sbt
A somewhat manual revert of https://github.com/guardian/support-frontend/pull/5507 because https://github.com/guardian/support-frontend/pull/5528 meant I couldn't do it automatically.
There is quite a lot in that PR - and it's quite hard to test locally as there are very few tests.
I would like to revert this change and then try to deploy each part more incrementally and test locally as the current devx of this is very difficult. …
> revert: 264c3f3

- support-lambdas/acquisitions-firehose-transformer/README.md
- support-lambdas/acquisitions-firehose-transformer/build.sbt
Reverts guardian/support-frontend#5533
> Revert "fix: upgrade logback-classic to 1.3.14 in aquisition-firehose-transformer"

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/tracking/ophan.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/firstStepLanding.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
setup ab test in order to direct some users directly to the second page of the checkout
> Take users directly to second page of checkout

- support-frontend/app/controllers/DigitalSubscriptionFormController.scala
- support-frontend/conf/routes
Running through some code with @paul-daniel-dempsey and @GHaberis we realised this route is not used anywhere.
Less code, more fun and 🤑
> Remove thank you existing route

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
I should have removed some code comments that slipped through in a previous pr :s
> remove comments that slipped through in a previous pr

- support-frontend/assets/components/subscriptionCheckouts/digitalPlusPrintSummary.tsx
- support-frontend/assets/components/subscriptionCheckouts/directDebit/directDebitTerms.tsx
- support-frontend/assets/components/subscriptionCheckouts/layout.tsx
- support-frontend/assets/components/subscriptionCheckouts/layoutStyles.ts
- support-frontend/assets/components/subscriptionCheckouts/threeTierTerms.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/helpers/utilities/timePeriods.ts
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierConfig.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Correction to Quarterly BillingPeriod Type Failure On Original PR -> https://github.com/guardian/support-frontend/pull/5644
Reverts guardian/support-frontend#5646
> Revert "Revert "Three tier Guardian Weekly checkout changes""

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierDisclaimer.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierConfig.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
3-tier landing and checkout page - copy updates
- Tier Card copy
- Tooltip copy updates
- Tier Card2 header
- Main Copy
- Extra Tooltip
- Digital+print description enlarge
- Disclaimer
Tier Card's
Tooltip's
Disclaimer (desktop / mobile)
[**Trello Card**](https://trello.com/c/AJZ1yIDO/548-3-tier-landing-and-checkout-page-copy-updates-additional-tooltip)
Checkout can be viewed at the following url behind (currently disabled) ab-Test named `threeTierCheckout` ->
> Three tier copy update to config and tier3 disclaimer

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/helpers/campaigns/campaigns.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/firstStepLanding.tsx
removing old code from the last campaign
> Remove US EOY

- support-workers/cloud-formation/src/templates/cfn-template.yaml
Create PROD resources on the `CreateProdResources` check.
> fix: CreateProdResources on SupportThreeTierPROD

- support-frontend/package.json
- support-frontend/yarn.lock
Updated @guardian/consent-management-platform to 13.1.1
[**Trello Card**](https://trello.com/c/np6jZJHk)
Keep CMP up to date.
Tested in CODE.
> Bump @guardian/consent-management-platform to 13.1.1

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#5729
> Revert "3-tier: activate ab-test threeTierCheckoutV2"

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/digital-subscriber-checkout/components/billingPeriodSelector.tsx
- support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
Removes these PR's
https://github.com/guardian/support-frontend/pull/5618
https://github.com/guardian/support-frontend/pull/5630
https://github.com/guardian/support-frontend/pull/5632
https://github.com/guardian/support-frontend/pull/5633
https://github.com/guardian/support-frontend/pull/5634
abtest not succesful
> Remove unused (US) emotional benefits ab-test

- support-frontend/app/controllers/CreateSubscriptionController.scala
This PR allows users to send double the amount of body size to the create endpoint.  From 100k to now 200k for this endpoint.
This means that users can spend more time editing their details and building up debug info before it would get a 413 error from the endpoint.
Although the documentation for play-circe is not too detailed, it's clear how to override the max length https://github.com/jilen/play-circe/blob/da0959ea58c8eb42b92e9c1bea88c523a2f56f74/src/main/scala/play/api/libs/circe/Circe.scala#L42
the default global for play is set here: https://www.playframework.com/documentation/3.0.0/api/scala/play/api/mvc/PlayBodyParsers.html#DefaultMaxTextLength:Long
This PR also includes a little refactoring.
Tested locally and created a Guardian Weekly successfully.
> increase the size of create payload to 200k

- .github/workflows/playwright.yaml
I introduced a formatting error in `playwright.yaml` used by our e2e Github Action.
> Fix formatting issue with playwright.yaml

- support-frontend/app/controllers/PricesController.scala
The prices encoder had no explicit type and used an auto decoder.
This meant that if you added an explicit type, it would cause it to depend on itself and therefore cause a NPE [1]
This PR changes it to a semiauto so that we can add a type.
A type is important because if we switch over to Scala 3, types are required on all implicits.
Also, it's risky to have code that misbehaves at runtime if a type is added!  Especially as this code path is used by dotcom, so unless you check the logs you won't realse you have broken it!
semi auto: https://circe.github.io/circe/codecs/semiauto-derivation.html
[1]
```
Caused by: java.lang.NullPointerException: Cannot invoke "io.circe.Encoder.apply(Object)" because "encoder" is null
at io.circe.syntax.package$EncoderOps$.asJson$extension(package.scala:24) …
```
> safely add explicit type to prices encoder

- support-e2e/tests/tieredCheckout.test.ts
These aren't passing in PROD - let's turn them off until we know why to avoid noise in further PRs.
> Skip promocode e2e tests

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Copy adjustment on TierCards for promotions ->
[**Trello Card**](https://trello.com/c/HvmqvZfU/726-promo-small-print-overlays-the-cta-on-tier-card)
> Tier Card Promotion copy adjustments

- support-e2e/tests/tieredCheckout.test.ts
Playwright promotion offer text
Tests corrected to match below ->
Expected Results->
> Playwright promotion offer text test corrected

- support-e2e/tests/gwCheckout.test.ts
Related to #5865 #5860
Inactivates one last PayPal test
> Inactivate one last PayPal test

- support-frontend/assets/helpers/legalCopy.ts
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierTsAndCs.tsx
Tier Card Price Rounding (2-decimal places) on non-whole amounts
[**Trello Card**](https://trello.com/c/1n6J7gE7/741-tier-card-price-rounding)
> Promo: Discount price rounding 

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Hoists values that aren't dependant on the component state out of the component.
This
- is generally good practise to not redefine values on each component render
- Helps with the [refactor I am doing](https://github.com/guardian/support-frontend/issues/5882) to get the [product catalog](https://product-catalog.guardianapis.com/product-catalog.json) into the `ThreeTierLanding` and avoids muddying that PR
Should be a complete no-op.
> Hoist static values out of component

- support-frontend/assets/components/offer/offer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierConfig.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
AB Test to show the Book benefits, Ts&Cs and thankyou page. 
This will be `enabled` & displayed to 100% US audience.
[**Trello Card**](https://trello.com/c/iJV8lQJc/729-add-book-benefits-copy-to-the-us-landing-pages-and-ty-pages-15th-april-if-possible)
|ab-additionalOffers=control|original|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/729d04ab-7c2d-4173-b8ef-fe91d8dc8b8b)|![image](https://github.com/guardian/support-frontend/assets/76729591/4690f46d-0ff9-447e-81cc-c87c679943f1)|
https://support.thegulocal.com/us/contribute#ab-additionalOffers=control
> Three tier (US book) benefit offers

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
No-op refactor to make the `onSubmit` a little more readable, and to make it more procedural when adding new payment methods and products.
You can see this starting to happen here #5920
> refactor: make checkout onsubmit async

- support-frontend/assets/helpers/abTests/abtest.ts
Part of https://github.com/guardian/support-frontend/issues/5829
Fixes `noUncheckedIndexedAccess` errors in `abtests`.
- Mostly adds `undefined` checks
- Sets the `@typescript-eslint/no-unnecessary-condition": "off"` eslint rule on the file. This can sometime leave unnecessary code, but never buggy code
- Adds the [non-null assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) as a bit of a cheat - but the code doesn't change so we should be good
> fix: noUncheckedIndexedAccess in abtests

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#5911
To be merged on Monday 9am.
> [MERGE_LATER] Revert "Enable US free book offer on three-tier"

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/guardianTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Generic checkout displays Ts&Cs for recurring Contribution & SupporterPlus products.
|Contributions|S+|
|------|------|
|![image](https://github.com/guardian/support-frontend/assets/76729591/67fbe39f-0a57-449d-8c52-b4b3a66ffdcf)|![image](https://github.com/guardian/support-frontend/assets/76729591/314a98af-e33f-4b1c-82bb-26dc6bad9fb9)|
[**Trello Card**](https://trello.com/c/c702Si1X/808-ts-and-cs-in-generic-checkout)
https://support.thegulocal.com/uk/checkout?product=Contribution&ratePlan=Annual&price=30
https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Annual&price=95
> Generic checkout Ts&Cs

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Global AB test on the 3 tier landing page
- Control: "Subscribe" across all 3 buttons
- V1: ‘'Select’' across all 3 buttons
- V2: ‘'Support’' across all 3 buttons
- V3: ‘'Support’' on tier 1 and "Subscribe" on tier's 2 and 3
[**Trello Card**](https://trello.com/c/Bg8x3k7Y/826-3-tier-lp-cta-test-subscribe-cta-support-continue)
> Three Tier Landing Page AB Test : Change Tier Card CTA

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Turn on the `tierCardCtaCopy` AB test.
> Enable tierCardCtaCopy AB test

- cdk/lib/__snapshots__/acquisition-events-api.test.ts.snap
- cdk/lib/acquisition-events-api.ts
we're migrating alarms to google chat
> Update acquisition-events-api alarm topic

- support-frontend/assets/components/personalDetails/stateSelect.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
State Selector Added for US,CA,AU 
[**Trello Card**](https://trello.com/c/ihabrisb/802-form-validation-for-generic-checkout)
> Generic checkout state selector add

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
PaymentFields corrected  for DirectDebit (removes PaymentMethod). Checkout operating as expected
[**Trello Card**](https://trello.com/c/ihabrisb/802-form-validation-for-generic-checkout)
> Generic Checkout :  Remove paymentMethod directDebit

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Ensure Generic Checkout has a 'signed in' feature
[**Trello Card**](https://trello.com/c/EdqM43Oy/809-signed-in-on-generic-checkout)
> Generic Checkout :  Signed-In

- support-frontend/assets/components/personalDetails/stateSelect.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Part of https://github.com/guardian/support-frontend/issues/5722
State & ZipCode validation for the Generic Checkout
|State|ZIP Code|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/90035668-c2c1-4ca7-b598-7c6e9091a984)|![image](https://github.com/guardian/support-frontend/assets/76729591/35fd847b-0977-4c0b-9ad6-2d0732b074c2)|
[**Trello Card**](https://trello.com/c/ihabrisb/802-form-validation-for-generic-checkout)
> Generic checkout:  zip-code & state validation

- support-frontend/assets/helpers/internationalisation/Readme.md
- support-frontend/assets/helpers/internationalisation/countryGroup.ts
Add a type for supportinternationalisationId to restrict acceptable values.
> Add type for supportinternationalisationId

- support-frontend/assets/helpers/redux/checkout/payment/payPal/thunks.ts
Apply the promotion to the price we send to PayPal to ask for.
This shouldn't have taken money from anyone unwittingly as that's just how much _**we can take**_ vs how much _**we do take**_, which would be the discounted amount.
| Summary | PayPal |
|---|---|
| ![Screenshot 2024-05-31 at 12 43 21](https://github.com/guardian/support-frontend/assets/31692/129e4072-1f87-48ec-af4d-088004d223b4) | ![Screenshot 2024-05-31 at 12 43 34](https://github.com/guardian/support-frontend/assets/31692/86148193-be2b-4246-8028-5278e1291ef6) |
Tests to come
> Apply S+ promotion to price we send to PayPal

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
[Viewing without whitespace is recommended](https://github.com/guardian/support-frontend/pull/6049/files?w=1)
- Puts the button into the white background box
- Updates text on button to be "Pay £x per Month" (with currency and frequency alternatives)
- Adds Patrons text
The Ts and Cs read differently to PROD, but I think this is because we're being more specific to the product.
> fix: update styling of payment button and ts and cs on checkout

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the benefits you're missing out on to the checkout.
> Add missing benefits to checkout

- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/package.json
- support-frontend/yarn.lock
Upgrades valibot. ~Hopefully~ A smaller filesize (-1.37 kB) and some new features.
> chore(deps): upgrade valibot

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Add `supportAbTests` to checkout.
I was just going through the `TODOs` and this stood out.
> Add supportAbTests to checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Adds `variant` to `useGenericCheckout` test
> chore(test): activate `useGenericCheckout` test

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#6082
> Revert "chore(test): activate `useGenericCheckout` test"

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreateZuoraSubscriptionState.scala
- support-models/src/main/scala/com/gu/support/workers/states/ExecutionTypeDiscriminators.scala
- support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
- support-workers/src/main/scala/com/gu/emailservices/ThreeTierEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
- support-workers/src/main/scala/com/gu/zuora/productHandlers/ZuoraTierThreeHandler.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SupporterPlusSubcriptionBuilder.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/TierThreeSubscriptionBuilder.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
This PR adds the new Tier Three product into the code base as a separate product rather than an additional rate plan in Supporter Plus. Reasons for this are explained in [this document](https://docs.google.com/document/d/1NOata7_3YNsZ97bd312QQ9MYJrmko55CaO4D77ExUhI/edit?usp=sharing)
> New Tier Three Product

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds notification of stripe payment errors to the generic checkout.
This is an initial step - I'll be adding some more to the page incrementally.
Testing was done with [these testing card details](https://docs.stripe.com/testing).
> feat: add stripe payment errors to generic checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
1. Change Tier3 S+ hard coded prices under abtest `july2024PriceRise`
|Country|Monthly Before|Monthly After|Annual Before|Annual After|
|-----|-----|-----|-----|-----|
|US|![image](https://github.com/guardian/support-frontend/assets/76729591/d5a4dfc6-9f12-42e9-b054-1f569804fb8b)|![image](https://github.com/guardian/support-frontend/assets/76729591/0eb0c8d2-de1c-46d5-97a6-6e1a6ce1f25a)|![image](https://github.com/guardian/support-frontend/assets/76729591/5ea6612a-7bbe-45c4-9804-d4af47fbf9e0)|![image](https://github.com/guardian/support-frontend/assets/76729591/d3d9e643-1e10-4aad-ab5b-23265c53b51b)|
|UK|![image](https://github.com/guardian/support-frontend/assets/76729591/7f9b96cb-c4c6-4237-bb6e-e2551c71d58c)|![image](https://github.com/guardian/support-frontend/assets/76729591/795c8617-ff94 …
> Tier3 Price Rise - July price update  (S+ and GW)

- support-frontend/assets/components/paymentRequestButton/hooks/payerDetails.ts
Reverts guardian/support-frontend#6142
Mandatory Country & State are required for US/CA/AU, even ApplePay/GooglePay users (so these fields need taking from there even if they conflict with a valid PromoCode region).
> Revert "ApplePay/GooglePay: PromoCode supplied is not applicable in this country"

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Put Feast Landing page A/B test live which makes Feast benefit offer visible, we can merge #6151 after this 
[**Trello Card**](https://trello.com/c/t3jT2OEL/946-put-feast-landing-page-a-b-test-live)
> Turn on Feast offer AB test

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/helpers/productCatalog.tsx
Hide partner offer - revert showing that new benefit
> Hide partner offer

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/helpers/productCatalog.tsx
Reverts guardian/support-frontend#6171
> Put Aus partner offer live 🇦🇺 

- .github/workflows/playwright.yaml
Add repo name to alert description
> add support-frontend to E2E alert description

- support-frontend/assets/components/subscriptionCheckouts/threeTierTerms.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/manageMyAccountLink.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
This PR adds the new approved disclaimer text and T&Cs link to the Tier Three checkout
[**Trello Card**](https://trello.com/c/pUvH8d1p/920-tier-legal-disclaimer-and-link-to-new-tcs-copy-to-be-added-to-new-tier-3-checkout)
[**Doc containing agreed disclaimer text**](https://docs.google.com/document/d/1WmhVI_44gdKj7Eztzh5xmzSxVh8d7y22/edit)
[**Overall T3 progress doc**](https://docs.google.com/document/d/1exq06PZVjPwJ88o2vV8yeU9Fd-C0ey6DBGQYxGkGOB0/edit)
[**New T3 T&Cs page on dotcom**](https://docs.google.com/document/d/1exq06PZVjPwJ88o2vV8yeU9Fd-C0ey6DBGQYxGkGOB0/edit)
> T3 disclaimer

- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
Fixes a small oversight in non-hardcoded dates in tests.
> fix: hardcode dates in EmailFieldsSpec

- support-e2e/tests/genericCheckout.test.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-e2e/tests/utils/cookies.ts
- support-e2e/tests/utils/testUserDetails.ts
Playwright : Tier3 testing chnags :-
- Remove repeat 2xcontribute genericTests
- Add 3xTier3 test (per paymentType)
- Add Billing/Delivery address difference test
- Rename tests into Tiers
[**Trello Card**](https://trello.com/c/X65MMrZ8/974-end-2-end-testing-tier-3-generic-checkout)
`cd e2e-support`
`yarn test-local`
> E2E Playwright Testing : Generic Checkout Tier3 

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
As we've been working through the file and the PRs, the order in which the code is run, currently bottom to top, is confusing.
This is a no-op, but puts the initially run code at the top.
> fix: reorder Checkout and CheckoutComponent for clarity

- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
We want to switch over to selling the new bundled version of our tier three product. This PR does that by using an ab test as a feature switch, future PRs will remove the old T3 code.
[This doc](https://docs.google.com/document/d/1exq06PZVjPwJ88o2vV8yeU9Fd-C0ey6DBGQYxGkGOB0/edit#heading=h.im2cmlja4jaf) tracks all the work that has been done.
> Switch on T3

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouFooter.tsx
Follow on design review from this [PR](https://github.com/guardian/support-frontend/pull/6210)...
Spacing adjustments and footer copy removal
[**Figma**](https://www.figma.com/design/E4KGImPY7IiIyEn8yKfDh4/GLive-events?node-id=346-4926&t=uKPLYvl5YRXHnmRQ-1)
[**Trello Card**](https://trello.com/c/915GAuRd/965-ticket-tailor-ui-refinement)
https://support.thegulocal.com/uk/events?eventId=4452337&chk=296a
|Mobile|Desktop|
|-----|-----|
|![image](https://github.com/user-attachments/assets/836e7ea5-82fc-4ae5-a94e-7878a018625b)|![image](https://github.com/user-attachments/assets/858d1c31-c1fa-4c6d-8f7b-41d85fd9f2ea)|
> Ticket Tailor: UI Review Revisions

- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Tidy the Tier 3 AB test after the real Tier 3 product has gone live. 
[**Trello Card**](https://trello.com/c/ZaGaRI9h/1013-unpick-and-remove-old-tier-3-checkout-changes)
Tier 3 (the real product) is live and stable, we can remove the hardcoded elements from the codebase. Doing this piece by piece.
> Tidy up Tier 3 AB test

- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
This PR wraps the first name used on the Thank You page in a `<span>` with the attribute `data-qm-masking="blocklist"`, this blocks QM from reading the first name, so it won't be rendered in playbacks.
> Use data-qm-masking on TY page

- support-e2e/tests/smoke/promo-codes.test.ts
Copy / pasting the promoCode tests into the new playwright smoke tests.
> feat: add promoCode tests to playwright smoke tests

- support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
Some extra logging to try work out why login isn't working on live.theguardian.com.
My hunch is that the referrer here isn't going to be `live.theguardian.com` - it will be `support.theguardian.com` or missing.
> chore(debugging): add logging to calculate what the referrer is on live.theguardian

- support-frontend/assets/components/payPalPaymentButton/payPalOneOffContainer.tsx
- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/helpers/__tests__/utilitiesTest.ts
- support-frontend/assets/helpers/contributions.ts
- support-frontend/assets/helpers/forms/checkouts.ts
- support-frontend/assets/helpers/redux/checkout/product/selectors/cartValue.ts
- support-frontend/assets/helpers/redux/checkout/product/selectors/selectedAmount.ts
- support-frontend/assets/helpers/utilities/utilities.ts
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
> Cover transaction cost refactor

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
Update the copy used in the cover transaction cost (#6277) checkbox and its styling
> feat: update styling and copy of cover transaction checkbox

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Reverts guardian/support-frontend#6300
> Revert "fix: add contribution amount to order-summary"

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Turning on `coverTransactionCost` ab test
> Turn on `coverTransactionCost` ab test

- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- Thankyou page asterisk text displays discount and original amounts when PromoCode used.
- Test with non-promoCode's
|before|after|noPromo|
|![image](https://github.com/user-attachments/assets/eb5f4247-3430-428a-abe3-35570e48b1f6)|![image](https://github.com/user-attachments/assets/72ffe452-bf2c-4590-8e4a-37eab97659f2)|![image](https://github.com/user-attachments/assets/954f6ea5-71fe-4483-9cf9-13eabceb03d1)|
> Thankyou page asterisk text displays discount and original amounts when PromoCode used

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
> AB test for 'one-tab' on landing page

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/orderSummaryText.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductOptions.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
Reverts guardian/support-frontend#6322
#6322 causes a problem with promotions being applied to T3. Reverting while I investigate.
> Revert "New Plans for T3 archive benefit"

- support-frontend/assets/components/otherAmount/otherAmount.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/[countryGroupId]/validation.ts
PriceCard `OtherAmount` Validation->
- Starts With Validation Disabled
- No Item entered (after focus lose)
-  Non-numeric entered (after focus lose)
[**Trello Card**](https://trello.com/c/1zyFpDGD/1073-one-time-generic-checkout-form-validation-upon-defaultpaymentbutton-request)
|Initial Startup|Empty|Invalid Entry|
|![image](https://github.com/user-attachments/assets/11d919f1-a3cb-4bc3-9d8c-b0f55e0e91b9)|![image](https://github.com/user-attachments/assets/86d58e8a-a1dc-4dc7-8494-4ae5685f3cd2)|![image](https://github.com/user-attachments/assets/7e35ae76-ef29-4f53-a4cb-1677250f0ebc)|
> One Time Checkout - PriceCard Other Amount Validition

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/orderSummaryText.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductOptions.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
This PR reapplies the changes in #6322 with a [fix for the bug](https://github.com/guardian/support-frontend/pull/6328/commits/5a2ce32e0f5e2ddb4dcbb229bf50f5f7ca145f1e) in that release
> Reapply "New Plans for T3 archive benefit"

- support-e2e/tests/oneOffContributions.test.ts
1. Playwright Landing Page One-Time Test : button changed to link
2. Tier3 annual replaces Tier2 annual
> Playwright Landing Page One-Time Test : button changed to link

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds RECAPTCHA as required field before you can re-submit form for payment.
> Checkout - Recaptcha required to resubmit form

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This PR has changes to select One-time tab from the Epic Urls .To do this we have to use the 'oneTime' query params
> Changes to land on One-time tab from the Epic Urls

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- Bring up the PayPal Checkout
- Allow payments
[**Trello Card**](https://trello.com](https://trello.com/c/WSpTNzCA/1086-generic-checkout-one-time-paypal))
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/de032c4f-6b98-445f-b812-a70c8284fcef)|![image](https://github.com/user-attachments/assets/a804e1ff-2703-4373-a30a-34fdc78f121b)
|
> One-Time Checkout : PayPal Checkout

- support-frontend/app/controllers/PayPalOneOff.scala
- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/conf/routes
- Route to the  genericCheckout oneTime Thankyou pages
- FROM `https://support.thegulocal.com/uk/thankyou`
- TO `https://support.thegulocal.com/uk/thank-you`
[**Trello Card**](https://trello.com](https://trello.com/c/WSpTNzCA/1086-generic-checkout-one-time-paypal))
OLD : `https://support.thegulocal.com/uk/contribute/checkout?selected-contribution-type=one_off`
NEW:: `https://support.thegulocal.com/uk/one-time-checkout`
|from|to|
|-----|-----|
|![image](https://github.com/user-attachments/assets/0ff4807e-ff1d-40ba-946c-0d87b8bd126e)|![image](https://github.com/user-attachments/assets/9bbafb22-718d-4eea-a878-fd1f5f1c11f0)|
> One-Time Checkout : PayPal Thankyou

- support-e2e/tests/cron/one-time-checkout.test.ts
- support-e2e/tests/genericCheckout.test.ts
- support-e2e/tests/oneTimeCheckout.test.ts
- support-e2e/tests/smoke/one-time-checkout.test.ts
- support-e2e/tests/smoke/promo-codes.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/test/oneTimeCheckout.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-e2e/tests/utils/testUserDetails.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Playwright Cron and Smoke test setup for generic one-time checkout
Added (part of defined test) ->
- US ZipCode optional field
[**Trello Card**](https://trello.com/c/15RJdcGR/1107-generic-checkout-one-time-playwright-test-setup)
`yarn test-cron`
`yarn test-smoke`
> One-Time Checkout : Playwright

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Matching Ts&Cs to /checkout
[**Trello Card**](https://trello.com/c/RMtejCAY/1147-one-time-checkout-ts-and-cs)
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/38a70499-45e9-4f6b-bb2b-8aafb199059a)|![image](https://github.com/user-attachments/assets/df9b9dc7-eaac-496f-ad71-83fc16dced01)|
> One-Time Checkout : T's & C's

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
#6414 missed a few references to the old promo code field in the client side code
> Remove promo field from client

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Updating the copy for support another way to reflect the different philanthropy-based contribution options.
[**Trello Card**](https://trello.com/c/ff1GkVz8)
> Change copy on support another way for US only

- cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
- cdk/lib/stripe-patrons-data.ts
Migrate alarms for stripe-patrons-data application to SR centralised notification application.
> feat: migrate alarms for stripe-patrons-data application

- .github/workflows/playwright-cron.yml
Changing the description - these alarms are not triggered by PRs as its a cron job.
> Playwright - update cron alarm message

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Turning on Link payment wallet A/B test
> Turn on link test

- support-frontend/assets/helpers/tracking/quantumMetric.ts
- support-frontend/assets/pages/[countryGroupId]/components/thankyou.tsx
What are you doing in this PR?
Fires the new conversion one-time and recurring conversion events.
[Trello](https://trello.com/c/H1okzlsN/1173-qm-events-part-3-conversion-tracking)
This PR does not cover:
- Reporting one-time-checkout value from the 3-tier landing page
> QM : Report conversion value from generic thankyou

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
Put `variantA` cover transaction component live, as tested in `coverTransactionCost` A/B v2.
> put coverTransactionCost variantA live to 100%

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Updates the copy in the landing page.
Also refactors the config in productCatalog.tsx to make it easier to reuse copy.
> Update Landing Page copy

- support-frontend/app/controllers/SubscriptionsController.scala
Replace the minimun Paper price with the Weekend Paper Delivery Price
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/72cc271f-a1b8-4f29-8421-1ecaf9088803)|![image](https://github.com/user-attachments/assets/ff8ae4c5-0403-42a3-b3cb-ba33b6b21fb7)|
> Subscribe : Landing Paper SubsCard, replace the minimun Paper price with Weekend Paper Delivery Price 

- support-frontend/app/controllers/DiagnosticsController.scala
We sometimes have users with signin issues which are hard to debug, this just adds a little more info to see whether support frontend can see those cookies (without revealing their value, only its length)
> add identity cookies to diagnostic info

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#6501
> Revert "One Time Checkout : Set Test Live"

- support-frontend/assets/helpers/tracking/__tests__/thirdPartyTrackingConsentTest.ts
- support-frontend/assets/helpers/tracking/thirdPartyTrackingConsent.ts
- support-frontend/package.json
- support-frontend/yarn.lock
- Updating @guardian/libs to latest version.
- Migrating from deprecated ccpa to usnat.
- 
To be compliant with latest framework/
- Tested support functionality in CODE.
- Tested __gpp function.
> Update @guardian/libs to 19.1.0

- lighthouserc.json
Increase lighthouse `resource-summary:document:size` threshold.
We've been close to the threshold for a while, and have recently exceeded it multiple times (slightly). While we get a better understanding of what we want out of this, increase the budget by 10%.
-  [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-vi …
> Increase lighthouse resource-summary:document:size threshold

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/test/actions/ActionRefinerTest.scala
- support-frontend/test/admin/settings/SwitchesSpec.scala
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/test/controllers/SiteMapTest.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-frontend/test/fixtures/DisplayFormMocks.scala
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
Add the ability to remove countdowns in case of problems.
[**Trello Card**](https://trello.com/c/gECTtqrM)
If there are significant problems with the countdowns, we need the ability to turn them off quickly.
Use the feature switch in the RRCP switches dashboard for the appropriate stage.
> Add a countdown feature switch

- support-frontend/build.sbt
Upgrade the `io.github.bonigarcia:webdrivermanager` test dependency.
This brings in a more recent version of
`org.apache.commons:commons-compress` (Dependabot has reported a vulnerability for the version we're on).
> Upgrade io.github.bonigarcia:webdrivermanager

- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalDetailsFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Refactor a `PersonalDetailsFormFields` component out of the checkout. This pushes the complex jsx down, and some of the state can be private to this component.
[**Trello Card**](https://trello.com/c/LPsGE92d/1156-explore-refactor-checkouttsx)
Attempting to break down the very large checkout component. …
> Refactor a `PersonalDetailsFormFields` component out of the checkout

- support-frontend/assets/helpers/campaigns/campaigns.tsx
> Stop forcing on US campaign

- support-frontend/assets/helpers/productPrice/productOptions.ts
Re-display the Saturday newspapaer product
[**Trello Card**](https://trello.com/c/BbbSOtmO/1294-add-3-print-offer-options-back-to-newspaper-landing-pages)
https://support.thegulocal.com/uk/subscribe/paper#HomeDelivery
> Subscribe : Re-display print package Saturday

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
We didn't capture any issues with this logging, the problem we were troubleshooting was caused by something different
> Remove sentry logs from events page

- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/helpers/legal.ts
- support-frontend/assets/helpers/urls/externalLinks.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/form.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/accordianComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Signed-off checkout revsions
- `Back` to `Change` button
- top summary
- bottom summary
- Ts&Cs
- Remove `Patrons` and  lower TsCs plus spacing
- Benefits Change
[**Trello Card**](https://trello.com/c/7EM3IYtS/1246-guardian-ad-lite-checkout-copy-changes)
https://support.thegulocal.com/uk/checkout?product=GuardianAdLite&ratePlan=Monthly
> Guardian Ad-Lite: Checkout Revisions

- cdk/lib/support-workers.ts
The support-workers.ts file which defines the CDK for support-workers didn't conform to our prettier rules so this PR formats it correctly.
There are no functional changes so the snapshot is unchanged.
> Fix formatting in the support-workers.ts CDK lib

- support-frontend/assets/components/thankYou/guardianAdLite/activateSubscriptionReminder.tsx
- support-frontend/assets/components/thankYou/guardianAdLite/whatNext.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/helpers/productCatalog.ts
Thank-you page copy updates->
1. Signed-In
2. Not Signed-In
3. Not Registered (Guest)
[**Figma**](https://www.figma.com/design/daOtcjwsPKfCc1GvSpuBn7/Consent-or-Pay---user-flows?node-id=2315-35348&t=3DNoc53pK3CYU93W-1)
[**Trello Card**](https://trello.com/c/HlsQv2PP/1371-guardian-ad-lite-thank-you-page)
|Signed-In|Not Signed-In|Not Registered|
|![image](https://github.com/user-attachments/assets/bd44ac5c-80a2-4a26-ac55-39c18aa744a2)|![image](https://github.com/user-attachments/assets/27338fb5-45f2-404d-a0eb-b0bd6a3a2453)|![image](https://github.com/user-attachments/assets/1f688fad-5663-4171-99d0-a3ed0d9bc611)|
> Guardian Ad-Lite: Thank-you Copy Updates

- support-frontend/assets/helpers/page/analyticsAndConsent.ts
- support-frontend/package.json
- support-frontend/yarn.lock
Bumps @guardian/libs to the latest version.
Using non advertising vendor list.
Ensuring support-frontend uses non advertising banner. (Part of Consent or Pay work)
Tested in CODE.
> Update guardian/libs to 21.1.0

- support-e2e/package.json
Adding a custom script for running the cron playwright tests against CODE.
I wanted to run this to test a change and found there wasn't a script for it.
> Add script to run cron tests against CODE

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/accordianComponent.tsx
Change Copy in Accordian row2 as shown ->
|from|to|
|-----|-----|
|![image](https://github.com/user-attachments/assets/2d9cbe57-e637-49c0-b071-29e7e4045e7d)|![image](https://github.com/user-attachments/assets/590a4092-990d-46c9-bf35-de0787da42bf)|
> Guardian Ad-Lite: Accordian copy change, question2

- support-e2e/yarn.lock
Updating the support-e2e lockfile.
I missed committing this in #6819.
> Update the support-e2e yarn lockfile

- support-frontend/package.json
- support-frontend/yarn.lock
Bumping @guardian/libs to latest version.
For Consent or Pay release
> Bump @guardian/libs to 22.0.0

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/accordianComponent.tsx
|from|to|
|----|----|
|![image](https://github.com/user-attachments/assets/60f3b945-2ea2-4043-ab43-f1ac479ee307)|![image](https://github.com/user-attachments/assets/c176eaf3-911f-4e70-8e0e-0118578b4279)|
> Guardian Ad-Lite: Revert accordian contact us copy

- .github/workflows/bundle-analyser.yml
Fixing some small issues which came up after merging #6806.
> Fix the bundle analyser workflow to work with pnpm

- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/helpers/legalCopy.ts
- support-frontend/assets/helpers/supporterPlus/benefitsThreshold.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
- support-frontend/stories/checkouts/SummaryTsAndCs.stories.tsx
- support-frontend/stories/checkouts/paymentTsAndCs.stories.tsx
Create Storybook of the Terms and Conditions components shown below:-
- paymentsTsAndTcs component
- summaryTsAndCs component
[**Trello Card**](https://trello.com/c/hUjNytsY/1495-onetimecheckout-checkout-tscs-components-snapshot-test-setup)
The ensure ALL changes affecting Ts&Cs are flagged and accepted.
Visual regressions will be flagged for accpetance with the github action `UI Checks`
|summaryTs&Cs|paymentTs&Cs|
|----|----|
|![image](https://github.com/user-attachments/assets/213b5c90-2e4e-494c-8d3e-7d7af3564253)|![image](https://github.com/user-attachments/assets/b64b0242-b877-4efb-8bf4-987961a069e8)|
> Checkout: Ts&Cs Components Testing Storybook Approach

- lighthouserc.json
Bump the resource-summary:document:size threshold (lighthouse metric).
This lighthouse check is failing on every PR merge which is spamming the SR Dev chat channel. We've got an agenda item to discuss what to do with this check later in the week but for now lets increase the threshold slightly so we stop spamming the chat channel.
> Bump the resource-summary:document:size threshold

- support-frontend/assets/components/thankYou/subscriptionStart/__snapshots__/subscriptionStartItems.test.tsx.snap
- support-frontend/assets/components/thankYou/subscriptionStart/subscriptionStartItems.tsx
- support-frontend/assets/components/thankYou/thankYouModule.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/pages/[countryGroupId]/components/__tests__/thankYouComponent.test.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/assets/pages/digital-subscriber-thank-you/digitalSubscriptionThankYou.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
- support-frontend/stories/checkouts/thankYouModule.stories.tsx
Re-use existing `subscriptionStart` component. 
Apply copy (shown below) for
- Guardian Weekly (portion of TierThree)
- Newpaper (delivery)
- Newspaper (subscription Card)
Dates
- NewpaperHome/National we need delivery date.
- GuardianWeekly we need the publication date.
NewsPaper Header Copy Update (complete /pending)
- Newspaper Pending : `Look out for an email from us confirming your subscription. It has everything you need to know about how to manage it in the future. As well as future communications on how to make the most of your subscription and weekly newsletters written by the editors.`
- Newspaper Complete : <above> + `You can opt out any time via your account`
Add Storybook tests
Add Component tests
[**Trello Card**](https://trello.com/c/EJkcUEb2/1483-ty-component-modify-existin …
> Checkout Thankyou: Subscription Start Component

- support-frontend/app/controllers/Application.scala
This is needed to get promo information for these products on the generic checkout.
> Add product price information for Guardian Weekly and Digital Subscription

- support-frontend/app/controllers/SubscriptionsController.scala
Show subs card Saturday as the minimum paper price on subscriptions landing page
### Before:
> Subscription Landing Page Newspaper Pricing

- support-frontend/app/config/Configuration.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/services/StripeCheckoutSessionService.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/app/wiring/Services.scala
- support-frontend/assets/components/paymentMethodSelector/paymentMethodData.tsx
- support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.tsx
- support-frontend/assets/helpers/forms/checkouts.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/forms/paymentMethods.ts
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/formDataExtractors.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/sessionStorage.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripe.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
- support-frontend/assets/pages/[countryGroupId]/components/paymentFields.ts
- support-frontend/assets/pages/[countryGroupId]/components/submitButton.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
- support-frontend/conf/routes
- support-frontend/stories/landingPage/PaperProductPrices.stories.tsx
- support-frontend/test/services/StripeCheckoutSessionServiceSpec.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentProvider.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
This PR implements the first part of the Stripe hosted checkout flow. For HomeDelivery/Sunday selecting the `Credit/Debit card` payment option and clicking `Continue to payment` will:
* Validate the user form data
* Create the checkout session with Stripe
* Redirect the user to Stripe (client side redirect)
* If the Stripe checkout is successful, redirect back to the checkout with the checkout session ID set as a URL fragment
This is not a complete flow. In prod the Stripe hosted checkout option will be hidden by a switch until ready. We also won't be showing any cards directing the user to the checkout for Sunday.
Missing elements:
* Persisting the user's details on the form before they are redirected to Stripe
* Processing the sub when the user returns to the support site
~~**Note: I'm …
> Stripe Hosted Checkout: Validate form data and redirect to Stripe

- lighthouserc.json
Increasing the allowed max document size for the Lighthouse tests
> Increase maximum allowed document size

- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
Following on from https://github.com/guardian/support-frontend/pull/6927 we don't want to alarm on card declined errors, as these are common and the user should be able to retry.
> Don't alarm for card declined errors

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
This PR adds more transaction declined messages which we want to ignore for now.
> More transaction declined messages

- .github/workflows/dependabot.yml
Fix the GH workflow which runs on dependabot PRs.
I noticed that this action was failing for dependabot PRs, I think this must have started after merging #6806 to switch to pnpm.
I temporarily commented out the condition in the dependbot workflow, and saw the dependabot workflow pass on this PR.
> Fix dependabot action

- .github/workflows/dependabot.yml
Run bigquery-acquisitions-publisher tests for dependabot PRs
Dependabot is opening PRs against the bigquery-acquisitions-publisher, so we should test it.
> Run bigquery-acquisitions-publisher tests for dependabot PRs

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Set similarProductsConsent  experiment active status to true
Start the AB Test.
[Control](https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly#ab-similarProductsConsent=Control)
[VarianA](https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly#ab-similarProductsConsent=VariantA)
[VarianB](https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly#ab-similarProductsConsent=VariantB) …
> Set live A/B/C test on recurring generic checkouts for SOI

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Set `oneTimeContributionConsent ` experiment active status to true.
[**Trello Card**](https://trello.com/c/eaLTl5zd/1611-set-live-a-b-c-test-on-one-time-journey)
[Control](https://support.thegulocal.com/uk/one-time-checkout#ab-oneTimeContributionConsent=Control)
[VariantA](https://support.thegulocal.com/uk/one-time-checkout#ab-oneTimeContributionConsent=VariantA)
[VariantB](https://support.thegulocal.com/uk/one-time-checkout#ab-oneTimeContributionConsent=VariantB) …
> Set live A/B/C test on One time journey

- support-frontend/build.sbt
~~Upgrade~~ Remove `io.github.bonigarcia:webdrivermanager` ~~to 6.1.0~~.
[**Trello Card**](https://trello.com/c/0TTsr3nH/1672-critical-vulnerability-on-support-frontend-dev-dependency-bonigarcia-webdrivermanager)
Dependabot has reported a vulnerability for the version of this package, and I don't think it's used.
> Remove io.github.bonigarcia:webdrivermanager

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/frontend.ts
- cdk/lib/payment-api.ts
- cdk/package.json
- pnpm-lock.yaml
This reverts commit 9616bbe3f42a48580d1952a0affec9eae86212e9, reversing changes made to 22f951c815340db9dbb8a4df11f1c1467ee3c44d. (Added in #7044).
The gu/cdk release 61.5.0 (which the reverted PR includes) needs to be released in two stages because of a breaking change. Currently deploys are failing. I'm going to revert and then use the two step approach.
> Revert "Merge pull request #7044 from guardian/dependabot/npm_and_yarn/cdk/guardian/cdk-61.5.1"

- support-frontend/assets/helpers/coreWebVitals/withCoreWebVitals.tsx
Increase the CWV sampling rate from the default (1%) to 20%.
Now that we're graphing this data from prod I can see that we're seeing quite spiky graphs. I think increasing the sampling may improve this.
> Increase CWV sampling to 20%

- support-frontend/assets/helpers/images/imageCatalogue.json
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentHeader.tsx
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentHeaderStyles.tsx
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentProductCardStyles.tsx
Add Grid Images for the student landing page.Images vary for diferent breakpoints:
- Desktop
- Tablet
- Mobile
[**Trello Card**](https://trello.com/c/JALZkATM/1708-update-image-on-the-aus-landing-page)
Design specs
> Update Image on the AUS landing page

- support-frontend/build.sbt
Upgrading `com.gu:simple-configuration-ssm` to the latest version.
Although this is a bump of many major versions it seems straightforward. The changelog doesn't look too scary (https://github.com/guardian/simple-configuration/releases) and the code compiles/smoke tests pass.
This pulls in a new version of `io.netty:netty-codec-http2` (`4.1.124.Final`). The current version has a vulnerability reported by Dependabot.
> Upgrade `com.gu:simple-configuration-ssm` to 7.0.0 in support-frontend

- support-workers/src/main/scala/com/gu/emailservices/SupporterPlusEmailFields.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
Adapt SupporterPlus email fields if the rate plan is fixed term
[**Trello Card**](https://trello.com/c/KijeZU8T/1820-add-an-identifier-to-crm-team-so-day-o-email-wont-have-reference-to-recurring-support)
Because in the email which these fields are used by we want to modify the copy depending on whether the product will auto renew.
This currently affects two email fields:
* `subscription_details` (existing field)
* `is_fixed_term` (new field which will be either the string `true` or the string `false`)
Currently the only fixed term S+ rate plan is `OneYearStudent`.
When this lambda is migrated to TypeScript we should use the product catalog (which has term type) instead of using a hard coded list of fixed term rate plans. We're not doing that now because we think the effort required to …
> Adapt SupporterPlus email fields if the rate plan is fixed term
