support-frontend/app/utils/CheckoutValidationRules.scala

There is a bug in the validation for Digital Subscription gift redemption for users in AU, US & CA because the validation was making state a required field in these countries and it is impossible to set it via the form.
This PR removes that validation

Don't require a state for DS gift redemptions

---

support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx

Show frequency buttons in all regions (before `GBCountries` was excluded), as per [this card](https://trello.com/c/0cT2L6dC/2449-update-uk-landing-page).

Show frequency buttons in all regions

---

support-frontend/app/controllers/CanonicalLinks.scala
support-frontend/app/controllers/DigitalSubscriptionController.scala
support-frontend/app/controllers/WeeklySubscription.scala

This is an update to the url builder for sharing links. This function wasn't taking gifting into account, so if someone tried to share the GW or DS gifting pages (using the share button on the browser on mobile) they would share the non-gift version of the page.
So people can share the gifting pages.

Add gifting url info to sharing links

---

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx

Remove the 25 December date from the Guardian Weekly checkout. Customers who select this date will not receive a paper until the week after.

Hide option to start subscribing to Guardian Weekly on Christmas day

---

support-models/src/main/scala/com/gu/support/zuora/api/PreviewSubscribeRequest.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscribeRequest.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscriptionData.scala
support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionPurchaseBuilder.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/ProductSubscriptionBuilders.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscriptionDataBuilder.scala
support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala

This PR makes the step functions write the gift notification date to zuora when a DS gift is purchased.
This field will end up in the DL, so we can do a one off report on this in a couple of weeks.
https://trello.com/c/gRopJsmH/3498-write-gift-delivery-date-to-zuora
CEX team are concerned that if a lot of gifts are scheduled for e.g. christmas day, it might cause a risk to support, as the call centre is not open over christmas/boxing day.
Tested in DEV:
https://apisandbox.zuora.com/apps/Subscription.do?method=view&id=2c92c0f975e5ba1e01761e9e1109498d
Tested in UAT:
https://apisandbox.zuora.com/apps/Subscription.do?method=view&id=2c92c0f975e5ba2601761e9f907d5bcb
I also tested a normal Direct DS in UAT.
PROD field name:

write gift notification date to zuora, when DS is purchased

---

support-frontend/assets/helpers/tracking/googleTagManager.js

This PR updates `googleTagManager.js`, I've created a new string variable `vendorConsentsLookup` in this module. Whenever a user updates their consent via the CMP we set the value of `vendorConsentsLookup` to be a comma delimited string of vendor names (eg. "google-analytics") that have had consent granted to them.
This variable `vendorConsentsLookup` is now pushed to Google Tag Manager (GTM), and will look something like "google-analytics,twitter,bing".
In GTM we can set a conditional check for each tag that must be met for the tag to be enabled. We have the ability to use a regular expression as part of this condition. I therefore propose for each tag we query `vendorConsentsLookup` in GTM using a regular expression. Eg. For Google Analytics to run we check the condition …

Pass comma delimited string of vendors with consent to GTM

---

support-frontend/assets/helpers/paymentIntegrations/readerRevenueApis.js
support-frontend/assets/helpers/subscriptionsForms/submit.js
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
support-frontend/assets/pages/subscriptions-redemption/api.js

This PR gets the client side to send a discriminator field when creating a subscription.  This means that it is explicit about which product the user is signing up for, rather than just looking at the shape of the data.
The next PR will actually use the PR on the server side.
https://trello.com/c/Mwb7aMda/3379-add-discriminator-to-producttype
We had a contribution that came through a few months without an amount, so the system tried to put it through as a digital subscription.  Luckily it failed for other reasons (payment) but this is a flaky situation to be in, so we decided to make things more explicit in case it breaks as we refactor things or add a new product.
part of the POST request from testing locally, per product
```
product: {productType: "Contribution", amount: 5, currency: …
```

send product discriminator when creating a subscription

---

build.sbt
project/LibraryVersions.scala

and also play-json (which depends on jackson-databind) to the version that this repo's version of play uses

update jackson dependency

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/heroGift/hero.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx

Removing the nudge from the CTA icon in the hero on the digisubs landing pages (gift and non-gift).
Because it looks silly. 
Thanks @jesseyuen!

Remove nudge from CTA digital subscriptions landing pages

---

support-frontend/app/controllers/DigitalSubscriptionController.scala

This PR updates the packshot used when sharing https://support.theguardian.com/uk/subscribe/digital via social media, as demoed here using https://cards-dev.twitter.com/validator.
[**Trello Card**](https://trello.com/c/N0PrkK0G/3441-update-digital-sub-open-graph-with-new-rebrand-packshot)

Update share image URL for Digital Subscriptions page

---

support-frontend/app/controllers/TestUsersManagement.scala
support-frontend/app/views/testUsers.scala.html

This PR adds a nice link to the test users Wiki page.  Also makes it a bit clearer what to use for what.
Ideally it could just have a list of links with the details prefilled for each product, but that might be a job for another day!
https://trello.com/c/Og2MS2Ts/3450-add-link-from-test-users-page-to-test-users-wiki-page
When we were testing gift DS throughout the whole subs team, a lot of us were having trouble!  Devs and non devs alike.

make the test users page more useful

---

support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/EmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/FailedContributionEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/GuardianWeeklyEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

This PR removes SF contact where it is not needed, for sending emails.  It only remains for gift notification for DS, as we do not have an identity id for the giftee notification email address.
https://trello.com/c/IfG3s7tM/3505-user-identity-id-instead-of-email-address-for-sending-emails
This is because when the email gets to braze, it somehow messes things up if we send using an SF contact id instead of identity ID. @paulbrown1982 has requested we use identity id where possible.
tested with the IT tests, also running the manual email send, all 9 emails arrived successfully.
ToDO, test in CODE manually once it's approved.

use identity id instead of sf contact id for most emails

---

support-frontend/assets/helpers/tracking/googleTagManager.js

This PR is a follow up to https://github.com/guardian/support-frontend/pull/2864. This PR ensures the consent state for the tags below is made available to Google Tag Manager (GTM) via the `vendorConsentsLookup` variable:
- Google Ads Remarketing
- Facebook
- Twitter
- Bing
This `vendorConsentsLookup` variable is pushed to GTM, and looks something like "google-analytics,twitter,bing".
I've prepared and tested the GTM configuration update to query this `vendorConsentsLookup` for the tags listed above and it works as expected, eg. only enabling a tag if it is matched in the `vendorConsentsLookup` comma delimited list.
[**Trello Card**](https://trello.com/c/ounKMMqR/3511-granular-vendor-consent-checks-for-tags-within-google-tag-manager)
Once this is merged I'll publish the configuration …

Pass additional vendors in vendorConsentsLookup to GTM

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/helpers/checkouts.js
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx

We are bringing back the Payment Request button (the purple button in chrome).
We want to find out if it competes with Paypal, and if it impacts retention as well as AV.
Only some users are able to see the button because it depends on their browser and if they have payments set up. So for the test analysis we need the ability to filter both the control and the variant for only people who can see the button.
We do this by emitting a special `payment-request-button-loaded` event to ophan, to indicate that the user _could_ see it.
This cannot be done at the time that they're assigned to the test, because we do not know until later on if their browser supports the button.

PRB A/B test

---

support-frontend/assets/components/subscriptionCheckouts/subscriptionsSurvey/SubscriptionsSurvey.jsx

Update the survey link on the Digital Subscriptions non-gifting Thank You page. We're leaving the survey link on the Digital Subscriptions gifting Thank You page as is.
[**Trello Card**](https://trello.com/c/bdPz3zNb/3519-change-survey-link-on-thank-you-page)

Update digital subscriptions survey link

---

support-frontend/assets/helpers/internationalisation/weeklyDeliverableCountries.js

Remove Bolivia from GW weekly delivery listRemove Bolivia from GW weekly delivery list.
The card also requested reinstating Cuba, but Cuba was already present, and removing Haiti, but Haiti was not actually present on the list. So no additional changes were required.
[**Trello Card**](https://trello.com/c/HQny6odY/3516-update-gw-delivery-countries)

Remove Bolivia from Guardian Weekly delivery list

---

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

Remove the 25 December date from the Guardian Weekly **Gifting** checkout. Customers who select this date will not receive a paper until the week after.
Non-gifting PR previously merged: https://github.com/guardian/support-frontend/pull/2862

Prevent users from starting GW gift on Dec 25

---

support-workers/build.sbt

This PR adds a deployToCode task so we can deploy support workers to code from sbt without having to go through a push/build/deploy cycle.
```
$ sbt "support-workers / deployToCode"
[info] welcome to sbt 1.4.4 (AdoptOpenJDK Java 1.8.0_265)
[info] loading global plugins from /Users/john_duffell/.sbt/1.0/plugins
[info] loading settings for project support-frontend-build from plugins.sbt ...
[info] loading project definition from /Users/john_duffell/code/support-frontend/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project root from build.sbt ...
[info] loading settings for project support-frontend from build.sbt ...
[info] loading settings for project support-workers from build.sbt …
```

add a deployToCode task for support-workers

---

support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx

This is a fix to reinstate a missing id for a selenium test.
Because of an error introduced in this PR: https://github.com/guardian/support-frontend/pull/2786

Fix for checkout selenium test: update inputId to be just 'id'

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

This is a second attempt to remove the inputIds from the code, so these can be passed in correctly and picked up by selenium. First attempt to fix in this PR: https://github.com/guardian/support-frontend/pull/2888
The issue was introduced in this PR: https://github.com/guardian/support-frontend/pull/2786

Remove inputId and replace with id for selenium tests

---

build.sbt
support-payment-api/build.sbt

ophan is now returning 400s since a play upgrade.
This change makes payment-api use the same dependency as support-workers, which is still working
I cannot test the actual ophan integration until it's in PROD, but have confirmed it still creates the correct payload in CODE

use acquisition-event-producer

---

acquisition-event-producer/src/main/scala/com/gu/acquisition/services/OphanService.scala

Revert #2893  
This is because the request was indeed double URL encoded:
```
message:Unable to decode Acquisition Event - expected json value got '%7B%22...' (line 1, column 1) @timestamp:Dec 17, 2020 @ 11:46:43.192 app:the-slab level_value:40,000 buildNumber:14558 source_stream:ophan logger_name:extractors.AcquisitionExtractor$ stage:PROD stack:ophan @version:1 level:ERROR thread_name:RecordProcessor-0015 _id:3MWGcHYBX3IuK76qFZFF _type:_doc _index:logstash-ophan-2020.12.17 _score: -
```
Instead to fix the acquisitions data issue, the Ophan team will tweak their app's Play configuration: 
https://github.com/guardian/ophan/pull/3986

Revert url encode 

---

support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/components/form.jsx

This stops click events aimed at the Source checkbox component used to confirm that the user can authorise a direct debit from getting intercepted by a `<span>` element that overlays the input to provide the nice ticking animation.
This is a **temporary** fix- this ought to be fixed in Source itself and I'll be raising a PR to that effect- but will stop the post-deploy tests from constantly failing.

Temporary fix to stop the tests failing on direct debit subscription payments

---

support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.jsx

Quick fix for a visual bug on the LP. This was caused by an update to source. The css we're using is a little hacky - it assumes knowledge of the internal structure of the `Radio` component. This css broke when source swapped out a `div` element for a `span` element. 
We should come up with a proper fix for this, but as it stands I don't think we can quite replicate the current behaviour without this hacky css. The tricky part to replicate is having the whole area between the label text and the image being clickable. That might require a change to source. In the mean time I think this quick fix will work. This is also potentially an argument for having some sort of visual regression testing (chromatic?).

Quick fix for LP layout bug

---

support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
support-frontend/test/selenium/subscriptions/pages/PaperProductPage.scala

This adds an ID to the main element on the paper landing page for the tests to select, as we're now styling with Emotion and the old class name is obsolete.

Fix the Selenium tests for the paper landing page

---

support-workers/cloud-formation/src/templates/cfn-template.yaml

This PR reverts one of the changes in https://github.com/guardian/support-frontend/pull/2891 as we still use the old name for the metric, so the alarm also needs to do the same.
[New exectutions](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-PROD:6b38cfef-a4de-4b6c-a453-17df87503431) still use the old name

use DigitalPack instead of DigitalSubscription for alarm

---

support-modules/bigquery/src/main/scala/com/gu/support/acquisitions/AcquisitionDataRowMapper.scala
support-workers/src/test/scala/com/gu/acquisitions/BigQuerySpec.scala

#2891 started sending subscription acquisition data to BigQuery, however there were a couple of mapping bugs which means that some data isn't being be saved to BigQuery correctly. This PR fixes this.

Fix some mapping bugs in AcquisitionDataRowMapper

---

support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala

This adds the sub number field to the test data for 
SendThankYouEmailITSpec
SendOldAcquisitionEventSpec
The IT tests are failing due to missing field that is now required in 
https://github.com/guardian/support-frontend/pull/2891

add sub number to the IT test data

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlock.jsx

This adds in special copy on the non-Aus digital subscriptions landing page referring to the end of year special edition.
[**Trello Card**](https://trello.com/c/EzXWkvR0)

Copy changes for 'The best of a bad year' special Edition

---

support-payment-api/src/main/resources/cloud-formation.yaml

We're getting a lot of ERROR logs for payment-api:
`Error udpating cache for recaptchaSwitch:. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied`
This particular error isn't actually causing any problems, but we shouldn't have ERRORs!
This is because the cloudformation grants permission to s3 objects under `/support-admin-console/PROD/*`, but PROD actually requires the CODE object as well.

Fix payment-api switches permission

---

support-frontend/build.sbt

Change the default heap size to the default (1/4 of physical memory) to free up more space for non heap.
https://trello.com/c/Zmb4UJdM/3553-investigate-out-of-memory-errors-on-support-frontend-instances
The support-frontend instances are kiling their JVMs after around 5 days due to the JVM process becoming too big for physical memory.
It looks like the heap size is 1gb and the t3.small have 2gb memory.  After 20 hours or so the process is using about 50% of memory, 
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                              
7746 support+  20   0 3717404 1.022g  19040 S   0.7 53.3  19:10.91 java
```
but after 5 days it is up to around 80%
```
PID …
```

use default heap size for JVM

---

support-frontend/app/controllers/DiagnosticsController.scala
support-frontend/app/wiring/AppComponents.scala
support-frontend/app/wiring/Controllers.scala
support-frontend/conf/routes

This PR adds a diagnostics endpoint to return several useful cookies in the response.  The user can then forward to us for debugging reasons.
We do have to be careful, as we are turning cookies from the server side into a response, so we don't want to make anything accsible via XSS or other JS that wouldn't otherwise be.  Therefore I have hard coded a list of allowed cookies which should not contain anything sensisive.  For example, it would be a very bad idea to return all cookies, because that would include the SC_GU_U identity log in cookie in the list allowing someone to impersonate the user if they got hold of it.
There seem to be a lot of strange issues with ad free and support asks.  Members data api generally seems to be ok, so there may be some client side issue or cookies issue. …

return list of interesting cookies for diagnostics purposes

---

support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala
support-frontend/test/selenium/subscriptions/pages/DigitalPackGiftCheckout.scala
support-frontend/test/selenium/subscriptions/pages/DigitalPackGiftProductPage.scala

This adds post-deployment Selenium tests for the digital subscription gift landing page and checkout. It also updates the way we determine the billing period in the digital subs checkout in order to enable the tests to run without being dependent on a query string in the URL.
[**Trello Card**](https://trello.com/c/GbmnFfY0)

Add post-deployment tests for digital subscription gifting

---

support-frontend/app/controllers/DiagnosticsController.scala

add a zero cookies screen for when there are no cookies, to make it not a blank page!
Also added some other useful info

improve the /cookies diagnostics page

---

support-lambdas/it-test-runner/src/main/scala/com/gu/RunITTests.scala

This will make the put metric request throw an exception if the metric isn't sent.
There seems to be an issue where metrics for the IT tests are not always getting sent.  This means we get alarms going off, but reading the logs, the tests all ran as they should.
I noticed in the code, if the put metric call throws an exception, this will be ignored.

throw an exception if the IT test metrics don't succeed

---

support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala

This adds a short sleep to DD checkouts to make sure the button really is available.
https://trello.com/c/GHM1Ib1W/3570-fix-selenium-tests
WE  are not sure why this is failing in the automated run but not locally.  It is thinking it clicked the button but it doesn't actually seem to click it.  Perhaps there's a race condition there.

add a short delay before trying to pay with DD

---

support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx

On hitting the 'Pay Now' button when paying by credit card, the button will now be disabled while we retrieve the token from Stripe. The button will be re-enabled on any error, and at the point where the 'Processing' overlay is shown.
[**Trello Card**](https://trello.com/c/eMuYMAnH)
This fixes an issue where users were occasionally repeatedly clicking the subscribe button before the 'Processing' overlay appeared, causing errors in processing the payment.

Prevent double submission of Stripe payment form

---

support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala

Change DS gift checkout post deploy test to use CC instead of DD
https://trello.com/c/GHM1Ib1W/3570-fix-selenium-tests
there seems to be a weird bug that only affects gift+DD combination!
When it clicks on the confirm DD button, the Pay button is there, but clicking it doesn't seem to have much effect (at least the first click).
We tried a 1s delay in this PR: https://github.com/guardian/support-frontend/pull/2915 but this is a backup PR in case that doesn't work enough.  We prefer to add a delay and still have the testing, rather than not testing the DD at all with DS.

Use CC checkout instead of DD for DS gift post deploy test

---

support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.jsx
support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
support-frontend/assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.jsx

- Disable Source's Focus Manager on subscription checkout page
In Source, there is a blue "halo" around interactive components. This is intended for when users tab into, for instance, a text input field. However, by default clicking on an interactive element also triggers the focus state, applying focus styles inappropriately.
By running [`FocusStyleManager.onlyShowFocusOnTabs()`](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/32e9fb), we can ensure the focus state only applies when the user presses the tab key, not when they click on the element.
A similar change was made to the contributions landing page in #2384
**Note:** I haven't tested this locally as I don't have the right Janus credentials 😖

Enable onlyShowFocusOnTabs on subscription checkout

---

support-frontend/assets/helpers/formValidation.js
support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/datePicker.jsx
support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/datePickerHelpers.test.js
support-frontend/assets/pages/digital-subscription-checkout/components/datePicker/helpers.js

This fixes the issue where the date picker in the digital subs gift checkout is failing validation when left on today's date if the user is in a location where midnight UTC is the previous day in their timezone.
It removes all validation regarding whether the date is 'too early', and amends the way we confirm the date to the user so it will always show the correct date relative to their timezone.
[**Trello Card**](https://trello.com/c/TCZHMVV0)
This has been causing the Selenium tests for the gift checkout to fail as the CI server is located in the US, and may have been preventing gift checkouts for users outside of the UK.
The backend doesn't care if a date that the user selects is in the past- the gift will always be sent immediately if the delivery date is not in the future- so there's …

Fix validation issues with the date picker in timezones outside of the UK

---

support-frontend/assets/helpers/subscriptionsForms/formReducer.js

We have discovered that trying to stringify the state when it contains an error can cause the following exception:
```
Uncaught TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
--- property '__v' closes the circle
at JSON.stringify (<anonymous>)
at formReducer.js:70
at redux.js:435
at redux.js:435
at p (<anonymous>:1:36402)
at v (<anonymous>:1:36684)
at <anonymous>:1:40069
at Object.h [as dispatch] (redux.js:213)
at e (<anonymous>:1:40553)
at index.js:11
at dispatch (redux.js:563)
at formValidation.js:81
at Array.forEach (<anonymous>)
at b (formValidation.js:80)
at h (formValidation.js:99)
at paperCheckoutForm.jsx:148
at Object.dispatch (index.js:8)
at dispatch (<anonymous>:1:28545)
at Object.validateForm (redux.js:449)
at Object.onClick …
```

Remove redux debug information

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlock.jsx

This removes the copy relating to the 'best of a bad year' end of year special edition from the digi subs landing pages.
[**Trello Card**](https://trello.com/c/bZNL5kUC)
**DO NOT MERGE** until Tuesday evening at the earliest

Remove copy relating to the end of year special edition

---

support-frontend/assets/helpers/productPrice/productPrices.js
support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.jsx

This fixes two issues relating to the price cards when promo codes were used:
- Promo codes applying a 100% discount will now show the £0 price correctly, instead of defaulting back to the base price
- Where more than one promo code is applied for a specific product, the Guardian Weekly landing page will no longer always show the first one regardless of the query string.
[**Trello Card**](https://trello.com/c/TpBHm3KU)

Fix issues with price cards incorrectly displaying content from promo codes

---

support-payment-api/src/main/resources/cloud-formation.yaml
support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
support-payment-api/src/main/scala/backend/PaypalBackend.scala
support-payment-api/src/main/scala/backend/StripeBackend.scala
support-payment-api/src/main/scala/backend/SubscribeWithGoogleBackend.scala
support-payment-api/src/main/scala/controllers/AmazonPayController.scala
support-payment-api/src/main/scala/controllers/PaypalController.scala
support-payment-api/src/main/scala/model/amazonpay/AmazonPayApiError.scala
support-payment-api/src/main/scala/model/stripe/StripeApiError.scala
support-payment-api/src/main/scala/services/CloudWatchService.scala
support-payment-api/src/main/scala/services/PaypalService.scala

"failed payment" - caused by an issue with a customer's card/account/details. Has a cloudwatch metric, `failed-payment`.
"payment error" - any other cause, i.e. software/infrastructure/integration problems. . Has a cloudwatch metric, `payment-error`.
1. We currently send `ERROR` logs for failed payments, e.g. card declined payment failures. These are not errors.
2. We do not have alarms for some genuine errors, e.g. failure to complete post-contribution actions like analytics.
The aim of this PR is to ensure all ERROR logs are software/infrastucture/integration errors that require immediate investigation. Additionally, these errors should always trigger an alarm.
1. Lower `payment-error` alarms threshold to 1. These should indicate something is broken and needs investigating.
2. Stop …

payment-api error handling improvements

---

support-frontend/app/controllers/CreateSubscription.scala
support-frontend/app/wiring/Controllers.scala
support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala

Adding a metric for any kind of server side validation failure
At the moment we return a 4xx error for validation failures.  This is not monitored anywhere except a line in the logs.
```
2021-01-21T17:31:15,640+0000 [application-akka.actor.default-dispatcher-4] ERROR com.gu.monitoring.SafeLogger$ - [ff50d14a-2928-92ec-0000-000000000001] Failed to create new Monthly Paper-HomeDelivery-Everyday subscription, due to RequestValidationError(validation of the request body failed)
```
I am about to improve the validation, so it made sense to have a metric, so that we can easily compare before/after error rates.  It would be nice to have an alarm on this, which we can add once we know the baseline.
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2:graph=~(metrics~ …

add metric for server side validation failures

---

support-payment-api/src/main/resources/cloud-formation.yaml

The threshold for these alarms was recently lowered to 1 - https://github.com/guardian/support-frontend/pull/2919/files
@johnduffell pointed out that the period can be lower.

Lower payment-api alarm period to 60seconds

---

support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.jsx
support-frontend/assets/helpers/subscriptionsForms/formReducer.js

Use a plaain string in the redux Action instead of a react component with a link.
https://trello.com/c/O0LclNV2/3586-add-back-debug-info-for-checkouts
The original PR stated that the error system could only pass around strings (presumably due to it going into an Action): https://github.com/guardian/support-frontend/pull/2434
then later the covid message was removed and it was inlined by mistake, so the Action had a react component in it.
caused this https://github.com/guardian/support-frontend/pull/2921
and it lso breaks Redux devtools (it hangs!)
the docs suggest not really allowed: https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow#state-is-read-only
> Since actions are plain JS objects, they can be logged, serialized, stored, and later replayed for debugging or …

don't put a react component inside a redux action

---

support-workers/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala

Fix the step functions so they will retry unlimited on an SSL error
https://trello.com/c/RmyRUx0V/3589-fix-stripeerrorsspec-test
The stripe errors spec was failing intermittently.  This is because we were expecting a Socket timeout on connect, but sometimes the connection was quicker than 1ms (presumably already open).  This meant we had a read timeout instead, which is returned as an SSL exception.
There is a point to be made about whether some SSL exceptions should fail straight away.  Otherwise it might be 24 hours before we find out about an issue with the hostname (e.g. salesforce migrates to a new URL?)  We could check the string of the exception as well perhaps?

make a read timeout cause a retry unlimited

---

support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcherContainer.js
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx

This PR fixes a couple small issues with the tracking on our country dropdown list. 
1. If `trackProduct` was undefined in `onCountryGroupSelect` we'd never track the interactions, this meant we would't track interactions from our `/support` and `/subscribe` routes, however we're now able to remove the `if { ... }` block around the `sendTrackingEventsOnClick` call as this takes an optional `product` argument.
2. Specify the correct value for `trackProduct` from the `/subscribe/digital` route: 'DigitalPack'
3. Remove the incorrect value for `trackProduct` from the `/subscribe` route: 'GuardianWeekly'
[**Trello Card**](https://trello.com/c/AZDrxIgG/3566-fix-ophan-click-tracking-on-the-country-dropdown-toggle)

Track country dropdown clicks/interactions

---

support-frontend/assets/components/orderSummary/orderSummary.jsx
support-frontend/assets/components/orderSummary/orderSummaryProduct.jsx
support-frontend/assets/components/orderSummary/orderSummaryStyles.js
support-frontend/stories/checkouts.jsx

The designs for adding the new print & digital option in the print checkouts include an updated version of the order summary which needs to be able to handle the display of more than one product. Also currently all our checkouts have their own, slightly different order summaries.
This adds an initial version of a new, generic order summary component, developed in Storybook and decoupled from Redux state.
[**Trello Card**](https://trello.com/c/OSsIhbE0)
Separating the presentational aspect of the order summary from the product-specific logic that determines what we display in it means this component should be reusable across all our checkouts in the future.
This is also a part of the print & digital work that's easy to break out into a separate PR, rather than having one giant PR with …

New order summary component for subscriptions checkouts

---

support-frontend/assets/components/product/giftNonGiftCta.jsx
support-frontend/assets/pages/showcase/components/otherProduct.jsx
support-frontend/assets/pages/showcase/components/otherProducts.jsx

Adds click tracking to CTAs which didn't have. These include the "patrons" and "masterclasses" buttons on https://support.theguardian.com/uk/support ([Trello card](https://trello.com/c/mHHfUHpJ/3563-add-missing-ophan-click-tracking-on-https-supporttheguardiancom-uk-support-ctas)) and the "See gift/personal subscription" buttons on https://support.theguardian.com/uk/subscribe/weekly and https://support.theguardian.com/uk/subscribe/digital ([Trello card](https://trello.com/c/CMuWYWfE/3568-track-clicks-on-the-see-gift-subscriptions-see-personal-subscriptions-ctas-in-ophan)).
More tracking capabilities on our components

Add click tracking to subscription CTAs

---

support-frontend/assets/helpers/abTests/abtest.js
support-frontend/test/selenium/contributions/OneOffContributionsSpec.scala

Currently we're storing AB test participations in local storage, and reading them for every page view. This is actually wrong as it may bring back tests that are no longer running.
There is no reason for storing the participations in local storage, as we can recompute on each page load, and it should be deterministic because it's based on mvt value.
This PR also ensures only contributions pages are assigned an amounts test variant.

Do not use localstorage for AB tests

---

support-frontend/assets/components/list/list.jsx
support-frontend/assets/components/orderSummary/orderSummaryProduct.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/content/giftBenefits.jsx
support-frontend/stories/checkouts.jsx
support-frontend/stories/content.jsx

This is an extension/improvement of the List component built for the Guardian Weekly page, to be able to re-use it in the print and digital checkout.
[**Trello Card**](https://trello.com/c/OSsIhbE0)
The new checkout design calls for bulleted lists in both the order summary and the 'add the digital subscription' CTA that have the same style and use of a secondary line of text, so it makes sense to have this be a single component. We already had a list component; this PR simply adds the ability to adjust the colour and size of the bullets, and inject a different component as the list item.
**In Storybook - mobile**
**In Storybook - desktop**
**In the OrderSummary component**
**On Guardian Weekly landing page (no regression from what's currently there)**

Extend existing list component for use in print & digital checkout

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js

This adds new copy on the digital subscriptions landing page for the campaign launching on 8th Feb.
[**Trello Card**](https://trello.com/c/sRRjYm1h)
Note that colours may look slightly different due to device/OS/browser differences. Devices are:
- Mobile: Galaxy S20/Android/Chrome
- Tablet: iPad 8th gen/iOS/Safari
- Desktop: Macbook Pro/macOS/Firefox
**Mobile**
**Tablet**
**Desktop**

Copy for new digital subscription campaign

---

support-modules/bigquery/src/main/scala/com/gu/support/acquisitions/AcquisitionDataRow.scala
support-modules/bigquery/src/main/scala/com/gu/support/acquisitions/AcquisitionDataRowMapper.scala
support-payment-api/src/main/scala/model/acquisition/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/test/scala/com/gu/acquisitions/BigQuerySpec.scala

This PR adds the new payment_id field to the data we send to the real time acquisitions data store.
Data tech team had to  the field to the PROD datatech-platform-prod.datalake.fact_acquisition_event - Mike has done that.
https://trello.com/c/qgzqat0H/3579-add-paymentid-into-factacquisitionevent-for-single-contributions
This is needed to join to some other data stores.  Not totally sure what, but it has been requested by @jranks123

add paymentid field to data that we send to bigquery in real time

---

support-frontend/setup.sh

This PR changed the `dev-nginx setup-cert` step to use sudo instead.
To avoid errors such as one below when installing. Not having this forces the developer to have to run all the setup commands manually from that point onwards.

Use sudo for nginx setup-cert

---

support-frontend/app/controllers/DigitalSubscriptionController.scala
support-frontend/app/wiring/Controllers.scala
support-frontend/test/controllers/SubscriptionsTest.scala
support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala

This adds a default promo to the DS landing page, meaning that the headline and subpara can be edited in the promo code tool.
This was the number 1 thing that marketing want when I asked.
Also, it's 10% time, and I decided to do this.
promo code tool
landing page

make the landing page use a default promo for all copy (DS only)

---

support-models/src/main/scala/com/gu/support/catalog/Product.scala
support-models/src/test/resources/catalog-prod.json
support-services/src/test/resources/catalog-prod.json
support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala

Using a recurring charge for Digital Subscription gifts has caused a problem which could result it us charging customers more than once - see write up in [this doc](https://docs.google.com/document/d/1rtbJpBxGcYPqBeWRx22RXwwINKHATQkQVN1K0cI0Wuw/edit#heading=h.az7pfdab0x11)
This change switches the product rate plan used for Digital Subscription gifts to one with a one-time charge to prevent this problem.
[**Trello Card**](https://trello.com/c/MTJTLYxb/3596-prevent-gifters-being-charged-recurringly-for-unredeemed-gifts-59)

New product rate plan ids for one time charges on DS gifts

---

support-services/src/main/scala/com/gu/support/catalog/CatalogService.scala

We have had a number of failed redemptions for digital subscriptions since #2952. This is because during the redemption step support-workers needs to find the product rate plan by id to work out the length of the sub and since the old product rate plan ids were removed it can no longer do that. 
This PR just adds the old ids back in for the PROD environment in the method that does the lookup. As that method is only used for this one purpose there is minimal risk of confusion with the new product rate plans.
There is an example of a [failed execution here](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-PROD:054a7a9b-b86b-4283-825c-5c86f6b6eb64)

Fix redemption of gift subs with recurring charge

---

support-logs/cfn.yaml
support-logs/riff-raff.yaml

This PR adds ARM instance and uses bionic ubuntu for support-logs proxy.
This is needed because ubuntu xenial isn't supported by AWS any more so the amigo bakes don't work.  Also we might as well use ARM instances because they are cheaper.
Wait for the result of https://amigo.gutools.co.uk/recipes/ubuntu-bionic-arm-with-nginx/bakes/1 before merging.

use bionic / arm AMI for support-logs proxy

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js
support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx

This fixes the issue where paragraphs parsed from the markdown generated by the promo code tool did not show up with proper spacing in the hero on the digital subs landing page.
I've also applied the same fix across the other product landing pages.
**Before**
**After**

Fix paragraph spacing on copy coming from promo codes

---

support-frontend/devrun.sh

Run `nvm use` in the foreground. I think by running it in the backgroud, we don't actually use the correct node version for the `yarn devrun` and `yarn storybook` commands - this fixes that!

Run `nvm use` in the foreground

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js

This is a small copy change on the hero of the digital subscriptions landing page. The change is for copy for all regions except Australia.
[**Trello Card**](https://trello.com/c/IiYiFqQN/3602-digital-subs-updating-lp-with-product-information)
To support the February campaign we need to update the digital subscriptions LP with product information.

Digital Subs - updating LP with product information

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx

Adding supporting text to the Paper home delivery checkout delivery instructions text area component.
[**Trello Card**](https://trello.com/c/0ANg5Dw7/3595-add-delivery-instructions-above-delivery-info-box-on-print-hd-checkout)
Our print distribution crew have flagged that delivery drivers are having difficulty finding the letterbox of many initial newspaper deliveries, especially in the winter darkness. Resulting in customer service complaints. The aim is to encourage people to add instructions and reduce the customer complaints.
1. Please note that I have altered the supporting text very slightly to 'Crinan Street' rather than 'Crinan St' as the screen reader was reading it out as 'Crinan saint'
2. The trello card asks that this field remains optional but without the optional flag. At …

Add delivery instructions above delivery info box on Print HD checkout

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx

The delivery instructions text area had an autocomplete popup on it, which wasn't appropriate.
For a better user experience.
This should have been a simple case of adding `autocomplete="off"` to the textarea component. However, when I added this attribute, it did appear in the html, but it didn't stop the autocomplete popup. This is apparently caused by an issue in Chrome, where they were trying to hand off decisions about autocomplete to the user (though still seemingly allowing developers to turn off autocomplete for a whole form).
There are a number of solutions suggested in this [stack overflow post](https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off) and the one that seemed least hacky to me was to set …

Remove autocomplete from delivery instructions field

---

support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx

Fix a bug where the form is still submittable if a user goes from having entered correct card details to incorrect details. This is pretty unusual behaviour but is actually affecting adding an optional field to the card form. The optional field isn't validated until data is entered. This makes the behaviour above (valid details -> invalid details) much more likely! 
Currently I've done the simplest fix - just updating the form completion on every keystroke. If we only want to update it when it changes, I can alter the logic to look  a little like:
```js
if (formIsComplete && !formWasComplete || !formIsComplete && formWasComplete) { 
props.setStripeCardFormComplete(formIsComplete);
}
```
Where we can get `formWasComplete` from the redux store.

Fix stripe card validation bug

---

support-payment-api/src/main/resources/cloud-formation.yaml

* Open ports 1514 and 1515 for outbound traffic
* Give permission to the instance to call describe-tags,
so the agent can identify itself in a human readable way with 
the wazuh server.
There's currently a major review of the guardian's security practices under the cyber security programme. One of the projects in this programme is to install a vulnerability scanner called Wazuh in guardian ec2 instances.
The scanner has already been installed in the ami image, but it's attempt to connect with the central server is being block by the instance security group. Hopefully this will fix it, otherwise I'll have to review network ACLs!
Works in code ✅

Payment api: Patch in necessary permissions for wazuh

---

support-frontend/cloud-formation/cfn.yaml

This is opening ports 1514 and 1515 for outbound traffic, which is currently restricted to port 443.
There's currently a major review of the guardian's security practices under the cyber security programme. One of the projects in this programme is to install a vulnerability scanner called Wazuh in guardian ec2 instances.
The scanner has already been installed in the ami image, but it's attempt to connect with the central server is being block by the instance security group. Hopefully this will fix it, otherwise I'll have to review network ACLs!
Works in code ✅

Allow outbound traffic from Wazuh scanner

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/heroGift/hero.jsx

We're not tracking clicks on the "pricing options" CTA on the Digital Subs landing page, this PR adds a tracking call in the click handler (for both the gifting and non-gifting landing pages).

Track "pricing options" CTA on Digital Subs landing page

---

support-frontend/assets/helpers/routes.js
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx

Currently all users see this, even if they have signed up.
If a user is signed in then we could find out from MDAPI if they already have a reminder, but I'm leaving this to a follow up task.
A new option for monthly:
The recurring request:
The single request still works:

Recurring reminders on the thank you page

---

support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.jsx

Adding validation to the state / province / territory address field for billing and delivery addresses so they can't be longer than 40 characters.
[**Trello Card**](https://trello.com/c/Xn0mmPUu/3601-add-40-character-limit-to-state-field-in-billing-and-delivery-address-form-25)
There have been a number of issues with customer payments recently, in which state names that are longer than we can store have been submitted. We'd like to prevent this from happening.

Add 40 character limit to state field in billing and delivery address form

---

support-frontend/assets/components/headers/links/links.jsx

I noticed when clicking on traffic drivers (eg. Banners) from the main site to the Support site that the navigation didn't indicate the initial active page on which I had landed. This is because the logic to set the active state on a navigation link doesn't take into account query string parameters, which all our traffic driving CTAs use for tracking purposes. This PR addresses that so when you click on a traffic driving CTA the nav will show the active state (the yellow bar) on the appropriate link.
Gives users landing on our site a better indication of where they are in relation to the navigation.

Show active navigation link even with query params in url 

---

support-frontend/assets/helpers/page/page.js
support-frontend/assets/helpers/tracking/ophan.js

The pageview table in datalake has a `referrerPageViewId` column, but it is rarely populated for support pageviews.
This is because the existing mechanism in tracker-js relies on attaching an event listener to links, and adding the id to localstorage, see:
https://github.com/guardian/ophan/blob/75b86abcce07369c8998521399327d436246c016/tracker-js/assets/coffee/ophan/click-path-capture.coffee#L41
We reliably add the REFPVID param to the querystring, so this PR uses that to set the localstorage item if it's not already set.
Using localstorage isn't ideal, but it works and I'd prefer not to make changes in ophan.
Now the initial ophan event includes `refViewId`:

Send refViewId to ophan

---

support-frontend/README.md
support-frontend/cloud-formation/cfn.yaml

Co authored with @i-hardy and @lucymonie 
This PR updates support-frontend to use SSM Tunnel
https://github.com/guardian/ssm-scala#enabling-ssm-tunnel
https://trello.com/c/mr8yEEdp/3634-switch-support-frontend-to-ssm
It's latest security best practice, it only relies on built in AWS infrastructure and AWS credentials.

make support frontend use SSM tunnel for SSH access

---

.travis.yml

following on from https://github.com/guardian/support-frontend/pull/2881
This makes sure travis uses the right version of scala also.
The tests are failing with a version mismatch

use the correct scala version in travis

---

support-frontend/assets/helpers/page/page.js
support-frontend/assets/helpers/tracking/ophan.js

Previous attempt: https://github.com/guardian/support-frontend/pull/2979
We're now sending `refViewId` with the initial ophan event.
However, we also need to send `ref` (which has the url), otherwise ophan ignores it. See here:
https://github.com/guardian/ophan/blob/75b86abcce07369c8998521399327d436246c016/the-slab/app/extractors/ReferrerExtractor.scala#L180
This change uses the `referrerAcquisitionData` object to get referrerUrl + referrerPageviewId, which we already construct for the acquisition event.
Example event in CODE:

Set referrer url

---

support-frontend/assets/helpers/tracking/googleTagManager.js

This PR simplifies the conditional that checks whether we can use Google Tag Manager by removing the part that checks whether Google Analytics has been granted user consent. We can do this as we're now passing Google Analytics consent state to Tag Manager and making that conditional check in tag manager.

Remove Google Analytics conditional check in-front of Tag Manager

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx

**DO NOT MERGE** before EOW (03/19)
Add an ab test for messaging of price breakdown.
[**Trello Card**](https://trello.com/c/NqjaV1Xq/2574-landing-page-copy-test-x2)

Add breakdown ab test

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx

This adds an extra line about the 'books of 2021' special edition to the digital subs landing page.
[**Trello Card**](https://trello.com/c/6XYK5hYb)

Digital subs copy update

---

support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx

This PR adds an Ophan event to record the wallet type if a transaction using the Stripe payment request button uses a wallet.

add ophan event for recording stripe prb wallet payments

---

support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx

Add "US" prefix to price breakdown for International to highlight that we charge US dollars on the international page.
[**Trello Card**](https://trello.com/c/CcV0J6af/2564-highlight-we-charge-us-dollars-on-international-landing-page)

Add "US" prefix to price breakdown for International

---

support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx

Makes a small copy change to the US contributions landing page, per [this Trello card](https://trello.com/c/8zFv9ARK/2573-add-copy-how-to-send-checks-to-us-landing-page).

update terms copy for US contribs landing page

---

support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx

We're tracking the type of wallet used for each PRB contribution.
But - we also need to track the case where no wallet is used, i.e. the user has set up a card in their browser.

Track no wallet with PRB

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.jsx

Remove the zip code ab test we were running in the US. There was no significant difference so we're going ahead with requiring the field to reduce transactions fees.

Remove zip code ab test

---

support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx

This PR removes the commas after each line in our US postal address for checks.

remove commas

---

support-logs/cfn.yaml

Letting the kibana proxy instance query for tags!
There's currently a major review of the guardian's security practices under the cyber security programme. One of the projects in this programme is to install a vulnerability scanner called Wazuh in guardian ec2 instances.
The scanner has already been installed and connecting properly to the wazuh server, but it's only identifying itself with an instance id rather than app/stack/stage tags.

Add permissions to describe tags

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouMarketingConsent.jsx

Add marketing consent AB test. Additionally, for the control we now use the same copy across all breakpoints.
[**Trello Card**](https://trello.com/c/oho2SEP6/2582-marketing-opt-in-copy-a-b-test-ty-page)

Add marketing consent ab test

---

support-frontend/assets/helpers/externalLinks.js
support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx

This amends the copy in the checkout and thank you page for Guardian Weekly to clarify timing of payment and delivery, due to current delivery issues.
[**Trello Card**](https://trello.com/c/3yFFt9VP)
**Checkout**
**Thank You page**

Guardian Weekly copy amendments due to delivery days

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js

Update the marketing consent test to target the LP + TYP. Before it just targeted the TYP, but as the routing between LP -> TYP is done client side, we weren't registering the new ab test participation.

Update marketing consent test to target LP + TYP

---

support-frontend/app/controllers/PaperSubscription.scala
support-frontend/app/views/subscriptionCheckout.scala.html
support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
support-frontend/assets/helpers/globals.js
support-frontend/assets/helpers/settings.js
support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/thankYou.jsx
support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
support-frontend/assets/pages/paper-subscription-landing/components/content/prices.jsx
support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.jsx
support-frontend/assets/pages/paper-subscription-landing/components/tabs.jsx
support-frontend/assets/pages/paper-subscription-landing/helpers/products.js
support-models/src/main/scala/com/gu/support/catalog/Product.scala
support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala

Now that Subscription Card (AKA digital voucher or iMovo) is live we no longer need a flag for whether to use it or not. This PR removes that flag.
[**Trello Card**](https://trello.com/c/qMSYti7t/3400-post-subs-card-launch-remove-usedigitalvoucher-switch)
This PR is an update of https://github.com/guardian/support-frontend/pull/2794 - that had hung around for so long that it was easier to start again than update it.

Remove use digital flag

---

support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx

Fix a couple of bugs with the stripe PRB:
1. the `otherAmount` field was only updating the redux state `onBlur` this meant there was a race condition when clicking on the PRB after updating the amount, meaning the previous value was shown in the PRB window.
2. when swapping between single and recurring contributions, the `stripePaymentRequestObject` was being recreated, which caused a bug in which updating the selected amount wouldn't update the amount shown in the PRB window.
[**Trello Card**](https://trello.com/c/l3S3VLnX/2602-prb-apple-pay-amount-sometimes-does-not-update)
**NB**: This *does* affect the UX of the page slightly. Error messages are now shown immediately on the `otherAmount` field. Whilst this isn't ideal, we decided to wait on the full UX audit of the LP before spending …

Fix PRB bugs

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlock.jsx
support-frontend/assets/pages/digital-subscription-landing/components/productBlock/productBlockAus.jsx
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx

This PR rolls back the changes put in place in https://github.com/guardian/support-frontend/pull/2994 to support the Accordion AB test. The original aim of the test is to see whether having the information accordions open by default will result in an increase in checkout starts. The results show the original implementation (closed by default) was 61% probability to be best, so we can roll back to that now.

Roll back changes made to support accordion AB test

---

support-internationalisation/src/main/scala/com/gu/i18n/Currency.scala
support-payment-api/src/main/scala/model/Currency.scala
support-payment-api/src/main/scala/model/acquisition/AcquisitionDataRowBuilder.scala
support-payment-api/src/main/scala/model/email/ContributorRow.scala

Adds four European currencies to the api
- Swedish Krona (SEK)
- Swiss Franc (CHF)
- Norwegian Krone (NOK)
- Danish Krone (DKK)
These are the top four European countries, which don't use Euros as their nation currency, from which we receive contributions. This PR is laying groundwork for us to run A/B tests to assess the effectiveness of offering local currencies.

Mj update currencies on payment api

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouMarketingConsent.jsx

Restart marketing consent test to start collecting data again. We had updated the name of the test `thankyouPageMarketingConsentTest` -> `thankyouPageMarketingConsentTestR2` in the definition, but not where it was being used (in the `ContributionThankYouMarketingConsent` component). This meant that users we segmented into different variants, but would have all seen the control copy. I think when we upgrade to typescript we should try and catch this sort of error.

Restart marketing consent test

---

support-frontend/assets/helpers/contributions.js

Update the copy for the monthly/annual price breakdown from 'a (month/year)' to 'per (month/year)' to be consistent with the other parts of the landing page
[**Trello Card**](https://trello.com/c/A4iF30AB/2609-change-landing-page-cta-copy)

Update the copy from 'a month/year' to 'per month/year'

---

build.sbt
project/plugins.sbt
support-frontend/app/wiring/AppLoader.scala
support-frontend/build.sbt
support-models/build.sbt
support-payment-api/build.sbt
support-workers/build.sbt

This PR removes references to bintray, and also updates the SSM configuration library to use one that is in normal sonatyle.
https://trello.com/c/cyWdxhry/3659-remove-support-frontend-dependency-on-bintray
Bintray is going away on 1st may https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

remove references to bintray

---

support-frontend/assets/pages/paper-subscription-checkout/components/addDigiSubCta.jsx
support-frontend/assets/pages/paper-subscription-landing/components/content/tabAccordionRow.jsx

This fixes an issue where `sendTrackingEventsOnClick` was being called on the initial render of an accordion component. This was happening as we'd made use of `useEffect` to call `sendTrackingEventsOnClick` when the `expanded` state of the accordion was updated (via a click event). `useEffect` however is called on initial render too. 
To prevent this I'm making use  of `useRef` as it can be used to store a mutable value (`initialRender`) that persists across re-renders, the value of this is `true` at first, and on initial render we set it to `false`, so any subsequent change to the `expanded` state will result in `sendTrackingEventsOnClick` being called.

Fix click tracking on the accordions

---

support-frontend/assets/helpers/subscriptionsForms/formReducer.js

There was a bug in the newspaper checkout where if you changed the country drop down to Isle of Man it ended up setting the fulfilment options to a value which is not applicable to newspaper and this broke things. This was because of some code which only applies to Guardian Weekly but was being run on the paper checkout as well.
[**Trello Card**](https://trello.com/c/sMfwCmXm/3671-country-dropdown-bug-on-newspaper)

Fix paper checkout country change bug

---

support-frontend/assets/pages/digital-subscription-landing/components/feedbackWidget/feedbackWidget.jsx
support-frontend/assets/pages/digital-subscription-landing/components/feedbackWidget/feedbackWidgetStyles.js
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx

This ensures the feedback widget on the digital subs landing page won't display until the user has scrolled part way through the product information block, at which point it will gently animate in.
The feedback widget takes up a lot of above-the-fold space on small mobile devices. It also seems a bit odd to be asking users how helpful they find the page when they've barely seen any of it!
Apologies for low gif quality!
**Mobile - iPhone SE**
**Tablet - Samsung Galaxy Tab S7**
**Desktop - Firefox/macOS**

Hide digi subs feedback widget until user has scrolled past the hero

---

support-frontend/assets/components/subscriptionCheckouts/billingPeriodSelector.jsx
support-frontend/assets/helpers/subscriptionsForms/submit.js
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscriptionDataBuilder.scala

The Guardian weekly checkout currently decides which currency a user will pay in based on their billing address. 
However the current pricing structure uses currency as a proxy for delivery cost - so for instance the price in New Zealand dollars is nearly twice the price in GBP to reflect the higher cost of delivery to New Zealand.
This means that we need to customers to pay in the currency of the country they want their sub delivered to, even if this is not the same as their billing country.
[**Trello Card**](https://trello.com/c/MGzDyodg/3649-gw-should-use-pricing-for-delivery-address-country-not-billing-address)

Use delivery address country to determine currency in GW checkout

---

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.jsx

This is a follow up for [this PR](https://github.com/guardian/support-frontend/pull/3020). This improves the display of currencies on the post-contribution thank you page, eg. `10 kr` instead of `kr10`.

improve currency display on thankyou page

---

build.sbt
project/plugins.sbt
support-frontend/app/wiring/AppLoader.scala
support-frontend/build.sbt
support-models/build.sbt
support-payment-api/build.sbt
support-workers/build.sbt

Second go at removing bintray - first is here: https://github.com/guardian/support-frontend/pull/3016
The first one failed due to SSM working differently in AWS v2, so the exception needed catching, see @tomrf1 's PR https://github.com/guardian/simple-configuration/pull/22

bintray part 2

---

support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
support-workers/src/test/scala/com/gu/support/workers/lambdas/UpdateSupporterProductDataSpec.scala

Digital Subscription gift purchases should not be added into the SupporterProductData Dynamo store because they do not give the purchaser any digisub benefits. 
This is correct behaviour, but it is currently being treated as an error by the UpdateSupporterProductData lambda. This PR changes that behaviour so that only actual failures are treated as errors.
[**Trello Card**](https://trello.com/c/vLFmYSPI/3510-improve-retrieval-of-supporter-information-from-zuora-members-data-api-members-data-api-work-part-4-80)

Distinguish between failures and null operations in UpdateSupporterProductData

---

support-frontend/assets/helpers/internationalisation/currency.js
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

I've noticed a bug in the way that the Guardian Weekly checkout works now that it uses currencyId to work out which payment methods to allow - the currencyId is updated in the state when **either** of the billing or delivery address is changed, whereas we always want to use the currency associated with the delivery address as this is the currency we will ultimately charge the customer in.
[**Trello Card**](https://trello.com/c/MGzDyodg/3649-gw-should-use-pricing-for-delivery-address-country-not-billing-address-99)

Always take currencyId from delivery address in weeklyCheckoutForm.jsx

---

support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx

This adds back Google Analytics tracking of CTA clicks on the digital subs landing page, which was accidentally removed in #3014

Add back GA tracking of cta clicks on digi subs page

---

support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala

The UpdateSupporterProductData lambda is failing for all digital subscription redemptions at the moment because the billing period is incorrect in the state. This is triggering 'support-workers execution failed' alarms on a regular basis which is wasting developers time so I'm commenting out the part of the lambda that is failing until a proper fix can be put in place.

Comment out supporter product data updates for gift redemptions

---

support-payment-api/src/main/scala/model/acquisition/AcquisitionDataRowBuilder.scala

Currently all single contributions in the new realtime table (fact_acquisition_events) have a country_code of 'GB'.
This is because it's trying to lookup by country name rather than country code

Fix countryCode in bigquery for contributions

---

support-frontend/assets/helpers/timeBoundedCopy/timeBoundedCopy.jsx
support-frontend/assets/helpers/timeBoundedCopy/timeBoundedCopy.test.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/hero.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroStyles.js

In order to both release new copy on the digital subs landing page on Saturday morning, when the G200 special edition is released, and yet also avoid having to do work on a Saturday, this adds a small helper to enable us to set up copy to be displayed only after a certain date and time, and potentially with a pre-set end date.
The helper has been set up with the G200 copy to release on Saturday.
[**Trello Card**](https://trello.com/c/uVEdjCyp)
This specific copy is intended to be released on Satuday, but having new hero copy that should go out on a certain day is a common requirement and this should save us having to sit around with un-merged PRs that have a specific go-live date.
**System time set to current date - existing copy**
**System time set to Saturday afternoon - new G200 copy** …

Add a helper for timed release of new landing page copy, and copy for G200 special edition

---

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

This PR fixes an issue in the checkout form for Guardian Weekly Gift Subscriptions where we were using the stripe account linked to the billing address country, when in fact we need to use the stripe account associate to the delivery address, even if this is not the same as the billing country (As already implemented for non-gift Guardian Weekly subscriptions).

Use the correct stripe account for GW gift

---

support-frontend/assets/components/generalErrorMessage/generalErrorMessage.scss

When a user clicks Contribute but there is an issue with the form (e.g. missing email address), we have a generic error message above the Contribute button. But - this message is hidden above mobileMedium, which is most users. This is very confusing UX because the error message next to the specific field is often out of view.
E.g. clicking Contribute with an empty email address field:

Always show general error message on landing page

---

support-frontend/assets/helpers/productPrice/paperProductPrices.js
support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.test.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx

This fixes the bug where, when using a promo code, the correct promotion price was not being shown in the paper checkout order summary, and the 'add-on' cost of a digital subscription was not correctly calculated.
[**Trello Card**](https://trello.com/c/dme03frP)

Fix bug with promo code prices not appearing in Paper checkout

---

support-frontend/package.json
support-frontend/yarn.lock

These were flagged by snyk.
We tried to do this by updating webpack to v5 (as ssri/y18n are pulled in via webpack). But webpack v5 breaks storybook, so we'll have to wait until storybook catches up.
Our attempt to upgrade webpack is [here](https://github.com/guardian/support-frontend/tree/upgrade-webpack-5)

Update ssri/lodash/y18n dependencies

---

support-frontend/assets/pages/paper-subscription-checkout/components/addDigiSubCta.jsx

This makes the background of the CTA yellow while it's closed, transitioning to the original light grey when opened.
[**Trello Card**](https://trello.com/c/HpPLNioV)
The grey colour is easy to miss in the checkout, whereas the yellow is more eye-catching and (hopefully) more tempting to click on.

Make the 'add digital' CTA in the print checkout stand out more

---

support-frontend/assets/components/subscriptionCheckouts/subscriptionsSurvey/SubscriptionsSurvey.jsx

This updates the survey links on the thank you pages for the Guardian Weekly and Paper checkouts to direct users to the new surveys.
[**Trello Card**](https://trello.com/c/ecjeiEZW)

Update links for the GW and paper surveys on the thank you pages

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx

This work is to reinstate the floating point numbers in the digital add-ons in the print checkout.
[**Trello Card**](https://trello.com/c/QBCMK6dh/3705-print-campaign-print-checkout-paper-accordion-and-order-summary-shows-incorrect-additional-charge-for-the-paper-add-on)
When digital add-on prices include pence (eg £1.80) the pence are getting chopped off. This adds an additional line of code to check whether the float is redundant or not.

Fix price presentation in print+

---

support-frontend/assets/helpers/stripe.js
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js

This is the object returned by the Stripe SDK.
This type of thing doesn't really belong in redux, and we're trying to tidy up/remove redux use in support-frontend.
I had hoped to do this as a custom hook but it's fiddly because it has to happen inside an `Elements` component.

Move PRB object out of redux

---

support-frontend/assets/helpers/tracking/acquisitions.js
support-frontend/assets/helpers/tracking/ophan.js

An increase in client-side errors coincided with the 18th March.
The only deploy that day which could potentially cause problems is this:
https://github.com/guardian/support-frontend/pull/2987
I'm not sure what the cause is yet. One possibility is that the `ReferrerAcquisitionData` value is `undefined`. This PR makes things a bit safer

Make getReferrerAcquisitionData safer

---

support-frontend/assets/helpers/tracking/ophan.js

to prevent errors if localstorage is not available
redux still has the data:

Check localstorage available

---

support-frontend/assets/components/page/heroRoundel.jsx
support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx

This fixes an issue with the roundel on the paper landing page when using a promo code- the headline was getting covered by the roundel on smaller screens.
[**Trello Card**](https://trello.com/c/QkA2DBG7)
**Mobile**
**Mobile Medium**
**Mobile Landscape**
**Phablet**
###Devices
**iPhone SE**
**Pixel 5**
**iPhone 12**

Fix issue with the roundel on the paper subs landing page

---

support-frontend/assets/components/product/productOption.jsx

This fixes an issue where text running over too many lines would become hidden by the pricing card CTA at the tablet breakpoint. As the fix is on the shared `ProductOption` component, I've included screenshots of the other product pages below to demonstrate that there's no regression.
[**Trello Card**](https://trello.com/c/ZwRqNcnw)
**iPad 8th gen**
**Google Nexus 9**
**Digital subscription**
**Guardian Weekly**

Fix issue with spacing on the pricing cards on the print landing page

---

build.sbt
scalastyle-config.xml
support-frontend/app/admin/settings/Settings.scala
support-frontend/app/monitoring/Tip.scala
support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
support-frontend/test/codecs/CirceDecodersTest.scala
support-frontend/test/controllers/SubscriptionsTest.scala
support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
support-models/src/main/scala/com/gu/support/workers/PaymentMethods.scala
support-models/src/main/scala/com/gu/support/workers/PaymentProvider.scala
support-models/src/main/scala/com/gu/support/workers/states/CreatePaymentMethodState.scala
support-models/src/main/scala/com/gu/support/zuora/api/PaymentGateway.scala
support-models/src/test/scala/com/gu/support/SerialisationTestHelpers.scala
support-models/src/test/scala/com/gu/support/encoding/PaymentMethodEncoderSpec.scala
support-models/src/test/scala/com/gu/support/workers/Fixtures.scala
support-models/src/test/scala/com/gu/support/workers/SerialisationSpec.scala
support-modules/bigquery/src/main/scala/com/gu/support/acquisitions/AcquisitionDataRow.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
support-workers/src/main/scala/com/gu/emailservices/PaperFieldsGenerator.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/PaymentMethodExtensions.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendOldAcquisitionEvent.scala
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala

With @TomPretty 
Adds Stripe SEPA as a payment method for recurring contributions.
Stripe requires the client's IP address and user agent, so we pass this through from support-frontend's backend.

SEPA backend support

---

support-frontend/assets/components/page/heroRoundel.jsx
support-frontend/assets/components/page/heroStyles.js
support-frontend/assets/components/page/pageTitle.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroPriceCards.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithImage.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithPriceCards.jsx
support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithPriceCardsStyles.js
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx

This work is to update the text in the Australian digital subscriptions hero, and switch it over to the price cards version of the hero (formerly it had packshots). The text has been reduced to make it fit better with the price cards layout.
[**Trello Card**](https://trello.com/c/GLhVZjeO/3723-aus-pricing-card-component)
In addition, I have fixed a small layout issue where the DS gift heading was rolling over the line on desktop (screenshot below).
The Australian version of the page had been left behind when we switched the hero of this page to the new version with the price cards. The reason (as mentioned above) was that the Australian text was a bit long to fit comfortably with the price cards layout. With this new shorter text, it now fits.
This means that all non-gift digital …

Aus pricing card component

---

support-frontend/package.json
support-frontend/yarn.lock

This updates our runtime `dompurify` dependency to mitigate a [cross-site scripting vulnerability](https://app.snyk.io/vuln/SNYK-JS-DOMPURIFY-1035544).

Update dompurify to mitigate XSS vulnerability

---

support-frontend/assets/components/product/productOption.jsx

Reverting guardian/support-frontend#3081 whilst we look at an issue it introduced on Safari at the mobile breakpoint:

Revert "Fix issue with spacing on the pricing cards on the print landing page"

---

support-frontend/assets/components/page/hero.jsx
support-frontend/assets/components/page/heroRoundel.jsx
support-frontend/assets/components/page/heroStyles.js
support-frontend/assets/components/page/pageTitle.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx

The aim is to fix some slightly strange overlap-y weirdness with the Guardian Weekly landing page hero roundel on mobile breakpoints.
[**Trello Card**](https://trello.com/c/d0iZbHDQ/3740-fix-guardian-weekly-mobile-roundel-position-problem)
To make the page match the designs.

Fix roundel positioning on GW landing page

---

support-frontend/assets/components/product/productOption.jsx

This actually for real this time fixes the issue where text running over too many lines would become hidden by the pricing card CTA at the tablet breakpoint. This applies the same CSS as used in #3081, reverted in #3088, but without the changes to the HTML structure that caused issues in Safari. 
[**Trello Card**](https://trello.com/c/ZwRqNcnw)
**iPhone SE**
**iPhone 12**
**iPad Mini**
**Galaxy Tab S3**
**macOS - Firefox**

Fix spacing issue with pricing cards at tablet breakpoint

---

support-frontend/assets/helpers/urls/routes.js
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPageActions.js

This amends the behaviour of switching tabs on the paper landing page, and also amends the 'Change' link in the paper checkout order summary, to preserve any promo code that's present on the URL.
[**Trello Card - promo code not retained when switching tabs**](https://trello.com/c/WBcs2fEP)
[**Trello Card - promo code not retained when clicking 'Change'**](https://trello.com/c/xBvTgNly)
This is to support the June 2021 paper subscriptions sale.

Pass any existing promo code when switching tabs or returning to the paper landing page from the checkout

---

support-frontend/package.json
support-frontend/webpack.common.js
support-frontend/webpack.prod.js

This PR introduces a new `yarn` script `build-github-action` to the `package.json`. This script builds the production assets without hashing the filenames. The script is to be used by a new "Compressed Size" Github Action: https://github.com/guardian/support-frontend/pull/3079
I'm submitting the change that introduces the script in this advance-PR, and I'll introduce the action in a follow-up PR: https://github.com/guardian/support-frontend/pull/3079. I'm doing this as in order for the action to work the target branch needs to have the build script specified in the action's `.yml` file already in place. 
The weback configuration has been updated so when so the process environment variable `CI_ENV === "github"` is true we omit hashes from the generated filenames, and when `CI_ENV !== …

Add build-github-action script to package.json

---

support-frontend/assets/helpers/forms/stripe.js
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.jsx
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx

Turn off stripe fraud detection to remove reliance on sourcepoint. If a user's add blocker blocks source point (`cdn.privacy-mgmt.com`) we fail to read consents and therefore never load the stripe sdk. We were relying on purpose 1 (`Store and/or access information on a device`) before loading stripe fraud detection which sets a couple of cookies. As a quick fix, we are turning off fraud detection so that we don't need to read consents. 
[**Trello Card**](https://trello.com/c/bopeWCba/2682-ad-blocker-disables-sourcepoint-affecting-stripe)

Remove stripe fraud detection

---

.github/workflows/compressed-size.yml

This PR introduces a new Github action, "Compressed Size", to `support-frontend`.
Compressed Size runs on every pull request and uses the action https://github.com/preactjs/compressed-size-action. This action checkouts the Pull Request's target branch, runs a build and records the file sizes of the generated JS, it then does the same to the branch under review and generates a comparison of the sizes which it adds to the Pull Request.
To enable this I introduced new `yarn` script `build-github-action` to the `package.json` in this PR: https://github.com/guardian/support-frontend/pull/3082

Github action to measure compressed size changes to JS on PRs

---

support-frontend/assets/helpers/timeBoundedCopy/timeBoundedCopy.jsx

This adds a new line of copy for the Euros special edition, to be live for a month from 11th June.
[**Trello Card**](https://trello.com/c/DR3hIrqY)

Add new timed copy for Euros special edition

---

support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala

We have an issue whereby the amount a user will pay for a subscription after a promotion is applied is slightly different on support-frontend to how it appears in the promo code tool.
It turns out that this is because the discount percentage (after adjustment for the billing period length, see [here for more details](https://github.com/guardian/support-frontend/blob/2978de06f4adb86d99473571775eef7ec24eac46/support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala#L127)) was being rounded to two decimal places whereas the promo code tool and most importantly Zuora support at least 3, which is what is needed to be able to target prices at a penny level of granularity.
[**Trello Card**](https://trello.com/c/Dkmk4eNZ/3752-discount-rounding-issue-on-support-frontend)

Fix issue with discount rounding

---

support-frontend/app/views/contributions.scala.html

Stop using on identity billing address fields
https://trello.com/c/cKwVxoT8/3036-remove-billingaddress-from-identity
We are planning on removing billing address from the Identity user model in preparation for the Identity OKTA migration. This PR implements @paulbrown1982 's advice of using correspondence address for county and country.
https://github.com/guardian/membership-workflow/pull/295

Stop using on identity billing address fields

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
support-workers/src/main/scala/com/gu/zuora/productHandlers/ZuoraDigitalSubscriptionDirectHandler.scala
support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

We want to run an AB test to measure the appetite for bundling an events benefit with the digital subscription. 
As part of this we will need to add an unmanaged attribute to Braze for all users who fall within the variant cohort - this PR adds code to do that.
For reference the attribute will be called `unmanaged_digital_subscription_in_events_test`
[**Trello Card**](https://trello.com/c/2mB24ver/3733-events-custom-attribute-to-send-to-braze)
I have tested this on CODE and the attribute shows up in Braze as expected.

Send unmanaged attribute for events test to Braze

---

support-frontend/app/controllers/SubscriptionsController.scala

This fixes an issue where the incorrect rate plan was being used to provide the display price for Guardian Weekly on the subscriptions landing page to users in ROW. The rate plan for GW Domestic only includes the US$75 quarterly rate for the USA, and there is a completely separate rate plan for ROW which was not being retrieved.
[**Trello Card**](https://trello.com/c/sWRc0WGy)

Fix issue where the US quarterly price for Guardian Weekly was displayed to ROW on the subs landing page

---

support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala

This PR, which should be merged alongside changes to relevant Braze campaign, tweaks the `support-workers` repo to further make it compatible with SEPA direct debit recurring contributions.

MJ tweak support workers for sepa emails

---

support-frontend/app/controllers/Application.scala
support-frontend/app/services/MembersDataService.scala
support-frontend/app/views/contributions.scala.html
support-frontend/assets/helpers/abTests/lpPreviousGiving.js
support-frontend/assets/helpers/customHooks/useLastOneOffContribution.js
support-frontend/assets/helpers/forms/existingPaymentMethods/existingPaymentMethods.js
support-frontend/assets/pages/contributions-landing/components/ContributionFormBlurb.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionsFormBlurbPreviousGiving.jsx

Add a special message to the contributions landing page for users that clicked through from the "support again" header (https://github.com/guardian/support-dotcom-components/pull/469)
[**Trello Card**](https://trello.com/c/2jUr2U7V/2637-poc-display-a-custom-message-on-the-lp-based-on-readers-previous-giving)

Add special "previous giving" message to the LP

---

support-frontend/app/controllers/SubscriptionsController.scala
support-frontend/assets/helpers/productPrice/__tests__/priceDescriptionsTests.js
support-frontend/assets/helpers/productPrice/billingPeriods.js
support-frontend/assets/helpers/productPrice/priceDescriptions.js
support-frontend/assets/pages/promotion-terms/weeklyTerms.jsx
support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.jsx
support-frontend/assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.jsx
support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.jsx
support-models/src/main/scala/com/gu/support/catalog/Product.scala
support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
support-services/src/main/scala/com/gu/support/catalog/CatalogService.scala
support-services/src/test/scala/com/gu/support/catalog/CatalogServiceSpec.scala
support-services/src/test/scala/com/gu/support/pricing/PriceSummaryServiceSpec.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendOldAcquisitionEvent.scala

We would like to trial a monthly option for Guardian Weekly as there is a belief that it may reduce churn rates from customers coming to the end of the 6 for 6 period.
[**Trello Card**](https://trello.com/c/jShvc0c9/3455-guardian-weekly-replace-quarterly-with-monthly-test)
This PR introduces a new variable `postIntroductorySixForSixBillingPeriod` in both the Javascript code and the Scala code - this are used to determine:
- what rate plan to show alongside Annual
- what rate plan 6 for 6 customers go on to after the introductory offer period
I have tested monthly and 6 for 6 purchases locally and checked the resulting subscription record in Zuora, the thank you email and how it appears in manage my account are all correct.

GW Monthly rate plan

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx

Turn off the stripe PRB design test. There was no significant difference between the control and the variant, but we've decided to roll the variant out to 100%.

Turn off PRB design test

---

support-workers/build-tc
supporter-product-data/build-tc

Make it explicitly run the tests for supporter-product-data project
This means that any failures in aggregated projects will prevent the build producing an artifact
https://github.com/guardian/support-frontend/blob/47aa4e818eeb80b96d1a4a921e739b853e33eded/build.sbt#L133

make sure failing tests in depended projects prevent deployment

---

support-frontend/assets/stylesheets/emotion/colours.js
support-frontend/webpack.common.js

This restores the `paperSubscriptionsBlue` colour that was accidentally deleted, and is required for the paper subs landing page. It also makes the Webpack settting [output.strictModuleErrorHandling](https://webpack.js.org/configuration/output/#outputstrictmoduleerrorhandling) `true` in production builds, in order to catch issues like this in future.

Restore missing paper subs blue colour

---

support-lambdas/it-test-runner/cfn.yaml

Make the IT tests use the corretto runtime, to check for issues.
AWS is switching over from July 19th, so we should test in advance.
https://aws.amazon.com/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/
The IT test runner is about the least consenquential thing we have, however it does use a lot of our code and exercise it, so it should be a good test.
We would need to follow up with support-workers, etc.

java 8 corretto for it test runner

---

support-frontend/assets/components/footerCompliant/ContributionsFooter.jsx

Point to the help centre instead of the outdated FAQs page
> It was originally created as something to include in our auto-response, but now our auto-response isn't working anyway, plus cases are going to TP in the first instance most of the time.
> The page is still getting some traffic, mostly referrals from other Guardian pages, would it make sense to set up a redirect on the URL to send people directly to the help centre and to take this page down?
> The page is here: https://www.theguardian.com/help/users/faq
------
>This page is not being migrated as it mostly contains information that is already elsewhere on the help centre. I would advise sending people to the help centre instead.
----
re this particulaar page 
> Worth updating that to point directly at the help centre, I'd say.

update contributions FAQs link

---

support-frontend/app/controllers/Application.scala
support-frontend/assets/pages/aus-moment-map/components/socialLinks.jsx
support-frontend/assets/pages/contributions-landing/components/AustraliaMapLink.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouAusMap.jsx
support-frontend/conf/routes

Add a new route for the aus map page that doesn't reference the year (`/aus-map`). We're still keeping the old route to avoid breaking existing links.
[**Trello Card**](https://trello.com/c/w39rGCdI/2701-update-aus-map-url)

Update aus map URL

---

support-lambdas/acquisitions-firehose-transformer/cfn.yaml
support-lambdas/stripe-intent/cfn.yaml
support-workers/cloud-formation/src/templates/lambda.yaml
supporter-product-data/cloudformation/cfn.yaml

This PR updates all the remaining lambdas to use amazon java
https://trello.com/c/deNeOy6x/3778-switch-over-scala-lambdas-to-corretto
Following on from https://github.com/guardian/support-frontend/pull/3133 which seems to have had no issues
This is per the amazon announcement they will all move over https://aws.amazon.com/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/

Update lambdas to use amazon java instead of openjdk

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js

pending further exploration.
There's quite a lot to unpick to remove this properly, and we may use it again later, so for now I'll leave it inactive

end local currency test

---

support-frontend/.eslintrc
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.jsx

1. Removes the marketing opt in component from the contributions thank you page for recurring
2. Updates the copy about marketing emails in the header copy (see screenshots)

remove marketing opt in from thank you page for recurring

---

support-frontend/assets/components/footerCompliant/Footer.jsx
support-frontend/assets/helpers/page/analyticsAndConsent.js
support-frontend/assets/helpers/page/page.js
support-frontend/assets/helpers/page/statelessPage.js
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
support-frontend/assets/pages/error/error404.jsx
support-frontend/assets/pages/error/error500.jsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
support-frontend/assets/pages/paypal-error/payPalError.jsx
support-frontend/assets/pages/showcase/showcase.jsx
support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx

This puts the tracking and CMP back on the subscriptions landing pages where they were mistakenly removed after removing those pages' Redux dependency. I've done a little bit of reorganisation too and given the 'stateless init' function a hopefully clearer name and moved it into a separate file, which should keep Redux out of the bundle for pages that aren't using it.
We noticed a drop off in the analytics at around the time the PR removing the Redux dependency was merged; there may be other causes but it seems pretty likely that this issue is at least part of it.

Extract tracking and A/B test setup from Redux setup and restore them to the subscriptions landing pages

---

support-frontend/assets/helpers/abTests/__tests__/abtestTest.js
support-frontend/assets/helpers/abTests/abtestDefinitions.js

We don't watch to show the `digiSubEventsTest` AB test on the Digital Subs Gifting landing page,  however the current `nonGiftLandingNotAusNotUS` regex still matches the gifting URL "https://support.theguardian.com/uk/subscribe/digital/gift", as can be seen here: https://regex101.com/r/HO8nZC/1
This PR updates the `nonGiftLandingNotAusNotUS` regex to omit the gifting landing page URLs, as can be seen here: https://regex101.com/r/OCYfxg/1
I've also included some unit tests to validate this.

Update nonGiftLandingNotAusNotUS regex to omit gift checkouts

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/acquisitions-stream/AcquisitionsStreamService.scala
support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
support-payment-api/src/main/scala/backend/PaypalBackend.scala
support-payment-api/src/main/scala/backend/StripeBackend.scala
support-workers/src/main/scala/com/gu/services/Services.scala
support-workers/src/test/scala/com/gu/support/workers/lambdas/SendAcquisitionEventSpec.scala

The `AcquisitionsStreamService` was introduced as a service in a previous PR, and this test is now failing.
I've added a mock implementation that always succeeds

fix SendAcquisitionEventSpec 

---

support-frontend/assets/helpers/forms/checkouts.js
support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js

e.g.
`?selected-amount=15&selected-contribution-type=monthly`
If the selected amount is available in the set of configured amounts then this will be selected. If it's not available, we set it as the 'other' amount.
E.g. an amount is available:
An amount is not available:

Enable amount selection from the url

---

support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

This changes the payment selection logic so we show direct debit as an option if the country is GB rather than if the currency is GBP.
[**Trello Card**](https://trello.com/c/OaMMxRYL/3782-only-enable-direct-debit-where-countryid-gb)
We've had a few errors where people from the Isle of Man try to pay with direct debit (which is an option presented to them) and their payments can't be processed because they're not in GB.

Update payment selection logic to use country rather than currency

---

support-frontend/assets/pages/aus-moment-map/ausMomentMap.scss
support-frontend/assets/pages/aus-moment-map/components/socialLinks.jsx

just changes colours on the territories and their labels, including hover + selected states.
Also changed the social share icon colour to blue

Update aus map colours

---

support-frontend/assets/helpers/user/user.js
support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.jsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js

The `gu_recurring_contributor` cookie is used for 2 things:
1. on dotcom: to hide support messaging,
2. on the contributions landing page: to prevent people from creating more than one recurring contribution.
The second use is problematic because the cookie is set when support-workers runs. This means if it fails during/after then the user cannot retry unless they delete the cookie.
With this PR, the landing page instead queries MDAPI to find out if the user has a recurring contribution. This does mean that non-signed-in users will not have this check.
Separately, we should delay setting the cookie until support-workers completes or hits the timeout.

Set isRecurringContributor using MDAPI

---

support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJson.scala
support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala

Update the format of the `timestamp` field that we save to s3 as the current format doesn't play nice with athena.

Update `timestamp` format

---

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSocialShare.jsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/utils/social.js

1. Different copy in the social share component
2. Add campaign code to the INTCMP (facebook/twitter/email)
3. Different copy for twitter
Facebook:
`https://www.facebook.com/sharer/sharer.php?u=https://support.theguardian.com/contribute?INTCMP=component-share-facebook-Aus_moment_2021`
Twitter:
`https://twitter.com/intent/tweet?url=https://support.theguardian.com/contribute?INTCMP=component-share-twitter-Aus_moment_2021&text=I%20support%20Guardian%20Australia%20because%20I%20believe%20in%20rigorous,%20independent%20journalism%20that%E2%80%99s%20open%20for%20everyone%20to%20read.%20Join%20me%20by%20making%20a%20contribution%20and%20together%20we%20can%20be%20a%20voice%20for%20change.%20#supportGuardianAustralia`
Email:
`mailto:?subject=Join%20me%20in%20supporting%20open,%20independent%20jour …

Aus moment social share

---

support-frontend/assets/pages/digital-subscription-landing/components/comparison/tableContents.jsx

Removing the comparison table line that says that we are offering six free tickets to events, as this was not meant to be in the test version, this was just for the qual tests.
This is to fix an issue from this PR: https://github.com/guardian/support-frontend/pull/3145
To correct the content of the new comparison table.

Remove tickets offer from comparison table

---

support-frontend/assets/pages/digital-subscription-landing/components/comparison/comparisonTable.jsx
support-frontend/assets/pages/digital-subscription-landing/components/comparison/tableContents.jsx

Adding a border to a yellow square in the comparison table and fixing the spacing issue that resulted from adding this border.
This is a fix relating to this PR: https://github.com/guardian/support-frontend/pull/3145
Dipa asked me to add it!

Add border to free column checkmark and fix resulting spacing issues

---

support-frontend/assets/helpers/forms/formValidation.js
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.js
support-frontend/assets/pages/contributions-landing/components/SepaForm.jsx

IBANs are sometimes entered with spaces within. This PR allows users to include spaces, and only removes them when it posts the form to the backend
Both of these are ok:

Allow spaces in IBAN

---

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx

Currently it uses the default values, which can cause it to incorrectly show the message about a "generous contribution".
A proper fix would involve setting the amount in session storage before the redirect

Disable high contributor message for paypal/one-off

---

support-frontend/assets/helpers/subscriptionsForms/submit.js
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js

We've had some recurring contributions fail because identity doesn't allow whitespace before or after the name fields.
This change trims these fields client-side before posting to the backend.

trim name and email before sending to backend

---

support-frontend/assets/helpers/productPrice/__tests__/promotionsTests.js
support-frontend/assets/helpers/productPrice/promotions.jsx
support-frontend/package.json
support-frontend/yarn.lock

This pr removes the markdown library `marked` and replaces it with `snarkdown`.
[**Trello Card**](https://trello.com/c/NCxiJcmU/3719-swap-out-marked-for-snarkdown-on-support-frontend)
We rely on the marked library to parse markdown coming from the promo code tool. However we only support a limited amount of markdown styling, and don't need to include a full markdown parser on every page. Marked is about 10KiB gzipped and is one of the largest single dependencies on our landing pages whilst Snarkdown is considerably smaller.

Swap out marked for snarkdown

---

support-lambdas/it-test-runner/cfn.yaml

We get a lot of false alarms for the IT tests recently,  this is usually just network issues or other random issues.
We only really want to know if they are totally broken, so probably finding out within 3 hours would be enough.
This PR updates it to have (60*2) + 10 which should cover 3 periods.

extend it test failing to 3 in a row to lower false alarms

---

support-lambdas/it-test-runner/cfn.yaml

Following on from https://github.com/guardian/support-frontend/pull/3188
The alarm period could be 15 minutes, this will make it group together data points from slower runs, this making it less likely to trigger.
I ahve also extended the range of the "not running" alarm to make sure it isn't running for 2 hours before going off.

change IT test alarms to 15 minute period

---

support-frontend/assets/helpers/urls/routes.js
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx

This PR prevents query parameters from being stripped out of the newspaper landing page url as well as ensuring that tracking information for the landing page is only sent on click are not being sent on initial page load. 
[**Trello Card**](https://trello.com/c/mxxVFqnJ/3810-paper-landing-page-loses-tracking-params)
Marketing use certain query parameters to attribute traffic etc to their campaigns.

Retain query params for paper landing page

---

support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/directDebitForm.jsx
support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.jsx
support-frontend/assets/helpers/subscriptionsForms/__tests__/validationTest.js
support-frontend/assets/helpers/subscriptionsForms/rules.js
support-frontend/assets/helpers/subscriptionsForms/validation.js
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.test.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.test.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.jsx

This adds a validation rule to the relevant text input fields in the digital, GW and newspaper checkouts which prevents a user from submitting the form if they have included non ASCII characters. The user will now be shown an error message prompting them to change their input value.
[**Trello Card**](https://trello.com/c/Iyyimr7j/3094-disallow-funny-characters-in-submission-validators-80)
When people put emojis or font changes into their checkout submissions, it causes a zuora repeated failure followed by eventual timeout.
|  |  |
| <img width="1170" alt="Screenshot 2021-08-02 at 10 21 22" src="https://user-images.githubusercontent.com/44685872/127837626-41c82c1c-c2ea-453d-86f8-7291d8005ba4.png"> | <img width="1170" alt="Screenshot 2021-08-02 at 10 21 47" …

Disallow non ASCII characters in submission validators 

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js

This turns off the comparison table A/B test. We may use it again later, so for now the test and related components will remain in the codebase in an inactive state.

Turn off comparison table A/B test

---

support-frontend/assets/helpers/tracking/acquisitions.js

[**Trello Card**](https://trello.com/c/AJVCpH2a)
The Support website does not attribute inbound links from search engine pay-per-click sources (e.g. Google Ads) as having a `source` of `PPC`, even though that enum is supported. As a consequence, acquisitions made via this journey are attributed the same as if the user had visited the site via organic search or by just typing support.theguardian.com/* in their address bar.
I've solved this by:
- Including the value from &CMP= in the hierarchy of values which identify a campaign code. This adds only additive tracking benefits from what I can understand.
- Adding a tiny parser of that to identify the link as coming from a search engine pay-per-click. This is driven by the assumption that inbound links from Bing have an `&CMP=ppc_*` param and …

Identify PPC sources in acquisitions data

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.jsx
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
support-workers/src/main/scala/com/gu/zuora/productHandlers/ZuoraDigitalSubscriptionDirectHandler.scala

This PR sets up a referrer controlled 0% A/B test for the Events module on the digital subscriptions landing page. 
NB: The Events module component is due to be updated in a subsequent PR and the `emailDigiSubEventsTest` A/B test is yet to be set up in Optimize.
To view the existing Events module component you can use the following endpoint to force the variant: /subscribe/digital#ab-emailDigiSubEventsTest=variant
[**Trello Card**](https://trello.com/c/4QY6ub1H/3823-set-up-a-referrercontrolled-abtest-for-the-events-email-ab-test)
We want to test whether user's in our email distribution lists will be encouraged to subscribe by the Digi Subs + Events offer of 6 free tickets to events and masterclasses.
The current Events module:
| Desktop  | Mobile |
| <img …

Events email referrer controlled A/B test

---

support-frontend/assets/components/icons/clock.jsx
support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/helpers/images/imageCatalogue.json
support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/eventsModule.jsx
support-frontend/assets/pages/digital-subscription-landing/components/events/eventCard.jsx
support-frontend/assets/pages/digital-subscription-landing/components/events/eventsImages.jsx
support-frontend/assets/pages/digital-subscription-landing/components/events/eventsModule.jsx

This follows a previous PR which set up a referrer controlled 0% A/B test for the Events module on the digital subscriptions landing page, which can be found [here](https://github.com/guardian/support-frontend/pull/3202). This PR updates the images and copy for the events shown in the Events module component.
[**Trello Card**](https://trello.com/c/191FZirU/3802-update-events-module-component-for-email-digi-subs-events-ab-test)
So when the Events module component is rendered we show appropriate up-to-date events information.
[**Optimize Link**](https://optimize.google.com/optimize/home/#/accounts/1368065808/containers/6827913/experiments/497)
| Left col  | Mobile medium |
| <img …

Update Events module for Email Digi Subs + Events AB test

---

.github/workflows/snyk.yml

It marks all branches as failed, which isn't helpful.
We have a snyk rota for addressing these issues

Remove snyk check from branches

---

support-lambdas/acquisitions-firehose-transformer/build.sbt
support-lambdas/acquisitions-firehose-transformer/cfn.yaml
support-lambdas/acquisitions-firehose-transformer/riff-raff.yaml
support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJson.scala
support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/GBPConversionService.scala
support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/Lambda.scala
support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala

This lambda uses the `AnnualisedValueService` to calculate AV before writing to S3.
But despite taking currency as a parameter, this service does not calculate AV in GBP!
The `fixer-io-cache` dynamodb table has daily currency conversions rates.
I used a scala library called scanamo for querying dynamodb as the java sdk is not great.
An event in athena:

acquisitions-firehose-transformer: GBP conversion

---

support-frontend/assets/components/interactiveTable/interactiveTable.jsx
support-frontend/stories/content.jsx

This adds the interactive table component built as an exploratory spike, ahead of the more specific A/B test work to add it to the digi subs landing page.
[**Trello Card**](https://trello.com/c/jGZVS2Om)
This component is by no means ready for production, but merging it means the prototype will be ready to go for future dev work.

Add prototype for interactive table for future digi subs A/B test

---

support-workers/cloud-formation/src/templates/cfn-template.yaml

This PR adds an alarm so we know if GW conversion is broken.
https://trello.com/c/9uB91SVP/2909-add-an-alarm-for-no-gw-acquisitions-in-x-hours-like-we-have-for-paper-and-digital
We won't know until userhelp get in touch, if the GW checkout is not allowing people to complete a purchase in any payment method at all.  This should be a cheap way to find out quicker.

Add alarm for "no Guardian Weekly checkouts"

---

support-frontend/assets/helpers/tracking/acquisitions.js

This PR converts the queryParameters in the referrerAcquisitionData into the correct format.
Before it was
...which caused a 400 bad request due to a backend deserialisation error
This will change it to 
```json
[
{
"name": "thekey",
"value":"thevalue"
}
... more pairs here
]
```
This is a fix to this PR: https://github.com/guardian/support-frontend/pull/3204
Stop the failed signups from happening.

convert query params in GCL case to the correct format for the backend

---

support-workers/cloud-formation/src/templates/cfn-template.yaml

This PR changes the DS alarm back to 3h
I changed it to 2h as an opportunity in this PR
https://github.com/guardian/support-frontend/pull/3221/files#r695752789
However, it seems it went off fairly soon after, so I was a bit optimistic (I only checked back a week or so to ensure no false alarms would happen)

change DS alarm back to 3h

---

support-frontend/assets/helpers/productPrice/__tests__/paperProductPricesTests.js
support-frontend/assets/helpers/productPrice/__tests__/priceDescriptionsTests.js
support-frontend/assets/helpers/productPrice/__tests__/productPricesTests.js
support-frontend/assets/helpers/productPrice/__tests__/promotionsTests.js
support-frontend/assets/helpers/productPrice/paperProductPrices.js

This pr adds tests for a number of files in the `productPrice` folder that handle the way we access pricing information and the text about them.
These tests will prevent regressions when modifying code within the `productPrice` folder. We will soon be separating the work of getting the correct price from the text about the price, as they are currently intertwined in a way that makes it difficult to make the nimble text changes that we increasingly need to make. 
[**Trello Card**](https://trello.com/c/t6CiFUA6/3753-write-tests-for-price-text-and-price-calculation-code-90)

Update product price tests

---

support-frontend/assets/helpers/abTests/abtestDefinitions.js

The `emailDigiSubEventsTest` has come to an end, this PR turns off the test in `abtestDefinitions.js` so members of the public will no longer be able to enter the test. A follow-up PR will remove the Event component and any other associated logic required to support the test.

Turn off emailDigiSubEventsTest AB test

---

support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx

Add a line break after the patrons text to give spacing at the bottom
**before**
**after**

Add spacing in the bottom of patrons text

---

support-frontend/assets/helpers/forms/paymentIntegrations/oneOffContributions.js

We already send an ophan event when the 3DS popup appears, but not when it succeeds/fails.
With this PR we now have all 3 events:
3DS popup:
{"component":{"componentType":"ACQUISITIONS_OTHER","id":"stripe-3ds"},"action":"VIEW"}
Fail:
{"component":{"componentType":"ACQUISITIONS_OTHER","id":"stripe-3ds-failure"},"action":"CLICK"}
Succeed:
{"component":{"componentType":"ACQUISITIONS_OTHER","id":"stripe-3ds-success"},"action":"CLICK"}
This applies for single contributions only. For recurring the appearance of the 3DS popup is managed by the stripe sdk, so we cannot have these events (https://stripe.com/docs/js/deprecated/handle_card_setup).
Stripe have provided us with a dashboad for monitoring 3DS events so hopefully we'll still have the full picture

Track 3ds result for single contributions

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

@johnduffell and I noticed that `subs-checkout-submit-` componentEvent for paypal is missing in the pageview table.
This is because we have to handle paypal differently, which we do for digisub: https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx#L136

track paypal submissions for weekly + paper subs

---

support-frontend/assets/components/product/productInfoChip.jsx
support-frontend/assets/components/product/productOption.jsx
support-frontend/assets/pages/paper-subscription-landing/components/content/linkTo.jsx
support-frontend/assets/pages/paper-subscription-landing/components/content/prices.jsx
support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.jsx

This pr implements the design changes to the paper pricing cards with the inclusion of the Saturday plan
[**Trello Card**](https://trello.com/c/5ROhF0di/3845-paper-campaign-support-5th-pricing-card-saturday-subscription60)
These changes are necessary for when we enable the Saturday paper subscription pricing card.
| mobile | mobileMedium | mobileLandscape | phablet | tablet | leftCol | wide |
|--------|--------------|-----------------|---------|--------|---------|------|
| ![mobile](https://user-images.githubusercontent.com/44685872/132847463-09c5a705-6486-4f45-b98f-24762432fd9c.png) | ![mobileMedium](https://user-images.githubusercontent.com/44685872/132847630-b588326e-7f9a-456f-a903-d78b5e5fd3e0.png) | ![mobileLandscape](https://user-images.githubusercontent.com/44685872/132847710-e3608c …

Paper product pricing cards with Saturday plan 

---

support-frontend/app/actions/CustomActionBuilders.scala
support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/controllers/RegularContributions.scala
support-frontend/app/wiring/ActionBuilders.scala
support-frontend/cloud-formation/cfn.yaml
support-frontend/test/actions/ActionRefinerTest.scala
support-frontend/test/controllers/ApplicationTest.scala
support-frontend/test/controllers/SiteMapTest.scala
support-frontend/test/fixtures/DisplayFormMocks.scala
support-frontend/test/selenium/subscriptions/pages/GuardianWeeklyGiftCheckout.scala
support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala

The server side create endpoint is the final step in creating a subscription, after the client side work has been done.
This PR makes us get an alarm if there's any non 2xx response from the create endpoint on the server side.
Tested locally with Digi sub and contribution (positive and negative cases)
https://trello.com/c/RzkGDEbI/3849-alarm-on-a-single-deserialisation-failure-on-acquisition
This is needed in response to an incident where some subscribe requests did not validate on the server side, but no alarms were able to detect that, as it was rejected immediately by the parser.  See retro doc here https://docs.google.com/document/d/10K8VFm2oUv6SOu6U49B1rUPtHQPwGyZB2pV8Cfam_dE/edit#
This tries to capture all errors between the request header being read in to the server and available …

if a create request fails for any reason, alarm immediately

---

support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx

This PR makes sure a stripe error is logged as a rejected promise rather than the error being used to resolve the promise.  This means it doesn't get submitted to the back end as a valid payment id.
https://trello.com/c/hR0Sn4K3/3870-dont-submit-client-side-stripe-error-as-payment-details-to-back-end
This is needed to reduce the number of alarms that go off, and make the error message clearer.
Before the user used to see:
and this extra request:
Now they will see:

don't submit stripe errors to the backend as a payment method

---

support-frontend/assets/helpers/forms/checkouts.js

currently you can only see SEPA if you add `?sepa=true` to the url.
This PR removes this.
After this PR is merged all EUR users will see SEPA. The RRCP switchboard has a switch for SEPA if we need to disable it.
To be merged on Monday.

Remove querystring switch for SEPA

---

support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala

A sepa recurring contribution failed at the zuora step with:
`The length of IP Address can not be longer than 15 characters`
This doesn't work for ipv6

fix ipaddress field in zuora request

---

support-frontend/app/actions/CustomActionBuilders.scala
support-frontend/app/services/HttpIdentityService.scala

Follwing on from https://github.com/guardian/support-frontend/pull/3246
It became clear that failed futures can be returned by an action and cause a 5xx in place of the Result object.
This PR traps them too and also pushes an alarm if it fails.
We want to know when things are going wrong right at the end of the process of purchasing, so we can make the experience better. And avoid losing money.

also alarm on failed futures on the create endpoints

---

supporter-product-data/build.sbt

The supporter product data build has been failing in TeamCity for a while because of a merge problem in the assembly step of the build. This PR fixes it.

Fix assembly by applying merge strategy to execution.interceptors

---

support-frontend/app/services/HttpIdentityService.scala

This PR extends the IDAPI timeoiut from 3 to 5s in order to reduce the number of 5xx errors due to identity timeout on the recurring product create endpoint.
The timeout was 1s and we were getting errors, so I increased to 3 in this PR
https://github.com/guardian/support-frontend/pull/3247/files#diff-de948b533ed461aa9f0a28870a991d90798894d20fb7295a129a60965c90851eR183
I had a chat with identity but they didn't see any issues at their end.
However it's still timing out every day so I have extended again (optimisticvally)
My feeling is it's a network issue and it won't recover even in 5s, but it is worth a try.  Failing that it might be worth seeing if we can get rid of the call, as all we are doing is getting the displayname and email address for support-workers, which may already be …

optimistically extend identity timeout further

---

support-frontend/assets/pages/paper-subscription-landing/components/content/subsCardTab.jsx

This updates the Newspaper Landing Page.
The link at the bottom of the "Delivery from your retailer" accordion on the "Subscriptions Card" tab had the wrong copy and URL. It's now been updated to use this URL https://www.delivermynewspaper.co.uk/ and to say  'Find your nearest delivery retailer'.

Fix Subscription Card delivery link on Newspaper Landing Page

---

support-frontend/assets/helpers/subscriptionsForms/formActions.js

We have a bug caused by users setting a title and then unsetting it which results in a value of empty string rather than null if it was never set in the first place. 
This causes problems when deserialising the json body of the create request to the backend.
[**Trello Card**](https://trello.com/c/2VqcjyCh/3881-title-field-as-an-empty-string-does-not-pass-server-side-validation-on-the-susbscription-create-endpoint)

Unset title field to null rather than empty string in checkout

---

support-frontend/app/controllers/PaperSubscriptionForm.scala
support-frontend/assets/components/csr/csrMode.js
support-frontend/assets/helpers/abTests/abtestDefinitions.js
support-frontend/assets/helpers/urls/routes.js
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.jsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingProps.js
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/conf/routes

This PR removes the [ab test for newspaper guest checkout](https://github.com/guardian/support-frontend/pull/3232) and rolls guest checkout out to 100% of users.
[**Trello Card**](https://trello.com/c/j4hh5Kw4/3887-release-the-newspaper-guest-checkout-to-100-of-the-audience-stop-test)
[**Link to the test results in Optimize**](https://optimize.google.com/optimize/home/#/accounts/1368065808/containers/6827913/experiments/496/report)

Remove newspaper guest checkout test

---

support-frontend/assets/components/paypalExpressButton/PayPalOneClickCheckoutButton.jsx
support-frontend/assets/helpers/abTests/abtestDefinitions.js

There was a bug with the #3249 test affecting users in countries where state is a required field:
When we retrieved the address information from PayPal we set the `state` field in Redux before `country`, however changing the value of `country` then sets `state` back to `null` see: https://github.com/guardian/support-frontend/blob/7f81d37da9a377d2fc304f2d50e228abe6a86dca/support-frontend/assets/components/subscriptionCheckouts/address/addressFieldsStore.jsx#L283
This PR fixes this by setting the `country` field before the `state` field.
Unfortunately this means that we will have to restart the PayPal one click test
[**Trello Card**](https://trello.com/c/X6JZVvOe/3892-paypal-one-click-users-in-the-us-have-null-state)
If this is an AB test, PR reviewers should open and check the Optimize …

Fix state bug

---

support-frontend/assets/helpers/urls/routes.js

Investigated an issue with @rupertbates and @johnduffell where the Newspaper checkout form was always displaying Subs Card as selected product, even if Home Delivery had been selected. This was down to an issue with the way we construct the URL and query params.  
Incorrect: https://support.theguardian.com/subscribe/paper/checkout?fulfilmentOption=HomeDelivery&productOptions=Everyday
Correct: https://support.theguardian.com/subscribe/paper/checkout?fulfilment=HomeDelivery&product=Everyday

Fix issue with query string param on Newspaper LP

---

support-frontend/assets/components/footerCompliant/ContributionsFooter.jsx
support-frontend/assets/components/footerCompliant/DigitalFooter.jsx
support-frontend/assets/components/footerCompliant/Footer.jsx
support-frontend/assets/components/footerCompliant/WeeklyFooter.jsx
support-frontend/assets/pages/digital-subscription-checkout/thankYouExisting.jsx
support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.jsx
support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
support-frontend/assets/pages/promotion-terms/promotionTerms.jsx
support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx
support-frontend/assets/pages/subscriptions-redemption/subscriptionsRedemption.jsx
support-frontend/stories/footer.jsx

This PR updates the footer FAQs link to point to the Help Centre.
We got this message pointing out the change needed
>I've noticed that through the footer on the support.theguardian.com platform you can access this set of FAQs.
>This should really be pointing at the help centre instead. The long list of Subscription FAQs that's currently on there has a very high bounce rate and is also difficult to maintain as it's managed on a separate platform. 
>If there's anything on the long list of Subscription FAQs that's currently not on the help centre can you please let me know so that I can add it, so that everything is in the same place. Then we should change all FAQ links on the support.theguardian.com to point to the help centre.

update footer faq link to the help centre

---

support-frontend/app/controllers/WeeklySubscriptionForm.scala
support-frontend/assets/components/subscriptionCheckouts/personalDetails.jsx
support-frontend/assets/helpers/subscriptionsForms/guestCheckout.js
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.jsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.jsx

This PR removes the requirement to sign in before purchasing a GW sub or gift sub
[**Trello Card**](https://trello.com/c/YB2VSB5h/3880-implement-gw-gifting-and-non-gifting-guest-checkout-not-an-ab-test)
- To remove friction from the checkout process
- Changes to the Identity sign up process mean that users can no longer be logged in until they verify their email. This would make the old flow completely impractical
- It allows customer service representatives (CSRs) to use these checkouts to purchase subscriptions for customers rather than having to use the subscribe site

Enable Guardian Weekly guest checkout

---

support-frontend/app/services/HttpIdentityService.scala

This PR makes the identity timeout for guest checkout also 5 seconds.
This is to put it in line with the user-get timeout in https://github.com/guardian/support-frontend/pull/3258
We get occasional identity timeouts, it makes sense to be generous.  I think the real issue is a network issue, so we should probably use a retry if it still happens often.

make the guest checkout identity timeout 5 seconds

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/ga/GoogleAnalyticsService.scala

This was the old behaviour: https://github.com/guardian/support-frontend/blob/6fbf84dda131dc5eb01f8bf11437ee3cb54cfd16/support-workers/src/main/scala/com/gu/support/workers/lambdas/SendOldAcquisitionEvent.scala#L161

Default amount to 0 for GA AV calculation

---

support-models/src/main/scala/com/gu/support/promotions/Promotion.scala
support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala

This PR gives people 7 weeks of 6 for 6, to guarantee that they get enough issues over christmas
NOTE we need to change the Specific Weeks for 6 for 6 in zuora (for ROW AND Domestic) to 7 at the moment this goes to PROD, and we need to revert this after or just before christmas (including the zuora change).
https://trello.com/c/IzbPWEkh/17-guardian-weekly-6-for-6-christmas-plan-change
Avoid people missing an issue, or the retention team having loads of subs to fix manually.

give people 7 weeks of 6 for 6 when we are in the christmas zone

---

support-frontend/app/wiring/AppComponents.scala

We want to be able to run support-frontend inside an iframe so that it can be embedded in Salesforce and potentially in dotcom as well.
This causes an issue with ajax requests from the client side code to the back end because these are protected by a CSRF check which needs access to the `GU_support_csrf` cookie to succeed. As this cookie has the `sameSite` value of `Lax` [see docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) it is not sent for a cross-site request (Salesforce to support) and so the CSRF check fails and the request returns a 403 error.
Fortunately the Play Framework bypasses CSRF checks for domains which are [trusted using CORS](https://www.playframework.com/documentation/2.8.x/CorsFilter) so we just need to configure CORS to trust the …

Configure CORS for the support domain

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

The decision has been made to completely remove 6/6 for Guardian Weekly.
But we want the ability to bring it back at some point, but it might be a bit different, and we don't know if it'll be an AB test.
In the absence of requirements I'm just removing the control from the AB test. This means all users will _not_ see 6/6.
We can revisit this later and remove the AB test once we know how it's going to work.

Fully disable 6/6

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithImage.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx

This PR removes the subheader copy from the gifting pages for digital subscriptions and Guardian Weekly. 
[**Trello Card**](https://trello.com/c/JvASVIip/168-remove-hardcoded-gifting-subheaders)
A new gifting marketing campaign kicks off next week and the narrative is taking a different direction from the 'even while apart' concept. The old copy could clash so we're removing it.
Before:
After:

Remove subheader copy from gifting product pages

---

support-lambdas/acquisitions-firehose-transformer/scripts/backfill.md
support-lambdas/acquisitions-firehose-transformer/scripts/backfill.sc

On 2021-11-24 we failed to write most acquisitions to the acquisition_events_prod athena table.
This was caused by a temporary fixer.io outage, which meant we didn't have currency rates in dynamodb.
We backfilled the missing data using this script.

Acquisitions backfill script

---

support-frontend/assets/pages/digital-subscription-landing/components/hero/heroWithPriceCards.tsx

The UX is quite bad if the roundel copy is set from the promo tool:
1. It's not clear which cta the roundel copy is referring to (it's actually the second here)
2. The size and formatting of the copy can break the UI
For now the solution is to stop taking the copy from the promo tool.
The roundel will always say "14 day free trial", which is what the default page says.

Disable promo message in roundel

---

support-frontend/app/admin/settings/Settings.scala
support-frontend/app/admin/settings/SettingsProvider.scala
support-frontend/app/admin/settings/Switches.scala
support-frontend/app/controllers/DigitalSubscriptionController.scala
support-frontend/app/controllers/StripeController.scala
support-frontend/app/views/contributions.scala.html
support-frontend/app/views/subscriptionCheckout.scala.html
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/helpers/utilities/dotcomContactPage.tsx
support-frontend/build.sbt
support-frontend/test/admin/settings/SwitchesSpec.scala
support-frontend/test/controllers/SubscriptionsTest.scala

We are migrating the switches json config to a new format. This is to make the S3 file the single source of truth. See switchboard PR: https://github.com/guardian/support-admin-console/pull/256
This PR migrates the scala model and uses the new file, switches_v2.json.
It does some transformation to the json to make the scala case classes more convenient for our app.
The app will fail to come up if the file is missing/invalid or any switches are missing (same behaviour as before)

Migrate to switches v2

---

support-frontend/app/views/subscriptionCheckout.scala.html

this was broken in the previous merge: https://github.com/guardian/support-frontend/pull/3358

Fix subs checkout page script

---

project/build.properties
support-frontend/project/build.properties

Bump SBT to 1.5.6 to get around the log4j vulnerability.

Bump SBT to 1.5.6

---

support-logs/retention-lambda/riff-raff.yaml

Co-authored-by: TomPretty <TomPretty@users.noreply.github.com>
This PR adds a dependency from the lambda to the cfn step in the support-logs-retention lambda.
There waas a race condition where it would sometimes (10% of the time) fail with a 
```
software.amazon.awssdk.services.lambda.model.ResourceConflictException The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:865473395570:function:support-logs-retention-lambda-PROD (Service: Lambda, Status Code: 409, Request ID: 887dde9b-e592-44c6-9ae9-66faa7d6a1b5, Extended Request ID: null)
```
This was because the cfn and the lambda were deploying  the same time, which occasionally collided.

add dependency to deploy to avoid race condition

---

support-workers/cloud-formation/src/package.json
support-workers/cloud-formation/src/yarn.lock

Upgrade the handlebars dependency in the support-workers script used to build the cloud formation. 
This gets rid of a critical severity vulnerability which would not actually affect us but it keeps our dependabot report clean

upgrade handlebars in support-workers

---

support-frontend/package.json
support-frontend/yarn.lock

Upgrade `immer` to version `9.0.6` to address dependabot alert.
This is a nested dependency via `@storybook/react@5.3.21` which requires `immer@1.10.0` via a transitive dependency on `react-dev-utils@9.1.0`, none of the dependencies in this nested tree have updated `immer` to the version with the resolution (`9.0.6`), so I'm adding this to the `resolutions` section in our `package.json`.

Update nested dependency immer

---

support-frontend/package.json
support-frontend/yarn.lock

Upgrade `serialize-javascript` to version `4.0.0` to address dependabot alert.
This is a nested dependency via `uglifyjs-webpack-plugin@^2.2.0`, there is no updated version of `uglifyjs-webpack-plugin`  with the resolution (`4.0.0`), so I'm adding this to the `resolutions` section in our `package.json`.
I've tested our build steps and it all looks OK.

Update nested dependency serialize-javascript

---

support-frontend/assets/components/subscriptionCheckouts/subscriptionsSurvey/SubscriptionsSurvey.tsx

Update the digital pack post-purchase survey link to point to the new survey.
[**Trello Card**](https://trello.com/c/52J7FJew)
We're running new motivation surveys, hence the new link here (replacing the old 2020 one).

Update digital pack post-purchase survey

---

support-frontend/conf/riff-raff.yaml
support-workers/riff-raff.yaml

This PR adds the publicReadAcl: true parameter to the s3 upload for the assets.
This is needed because these are served from the web s3 interface direct to fastly.
There is a coming change to riffraff to make the default "false" instead of "true" https://github.com/guardian/riff-raff/pull/664

add public flag to s3 assets

---

support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

This fixes the link for the promos on the GW gift page
This page has a broken link https://support.theguardian.com/int/subscribe/weekly/gift

use default param for default promo code on gift page

---

project/plugins.sbt
support-frontend/build.sbt
support-payment-api/build.sbt
support-payment-api/src/main/scala/actions/RateLimitingAction.scala
support-payment-api/src/test/scala/actions/RateLimitingActionSpec.scala
support-services/build.sbt
support-services/src/main/scala/com/gu/support/redemption/corporate/DynamoTableAsync.scala

The dependency `akka-http-core` has been marked by snyk as high severity.
Updates to scaffeine/play-googleauth necessary because of a `scala-java8-compat_2.13` version incompatibility

Upgrade to play 2.8.13

---

support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

This Pr prevents us sending PROD PaymentSuccess for test users.
We will send them as stage `PROD-UAT` instead
We have a bunch of alarms looking for PROD payment success events, however it turns out test users (e.g. post deploy tests) will trigger the same event, causing the alarms to not be fired if we have done deploys recently!

don't send PROD PaymentSuccess for test users

---

support-workers/src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

Change contributions thank you email to send the currency field as iso (e.g. AUD) instead of the text version (e.g. AU$)
https://trello.com/c/iuiXcPqV/258-make-thank-you-email-send-eg-gbp-instead-of-as-currency
We noticed the thank you emails were missing the currency symbol.  The code our end didn't seem to have changed in any way for several years, and was expecting the contents of the currency field to be used in the email.  It was previously the ISO code but was changed in 2018 to be the "glyph" as a request from someone https://github.com/guardian/support-workers/pull/114
Current logic in braze is to assume it's an iso currency code and do a look up, so we will match that.
No one on the team that looks after braze seems to know about it so the suggestion is to just fix our end to …

use iso country instead of the text to fix braze issue

---

support-frontend/assets/components/interactiveTable/interactiveTable.tsx
support-frontend/assets/components/interactiveTable/interactiveTableRow.tsx
support-frontend/assets/pages/digital-subscription-landing/components/comparison/interactiveTableContents.tsx
support-frontend/assets/pages/digital-subscription-landing/components/comparison/interactiveTableRowContents.tsx
support-frontend/typescript-errors.json

This PR tries to address errors in `interactiveTables.tsx` and its child components. There are a few more changes than in previous error busting efforts, though each quite small.
- Add several `grid-column` and `grid-row` properties to `interactiveTableRow.tsx` as the styling plugin says it improves browser compatability
- The values for `colSpan` and `aria-colspan` have been changed from strings to numbers 
As in previous PRs I have also added return types where possible, though there were a couple of places (`getRows()` and `getLocalisedRows()`) where what's being returned doesn't fit the nice neat `JSX.Element` or similar. Rather than get bogged down I've left them without return types for now.

Interactive table TS error fixes

---

support-modules/acquisition-events/build.sbt

because it depends on a version of protobuf with a vulnerability.
we [previously](https://github.com/guardian/support-frontend/pull/3431) attempted just a minor version upgrade but this wasn't enough.
Testing:

upgrade google-cloud-bigquery to 2.8.0

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/models/identity/responses/IdentityErrorResponse.scala
support-frontend/app/services/HttpIdentityService.scala
support-frontend/assets/helpers/forms/errorReasons.ts
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts

There are some email providers which are disallowed by Identity eg. `@0815.ru` addressses. Currently when a user tries to sign up for a contribution or subscription with one of these addresses we return a generic 500 error and trigger an alarm which then needs to be investigated.
This PR takes advantage of some [work done by Identity]( https://github.com/guardian/identity/pull/2023) to return a better error message to users and to avoid triggering an alarm for these cases. 
Unfortunately there are still a lot of email addresses which will trigger the alarm, for example `test@gmail.com123`. This is because Identity's email validation regex doesn't pick up the error in this email address, so it is trying to create the user but failing when it tries to create it in Okta as their email …

Show a more specific error message for users with disallowed email

---

support-frontend/conf/DEV.public.conf
support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
support-frontend/test/selenium/util/Config.scala
support-frontend/test/selenium/util/PostDeployTestUser.scala

When I tried to run the selenium tests against CODE to test some changes they failed due to an error writing cookies. This PR fixes that and puts a comment in the `DEV.public.conf` file to make it clear how to run the tests against CODE.

Fix for running selenium tests against code

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/models/identity/requests/CreateGuestAccountRequestBody.scala
support-frontend/app/services/HttpIdentityService.scala
support-frontend/app/utils/EitherTRetry.scala
support-frontend/app/utils/FutureRetry.scala
support-frontend/app/wiring/Controllers.scala

We have been seeing frequent timeouts from Identity when creating guest users which has been causing checkouts to fail. This PR introduces some retry functionality so that when a create attempt times out we try again before giving up.
We had considered moving the create guest account step into the support-workers step function but a potential issue would be if we get a user who gives us a bad email address when Identity is down for some reason we will keep retrying until we eventually find out that it's bad, but by that point the user will have gone away, probably thinking that their purchase has succeeded. It's not clear what we can actually do at that point, we won't be able to email them as we normally would on failure because their email is invalid. While this is a bit of an edge case …

Retry failed Identity calls

---

support-payment-api/src/main/scala/controllers/StripeController.scala

We get quite a few Alarms triggered by requests to the payment-api hitting the rate-limit, this PR increases it from 5 requests over 5 hours to 10 requests.

Increase payment-api rate limit

---

support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala

Currently the link at the bottom of the /au/subscribe/weekly page goes to the default `10ANNUAL` terms & conditions instead

Link to Aus GW promo terms

---

support-frontend/cloud-formation/cfn.yaml

Prepare `cfn.yaml` for the cdk migration. The `GuEc2App` pattern adds some of its own parameters & resources, which conflict with our existing template.
The simple change is to rename our `VpcId` to remove the conflict.
The slightly trickier change is around the security group. We can't just rename our `WazuhSecurityGroup` resource. Changing this logical ID will cause AWS to delete the old resource and create a new one. However, AWS won't let us delete a security group that is being used by ec2 instances (it would probably be bad if it did!). This means we need to do this rename in two steps:
1. Add a new security group with a new name and update all references to the old security group to this new one (this PR)
2. Remove the old security group (#3594)
By adding a new security group and …

Prepare cfn template for cdk migration - phase 1

---

support-frontend/assets/helpers/forms/checkouts.ts

This PR removes the need for a query string to allow SEPA transactions.

remove sepa query param

---

.github/workflows/bundle-analyser.yml
.github/workflows/compressed-size.yml
.github/workflows/scala-steward.yml
.github/workflows/support-frontend-build.yml
.github/workflows/ts-monitor.yml
support-frontend/build.sbt
support-frontend/webpack.ssr.js

This PR adds a github action to run the full support-frontend build. This will replace the Teamcity build which we currently have and has the benefit of moving all of our CI logic into source control rather than having it only accessible through the UI of Teamcity.
It also adds a new action which will test PRs from the [Scala steward fork](https://github.com/scala-steward/support-frontend) which is the method Scala steward uses to open PRs against our codebase. Currently these are not tested by CI which makes dealing with them a pain.
[**Trello Card**](https://trello.com/c/s6l5ywJu/330-move-support-fronted-build-to-github-actions)

Move support-frontend build to Github actions

---

support-frontend/nginx/support.conf
support-frontend/package.json
support-frontend/webpack.dev.js

This fixes an issue where, following the recent upgrade to Webpack 5, the hot reloading feature of Webpack dev server was no longer correctly being proxied via Nginx. It also fixes an issue where Preact devtools were not working when running the site locally.
**NB. After this is merged, everyone will need to run the setup.sh script to update their local Nginx config**
With Webpack 4, we were using the old `public` configuration option to make sure that dev server websocket requests were proxied via our local HTTPS setup:
[Docs on 'public'](https://v4.webpack.js.org/configuration/dev-server/#devserverpublic)
[Dev server script prior to the Webpack 5 upgrade](https://github.com/guardian/support-frontend/blob/773ad1cdc1472a0e1977d87d5c1d3664d06550b1/support-frontend/package.json#L17)
This …

Fix issues with proxying Webpack hot reloading via websocket

---

.github/workflows/support-frontend-build.yml

#3531 introduced a mechanism to run support-frontend builds with Github actions. Unfortunately the build was only running on pull requests, not on merges to `main`. This fixes that.

Run build on merge to main

---

.github/workflows/support-frontend-build.yml
project/plugins.sbt
support-frontend/build.sbt
support-lambdas/acquisition-events-api/build.sbt
support-lambdas/acquisitions-firehose-transformer/build.sbt
support-lambdas/it-test-runner/build.sbt
support-lambdas/stripe-intent/build.sbt
support-redemptiondb/build.sbt
support-workers/build.sbt
supporter-product-data/build.sbt

#3661 updated our Github build action so that it ran on merge to the main branch, however builds were not being picked up by RiffRaff's continuous deployment. This was because we were using a very old version of the `sbt-riffraff-artifact` library which didn't fully support the GHA environment. This has now been upgraded to the latest version and CD is working correctly.
[**Trello Card**](https://trello.com/c/s6l5ywJu/330-move-support-fronted-build-to-github-actions)

Fix continuous deployment for GitHub action build

---

support-frontend/app/actions/CustomActionBuilders.scala
support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/wiring/Controllers.scala

#3436 introduced better handling of disallowed email addresses, however we are still triggering an alarm every time one is used which is unnecessary now that we inform the end user and allow them to input a different email.
This PR removes the alarm for this type of email error.
[**Trello Card**](https://trello.com/c/cipTaMhA/333-prevent-alarm-when-user-signs-up-with-a-blocked-email-domain)

Don't alarm for disallowed email addresses

---

support-payment-api/src/main/resources/cloud-formation.yaml

Remove duplicated VpcId property from `AWS::ElasticLoadBalancingV2:TargetGroup`.

Remove duplicated VpcId property from `AWS::ElasticLoadBalancingV2:TargetGroup`

---

support-frontend/app/controllers/PricesController.scala
support-frontend/app/wiring/AppComponents.scala
support-frontend/app/wiring/Controllers.scala
support-frontend/conf/routes
support-frontend/test/controllers/PricesControllerTest.scala

This adds a `/prices` endpoint.
It takes the internal `ProductPrices` model used by support-frontend and returns a simplified model for use by support-dotcom-components. This enables us to reference regional product prices in dotcom messages.
For now I've just included Digisub and Weekly, and Monthly/Annual rate plans.
If there are promos for a given region/product/rate-plan, then it goes with the `discountedPrice` of the first promo. Otherwise it falls back on the standard `price`.
E.g. response:

Prices endpoint

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala

The apps teams are going to start using the acquisitions api we built rather than sending events via Ophan. To enable this we need to add some missing data values into the acquisition model.
[**Trello Card**](https://trello.com/c/OkahHCdA/412-add-new-values-to-acquisition-data-model-to-support-apps)

Add some new acquisition data values to support apps

---

.github/workflows/scala-steward.yml
.github/workflows/support-workers-build.yml

Following on from #3531 this moves the support-workers build from Teamcity to Github actions. The benefits are the same - having CI/CD configuration in source control.
Once this is merged I'll switch off the old build and change the required check to this build rather than the TC one.

Github action build for support-workers

---

support-frontend/assets/helpers/images/imageCatalogue.json

This PR update the packshot images for Guardian Weekly.
There are 3 image sizes, used in 5 pages.
**1358x954**
| /subscribe | /subscribe/weekly/checkout |
| --- | --- |
| ![GW uk:subscribe](https://user-images.githubusercontent.com/99180049/167438282-10b5db5a-d576-48f5-82b0-a8486358b177.png) | ![GW :subscribe:weekly:checkout](https://user-images.githubusercontent.com/99180049/167439296-5c7dbf09-0bea-46b2-a7bc-76929f87da65.png) |
**1552x1176**
| /subscribe/weekly | /subscribe/weekly/gift |
| --- | --- |
| ![GW uk:subscribe:weekly](https://user-images.githubusercontent.com/99180049/167439449-7d9f6b97-6bd2-4a0c-9af2-cfd461390ea1.png) | ![GW uk:subscribe:weekly:gift](https://user-images.githubusercontent.com/99180049/167439648-0091044a-d483-4bbb-a3d3-17dae93d15f5.png) |
**696x400**
| …

Update GW images

---

support-frontend/build.sbt

Upgrade identity-auth-play to 3.248 to mitigate a critical vulnerability in http4s see https://github.com/guardian/identity/pull/2106 for more info.

Fix a critical vulnerability in http4s

---

cdk/package.json
cdk/yarn.lock

Update `jest` and `ts-jest` to their latest version to fix the [critical vulnerability in minimist](https://github.com/guardian/support-frontend/security/dependabot/59).
@akash1810 This an example of accidental complexity brought by the current coupling @davidfurey was mentioning which we need to address. Team should not need to maintain a compilation and build toolchain (with all the dependencies) for their infrastructure code, otherwise the maintenance costs grow significantly.

Update jest and ts-jest

---

support-frontend/app/controllers/PricesController.scala
support-frontend/conf/routes
support-frontend/test/controllers/PricesControllerTest.scala

Added the ability for the `/prices` endpoint endpoint to include, when the query parameter `?include-summary` is provided, details about the promotions which determine the returned prices.
Also added currency as a price should never be referenced without its currency being alongside.
This is to enable the currently displayed offers on the Digital Subscription and Guardian Weekly checkouts to be shown elsewhere, for example a cancellation-save journey.
N/A

Added the ability for the /prices endpoint to include details about the promotions which determine the returned prices

---

cdk/lib/__snapshots__/frontend.test.ts.snap
cdk/lib/frontend.ts

Currently a single 500 response is often enough to trigger this alarm. This means our `create recurring product failed` alarm is almost always followed by the 5xx alarm. In the spirit of trying to reduce the number of alarms that we receive to reduce noise and increase the proportion of meaningful alarms, we decided to up the threshold.
We can see the last few times that we received the create recurring product alarm the traffic percentage was up to about 3.6%. By upping to 5% the aim is only get alerted by this alarm when an issue is affecting multiple users at the same time.

Increase 5xx alarm threshold

---

.github/workflows/support-frontend-build.yml

Now that we're using the same version of node for cdk and support-frontend there is no need to have two separate node setup steps

Remove set up of extra node version in workflow

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/services/HttpIdentityService.scala

This adds the Ophan page view ID and referrer URL as query parameters when creating a new Identity account for a guest user during the checkout process. We already pass the page view ID as part of the acquisition data, and as we submit form data via AJAX we can access the 'last visited URL' as the `Referer` header on the request, which is automatically added by the browser.
[**Trello Card**](https://trello.com/c/pgyDZqdO)
This is due to a request from the Identity team to help them better track where account registrations originat

Pass Ophan page view id and referer URL when creating an Identity guest account

---

support-modules/rest/src/main/scala/com/gu/rest/WebServiceHelper.scala

Http responses from the Stripe billing API have lots of newlines in them which when logged break out the message into multiple lines, this gets very confusing for large responses.
This PR strips the newline characters before logging

Strip new line characters from response body logging

---

.github/workflows/support-frontend-eslint.yml
.github/workflows/support-frontend-typescript.yml

Adds two new workflows: `support-frontend-typescript` and `support-frontend-eslint`. Now that we've got both typescript and lint errors down to 0, we can turn on these checks in CI to ensure they stay that way.
I've followed the style of dotcom-rendering which is to have them as separate workflows so that they can run in parallel.
**NB:** The new actions won't show on this PR as it's not touching any files in the `support-frontend` directory. I tested they were working by making a small change to a `ts` file, but have now dropped that change.

Add typescript & eslint workflows

---

support-frontend/assets/helpers/page/analyticsAndConsent.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/package.json
support-frontend/window.d.ts
support-frontend/yarn.lock

We need to notify Quantum Metric of a user's AB test participations, using the `window.QuantumMetricAPI.sendEvent` function. This PR sends this relevant data to Quantum Metric.
Whilst doing this I've also updated the logic to load Quantum Metric's script by replacing some custom logic to add the script with `import { loadScript } from '@guardian/libs'`. 
[**Trello Card**](https://trello.com/c/BfI7Ru7b/462-quantum-metric-implement-sendevent-call-for-ab-test-participations)

Notify Quantum Metric of user AB test participations 

---

stripe-patrons-data/src/main/scala/com/gu/patrons/services/StripeSubscriptionsProcessor.scala

We want to filter out the patrons@theguardian.com email address from the Stripe to SupporterProductData pipeline as this is an address used by CSRs when a patron does not provide an email, however we shouldn't filter out all guardian email addresses - mostly because this makes testing difficult!

Small tweak to the patrons data pipeline

---

support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/fields.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/useCardFormFieldStates.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/useSelectedField.ts

A separate piece of work requires some changes to `StripeCardForm.tsx`. The file is pretty big and has a mix of stripe/redux/rendering logic going on which makes it quite difficult to work on. I'm planning to do a few refactors to chunk the file up a bit and make it easier to work with. This first change factors out a couple of hooks:
- useSelectedField
- useCardFormFieldStates
The `useSelectedField` hook isn't really needed at all. I just quite like the aesthetic of having functions that create callbacks to be passed to click handlers. That is, using:
```ts
onFocus={selectField("CVC")}
```
over:
```ts
onFocus={() => selectField("CVC")}
```
The `useCardFormFieldStates` moves the logic associated with keeping track of the state of each of the form fields out of main component and into this …

Factor out some hooks from `StripeCardForm.tsx`

---

support-frontend/assets/pages/contributions-landing/components/StripeCardForm/CreditCardIcons.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/VerificationCopy.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/dom.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/errors.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/logging.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/stripe.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/styles.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/helpers/tracking.ts

A handful of refactors to the `StripeCardForm.tsx` file consisting of:
- adding comment headers
- deleting/updating old comments
- small formatting tweaks (e.g adding some extra spaces)
- moving things around
- factoring out some helper components
- factoring out some helper functions
I'll dig into the reasoning behind these individually.
This just helps to break the file up at a glance into distinct sections
Some of the old comments were a little misleading so I've updated/deleted them where appropriate to make them more helpful
Mainly just adding some spaces that were lost in the typescript migration
I've tried to reorgansise the file to have more important things (e.g the component itself) nearer the top and less important things (e.g the styles) nearer the bottom. I've also moved some …

More `StripeCardForm.tsx` refactors

---

support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardFormContainer.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts

We're aiming to remove all non-serialisable state from the contributions redux store. This PR removes the `createStripePaymentMethod` by moving it into state in the `ContributionsForm` component.

Remove `createStripePaymentMethod` from redux state

---

support-workers/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala

We have some bad support-workers runs which we need to fail immediately, as they're currently retrying and hitting zuora.
This PR changes it to look for an environment variable, and if it exists and the `lastName` in the request matches then it fails.

Fail CreatePaymentMethod for bad runs

---

support-workers/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala

Reverts guardian/support-frontend#3918
It was a temporary change to end a large number of bad runs.
I've added a commit to keep the change to pass through `RetryException`s in the `ErrorHandler`, as this is a useful feature.

Revert "Fail CreatePaymentMethod for bad runs"

---

support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/helpers/tracking/__tests__/quantumMetricHelpersTest.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/helpers/tracking/quantumMetricHelpers.ts
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutForm.tsx
support-frontend/assets/pages/digital-subscription-checkout/components/digitalCheckoutFormGift.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx

This PR implements a `sendEvent` call for Subscription checkout Conversions. To do this I've created a new export `sendEventSubscriptionCheckoutConversion` from `quantumMetric.ts`, there was a lot of repeated logic between this and `sendEventSubscriptionCheckoutStart` so I pulled out the common code between these two functions into a new  function`sendEventSubscriptionCheckoutEvent` that is internal to `quantumMetric.ts`.
[**Trello Card**](https://trello.com/c/juhvvBXC/491-quantum-metric-implement-sendevent-call-for-subscription-conversion)

Quamtum Metric: sendEvent on subscription conversion

---

support-frontend/assets/helpers/productPrice/__tests__/priceDescriptionsDigitalTests.ts
support-frontend/assets/helpers/tracking/__tests__/quantumMetricHelpersTest.ts
support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/__tests__/__fixtures__/productPrices.ts
support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala

the offers are all the same, so a single promo works.
Currently on the checkout page if a user changes their country then it loses the offer

Use global default promo for Digisub

---

support-lambdas/acquisition-events-api/cfn.yaml

bots are hitting `GET /`, which triggers this alarm. We're only interested in POST requests

Limit acquisition-events-api 4XX alarm

---

support-frontend/test/selenium/contributions/RecurringContributionsSpec.scala
support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala
support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala

This reinstates the Selenium tests for paying with direct debit for various products, adding a 'complete recaptcha' step to them.
Now we've reinstated direct debit payment in #3941 we can bring these tests back.

Restore post-deployment tests for direct debit checkouts

---

support-frontend/package.json
support-frontend/yarn.lock

This updates our Browserslist config to use the shared [@guardian/configs](https://github.com/guardian/configs) package, which draws on our actual usage stats.

Use shared Guardian browserslist config

---

support-frontend/assets/helpers/tracking/quantumMetricHelpers.ts
support-frontend/package.json
support-frontend/yarn.lock

This PR updates `@guardian/consent-management-platform` to the latest version so we can query a user's consent state related to Quantum Metric directly. As part of this change I've also switch from using the `onConsentChange` (runs a callback after every change to consent) function exposed by the library to `onConsent` (resolves a Promise on initialisation with a user's consent state) as I don't believe we need to re-run any code on consent status changing.

Quantum Metric: Check Quantum Metric's consent state before

---

support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionAmountChoices.tsx

This PR introduces a new `sendEvent` call on Quantum Metric when users toggle the contribution amount on the contributions checkout or specify an "other amount" to contribute.

Quantum Metric: sendEvent on contribution amount updates

---

support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/helpers/tracking/quantumMetricHelpers.ts
support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx

Note: This PR merges into [gh-sendEvent-contribution-toggle](https://github.com/guardian/support-frontend/tree/gh-sendEvent-contribution-toggle), I'd like to merge that branch's associated PR (https://github.com/guardian/support-frontend/pull/3945) before updating this PR to target `main`.
Trigger sendEvent call to Quauntum Metric's API on Contribution Checkout conversion. The PR splits out some common logic into 2 new functions: `sendEventWhenReadyTrigger` and `getContributionAnnualValue`.

Quantum Metric: sendEvent contribution conversion

---

support-frontend/assets/helpers/forms/paymentIntegrations/amazonPay/setup.ts
support-frontend/assets/helpers/forms/paymentIntegrations/amazonPay/types.ts
support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayCheckout.tsx
support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayLoginButton.tsx
support-frontend/assets/pages/contributions-landing/components/AmazonPay/AmazonPayWallet.tsx
support-frontend/assets/pages/contributions-landing/components/AmazonPay/useAmazonPayObjects.ts
support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
support-frontend/assets/pages/contributions-landing/components/PaymentMethodSelector.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingInit.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts

This change removes the `AmazonLoginObject` and `AmazonPaymentsObject` from the redux store, and moves them to component state. We're removing them as they contain non-serialisable state.
To do this, I've created a `useAmazonPayObjects` hook that is responsible for initialising the AmazonPay sdk and storing the objects in state. I initially used this inside of the new `AmazonPayCheckout` component that I factored out of the `ContributionsSubmit` component. However, that gets mounted/unmounted as the user changes payment method which makes it a little awkward as we only want to initialise the sdk once. Instead, I lifted the `useAmazonPayObjects` hook into the parent `ContributionsSubmit` component as that is always rendered. This makes the `AmazonPayCheckout` component less useful, but I …

Remove AmazonPay objects from redux store

---

support-frontend/assets/helpers/contributions.ts
support-frontend/assets/helpers/forms/checkouts.ts
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts

This is the last bit of state that is non-serialisable. It's legacy state that isn't used anywhere (this means it was always just `null`).
[**Trello Card**](https://trello.com/c/YMpJALyM/507-%F0%9F%9B%A0-redux-toolkit-migration-remove-amazonpay-objects-from-contributions-state-%F0%9F%9B%A0)

Remove third party payment lib from contribs state

---

support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala
support-services/src/test/scala/com/gu/support/promotions/PromotionServiceSpec.scala

`PromotionsService.findPromotions` receives a list of possible `promoCodes`, and returns the full data for each (originating from dynamodb).
We define an array of 'default' promos (in S3), and the ordering of this array is important. But currently the ordering gets lost in `findPromotions`, because it iterates (with `foldLeft`) through the full list of promotions from dynamodb.
This PR changes the logic to iterate through the list of `promoCodes`, mapping each to a promotion object from dynamodb.

Maintain order of promos

---

support-frontend/assets/helpers/images/imageCatalogue.json

This PR update the packshot images for Guardian Weekly.
There are 3 image sizes, used in 5 pages.
**1358x954**
| /subscribe | /subscribe/weekly/checkout |
| --- | --- |
| ![Screenshot 2022-07-08 at 16 39 42](https://user-images.githubusercontent.com/99180049/178026417-4584a37c-37a7-48c1-9165-4be32543fb11.png) | ![Screenshot 2022-07-08 at 16 39 13](https://user-images.githubusercontent.com/99180049/178026375-a91ebc59-1e9b-4741-82ac-45adf56305b6.png) |
**1552x1176**
| /subscribe/weekly | /subscribe/weekly/gift |
| --- | --- |
| ![Screenshot 2022-07-08 at 16 38 36](https://user-images.githubusercontent.com/99180049/178026332-4161c70d-d2d7-459b-877f-462a307e3634.png) | ![Screenshot 2022-07-08 at 16 38 16](https://user-images.githubusercontent.com/99180049/178026273-304e4ab2-1907-4db5-aac7-bb76 …

Update GW landing page images in line with Boris Johnson promo

---

support-frontend/assets/helpers/tracking/quantumMetric.ts

We've been seeing unusually high product values in Quantum Metric (QM), the issue lies in the way we convert the product value when sending it onto QM.
We pass the monetary value of a subscription or contribution to QM, before we send this figure we pass the value through `window.QuantumMetricAPI.currencyConvertFromToValue` to get the value in `GBP`
For example if a user chooses a one off contribution of $30. This value is multiplied by 100 to get it's value in cents: 3000. When this is converted to GBP, the number that is returned from `currencyConvertFromToValue` is 2533.77.  We've been passing 2533.77 to Quantum Metric. The problem is QM interprets this as 253377 (or $2533.77) because it ignores the decimal point. 
The solution is to apply `Math.round()` to the value before we send it …

Quantum Metric: Round product value before sending to Quantum Metric

---

support-frontend/app/admin/settings/Switches.scala
support-frontend/test/admin/settings/SwitchesSpec.scala
support-frontend/test/controllers/SubscriptionsTest.scala

This adds a direct debit feature switch for subscriptions which will allow us to switch off direct debit as a payment method in future if need be.
The corresponding JSON files have been updated in S3 and the new switch is present in the RRCP for all environments.
[**Trello Card**](https://trello.com/c/6JPATMMG/495-put-feature-switches-around-subscription-payment-methods-client-side)

Add direct debit feature switch for subs

---

build.sbt
project/LibraryVersions.scala
support-frontend/build.sbt
support-payment-api/build.sbt

This PR updates `jackson-databind` to version 2.13.3. In order to do this we also needed to update the `jackson-module-scala` transitive dependency which requires an older version of jackson-databind.
[**Trello Card**](https://trello.com/c/QWsbCtTn/506-update-jackson-databind-dependency-high-vulnerability)
To mitigate potential security vulnerabilities.

Bump jackson-databind to version 2.13.3

---

support-frontend/assets/helpers/subscriptionsForms/formValidation.ts

Make a few refactors to the subs form validation logic. This was due to a seemingly unrelated piece of work to migrate the PayPal state to an RTK slice causing some errors in this file. 
I noticed that our types were slightly weaker than they needed to be. We have
```ts
type Error<T> = {
errors: Array<FormError<T>>;
errorAction: (arg0: any) => Action;
};
```
But the `errorAction` function takes the `errors` array if it gets called, so we should be able to use
```ts
type Error<T> = {
errors: Array<FormError<T>>;
errorAction: (errors: Array<FormError<T>>) => Action;
};
```
However, that introduced a new error. What we currently have is an array of 
```ts
type AnyErrorType = Error<AddressFormField> | Error<FormField>;
```
Which we then loop through to dispatch the errors
```ts …
```

Refactor subs form validation

---

cdk/lib/stripe-patrons-data.ts

The alarm we currently have for the Guardian Patrons Stripe export lambda is too sensitive - it triggers after a single failure, however as it processes all records every time and is scheduled to run every 15 minutes, we only need to worry if it fails multiple times consecutively.
This PR updates the alarm so that it will only trigger after 3 failures in a row.

Make the patrons alarm less sensitive

---

support-frontend/assets/components/checkoutBox/checkoutBox.tsx
support-frontend/stories/checkoutLayout/CheckoutBox.stories.tsx
support-frontend/stories/checkoutLayout/CheckoutHeading.stories.tsx

This adds a simple white box component that is used throughout the new checkout MVP to contain elements of the form and other content. The box applies a consistent background colour, font colour, border, border radius, and bottom margin, but has no pre-determined width or height. Additionally there is an accompanying `BoxContents` component that can be used to apply consistent padding at different breakpoints to items inside the box.
[**Trello Card**](https://trello.com/c/N9HYZrrC)
This is another core component of the new checkout MVP.

Create reusable white box container component for checkout MVP

---

support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/ContributionSubscriptionBuilder.scala

Changeing the Customer Acceptance Date for Recurring Contributions to tomorrow instead of today.
Before 26 July 2022 the Customer Acceptance Date for Recurring Contributions was always  the same as the Contract Effective Date (i.e. today). A change was made to push the CAS one day forward so as not to trigger an invoice and payment immediately when making a Recurring Contribution. This will affect the customer experience for users who have no money in their account when purchasing, as they will no longer be notified on the checkout, instead they will be notified by email the day after purchasing.
The reason for making this change relates to a project being undertaken by the Finance team on August 1st 2022 to re-publish revenue schedules from 4-4-5 …

Change the Customer Acceptance Date to tomorrow for Recurring Contributions

---

support-frontend/assets/helpers/tracking/quantumMetric.ts

This PR is an addition to https://github.com/guardian/support-frontend/pull/4024. We need to round `convertedValue` before passing it to Quantum Metric, for the reason explained in https://github.com/guardian/support-frontend/pull/4024.

Quantum Metric: Round contribution value on contributions checkout amount update event

---

support-frontend/stories/checkouts/DatePicker.stories.tsx

Disable `DatePicker` snapshot tests. We should be able to add the tests back if we factor out a presentational component that doesn't have any hardcoded references to `Date.now`.

disable DatePicker snapshot tests

---

support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionAmountOtherAmountField.test.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionAmountOtherAmountField.tsx
support-frontend/package.json
support-frontend/yarn.lock

Factors out a new `ContributionAmountOtherAmountField` component and adds some unit tests. I went back and forth a little bit on the best way to add tests to this component. I was weighing up:
1. Factoring out a simple, presentational component that can be tested very easily (what I did in the end)
2. Just adding tests to the more complex, `ContributionAmount` component. 
Adding the tests to `ContributionAmount` component would have more closely replicated a proper user interaction, but would have required getting things to play nice with redux. 
In the end I decided to factor out a component which would be easy to test - we can just pass in different props and assert it renders in different ways. 
I think we'd also get benefits of some higher level tests too, e.g testing the …

Factor out other amount field component and add tests

---

.github/workflows/payment-api-build.yml
cdk/bin/cdk.ts
cdk/lib/__snapshots__/payment-api.test.ts.snap
cdk/lib/payment-api.test.ts
cdk/lib/payment-api.ts
cdk/package.json
cdk/yarn.lock
support-payment-api/build.sbt
support-payment-api/src/main/resources/riff-raff.yaml

In this phase, we introduce CDK to the payment-api project. At this stage we're just using the `CfnInclude` construct to load the existing cloudformation template. This allows us to get all the plumbing in place (eg generating the template during CI and pointing riffraff at the new location) without also generating new versions of all of the resources. In phase 2, we will spin up a duplicate set of all resources using proper cdk/gu-cdk constructs/patterns. When we are happy this new set of resources is running as expected, we can redirect traffic to the new resources. In phase 3, after the old resources are no longer receiving traffic, we can tear them down.

Payment API CDK migration - Phase 1

---

stripe-patrons-data/src/main/scala/com/gu/patrons/services/StripeSubscriptionsProcessor.scala

There  was a bug with the previous implementation  of this function which meant that it was returning after the first future completed rather than when there were no more records available, this is now fixed.

Fix patrons export

---

support-frontend/test/selenium/contributions/pages/ContributionsLanding.scala

This fixes the post deployment contribs LP payment method tests by updating the relevant test ids following https://github.com/guardian/support-frontend/pull/4056.

Update contribs LP payment method test ids

---

.github/workflows/payment-api-build.yml

For the CDK migration work, it would be convenient to run this workflow manually. In order to do that we need allow it to trigger on the `workflow_dispatch` event: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow.
Annoyingly we can't actually test this is working as we need the updated workflow in the `main` branch to trigger it manually!

Allow payment api build to run on dispatch

---

support-frontend/assets/pages/contributions-landing/components/DigiSubBenefits/BenefitsBulletPoints.tsx

This PR
- Reorders benefits list in checkout
- Greys out benefits below the threshold amount
- Changes the copy related to newsletters dependant on country group
[**Trello Card**](https://trello.com/c/M5ZHIGk0/573-minimal-checkout-changes-to-release-v1-winning-test-variant)
These are the minimal design and copy changes needed to release v1 of the upcoming test
| UK below threshold | UK above threshold |
| -- | -- |
| <img width="505" alt="Screenshot 2022-08-11 at 10 44 47" src="https://user-images.githubusercontent.com/44685872/184107032-81578f84-831d-4cce-98ea-d8981cd41faa.png"> | <img width="505" alt="Screenshot 2022-08-11 at 10 45 21" src="https://user-images.githubusercontent.com/44685872/184107232-5e56964b-a534-4524-b434-86d346d528c7.png"> |

Minimal updates for v1 benefits test

---

support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss

Co-authored-by: Maria Olanipekun <marialani@users.noreply.github.com>
Co-authored-by: Paul Dempsey <paul-daniel-dempsey@users.noreply.github.com>
This PR fixes a visual layout bug for the Digital Subscriptions pack shot on the subscriptions-landing-page
[**Trello Card**](https://trello.com/c/bj8rocra/433-subscriptions-lp-digisub-packshot-mobile-layout-bug)

Fix layout bug for DigiSubs packshot

---

support-frontend/assets/components/headers/links/links.tsx

This PR fixes a missing yellow highlight selection bug for Newspaper  /  home delivery 
[**Trello Card**](https://trello.com/c/KcjWDEQ3/518-fix-issue-with-header-link-highlight-on-newspaper-landing-page)

fix issue with newspaper link highlighting in header

---

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx

This PR adds a new test to validate that, in the Guardian Weekly checkout, the prices displayed are those for the delivery country, not the billing country.

re-add previous changes

---

support-frontend/assets/helpers/subscriptionsForms/rules.ts

Email should not have a max-length validation on it, this rule was incorrectly added when adding max-length validation to first and last name.

Remove email max-length validation message

---

support-frontend/assets/helpers/subscriptionsForms/submit.ts

When we work out which promo code applies in the Guardian Weekly checkout we need to use the country from the user's delivery address as this is what pricing is worked out from. Previously we weren't doing this so this PR changes the logic.

Work out promo code from delivery address not billing address

---

support-frontend/app/controllers/PaperSubscriptionController.scala
support-frontend/app/controllers/SubscriptionsController.scala
support-frontend/app/services/pricing/DefaultPromotionService.scala
support-models/src/main/scala/com/gu/support/promotions/DefaultPromotions.scala

We already do this for Guardian Weekly, this PR replaces hardcoded default promos for the `Paper` product.
I tested locally by:
1. setting `stage="PROD"`
2. adding `"paper": ["AUTUMN14"]` to the config file in S3
3. checking the `AUTUMN14` promo comes through on the default `/subscribe/paper` page

Get paper default promos from S3

---

support-frontend/assets/helpers/__tests__/formValidation.ts
support-frontend/assets/helpers/forms/formValidation.ts
support-frontend/assets/helpers/subscriptionsForms/rules.ts

We've seen invalid (too long) first name (max length 40), last name (max length 40) and email addresses (max length 80) submitted from the Contributions checkout which have caused errors on the server. 
This happens because the Contributions form does not currently block the form's submission on max-length validation errors, although it does show the validation error message on the form's submission.
After looking at this I found we're using different logic to show validation error messages and prevent form submission on the Contributions checkout. The rules defined in `assets/helpers/subscriptionsForms/rules.ts` determine when validation error messages show. However the rules defined in `support-frontend/assets/helpers/forms/formValidation.ts` are used when determining whether the form …

Block contributions form submission on first name, last name and email validation errors

---

support-frontend/assets/components/headers/header/header.scss
support-frontend/assets/components/headers/header/header.tsx
support-frontend/assets/components/headers/header/headerWithCountrySwitcher.tsx
support-frontend/assets/components/headers/links/links.tsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

We need to remove the 'Support' page on the Support site, remove it from the nav.
This should be released behind the ab-newProduct 0% AB test so they're visible to the variant only. This AB test has already been set-up and is in use for showing changes to the checkout, you can force the AB test to be visible as so: https://support.theguardian.com/uk/subscribe#ab-newProduct=variant
[**Trello Card**](https://trello.com/c/3UI1xLUM/576-support-site-remove-the-support-landing-page)

Pd support link remove

---

support-frontend/assets/helpers/forms/recaptcha.ts

This adds Sentry logging when the Recaptcha script fails to load.
This increases visibility on problems with Recaptcha loading in certain environments.

Add sentry logging when recaptcha fails to load

---

support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.tsx
support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/components/playback.tsx
support-frontend/assets/components/recaptcha/recaptcha.tsx
support-frontend/assets/components/subscriptionCheckouts/stripeForm/composedStripeElements.tsx
support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.tsx
support-frontend/assets/helpers/customHooks/useRecaptcha.ts
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx

This moves responsibility for loading the recaptcha script and rendering the checkbox into the `Recaptcha` component.
When loading recaptcha in a parent component via the hook, we were depending on the placeholder element `<div id="robot_checkbox"></div>`, which the recaptcha checkbox attaches to, being available by the time the script itself loaded. Normally this would be fine, as a `useEffect` hook is guaranteed to be called _after_ the first component render.
However in the case of the Stripe payment form components, on the first render the component will be empty- we wait for the Stripe SDK to load before rendering the contents of the form, _including the recaptcha placeholder_. This was inadvertently causing a race condition between the recaptcha script and the Stripe SDK- if Stripe …

Make recaptcha script loading the responsibility of the Recaptcha component

---

support-frontend/assets/helpers/tracking/quantumMetric.ts

Logs the error message when the Quantum Metric script fails to load. We see this error in Sentry often and this extra information might help understand why.

Log error message on Quantum Metric script load error

---

support-frontend/assets/components/headers/links/links.tsx

The "Subscriptions" and "Newspaper" links in the navigation should only be visible to users within the UK.
This should be released behind the ab-newProduct 0% AB test so they're visible to the variant only. This AB test has already been set-up and is in use for showing changes to the checkout, you can force the AB test to be visible as so: https://support.theguardian.com/uk/subscribe#ab-newProduct=variant
NOTE : 2 menu items small enough to not require side-bar (additional code change reqd?)
[**Trello Card**](https://trello.com/c/d3CVEEHj/652-support-site-only-show-subscriptions-and-newspaper-links-in-the-nav-for-the-uk)

Pd links remove newspaper subscriptions nonuk

---

support-frontend/assets/__test-utils__/testStore.ts
support-frontend/assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts
support-frontend/assets/helpers/redux/contributionsStore.ts
support-frontend/assets/helpers/redux/debug/reducer.ts
support-frontend/assets/helpers/redux/redemptionsStore.ts
support-frontend/assets/helpers/redux/subscriptionsStore.ts
support-frontend/assets/helpers/subscriptionsForms/formFields.ts
support-frontend/assets/helpers/subscriptionsForms/formReducer.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/pages/contributions-checkout-in-epic/ContributionsCheckout.tsx
support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.ts
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionErrorMessage.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionState.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/subscriptions-redemption/api.ts

This replaces the current Redux 'debug' setup, which records action history only for subscriptions checkouts, with a dedicated debug slice incorporated into all checkouts.
The debug slice has no reducers of its own but uses a [matcher](https://redux-toolkit.js.org/api/createReducer#builderaddmatcher) to determine what other actions it listens to. I've set it up to record any action that gets dispatched, but if there are actions that we find are too noisy or not relevant for debug purposes we can use this to exclude them in future.
The majority of changes in this PR are just updating state types for various contribution components now that the top level shape of the state has changed.
This replaces the old debug mechanism with a RTK-based one, and extends it to all checkouts, meaning we …

Add a debug slice to enable sending Redux action history from all checkouts

---

support-frontend/assets/__test-utils__/testStore.ts
support-frontend/assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts
support-frontend/assets/helpers/redux/contributionsStore.ts
support-frontend/assets/helpers/redux/debug/reducer.ts
support-frontend/assets/helpers/redux/redemptionsStore.ts
support-frontend/assets/helpers/redux/subscriptionsStore.ts
support-frontend/assets/helpers/subscriptionsForms/formFields.ts
support-frontend/assets/helpers/subscriptionsForms/formReducer.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/pages/contributions-checkout-in-epic/ContributionsCheckout.tsx
support-frontend/assets/pages/contributions-landing/checkoutFormIsSubmittableActions.ts
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionErrorMessage.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionFormFields.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionState.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.tsx
support-frontend/assets/pages/contributions-landing/components/StripeCardForm/StripeCardForm.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/subscriptions-redemption/api.ts

This is a re-do of #4188 - please see that PR description for details on the change.
The previous PR caused a problem on the contributions checkout with the async thunk action that checks the validity of direct debit details, which contains a `meta` property with an unserializable, circular reference. This issue has been corrected by only serialising the `type` and `payload` values from actions, and additionally adding a try/catch to the debug reducer to guard against future edge cases.

Add a debug slice for Redux action history - with serialisation error protection

---

support-frontend/assets/pages/contributions-landing/contributionsLanding.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingPage.tsx

This PR removes function calls that are duplicated in the `contributionsLanding` and `contributionsLandingPage` modules.
Earlier today I noticed the function `setUpTrackingAndConsents` was unexpectedly being called twice on the Contributions Landing Page. 
Having investigated this I found that we are calling it twice in the hierarchy of components used to render this page:
```jsx
<ContributionsLanding>
<ContributionsLandingPage />
</ContributionsLanding>
```
Originally `setUpTrackingAndConsents` was called once from `ContributionsLanding` , however in https://github.com/guardian/support-frontend/pull/4156 we split out the main body of the component into two new child components (`SupporterPlusLanding` / `ContributionsLandingPage`), these are rendered conditionally depending on whether a …

Remove duplicated code between ContributionsLanding and ContributionsLandingPage

---

support-frontend/assets/components/nav/nav.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/nav/Nav.stories.tsx

This PR adds a `Nav` component for use on the new Guardian supporter checkout. This component will only be displayed on screen sizes desktop and above.
[**Trello Card**](https://trello.com/c/tKBalS2s/638-checkout-mvp-build-new-nav-component)
Desktop
LeftCol
Wide

Add Nav component - checkout MVP

---

support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.tsx

This PR is to support Marketing's autumn campaign of newspaper offers.
They are creating a number of offers for this campaign and (initially) want the offer text in the product price cards to be empty as it otherwise displays the saving from regular price vs retail price without taking the promotion into account.
In conjunction we are making some of the promotions default.

Newspaper autumn offers changes

---

supporter-product-data/cloudformation/cfn.yaml

I've noticed an error in the supporter product data logs because it is unable to write metric to CloudWatch due to a permissions issue. This PR fixes that

Allow supporterProductData to put metric data in CloudWatch

---

support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.tsx
support-frontend/assets/components/headers/simpleHeader/countrySwitcherContainer.tsx
support-frontend/assets/components/headers/simpleHeader/simpleHeader.tsx
support-frontend/assets/components/layout/container.tsx
support-frontend/assets/components/nav/nav.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/core/SimpleHeader.stories.tsx

This adds a simplified header component for the new checkout, and adds it to the new page showing the country group switcher below the desktop breakpoint.
I've also made some tweaks to the `Nav` component to make sure we retain the top border below the desktop breakpoint, and make sure the switcher sits in line with the body columns when visible.
[**Trello Card**](https://trello.com/c/Ho5AyV02)
This is part of the ongoing work for the new product checkout.

Add header for new checkout

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx

The amounts being shown for print + digital on the newspaper checkout are incorrect so we are going to switch it off. Assuming that the new proposition launches and  is successful we can delete it at a later date as it will no longer be needed.

Remove the print + digital component from newspaper checkout

---

support-frontend/assets/components/StripePaymentRequestButton/StripePaymentRequestButton.tsx
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/actions.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/selectors.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/state.ts
support-frontend/assets/helpers/redux/checkout/payment/reducer.ts
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts

This refactors the Redux state relating to the Payment Request Button- which allows users to pay with Apple/Google pay or other saved payment methods- into an RTK slice, and removes the old code. It also removes some other action and reducer code that is no longer being used.
[**Trello Card**](https://trello.com/c/E0iqjJ1R)
This is the last bit of payment-related state that needed migrating to RTK 🥳

Migrate payment request button state to Redux Toolkit

---

support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.tsx

This is  a PR to remove the country dropdown on the Subscriptions Landing Page
This should be released behind the ab-newProduct 0% AB test so they're visible to the variant only. 
[**Trello Card**](https://trello.com/c/whARz87c/706-remove-the-country-dropdown-on-the-subscriptions-landing-page)
After removing Digital Subscriptions from sale the Subscriptions Landing Page ([Support the Guardian | Get a Subscription](https://support.theguardian.com/uk/subscribe)) will only become relevant to the UK only, as Guardian Weekly will be the only sub on offer to non-UK regions.So we have to remove the country dropdown on the Subscriptions Landing Page
Before Change
After change

PR to remove the country dropdown on the Subscriptions Landing Page

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/priceCards/priceCard.tsx
support-frontend/assets/components/priceCards/priceCards.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/helpers/forms/checkouts.ts
support-frontend/assets/helpers/redux/checkout/product/selectors/selectedAmount.ts
support-frontend/assets/helpers/redux/commonState/selectors.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
support-frontend/stories/checkouts/PriceCard.stories.tsx
support-frontend/stories/checkouts/PriceCards.stories.tsx

This adds the component for selecting the user's contribution amount, along with the logic to manage updating Redux and thus feeding back into the state of the benefits checklist component.
There are two outstanding aspects of this work that still need to be resolved:
- The 'greyed out' text in the benefits checklist [has insufficient colour contrast against a white background](https://www.whocanuse.com/?bg=ffffff&fg=999999)
- We don't have precise wording for the benefits list title when the user chooses to contribute a custom amount and the amount of their contribution is initially nothing.
[**Trello Card**](https://trello.com/c/NYI2pZTN)
This is a core component for the new product checkout.

Add PriceCards component and connect to benefits checklist via Redux

---

.github/PULL_REQUEST_TEMPLATE.md

This updates our PR template so the links for the accessibility checks go to useful resources rather than the broken accessibility.gutools.co.uk site.

Update broken accessibility testing links in our PR template to point at useful resources

---

support-frontend/assets/helpers/page/analyticsAndConsent.ts
support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
support-frontend/assets/helpers/redux/checkout/product/selectors/cartValue.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/pages/contributions-landing/components/ContributionAmount.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.ts

The aim here is to keep QM informed of the "cart value" during a contributions checkout session.
We currently have a function `sendEventContributionAmountUpdated` that's called when user clicks on a contribution amount button on the contributions checkout, this function informs Quantum Metric of the "cart value" of the checkout  session. However we only send this event on these button click, whilst a users cart value can be set on other page events, specifically...
- **Page load:** When a user lands on the page there is a default payment frequency and a default payment amount already selected - so the cart essentially has a default value on page load, should we track this as a user could feasibly checkout without clicking a payment amount button.
- **Changing payment frequency:** When a …

Quantum Metric: sendEventContributionCartValue

---

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.tsx

This updates the contributions thank you pages copy to include reference to soft-opt in.
[**Trello Card**](https://trello.com/c/bHWcgbI8/752-ensure-that-appropriate-soft-opt-in-copy-is-on-all-post-purchase-confirmation-pages)
This copy was to be included when soft opt in was first implemented. It may have since be overwritten, this is to reinstate the correct copy whilst we continue to investigate.

Update TY page copy

---

support-frontend/app/monitoring/SentryLogging.scala
support-frontend/build.sbt

Update Scala dependency sentry-logback from 1.7.30 to 6.5.0 for support-frontend.
[**Trello Card**](https://trello.com/c/z0bNp5nJ/603-support-frontend-update-scala-dependency-sentry-logback)
We are five major versions behind, and automated Scala Steward PRs are failing for this dependency, so we need to manually update.
Cf. https://github.com/guardian/support-frontend/pull/4164
Latest-https://github.com/guardian/support-frontend/pull/4274

Changed sentry logback to 6.5.0

---

support-config/src/main/resources/touchpoint.PROD.conf
support-config/src/main/resources/touchpoint.SANDBOX.conf
support-config/src/main/resources/touchpoint.UAT.conf
support-config/src/main/scala/com/gu/support/config/ZuoraConfigProvider.scala
support-models/src/main/scala/com/gu/support/zuora/api/Account.scala
support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
support-models/src/test/scala/com/gu/support/zuora/api/SerialisationSpec.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscribeItemBuilder.scala
support-workers/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionStepsSpec.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala
support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/GuardianWeeklySubscriptionBuildersSpec.scala

Inserting the correct invoice template ID, based on the sold-to country and currency, into every account creation API call to Zuora.
[**Trello Card**](https://trello.com/c/LFp15ME6)
This change replicates, and improves upon, what used to happen in Membership Common (https://github.com/guardian/membership-common/pull/539). It ensures any new customer having their product supplied to Australia, paying AUD, who wants to download (within Manage which calls https://github.com/guardian/invoicing-api/tree/main/src/main/scala/com/gu/invoicing/pdf) their invoice from Zuora, has the correct company name, and correct layout for GST (Goods and Sales Tax), rather than showing the UK company name and VAT.
There will also be some follow-up changes to:
1. Backfill
2. Create a Zuora Workflow to ensure …

Set the correct invoice template ID when creating a subscription in Zuora

---

support-workers/src/test/scala/com/gu/zuora/Fixtures.scala

#4261 introduced a mechanism to set the correct invoice template on a subscription, however it broke some integration tests because it used dummy data in the fixtures used by those tests to make calls made to Zuora whereas Zuora expects the invoice id which is passed in to actually exist.
[**Trello Card**](https://trello.com/c/PjWsKxcH/773-fix-it-test-regression)

Fix integration tests

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/otherAmount/otherAmount.tsx
support-frontend/assets/components/priceCards/priceCards.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/package.json
support-frontend/stories/checkouts/OtherAmount.stories.tsx
support-frontend/yarn.lock

This adds the 'other amount' field to the new checkout, to allow users to select a custom amount. It uses the [NumericInput](https://guardian.github.io/source/?path=/docs/packages-source-react-components-development-kitchen-numericinput--playground) component from Source dev kitchen to display the currency glyph either before or after the field, depending on localisation, and force a numeric keypad on mobile devices.
[**Trello Card**](https://trello.com/c/3TeO6cLv)
This allows users to select a custom amount to contribute. I've also added a supplementary hint to the input indicating our (configurable) minimum contribution amount, as we don't currently surface this to users.

Add the 'other amount' field to the new product checkout

---

support-frontend/assets/components/button/upsellButton.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/assets/helpers/globalsAndSwitches/globals.test.ts
support-frontend/assets/helpers/globalsAndSwitches/globals.ts
support-frontend/assets/helpers/redux/checkout/product/state.ts
support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx

This PR adds the up-sell CTA to the v2 checkout. A previous [PR](https://github.com/guardian/support-frontend/pull/4256) doing this was merged and [reverted](https://github.com/guardian/support-frontend/pull/4284) yesterday due to a bug caused by changes to the default product state in redux (see below). 
Most all of the changes in this PR are the same as the original, apart from the changes necessary to fix this bug, which are as follows:
- globals.ts - where the `getGlobal` function now has the ability to take a full path i.e. one prefixed with the string `window.guardian`
- globals.test.ts - where we include a test to ensure the `getGlobal` function can handle a string prefixed with `window.guardian` 
Whilst working on the original PR we'd encountered a bug in storybook whereby the …

Reinstate Upsell CTA - v2 Checkout

---

support-frontend/assets/components/subscriptionCheckouts/subscriptionsSurvey/SubscriptionsSurvey.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.tsx
support-frontend/assets/pages/digital-subscription-checkout/thankYouContent.tsx
support-frontend/assets/pages/digital-subscription-checkout/thankYouGift.tsx
support-frontend/assets/pages/digital-subscription-checkout/thankYouPendingContent.tsx
support-frontend/assets/pages/digital-subscription-landing/components/feedbackWidget/feedbackWidget.tsx
support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.tsx

This PR removes a) removes / updates post-purchase motivation survey links from our 'thank you' pages and b) removes the 'Is this page helpful/' feedback widget from the digisub product landing page.
[**Trello Card**](https://trello.com/c/M2oMTLLM/778-motivations-survey-on-support-site-update-links-and-remove-where-no-longer-required)
Some old surveys are not longer required and we shouldn't keep gathering responses for them. We've also moved away from SurveyMonkey to Formstack, and we have a fresh survey ready to go for Contributions.
(The widget has been removed.)
The Contributions 'thank you' page survey link has been updated and the survey has been switched off for the digi sub / digi sub gift thank you pages. Surveys are unchanged for print subscriptions (including Guardian Weekly).

Update survey links (and remove feedback widget)

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/assets/components/otherAmount/otherAmount.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
support-frontend/stories/checkouts/OtherAmount.stories.tsx
support-frontend/stories/screens/SupporterPlusLanding.stories.tsx

This updates the behaviour of the 'choose your amount' field and the benefits checklist in the following ways:
- When the field is empty or the user has entered an amount lower than the minimum contribution amount, the benefits list is not rendered, rather than being rendered with all items greyed out/crossed out
- When the user enters an amount at or above the minimum amount, the list will appear
- We no longer show supporting text informing the user of the minimum contribution amount as this is too much of a divergence from the existing checkout
[**Trello Card**](https://trello.com/c/tu7pD3uM)
These are some amendments following design review of the initial implementation

Update the interaction of the other amount field with the benefits list

---

support-frontend/app/controllers/CreateSubscriptionController.scala

We want to add a cookie (gu_supporter_plus) which enables the website to identify and treat a signed-out browser as hosting a recently subscribed "Supporter plus" product holder, however the new cookie has not yet been cleared by the data protection team and added to the consent manangement platform so we are commenting it out until that work is complete.
[**Trello Card**](https://trello.com/c/MgspqDBS/802-dont-set-gusupporterplus-cookie-until-it-is-added-to-the-consent-management-platform)

Remove the gu_supporter_plus cookie for now

---

support-frontend/app/controllers/LandingCopyProvider.scala
support-frontend/app/controllers/PaperSubscriptionController.scala
support-frontend/app/controllers/WeeklySubscriptionController.scala
support-services/src/main/scala/com/gu/support/promotions/ProductPromotionCopy.scala

PR to  correct the  promotion code in offer strap line on the Guardian Weekly International Landing Page.
[**Trello Card**](https://trello.com/c/h252Ele8/725-gw-int-lp-offer-strap-line-bug)
The offer strap line on the Guardian Weekly International Landing Page is displaying a promotion in the strap line even if the promotion is only set-up for "Domestic" fulfilment in the promo code tool.
This is a bug, the only promos supported on the international landing page are those set-up for "ROW" fulfilment in the promo code tool.
Before Change
After Change
"Save up to 35% a year" is the default PromoCode.

Rb gw promo copy fix

---

support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.tsx

Update the headline and body copy for consistency ahead of the v2 checkout AB test.
Update the Contributions checkout headline and body copy for consistency with the new v2 checkout design, ahead of the upcoming AB test.
[**Trello Card**](https://trello.com/c/Cm0SKxUh/726-update-headline-and-body-copy-on-current-checkout-for-mvp-release)
We want to have consistency for this copy between variants in the upcoming test. There's no harm in releasing this change early.

Update contributions checkout copy

---

support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/window.d.ts

QM contacted us to request we update the 2nd argument in the `window.QuantumMetricAPI.sendEvent` call. Previously this had been `0` or `1`. `0` would indicate the event was not a conversion event, and 1 would indicate it was a conversion event. They've requested we change this, so now we still pass `1` for a conversion event, and non-conversion events will now be either `0` or `64`. `0` will indicate a non cart value event, and `64` will indicate a cart value event. "cart value" is the term QM use to indicate the value of the subscription/contribution a user is going to make.
I've also updated the QM script source.
[**Trello Card**](hhttps://trello.com/c/25ul9iPp/803-quantum-metric-cart-value-changes)

Update 2nd Argument in Quantum Metric sendEvent call

---

support-frontend/assets/components/errorSummary/errorSummary.tsx
support-frontend/assets/components/errorSummary/errorSummaryContainer.tsx
support-frontend/assets/components/otherAmount/selectors.ts
support-frontend/assets/components/paymentButton/noPaymentMethodButton.tsx
support-frontend/assets/components/stripeCardForm/selectors.ts
support-frontend/assets/components/stripeCardForm/stripeCardForm.tsx
support-frontend/assets/components/stripeCardForm/stripePaymentButton.tsx
support-frontend/assets/helpers/customHooks/useAutoFocus.ts
support-frontend/assets/helpers/customHooks/useFormValidation.ts
support-frontend/assets/helpers/redux/checkout/checkoutSelectors.ts
support-frontend/assets/helpers/redux/checkout/recaptcha/reducer.ts
support-frontend/assets/helpers/redux/checkout/recaptcha/state.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx

This adds
- An error summary component which will appear at the top of the form on validation and automatically receive keyboard focus, listing all errors as anchor links to the relevant input
- A `useFormValidation` hook to wrap any payment function that will submit the form, which will run form validation and only continue with form submission if the form state is valid.
- Some tweaks to error display based on validating the Stripe form (work in progress)
[**Trello Card**](https://trello.com/c/n6T98HFX)
This is a key part of building the new form validation system. Having an error summary with anchor links makes it much, much, much easier for all users to tackle problems that prevent them from submitting the form. The summary is announced to screen readers and auto-focused to make it …

Add error summary component and form validation on submit for new checkout

---

support-frontend/assets/components/subscriptionCheckouts/subscriptionsSurvey/SubscriptionsSurvey.tsx
support-frontend/assets/components/thankYou/feedback/FeedbackItems.tsx
support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/subscriptionSurvey.tsx

We've moved to an enterprise Formstack account. We need to migrate all old Formstack forms (on the 'legacy' account) to the new instance.
This PR covers updating the existing links so that they resolve correctly to the new instance.
[**Trello Card**](https://trello.com/c/dPnIjjdW/807-migrate-formstack-surveys-to-enterprise-formstack-instance)

Migrate Formstack links

---

support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestCompletion.ts
support-frontend/assets/components/personalDetails/personalDetails.tsx
support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
support-frontend/assets/components/personalDetails/stateSelect.tsx
support-frontend/assets/helpers/internationalisation/shouldCollectStateForContribs.ts
support-frontend/assets/helpers/redux/checkout/personalDetails/reducer.ts
support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/stories/checkoutLayout/PersonalDetails.stories.tsx

This adds validation to the personal details section on the new checkout form, displaying inline errors beside the relevant form fields as well as in the error summary at the top of the form.
It also adds a new `StateSelect` component to work with the new validation system and that makes use of the Source `Select` component, and makes some overall updates to styling.
[**Trello Card**](https://trello.com/c/n6T98HFX)
This is part of the ongoing validation system work for the new form.

Add validation to the personal details section on the new checkout

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.test.ts
cdk/lib/stripe-patrons-data.ts
stripe-patrons-data/build.sbt
stripe-patrons-data/riff-raff.yaml
stripe-patrons-data/src/main/scala/com/gu/patrons/conf/PatronsStripeConfig.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/PatronCancelledEventLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/model/Errors.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/Fixtures.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/SerialisationSpec.scala
support-modules/supporter-product-data-dynamo/src/main/scala/com/gu/supporterdata/model/FieldNames.scala
support-modules/supporter-product-data-dynamo/src/main/scala/com/gu/supporterdata/services/SupporterDataDynamoService.scala

Currently we have a system to add Patrons customers into the SupporterProductData data store when they take out a subscription, but no way to remove them when they cancel. This PR provides that mechanism.
This PR consists of a lambda `PatronCancelledLambda` which is triggered by an API Gateway endpoint which in turn is called by a Stripe webhook whenever a subscription is cancelled (the webhook type is `customer.subscription.deleted`). 
This then finds the appropriate record in the Dynamo table and sets a cancellation date attribute to today.
[Details of how to test this are here](https://docs.google.com/document/d/1IbU_r-h71cIHbtSpWkm43E_TRTxoKNQtjb4-PekXRkI/edit#heading=h.z5ca9etiqjqp)

Patron cancellations

---

support-frontend/assets/components/headers/simpleHeader/simpleHeader.tsx
support-frontend/assets/components/legal/contribLegal/contribLegal.tsx
support-frontend/assets/components/page/pageScaffold.tsx

This ensures that the v2 checkout and thank you pages stretches to fit the entire height of their container on larger screen sizes and turns the logo in the header into a link
[**Trello Card**](https://trello.com/c/bxeDOc3Y/817-ensure-the-page-scaffold-stretches-to-fit-the-entire-height-of-the-screen-on-larger-screen-sizes)
[**Trello Card**](https://trello.com/c/3NlwL7tj/804-make-the-guardian-logo-a-link-on-the-v2-checkout)

Fix v2 page layout, add link to header logo

---

support-frontend/assets/components/paymentButton/directDebitPaymentButton.tsx
support-frontend/assets/helpers/customHooks/useRecaptcha.ts
support-frontend/assets/pages/supporter-plus-landing/components/directDebitWrapper.tsx
support-frontend/assets/pages/supporter-plus-landing/paymentButtons.ts
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/window.d.ts

This adds a `DirectDebitPaymentButton` that opens the old direct debit popup form after validating the rest of the form, and a simple wrapper component for the form itself that manages the payment completion state.
It also tackles a small issue with the `Recaptcha` component and re-renders.
[**Trello Card**](https://trello.com/c/dZXBz1Q4)
We need to retain the old form for now until we can get a new design validated by GoCardless. This integrates it into the new form and allows payment via direct debit to be taken.
**NB. The old direct debit form is _not_ keyboard or screen reader navigable, which is why it needs to be replaced ASAP**

Integrate the old direct debit form with the new checkout

---

support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
support-frontend/stories/screens/supporterPlusThankYou/AusSupporterPlusThankYou.stories.tsx
support-frontend/stories/screens/supporterPlusThankYou/ROWSupporterPlusThankYou.stories.tsx

This updates the Header copy for the Supporter Plus thank you pages. 
Please see [this section](https://docs.google.com/document/d/1YBqE24iC2LZpdY_wfwLepgdN3zObpYe793DmAgdp_Pg/edit?hl=en-GB&forcehl=1#heading=h.6qt1hvesks1q) of the copy update dock for the required copy combinations. Until we test the live checkout you can view these copy updates / the expected thank you page header text combinations [here](https://62e115310aef0868687b2322-koviusoskb.chromatic.com/?path=/story/screens-supporter-plus-thank-you-page-rest-of-world--one-off-not-signed-in) in storybook. 
[**Trello Card**](https://trello.com/c/wIJdGCxX/730-show-appropriate-copy-on-thank-you-page-for-v2-checkout)
Please see the one-off/recurring supporter plus [storybook](https://62e115310aef0868687b2322-koviusoskb.chromatic.com/? …

Update V2 Thank You Page header copy

---

support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.tsx

[This PR](https://github.com/guardian/support-frontend/pull/4353/files#diff-7b8647d698721301523125caa4577622c2098c3a91ab14090f6e2d237787b92a) added the payment method selector for the v2 checkout and did some refactoring of the existing component. This PR reverts the existing payment method selector back to it's original state and removes a visual bug that had been introduced.

Fix payment method selector bug

---

support-frontend/assets/components/payPalPaymentButton/payPalButton.tsx
support-frontend/assets/components/payPalPaymentButton/payPalButtonProps.ts
support-frontend/assets/components/payPalPaymentButton/payPalOneOffContainer.tsx
support-frontend/assets/components/payPalPaymentButton/payPalPaymentButton.tsx
support-frontend/assets/components/payPalPaymentButton/payPalRecurringContainer.tsx
support-frontend/assets/components/payPalPaymentButton/utils.ts
support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
support-frontend/assets/helpers/customHooks/usePayPal.ts
support-frontend/assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts
support-frontend/assets/helpers/redux/checkout/payment/contributionsSideEffects.ts
support-frontend/assets/helpers/redux/checkout/payment/payPal/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/payPal/thunks.ts
support-frontend/assets/helpers/redux/checkout/payment/subscriptionsSideEffects.ts
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/supporter-plus-landing/paymentButtons.ts
support-frontend/window.d.ts

This adds PayPal as a payment method to the new checkout for both one-off and recurring contributions, using the button from the PayPal SDK for the latter.
I've taken some time to improve the types and refactor our handling of recurring PayPal payments specifically, as the existing implementation of this has quite a lot of dead code and is pretty confusing to try and follow.
In the future we should probably look at migrating to use [@paypal/paypal-js](https://github.com/paypal/paypal-js/) as this comes with built-in types.

Add PayPal payment method for new checkout

---

support-frontend/assets/components/loadingOverlay/loadingOverlay.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
support-frontend/assets/components/progressMessage/progressMessage.tsx
support-frontend/assets/helpers/redux/checkout/payment/stripe/reducer.ts
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/checkoutLayout/LoadingOverlay.stories.tsx

This adds a new, accessible 'Processing transaction' overlay for payment processing, and navigates the user to the thank-you page on successful checkout completion.
It also fixes a small bug with validation on the Stripe card form.
When people give us money it's nice to say thank you 😄
The old progress component is not properly announced to screen readers, and allows background keyboard events while it's visible.

Add a processing overlay and actually proceed to the thank you page on payment completion

---

support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/helpers/redux/selectors/formValidation/index.ts
support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts
support-frontend/package.json
support-frontend/yarn.lock

This PR
- Adds validation to the payment method selector when the user has not chosen a payment method
- Updates Source dev kitchen to fix a small visual bug with the error state of the other amount field
- Only checks recaptcha validation for Stripe, as we are still using the old direct debit form
[**Trello Card**](https://trello.com/c/n6T98HFX)
This is (hopefully) the last piece of form validation work for the new checkout (at least until we can add a better direct debit form).

Add validation message to payment method selector

---

support-frontend/assets/components/existingMethodPaymentButton/existingCardPaymentButton.tsx
support-frontend/assets/components/existingMethodPaymentButton/existingDirectDebitPaymentButton.tsx
support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelectorAccordionRow.tsx
support-frontend/assets/components/paymentMethodSelector/radioWithImage.tsx
support-frontend/assets/components/paymentMethodSelector/reauthenticateLink.tsx
support-frontend/assets/helpers/forms/existingPaymentMethods/existingPaymentMethods.ts
support-frontend/assets/helpers/redux/commonState/state.ts
support-frontend/assets/pages/contributions-landing/contributionsLandingInit.ts
support-frontend/assets/pages/supporter-plus-landing/paymentButtons.ts
support-frontend/stories/checkouts/paymentMethodSelector.stories.tsx

This PR:
- Fixes an issue where we were showing a permanent loading state for existing payment methods even when not retrieving them
- Simplfies the logic around whether we should show a user's existing payment methods or a sign-in link to reauthenticate if their payment methods are stale
- Fixes visual problems with the display of those payment method options and the reauthenticate link
- Adds payment buttons for the `ExistingCard` and `ExistingDirectDebit` payment methods so users can actually check out with these payment types
This is a virtually undocumented and very poorly understood aspect of the contributions checkout which we had largely neglected in building the new checkout so far. This PR should fix things ready for launch, but a lot of the code this behaviour relies on needs …

Fix issues around existing payment methods in the new checkout

---

support-frontend/assets/helpers/redux/checkout/product/state.ts

This fixes an issue where validating the other amount field could produce duplicate error messages in the summary, when the amount failed both the regex condition and the 'is not `NaN` when parsed as a float' condition.
I've removed the NaN check altogether as it's not actually necessary- the regex will permit _only_ a numeric string with a maximum of one decimal place, which will always successfully parse to a number.

Fix issue with validation on the other amount field

---

support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx

This fixes the styling for the terms and conditions for a single contribution on the Supporter Plus checkout.

Fix Supporter Plus Single Contrib T&Cs styling

---

support-frontend/assets/helpers/forms/checkouts.ts

AmazonPay on (One-Off/USD) hidden on V2 checkout whilst being built.
[**Trello Card**](https://trello.com/c/uMSzlgxN/828-v2-disable-amazonpay-on-supporter-plus-one-off-usd-whilst-being-built)
- [x ] Yes

AmazonPay disabled during construction

---

support-frontend/assets/pages/contributions-landing/newProductTestHelper.ts

`isSupporterPlusPurchase` returns a boolean to indicate when we should set the product type to "supporterPlus", it was previously set-up to only return true when the user was in the old `newProduct` AB test, however now it needs to return `true` if the users in the `variant` of the new `supporterPlus` AB test.
Note: It's been useful to have `newProduct` AB test as it's allowed us to complete supporter plus checkout whilst the new "V2" checkout has been in development, however now we can checkout using the V2 checkout we should be able get rid of the `newProduct` AB test and associated logic. This can be done in a follow-up PR.

use supporterPlus ab test in isSupporterPlusPurchase

---

support-frontend/assets/pages/contributions-landing/contributionsLandingActions.ts
support-frontend/assets/pages/contributions-landing/newProductTestHelper.ts

Users checking out above the threshold whilst in the `supporterPlus` AB test's `variant` will still be allocated as a Recurring Contributor. I thought this change to `isSupporterPlusPurchase` would fix that: https://github.com/guardian/support-frontend/pull/4382, however it didn't. That's because `isSupporterPlusPurchase` is not used at the point we submit the new checkout form and assign the `productOptions` in the `getProductOptionsForSupporterPlusTest` function.
In this PR i've renamed `getProductOptionsForBenefitsTest` to `getProductOptionsForSupporterPlusTest`, and updated it to use `isSupporterPlusPurchase` as they do exactly the same checks.
i've also updated `isSupporterPlusPurchase` to return `false` immediately if the user is not in the `supporterPlus` AB test's `variant` …

Use isSupporterPlusPurchase in new checkout

---

support-frontend/assets/components/paymentButton/directDebitPaymentButton.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodData.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelectorAccordionRow.tsx
support-frontend/assets/helpers/customHooks/useFormValidation.ts

This fixes an issue with the payment processing overlay, which would appear immediately when attempting to pay via direct debit. The overlay would sit above the modal and therefore block the user from completing the form. 
The form validation hook now takes an optional `dispatchPaymentWaiting` argument and to prevent recaptcha being called on component load the `accordionBody` of the payment method selector is now a function.
Co-authored by: @GHaberis @i-hardy

Fix Direct Debit overlay bug

---

support-frontend/assets/components/payPalPaymentButton/payPalRecurringContainer.tsx

This fixes a bug where completing the recurring checkout with PayPal on the new checkout did not trigger the 'payment processing' state before navigating to the thank you page on payment completion.

Fix issue with PayPal checkout not triggering the correct pending state

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala

Supporter plus has the same available payment methods as a contribution so it should be treated as one when evaluating payment method switches. 
Prior to this PR it wasn't - it was being treated as a subscription. However subscriptions do not have a switch for Sepa or Apple pay payment methods so supporter plus purchases were failing with an 'Invalid Payment Method' error.

Treat supporter plus as a contribution when considering payment method switches

---

support-frontend/assets/components/thankYou/appDownload/AppDownloadBadges.tsx

This is a small fix to address an accessibility issue on the thank you pages that was being flagged up in Storybook. The app store logo links now have screen reader accessible text.

Add aria labels to app store logo links on the thank you page

---

support-frontend/assets/helpers/rendering/ssrPages.ts

This disables pre-rendering (aka SSR, although it's not really) of the contributions landing page with the `EmptyContributionsLandingPage` component, ahead of A/B testing the new checkout.
[**Trello Card**](https://trello.com/c/dNBJJElZ)
Showing the pre-rendered version of the old checkout at first and then flashing to the very different new design creates a weird user experience that might unduly influence the A/B test.
After the conclusion of the test we'll need to think about what a pre-rendered version of the new checkout would need to look like before restoring this feature.

Disable pre-render of the contribution landing page

---

support-frontend/assets/components/sepaForm/SepaForm.tsx

This adds legal copy required for the sepa payment method on the supporter plus checkout page.
[**Trello Card**](https://trello.com/c/IINMXe6Y/834-2-sepa-tab)

Add legal copy for Sepa payment method

---

support-frontend/assets/components/paymentFrequencyTabs/paymentFrequenncyTabs.tsx
support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestCompletion.ts
support-frontend/assets/components/paymentRequestButton/paymentRequestButtonContainer.tsx

This fixes:
- An issue where the `PaymentFrequencyTabs` tab panel was receiving manual keyboard focus, when it should only be able to receive focus programmatically
- An issue where opening a payment request interface (ie. Apple or Google Pay) and then closing it without paying left the checkout stuck in the 'processing' state

Fix issue with tab panel focus and issue with loading state after exiting a PRB interface

---

support-frontend/assets/helpers/redux/selectors/formValidation/index.ts
support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/assets/helpers/user/userActions.ts
support-frontend/assets/helpers/user/userReducer.ts
support-frontend/assets/pages/supporter-plus-landing/components/existingRecurringContributorMessage.tsx
support-frontend/assets/pages/supporter-plus-landing/components/nonValidationFailureMessage.tsx
support-frontend/assets/pages/supporter-plus-landing/components/paymentFailure.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx

This fixes an issue where we were not preventing users who already have a recurring contribution from checking out with a new one. This is very much a quick-n-dirty patch as this information is stored in the user reducer which has not yet been migrated to Redux Toolkit and requires a significant refactor.

Prevent users who already have a recurring contribution from taking out another on the new checkout

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

This turns on the `supporterPlus` A/B test to a limited amount of the audience. This will allocate 2% of users into the test, with half each being assigned to the control and variant.
[**Trello Card**](https://trello.com/c/od9m55Bw)

Soft-launch new checkout to 1% of audience

---

support-frontend/assets/helpers/redux/checkout/product/reducer.ts

This fixes a bug where error messages associated with the other amount field were not cleared when switching contribution frequency.

Clear other amount errors when switching product type

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

This will allocate 20% of the whole audience into the test, with half of that ie. 10% seeing the variant

Increase audience size of supporterPlus AB test

---

support-frontend/assets/components/thankYou/feedback/FeedbackItems.tsx
support-frontend/assets/components/thankYou/thankYouModuleData.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSurvey.tsx
support-frontend/stories/checkouts/thankYouModule.stories.tsx

This removes Aus specific logic from the contributions and supporter plus thank you page feedback components. After this PR we will no longer be showing different copy and a different survey link to users in Australia.
[**Trello Card**](https://trello.com/c/DCMhYK5l/850-update-post-purchase-survey-link-for-supporter-plus-thank-you-page-and-remove-aus-specific-logic)
| Before  | After  |
| -- | -- |
| ![localhost_9001_iframe html_args= id=screens-supporter-plus-thank-you-page-australia--recurring-not-signed-in viewMode=story (1)](https://user-images.githubusercontent.com/44685872/200826077-a193b0fc-8643-40fc-a84a-4aa38317f648.png) | ![localhost_9001_iframe html_args= id=screens-supporter-plus-thank-you-page-australia--recurring-not-signed-in …

Remove Aus specific logic from TY page feedback components

---

support-frontend/assets/components/payPalPaymentButton/payPalOneOffContainer.tsx
support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx

This PR makes an update so we now call `sendEventContributionCheckoutConversion` when the new `supporterPlus-variant` TY page loads. This `sendEventContributionCheckoutConversion` function sends a conversion event to QuantumMetric (QM) with the `amount`, `contributionType` and `currencyId`.
I've also had to dispatch an additional `setCheckoutFormHasBeenSubmitted` action when a user clicks the Paypal payment button for one off contributions. This action has a side affect of setting the `contributionAmount` value in Session Storage, which is retrieved from Session Storage on the TY page, before being sent to QM.

supporterPlus-variant: send contribution conversion event to QM

---

support-frontend/assets/helpers/urls/externalLinks.ts
support-frontend/assets/pages/supporter-plus-landing/components/patronsMessage.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/checkouts/Patrons.stories.tsx
support-frontend/stories/screens/SupporterPlusLanding.stories.tsx

This regionalises the patrons messaging on the v2 supporter plus checkout page.
[**Trello Card**](https://trello.com/c/63QqPWSi/849-regionalise-patrons-copy-on-the-s-checkout)
You can view the [patrons messaging story for this build here](https://62e115310aef0868687b2322-cqppmenzxh.chromatic.com/?path=/story/checkouts-patrons-message--default) to see the copy for each region. Please use the controls tab at the bottom of the page on storybook to change the country group.

V2 Checkout - Regionalise Patrons Message

---

support-frontend/assets/pages/supporter-plus-landing/components/patronsMessage.tsx

Use a US specific header "Support another way" above US patrons message.

Use a US specific header above US patrons message

---

support-frontend/assets/components/errorSummary/errorSummary.tsx

This PR adds a custom data attribute to the client-side validation messages on the new checkout, this will allow Quantum Metric to analyse how users confronted with these validation errors behave on the new checkout, by using a selector like `data-qm-validation[href="#email"]`.

Add custom data attribute to client-side validation error message for QM

---

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx

We offer users the opportunity to choose their first publication date on the Guardian Weekly non-gifting checkout, or delivery date on the gifting checkout. The logic to determine which dates to show them is pretty simple, we calculate the next 5 Friday's and list them out.The issue we've had in the past is we've sometimes offered a publication/delivery date over the Christmas week when an issue isn't published. Users have selected this, and we've been unable to fulfil it
In 2022 we won't be publishing an issue on Friday 30th December 2022, so need to make sure that's not included as an option on these checkouts.
[**Trello Card**](https://trello.com/c/XzBzUL2V/369-dont-show-30-12-2022-as-an-available-publication-option-on-the-gw-checkout)

Filter 2022-12-30 option from GW checkout

---

support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/helpers/forms/checkouts.ts

Disabled AmazonPay for variant only (in code), control will display depending on switch in RRCP switches (one-off AmazonPay) afterwards.
https://support.thegulocal.com/us/contribute#ab-supporterPlus=variant
Variant (After - no change)
https://support.thegulocal.com/us/contribute#ab-supporterPlus=control
Control (After - change)
[[**Trello Card**](https://trello.com)](https://trello.com/c/R8pjseOj/869-amazonpay-disabled-for-variant-enabled-for-control-one-off-usd)
- [x ] Yes

AmazonPay disabled for variant,  enabled for control

---

support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestEvent.ts
support-frontend/assets/components/paymentRequestButton/paymentRequestButtonContainer.tsx
support-frontend/assets/helpers/customHooks/useFormValidation.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/actions.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/reducer.ts
support-frontend/assets/helpers/redux/checkout/product/actions.ts
support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
support-frontend/assets/helpers/redux/checkout/product/reducer.ts

This tackles a couple of bugs related to validation and the payment request button.
We originally dispatched `validateForm` when clicking the PRB like we do for every other payment button, as we need to verify that the user hasn't entered an invalid custom amount. However this had the undesirable side effect of causing validation messages to show up beside personal details fields that the user doesn't actually need to fill out if they're paying with Apple/Google Pay (although it would not block them from making a payment and submitting the form). This changes the validation behaviour for the PRB so it _only_ validates the other amount field.
There was also an edge case where if the user opened the PRB interface but changed their mind, exited it, and tried to complete the form with another …

Fix some issues with form validation and the payment request button

---

support-frontend/assets/pages/supporter-plus-landing/components/nonValidationFailureMessage.tsx

This adds a data-attribute selector to the non-validation error which appears beneath the submit button when a user submits the form and encounter some kind of server side error. This will allow Quantum Metric to monitor user behaviours in the event this error occurs.

Add selector to non validation error for Quantum Metric

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/calculator/AnnualisedValueTwoCalculator.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
support-modules/acquisition-events/src/test/scala/com/gu/support/acquisitions/calculator/AnnualisedValueTwoCalculatorSpec.scala

Adding support for Supporter Plus to the acquisitions-firehose-transformer lambda.
[**Trello Card**](https://trello.com/c/hOVJ6jSz/926-ticker-include-supporter)
We want to include Supporter Plus in the ticker and RRCP super mode, which both rely on the acquisitions-firehose-lambda.

Add supporter plus support to acquisitions-firehose-transformer

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

Temporary solution to show Black Friday offer (strapline and prices) in the Guardian Weekly section of subs landing page between 21/11/2022 and 28/11/2022.  The subs landing page does automatically pull this info in for Monthly offers but doesn't do this for Annual, the fastest solution was to hardcode the info in for the time being, given the imminent start of the offer period!
To be merged on 21/11/2022

Temporarily hardcoded GW Black Friday offer

---

stripe-patrons-data/build.sbt
stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/PatronCancelledEventLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/model/StripeSubscriptionsResponse.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/services/PatronsStripeService.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/services/StripeSubscriptionsProcessor.scala

Some patrons subscriptions have a joint account holder. Currently these are only recorded in Salesforce however we want to ensure they receive their digital benefits when they sign into the apps or website.
This PR adds a mechanism for adding joint patrons to the SupporterProductData Dynamo db table so that they receive benefits. That mechanism is as follows:
- add two metadata fields `joint_patron_email` (mandatory) and `joint_patron_name` (optional) to the metadata of the existing patron customer record
- this metadata is picked up by the stripe-patrons-data lambda and the identity account for the email is either retrieved from identity or a new account created
- a patron record is created in SupporterProductData for this identity id 
[There are more details in this …

Support for joint patrons

---

support-frontend/assets/components/personalDetails/stateSelect.tsx

This adds a localised placeholder message to the state select component on the new checkout.
[**Trello Card**](https://trello.com/c/SZVSFZhC)

Add localised placeholders to the state select field for the supporter plus checkout

---

support-frontend/assets/components/payPalPaymentButton/payPalButtonProps.ts
support-frontend/assets/components/payPalPaymentButton/payPalRecurringContainer.tsx
support-frontend/assets/helpers/redux/checkout/payment/payPal/thunks.ts
support-frontend/window.d.ts

This fixes an issue on the new checkout where if form validation issues are introduced _after_ selecting to pay with PayPal it's possible to proceed with payment.
This **does** cause other issues due to our use of a deprecated PayPal SDK- please see [the write-up here](https://docs.google.com/document/d/1q8G1ZuelCyIm8GT7d-GT-b3d0NL3LpfpfKvDC7N3p4E/edit#heading=h.bminhblhkoif)
[**Trello Card**](https://trello.com/c/e1X68Isz)

Re-run form validation when attempting to open the PayPal pop-up

---

.sdkmanrc
supporter-product-data/cloudformation/cfn.yaml
supporter-product-data/src/main/scala/com/gu/lambdas/FetchResultsLambda.scala
supporter-product-data/src/main/scala/com/gu/services/S3Service.scala
supporter-product-data/src/main/scala/com/gu/services/ZuoraQuerierService.scala

Recently executions of the supporter-product-data-DEV (for example [this one](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:865473395570:execution:supporter-product-data-DEV:15e359bc-8cef-46f3-782d-a37e9fb768a3)) step function have started failing with the error `The request signature we calculated does not match the signature you provided. Check your key and signing method.`
It turns out that this was actually because we were passing the wrong content length for the Zuora CSV results file we were trying to transfer to S3 and that the reason that the content length was wrong was because Zuora had stopped returning the `Content-length` header on the file response. 
As this was only happening in the sandbox environment …

Fix error in supporter-product-data caused by compression of a zuora http response

---

support-frontend/app/admin/settings/Switches.scala
support-frontend/assets/components/headers/header/header.tsx
support-frontend/assets/components/headers/header/headerWithCountrySwitcher.tsx
support-frontend/assets/components/headers/links/links.tsx
support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/forms/checkouts.ts
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionSubmit.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.tsx
support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouHeader.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.test.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/orderSummary/orderSummary.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
support-frontend/assets/pages/subscriptions-landing/components/subscriptionsLandingContent.tsx
support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx
support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
support-frontend/test/admin/settings/SwitchesSpec.scala
support-frontend/test/controllers/SubscriptionsTest.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala

This removes all aspects of the old `newProduct` AB test from the contributions checkout, and moves the aspect of that test that hid links to the digi sub landing page to be behind a new feature switch instead.
The switch has been added to the switchboard in all environments, so can be tested with this branch in CODE.
[**Trello Card**](https://trello.com/c/IsN6u3MO)
We're no longer running any testing for offering benefits on the old contributions checkout, but need to retain the ability to easily hide links to the digital subscription pages.

Remove newProduct AB test and add switch for suppressing digi sub pages

---

build.sbt
support-lambdas/it-test-runner/build.sbt
support-payment-api/src/test/scala/conf/ConfigLoaderProvider.scala
support-workers/build.sbt
supporter-product-data/src/test/scala/com/gu/services/S3ServiceSpec.scala

Upgrading Scala to 2.13.10.This  fixes security vulnerability
[**Trello Card**](https://trello.com/c/x3O4ppp3/727-scala-213x-critical-vulnerability)
Flagged by DevX Security a critical-severity vulnerability was discovered in Scala versions 2.13.x, and fixed in Scala 2.13.10.

Scala upgrade to 2.13.10

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

Reverts guardian/support-frontend#4454 as this Black Friday campaign has now come to an end.

Revert "Temporarily hardcoded GW Black Friday offer"

---

support-frontend/app/services/pricing/DefaultPromotionService.scala

This is part of the work to create a new default promotions tools page in RRCP (https://github.com/guardian/support-admin-console/pull/409). We need to update support-frontend to use the new default-promos.json file stored in the support-admin-console bucket. 
[**Trello Card**](https://trello.com/c/HPAIvddZ/954-use-new-defaultpromotions-file)

Use the new default-promos file

---

support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx

We need to hide some invalid delivery dates that we're currently offering from the paper checkout on support site...
Before....
After...

Filter invalid delivery dates from paper checkout

---

support-frontend/assets/components/amazonPayForm/amazonPayForm.tsx
support-frontend/assets/components/amazonPayForm/amazonPayFormContainer.tsx
support-frontend/assets/components/amazonPayForm/amazonPaymentButton.tsx
support-frontend/assets/helpers/redux/checkout/payment/amazonPay/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/amazonPay/state.ts
support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts

AmazonPayButton - integration with the new validation system (USD, Single Contribution, AmazonPay)
An example of the generic multi-use form validation for SupporterPlus as described here->
https://github.com/guardian/support-frontend/wiki/Form-validation
Errors include Email missing+Proceed not pressed->
https://trello.com/c/SH6Fl37v/895-amazonpaybutton-integration-with-the-new-validation-system
To Preview ->
[https://support.thegulocal.com/us/contribute#ab-supporterPlus=variant](https://support.thegulocal.com/uk/contribute#ab-supporterPlus=variant)

Pd contribs amazonpay validation

---

support-frontend/app/actions/CustomActionBuilders.scala
support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/models/identity/responses/IdentityErrorResponse.scala
support-frontend/assets/helpers/forms/errorReasons.ts

PR to handle bad email error from Identity
[**Trello Card**](https://trello.com/c/dmVAQEHA/873-handle-bad-email-error-from-identity)
We have the issue of "bad" email addresses being submitted on our checkouts /create endpoint.We frequently get alarms triggered by users unsuccessfully attempting to checkout on our recurring contributions / subscriptions checkouts. A lot of these alarms are down to users entering email addresses which Identity considers valid but Okta doesn't: [test@gmail.com](mailto:test@gmail.com)123.This issue occurs when we're posting to the endpoint https://idapi.code.dev-theguardian.com/guest when creating a guest identity account as part of the checkout process.
The issue we've had is in the past we've received a generic 500 from Identity which triggers a generic 500 …

Handle bad email errors from Identity

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

Hardcode Christmas gifting offer on [Support the Guardian | Get a Subscription](https://support.theguardian.com/uk/subscribe), to run 1st Dec - 23rd Dec
Strapline
50% off annual gifting subscription
Prices
GBPCountries: 82.5,
UnitedStates: 165,
AUDCountries: 216,
EURCountries: 141,
NZDCountries: 273,
Canada: 180,
International: 180
Copy
Give someone answers and insights that go beyond the headlines,
and into the issues that matter most. They can enjoy handpicked
articles from the Guardian and Observer, curated into one magazine
and delivered for free, wherever they are in the world. Plus, for a
limited time, gift a whole year’s subscription, for half the usual price.
Swap buttons
Primary: See gift options
Secondary: See personal subscriptions
[**Trello …

Temporarily hardcoded GW Gifting Christmas Promo

---

support-lambdas/it-test-runner/cfn.yaml

The [it-test-runner](https://github.com/guardian/support-frontend/wiki/Automated-IT-Tests) is failing because of a recent java upgrade of support-workers. This lambda shares a build with support-workers despite being in a different part of the mono repo

Update it-test java version

---

support-frontend/assets/components/datePicker/datePicker.tsx
support-frontend/assets/components/datePicker/helpers.ts

Fix - Digi Sub gifting client-side datepicker validation
Bug 1
The Digi Subs Gifting checkout allows the gifter to select a date in the future on which the giftee will receive the gift via email. However the form's client side validation is not blocking invalid dates and dates in the past from being submitted. eg. I can submit the form with 01/01/2022 as my chosen gift date, or 01/01/202.
If a date in the past is accidentally submitted the email will be sent immediately - Retention have received a bug report from the contact centre about such an incident.
Bug 2
There's also another bug on the form related to the date picker. If I click the "Check date" button we see a message "Your gift will be delivered on NaN undefined Nan"
Bug 3 
Calendar should not allow dates to be selected before …

Fix - Digi Sub gifting client-side datepicker validation

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/productPrice/billingPeriods.ts
support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

This removes the `sixForSixSuppression` A/B test and makes excluding the six for six offer the default on Guardian Weekly pages.
[**Trello Card**](https://trello.com/c/QoztCe0Z)
The test was obsolete as 100% of users were in the variant.

Remove sixForSixSuppression A/B test

---

support-workers/cloud-formation/src/templates/cfn-template.yaml

Co-authored by : **Emily Bourke**
PR to update New Alarm: No successful recurring [PAYMENT METHOD] SupporterPlus contributions for two hours as the Continuous Deployment  through Riff-Raff failed  to update the alarms.
[**Trello Card**](https://trello.com/c/bXhgCQUs/907-new-alarm-no-successful-recurring-payment-method-supporterplus-contributions-for-two-hours)
Continuous Deployment  through Riff-Raff failed  to update the alarms due  to duplicate alarm names and unnecessary setting of Statistic  field.

Updated alarms for SupporterPlus post CD failure in Riff-Raff

---

project/LibraryVersions.scala
support-frontend/build.sbt
support-lambdas/acquisitions-firehose-transformer/build.sbt

However, don’t update circe-optics, the newest version of which is still 0.14.1
Question for PR reviewers: is it ok for these versions to be different? The [release notes for circe v0.14.1](https://github.com/circe/circe/releases/tag/v0.14.1) suggest to me that it is ok, plus that there are no 0.14.2 and 0.14.3 releases for circe-optics.
This is a manual update, as the automated update failed.

Update circe to 0.14.3

---

.github/workflows/chromatic.yml

This amends the config for our Chromatic workflow to exclude PRs raised by scala-steward. It's impossible for these PRs to affect our stories so it's a waste of money to create Chromatic builds for them.

Amend Chromatic workflow to exclude scala steward PRs

---

support-frontend/assets/components/existingMethodPaymentButton/existingCardPaymentButton.tsx
support-frontend/assets/components/existingMethodPaymentButton/existingDirectDebitPaymentButton.tsx
support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelectorAccordionRow.tsx
support-frontend/assets/components/svgs/amazonPayLogoDs.tsx
support-frontend/assets/components/svgs/directDebitSymbol.tsx
support-frontend/assets/components/svgs/directDebitSymbolDs.tsx
support-frontend/assets/components/svgs/downChevronDs.tsx
support-frontend/assets/components/svgs/newCreditCardDs.tsx
support-frontend/assets/components/svgs/paypalDs.tsx
support-frontend/assets/components/svgs/sepa.tsx
support-frontend/assets/helpers/__tests__/checkoutsTest.ts
support-frontend/assets/helpers/forms/checkouts.ts
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/actions.ts
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/state.ts
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/thunks.ts
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/utils.ts
support-frontend/assets/helpers/redux/checkout/payment/reducer.ts
support-frontend/assets/helpers/redux/commonState/actions.ts
support-frontend/assets/helpers/redux/commonState/reducer.ts
support-frontend/assets/helpers/types/asyncStatus.ts
support-frontend/assets/pages/contributions-landing/components/ContributionForm.tsx
support-frontend/assets/pages/contributions-landing/contributionsLandingInit.ts
support-frontend/stories/checkouts/paymentMethodSelector.stories.tsx

This adds an RTK slice for existing payment methods- card or direct debit payment methods that a user has already used to pay for another Guardian product, which we may offer them the option to re-use when they land on the support site from MMA. The conditional logic around when and how to fetch this data has been refactored into a thunk for better encapsulation. The supporter plus checkout code now uses this new slice.
I've also:
- Refactored the `PaymentMethodSelector` component to remove its explicit dependency on Redux and use the same component for regular and existing payment methods
- Fixed an accessibility issue with our payment SVG icons that was being flagged up in Storybook
- Added an existing payment to the `PaymentMethodSelector` stories, and a story for the component in an …

Set up reducer for existing payment methods

---

support-frontend/assets/components/headers/links/links.tsx

This removes Patrons from Support pages in Australia / NZ
[**Trello Card**](https://trello.com/c/bcA6f2iB/931-remove-patrons-from-support-pages-aus-navigation)
Patrons is not a marketable product is Australia / NZ
| Aus | NZ |
| --- | ---- |
| <img width="1317" alt="Screenshot 2022-12-16 at 11 56 09" src="https://user-images.githubusercontent.com/44685872/208094160-2ee115a2-7603-4dba-8ec4-ed152da9af7f.png"> | <img width="1317" alt="Screenshot 2022-12-16 at 12 04 16" src="https://user-images.githubusercontent.com/44685872/208094328-8b029e27-7029-4ad0-a89a-36dd447b9abd.png"> |

Remove Patrons from Aus / NZ support pages

---

support-frontend/app/controllers/Application.scala

This changes the page title on the supporter plus checkout page from "Support the Guardian | Make a Contribution" to just "Support the Guardian".
[**Trello Card**](https://trello.com/c/uOXFgnMa)
This is a part of the work to make the new supporter plus checkout the default, in place of the old contributions checkout.

Change the page title on the supporter plus checkout

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.ts

Increase the memory allocation of two lambdas in the stripe-patrons-data project.
These lambdas are called by Stripe webhooks and occasionally the webhook times out so the call appears to have failed in Stripe. These usually succeed on retry but increasing the memory allocation of the lambda should speed the execution up and allow it to complete more reliably.

Increase the memory allocation of two lambdas

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

This PR reverts the changes made here which temporarily hardcoded a Guardian Weekly gifting offer for promotion: https://github.com/guardian/support-frontend/pull/4495

Remove temporary GW gift offer from subs page

---

support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala

Changes the test credit card expiry to 2041, for consistency with the one in Stripe.
Changes the `PreparePaymentMethodForReuseSpec` expiry back to 2022, because we can't change the expiry date in zuora. It's only testing cloning of a payment method so the expiry doesn't matter.

Update card expiry in IT tests (again)

---

support-payment-api/build.sbt

Update Scala dependency kind-projector_2.13.4 manually as it failed checks when updating from 0.11.3 to 0.13.2
[**Trello Card**](https://trello.com/c/oX9HK0tX/502-support-frontend-update-kind-projector-dependency)

Update kind-projector_2.13.4 to 0.13.2

---

stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/PatronCancelledEventLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/model/Errors.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/SupporterDataDynamoServiceSpec.scala
support-modules/supporter-product-data-dynamo/src/main/scala/com/gu/supporterdata/services/SupporterDataDynamoService.scala

We have been getting a number of alarms caused by incomplete data for Patrons subscriptions in the SupporterProductData dynamo table. Upon investigation it appears that what is happening is the following:
- All subscriptions have a [TTL (time to live)](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html) setting in Dynamo which is set to the term end date of the subscription. This means that when this date is reached the record will automatically be deleted from the data store.
- There is also a Stripe webhook which triggers when a subscription is cancelled to enable us to mark these subs as cancelled by adding a cancellation date to the record - this is mostly to take care of accounts which are cancelled mid-term
- It appears that in some (all?) cases the webhook …

Fix problem with Patron cancellations

---

.github/workflows/bundle-analyser.yml
.github/workflows/chromatic.yml
.github/workflows/compressed-size.yml
.github/workflows/payment-api-build.yml
.github/workflows/stripe-patrons-data.yml
.github/workflows/support-frontend-build.yml
.github/workflows/support-lambdas-build.yml
.github/workflows/support-workers-build.yml
support-frontend/assets/components/animations/giftHeadingAnimation.tsx

Our bundle analyser github action was being skipped for some time due to a conditional check in the yaml file. This conditional had been introduced to prevent certain actions running on a fork. Although, in the bundle analyser check the value we were attempting to access i.e. `github.event.pull_request.head.repo.owner.login` was undefined. This uses an alternative github context value `github.repository_owner` for the repo owner conditional checks in our github actions.
[**Trello Card**](https://trello.com/c/cEiFq7u9/964-support-frontend-fix-bundle-analyser-action)

Fix bundle analyser gh action

---

support-frontend/app/controllers/GetAddress.scala

For certain very long input values, getAddress.io’s postcode lookup returns a 404 instead of the expected error. To guard against this, this change avoids calling the API for values too long to be a valid postcode.
I believe the longest valid postcodes are 8 characters; this check checks for inputs longer than 10 characters in case I’m mistaken or in case that changes.
This issue came up from an alarm investigation.

Don’t do postcode lookup for long inputs

---

support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx

There's a bug on [supporterPlusThankYou.tsx](https://github.com/guardian/support-frontend/blob/00468e02176ea94faed4a3982c2a585befcf8527/support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx) for One Off Paypal contributions, it's passing the wrong `amount` to Quantum Metric via the `sendEventContributionCheckoutConversion` function.
It should be pulling the `contributionAmount` from session storage if `isOneOffPayPal` is true, but we're not making the check so it looks like it's pulling the `amount` from Redux, which is set to the default and therefore it's reporting the wrong amount to Quantum Metric.
This PR gets the`contributionAmount` from session storage if `isOneOffPayPal` is true and assigns that to the `amount` variable on the `supporterPlusThankYou.tsx` …

Quantum Metric: Get contribution amount from session storage for one off paypal contributions

---

.github/workflows/bundle-analyser.yml
.github/workflows/chromatic.yml
.github/workflows/compressed-size.yml
.github/workflows/dependabot.yml
.github/workflows/payment-api-build.yml
.github/workflows/stripe-patrons-data.yml
.github/workflows/support-frontend-build.yml
.github/workflows/support-frontend-eslint.yml
.github/workflows/support-frontend-typescript.yml
.github/workflows/support-lambdas-build.yml
.github/workflows/support-workers-build.yml

We're seeing Github Actions fail with a warning related to dependent actions they use: `actions/setup-node@v2` and `actions/setup-node@v2`. Both these actions used Node 12 which is now deprecated (see screenshot below). Updates to https://github.com/actions/checkout and https://github.com/actions/setup-node to there latest `v3` versions should resolve this.

Update github actions to use Node 16

---

support-frontend/assets/components/containers/centredContainer.tsx
support-frontend/assets/components/product/giftNonGiftCta.tsx
support-frontend/assets/helpers/urls/routes.ts
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

1) Add new ''Student subscriptions'' element to GW landing page (See design)
2) Link out to Student Beans portal (url below)
Where to link from GW landing page: https://connect.studentbeans.com/v4/hosted/the-guardian-weekly/uk
After student status verification via this portal, users will be directed to GW offer landing page to subscribe.
[**Trello Card**](https://trello.com/c/31VRnK2G/975-dev-enable-student-beans-link-in-gw-landing-page)
Print Publishing have engaged Student Beans, a student promotion platform, to test whether a student proposition for GW will be effective. They have asked for a new ' Student subscriptions'' element to be added next to '' Gift subscriptions'' and to link out to the Student Beans site, where students can verify their student status and claim for their …

Student beans link

---

support-frontend/assets/components/containers/centredContainer.tsx
support-frontend/assets/components/product/giftNonGiftCta.tsx
support-frontend/assets/helpers/urls/routes.ts
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

Enable Student Beans link in GW landing page (UK-only)
1) Add new ''Student subscriptions'' element to GW landing page (See design)
2) Link out to Student Beans portal (url below)
[**Trello Card**](https://trello.com/c/31VRnK2G/975-dev-enable-student-beans-link-in-gw-landing-page)

Enable Student Beans link in GW landing page, layout correction

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.ts
supporter-product-data/cloudformation/cfn.yaml

Costs for running  the supporter product data update step function have increased out AWS  bill noticeably and are the single largest step function cost by a long way.
While it is important that the SupporterProductData dynamo table (which is used by members-data-api to work out which products a user has) is kept up to date, it is already updated separately by support-workers when a purchase is made via the support site so it is only for purchases made via CSRs that we are wholly reliant on this step function. Since these are much lower volume and due to their nature (via a phone call) are probably less time sensitive I think it is reasonable to decrease the frequency of the execution of this step function. I have also decreased the frequency in the DEV and UAT environments to once a day. …

Change lambda scheduling

---

supporter-product-data/cloudformation/cfn.yaml

Based on [the docs](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents-expressions.html), I believe either day-of-week or day-of-month should be a question mark. I think builds are currently failing in UAT.

Fix supporter-product-data schedule cron

---

support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
support-frontend/test/selenium/subscriptions/ProductPagesSpec.scala

Remove Digital Pack post deployment tests  from CheckoutsSpec and ProductPagesSpec files as we are deprecating  Digital Subscriptions.
[**Trello Card**](https://trello.com/c/lKwIz0Cy/695-switch-off-digital-pack-post-deployment-tests-before-adding-redirects-to-https-supporttheguardiancom-uk-subscribe-digital-routes)
Switch off Digital Pack post deployment tests before adding redirects to https://support.theguardian.com/uk/subscribe/digital/* routes

Switch off Digital Pack post deployment tests

---

.scala-steward.conf

Not sure if this will fully resolve the problems with Scala Steward not respecting the `pullRequests.grouping` setting, but from testing on another repo (https://github.com/guardian/play-secret-rotation), I did find that the full group name must be specified (so `software.amazon.awssdk`, not `software.amazon`, changed with https://github.com/guardian/play-secret-rotation/commit/c1cbc2a8a2096a96c5b9f79f607d2436118102cd).
* https://github.com/guardian/play-secret-rotation/pull/381 - ❌ incorrectly grouped & named "Non AWS", Scala Steward conf was `"group" = "software.amazon"`
* https://github.com/guardian/play-secret-rotation/pull/382 - ✅ correctly grouped & named "AWS", Scala Steward conf was `"group" = "software.amazon.awssdk"`
See also the discussion in …

Scala Steward PR grouping: use full group name

---

supporter-product-data/cloudformation/cfn.yaml
supporter-product-data/src/main/scala/com/gu/lambdas/AddSupporterRatePlanItemToQueueLambda.scala
supporter-product-data/src/main/scala/com/gu/services/SelectActiveRatePlansQuery.scala
supporter-product-data/src/test/scala/com/gu/lambdas/AddSupporterRatePlanItemToQueueIntegrationTest.scala

We recently noticed some issues with the [supporter-product-data-UAT](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/statemachines/view/arn:aws:states:eu-west-1:865473395570:stateMachine:supporter-product-data-UAT) step function which meant it had been failing repeatedly for many months. This PR makes some changes to try to prevent this happening again.
The supporter product data step function extracts data from Zuora on a scheduled basis using a stateful Aqua query: https://knowledgecenter.zuora.com/Zuora_Central_Platform/API/AB_Aggregate_Query_API/BA_Stateless_and_Stateful_Modes
This means that it has two modes of running - Full or Incremental specified by the value that is passed into it eg
{
  "queryType": "incremental"
}
when a full extract is required the …

Supporter Product Data Step function Fixes

---

build.sbt
support-internationalisation/build.sbt
support-internationalisation/src/test/scala/com/gu/i18n/CountryGroupTest.scala
support-internationalisation/version.sbt

This PR updates support-i18n to release for scala 2.13 and 3.1., and releases v0.14+0.15
It didn't even build with scala 2.11, and it had previously been released for scala 2.13 (for support-service-lambdas)
We now use scala 3 for new product-move-api, and even though scala 3 can use scala 2.13 libraries, it does make sense to release scala 3 libs where possible if we're ever going to use scala 3.
I have done a release to confirm my changes work, so this PR is to review what's already been done! Release is visisble here https://mvnrepository.com/artifact/com.gu/support-internationalisation_3/0.15
(Supersedes https://github.com/guardian/support-frontend/pull/4125 )
This PR does mean that it's the first thing in this mono repo to really use scala 3, but there's no reason why more things …

upgrade support-internationalisation to scala 3

---

support-frontend/assets/helpers/contributions.ts

This PR sets the MIN value users are allowed to submit in the "Other amount" field on the monthly tab at https://support.theguardian.com/contribute to `2` in all regions. 
We've seen when AB testing choice card amounts that the MIN value in the code is sometimes greater than the lowest value choice card, so isn't really the MIN, this leads to confusing UX, as shown below:
The current MIN values also contradict some support messaging on www.theguardian.com that states "you can give from as little as £/$2 a month".
It's been agreed that the smallest monthly choice card in an amounts AB test will not be less than 2.

update monthly MIN value for other amount field

---

support-frontend/assets/helpers/productPrice/productPrices.test.ts
support-frontend/assets/helpers/productPrice/productPrices.ts
support-frontend/assets/pages/paper-subscription-landing/components/paperPrices.tsx

Currently in the newspaper product page the price cards only show the normal online vs retail discount, even if a promo is applied.
We only have the `savingVsRetail`, so the logic is a bit fiddly.

Show discount vs retail for newspaper

---

support-workers/cloud-formation/src/templates/cfn-template.yaml
support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala

I noticed an issue with the UpdateSupporterProductData lambda which updates the Dynamo cache when a user purchases a product. When we were working out what type of record to insert, we returned an Option to represent the fact that for Digital Subscription gift purchases we don't insert a record (because gift purchases don't receive the benefits, the giftee does). However the code was actually returning `None` for any unknown product not just DS gifts and because the function wasn't updated when Supporter Plus was released we were returning `None` for all S+ purchases and not writing a record to the data store.
The impact of this would be that purchasers of Supporter Plus would not have been recognised by members-data-api until up to 5 minutes after their purchase. In some cases if a user …

Fix UpdateSupporterProductData lambda

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala

Validate PostCode  length on server side for Guardian Weekly and Paper 
[**Trello Card**](https://trello.com/c/hgXWkPCo/663-validate-length-on-postcode-field)
Salesforce cannot accept postcodes greater than 20 characters in length, but we currently do not validate the length of this field on the server side. The client side validation for postCode field is in place.
We use Salesforce for all Subscriptions (Newspaper, Guardian Weekly) and Recurring Contributions, so any checkout for these products which has a postcode field should adopt this rule. As we're removing Digital Subs making the change this checkout is not a priority.
- [x ] No

Validate postCode length on server side

---

support-frontend/assets/helpers/redux/checkout/address/reducer.ts

Guardian Weekly checkout: Clear "State" property in Redux on Country Change
[**Trello Card**](https://trello.com/c/DKx4hYQG/751-guardian-weekly-checkout-clear-state-property-in-redux-on-country-change)
We've seen errors when users try to create Guardian Weekly subscriptions, sent back from Zuora such as "FL not a valid ISO state in CA".
Upon inspection we found it's possible for a user to select state in the checkout for one country then change country, without the state altering in Redux state - resulting in a possible bad submission

Clear State property in Redux on Country Change

---

support-frontend/app/config/StringsConfig.scala
support-frontend/app/controllers/Application.scala
support-frontend/app/controllers/SiteMap.scala
support-frontend/conf/routes
support-frontend/conf/strings.conf

Removing the server-side code responsible for the current showcase page.
Trello card: https://trello.com/c/KHY6bcbI/938-remove-server-side-code-for-showcase-landing-page-from-codebase
The redirects in Fastly can’t be removed till this change is live, if I understand correctly.
We no longer want this page, as part of removing digisubs and moving to supporter-plus.

Remove showcase page (server side)

---

support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx

This temporarily disables the supporter plus thank you page survey by removing the feedback/survey module from the page.
[**Trello Card**](https://trello.com/c/qpQY1RkC/1010-switch-off-the-supporter-plus-post-purchase-motivations-survey)
Please see [Storybook UI test diffs here](https://www.chromatic.com/build?appId=62e115310aef0868687b2322&number=1603).

Temporarily disable Supporter Plus thank you page survey

---

supporter-product-data/src/main/scala/com/gu/lambdas/AddSupporterRatePlanItemToQueueLambda.scala

this is causing build failures:
`[error] (Compile / scalafmtCheck) scalafmt: 1 files must be formatted (/opt/teamcity/buildAgent/work/2c6b1421bde49969/supporter-product-data)`

scala format supporter-product-data

---

.github/workflows/supporter-product-data.yml
supporter-product-data/build-tc

Use Github actions rather than TeamCity to build the supporter-product-data project. This gives us better visibility of failures as the current TC project doesn't report status back to GH.

Build supporter-product-data with github actions

---

build.sbt
support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
support-payment-api/src/main/scala/backend/BackendError.scala
support-payment-api/src/main/scala/backend/PaymentBackend.scala
support-payment-api/src/main/scala/backend/PaypalBackend.scala
support-payment-api/src/main/scala/backend/StripeBackend.scala
support-payment-api/src/main/scala/services/SupporterProductDataService.scala
support-payment-api/src/test/scala/backend/AmazonPayBackendSpec.scala
support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
support-payment-api/src/test/scala/backend/StripeBackendSpec.scala

This  PR adds code to the payment-api to write single contributions into the Supporter Product Data Dynamo store.
Doing this will allow mean that  we don't need to query the contributions data store from members-data-api whenever we get a request to retrieve a users single contributions - we can get both single contributions and subscriptions from the same store.  
This will be both more performant and reduce the load on the postgres database  as well as simplifying the code base.

Add single contributions into the supporter product data Dynamo store

---

.github/workflows/support-frontend-build.yml

Remove large runner from support-frontend-build workflow 
[**Trello Card**](https://trello.com/c/nrDQctko/716-test-using-larger-runners-to-speed-up-support-frontend-build)

Remove large runner from support-frontend-build

---

support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.module.scss
support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.scss
support-frontend/assets/components/dialog/dialog.scss
support-frontend/assets/components/menu/menu.module.scss

Supporter Plus checkout: Fix layout bug with the country dropdown
[**Trello Card**](https://trello.com/c/CeJ4lNs4/932-supporter-plus-checkout-fix-layout-bug-with-the-country-dropdown)
Dropdown of country picker doesn't align properly when it's open.
Also, a small tweaks needs to be done on the 320 breakpoint to align the chevron with the link.
Before Change
After Change

 Fix for Supporter Plus checkout country dropdown layout bug

---

support-frontend/assets/components/existingMethodPaymentButton/existingCardPaymentButton.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx

We enabled existing card payment methods, which worked in testing but then ran into errors in production. This PR is to fix the errors that have cropped up.
~~Specifically, the errors we’ve had have the following form: `Failed to create new Annual-SupporterPlus-USD-120, due to RequestValidationError(validation of the request body failed with existing billing account id missing...`. From looking at the [failed step function](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-PROD:a6266d8b-83c4-4fa2-919e-ee30ef8ae5dc) that produced that error, and examining [the code the error came from](https://github.com/guardian/support-frontend/blob/6dd1b1268557cec9cb94919fd15e80779e3a1c53/support-fr …

Try to fix existing payment methods

---

support-frontend/app/controllers/Application.scala
support-frontend/app/controllers/CanonicalLinks.scala

When running locally, we now redirect to `/support` in a couple of places, while our site is actually at `/contribute`. This PR updates those places to redirect straight to `/contribute`. Since we’re redirecting with Fastly anyway (in code and prod), this isn’t essential, but it’s a small change and makes things more consistent.

Use /contribute over /support in geoRedirect

---

support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.module.scss
support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.scss
support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.tsx
support-frontend/assets/components/menu/menu.module.scss

Supporter Plus checkout: Fix layout bug with the country dropdown
[**Trello Card**](https://trello.com/c/CeJ4lNs4/932-supporter-plus-checkout-fix-layout-bug-with-the-country-dropdown)
Dropdown of country picker doesn't align properly when it's open.
Also, a small tweaks needs to be done on the 320 breakpoint to align the chevron with the link.
Before Change
After Change

Country drop down supporter plus fix

---

support-frontend/assets/components/headers/header/header.scss
support-frontend/assets/components/headers/header/header.tsx

This PR fixes some inconsistencies in the way the nav was appearing across regions on the GW landing page, we had some logic in the JS that would decide whether to show the veggie-burger or non-veggie-burger menu. In all regions other than the UK this logic was concluding to show the non-veggie-burger menu on mobile devices (a side effect of removing some links when deprecating Digi Subs). 
The issue is the non-veggie-burger doesn't look great on Mobile and shifts the contents of the page down, as shown below:
**Ideally we'd be consistent and show the veggie-burger menu in ALL regions at the mobile breakpoint.**
I've therefore replaced this JavaScript logic that calculates whether to add the CSS class name modifiers to the `.component-header` element, with something more simple. 
Before …

Use CSS media queries to show/hide mobile menu on Support site Landing pages

---

support-frontend/assets/components/checkoutNudge/checkoutNudge.tsx
support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts

Nudging component, encouraging single to monthly or annual recurring contributions
Rename test  to 'ab-singleToRecurringV2'
[**Trello Card**](https://trello.com/c/4bRuTMkx/1028-nudging-recurring-to-annual-build)
Features->
- copy change,
- differing minimum contributions,
- differing link (copy and location)
2-cohort A/B test for implementation ->
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV2=control (Monthly)
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV2=variant (Annual)

Supporter plus nudge annual

---

support-frontend/stories/images/GridImage.stories.tsx
support-frontend/stories/images/GridPicture.stories.tsx

Documenting the GridImage and GridPicture controls.
This has been done in Storybook (alongside Wiki update).
[AFTER]
GridImage controls ->
GridImage docs ->
GridPicture controls ->
GridPicture docs ->
[**Trello Card**](https://trello.com/c/e4Jy9UDh/720-supportfrontend-wiki-add-helpercomponent-section-document-gridimage-gridpicture)
To provide GridPicture & GridImage documentation

GridImage GridPicture Storybook controls / docs updated

---

support-frontend/.husky/pre-commit
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala

Because they tax digital news products so it is useful to have some being created in Zuora on a regular basis.
I've also added a git pre-commit hook to run `scalafmtCheckAll` if the commit contains Scala files, to avoid the annoying situation where you push files and they then fail the build with a formatting error.

Add a new integration test to create a supporter plus sub in Austria

---

support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx

This restores setting the `gu.contributions.contrib-timestamp` cookie via the thank you page for users who have made a one-off contribution.
While clearing up orphaned code in #4741 I noticed that the `contributionsCookies.ts` module was no longer being imported anywhere; however this code serves an important purpose in setting a cookie enabling us to identify recent one-off contributors. This cookie is regarded as essential so there are no consent issues around setting it again.

Restore setting a cookie when a user makes a one-off contribution

---

support-frontend/assets/components/paymentMethodSelector/creditDebitIcons.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodData.tsx
support-frontend/assets/components/stripeCardForm/elementDecorator.tsx

This adds branded payment icons on mobile breakpoints. 
[**Trello Card**](https://trello.com/c/ceVVc9KJ/1016-add-payment-branded-icons-on-small-breakpoints-in-the-checkout)
| Under 355px (320px) |  Over 355px (360px) |
| -- | -- |
| <img width="320" alt="Screenshot 2023-02-09 at 15 18 09" src="https://user-images.githubusercontent.com/44685872/217855518-666bb7ba-1528-4db0-9c1a-f670966aa4d9.png"> | <img width="360" alt="Screenshot 2023-02-09 at 15 18 26" src="https://user-images.githubusercontent.com/44685872/217855523-daf9154c-5c57-4cf5-9474-c33bc36ec274.png"> |

Add branded payment icons on mobile breakpoints

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.ts
stripe-patrons-data/build.sbt
stripe-patrons-data/riff-raff.yaml
stripe-patrons-data/src/main/scala/com/gu/patrons/conf/PatronsStripeConfig.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/PatronCancelledEventLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/PatronSignUpEventLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/lambdas/ProcessStripeSubscriptionsLambda.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/model/Errors.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/model/StripeSubscriptionsResponse.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/services/PatronsStripeService.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/services/StripeSubscriptionsProcessor.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/lambdas/ProcessStripeSubscriptionsLambdaSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/Fixtures.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/PatronsStripeServiceSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/SerialisationSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/StripeSubscriptionsProcessorSpec.scala

At the moment, there is a scheduled lambda which gets information from stripe about newly-signed-up patrons and adds it to the SupporterProductDataPROD DynamoDB table. This PR makes a new lambda which can do the same job but is triggered by a stripe webhook rather than a schedule.
[**Trello Card**](https://trello.com/c/1LKM0HEu/998-change-stripe-patrons-lambda-into-a-webhook-rather-than-a-scheduled-lambda)
In more detail, this change:
- Makes that new lambda
- Adds an API gateway endpoint for calling it
- Adds necessary config for it to be called from both patron stripe accounts (GNM Patron Scheme and GNM Patron Scheme AUS)
- Adds necessary config for the existing cancel-event lambda to be called from GNM Patron Scheme AUS
- Changes existing stripe service calls to specify which account …

Add lambda for patron sign-up stripe webhook

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.ts

Now that sign-up is being handled by a webhook, we don’t need this schedule. We do want to keep the lambda though, in case we want to run it again sometime.
This PR is post-deployment work needed for [this Trello card](https://trello.com/c/1LKM0HEu/998-change-stripe-patrons-lambda-into-a-webhook-rather-than-a-scheduled-lambda), as detailed in https://github.com/guardian/support-frontend/pull/4719

Remove schedule from StripePatronsDataLambda

---

support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequest.ts

Click on single, then click on other amount button. Then (without touching the exposed other amount field) click on monthly, and then click on single again. We get a NaN error in the console.This PR fixes that
[**Trello Card**](https://trello.com/c/DrwJf6ix/1054-nan-error-with-other-amount-field)

Fix for NaN error with  Other Amount Field

---

support-frontend/assets/helpers/subscriptionsForms/rules.ts

This is to place a validation for lengths of FirstName and LastName field  within the Guardian Weekly checkout ,It should not be more than 40 characters.
[**Trello Card**](https://trello.com/c/zFFAjsWu/1024-subscribe-gw-firstname-field-not-limited-to-40chars)
Validation not appearing for FirstNames greater than 40 characters (SalesForce limit) in length within the Guardian Weekly checkout - see screenshot for example.
Before Change
After Change

Fix Subscribe GW firstName field not limited to 40chars

---

support-frontend/app/utils/CheckoutValidationRules.scala

This validation is currently disabled for recurring contributions below the threshold for supporter plus. It was disabled [in October 2021](https://github.com/guardian/support-frontend/commit/0ef5a8277d5b45209752e123a8c4a36b51b5adbd#diff-a6dbd081ad177ddb469e4501b720b5bf9bbb45801fa6ad382c6c0be4e28c25daL18), and I don’t think it should stay disabled any longer, as it would now be called if enabled.
I’ve tested in CODE, verified that the validation is called (by curling the endpoint with an empty billing account ID), and that I can still get through some normal user journeys (new recurring contribution with existing card, new recurring contribution with new card, new recurring contribution with new direct debit). The plan is to merge this and keep an eye out for any errors, though I don’t …

Restore contribution validation

---

.scala-steward.conf

This is to remove the pullRequests.frequency = "0 10 * * 1-5" #10 am Monday to Friday from the  .scala-steward.conf file  as it wasn't parsed correctly
cron4s.InvalidCron: Either DayOfMonth and DayOfWeek must have a ? expression: DownField(frequency),DownField(pullRequests)
Please check comments from https://github.com/guardian/support-frontend/pull/4541
- [ x] No

Update ScalaSteward config file by removing pull request frequency

---

support-frontend/assets/helpers/tracking/quantumMetric.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

This adds a Quantum Metric event recording the user's selected payment method at the point of conversion, enabling us to better track conversions via payment method. It also refactors some repeated code in our various QM tracking functions to make it easier to establish when a call can be sent.
[**Trello Card**](https://trello.com/c/F1P7jkM6)

Add QM event to track payment method at the point of conversion

---

support-frontend/assets/components/containers/centredContainer.tsx
support-frontend/assets/components/containers/fullWidthContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/content/productInfo.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLandingProps.ts

This adds an AB test to change the order and position of price cards on the Guardian Weekly landing page. Please see attached screenshots for the control and variant.
[**Trello Card**](https://trello.com/c/fb1qK6jg/1032-change-position-and-order-of-price-cards-for-gw-on-mobile-build)
| | Mobile | Desktop |
| -- | -- | -- |
| Control | ![localhost_9211_uk_subscribe_weekly (2)](https://user-images.githubusercontent.com/44685872/219340745-d677d28e-5e1b-4717-8fb6-4872c22a5a17.png) | ![localhost_9211_uk_subscribe_weekly (1)](https://user-images.githubusercontent.com/44685872/219340023-f6215a69-da70-4c19-af97-ecaaa03d8ffb.png) | 
| Variant | ![localhost_9211_uk_subscribe_weekly (3)](https://user-images.githubusercontent.com/44685872/219340860-e157975f-2f95-456f-953f-c433e46d0a0b.png) | …

Add GW price cards reordering AB test

---

support-workers/cloud-formation/src/yarn.lock

Update minimist from 1.2.5 to 1.2.8.
As this is dependency of "handlebars": "^4.7.7",I have run -yarn upgrade handlebars which in turn upgraded the below handlebars dependencies
1)Minimist from 1.2.5 to 1.2.8
2.uglify-js from 3.14.5 to 3.17.4
3.wordwrap
[**Trello Card**](https://trello.com/c/NCivfZE1/755-support-frontend-update-minimist-from-125-to-127)
Patch update (1.2.5 to 1.2.7), and dependabot automated PRs are failing for this dependency, so we need to manually update.
Updates ->
minimist from 1.2.5 to 1.2.7 in /support-workers/cloud-formation/src #4275
- [ x] No

Update minimist from 1.2.5 to 1.2.8

---

support-frontend/assets/components/existingMethodPaymentButton/existingCardPaymentButton.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx

After we enabled existing payment methods on the new checkout we began seeing failed checkouts in our Step Function executions. These were caused by an empty string for the `paymentMethod`'s `billingAccountId` in the Step Function's input JSON, which causes the failure.
In response we introduced a change (https://github.com/guardian/support-frontend/pull/4667) that aimed to block users from checking out if the existing payment method they selected had an invalid `billingAccountId`.  It would block checking out by disabling the submit button on the checkout.
Unfortunately there was an issue with the condition used for disabling/enabling the button, and we were disabling it for users with a valid `billingAccount` and enabling for those without.
Rather than fix I've removed that logic as I'm …

Only render existing payment methods that have a valid billingAccountId

---

support-frontend/assets/helpers/user/reduxSetup.ts

This simplifies the conditions around detecting when a user is using test credentials, to solve a bug that's arisen from merging user detection and setup logic between the contribution and subscriptions checkouts.

Simplify basis of detecting when a user is a test user

---

support-frontend/build.sbt

Change okhttp from 4.10.0 to 3.14.9 as it caused post deployment build failure
Scala Steward bot had upgraded okhttp to 4.10.0 from 3.14.9  in the  https://github.com/guardian/support-frontend/pull/4792.
But this caused post deployment test failures.So we need to revert it

Change okhttp from 4.10.0 to 3.14.9 as it caused post deployment build failure

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

Nudging component, encouraging single to monthly or modified annual recurring contributions
Rename test  to 'ab-singleToRecurringV3'
[**Trello Card**](https://trello.com/c/0bPcisad/1082-ab-test-copy-change-for-the-single-nudge-on-the-checkout)
Annual Features->
- abtest to work at breakpoints above mobile 
- copy change variant (control stays monthly)
- minimum weekly contribution rounded (p = GPB Countries, displayCcy = remainder)
- 740px+ headline2 copy 
- <375px-739px headline2 copy font adjusted to fit in single line at 375px
control (All)
variant (All 740px+)
variant (GBP / <375px->739px)
variant (EUR / <375px->739px)
variant (Others  / <375px->739px)
2-cohort A/B test for implementation ->
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV3=control (Monthly) …

nudge yearly copy abtest applies to audiences above mobile only

---

support-lambdas/it-test-runner/cfn.yaml

#4474 introduced a new integration test for the creation of Supporter plus V2 subs but when this test runs in AWS via the [automated test runner](https://github.com/guardian/support-frontend/wiki/Automated-IT-Tests) it has been failing. 
This was because the runner lambda didn't have permission to load the catalog file from S3, this PR adds that permission.

Add permission for it-test lambda to load the catalog

---

support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx

This updates the legal disclaimer underneath the payment cta for users who qualify for 'supporter plus' i.e. are above the recurring minimun threshold amount to recieve additional benefits.
[**Trello Card**](https://trello.com/c/1pycOuog/1067-update-legal-disclaimer-below-the-payment-cta-on-the-s-checkout)
On the supporter plus LP, as a recurring contributor (monthly or annual) ensure your selected amount is above the [minimum amount](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/supporterPlus/benefitsThreshold.ts#L8) to view the updated copy.
| UK | US |
| -- | -- |
| <img width="560" alt="Screenshot 2023-02-24 at 11 43 24" src="https://user-images.githubusercontent.com/44685872/221176197-fdca371f-e090-41dd-9a4c-0bb71e2fd86f.png"> | <img …

Update Supporter Plus Legal Disclaimer

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

Nudging component, encouraging single to monthly or modified annual recurring contributions
Rename test  to 'ab-singleToRecurringV3'
Annual Features->
- abtest to work at ALL breakpoints
- copy change variant (control stays monthly)
- minimum weekly contribution rounded (p = GPB Countries, displayCcy = remainder)
- 740px+ headline2 copy 
- <375px-739px headline2 copy font adjusted to fit in single line at 375px
control (All)
variant (All 740px+)
variant (GBP / <375px->739px)
variant (EUR / <375px->739px)
variant (Others  / <375px->739px)
2-cohort A/B test for implementation ->
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV3=control (Monthly)
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV3=variant (NEW Annual)

nudge works at all  breakpoints

---

support-frontend/assets/helpers/redux/checkout/address/reducer.ts

Fix the Bug on error message for State / province dropdown (for US / AUS / CA pages)
[**Trello Card**](https://trello.com/c/br9VGdKF/1100-bug-on-error-message-for-state-province-dropdown-for-us-aus-nz-pages)
Error messages is not dismissed when the users chooses an item from the dropdown for the State or Province dropdown on US / AUS and CA pages.
- [x ] No
**Before Change**
**After Change**

Fix the Bug on error message for State / province dropdown (for US / AUS / CA pages)

---

support-frontend/assets/helpers/abTests/abtest.ts

Relates to changes to the Epic CTA URL string made in this PR in `support-dotcom-components` repo https://github.com/guardian/support-dotcom-components/pull/839 
[**Trello Card**](https://trello.com/c/1viEFveD)
We have a request from Marketing colleagues that, for cases where they are running an `Amounts AB test` in support-frontend, the amounts data for the user's selected variant of that test should also display in the `ContributionEpicChoiceCard` when that user sees an Epic marketing message on the main site.
This PR updates the `support-frontend` Amounts AB testing allocation code to look for an amounts test variant detailed in the URL query string and use that variant if found, otherwise continuing to allocate the user to an Amounts test variant as happened before.
See testing …

Support Amounts AB testing in the Epic choice cards component

---

support-frontend/assets/components/thankYou/appDownload/appDownloadItems.tsx
support-frontend/assets/components/thankYou/thankYouModule.tsx
support-frontend/assets/components/thankYou/thankYouModuleData.tsx
support-frontend/assets/pages/kindle-subscriber-checkout/kindleSubscriptionRouter.tsx
support-frontend/assets/pages/kindle-subscriber-thank-you/components/heading.tsx
support-frontend/assets/pages/kindle-subscriber-thank-you/components/subheading.tsx
support-frontend/assets/pages/kindle-subscriber-thank-you/components/thankYouHeader.tsx
support-frontend/assets/pages/kindle-subscriber-thank-you/kindleSubscriptionThankYou.tsx
support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx

Following https://github.com/guardian/support-frontend/pull/4811 which adds a new checkout page for migrating Kindle subscribers, this adds the accompanying thank you page. This page is based on the preexisting Supporter Plus(S+) thank you page, with a few key differences:
- We do not show the [marketing consent](https://62e115310aef0868687b2322-rxpdpiiwpg.chromatic.com/?path=/story/checkouts-thank-you-module--marketing-consent) or [support reminder](https://62e115310aef0868687b2322-rxpdpiiwpg.chromatic.com/?path=/story/checkouts-thank-you-module--support-reminder) thank you page modules as they are only displayed for users who make a `ONE_OFF` contribution for S+
- We are not currently showing the [feedback](https://62e115310aef0868687b2322-rxpdpiiwpg.chromatic.com/?path=/story/checkouts- …

Set up a new thank you page for migrating Kindle subscribers

---

support-frontend/assets/helpers/redux/checkout/product/selectors/subscriptionPrice.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

This fixes an issue where we were not sending the `promoCode` field in the payload when submitting a digi sub purchase on the new checkout.

Ensure we send the relevant promo code for Kindle digi sub purchases

---

support-frontend/assets/helpers/redux/checkout/product/selectors/subscriptionPrice.ts

This fixes a bug introduced by #4817 that affects the supporter plus checkout.

Do not try to retrieve product price on S+

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/directDebitForm.tsx
support-frontend/assets/helpers/forms/formValidation.ts
support-frontend/assets/helpers/redux/checkout/address/validation.test.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts
support-frontend/assets/helpers/redux/checkout/personalDetails/state.ts
support-frontend/assets/helpers/redux/utils/validation/commonRules.ts
support-frontend/assets/helpers/subscriptionsForms/__tests__/validationTest.ts
support-frontend/assets/helpers/subscriptionsForms/rules.ts
support-frontend/assets/helpers/subscriptionsForms/validation.ts
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.test.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx
support-frontend/test/utils/CheckoutValidationRulesTest.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscribeRequest.scala

Trello Card: https://trello.com/c/47aV3LRb/1102-block-entering-emojis-in-the-delivery-instructions-field-in-newspaper-home-delivery-checkout
Some characters cause Zuora's API to break, or at least the `/subscribe` endpoint – it’ll return a 200 with an error in the response body. Validating the input first avoids weird behaviour in our step functions (like retrying for a day because the response from Zuora doesn't look like an error), and by validating on the client as well we can help users catch/correct errors more quickly.
The characters that break Zuora are those whose UTF-8 representation contains more than 3 bytes. [According to Wikipedia](https://en.wikipedia.org/wiki/UTF-8#Encoding), that’s those code points above U+FFFF.
I stole this regex method [from …

Fail validation for create requests containing characters that would break Zuora

---

.github/dependabot.yml

This introduces a `dependabot.yml` file which is necessary for enabling [Dependabot Version & Security Updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates).
This targets 4 package-ecosystems that Dependabot will monitor for new versions.
`/support-frontend`, `/support-workers/cloud-formation/src` and `/cdk` are the locations of 3 `package.json` files (aka dependency manifests) within this mono-repo. 
We can also keep our [Github Actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) up to date with Dependabot. Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer.  Enabling …

Enable Dependabot Version Updates

---

support-frontend/assets/components/page/pageTitle.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
support-frontend/assets/pages/paper-subscription-landing/components/content/paperProductInfo.tsx
support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.tsx
support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingProps.ts
support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingStyles.ts

This adds an AB test to change the order and position of price cards on the Newspaper Subscriptions landing page ->
#ab-newspaperPriceCards=control / #ab-newspaperPriceCards=variant
Please see attached screenshots for the control and variant.
[**Trello Card**](https://trello.com/c/fhBoFK3Y/1124-newspaper-price-cards-move-to-top-engineering)
| | Mobile | Desktop |
| -- | -- | -- |
| Control | ![Screenshot 2023-03-03 at 10 45 35](https://user-images.githubusercontent.com/76729591/222701203-e4341f83-4041-45fc-9046-e88f41027782.png) | ![Screenshot 2023-03-03 at 10 46 52](https://user-images.githubusercontent.com/76729591/222701297-8e42901a-81c2-4176-b229-73f2210bcf79.png)
| Variant | ![Screenshot 2023-03-03 at 10 52 02](https://user-images.githubusercontent.com/76729591/222702134-a4325ab3-e99a …

Newspaper Subscription Price Cards - move to top

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

ACTIVATE PRICE CARDS ABTEST
This adds an AB test to change the order and position of price cards on the Newspaper Subscriptions landing page ->
#ab-newspaperPriceCards=control / #ab-newspaperPriceCards=variant
Please see attached screenshots for the control and variant.
[**Trello Card**](https://trello.com/c/fhBoFK3Y/1124-newspaper-price-cards-move-to-top-engineering)
| | Mobile | Desktop |
| -- | -- | -- |
| Control | ![Screenshot 2023-03-03 at 10 45 35](https://user-images.githubusercontent.com/76729591/222701203-e4341f83-4041-45fc-9046-e88f41027782.png) | ![Screenshot 2023-03-03 at 10 46 52](https://user-images.githubusercontent.com/76729591/222701297-8e42901a-81c2-4176-b229-73f2210bcf79.png)
| Variant | ![Screenshot 2023-03-03 at 10 52 …

Guardian Weekly and Newspaper Prices Card move - Activate

---

support-payment-api/src/main/resources/riff-raff.yaml

Ubuntu Bionic is approaching end of life. This PR updates the metering api to use an AMI based on Jammy.
Tested with a contribution in CODE

Upgrade payment-api to ubuntu jammy

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/layout/container.tsx
support-frontend/assets/components/paymentButton/paymentButtonController.tsx
support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/components/priceCards/priceCards.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/components/secureTransactionIndicator/secureTransactionIndicator.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/redux/commonState/selectors.ts
support-frontend/assets/pages/kindle-subscriber-checkout/kindleSubscriptionLandingPage.tsx
support-frontend/assets/pages/supporter-plus-landing/components/checkoutDivider.tsx
support-frontend/assets/pages/supporter-plus-landing/components/finePrint.tsx
support-frontend/assets/pages/supporter-plus-landing/components/guardianTsAndCs.tsx
support-frontend/assets/pages/supporter-plus-landing/components/patronsMessage.tsx
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/checkouts/SecureTransactionIndicator.stories.tsx

This PR sets up the first mobile optimisation test. I've also refactored a few components used in the checkout that were relevant to the test to make them a little more flexible and easier to apply conditional styling to.
[**Trello Card**](https://trello.com/c/zdqCSfuk)
This test aims to start to streamline the user flow on mobile.

Set up first mobile optimisation test for the supporter plus checkout

---

support-frontend/assets/helpers/forms/existingPaymentMethods/existingPaymentMethods.ts

Existing Payment Method: update “Supporter Plus” in user facing copy
[**Trello Card**](https://trello.com/c/056jJ3Pt/1157-existing-payment-method-update-supporter-plus-in-user-facing-copy)
Existing payment methods for recurring contributions are currently switched OFF. Before we can switch them ON we need to stop using “Supporter Plus” in user facing copy in the Existing payment method component.
It was suggested, we simply use 'Used for your current monthly support' .Also we need to watch out for capping here. For example it should be: 'Used for your current monthly contribution / single contribution / annual contribution / monthly support / annual support' etc.
You might find my recently created style guide quite handy! Especially this …

Existing Payment Method: update “Supporter Plus” in user facing copy

---

support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelectorAccordionRow.tsx

Before we turn on existing payment methods on the new checkout we have a task to add the `data-qm-masking="blocklist"` data attribute (explained here: https://github.com/guardian/support-frontend/pull/3789 ) to the payment method label. This will block QM for recording this info.

Add masking data-atrribute to existing payment method label

---

build.sbt
support-modules/acquisition-events/build.sbt
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/AcquisitionDataRowMapper.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
support-workers/src/test/scala/com/gu/acquisitions/BigQuerySpec.scala

Trello card: https://trello.com/c/x5ipW2Ty/475-migrate-bigquery-code-from-streaming-api-to-the-storage-write-api
The storage write API is a newer API than the legacy streaming API we currently use, and google recommends changing to it because it has [lower pricing and more robust features](https://cloud.google.com/bigquery/docs/streaming-data-into-bigquery) such as exactly-once delivery semantics. This change moves our code to the new API, but uses the default stream and so _doesn’t_ provide exactly-once delivery semantics (instead it provides at-most-once semantics).
Changing the API we’re using involves:
1. Converting the data to the org.json types
- To do this, Maps are wrapped in JSONObjects and Lists in JSONArrays
2. Replacing the existing blocking future with a promise-based one
- …

Migrate BigQuery code to storage write API

---

support-lambdas/it-test-runner/cfn.yaml
support-workers/cloud-formation/src/templates/cfn-template.yaml
support-workers/cloud-formation/src/templates/environment-variables.yaml
support-workers/src/main/resources/application.conf
support-workers/src/main/scala/com/gu/config/Configuration.scala
support-workers/src/main/scala/com/gu/emailservices/EmailService.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
support-workers/src/test/scala/com/gu/support/workers/integration/util/EmailQueueName.scala
support-workers/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala

We decided to retire all SQS queues that send emails in favour of single queue - braze-emails.
This change switches support-frontend to use braze-emails queue rather than contribution-thanks.
It also provides the queue name through CloudFormation / system environment rather than config.

Switching to braze-emails queue (from contribution-thanks).

---

cdk/lib/__snapshots__/stripe-patrons-data.test.ts.snap
cdk/lib/stripe-patrons-data.ts

This PR reinstates the scheduled execution of the stripe-patrons-data lambda which pulls information about  Guardian Patrons from Stripe. 
The schedule was removed because we now have a separate lambda which is called by a Stripe webhook when a new subscription is created however this has some issues [described in this card](https://trello.com/c/5fquQCUe/1205-stripe-patrons-customer-update-details-webhook) so until they are fixed I am going to re-enable the scheduled full synchronisation.

Re-enable the stripe patrons scheduled data export

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

This enables the test added in #4791.
[**Trello Card**](https://trello.com/c/sWdAjrUq/1254-enable-mobile-optimisation-variant-a-for-a-b-test)
It's time to run the first mobile optimisation test!

Turn on first mobile optimisation abtest for the supporter plus checkout

---

support-frontend/assets/components/paymentFrequencyTabs/paymentFrequencyTabsContainer.tsx
support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestCompletion.ts
support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestEvent.ts
support-frontend/assets/components/paymentRequestButton/paymentRequestButtonContainer.tsx
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
support-frontend/assets/helpers/forms/paymentMethods.ts
support-frontend/assets/helpers/redux/checkout/payment/contributionsSideEffects.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/state.ts
support-frontend/assets/helpers/redux/checkout/payment/subscriptionsSideEffects.ts
support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/assets/pages/kindle-subscriber-checkout/setup/setUpRedux.ts
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
support-frontend/assets/pages/supporter-plus-landing/setup/setUpRedux.ts
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx
support-frontend/stories/screens/SupporterPlusLanding.stories.tsx
support-frontend/stories/screens/supporterPlusThankYou/AusSupporterPlusThankYou.stories.tsx
support-frontend/stories/screens/supporterPlusThankYou/ROWSupporterPlusThankYou.stories.tsx
support-payment-api/src/main/scala/backend/StripeBackend.scala

Trello card: https://trello.com/c/PBBDfgCy/1159-check-on-client-side-validation-for-state-field-when-using-apple-pay-or-google-pay
We’ve had some examples recently of users paying via Apple Pay where the currency is GBP and the credit card country is GB, but the billing address country is US and the `state` field is the empty string. This then fails in support-workers because the state isn’t allowed to be empty when the country is US. Some users then try another payment, and unfortunately the country and state data from Apple Pay is reused on subsequent submissions, preventing them from continuing.
At the moment, if a user is on the UK page but uses Apple Pay and we get a billing address that’s in the US, we don’t require a non-empty state on the client-side. We then send the request to …

Fix apple pay country & state logic

---

support-frontend/test/selenium/util/DriverConfig.scala

We currently don't have network logs enabled for our post deploy tests but I think they would be useful so this PR enables them.
[Related docs](https://www.browserstack.com/docs/automate/selenium/debugging-options?_gl=1*1yjr133*_ga*MTc5MjUxMTM3Ni4xNjY5MjEyNDk2*_ga_BBS5LEDVRG*MTY4MTQwNDM1OS4zLjEuMTY4MTQwNDM5MS4yOC4wLjA.#enable-network-logs)

Enable browserstack network logs

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx

Minor PR follows on from the first mobile optimisation test ->
https://github.com/guardian/support-frontend/pull/4791
Header resized to display over 2 lines
This test aims to start to streamline the user flow on mobile.

mobile optimisation test, 2-line header change for the supporter plus checkout

---

.github/workflows/acquisition-events-api.yml

This is to update acquisition-events-api.yml to realign the build numbers  for Acquistion-events-api .
This is to resolve the issue 
that occurred during the riff-raff deployment caused due to a mismatch in the build numbers

Realign the build numbers for Acquisitions events api

---

support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/directDebitForm.test.tsx
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/actions.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/reducer.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/state.ts
support-frontend/assets/helpers/subscriptionsForms/formActions.ts
support-frontend/assets/helpers/subscriptionsForms/formFields.ts
support-frontend/assets/helpers/subscriptionsForms/formReducer.ts
support-frontend/assets/helpers/subscriptionsForms/formValidation.ts
support-frontend/assets/helpers/subscriptionsForms/rules.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/assets/helpers/subscriptionsForms/subscriptionCheckoutReducer.ts
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
support-frontend/assets/pages/supporter-plus-landing/setup/legacyReducer.ts
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx

This creates an `addressMeta` slice that manages a couple of additional bits of address-related information:
- Delivery instructions for newspaper home delivery
- Whether or not the user's billing address is different to their delivery address
This also fixes a small bug where errors relating to the delivery instructions field- if users entered characters that aren't compatible with Zuora's database- were not being passed to the text area component to be displayed inline as well as in the error summary at the bottom of the form.
[**Trello Card**](https://trello.com/c/FeSSCuFe)
This is a bit of address-related state that we missed in the original address migration.

Migrate delivery instructions and separate billing address toggle to RTK

---

support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx

This fixes a bug where a user signing up for an annual contribution of an amount below the Supporter Plus threshold would see an incorrect date in the terms and conditions.
[**Trello Card**](https://trello.com/c/uL6COPQL)
**Before**
**After**

Fix bug with renewal date display in S+ terms & conditions

---

support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

I changed this logic to fix a bug where incorrect payment request button country info was getting reused on subsequent payment attempts (with different payment methods). However, it caused another bug: [the fallback logic](https://github.com/guardian/support-frontend/blob/7c692d7212d169d8d026f3767debaa43e96f2613/support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts#L183-L195) prioritises geolocation over detection of region based on the path of the page, unlike [the initial detection of the billing country on page load](https://github.com/guardian/support-frontend/blob/7c692d7212d169d8d026f3767debaa43e96f2613/support-frontend/assets/helpers/redux/checkout/address/state.ts#L50).
This meant that users trying to use a currency other than that of their current …

Revert billing country logic change

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/acquisition-events-api.test.ts.snap
cdk/lib/acquisition-events-api.test.ts
cdk/lib/acquisition-events-api.ts
support-lambdas/acquisition-events-api/cfn.yaml
support-lambdas/acquisition-events-api/riff-raff.yaml

Recreate existing CFN template using CDK constructs, while retaining existing infrastructure for Acquisition-events-api.This is done for Support Acquisition API GuCDK Migration.
[**Trello Card**](https://trello.com/c/UMwD5nX3/1222-support-acquisition-api-gucdk-migration-recreate-existing-cfn-template-using-cdk-constructs-while-retaining-existing-infrastruct)
For apps where avoiding downtime is critical, a dual-stack migration strategy forGuCDK Migration is recommended . The idea is to duplicate the key parts of the stack using the pattern, test, and, once confident, switch DNS to point to the new stack.
In this phase  we create a new version of your app's infrastructure, according to CDK’s best practices. So, we should have a functional copy of the application, which can be used for …

Support Acquisition API GuCDK Migration-Recreate existing CFN template using CDK constructs

---

cdk/lib/stripe-patrons-data.ts
stripe-patrons-data/src/main/scala/com/gu/patrons/model/StageConstructors.scala
stripe-patrons-data/src/main/scala/com/gu/patrons/services/ParameterStoreService.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/lambdas/ProcessStripeSubscriptionsLambdaSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/ConfigServiceSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/PatronsIdentityServiceSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/PatronsStripeServiceSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/StripeSubscriptionsProcessorSpec.scala
stripe-patrons-data/src/test/scala/com/gu/patrons/services/SupporterDataDynamoServiceSpec.scala
support-modules/supporter-product-data-dynamo/README.md
support-modules/supporter-product-data-dynamo/src/main/scala/com/gu/supporterdata/model/Stage.scala
support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
support-payment-api/src/main/scala/services/SupporterProductDataService.scala
support-workers/src/main/scala/com/gu/services/Services.scala
supporter-product-data/cloudformation/cfn.yaml
supporter-product-data/cloudformation/create-table-stack.sh
supporter-product-data/cloudformation/dynamo-tables.yaml
supporter-product-data/riff-raff.yaml
supporter-product-data/src/main/scala/com/gu/lambdas/ProcessSupporterRatePlanItemLambda.scala
supporter-product-data/src/main/scala/com/gu/model/StageConstructors.scala
supporter-product-data/src/main/scala/com/gu/services/ConfigService.scala
supporter-product-data/src/main/scala/com/gu/services/SelectActiveRatePlansQuery.scala
supporter-product-data/src/test/scala/com/gu/lambdas/AddSupporterRatePlanItemToQueueIntegrationTest.scala
supporter-product-data/src/test/scala/com/gu/lambdas/QueryZuoraLambdaSpec.scala
supporter-product-data/src/test/scala/com/gu/services/ConfigServiceSpec.scala
supporter-product-data/src/test/scala/com/gu/services/DynamoDBServiceSpec.scala
supporter-product-data/src/test/scala/com/gu/services/ParameterStoreServiceSpec.scala
supporter-product-data/src/test/scala/com/gu/services/S3ServiceSpec.scala
supporter-product-data/src/test/scala/com/gu/services/ZuoraQuerierServiceSpec.scala

This PR continues the work started in #4889 and described in [this document](https://docs.google.com/document/d/1wg1kMk7U7ht3AmPpsPUimtz1FkVbu5BWjijjme2598s/edit#) to standardise environment names across the supporter revenue stacks.
The supporter product data stack (and stripe patrons data stacks) have their own definition of stages (to avoid pulling in a large number of dependencies from the support-frontend stack I think?), which was not changed in previous PRs but is updated here.

Rename DEV to CODE in supporter product data

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/frontend.test.ts.snap
cdk/lib/frontend.ts
cdk/lib/payment-api.ts
support-config/src/main/resources/touchpoint.CODE.conf
support-config/src/main/scala/com/gu/support/config/TouchpointConfigProvider.scala
support-config/src/test/scala/com/gu/support/config/PromotionsConfigSpec.scala
support-frontend/conf/riff-raff.yaml
support-lambdas/acquisition-events-api/riff-raff.yaml
support-lambdas/acquisitions-firehose-transformer/riff-raff.yaml
support-lambdas/it-test-runner/cfn.yaml
support-lambdas/it-test-runner/riff-raff.yaml
support-lambdas/it-test-runner/src/main/scala/com/gu/RunITTests.scala
support-lambdas/stripe-intent/riff-raff.yaml
support-modules/supporter-product-data-dynamo/README.md
support-payment-api/src/main/resources/riff-raff.yaml
support-services/src/main/scala/com/gu/support/catalog/CatalogJsonProvider.scala
support-workers/build.sbt
support-workers/cloud-formation/src/templates/cfn-template.yaml
support-workers/riff-raff.yaml
support-workers/src/main/scala/com/gu/services/Services.scala
support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
supporter-product-data/build.sbt

Following on from #4938 this PR switches over all projects to use the CODE version of the supporter product data and promotions tables and updates the cloudformation to apply the correct permissions.

More DEV to CODE stuff

---

support-frontend/build.sbt

Update  okhttp3 to 4.11.0(Snyk High-level vulnerability) manually.
[**Trello Card**](https://trello.com/c/u5rvh17F/1078-support-frontend-update-okhttp3-to-at-least-492-snyk-high-level-vulnerability)
In June 2022 we merged [a scala steward PR](https://github.com/guardian/support-frontend/pull/3892) that built successfully updating okhttp3 to v4.10, but the post-deployment tests failed to work with that version, so we reverted it .
But the okhttp3 dependency is listed as having a high-severity vulnerability by Snyk, so we have to upgrade it .
Upgrading to 4.10.0  showed issues like
java.lang.NoClassDefFoundError: Could not initialize class org.openqa.selenium.chrome.ChromeDriverCommandExecutor
and java.lang.NoSuchFieldError: Companion as in screenshots below
But upgrading to 4.11.0 seems to …

Update  okhttp3 to 4.11.0

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx

Set-up Emotional benefit AB Test
[**Trello Card**](https://trello.com/c/a2iskxQ7/1219-set-up-emotional-benefit-ab-test)
Test whether adding in an emotional benefit in to the benefits bullet points will increase conversion
### Context:
Following the latest copy changes and review, we have decided to change this to make more sense in a flow
Remove “you will” in title
change all benefits copy for variant
[**Figma link here**](https://www.figma.com/file/MQu0jaD3GR1C0CpdLLozOJ/MVP---optimisation---Q4?node-id=1672-87106&t=sIKUwyRJh6ZKQin9-0)
- [ x] Yes
Test details:
this will be AB tested on desktop only, at the same time as mobile variant B
Metrics: This will be to test conversion rate
[**Optimize …

Set-up Emotional benefit AB Test

---

support-frontend/package.json
support-frontend/yarn.lock

Updating @guardian/consent-management-platform to the latest version.
[**Trello Card**](https://trello.com/c/oAu5oDfQ/1025-bump-all-consumers-of-the-consent-mangement-platform-library-v1302)
We recently updated the vendors list.

Updated @guardian/consent-management-platform": to "^13.0.2"

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

This PR is to make the Emotional benefit AB test active
Refer  [**PR 4943**](https://github.com/guardian/support-frontend/pull/4943)
[**Trello Card**](https://trello.com/c/a2iskxQ7/1219-set-up-emotional-benefit-ab-test)
- [ x] Yes

Set emotional benefit test active

---

support-frontend/assets/components/product/productOption.tsx
support-frontend/assets/components/product/productOptionStyles.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
support-frontend/stories/product/ProductOption.stories.tsx

This adds a 'special offer' variant of our `ProductOption` component that adds a border, background, and full width top label, to support the upcoming '12 for £12' promotion for Guardian Weekly.
It also adds some promotion-specific logic to display this component variant, and an amendment to add a link to our terms and conditions below the product price cards.
[**Trello Card**](https://trello.com/c/YONhXPJM)

Add a 'special offer' variant of the print product option cards for 12for12

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

On Subscriptions landing page - price should say “£12 for 12 issues” instead of “13.75/monthly”
This should be for UK only- as this page is only visible in UK
This should be turned off 12th June and revert to original text of “13.75/monthly” (unhighlighted)
[**Trello Card**](https://trello.com/c/2wVVekB7/1275-gw-12for12-change-price-on-subscriptions-landing-page-to-12-for-12-instead-of-1375-monthly-for-gw)

Change price on Subscriptions landing page to £12 for 12 instead of 13.75/monthly for GW

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/services/HttpIdentityService.scala

We’ve had some timeouts recently, and it’d be helpful to know which endpoint we’re getting the timeout from: this should mean we see it in the logs.
This came up during alarm investigations: we considered raising the timeouts, but I’ve noticed that there’s retry logic in place: up to 2 retries, 3 seconds timeout per request. So raising to 5 seconds would mean it might take over 15 seconds, which is quite long to make the user wait. I’ll bring it up with Identity anyway, see what’s normal for a timeout.

Include identity endpoint in error messages

---

support-frontend/assets/components/paymentRequestButton/hooks/payerDetails.ts
support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
support-frontend/assets/components/personalDetails/stateSelect.tsx
support-frontend/assets/helpers/__tests__/formValidation.ts
support-frontend/assets/helpers/forms/formValidation.ts
support-frontend/assets/helpers/internationalisation/country.ts
support-frontend/assets/helpers/internationalisation/shouldCollectStateForContribs.ts
support-frontend/assets/helpers/redux/checkout/address/state.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/actions.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/state.ts
support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
support-frontend/stories/checkoutLayout/PersonalDetails.stories.tsx

Trello Card: https://trello.com/c/ILKQJnOC/1262-support-checkout-client-side-validation-not-enforcing-required-state-field-for-recurring-supporters-in-usa-and-ca-paying-with-cr
This PR attempts to fix issues we’ve had with apple pay users by storing the payment-request-button-provided country and state separately from the form-entered or guessed ones, so that our code can choose to only use the payment-request-button-provided info when the payment request button is the current payment method. I’ve split the description of the changes for the three commits in the PR:
Rather than have two places in which country-guessing logic lives, this commit consolidates them into one: the country is guessed on page load, and not when sending data to the backend.
I’ve also removed the special case for …

Store payment method country/state separately

---

.git-blame-ignore-revs
.scalafmt.conf
support-payment-api/src/main/scala/services/StripeService.scala

Update scalafmt to 3.7.3

---

project/build.properties

Update sbt to 1.8.2

---

project/LibraryVersions.scala

Update jackson to 2.15.0

---

stripe-patrons-data/build.sbt

Update logback-classic to 1.4.7

---

support-frontend/build.sbt

Update sentry-logback to 6.18.1

---

support-models/build.sbt

Update joda-time to 2.12.5

---

support-lambdas/acquisitions-firehose-transformer/build.sbt

Update scanamo to 1.0.0-M25

---

support-modules/acquisition-events/build.sbt

Update google-cloud-bigquery to 2.25.0

---

.scala-steward.conf

Grouping all non-AWS PRs leads to big failing PRs like [4919](https://github.com/guardian/support-frontend/pull/4919) where it’s unclear which dependency is causing the failure. Major version changes in dependencies are less likely to pass without attention, so let’s remove those from the group to improve the odds of getting large PRs with successful builds. If no group matches, individual PRs will be raised.
This configuration is described [here](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md). I think it’s just minor, patch, and major that we need to worry about, but I’m not certain: maybe we should include pre-release and build-metadata? Should be easy to see if that happens anyway, and we can fix then.

Only group minor and patch non-aws PRs

---

support-lambdas/it-test-runner/build.sbt
support-lambdas/stripe-intent/build.sbt
support-payment-api/build.sbt
support-workers/build.sbt
supporter-product-data/build.sbt

Update logback-classic to 1.2.12

---

project/LibraryVersions.scala

Update okhttp to 3.14.9

---

project/plugins.sbt

Update sbt-sonatype to 3.9.20

---

project/LibraryVersions.scala
support-frontend/build.sbt
support-models/build.sbt
support-modules/rest/build.sbt
support-payment-api/src/test/scala/controllers/StripeControllerSpec.scala
support-payment-api/src/test/scala/model/paypal/PaypalRefundWebHookBodySpec.scala
support-workers/build.sbt

Update circe-core to 0.14.5

---

support-frontend/assets/components/subscriptionCheckouts/total/total.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

The 12for12 discount we've made for the GW doesn't work for PayPal customers, even if they've selected 'Quarterly' with the discount. They get shown full price not discounted price (for all offers). PayPal isn’t showing the discounted amount on checkout, it is still charging £12 in this offer case.
1. Compared `PaperCheckoutForm.tsx` with `weeklyCheckoutForm.tsx` as discounts prices were displayed correctly in the former.
2. Discount price was taken from redux state (function 'selectedDiscountedPrice') which we could apply to the `weeklyCheckoutForm.tsx` (first commit). Tested '_PayPalScreenTotal_' (below screenshot table).
3. `Total.tsx` discounted component price was calculated and displayed at mobile breakpoints. To simplify (reduce code) the calculation was removed and …

Paypal total to include discount final amount

---

support-frontend/assets/pages/supporter-plus-landing/components/stickyCta.tsx

Quantum metric user replays highlighted a focus issue for the `mobileOptmisation2` AB-Test. When switching between single, monthly, annual tabs the benefits list can run underneath and take focus priority over the floating stickyCta. In this case, the stickyCta does not receive a click event because the benefit list has focus. A double press is required, not what is required.
[**Trello Card**](https://trello.com/c/Sy5xzfu2/1317-mobile-optimisation-variant-b-build-stickycta-focus-repair)
A  high z-index priority (10000 as used in overlays and progress messages) was required to be applied to the StickyCta container in order for it to respond to click events rather than the content underneath it.
https://support.thegulocal.com/uk/contribute#ab-supporterPlusMobileTest2=variant …

mobile optimisation variantb stickyCta floats with focus above all content

---

support-payment-api/src/main/scala/backend/PaymentBackend.scala
support-payment-api/src/main/scala/services/SoftOptInsService.scala
support-payment-api/src/test/scala/backend/AmazonPayBackendSpec.scala
support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
support-payment-api/src/test/scala/backend/StripeBackendSpec.scala

Message structure being sent to the `soft-opt-in-consent-setter` was incorrect, as the `identityId` must be converted to a string. The sending of the message to the queue was also not put behind the feature flag.
Have also expanded tests to verify that the soft opt-ins service was called just once.

Fix message structure when sending message to `soft-opt-in-consent-setter`

---

support-workers/build.sbt

Update mockito-scala and mockito-scala-scalatest to 1.17.14

---

support-payment-api/src/main/scala/services/PaypalService.scala
support-payment-api/src/test/scala/services/PaypalServiceSpec.scala

This fixes an issue where the PayPal invoice for single contributions had incorrect capitalisation of 'Guardian'.
[**Trello Card**](https://trello.com/c/fr1Y7yC6)

Fix the capitalisation of Guardian in PayPal invoices

---

build.sbt
support-payment-api/build.sbt

The latter [has been deprecated](https://github.com/sbt/librarymanagement/pull/393). I don’t fully understand why, but the new function uses both old and new sonatype repos somehow. This is a minor sbt change.

Use sonatypeOssRepos over sonatypeRepo

---

project/BuildInfoSettings.scala
project/plugins.sbt

Update sbt-buildinfo to 0.11.0

---

support-frontend/app/services/AuthenticationService.scala
support-frontend/app/wiring/Services.scala
support-frontend/build.sbt

Reverts guardian/support-frontend#4977 as causing errors when user is signed out.  But no public-facing problems.

Revert "Bump Identity lib from 3.255 to 4.11"

---

support-frontend/assets/components/tooltip/Tooltip.tsx

Tooltip paragraph content/text box overlaps any content below it.
This appears to cause an un-selectable region below, as highlighted in the screenshot in blue.
ie. If you were to click in this region there would be no response, it could also possibly be an email box, GooglePay or ApplePay.
[**Trello Card**](https://trello.com/c/48pUZOtu/1318-tooltip-paragraph-text-box-overlay-repair)
`Tooltip.tsx` component 'open' state checked and containig div component css set to display:none if closed.

tooltip hidden paragraph overlaying components below

---

support-frontend/app/services/AuthenticationService.scala
support-frontend/app/wiring/Services.scala
support-frontend/build.sbt

This is identical to #4977 with the addition of dca129840101002ea4a9131970313d7c2d5660b5, which ensures that we don't log an exception when a user isn't signed in.  Users aren't necessarily expected to be signed in.
Tested in Code env.
Can subscribe signed in or signed out and there are no errors appearing in logs.

Bump Identity lib from 3.255 to 4.11 (second attempt)

---

support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx

- bullet points under 12 for 12 UK (only) offer are inaccurate for this offer
- This is because during the campaign, the price per issue is £1. The retail price is £4.95, which is 79% off. This will help conversion and improve the UX flow of the page. Currently, 35% off the cover price doesn’t make sense in the context of the discount and may cause confusion.
UK => 79% discount (until June 9th when 12for12 ends, will need to be reverted alongside £10 bookshop voucher)
Non-Uk => 35% discount
[**Trello Card**](https://trello.com/c/udHn1NHi/1321-gw-support-amend-benefits-line-for-12for12-uk)
12 for 12 Offer
79% benefit discount
https://support.thegulocal.com/uk/subscribe/weekly
35% benefit discount
https://support.thegulocal.com/int/subscribe/weekly

12for12 benefits - uk discount increase

---

support-lambdas/acquisition-events-api/src/test/scala/com/gu/acquisitionEventsApi/LambdaSpec.scala
support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/AcquisitionDataRowMapper.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
support-modules/acquisition-events/src/test/scala/com/gu/support/acquisitions/ga/GoogleAnalyticsServiceSpec.scala
support-payment-api/src/main/scala/model/acquisition/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/test/scala/com/gu/acquisitions/BigQuerySpec.scala

The Zuora Account number is not used in any downstream process of `datalake.fact_acquisition_event`. As the Zuora Subscription ID is already there, there should be no benefit to having the Billing Account number too, so this PR removes it to reduce complexity.
Hopefully just not providing the `zuora_account_number` key in the BigQuery post will still work, as it's always been optional - and so not sent in the JSON payload for non-Zuora acquisitions. 
FYI - I staged a PR to remove the column but it reported that the whole table would be dumped to achieve that, so I'll check in with Data Tech - see: https://github.com/guardian/datatech-tf-modules/pull/164. 
- This PR also paves the way in another PR to add the Zuora Payment ID during checkouts which take payment immediately (e.g. Recurring …

Remove Zuora Account Number from the AcquisitionDataRow

---

support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

If the payment request button state is null, we may still have worked out a sensible state from geolocation. This makes a reasonable fallback if the inferred country matches the payment method country.

Fall back to inferred state when payment request button state is null

---

build.sbt

At the moment, there are frequently two deployments being attempted for the acquisition-events-api at the same time: one from the acquisition-events-api github action, and one from the support-lambdas github action. The latter always fails, I think because the acquisition-events-api now uses CDK but the support-lambdas github action doesn’t do the necessary CDK setup.
I don’t _think_ it makes sense for us to have this being built by two separate github actions, so I propose we remove it from the support-lambdas project (and thereby from the action).

Remove duplicate acquistion-events-api build

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx

Reverts guardian/support-frontend#4917, as the 10-year anniversary campaign is coming to an end. Should be merged shortly before 3pm UTC+1 on the 31st of May.

Revert "Add tote bag to benefits in Australia"

---

support-payment-api/src/main/scala/backend/BackendError.scala

Payment-api tests have been failing recently. With these cases covered, the payment-api tests no longer seem to fail. Interestingly, the null pointer exception still happens, but the subsequent test passes. I guess that’s ok?

support-payment-api: Catch missed error cases

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

Extension to June 25th of Uk Subscription landing copy change -> https://github.com/guardian/support-frontend/pull/4958
[**Trello Card**](https://trello.com/c/zLXHnIB8/1362-gw-support-revert-print-landing-page-updates-when-uk-12for12-campaign-ends-on-june-9th)

Change price on Subscriptions landing page to £12 for 12 until 25th June

---

support-payment-api/src/main/scala/services/SupporterProductDataService.scala

Currently we are adding single contributions to the supporter product data store with a TTL of 999 years, this PR reduces that to 8 years and 1 week, the same as the [contributions data store](https://github.com/guardian/contributions-platform/tree/main/contributions-store/retention-policy)

Set the TTL for single contributions to 8 yrs & 1 week

---

support-frontend/assets/components/cardClickable/cardClickable.tsx

Clickable Card copy text colour change
Minor Update PR ->  https://github.com/guardian/support-frontend/pull/4853 {shown below}
Build of the single less prominent designs. ab-test name 'singleLessProminent'
- Desktop web - designs below
- Mobile web - re-based on mobile optimisation variantA 
- Initial ONE_OFF only contribution types via URL query parameters or session storage need to be removed from the abtest group (not control or variant).
Variant Features/Assumptions->
1. Support Once entire component clickable (not just arrow).
2. Once clicked, Single tab remains visible (a refresh required to reset).
A ClickableCard component may be a more accessible way to contain multiple elements that can be mouse clicked (or the card itself can be tabbed onto and enter pressed to re-produce …

Single Less Prominent, copy text colour change

---

support-frontend/assets/helpers/redux/commonState/selectors.ts

Correction to `Supporter plus nudge annual copy minimum amount increase PR`->https://github.com/guardian/support-frontend/pull/5000
Reverts 'choose your amount' minimum verified annual amounts from 10,  30 and 50 back to 10 regardless of limit on Nudge specified.
[**Trello Card**](https://trello.com/c/DVmMHOHx/1378-increase-nudge-of-single-to-annual-minimum-contribution-revert)
| version | Control | variantA | variantB |
|--------|--------|--------|--------|
|before|![Screenshot 2023-05-23 at 11 24 58](https://github.com/guardian/support-frontend/assets/76729591/6f801853-c1d4-4f4a-987d-a396e602bfb8)|![Screenshot 2023-05-23 at 11 24 17](https://github.com/guardian/support-frontend/assets/76729591/5edd9ebc-2573-42e8-8c75-8380d9cec9fe)|![Screenshot 2023-05-23 at 11 24 …

donot overide the selectors minimum amounts

---

support-frontend/assets/helpers/contributions.ts

Due to changes in pricing requirements, we need to change the nudge pricing for all regions. The new prices are as shown below ->
UK
Control: 10
VariantA: 25
VariantB:50
US
Control: 10
VariantA: 25
VariantB:50
EU
Control: 10
VariantA: 30
VariantB:50
AU
Control: 10
VariantA: 40
VariantB: 75
INT
Control: 10
VariantA: 30
VariantB: 50
CA
Control: 10
VariantA: 35
VariantB: 60
NZ
Control: 10
VariantA: 40
VariantB: 75
[**Trello Card**](https://trello.com/c/Gd9Ff20Z/1405-increase-nudge-to-recurring-change-the-nudge-pricing-for-regions)
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=control
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=variantA
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=variantB
- [Tested with screen …

Supporter plus nudge annual copy minimum amounts revised per region

---

support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx

Can we hard code the line under ‘As a subscriber you’ll enjoy' as follows
AUS GW landing page ONLY (16th June to 15th July)
MODIFY: 'Every issue delivered with up to 35% off the cover price' -> 'Every issue delivered with up to 91% off the cover price'
ADD: 'A free Guardian Weekly tote bag with every 12 for 12 subscription'
N.B. we will then revert to original “35% off” when campaign is complete ( 16th July)
[**OLD Trello Card**](https://trello.com/c/Ci9sx7aI/1325-gw-support-amend-benefits-line-for-12for12-aus)
[**NEW Trello Card**](https://trello.com/c/oNQUt84d/1368-guardian-weekly-au-support-page-changes)
AUS offer period starts June 16th onwards
UK offer period finishes on June 25th.
|After|Desktop|Mobile|
|--------|--------|--------|
|AUS GW|![Screenshot 2023-06-06 at 16 22 …

12for12 Australia benefits Add (16/6/23)

---

support-workers/cloud-formation/src/templates/cfn-template.yaml

The old link gives me a 404, and our first step in alarm investigations is always to look at the list of failed executions – having a link in the alert should help investigate more quickly.

Use better link in support-workers failure alarms

---

support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx

Changes Nudge Subtitle Copy For Variants Only
FROM
'from just'
TO
'for'
| ScreenSize | Control | variantA | variantB |
|--------|--------|--------|--------|
| desktop |![unnamed (5)](https://github.com/guardian/support-frontend/assets/76729591/67b09833-ecce-4011-9560-61cefb184e04)|![unnamed (6)](https://github.com/guardian/support-frontend/assets/76729591/8fb9ed17-daac-40ed-9d64-a1dbd28f03d0)|![unnamed (4)](https://github.com/guardian/support-frontend/assets/76729591/78a086fc-cbe0-462b-99d9-8592e3a4265f)|
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=control
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=variantA
https://support.thegulocal.com/uk/contribute#ab-nudgeMinAmountsTest=variantB
- [Tested with screen …

Supporter plus nudge annual copy variant subtitle change

---

support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

We’ve noticed in at least [one recent support-workers execution](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:865473395570:execution:support-workers-PROD:1578622a-578c-484f-b2bb-3a66c4f8c69a) that Zuora sometimes complains if the state in the address is set but the postcode isn’t.
Since we only _need_ the state on the backend for certain country values, this change only sends it when it’s needed. It’s not clear yet how many people are affected (from testing it seems to be just UK users attempting to use direct debit where Fastly’s geolocation has determined a state for them), but I reckon it’s worth fixing the bug even though we’re not certain of the impact.

Don’t send state to backend unless required

---

support-frontend/assets/helpers/internationalisation/gwDeliverableCountries.ts

Adding additional country missed of this list since October 2019.
Issue raised by Customer Experience team.

Adding additional country missed of this list since October 2019

---

support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
support-frontend/app/controllers/AuthCodeFlowController.scala
support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/thunks.ts
support-frontend/assets/helpers/redux/user/thunks.ts
support-frontend/assets/helpers/user/user.ts
support-frontend/assets/helpers/utilities/authorisation.ts
support-frontend/conf/application.conf
support-frontend/test/controllers/AuthCodeFlowControllerTest.scala

This modifies calls out to the members' data API so that they include an authorization header containing an Okta access token when the feature switch `authenticateWithOkta` is on.  When the feature switch is on but a user isn't signed in, calls to members' data API won't occur at all as they are bound to fail without authorisation.  When the switch is off, the authorization header is omitted and the legacy `SC_GU_U` cookie is used for authorisation.
[**Trello Card**](https://trello.com/c/yun441Ni/4437-support-migrate-clientside-calls-to-mdapi-to-use-okta-access-tokens)
Smoke test is:
1. Feature switch `authenticateWithOkta` off:
All functionality is same as before. Calls out to members' data API give a successful response in browser console network tab when user is signed in with a legacy …

Use Okta access token to authorise call to Mdapi

---

support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx

On Subscriptions landing page - price should say “13.75/monthly” instead of “£12 for 12 issues”
This should be for UK only- as this page is only visible in UK
[**Trello Card**](https://trello.com/c/mULRBmjb/1326-gw-support-amend-benefits-line-for-12for12-uk-revert-to-original)
UK offer period finishes on June 25th.

£12for12 UK Subscriptions Landing page subtitle remove

---

support-frontend/assets/components/checkmarkList/checkmarkList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/assets/components/infoBlock/infoBlock.tsx
support-frontend/assets/components/priceCards/simplePriceCards.tsx
support-frontend/assets/pages/kindle-subscriber-checkout/components/subscriptionBenefitsListData.tsx
support-frontend/stories/checkouts/SimplePriceCards.stories.tsx
support-frontend/stories/content/CheckmarkList.stories.tsx
support-frontend/stories/content/InfoBlock.stories.tsx

This adds the following new components:
- A simplified price cards component limited to two options, with an accordion section for product details
- An extracted checklist component from the existing checkout with a new 'compact' variation
- An 'info box' component to display price and renewal information
[**Trello Card**](https://trello.com/c/xa882tGK)
These components are for use in an upcoming A/B test.

Add components for Supporter Plus Only checkout test

---

support-frontend/assets/components/infoBlock/infoBlock.tsx
support-frontend/assets/components/priceCards/simplePriceCards.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/limitedPriceCards.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/stories/checkouts/SimplePriceCards.stories.tsx

This sets up the limited, supporter plus only checkout for the upcoming email test. Users will be opted into the variant of a referrer-controlled A/B test based on the URL used to direct them to the page. The components merged in #5086 are now integrated with the checkout for users in the test variant, mostly reusing our existing data provider components and render functions.
[**Trello Card**](https://trello.com/c/k55jjs1M)

Set up referrer-controlled A/B test with a limited checkout

---

support-frontend/assets/components/paymentFrequencyTabs/paymentFrequencyTabsContainer.tsx
support-frontend/assets/helpers/__tests__/checkoutsTest.ts
support-frontend/assets/helpers/forms/checkouts.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/reducer.ts

This PR removes the existing feature where we automatically pre-select a payment method for users when they switch their contribution frequency, eg. switching from a monthly to a single contribution. It also reverts the selected payment method back to 'None' when the user switches contribution frequency, in order to avoid users attempting to pay with a disallowed payment method, eg. direct debit with a single contribution.
[**Trello Card**](https://trello.com/c/R3YkoxDd)
This is to reduce user confusion when selecting a payment method, and improve the overall user journey.

Do not auto-select a payment method when switching contribution frequency

---

support-frontend/assets/components/thankYou/feedback/FeedbackItems.tsx
support-frontend/assets/components/thankYou/thankYouModuleData.tsx
support-frontend/assets/pages/kindle-subscriber-thank-you/kindleSubscriptionThankYou.tsx
support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
support-frontend/stories/checkouts/thankYouModule.stories.tsx

Post-purchase surveys live for supporter-plus (ONLY) to build out a portfolio of supporter and subscriber motivations, spanning both digital and print products.These surveys are built using Formstack links.
- Supporter sees survey element on post-purchase ‘thank you’ screen (location?)
- Depending on the type of purchase, the relevant survey link is used.
The change this time is that we’d like to link to 3 different surveys, conditional on the type of purchase:
1. [Recurring, below ‘extras’ threshold](https://guardiannewsandmedia.formstack.com/forms/guardian_supporter_below)
2. [Recurring, above ‘extras’ threshold](https://guardiannewsandmedia.formstack.com/forms/guardian_supporter_above)
3. [Single contributions](https://guardiannewsandmedia.formstack.com/forms/guardian_supporter_single) …

Add post-purchase motivation survey links for supporter plus

---

support-frontend/stories/checkoutLayout/CheckoutNudge.stories.tsx

This adds a checkout nudge story
So there is a corresponding story file for the checkout nudge

Add Checkout Nudge Story

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-models/src/main/scala/com/gu/support/catalog/Product.scala
support-models/src/main/scala/com/gu/support/catalog/ProductOptions.scala
support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
support-models/src/test/scala/com/gu/support/catalog/SerialisationSpec.scala
support-services/src/test/scala/com/gu/support/catalog/ProductRatePlanSpec.scala
support-workers/src/main/scala/com/gu/helpers/SupportWorkersV2Helper.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
support-workers/src/main/scala/com/gu/zuora/productHandlers/ZuoraSupporterPlusHandler.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SupporterPlusSubcriptionBuilder.scala
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
support-workers/src/test/scala/com/gu/support/workers/lambdas/UpdateSupporterProductDataSpec.scala
supporter-product-data/src/main/scala/com/gu/services/S3Service.scala
supporter-product-data/src/test/scala/com/gu/lambdas/AddSupporterRatePlanItemToQueueIntegrationTest.scala

Supporter plus V2 is a reconfiguration of the Zuora product to make it more tax efficient
The high level overview [doc is here](https://docs.google.com/document/d/1_5BG0oj6npvz6X2MSs6XYIsW9uvL4d3tNqeYAG0C8Y8/edit#heading=h.y0059xq85tiu)
A folder containing other related documents, mostly technical spikes [is here](https://drive.google.com/drive/folders/1p8zVX2DfCeVZgFHZnA2ibJtPhFxX4Hz1?usp=drive_link)
Currently we have a 0% AB test which allows us to opt-in to purchasing version 2 of supporter plus but customers are still purchasing version 1, this PR switches that so that all supporter plus purchases are of version 2.
The user experience is unchanged however the terms and conditions page (lives on dotcom, updated through composer) will need to be updated at the same time as this is …

Make the V2 version of SupporterPlus the only one available

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/services/stepfunctions/SupportWorkersClient.scala

Recently, I’ve noticed that some errors mean we don’t see the nicely formatted debug info. I think this is because the errors happen before we get to the line that’s currently doing that logging. Moving that earlier in the execution flow should make our debugging a bit nicer.
To test this, run locally or deploy to CODE and check out using an email address whose domain is `qq.com`. In the support-frontend logs in CloudWatch, you should be able to see the log message that I’ve moved where the debug info is pretty printed. Without the change, the debug info would only be accessible in the request logging, where it is escaped inside a JSON string.

Print debug info earlier

---

support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx

Now we have moved to version 2 of supporter plus we need to update the disclaimer text at the bottom of the supporter plus checkout.

Update supporter plus disclaimer text

---

cdk/lib/__snapshots__/acquisition-events-api.test.ts.snap
cdk/lib/acquisition-events-api.ts

At the moment, the lambda that sends events to BigQuery frequently takes more than 30 seconds to run, which is the timeout limit for API Gateway: this causes the API Gateway to give up on the lambda and return a 5xx to the client, even though the lambda then succeeds shortly afterwards.
Since we can’t quickly fix the lambda to run in a shorter amount of time, this alarm isn’t worth having: it generates a really high level of (approximately) false positives.
Therefore this change disables the alarm for now, until we either speed up the lambda or replace it (possibly with the proposed new architecture where the API Gateway is connected directly to an event bus).

acquisition-events-api: Disable 5xx monitoring

---

cdk/lib/__snapshots__/acquisition-events-api.test.ts.snap
cdk/lib/acquisition-events-api.ts

Increasing the memory available to the lambda might help it run within the 30-second API Gateway timeout.

acquisition-events-api: Try increasing memory to prevent API Gateway timeouts

---

support-frontend/app/actions/CustomActionBuilders.scala
support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/controllers/SupportWorkersStatus.scala
support-frontend/app/wiring/ActionBuilders.scala
support-frontend/app/wiring/Services.scala
support-frontend/test/actions/ActionRefinerTest.scala
support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala
support-frontend/test/controllers/ApplicationTest.scala
support-frontend/test/controllers/SiteMapTest.scala
support-frontend/test/fixtures/DisplayFormMocks.scala

Previously, we had a [UserFromAuthCookiesActionBuilder](https://github.com/guardian/support-frontend/blob/fd08fbdc015eece6c8193bb6ad9b0bd93dc49653/support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala) that checked for cookies containing auth tokens and tried to fetch the tokens if the cookies didn't exist.
In this PR, we optimise the use of auth token cookies by renaming `UserFromAuthCookiesActionBuilder` to `UserFromAuthCookiesOrAuthServerActionBuilder` and introducing a new action builder called `UserFromAuthCookiesActionBuilder`.  Now,  `UserFromAuthCookiesOrAuthServerActionBuilder` either uses the cookies to authenticate or to tries to fetch them.  And the new `UserFromAuthCookiesActionBuilder` only tries to use the cookies to authenticate.  With this new action builder …

Add new action that tries to authenticate using cookies only

---

support-frontend/test/selenium/util/Dependencies.scala

We're seeing errors in the post-deploy tests: `Too many follow-up requests`
eg. https://github.com/guardian/support-frontend/actions/runs/5597174208/jobs/10235302875#step:6:163
This appears to be because in the site availability pre-check for the post-deploy tests, the site root is being redirected to `uk/contribute` and then that is going through a failing auth flow, which should be stopped by a [flashed flag](https://github.com/guardian/support-frontend/blob/4fe24eedc0ede09316175b9b8a705067e268eeb3/support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala#L58) in the request.  That doesn't appear to be happening in this case and we're getting an endless loop.
As this doesn't seem to be happening outside the Selenium pre-check, I'm adding a cookie that will stop the auth flow …

Stop redirecting in availability pre-check

---

support-frontend/app/controllers/DirectDebit.scala
support-frontend/app/controllers/PayPalOneOff.scala
support-frontend/app/controllers/PayPalRegular.scala

In some cases we're attempting to fetch auth tokens from the server when it's not necessary.  After the page has loaded any authenticated endpoints just need to check if auth token cookies are present.

Avoid unnecessary auth flow

---

.github/workflows/support-frontend-build.yml
support-config/src/main/resources/reference.conf
support-config/src/main/scala/com/gu/support/config/PaperRoundConfig.scala
support-frontend/app/config/Configuration.scala
support-frontend/app/controllers/PaperRound.scala
support-frontend/app/wiring/AppComponents.scala
support-frontend/app/wiring/Controllers.scala
support-frontend/app/wiring/Services.scala
support-frontend/conf/routes
support-services/README.md
support-services/src/main/scala/com/gu/support/paperround/PaperRoundService.scala
support-services/src/test/scala/com/gu/support/paperround/SerialisationSpec.scala

To expand paper delivery outside the M25 using PaperRound, we’ll need to offer users a choice of delivery agents for their postcode. This change makes a prototype API on the support-frontend backend which calls PaperRound’s test API to check the agents available for a certain postcode. (I’ve also added the other API endpoints to the service while here.)
- Fixtures taken from responses from the test API
I wanted to change the structure received by the frontend, so I’ve used separate types for the API called by the frontend. I didn’t want to have decoders and encoders for the PaperRound types that don’t round-trip. It also seems a good idea to isolate the dependency on PaperRound’s types from the frontend, but I’m less confident about that one.
The derived encoding of the …

Add endpoints for calling PaperRound’s API

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala

Enable address validation on supporter plus backend
[**Trello Card**](https://trello.com/c/NyRvsWdA/1346-enable-address-validation-on-supporter-plus-backend)
For supporter plus, our backend validation (before support-workers) [only runs the PaidProductValidation rules](https://github.com/guardian/support-frontend/blob/acaf1d05656b53ad9fc81763483fa3e2e8d435b2/support-frontend/app/utils/CheckoutValidationRules.scala#L100).
There’s also a rule on the AddressAndCurrencyValidationRules [that checks that a state has been provided if it’s required](https://github.com/guardian/support-frontend/blob/acaf1d05656b53ad9fc81763483fa3e2e8d435b2/support-frontend/app/utils/CheckoutValidationRules.scala#L239-L244).
We should enable this validation rule for supporter plus, as we know that the step function …

Enable address validation on supporter plus backend

---

.prout.json

The /contribute page now does an oauth redirect, which prout seems to be having trouble with. ([The logs](https://prout-bot.herokuapp.com/view/guardian/support-frontend) report `Could not read from this url, got java.net.ProtocolException: Too many follow-up requests: 21`.)
We think this is because the oauth redirects require cookies to be set in order to function correctly, while Prout doesn’t set cookies.
Handily, the /subscribe endpoint does not (currently) require an oauth redirect, and so this should fix the problem.

Point prout to subscribe page

---

support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx

This will update the GW benefits line in Aus from "Every issue delivered with up to 91% off the cover price" -> "Every issue delivered with up to 35% off the cover price"
[**Trello Card**](https://trello.com/c/VHPkOx08/1414-gw-support-amend-benefits-line-for-12for12-aus-revert-to-original-when-aus-campaign-ends-on-july-31st)

Amend GW benefits line for Aus

---

support-frontend/babel.config.json
support-frontend/package.json
support-frontend/webpack.common.js
support-frontend/yarn.lock

This pr babelify's private class field usage in our codebase so that the site will run in Firefox v78 (still just about on the support list: https://github.com/guardian/csnx/tree/main/libs/@guardian/browserslist-config#readme).
The private class field usage was found in the CMP(https://github.com/guardian/consent-management-platform). CMP support ES2020 and nothing older (https://github.com/guardian/consent-management-platform#bundling) so we are responsible for bundling the CMP should we need to. This was not the case as we had a blanket exclude of all node_modules in our babel config. This pr adds an exception to the node_modules exclude so that the CMP is included in the babel process.
I have also removed the `@babel/plugin-proposal-class-properties` dependancy as the functionality …

[RB] - Fix support for class private fields in firefox 78

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala

The code wasn’t closing the JsonStreamWriter or BigQueryWriteClient when finished with them, which is what’s been causing the OutOfMemoryErrors that we’ve seen in production. With this change we should stop seeing those.

acquisition-events-api: Close JsonStreamWriter and BigQueryWriteClient

---

support-frontend/webpack.common.js

This pr replaces the double exclusion regex pattern in the webpack common file used to decide which files should go through the babel transpilation process. (We want to include our own code and a few of the guardian node_modules dependencies).
The new pattern uses the 'and' and 'not' webpack conditions in order to make the process a bit more readable

[RB] - replace complex regex double exclusion

---

build.sbt

Scalafmt was previously being run on all scala files if any had been updated, this PR changes it to only run on changed files.
[Docs are here](https://scalameta.org/scalafmt/docs/installation.html#settings)

Only run scalafmt on files which have been changed

---

support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.tsx
support-frontend/assets/components/directDebit/directDebitForm/sortCodeInput.tsx
support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.scss
support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.tsx
support-frontend/assets/pages/supporter-plus-landing/components/directDebitWrapper.tsx

This removes phasing from the direct debit form. Prior to this change, the popup form contained 2 phases, an initial 'input' phase as well as a 'confirmation' phase. This PR removes the confirmation phase.
[**Trello Card**](https://trello.com/c/TunDNvQi/1474-removing-phasing-from-directdebitpopupform-and-subcomponents)
As part of the work to transfer the direct debit popup form to the payment method selector

Remove phasing from the Direct Debit Form

---

support-lambdas/acquisition-events-api/src/main/scala/com/gu/acquisitionEventsApi/Lambda.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

In commit fc82dde5c51f863f7c8d1c479592204ba4390389, I began closing resources after each request. However, while the acquisition-events-api can handle this, the payment-api can’t! The former creates a new service on every request, but the latter doesn’t, so on the first request the client was closed and never reopened, causing single contributions to break. (These changes were reverted in commit 6dbcd65e785a0498adbe9d0cc709d6a6fa8760a4).
This PR moves the closing logic so the payment-api doesn’t close the big query client after the first request, while the acquisition-events-api can still close and re-open on every request.
Another option would’ve been to create a new service on every request to the payment api, but the storage write api seems designed to be used in more of a long-running …

BigQueryService: Close resources, but avoid closing client prematurely

---

support-lambdas/acquisition-events-api/src/main/scala/com/gu/acquisitionEventsApi/Lambda.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/bigquery/BigQueryService.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

Reverts guardian/support-frontend#5171
Merging that appears to have broken support-workers’ acquisition event lambda: I don’t know why.

Revert "BigQueryService: Close resources, but avoid closing client prematurely"

---

support-frontend/app/services/HttpIdentityService.scala

We’ve had a couple more timeouts recently (4 in the last 2 months). We’d like to increase the timeout length slightly more to see if that resolves them, as we understand that the calls can take a while because it involves calling Okta.

Increase timeout for calling idapi to 7 seconds

---

support-frontend/assets/components/tooltip/TooltipContainer.tsx
support-frontend/assets/helpers/redux/checkout/product/selectors/isSupporterPlus.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx

This PR hides the benefits list if a user is participating in the `2023-08-08_BENEFITS_GONE` RRCP configured Amounts test and has been assigned to either the `V1` or `V3` cohort.
Note: When looking at this I also noted an issue we introduced when moving the Tooltip out of the benefits list ( https://github.com/guardian/support-frontend/pull/5176), this inadvertently meant the "Cancel anytime" Tooltip started appearing on the Single tab. To address this I've put in an `isOneOff` check when deciding to render this "Cancel anytime" Tooltip, I've also put this in a `TooltipContainer` module to keep the logic out of the presentational `Tooltip` component.
[**Trello Card**](https://trello.com/c/j4eWBkHY/1471-removing-benefits-on-the-current-1-step-checkout-a-b-test-with-amounts)

No Benefits AB test

---

support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.tsx
support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.tsx

This migrates our existing direct debit components to use the `useContributionsSelector` and `useContributionsDispatch` hooks rather than the deprecated connected props pattern.
[**Trello Card**](https://trello.com/c/DoAUCR1g)
This lays useful groundwork for ongoing work to replace this component with something more in line with the current design and UX of the checkout.

Migrate contribs/S+ direct debit components to use the Redux hooks pattern

---

support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

Reverts https://github.com/guardian/support-frontend/pull/5036
AUS GW landing page ONLY:
Removes the hard coded lines under ‘As a subscriber you’ll enjoy' as follows->
MODIFY: 'Every issue delivered with up to 35% off the cover price' -> 'Every issue delivered with up to 91% off the cover price'
ADD: 'A free Guardian Weekly tote bag with every 12 for 12 subscription'
CountryId not required for benefits now, removed.

Remove country specific benefits (Australia GW landing page)

---

support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx
support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx

Reverts https://github.com/guardian/support-frontend/pull/5138
Removes the copy on the Guardian Weekly landing page specifically for EU countries. For those countries the discount should be 35% not 87% now.
CountryGroupId not required for benefits currently so removed.

remove countrygroup specific benefits  (EU GW landing page)

---

support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
support-frontend/app/services/AuthenticationService.scala
support-frontend/app/wiring/Services.scala
support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala

This change ensures that when [gateway](https://profile.theguardian.com/) is down readers are still able to create subscriptions and make contributions.  It does this by making a server-side preflight call to the auth server to check that it's responding appropriately before starting the auth flow.  If the auth server is down the request will continue without user data, in the same way it would do if there were no signed-in user.
The preflight call will only take place if a call to the auth server is necessary for authentication.  In many cases, the cookies that are already present will be enough to authenticate the user.
1. Go to /uk/contribute in Code in an Incognito window and inspect network tab to see that call to auth flow is being made.
2. Disable Code gateway and then go to …

Allow site to continue when identity gateway is down

---

support-frontend/webpack.dev.js

stop webpack from showing an error overlay in the webpack dev config. (errors are still logged in the console and by default it doesn't do this in production)

go away webpack error overlay

---

support-frontend/assets/components/checkmarkList/checkmarkList.tsx
support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx

This adds a checkout summary component for the contributions/supporter plus checkout, for use in the upcoming 2-step checkout test. I've also added an initial container component to supply it with Redux data, but this will likely need refinement once the component is actually integrated into the checkout.
[**Trello Card**](https://trello.com/c/0JQSs5Dt)

Create checkout summary component for the 2 step A/B test

---

support-frontend/assets/helpers/productPrice/fulfilmentOptions.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts

This PR adds a function to change the fulfilment option of a payment request for a national delivery (outside M25). The logic is to check whether a delivery provider has been chosen - indicating the user has chosen a postcode outside the M25 area and seen a choice of suppliers. This will happen after validation
[**Trello Card**](https://trello.com/c/7o4FzIyy/75-support-frontend-change-product-rate-plan-when-postcode-is-chosen)
- [x ] No

Change fulfilmentOption when creating paper delivery checkout request

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala
support-models/src/main/scala/com/gu/support/catalog/FulfilmentOptions.scala
support-models/src/main/scala/com/gu/support/catalog/Product.scala
support-models/src/main/scala/com/gu/support/workers/Products.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscriptionData.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeDecoderTest.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeRatePlansSpec.scala
support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/ga/GoogleAnalyticsService.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/PaperSubscriptionBuilder.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscribeItemBuilder.scala
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala

This PR makes some of the changes in support-frontend required to handle new National Delivery products in Zuora. All Zuora changes I’ve made have been in the api sandbox, not in production.
Trello card: https://trello.com/c/4gIH3UcY/43-product-build-zuora-product-catalog-summary-journal
So far, I have:
- Created a [new product “Newspaper - National Delivery”](https://apisandbox.zuora.com/apps/Product.do?method=view&id=8ad096ca8992481d018992a35483159d) in CODE Zuora (the api sandbox) by cloning the existing [“Newspaper Delivery”](https://apisandbox.zuora.com/apps/Product.do?method=view&id=2c92c0f955c3cf0f0155c5d9ddc53bc3) product and making some changes.
- Removed the …+, Legacy, and Echo-Legacy product rate plans, because we no longer sell these
- Removed the Saturday and Sunday product …

Add new zuora product for national delivery

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala

Update server-side validation to  block support-workers executions with no state.
[**Trello Card**](https://trello.com/c/x9y6amch/1500-find-out-why-server-side-validation-didnt-block-support-workers-executions-with-no-state)
[The support-workers executions failed are attached to the trello card]
In alarm investigations, we found a few step functions where the support workers successfully went through CreatePaymentMethod step when the billing address details had an empty string in the State field for US .But later this caused a Step function failure at the CreateZuoraSubscription step  with the error "Taxation Requirement: State is required for Sold To Contact if the country is United States or Canada.\\\". Countries like US and CA should not have the empty State field.
Upon investigation, …

Update server-side validation to block support-workers executions with no state

---

support-frontend/assets/components/checkoutHeading/checkoutHeading.tsx
support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
support-frontend/assets/components/paymentMethodSelector/paymentMethodSelector.tsx
support-frontend/assets/components/personalDetails/personalDetails.tsx
support-frontend/assets/pages/kindle-subscriber-checkout/kindleSubscriptionLandingPage.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusLanding.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/checkoutScaffold.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/secondStepCheckout.tsx
support-frontend/stories/checkoutLayout/PersonalDetails.stories.tsx

Layout and style amends to the second page of the two step checkout.
Currently behind the `twoStepCheckout` ab test here ->
[https://support.thegulocal.com/uk/contribute#ab-twoStepCheckout=variant](https://support.thegulocal.com/uk/contribute#ab-twoStepCheckout=variant)
[***Trello Card**](https://trello.com/c/VELeJraK/1493-2-step-checkout-implement-design-updates-to-page-2-of-2-step-checkout)
Before (AB variant)             |  After (AB variant)
:-------------------------:|:-------------------------:
Before (AB variant)             |  After (AB variant)
:-------------------------:|:-------------------------:

Two step checkout page 2 (checkout) layout/style amends

---

support-frontend/assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.tsx

This is a small fix to the DD form popup close button. The redux state had recently been refactored to use the newer redux toolkit approach and therefore the function needed to close the button now need to be 'called'.
The popup form close button does not currently close the form.

Fix - Direct Debit popup form close button

---

support-frontend/assets/helpers/redux/checkout/address/validation.test.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/state.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/subscriptionsSideEffects.ts
support-frontend/assets/helpers/redux/subscriptionsStore.ts
support-frontend/assets/helpers/subscriptionsForms/__tests__/validationTest.ts
support-frontend/assets/helpers/subscriptionsForms/formFields.ts
support-frontend/assets/helpers/subscriptionsForms/formValidation.ts
support-frontend/assets/helpers/subscriptionsForms/rules.ts
support-frontend/assets/helpers/subscriptionsForms/validation.ts
support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.tsx

This PR adds validation to the paper checkout form field for selecting a delivery provider when one is available (based on postcode), as well as a side effect to clear the form error when one is selected. 
The validation itself is not behind the `nationalDelivery` AB test but the logic checks whether a delivery provider is available - which it won't be unless the user is in the AB test.
[**Trello Card**](https://trello.com/c/rpO50Bym/82-support-frontend-error-message-on-no-delivery-partner-chosen)
When inputting an address that requires a delivery partner, if a user doesn’t choose a partner, red error message should appear.

National Delivery - Add Validation for Delivery Provider

---

support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
support-frontend/app/controllers/AuthCodeFlowController.scala
support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala
support-frontend/test/controllers/AuthCodeFlowControllerTest.scala

When an auth flow takes place on page load, we lose the referrer for that page.  To get around that, in this PR we store the referrer of the URL when the auth flow begins.  Then, at the end of the auth flow, we expose it as the value of a new query parameter called `pre-auth-ref` so that it can be used for attribution and other analytics.
See also https://github.com/guardian/ophan/pull/5528

Pass referrer through auth flow

---

.scala-steward.conf

This [will require a manual update](https://trello.com/c/mvIwywtl/308-support-frontend-support-frontend-update-comgusimple-configuration-ssm-to-158). Until we do that manual update, let’s get scala steward to ignore it so it doesn’t break our scala steward PRs.

scala-steward: Ignore simple-configuration-ssm

---

support-frontend/app/controllers/AuthCodeFlowController.scala
support-frontend/package.json
support-frontend/test/controllers/AuthCodeFlowControllerTest.scala
support-frontend/yarn.lock

Previously, if a URL already had a `pre-auth-ref` query param another one would be added.  This creates a confusing situation and the first value would probably be taken as the referrer.
In this PR the new value replaces any existing values so that it's very clear what the referrer actually is.
This PR also bumps the version of `ophan-tracker-js` in use for the sake of clarity, although it would actually be covered by the existing specification because only the patch version has changed.
For more context, see:
* #5221 
* https://github.com/guardian/ophan/pull/5529

Remove existing pre-auth-ref values before adding

---

cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
cdk/lib/bigquery-acquisitions-publisher.ts

#4923 added a new stack for publishing acquisition events to BigQuery but there were a couple of TODOs in it
- add an alarm for the publisher lambda
- add a deadletter queue for the publisher SQS queue
this PR does that.

Add alarm and deadletter queue to bigquery-acquisitions-publisher.ts

---

support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala
support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala

Increasing the sleep time before thank you page.
This is an attempt to fix the intermittently failing post deployment tests

Add thread sleep time before thank you page

---

support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/test/utils/CheckoutValidationRulesTest.scala
support-models/src/main/scala/com/gu/support/workers/Products.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscriptionData.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeDecoderTest.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeRatePlansSpec.scala
support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscribeItemBuilder.scala
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala

These were out of sync, which I hadn’t noticed: the delivery agent returned from PaperRound’s API is a number, whereas the backend expected it from the frontend as a string – I’ve changed this to be a number everywhere.
Also, the backend expects it in the product but the frontend was sending it at the top level of the create request – I’ve moved this to the product.

Synchronise deliveryAgent on frontend and backend

---

support-workers/src/main/scala/com/gu/services/Services.scala

#5250 made a change which causes the BigQueryService to work out which data project (PROD or CODE) to write acquisition events to to based on the stage in which the code is running, however this doesn't take account of test users which can be running in PROD but should be written to the CODE project.
This PR fixes that bug

Use the CODE bigquery project for test users in PROD

---

support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmounts.tsx
support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmountsContainer.tsx
support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmountsStyles.ts
support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/checkoutTopUp/upperThreshold.ts
support-frontend/assets/helpers/redux/checkout/product/actions.ts
support-frontend/assets/helpers/redux/checkout/product/reducer.ts
support-frontend/assets/helpers/redux/checkout/product/selectors/selectedAmount.ts
support-frontend/assets/helpers/redux/checkout/product/state.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/limitedPriceCards.tsx
support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/secondStepCheckout.tsx
support-frontend/stories/checkouts/CheckoutTopUpAmounts.stories.tsx
support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx

This pr adds to the two step checkout a/b test to add another variant to the second page of the checkout where users are asked to top up the amount they choose on the first page.
[**Trello Card**](https://trello.com/c/NNBogC6e/1520-2-step-checkout-build-order-summary-component-with-the-nudge-for-page-2-of-2-step-checkout)
Page 2 before | Page 2 after
--- | ---
With amount selected
Contributing above threshold (page 1) | Contributing above threshold (page 2)
--- | ---
Contributing above threshold - starting below (page 1) | Contributing above threshold - starting below (page 2)
--- | ---
Page 2 - Desktop breakpoint
Page 2 - Desktop breakpoint US edition
Page 2 - Desktop breakpoint Europe edition

Two step checkout page two nudge

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/redux/commonState/reducer.ts
support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.tsx

Handle users viewing S+ only variant of checkout.
This change also includes the changes to check the VAT_COMPLIANCE test. On the 2-step checkout, we're going to need to do something to account for this VAT compliant (contributions only) checkout. Without doing anything users in the VAT compliant country list could be allocated to the 2-step checkout with the nudge component - which will allow them to contribute over the  threshold, and acquire S+.
Currently we bucket all users who land on /contribute into our [abtestDefinitions](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/abTests/abtestDefinitions.ts) tests, including those landing on the Supporter Plus Only variant of the checkout.
This isn’t ideal as a lot …

AB Test configuration - how to handle users viewing S+ only variant of checkout

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/tracking/ophan.ts
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/firstStepLanding.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/secondStepCheckout.tsx
support-frontend/package.json
support-frontend/yarn.lock

When a user navigates from page 1 to 2 (and vice-versa) of the 2 step checkout this is done via React Router, so no additional network request is made by the browser. This means both page views are covered by a single page view event in the Page View table of the Data Lake.
We'd like each page view to have a separate page view event in the Page View table of the Data Lake, to do this we can use the `sendInitialEvent` function exposed by Ophan's tracker-js library to manually trigger a second Page View event when a user navigates from Page 1 to 2 (and vice-versa). 
This PR introduces a new function to our Ophan module `navigateWithPageView`, that takes care of setting the referral data used by Ophan in localStorage, navigating to the next page and triggering the new page view event.
I've …

Send new Ophan page view event when navigating between page 1 and 2 on the 2-step checkout

---

support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmounts.tsx

Adding a data-attribute `data-qm-clickable` enables Quantum Metric (QM) to consistently track clicks on this element as it is a static attribute by which they can be identified. Once a static attribute is in place QM can then assign a click listener to it via instrumentation and serve the click events that are needed. This attribute name has been agreed with QM.
[**Trello Card**](https://trello.com/c/MXHksITd/1535-2-step-checkout-quantum-metrics-add-for-tracking-for-nudge)

Make amount button on 2-step nudge trackable with QM

---

support-frontend/assets/helpers/abTests/abtest.ts
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/redux/commonState/reducer.ts

Paired on with @LAKSHMIRPILLAI 
We added a rule in this PR https://github.com/guardian/support-frontend/pull/5251 that would make sure users allocated to the `VAT_COMPLIANCE` test were not included in any other test, implemented as we wanted to be sure they weren't allocated to the `twoStepCheckout` AB test. 
The change was implemented as we assumed the `VAT_COMPLIANCE` would appear in a user's `abParticipations` in state...unfortunately we were mistakenwith this assumption.
We therefore decided to revert back to an original plan for making sure users who experience the `VAT_COMPLIANCE` test are not allocated to the `twoStepCheckout` AB test. We did this by adding a new check when deciding on AB test participations in `abTest.ts`, this check checks a user's country against an …

Add omitCountries check on abTestDefinition

---

support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmountsContainer.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/secondStepCheckout.tsx

Do not show the checkout second page top up/nudge amounts to users that select an amount below the supporter plus threshold on the first page
page 1 before | page 2 before
--- | ---
page 1 after | page 2 after
--- | ---

Checkout page 2 lower threshold check

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx

Amend checkout benefits title to break at a sensible width and … stretch to a single line where possible.
This only affects the two step checkout view, the mutli page (original/control) version stays the same.
Because Helene asked me to :p
before | after
--- | ---
before | after
--- | ---
before | after
--- | ---

Amend checkout benefits title break points

---

support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx

When monitoring the `twoStepCheckout` test with Quantum Metric we noted some users on the 2 step checkout were experiencing an issue: If these user had to scroll down page 1 to click the navigate CTA, when page 2 loaded it retained the scroll position from page 1, meaning they would not see the order summary / nudge component.
This issue is related to the way we load the 2nd page, we use client-side routing, which doesn't trigger the page reload that would typically anchor a user at the top of the screen on a page load.
The solution applied here was recommended in React Router's docs: https://v5.reactrouter.com/web/guides/scroll-restoration

Restore scroll position to the top of the page on navigation change with React Router

---

support-frontend/assets/components/personalDetails/personalDetails.tsx
support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
support-frontend/assets/components/stripeCardForm/stripeCardFormContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts
support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

This sets up an A/B test for making the zip code field mandatory for all contribution types and payment methods in the US, instead of only required when paying by card.
The zip code field is moved into the personal details section alongside the state field, and validation messaging is shown for it regardless of payment method if the user is in the A/B variant.
Postcode/zipcode data will be included in the payload for a recurring contribution/S+, but the client side **DOES NOT** currently send this field for one-off contributions. The back end will need to accept this as part of the payload before this can be changed client-side.
[**Trello Card**](https://trello.com/c/pufBPFJv)
This test is for improved targeting with US contributors.

Client-side: Set up A/B test for making zip code a mandatory field for US contributors

---

.github/workflows/bundle-analyser.yml
.github/workflows/chromatic.yml
.github/workflows/compressed-size.yml
.github/workflows/dependabot.yml
.github/workflows/support-frontend-build.yml
.github/workflows/support-frontend-eslint.yml
.github/workflows/support-frontend-post-deploy-tests.yml
.github/workflows/support-frontend-prettier.yml
.github/workflows/support-frontend-typescript.yml
.github/workflows/support-workers-build.yml

Github Actions: Stop using guardian/actions-setup-node and use actions/setup-node instead
[**Trello Card**](https://trello.com/c/dlZA1kOt/1546-github-actions-stop-using-guardian-actions-setup-node-and-use-actions-setup-node-instead)
The [actions-setup-node repo ] (https://github.com/guardian/actions-setup-node) says that  has been archived by the owner on Dec 5, 2022 and will not be updated.
The official Github [actions/setup-node](https://github.com/marketplace/actions/setup-node-js-environment) now has [some support for node version files](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file).
You should use that instead.

Update to actions/setup-node@v3

---

.github/workflows/payment-api-build.yml
project/LibraryVersions.scala
support-payment-api/build.sbt
support-payment-api/src/main/resources/riff-raff.yaml

Update Payment API to JAVA 11
Along with that updating the below dependencies
1) support-payment-api: Update com.dripower:play-circe to 2814.4 from 2814.2
2) support-payment-api: Update mockito-core to 5.3.1 from 4.11.0
3) support-payment-api: Update scaffeine dependency to 5.2.0 from 4.1.0
[**Trello Card**](https://trello.com/c/Lj7Wu48p/1322-update-java-version-in-support-payment-api-from-8-to-11)
All apps [should move from java 8 to java 11](https://docs.google.com/document/d/1ZR-YnaXCT5_gLVmTCeGs0mWd3KPaAozPjQK8uUzHZ9w/edit?pli=1#), but this one is still on java 8. Some recent dependency upgrades like scaffeine are starting to require java 11 as well, so sticking with java 8 would mean sticking with some old dependency versions.
Have updated the github action for the CI, as well as …

Update payment api to java-11

---

.github/workflows/payment-api-build.yml
project/LibraryVersions.scala
support-payment-api/build.sbt
support-payment-api/src/main/resources/riff-raff.yaml

Reverts guardian/support-frontend#5270
support-frontend is still on java 8, so we can’t update circe just yet. Reverting this to get back to a good state, then we’ll do the payment-api java upgrade separate from the circe update.

Revert "Update payment api to java-11"

---

support-payment-api/README.md

I update the README instructions for running the `support-payment-api` app locally.
So that the next developer can successfully run the `support-payment-api` app locally at their first attempt.

docs: update README instructions for the support-payment-api app

---

.github/workflows/payment-api-build.yml
support-payment-api/build.sbt
support-payment-api/src/main/resources/riff-raff.yaml

Update Payment API  to JAVA 11 
Along with that updating the below dependencies
1) support-payment-api: Update mockito-core to 5.3.1 from 4.11.0
2) support-payment-api: Update scaffeine dependency to 5.2.0 from 4.1.0
[**Trello Card**](https://trello.com/c/Lj7Wu48p/1322-update-java-version-in-support-payment-api-from-8-to-11)
All apps [should move from java 8 to java 11](https://docs.google.com/document/d/1ZR-YnaXCT5_gLVmTCeGs0mWd3KPaAozPjQK8uUzHZ9w/edit?pli=1#), but this one is still on java 8. Some recent dependency upgrades like scaffeine are starting to require java 11 as well, so sticking with java 8 would mean sticking with some old dependency versions.
Have updated the github action for the CI, as well as which amigo recipe is used by riff raff. There’s also a debian package …

Update java 8 to 11 for payment-api

---

support-frontend/assets/pages/supporter-plus-landing/twoStepTest/firstStepLanding.tsx

This fixes an issue where users could proceed to the second step of the form in the two-step checkout test with an invalid custom amount, re-using the existing hook that validates any custom amount before opening the Apple/Google Pay interface.
[**Trello Card**](https://trello.com/c/Ei2JNRyt)

Validate custom amounts before proceeding to the second step in the two-step checkout test

---

support-frontend/assets/components/paymentRequestButton/hooks/payerDetails.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/actions.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/reducer.ts
support-frontend/assets/helpers/redux/checkout/payment/paymentMethod/state.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

This switches over the storage of country and state information for Apple and Google Pay payments from a separate section in the payment method reducer to using the address reducer that's used when a user fills out this information manually.
[**Trello Card**](https://trello.com/c/ChpoH4Qd)
This should help to address an issue where client-side validation is not correctly catching issues with a user's address information obtained from the payment request button interface. Using the address reducer means our existing validation for a user's country and state will run and should prevent form submission if there are any issues.

Make storage of country and state consistent for Apple/Google Pay payments

---

support-frontend/app/controllers/CreateSubscriptionController.scala
support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/app/wiring/Controllers.scala
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
support-frontend/assets/helpers/subscriptionsForms/submit.ts
support-frontend/test/utils/CheckoutValidationRulesTest.scala
support-models/src/main/scala/com/gu/support/workers/Products.scala
support-models/src/main/scala/com/gu/support/zuora/api/SubscriptionData.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeDecoderTest.scala
support-models/src/test/scala/com/gu/support/workers/ProductTypeRatePlansSpec.scala
support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
support-services/src/main/scala/com/gu/support/paperround/PaperRoundService.scala
support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SubscribeItemBuilder.scala
support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala

Trello Cards: 
- National Delivery: https://trello.com/c/r557VThC/65-support-frontend-backend-validates-paperround-coverage-of-provided-postcode-and-chosen-agent
- Conversion: https://trello.com/c/Z29Pxo2C/1525-validate-paperround-coverage-of-users-postcode-by-users-chosen-delivery-agent-on-server-side
The user’s choice of delivery agent needs to be validated on the server side (to guard against requests that haven’t come from the client): we need to validate that a delivery agent was provided, and that according to PaperRound it covers the user’s postcode.

Validate user’s choice of delivery agent on backend

---

support-frontend/assets/helpers/tracking/ophan.ts
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/firstStepLanding.tsx

This fixes an issue where A/B test data was not correctly associated with the new page view ID after navigating to the second step of the form. By sending the data again associated with the current page view ID we maintain the association as well as being able to track the transfer between pages.
[**Trello Card**](https://trello.com/c/SKdyDqD0)

Send AB test data to Ophan after navigating to second step

---

supporter-product-data/src/main/scala/com/gu/lambdas/FetchResultsLambda.scala
supporter-product-data/src/main/scala/com/gu/services/S3Service.scala
supporter-product-data/src/test/scala/com/gu/services/S3ServiceSpec.scala

This should fix errors writing the zuora batch request results to S3 when Zuora doesn’t include a Content-Length header in its response.

fix: Only pass content length to S3 if positive

---

support-modules/acquisition-events/build.sbt
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/eventbridge/AcquisitionsEventBusService.scala
support-modules/aws/build.sbt
support-workers/cloud-formation/src/templates/cfn-template.yaml
support-workers/src/main/scala/com/gu/services/Services.scala
support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
support-workers/src/test/scala/com/gu/support/workers/lambdas/SendAcquisitionEventSpec.scala

Following on from #4923 which created a new acquisition event bus, sqs queue and lambda to handle writing acquisition data to BigQuery, this PR update the support-workers `SendAcquisitionEvent` class to also use the event bus rather than writing to BigQuery directly.
The next step will be to do the same for the payment-api and then to trigger writes to the Kinesis stream from the event bus.
I have left a number of TODOs in the code, these will be removed in the upcoming PRs

Send acquisition events to BigQuery via the event bus

---

support-frontend/assets/helpers/tracking/__tests__/__snapshots__/acquisitionsTest.ts.snap
support-frontend/assets/helpers/tracking/__tests__/acquisitionsTest.ts
support-frontend/assets/helpers/tracking/acquisitions.ts
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
support-payment-api/src/main/scala/backend/PaypalBackend.scala
support-payment-api/src/main/scala/backend/StripeBackend.scala
support-payment-api/src/main/scala/model/AcquisitionData.scala
support-payment-api/src/main/scala/model/db/ContributionData.scala
support-payment-api/src/main/scala/model/paypal/PaypalPaymentData.scala
support-payment-api/src/main/scala/model/stripe/StripeRequest.scala
support-payment-api/src/test/scala/backend/AmazonPayBackendSpec.scala
support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
support-payment-api/src/test/scala/services/ContributionsStoreServiceSpec.scala

We want to collect zip codes for US contributions, and this change adds an optional postal code field to requests to the payment API to hold these values. It also stores users’ addresses in Zuora for supporter plus and for contributions. Finally, I’ve changed the frontend to send the postal code to the backend for single contributions. This isn’t limited to the US: if we’ve collected a postal code it’ll be sent.
I’ve gone with “postal code” rather than “zip code” because even though we’re only storing it for US contributions at the moment, we may expand that in future, and “postal code” appears to be the more general term, judging by [the Wikipedia page](https://en.wikipedia.org/wiki/Postal_code).
- Trello Card: https://trello.com/c/VSe61QY5/1436-support-checkout-back-end-changes-card-move …

Require zip code for US contributions (backend changes)

---

support-modules/supporter-product-data-dynamo/src/main/scala/com/gu/supporterdata/services/SupporterDataDynamoService.scala

The previous PR to use snapstart needed to add a new credentials provider - [see here.](https://github.com/guardian/support-frontend/pull/4869/files#diff-2b20bde739cbd13a3d9c392f38c53ca2196a6531f4a25800cf013e5e824a5096R18)
But these lambdas also use a dynamodb service which defines its credentials provider differently (using the newer aws sdk). This means we get a permissions error when using dynamodb.
Tested in CODE by creating a test user with patron subscription and running the `stripe-patrons-data-CODE` lambda:

Fix SupporterDataDynamoService permission for stripe-patrons-data

---

support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.tsx
support-frontend/assets/components/directDebit/directDebitForm/directDebitFormContainer.tsx
support-frontend/assets/components/paymentButton/directDebitPaymentButton.tsx
support-frontend/assets/helpers/customHooks/useFormValidation.ts
support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts

This hooks up the expanding direct debit form component to our existing form submission system, including form validation, and adds an additional validation step to verify the bank account details with the server before proceeding to attempt payment.
[**Trello Card**](https://trello.com/c/9TO5yLpO)
This is part of the ongoing work to migrate to a new direct debit form that matches our other payment method forms.

Check direct debit details before attempting form submission - expanding form

---

support-lambdas/bigquery-acquisitions-publisher/src/main/scala/com/gu/bigqueryAcquisitionsPublisher/Lambda.scala

The BigQueryService now needs to be shut down when it’s finished with, to close the underlying resources. When updating it recently, I missed the acquisitions-publisher, which has been intermittently throwing OutOfMemoryErrors.
- Trello Card: https://trello.com/c/J484F9Wz/1576-close-bigquery-stream-writer-resources-in-bigquery-acquisitions-publisher-lambda

acquisitions-publisher: Shut down BigQueryService

---

support-frontend/assets/helpers/redux/checkout/addressMeta/actions.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/reducer.ts
support-frontend/assets/helpers/redux/checkout/addressMeta/subscriptionsSideEffects.ts
support-frontend/assets/helpers/subscriptionsForms/formActions.ts
support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx

@undergroundquizscene spotted a bug in the national delivery checkout - when choosing a postcode with a single provider option the page hangs (and was infinitely rerendering). 
We investigated and found that the cause was the `addAddressMetaSideEffects` listener listening for changes to the `setDeliveryAgent` redux action and also calling this action in the component (when only one provider is available).
This PR instead sets the chosen delivery agent when only one option is available in the reducer.

Fix national delivery checkout: set single delivery agent in reducer, not component

---

support-frontend/app/controllers/AuthCodeFlowController.scala

On pages where an auth flow takes place on page load, the response from Gateway has a response header `X-Robots-Tag: noindex,nofollow`, which might be giving Google a hint not to index content at the end of the redirect chain.
This is an attempt to see if we can give an opposing hint in the final redirect to the content.
The test will be if the page can now be indexed.
Alternatively, bots could be being sent in a loop.  But let's see if this works first.

Reinstate indexing after auth flow on page load

---

support-frontend/assets/helpers/redux/checkout/personalDetails/state.ts

Adding the `.trim()` command to validation for both first and last name fields on the checkout.
[**Trello Card**](https://trello.com/c/kvnhy64j/1575-last-name-field-validation-in-the-checkout-to-block-an-empty-space)
Currently the client side validation does not complain when those two text fields contain only blank spaces.

Add .trim() to name validation on checkout

---

support-frontend/package.json
support-frontend/yarn.lock

Updating Zod to latest
[**Trello Card**](https://trello.com/c/hWJEIRrJ/1580-investigate-email-validation-issue-with-specific-address)
The regex used to validate emails on the currently installed version would erroneously throw errors on certain addresses, notably where the domains have subdomains. This was updated by this [PR](https://github.com/colinhacks/zod/commit/36fef58410f4b2c9e79edabae2fc567a4aee13a7).
| --- |  --- |
| ![image](https://github.com/guardian/support-frontend/assets/99400613/f2a274c6-9860-4dc0-a96a-24b5ff003c61) | <img width="558" alt="image" src="https://github.com/guardian/support-frontend/assets/99400613/0236ce01-8883-4817-b135-95bb69361075"> |

Update Zod from 3.21.4 to v3.22.2

---

support-frontend/assets/helpers/redux/checkout/address/validation.test.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts

Updating the validation message in Paper checkout when a user selects a postcode we cannot deliver to. 
[**Trello Card**](https://trello.com/c/4TtvEoqc/62-support-frontend-error-message-on-postcode-validation)
This is part of the National Delivery project, but the message applies to normal checkouts because we no longer advertise vouchers.

National Delivery - update validation message on paper postcode

---

support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.tsx
support-frontend/assets/pages/paper-subscription-landing/components/tabs.tsx

Adding new copy for Home Delivery once national delivery is available. Removes the reference to 'Greater London'.
[**Trello Card**](https://trello.com/c/kn5XlAzN/60-support-frontend-update-copy)
The copy on support frontend needs to be amended to reflect where we deliver. Currently it says Greater London.The copy on support frontend needs to be amended to reflect where we deliver. Currently it says Greater London.
Before / `ab-nationalDelivery=control`
After / `ab-nationalDelivery=variant`

Home Delivery Tab: add new copy for national delivery

---

support-frontend/assets/components/product/productOption.tsx
support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx

Adds copy to note Saturday/Sunday only home deliveries are not available outside of Greater London, for financial reasons. This change is behind the `nationalDelivery` ab test.
[**Trello Card**](https://trello.com/c/FVXTYV03/72-mark-saturday-and-sunday-delivery-options-as-only-available-within-greater-london-or-similar-wording)
We will not be offering the Saturday(-only) and Sunday(-only) delivery options for the new National Delivery product, as they’re not financially viable. There is a validation on the checkout so this note should hopefully prevent people from hitting that.
Before
After

National Delivery: Mark Saturday and Sunday home delivery options as “only available within Greater London”

---

support-frontend/app/controllers/AuthCodeFlowController.scala

This is the second attempt to get indexing working after the auth flow on checkout pages.
Reading the [documentation](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag) on the `X-Robots-Tag` header, I realise that I may have given it invalid values on the first attempt.  I've now corrected that.
> all: There are no restrictions for indexing or serving. This rule is the default value
The first attempt was at #5312.

Attempt 2 to reinstate indexing after auth flow on page load

---

cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
cdk/lib/bigquery-acquisitions-publisher.ts
support-lambdas/bigquery-acquisitions-publisher/src/main/scala/com/gu/bigqueryAcquisitionsPublisher/Lambda.scala

#4923 introduced a new SQS queue and lambda which handles writing acquisition events to BigQuery, while it had an alarm for unhandled runtime failures, any handled runtime failures were being returned to the queue via an `SQSBatchResponse`. The idea was that the queue would then pass the failed event to the dead letter queue where it could be investigated however there were two issues with this:
- the event source mapping between the queue and the lambda was not set up to report batch failures so these would have been lost.
- there was no alarm on the dead letter queue so events could be building up on there and we would not know
This PR fixes both of those issues.
As I have said in the description of the alarm, it is important from now on that when events arrive in the dead letter queue …

Add alarm to deadletter queue for bigquery-acquisitions-publisher

---

support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
support-frontend/app/config/Identity.scala
support-frontend/app/controllers/AuthCodeFlowController.scala
support-frontend/conf/application.conf
support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala

Previously, the `MaybeAuthenticatedAction` was attempting to fetch auth tokens unless the user was signed out.
Now we also check that the user isn't ***signed in*** as well, by checking for the presence of the `GU_U` cookie, which is only dropped for signed-in users.
The reason for this is that, if a person or bot (Google bot in this instance) is not signed in they go through a redirect path of:
- https://support.theguardian.com/uk/contribute
- https://support.theguardian.com/oauth/authorize
- https://profile.theguardian.com/oauth2/{id}/v1/authorize?state={state}
- https://support.theguardian.com/oauth/callback?state={state}
- https://support.theguardian.com/uk/contribute
The issue is that https://profile.theguardian.com has the `X-Robots-Tag:noindex,nofollow` header set which means that …

Ignore auth cookies if user isn't signed in

---

support-frontend/webpack.common.js

Including `@guardian/source` packages in the babel transpilation.
Source [suggest that you use certain babel plugins to have their components work](https://github.com/guardian/csnx/blob/main/libs/%40guardian/source-foundations/src/accessibility/focus-style-manager.ts#L9C14-L9C52)[^1]. This change ensures we're passing the components through those plugins.
To get support and 💰 from people using < Safari 13.
We should analyse the data post-fix to see try assess what the impact of this was. And maybe a way to test for large scale breaks like this
We are aware that this doesn't look ideal, but we have tested the functionality and will follow up visual changes once we have assessed the effort required and impact it might be having.
[^1]: I think this components doc is out of date as it works …

fix: include @guardian/source packages in babel

---

support-frontend/webpack.common.js

Reverts guardian/support-frontend#5339
Breaks the layout of the frontpage.

Revert "fix: include @guardian/source packages in babel"

---

support-frontend/assets/helpers/redux/checkout/address/validation.test.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts
support-frontend/assets/helpers/subscriptionsForms/formValidation.ts
support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx

Adding a validation to prevent taking out a Saturday or Sunday only delivery product with a postcode outside the M25.
[**Trello Card**](https://trello.com/c/FdANOd6O/69-support-frontend-error-message-on-postcode-validation-sat-sunday-delivery)
For financial reasons the Guardian cannot offer Sat/Sun deliveries outside Greater London.

National Delivery - Add Saturday/Sunday Only paper validation

---

support-frontend/webpack.common.js

Redux of https://github.com/guardian/support-frontend/pull/5339.
Transpiles `@guardian/source-foundations` `node_module` to support in Safari < v14.
The previous PR introduced a bug which seems to occur when you include `@guardian/source-react-components` to the transpilation (validated locally).
I would like to further investigate:
* Why does that transpilation create that bug?
* [Why didn't Chromatic pick up on the changes](https://www.chromatic.com/build?appId=62e115310aef0868687b2322&number=4215)?
But thought a fix first would be good.
[**Trello Card**](https://trello.com/c/PUYJmq9U/1607-safari-13-js-breaks)
**Chrome - modern OSX** 
**Safari 13.1**

fix: transpile @guardian/source-foundations for Safari < 14 support

---

support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala
support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
support-payment-api/src/main/scala/model/acquisition/AcquisitionDataRowBuilder.scala
support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
support-workers/src/test/scala/com/gu/acquisitions/BigQuerySpec.scala

I add the optional fields `postalCode`, `state` and `email` to the `AcquisitionDataRow` case class.
These new fields are sent from:
- `payment-api` producer
- `support-workers` producer
[**Trello Card**](https://trello.com/c/c6yBnLcu/366-single-contribution-record-add-fields-to-event-body-send-by-payment-api-and-support-workers-apps)
The single contribution record, I need to create in Salesforce, requires those fields if they are available.
This is the case class:
```scala
case class SalesforceSingleContributionRecord(
Amount__c: Double,
Contribution_ID__c: String,
Country_Code__c: String,
Country_Subdivision_Code__c: String, // Not available in the event yet
Currency__c: String,
Email__c: String, // Not available in the event yet
Identity_ID__c: String,
Payment_Date__c: String, …
```

feat: add fields (postalCode, state, email) to AcquisitionDataRow

---

supporter-product-data/cloudformation/cfn.yaml

Recently the support-product-data step function has been failing repeatedly without us being aware on two separate occasions. This PR adds an execution failure alarm so that if the same thing happens in future we will be notified.

Add an execution failure alarm to supporter product data

---

support-workers/src/test/scala/com/gu/zuora/Fixtures.scala

Updates a reference used in tests to be an actual Id for a Paperround retailer. 
Subscriptions generated in this test are included in the fulfilment files generated in CODE, which are being used by Paperround for testing fulfilment. Paperround tell us they can't test the files with incorrect agent Ids being used.

Use a real agent ID in National Delivery test

---

support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.tsx

Update the delivery details in the Home Delivery tab on paper checkout. Bring this in line with the new Ts & Cs. This change is behind the national delivery AB test.
[**Trello Card**](https://trello.com/c/fnq4DuIK/120-delivery-details-copy-tweaks)
Before
After

National Delivery - Delivery Details Update

---

support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/calculator/AnnualisedValueTwoCalculator.scala

As part of the work to create the new National Delivery product we need to provide an Annualised Value (AV) calculation for each configuration of the product (every day, six day and weekend).
This AV calculation is only used by the kinesis data stream which drives tickers and the Epic super mode, the calculation which is available in the data lake is specified in the [data-platform-models repo](https://github.com/guardian/data-platform-models/blob/498533bfe08ac005f95b961d87817130fb922c50/dbt/macros/annualised_value/annualised_value.sql#L4)

Add an AV calculation for the National Delivery product

---

support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala

We want to stop the IT test which creates National Delivery subs from running on a schedule so that we can more closely control what subs are created during the initial testing phase.

Stop IT test which creates National Delivery subs

---

support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala

#5357 Stopped one integration test which creates national delivery subs from running however there was another one still going. This PR sets that test to `ignored` as well but it also changes the test fixture data related to national delivery subs so that it is valid (at the current time) so that when we do reinstate those tests they shouldn't break the paperround processor

Stop National Delivery Integration test from running (take 2)

---

support-frontend/assets/components/paymentFrequencyTabs/paymentFrequencyTabsContainer.tsx
support-frontend/assets/helpers/redux/commonState/reducer.ts
support-frontend/assets/helpers/redux/commonState/selectors.ts
support-frontend/assets/helpers/redux/commonState/state.ts
support-frontend/assets/helpers/redux/utils/setup.ts
support-frontend/assets/pages/supporter-plus-landing/setup/setUpRedux.ts
support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx

Support checkout: Read the `defaultContributionType` and `displayContributionType` from RRCP Amounts config
[**Trello Card**](https://trello.com/c/EY0v3UWy/1565-default-to-annual-remove-monthly-support-checkout-read-the-defaultcontributiontype-and-displaycontributiontype-from-rrcp-amounts)
Currently the payment frequency tabs and the default tab on the Support Checkout are rendered based on the values in  `common.settings.contributionTypes` from Redux state.
However, the amounts cards rendered on the support checkout for each tab are defined in amounts test config set in RRCP, this config is written to S3 as JSON, and then read by support-frontend and made available in the client on `window.guardian.settings.amounts`.
`window.guardian.settings.amounts` is an array of amounts tests. Each …

Read the defaultContributionType and displayContributionType from RRCP Amounts config in Support Checkout

---

support-frontend/app/controllers/DigitalSubscriptionController.scala
support-frontend/app/views/main.scala.html
support-frontend/app/views/subscriptionCheckout.scala.html

We're stopping search engines indexing the `/{country}/kindle` as a test to see if that's where we're getting trickle of subs from.
We do this by adding the [`<meta name="robots" value="noindex" />`](https://developers.google.com/search/docs/crawling-indexing/block-indexing#meta-tag) tag.
All other routes that use `DigitalSubscriptionController.digital` are redirected in Fastly (no link as it's not in CVS) so unaffected by this.

feat: add noindex to digital subscription (Kindle) pages

---

support-e2e/playwright.local.config.ts
support-e2e/tests/monthlyContribution.test.ts

- forces the e2e tests to be running on the `ab-twoStepCheckoutWithNudgeBelow=variant_a`
- refactors a few of the [locators](https://playwright.dev/docs/locators#locate-by-text) to follow [Playwright's advice of "prioritizing user-facing attributes and explicit contracts such as page.getByRole()"](https://playwright.dev/docs/locators#locating-elements)
[**Trello Card**](https://trello.com/c/1F4DgCyB/1621-put-2-step-variant-live-to-100-of-audience)
This is because we're swapping to the 2 step checkout as default, but will allow us to work on the tests in parallel while doing so.

E2E tests: 2 step checkout

---

.vscode/settings.json

Ignores the `target` directories for when we're using [Metals](https://scalameta.org/metals/) for Scala.
This is a default set by Metals so anyone using it will have this automatically appended.

fix: ignore **/target for VS Code when using metals

---

support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
support-frontend/assets/helpers/forms/checkouts.ts

We need to change the wording for One-off contributions from Single to "One-time" in the checkout tab.
[**Trello Card**](https://trello.com/c/0ABxipb3/1619-changing-single-to-one-time-on-checkout-tabs-support-frontend)
Following UXR, We would like to test changing the word “single” on the checkout to “One-time”.
This would not be a test, this would be global.
- [x ] No
##  Before Change

Change Single to One-Time on checkout tabs (support frontend)

---

support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx

This is to update wording form One-Time to One-time in ContributionsOrderSummary "Your Support" to keep it consistent with the choice cards
- [x ] No

Update the one-Time to one-time in ContributionsOrderSummary

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
support-frontend/window.d.ts

Proposal: Release a disabled AB test canMakePaymentsWithActiveCard to PROD. Force myself in to the AB test to see whether the `window.ApplePaySession.canMakePaymentsWithActiveCard` resolves with `true` on `support.theguardian.com`. I've tested on CODE and it resolved as `false`. Once my test is complete I'll revert this change.

Temporary disabled AB test to test canMakePaymentsWithActiveCard

---

support-frontend/assets/components/checkoutTopUpAmounts/checkoutTopUpAmountsContainer.tsx
support-frontend/assets/helpers/redux/checkout/product/selectors/selectedAmount.ts
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/secondStepCheckout.tsx

Fix issue where other amount field hidden when returning to Page 1 from Page 2, having previously been visible.
[**Trello Card**](https://trello.com/c/kArMJ9aw/1643-2-step-checkout-other-amount-field-hidden-when-returning-to-page-1)
On Page 1 of the 2-step checkout (any tab) click the “Choose your amount” CTA and enter a value in the other amount field and proceed to Page 2.
On Page 2 click the “Change” CTA in the order summary component.
When you return to Page 1 the “Choose your amount” CTA is not highlighted and the other amount field is hidden.
This is not desired behaviour. We would like the “Choose your amount” CTA to be highlighted and the other amount field visible, with the previously entered amount in it.
- [x ] No

Fix Other amount field hidden when returning to Page 1

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
support-frontend/assets/components/checkoutNudge/checkoutNudge.tsx
support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
support-frontend/assets/components/priceCards/priceCardsContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
support-frontend/assets/helpers/redux/checkout/product/selectors/productType.ts
support-frontend/assets/helpers/redux/commonState/selectors.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx

Adding dynamic text to the checkout nudge component that displays the amount currently selected on single contributions
[**Trello Card**](https://trello.com/c/cf4kT5iL/1590-test-make-it-annual-nudge-development)
https://github.com/guardian/support-frontend/assets/2510683/0e057e23-e979-4dd3-9f6d-3a39c336cb9b

Add dynamic checkout nudge

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
support-frontend/window.d.ts

Reverts guardian/support-frontend#5380
I've run the test and concluded `support.theguardian.com` is not set-up to use `canMakePaymentsWithActiveCard`.
Tested on `PROD` using an iPhone with Apple Pay enabled, `canMakePaymentsWithActiveCard` resolved with `false`.

Revert "Temporary disabled AB test to test canMakePaymentsWithActiveCard"

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx

Rounding the amount in the benefits container to two fixed decimal places
Currently, if the user enters an invalid amount (i.e. with more than 2 decimal places) in the *choose amount* field, it will be shown in the benefits list below. 
| --- | --- |
| <img width="511" alt="image" src="https://github.com/guardian/support-frontend/assets/99400613/0314538d-9e00-47bb-b1ec-5d85dbbf49e6"> | <img width="520" alt="image" src="https://github.com/guardian/support-frontend/assets/99400613/20a80f1f-a177-4734-a6f8-bbae8ccf3ef4"> |

Round selected amount in benefits container to 2 decimal places

---

support-frontend/assets/components/ticker/ticker.tsx
support-frontend/assets/components/ticker/tickerContainer.tsx
support-frontend/assets/components/ticker/tickerStyles.ts
support-frontend/assets/components/ticker/types.ts
support-frontend/assets/helpers/abTests/abtestDefinitions.ts
support-frontend/assets/helpers/async/fetch.ts
support-frontend/assets/helpers/campaigns/campaigns.ts
support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
support-frontend/assets/helpers/redux/checkout/payment/payPal/thunks.ts
support-frontend/assets/helpers/redux/checkout/personalDetails/thunks.ts
support-frontend/assets/helpers/redux/user/thunks.ts
support-frontend/assets/pages/subscriptions-redemption/api.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
support-frontend/stories/checkouts/Ticker.stories.tsx

This adds a new and updated ticker component for the 2023 EOY US campaign and adds it to the checkout, behind the existing campaign switch.
[**Trello Card**](https://trello.com/c/XgWlzhwj)
There is a desire to revive the old campaign tickers used in previous years to track contributions during specific periods. The existing ticker component uses some difficult-to-maintain SCSS styles, is tightly coupled to the data fetching mechanism, is an older style class component, and is not especially screen reader accessible; the new component addresses these issues.

Set up new US campaign ticker

---

support-modules/acquisition-events/build.sbt

Update google-cloud-bigquery to 2.34.0  from 2.31.2 to fix org.json:json snyk vulnerability issue 
[**Trello Card**](https://trello.com/c/CO9Rba4g/1652-high-severity-snyk-vulnerability-support-frontendorgjsonjson)
org.json:json came up as a high severity vulnerability and this is a transitive dependency of com.google.cloud:google-cloud-bigquery and com.amazon.pay:amazon-pay-java-sdk@3.6.2
Updating com.amazon.pay:amazon-pay-java-sdk@3.6.2 to the latest version(3.7.1)  still has this as a vulnerability.So updating google-cloud-bigquery alone.

Update google-cloud-bigquery to 2.34.0 to fix org.json:json snyk vulnerability issue 

---

support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx
support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx

This PR refactors the delivery provider selection for newspaper home delivery outside London. From a dropdown to a radio group. This allows us to show information about the delivery method and a summary of each provider. 
The summary and delivery method are provided by the PaperRound API. There are three possibilities for delivery method: "Green delivery", "Green options" (both show messages) or anything else (display nothing).
[Figma](https://www.figma.com/file/IlRRbyvX3mxkytgQMnZgpR/Paper-Round-M25-(Minor-Updates)?type=design&node-id=286-815&mode=design&t=mG9X35HybOMlei9K-0)
[**Trello Card**](https://trello.com/c/VTW1j7Z3/123-delivery-options-dropdown-to-display-radio-buttons-with-green-options)
Single option
Before
After
Multiple options
Before
After

National Delivery - Add Provider Summary and Delivery Method

---

support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx

Hotfixing an issue caused by a [previous PR](https://github.com/guardian/support-frontend/pull/5393) where amounts displayed in the benfits container are rounded to two decimal places.
The previous PR had the unintended effect of converting whole numbers to floats with two decimal places. So **£95** became **£95.00** which is unnecessary.
| ------- | ---- |
| <img width="518" alt="image" src="https://github.com/guardian/support-frontend/assets/99400613/5ab3fa67-122c-4f61-8cff-03518c65b6ae"> | <img width="515" alt="image" src="https://github.com/guardian/support-frontend/assets/99400613/aaba8a4f-8d98-44a2-a0db-2028334dd133"> |

Hide decimals when they're unnecessary in benefits list

---

support-frontend/assets/pages/supporter-plus-landing/twoStepTest/checkoutScaffold.tsx

Resizes the text on the left to match the designs as per request from the designers.
This was spotted as part of the US EOY 2023 work.
|--------|-------|
| ![before][before] | ![before][after] | 
[before]: https://github.com/guardian/support-frontend/assets/31692/7fec79a3-9b9f-44ec-bfdf-2a6369c014a4
[after]: https://github.com/guardian/support-frontend/assets/31692/dfb6d00a-647c-4afc-8434-81d2590942cf

fix: make subHeading on left bar of contributions checkout 17px

---

support-frontend/assets/components/thankYou/thankYouModuleData.tsx

Hiding the “Set my reminder CTA”  on Support checkout once a reminder has been set up
[**Trello Card**](https://trello.com/c/2UvnYN8i/1658-support-checkout-ty-page-reminders-component-submitted-state)
We show a reminders component on the Support Checkout TY Page, for Single Contributions only. We should hide the “Set my reminder CTA” once the reminder has been successfully set-up. Currently it remains visible and active.
- [ x] No

 Fix Support Checkout TY Page - Reminders Component  showing up after  setting a reminder

---

support-frontend/assets/pages/supporter-plus-landing/components/landingPageHeading.tsx
support-frontend/assets/pages/supporter-plus-landing/twoStepTest/checkoutScaffold.tsx

- Adding line breaks to the heading for US EOY 2023 campaign
- Changing the copy
It would be good to have a think about how we might support this amount of copy control if it were configurable.
| --- | --- |
| ![Before][before] | ![After][after] |
[before]: https://github.com/guardian/support-frontend/assets/31692/b60e8cac-9b17-4258-84fc-e77ec2f8fae7
[after]: https://github.com/guardian/support-frontend/assets/31692/aeba7190-c4f2-4aca-b8ec-c6f3dc794e2d

fix: change US EOY content and do correct line breaks on heading

---

support-frontend/assets/helpers/campaigns/campaigns.ts

We allow yourself to put yourself into a campaign via the hash `#settings.switches.campaignSwitches.${campaignCode}=On`.
This will allow us to share these links with other colleagues outside of engineering who don't have access to editing the [local switch configuration](https://github.com/guardian/support-frontend/blob/main/support-frontend/conf/DEV.public.conf#L48). 
e.g. `https://support.theguardian.com/us/support#settings.switches.campaignSwitches.usEoy2023=On` should enable [the `usEoy2023` campaign](https://github.com/guardian/support-frontend/pull/5414). 
With this config
```JSONC
"campaignSwitches": {
"description": "Campaign switches",
"switches": {
// ...
"usEoy2023": {
"description": "EOY US 2023",
"state": "Off"
}
}
}
```
We would see this:
But can enable the campaign and see …

feat: allow enabling of campaigns via URL hash

---

support-frontend/assets/helpers/redux/checkout/payment/existingPaymentMethods/thunks.ts
support-frontend/assets/helpers/redux/user/thunks.ts

Changing the logic ever so slightly to avoid non-null assertions, mainly because they keep coming up in PR reviews which was bothering me slightly (and you should avoid them).
If we have the current types
```ts
authWithOka = true | false
accessToken = string | undefined
```
We could feasibly, but not practically, land up with
```ts
if (false && !undefined) return []
// which equates to
if (false && false) return []
```
Which would then continue with `accessToken = undefined`. In the new case if either are false, we exit early.
Mainly though, we don't get these errors any more:

fix: change Okta if to avoid non-null assertions

---

support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx

Making the green label for delivery providers outside London (ie the "Green options" in the image below) match case insensitive. 
We show something if the delivery provider response's `deliveryMethod` matches 'Green options' or 'Green delivery'.
I noticed in production the API was returning "Green Delivery" instead of "Green delivery".

Make delivery provider Green label case insensitive

---

support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx

Minor fix from #5428, preserving the case from the api response in the label
Before
After

fix: green label should preserve case from api response

---

support-frontend/assets/helpers/redux/checkout/address/validation.test.ts
support-frontend/assets/helpers/redux/checkout/address/validation.ts

This PR adds a validation for UK postcodes in the home delivery checkout. If it is a home delivery subscription we should validate that it is a valid UK postcode.
[**Trello Card**](https://trello.com/c/zXpiY8uV/130-postcode-input-during-paperround-call-causes-failure)
There was a race condition in the checkout for national delivery subscriptions - 
- Enter a postcode, and then change it before the call to get the delivery agents finishes so that it’s no longer a valid postcode (e.g. by adding a space at the end)
- Now when you submit the form the postcode validation won’t complain, because if you’ve chosen a delivery agent it assumes the postcode is correct
- The server side validation would fail, because the postcode and the delivery agent do not match.
This PR fixes this behaviour by …

Add postcode validation for home delivery

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

Whilst looking at Quantum Metric with @LAKSHMIRPILLAI and @paul-daniel-dempsey we noted that despite viewing the Support Checkout (https://support.theguardian.com/uk/contribute) we were being allocated to the `nationalDelivery` AB Test. The `nationalDelivery` AB test is for the Paper checkout flow only so we shouldn't allocate users across the entire site into this test - as it could potentially lead to misreporting of data. I noted the same issue for the other AB tests `supporterPlusOnly` and `makeItAnnualNudge`.
To remedy this I've add a `targetPage` prop to all these AB tests so:
- `supporterPlusOnly`/`makeItAnnualNudge` run only on the Support Checkout and Thank You page.
-  `nationalDelivery` runs only on the Newspaper Landing Page, Checkout and Thank You page.
I had to update the …

Add targetPage to AB test definitions

---

support-frontend/assets/helpers/abTests/abtest.ts
support-frontend/assets/helpers/abTests/helpers.ts

Adds a check to determine the source of an incoming user (`GOOGLE_AMP, APPLE_NEWS`) and enforces the requirement to show these users the appropriate regional data in the amounts card.
[**Trello Card**](https://trello.com/c/JtwmCKxH)
Epics shown on Google AMP and Apple News articles will always include `single`, `monthly` and `annual` payment options. We need to ensure that the amounts card shown on the landing page similarly includes all payment options as part of a seamless user journey.
Not required - will not affect visual output
Not required - will not affect visual output

AN and AMP sources should only use regional amounts tests

---

support-frontend/assets/pages/digital-subscriber-checkout/components/billingPeriodSelector.tsx

Update Digital checkout to handle no promo code
[**Trello Card**](https://trello.com/c/n5Rk3bwE/1670-editions-update-digital-checkout-to-handle-no-promo-code)
Currently the “Kindle” Checkout applies a promotion to the pricing cards if a promoCode query string is applied in the URL, eg. https://support.theguardian.com/uk/kindle?promoCode=DLESNCWON.
When we have a valid promoCode in the URL the promotion is available in the promotions array at window.guardian.productPrices.[REGION].NoFulfilmentOptions.NoProductOptions[FREQUENCY].promotions
When no promoCode is applied the checkout currently still renders the “% off regular monthly price” regardless of whether there’s a promo applied or not. We should hide this if no promo is applied, we also don’t want to show the “£9.74 per month for the …

 Update Digital checkout to handle no promo code

---

support-frontend/app/controllers/PaperRound.scala
support-frontend/test/utils/CheckoutValidationRulesTest.scala
support-models/src/main/scala/com/gu/support/paperround/PaperRound.scala

PaperRound appear to have removed this field from their responses, resulting in a decoding failure when the support-frontend backend tried to parse the response from their /coverage endpoint.
Removing the field from our code should prevent the decoding failure.

Don’t use top-level .message field

---

support-models/src/main/scala/com/gu/support/paperround/PaperRound.scala

This field has been removed by PaperRound from the API, presumably because they didn’t intend for us to rely on it. We weren’t actually _using_ the field, so we shouldn’t have been parsing it in the first place!
At the moment this is breaking the sending of thank you emails from support-workers, so this commit should fix that by no longer parsing it.

AgentsEndpoint.Response: Remove message field

---

.github/workflows/deploy-fastly-snippets.yaml

Removes the `snippets` directory in filepath.
Sorry for the repeat here, I have run `cat .github/workflows/deploy-fastly-snippets.js` to validate this one.
And even a screenshot to prove it:

fix typo: snippets/deploy-fastly-snippet => ./deploy-fastly-snippets

---

support-frontend/assets/components/ticker/tickerStyles.ts
support-frontend/assets/helpers/campaigns/campaigns.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx

This repositions the campaign ticker below the price cards and adds the desired headline ready for the campaign's release. The headline is visually hidden at the desktop breakpoint and above, but will still be read by screen readers.
[**Trello Card**](https://trello.com/c/vNQgmtE5)

Re-position the campaign ticker and amend headline ready for release

---

support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionRouter.tsx

Supporting the `/{countryId}/kindle/thankyou` route.
This bug was introduced here: https://github.com/guardian/support-frontend/pull/5433
So we don't see a blank page when someone pays for a digital subscription.
Thanks @GHaberis for spotting and reporting.

fix: support kindle thankyou route

---

support-frontend/assets/helpers/abTests/abtestDefinitions.ts

Deactivating the make it annual nudge for US market
The A/B test for make it annual nudge in the US performed poorly

Deactivate us make it annual nudge

---

support-frontend/assets/helpers/page/analyticsAndConsent.ts
support-frontend/assets/helpers/tracking/acquisitions.ts
support-frontend/assets/helpers/tracking/quantumMetric.ts

Send Acquisition Data to Quantum Metric
[**Trello Card**](https://trello.com/c/ES1hCYiJ/1663-quantum-metric-send-acquisition-data)
QM have suggested passing info from the acquisitionData query param via the sendEvent function call so we can partition results based on the various bits of information in this query param. 
acquisitionData Source
Captures the acquisitionData source as defined within the URL query string parameters.
QuantumMetricAPI.sendEvent(94, 0, "Insert Source here");
acquisitionData ComponentId
Captures the ComponentId from the acquisitionData query string parameter.
QuantumMetricAPI.sendEvent(95, 0, "Insert ComponentId here");
acquisitionData ComponentType
Captures the ComponentType from the acquisitionData query string parameters.
QuantumMetricAPI.sendEvent(96, 0, …

Send Acquisition Data-Quantum Metric

---

cdk/lib/__snapshots__/frontend.test.ts.snap
cdk/lib/frontend.ts
support-frontend/app/controllers/PaperRound.scala
support-frontend/app/wiring/Controllers.scala
support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala

- Add a metric for successes and one for failures
- Add an alarm on the failure metric
- Include an alarm in CODE so we get a heads up if it breaks in CODE first (as it did recently)
For national delivery, the support-frontend server has an endpoint that looks up postcode coverage with PaperRound by calling their API. If an error is encountered while doing this lookup, there’s currently no alert: a 500 is returned to the client, but that’s it (the 500 may cause an alert if it’s a big enough proportion of all requests, but it probably won’t be).
Adding a metric (and associated alarm) for failed calls to this endpoint will help us catch problems more quickly.
- Trello Card: https://trello.com/c/RUsF7U7e/479-add-metric-for-errors-checking-a-postcodes-coverage-with-paperround
- I ran this …

Add alarm for failures getting delivery agents

---

support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts

Add client-side validation  to prevent form submission if captcha hasn’t been selected with Direct Debit
[**Trello Card**](https://trello.com/c/VmdWC8sR/1425-look-into-captcha-validation-failures-not-preventing-support-workers-execution)
If the  getRecaptchaError  is not included in the  getDirectDebitFormErrors , it allows the form submission even if there is no recaptcha  selected  in Direct debit form when all the direct debit details/ fields are correct.
- [x ] No
###  (Before change)-Even if the recaptcha in the Direct debit section was not selected, the user was allowed to submit the form and the support workers successfully executed the request.
The user was shown -"Please check the 'I'm not a robot' " checkbox error message
## Screenshots 
###  (After change)- The user won't be …

Add client-side validation to prevent form submission if captcha hasn’t been selected with Direct Debit

---

support-frontend/assets/helpers/campaigns/campaigns.ts
support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx

This enables the ticker to show up on the Australia checkout for their end-of-year campaign. It also updates our campaign module to enable multiple campaigns to be run simultaneously
[**Trello Card**](https://trello.com/c/oGJcu4sv)

Add EOY campaign ticker for Australia to the S+ checkout

---

support-frontend/assets/pages/supporter-plus-landing/twoStepTest/checkoutScaffold.tsx
support-frontend/package.json
support-frontend/yarn.lock

This PR undoes a temporary fix that was made to introduce a "Privacy settings" link to the Support checkout's footer, when clicked this launches the CMP: https://github.com/guardian/support-frontend/pull/5442. This change was necessary as the `FooterLinks` component from `source-react-components-development-kitchen` wasn't flexible enough to support links other than anchor tags linking through to pages.
The `FooterLinks` component from `source-react-components-development-kitchen` has now been updated to support buttons with onClick handlers, which means we revert to using it again, making the most of this new feature: https://github.com/guardian/csnx/pull/940.

Use FooterLinks from source-react-components-development-kitchen on Support checkout

---

support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
support-frontend/assets/helpers/abTests/abtestDefinitions.ts

This removes the US-specific dynamic nudge test and adds the US to the global test, as requested.
[**Trello Card**](https://trello.com/c/w7TVgx9F)

Move the US into the global nudge test

---

.github/workflows/deploy-fastly-snippets.js
support-frontend/conf/fastly-snippets/vat-compliance-redirects-error.vcl
support-frontend/conf/fastly-snippets/vat-compliance-redirects-recv.vcl

Any users landing on the subscription checkout route should be redirected them to the S+ checkout, where they will be allocated in the VAT compliant amounts test.
[**Trello Card**](https://trello.com/c/lzATPJUo/1698-editions-prevent-users-in-vat-impacted-countries-from-purchasing-digi-subs)
This is to prevent users in VAT impacted countries from purchasing Digital Subscriptions
- [X ] No

Changes to redirect users in VAT impacted countries

---

support-frontend/assets/pages/subscriptions-landing/components/subscriptionsLandingContent.tsx

Date correction offer to appear on Sub Landing Page until 30/11/2023
This matches promocode GWBLACKFRIDAY
[**Linked BlackFriday PR**](https://github.com/guardian/support-frontend/pull/5417) 
[**Trello Card**](https://trello.com/c/vqW6PQYb/1651-black-friday-gw-landing-page-changes)

Black Friday Appeal Subscriptions Landing Closing Date

---

.github/workflows/stale.yml

Adds the [stale action](https://github.com/actions/stale) to the repo.
While we don't have a massive issue with tonnes of unclosed issues and PRs I was going to go asking folk if we can close some of the older ones to reduce noise and remembered - there's an action for this.
This will hopefully allow us to glance at the PRs number and be happy knowing that's how many things are in review.
We could then use something like [PR Announcer](https://github.com/guardian/actions-prnouncer) too.

feat: add actions/stale to marke PRs and issues as stale after 30 days

---

support-frontend/conf/fastly-snippets/vat-compliance-redirects-error.vcl
support-frontend/conf/fastly-snippets/vat-compliance-redirects-recv.vcl

Using `obj.http.Location` to send the `Location` header as per the examples
[Here's a fiddle to prove it](https://fiddle.fastly.dev/fiddle/6db36311) for now until we have more robust testing.

Redirect on obj.http.Location for VAT compliance redirects

---

support-e2e/tests/gwCheckout.test.ts

Fix case typo in import statement in GW e2e test
Before            |  After
:-------------------------:|:-------------------------:

fix case typo in import statement

---

support-frontend/app/controllers/DigitalSubscriptionController.scala
support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionRouter.tsx
support-frontend/conf/routes

Replace the `/kindle` route with a new route `/subscribe/digitaledition` as requested by stakeholders. This route loads the Digital Subscription checkout.
[**Trello Card**](https://trello.com/c/wLKDl31x/1715-editions-enable-subscribe-digital-route-in-prod-remove-noindex-restriction)

Replace /kindle route with /subscribe/digitaledition

---

support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionLandingPage.tsx

Making sure the country selector points to the `digitalsubscription` route. This is a hangover from some refactoring.
**Before**
**After**

Swap `kindle` for `digitaledition` on country selector

---

.github/workflows/deploy-fastly-snippets.yaml

Ensures that both inputs are required and default to true.
These default to true as that is the expected behaviour, with the option to opt-out for testing.

fix: Add `default: true` to delete-snippets on deploy-fastly-snippets action

---

support-frontend/app/utils/CheckoutValidationRules.scala
support-frontend/assets/components/paymentButton/digitalSubscriberPaymentButtonContainer.tsx
support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionLandingPage.tsx
support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts

Small bits of tidy up following the deprecation of the "Kindle" route, and the repurposing of the associated checkout for putting Digital Subscriptions (for the Edition) back on market.

Remove referrences to the "Kindle" checkout
