- .github/workflows/stripe-patrons-data.yml
PR actions-riff-raff v3: https://github.com/guardian/support-frontend/pull/5468
Associated file input/permissions that require changing alongside above PR (stripe-patrons-data will fail).
Bumps [guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff) from 2 to 3.
<details>
<p><em>Sourced from <a href="https://github.com/guardian/actions-riff-raff/releases">guardian/actions-riff-raff's releases</a>.</em></p>
<blockquote>
<h2>v3.0.0</h2>
<h1><a href="https://github.com/guardian/actions-riff-raff/compare/v2.2.4...v3.0.0">3.0.0</a> (2023-11-20)</h1>
<ul>
<li>Add a pull request comment with quick links to deploy with Riff-Raff (<a href="https://redirect.github.com/guardian/actions-riff-raff/pull/85">#85</a>)</li>
</ul>
<h2>BREAKING CHANGES</h2>
<p>A new required input …
> actions-riff-raff v3  setup changes

- support-e2e/package.json
- support-e2e/tests/recurringContributions.test.ts
- support-e2e/yarn.lock
Update version of playwright and browserstack dependancy to be happy not passing through 'allowDownloads' property to the test config when running the tests via browserstack. 
Change select element selection in test from 'fill' to 'selectOption'. 
Update assertion for 1st page of recurring contribution checkout to look for either 'pay  per X' OR 'Support us with  per X' instead of just the 'pay' string
> playwright selector, assertion and config fixes

- support-frontend/package.json
- support-frontend/webpack.common.js
- support-frontend/yarn.lock
Installing and configuring the circular-dependency-plugin for webpack
[**Trello Card**](https://trello.com/c/hnt5M6GX/1719-fix-cyclical-file-dependencies)
This is a really helpful plugin that finds and highlights circular dependencies and outputs them in the terminal log. We have a larger task to remove those, and this is foundational to that challenge. 
Run the dev server, you should see extra output in the terminal that highlights all circular dependencies
This should only affect the webpack dev server, it might slow build down a little but we can always remove it later when the problematic dependencies have been removed as ESLint will ensure that no new ones are created in future.
> Install and configure circular dependency plugin

- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
Currently the retention period on the BigQueryAcquisitionsPublisher dead letter queue is the default 4 days. This doesn't give much time to investigate and redrive any failures so this PR increases it to the maximum 14 days.
> Big query publisher deadletter retention

- support-frontend/assets/components/checkoutNudge/checkoutNudgeContainer.tsx
We should show the Dynamic nudge to all users in countries not affected by the VAT compliance issue, right now we're doing the opposite.
> Show dynamic nudge to all on one-time tab except those in VAT affected countries

- supporter-product-data/cloudformation/dynamo-tables.yaml
The `supporter-product-data-tables-CODE` CloudFormation stack cannot currently be updated due to the following error:
`Template error: instance of Fn::GetAtt references undefined resource DevOrUatTable`
I think this is due to a small omission from https://github.com/guardian/support-frontend/pull/4938, so this PR is just tidying up.
I don't think the Dynamo CFN changes in https://github.com/guardian/support-frontend/pull/4938 have ever been applied. This means that (manually) deploying this change will also deploy the changes in https://github.com/guardian/support-frontend/pull/4938/files#diff-99f29580ec61fd20b364bd7ae277583f1e36b8c6e192942a19f0b12e7db32495. 
~⚠️ Because the [logical id](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html#resourc …
> Fix CFN template for supporter-product-data

- .github/workflows/support-lambdas-build.yml
- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
- project/plugins.sbt
- stripe-patrons-data/build.sbt
- support-lambdas/acquisition-events-api/build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-lambdas/acquisitions-firehose-transformer/cfn.yaml
- support-lambdas/bigquery-acquisitions-publisher/build.sbt
- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/build.sbt
- support-lambdas/stripe-intent/cfn.yaml
- support-payment-api/build.sbt
- support-workers/build.sbt
- supporter-product-data/build.sbt
This PR is to upgrade java version for support-lambdas from 8 to 11 and update  ch.qos.logback:logback-classic to 1.4.13
[**Trello Card**](https://trello.com/c/dmkZYn1T/1720-high-snyk-vulnerability-in-support-frontend-denial-of-service-dos-affecting-chqoslogbacklogback-classic-package-versions-1412)
This was flagged as a HIGH SNYK vulnerability in support-frontend:  Denial of Service (DoS) Affecting ch.qos.logback:logback-classic package, versions 1.4.13
Notes:
In order to make the  update of logback-classic to 1.4.13, support lambdas must be in Java 11 as the 1.4.x series requires Java 11 at build time and at runtime. [Refer.](https://github.com/qos-ch/logback)
Have made the  update logback-classic to 1.4.13  in
1. acquisition-events-api
2. bigquery-acquisitions-publisher
3. …
> Upgrade java 8 => java 11 for support-lambdas and Update  ch.qos.logback:logback-classic to 1.4.13

- supporter-product-data/cloudformation/dynamo-tables.yaml
This PR allows us to start backing up these DynamoDB tables using https://github.com/guardian/aws-backup. For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit) and this [audit](https://docs.google.com/spreadsheets/d/1gNh_yQ3GVo_dVAemgZfRZM_MaQxep6_x-hzrhvVBGHY/edit#gid=1523470588) that @guardian/devx-reliability have been working on with Heads of Engineering.
We will be able to recover (most) data stored in this table in the unlikely event that it is deleted. 
As far as I can tell, this CloudFormation stack is deployed manually[^1].
If people are happy with this change in principle, I will:
[^1]: It looks like [some of this infrastructure is deployed via …
> Enable nightly backups for SupporterProductData tables

- support-lambdas/it-test-runner/build.sbt
Based on https://github.com/guardian/support-frontend/pull/5507, we think that we have a dependency issue where
* `support-workers` is dependent on `it-test-runner` when running in CI
* `it-test-runner` is on `logback-classic` `1.4.13` 
* `support-workers` doesn't work on `logback-classic` `1.4.13`
We are unsure of how to test this locally, but would like to get the tests green before working on a longer term fix and exploring how we could test this more thoroughly locally.
> fix: downgrade it-test-running logback-classic dep to 1.4.7

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtest.ts
Regional amounts test configurations are still used even if `isLive: false`. This is because there is always a regional amounts configuration, and the control should be used if the AB test is not live.
Currently, if `isLive: false`, the checkout page may still show the variants.
This PR fixes this by ensuring only the control is used in this case.
> Fix isLive flag use for regional amounts tests

- support-frontend/assets/pages/digital-subscriber-checkout/components/paymentTsAndCs.tsx
Digital Edition TsAndCs, change 'Manage My Account' from profile to manage. Profile won't send you through to manage unless you came from there.
|before|after|
|--------|---------|
|http://profile.theguardian.com/|http://manage.theguardian.com/|
> Editions : TsAndCs Manage My Account Url amended

- support-lambdas/acquisitions-firehose-transformer/README.md
- support-lambdas/acquisitions-firehose-transformer/build.sbt
Part of: https://github.com/guardian/support-frontend/issues/5532
Upgrades `logback-classic` to 1.3.14. We are sticking to 1.13 rather than 1.14 as 1.14 requires Java 11, and we would like to decouple the Java 8 => Java 11 upgrade.
[You can read about `logback-classis`'s support here](https://github.com/qos-ch/logback?tab=readme-ov-file#java-ee-and-jakarta-ee-versions).
Tested locally on Java 8 via `testOnly com.gu.acquisitionFirehoseTransformer.LambdaSpec`
> fix: upgrade logback-classic to 1.3.14 in aquisition-firehose-transformer

- support-lambdas/it-test-runner/build.sbt
Part of: https://github.com/guardian/support-frontend/issues/5532
Upgrades `logback-classic` to 1.3.14. We are sticking to 1.13 rather than 1.14 as 1.14 requires Java 11, and we would like to decouple the Java 8 => Java 11 upgrade.
[You can read about `logback-classis`'s support here](https://github.com/qos-ch/logback?tab=readme-ov-file#java-ee-and-jakarta-ee-versions).
This was tested on CODE.
> fix: upgrade logback-classic to 1.3.14 in it-test-runner

- support-e2e/browserstack.config.ts
- support-e2e/package.json
- support-e2e/playwright.browserstack.config.ts
- support-e2e/tests/gwCheckout.test.ts
- support-e2e/tests/landingPages.test.ts
- support-e2e/tests/newspaperCheckout.test.ts
- support-e2e/tests/oneOffContributions.test.ts
- support-e2e/tests/recurringContributions.test.ts
- support-e2e/tests/utils/afterEachTest.ts
- support-e2e/tests/utils/paypal.ts
This pr fixes the problem where browserstack was not reporting the status of the tests that were just run.
The paypal form filling in function has been changed to use id selectors instead of labels to address an issue where the paypal form was displaying in dutch, although this issue idsprobably also mitigated by selecting the geo location in the browserstack test config (also in this pr).
The paypal test user credentials have been updated so that these tests do not use a shared account that may be locked out if someone enters the wrong password too many times.
The browserstack automate runs are now labelled with the latest commit id and the date/time so that each run is unique and more discoverable.
> E2E paypal and browserstack fixes

- support-lambdas/it-test-runner/build.sbt
Reverts guardian/support-frontend#5535
I can see the `A needed class was not found. This could be due to an error in your runpath. Missing class: Could not initialize class com.gu.config.Configuration` when running these manually.
> Revert "fix: upgrade logback-classic to 1.3.14 in it-test-runner"

- support-frontend/package.json
- support-frontend/webpack.common.js
Removing the circular dependencies plugin from webpack.
[**Trello Card**](https://trello.com/c/hnt5M6GX/1719-fix-cyclical-file-dependencies)
In theory, we no longer need this plugin and might as well remove it to speed up the local build process. It was helpful to highlight the circular dependencies we had that were able to slip past eslint by ignoring rules, but they are now fixed and we should not be merging any PRs that ignore rules in the future which will prevent this from happening again and therefore make this plugin redundant. 
This is a change to the build process, but should only affect the local dev server builds. If the build passes on PROD and locally, it should be fine.
> Remove circular dependencies plugin

- support-frontend/app/controllers/DigitalSubscriptionController.scala
- support-frontend/app/controllers/DigitalSubscriptionFormController.scala
- support-frontend/assets/components/checkoutHeading/checkoutHeading.tsx
- support-frontend/assets/helpers/rendering/ssrPages.ts
- support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionLandingPage.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionRouter.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/preRenderDigitalSubscriptionLandingPage.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/landingPageHeading.tsx
- support-frontend/assets/pages/supporter-plus-landing/preRenderSupporterPlusLandingPage.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
- support-frontend/stories/checkoutLayout/CheckoutHeading.stories.tsx
CORRECTION REQUESTED 13/1/23 GeorgeH : 
Simplified Process, pre-render only basic page to  encompass all future checkout variants without modifcitsion
- Create (separate) preDigitalSubscriptionLandingPage
- Modify preSupporterPlusLandingPage 
1.  Remove LeftHand side text
2.  Remove Both White Stacked Containers
[**archived un-released PR**](https://github.com/guardian/support-frontend/pull/5512)
So users on slower devices (eg. Mobile devices not on WiFi) don’t just get a blank screen when they first land on the checkout.
> Build preRender DigitalSubscriptionLandingPage and simplify preRender SupporterPlusLandingPage

- .github/workflows/support-lambdas-build.yml
- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
- support-lambdas/acquisitions-firehose-transformer/cfn.yaml
- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/cfn.yaml
- support-workers/build.sbt
Part of: https://github.com/guardian/support-frontend/issues/5532
Upgrading all `support-lambdas` and `support-workers` to be on the same version of Java (Java11). There is an implicit coupling where `support-workers` calls `support-lambdas`. This should hopefully remove any conflict errors we're seeing because of that. 
Whilst trying to upgrade to `logback-classic@1.4.1` there are too many moving parts to try work out what is causing the issues. This should hopefully remove one of those variables.
> chore(deps): use java11 on all support workers and it-test-runner

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx
Uses the discountPrice as per the [`paperCheckout`](https://github.com/guardian/support-frontend/blob/44a30fdbcf9cfee3503d36e547ea703574e1d637/support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx#L552) and the [`weeklyCheckout`](https://github.com/guardian/support-frontend/blob/44a30fdbcf9cfee3503d36e547ea703574e1d637/support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx#L414).
✨ Bonus fix ✨: Fix the total at the bottom of the page
[**Trello Card**](https://trello.com/c/UHPzZKGZ/1745-guardian-weekly-gifting-checkout-incorrect-price-displayed-on-paypal-summary-when-promo-code-applied)
So people get discounts. And discounts mean prizes.
> fix: use discount price on Guardian Weekly Gift checkout

- support-frontend/assets/helpers/page/page.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/yarn.lock
Fixes issue where Ophan is being sent an empty ab test participations object (via `trackAbTests`) on Page 1 of the 2 step checkout, but not Page 2. 
[**Trello Card**](https://trello.com/c/M7Rg18K0/1742-trackabtests-participations-on-both-page-1-and-page-2-of-2-step-checkout)
trackAbTests for Ophan was provided with an empty ab participations on Page 1 of two-step checkout
This issue happened as the  Amounts Tests were not included in the ab participations sent to Ophan on Page 1.
Also the ab participations were not sent to Ophan on click of the "Change" button on second page and navigation to page 1.This PR includes a fix for that too
> Track AbTests participations  on both Page 1 and Page 2 of two-step checkout (Ophan)

- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx
Shrinking the blurb for the Digital Edition on the subscription page.
[**Trello Card**](https://trello.com/c/asnZwEzU/1743-update-the-editions-copy-on-the-subscribe-container)
To save readers precious time.
> fix: update blurb for digital edition on subscription page

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/page/page.ts
I've been documenting our [client-side AB tests](https://github.com/guardian/support-frontend/wiki/Client-side-AB-Testing) set-up on the support site. In doing so I noticed a few exports that weren't actually imported anywhere, or were only imported to test, so I made the following small changes:
1) Removed the export `getSourceFromAcquisitionData`, this function is only referenced within the module.
2) Moved the `targetPageMatches` export to an `_` export which is naming convention to highlight it's only exported for testing purposes.
3) Grouped the remaining named exports `init` and `getAmountsTestVariant` at the end of the module. I find grouping the exports like this at the end of the module easier when trying to get a quick overview of a modules interface. 
Interested in feedback on …
> Small refactor of abTest module interface

- support-frontend/assets/pages/supporter-plus-landing/components/finePrint.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/guardianTsAndCs.tsx
Spacing appears to have been lost from TsAndC’s fineprint text at bottom of checkout. 
Adjustments required ->
"<Tablet : 24px"
">=Tablet: 64px"
[**Trello Card**](https://trello.com/c/vjM36Wmb/452-checkout-scaffold-tax-donation-bottom-of-page-spacing-adjust)
|mobile|tablet+|
|--------|---------|
|![unnamed (7)](https://github.com/guardian/support-frontend/assets/76729591/f3f490f3-3156-4c25-914c-8a2bf1f6168c)|![unnamed (8)](https://github.com/guardian/support-frontend/assets/76729591/14226ecd-8ebd-47b3-8ddc-350729a025d4)|
> Checkout TsAndCs FinePrint bottom spacing adjust

- support-frontend/app/views/main.scala.html
- support-frontend/window.d.ts
Removing references to the polyfill callback code. I can't see anywhere we are using it and more code = more complexity.
The only thing I can think of is we might have used it for debugging, but I haven't seen this anywhere.
Less code = less complexity = more fun + more productivity.
Things like this also make it harder to refactor as I need to assess if it should come along for the ride or if we can remove it. This should make it easier for the next person to make changes.
> refactor: remove polyfill callback code

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/tracking/ophan.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/firstStepLanding.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Reverts guardian/support-frontend#5566
This test has reached significance and the control has won, AV per impression was -12.9% lower in the variant compared to the control, this was significant.
> Revert "Take users directly to second page of checkout"

- .gitignore
- .vscode/settings.json
- .vscode/settings.json.recommended
- support-frontend/.prettierrc.js
I've noticed VSCODE hasn't been applying Prettier formatting on save, despite the workspace settings in .`vscode/settings.json` containng a rule `"source.fixAll.prettier": "explicit"`, the purpose of which was to format using our Prettier settings on save, having looked at it this doesn't do anything.
I've looked at various examples online and have landed on an updated configuration that now:
- Applies Prettier fixes to all `.ts` and `.tsx` files on save, I've tested and confirmed it's using our Prettier settings in `support-frontend/.prettierrc.js` when formatting on save.
- Applies ESLint updates to all `.ts` and `.tsx` files on save.
- Doesn't attempt to format non `.ts` and `.tsx` files on save.
> VSCODE format .ts/.tsx on save

- support-frontend/assets/components/checkmarkList/checkmarkList.tsx
- support-frontend/assets/components/paymentFrequencyButtons/paymentFrequencyButtons.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierLozenge.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Build the new components needed for the three tier first page checkout. the main ones being the three column cards and the tabs above. The test will propose 3 tiers with fixed prices and an option to support just once with variable prices.
The tiers will be the following:
tier 1: our current recurring contribution product at a fixe price
tier 2: our current Supporter+ product at a fixed price
tier 3: GW + Supporter plus bundled together at a fixed price
Checkout can be viewed at the following url behind (currently disabled) ab-Test named `threeTierCheckout` ->
|mobile-mobileMedium|MobileLandscape|Tablet|Desktop-LeftCol-Wide|
|--------|---------|---------|---------|
|<img width="122" alt="image" …
> 3-tier first page, checkout inner content components

- support-frontend/assets/pages/weekly-subscription-landing/components/content/benefits.tsx
Update the list of benefits on the Guardian Weekly landing page.
[**Trello Card**](https://trello.com/c/LxnWxC09/60-change-gw-benefits-on-landing-page)
Go to `/subscribe/weekly`
Desktop before
Desktop after
Mobile before
Mobile after
> Update the list of guardian weekly benefits

- support-frontend/app/controllers/CanonicalLinks.scala
- support-frontend/app/controllers/PaperSubscriptionController.scala
- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/linkTo.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/paperTabs.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx
- support-frontend/conf/fastly-snippets/redirects-table.vcl
- support-frontend/conf/routes
- Removes the use of using a fully qualified route `paper/delivery` to control a fragment of the page in favour of using the url fragment/hash to do so
- Moves redirection for the paper route to Fastly
Using a URL to control a fragment of the page felt like the wrong tool for the job. This code also created some interesting logic between the history manipulation on the client and routing on the server where you couldn't hit `/paper` directly without redirecting to `/paper/delivery`.
It hopefully simplifies this part of the code too by using JS to deal with the fragment/hash and the server / fastly to deal with routing.
This code was introduced [here](https://github.com/guardian/support-frontend/pull/5436/files#diff-262aa4c1d3a23544743205a3065e7217fcc8f4638bf30c751a12469bd00e2f58R59). It …
> Remove `paper/delivery` url

- support-frontend/assets/components/page/pageScaffold.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionLandingPage.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/preRenderDigitalSubscriptionLandingPage.tsx
- support-frontend/assets/pages/digital-subscriber-thank-you/digitalSubscriptionThankYou.tsx
- support-frontend/assets/pages/supporter-plus-landing/preRenderSupporterPlusLandingPage.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
- support-frontend/stories/core/PageScaffold.stories.tsx
Removes the `id` from `PageScaffold` as it's unused.
Extra code = extra overhead when trying to refactor making things harder to change, and thus sometimes they don't get changed.
> refactor: remove id from pagescaffold

- support-frontend/app/wiring/ActionBuilders.scala
- support-frontend/app/wiring/AppComponents.scala
- support-frontend/app/wiring/AppLoader.scala
- support-frontend/app/wiring/Controllers.scala
- Extend `BuiltInComponentsFromContext` from `AppLoader`. This brings us closer inline with [the official](https://www.playframework.com/documentation/2.9.x/ScalaCompileTimeDependencyInjection#Application-entry-point) docs which helps for future travellers, especially those unfamiliar with Play. This seems to be [a more common way (80 examples)](https://github.com/search?q=org%3Aguardian+%22class+AppComponents%22&type=code) vs [how it's done here (23 examples)](https://github.com/search?q=org%3Aguardian+%22trait+AppComponents%22&type=code) across the org.
- Rename `actinRefiners` => `actionBuilders`. This is just one last loose end from [this commit](https://github.com/guardian/support-frontend/pull/120/commits/8693a10c6ce0880937051285d5bde68ddcf51fe4).
A little but of consistency and …
> AppLoader renaming for consistency

- support-lambdas/acquisition-events-api/build.sbt
- support-lambdas/acquisitions-firehose-transformer/build.sbt
- support-lambdas/bigquery-acquisitions-publisher/build.sbt
- support-lambdas/it-test-runner/build.sbt
- support-lambdas/stripe-intent/build.sbt
- support-workers/build.sbt
- support-workers/src/main/scala/com/gu/monitoring/PiiFilter.scala
Upgrades `logback-classic` => 1.14.14 in `support-workers` and `support-lambdas`.
[**Trello Card**](https://trello.com/c/Xmv2JyRL/457-update-logback-dependency-across-the-support-frontend-repo)
Security
We will deploy to `CODE` and ensure that everything is running as planned.
`support-workers` and `it-test-runner` were deployed to `CODE`, then the lambda run. We had the message: `RUN COMPLETED - sending metric: RunCompleted(Ordinal(1, 854),Some(66833),Some(Summary(234,0,7,0,0,60,0,0)),None,None,None,ScalaTest-main,1704894969526)`.
This previously failed. Looks like we're good to go!
> Support lambdas/workers upgrade to logback 1.4.14

- support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
- support-frontend/test/actions/UserFromAuthCookiesOrAuthServerActionBuilderTest.scala
We discovered an issue in the way that the GU_SO cookie works, meaning that a user could sign out, then immediately sign in again as a new user, but the tokens for the old user had not been cleared yet, so the new user would see the old users data.
The problem and solution have been outlined in detail within this PR https://github.com/guardian/gateway/pull/2529
And the documentation was updated in this PR https://github.com/guardian/gateway/pull/2530
Essentially the fix is to read the `GU_SO` cookie and get the timestamp for when a user signs out, and compare it to the `iat` claim of the ID token. This leads to one of three scenarios:
1. If the `GU_SO` value is > `iat` then the user has signed out recently, so the tokens are invalid, get new tokens if needed
2. If the `GU_SO` value is < …
> Identity | Change logic of `GU_SO` cookie use

- support-e2e/tests/newspaperCheckout.test.ts
Using the `/paper` over the [removed `/paper/delivery` route](https://github.com/guardian/support-frontend/pull/5572) for our e2e tests.
This is a no-op in terms of the test, as home delivery was the default option for the page.
> fix: remove use /paper over /paper/delivery route for e2e tests

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Updates the `canRun` function of the `threeTierCheckout` to run on contribution pages and the weekly checkout with the `isThirdTier=true` URL parameter.
Adding the new `isThirdTier=true` URL param allows us to
- Let the Weekly checkout know it should include the Support+ subscription
- Include a person in the test with this parameter
- Gives us a signal to pass the upstream `/create` endpoint & step functions that it should include the Subscriber+ contribution
> fix: run threeTierCheckout test on contribution or  weekly pages with relevant URL param

- support-models/src/main/scala/com/gu/salesforce/Salesforce.scala
- support-modules/rest/src/main/scala/com/gu/rest/WebServiceHelper.scala
- support-workers/src/main/scala/com/gu/salesforce/SalesforceService.scala
- support-workers/src/test/scala/com/gu/salesforce/SalesforceServiceSpec.scala
- support-workers/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/SalesforceErrorsSpec.scala
The Salesforce API returns a http status of 200 even if the request fails, but with the `Success` property on the response set to `false`.
e.g.
```JSON
{
"Success": false,
"ErrorString": "Failed Upsert of new Contact: Upsert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, ContactTrigger: execution of AfterInsert\n\ncaused by: line 78, column 9: Dependent class is invalid and needs recompilation:\n Class testUtilities : Dependent class is invalid and needs recompilation:\n Class KnowledgePublishToHelpCentreService : DML operation Update not allowed on Knowledge__kav: []",
"ContactRecord": null
}
```
This fix handles that case and returns the `SalesforceErrorResponse` to the lambda / client to ensure it's handled correctly i.e. retried.
[**Trello …
> fix: Handle error where salesforce API response status is 200 but Success is false

- support-frontend/Brewfile
Cleanup Brewfile to remove deprecated JDK8 cask installer.
Deprecation Notice -> [**here**](https://github.com/AdoptOpenJDK/homebrew-openjdk)
> Deprecated jdk8 cask installer removed from BrewFile

- support-frontend/assets/helpers/redux/checkout/personalDetails/state.ts
Addig an extra regex check to the email validation on the checkout.
[**Trello Card**](https://trello.com/c/0FPWDHrv/115-add-client-side-validation-to-prevent-email-addresses-including-commas-on-all-checkouts)
Currently, the checkout will allow commas, presumably as some email fields allow a comma separated list, which we do not. This PR adds an extra regex check that validates a single email address without commas. The question of whether the previously used validation check (`.emal()`) still has value is one I wanted to ask as part of reviewing. We could consider it redundant, or an extra security layer. 
Manually enter valid/invalid emails into the checkout form 
We should have no more alarms related to email addresses with commas in them.
> Add extra email validation regex

- support-models/src/main/scala/com/gu/support/zuora/api/response/Responses.scala
- support-services/src/main/scala/com/gu/zuora/ZuoraService.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/PreparePaymentMethodForReuseSpec.scala
The `PreparePaymentMethodForReuse lambda was fetching account information using a Zuora api call which required the guid id of the account rather than the more usual account number. This was a problem for the three tier work currently taking place as we do not have this id readily available.
This PR changes the lambda to use the more commonly used api call which accepts either an account id or an account number and also adds a few fields to the response of that call which were not being mapped previously.
> Switch PreparePaymentMethodForReuse lambda to use standard getAccount

- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-models/src/main/scala/com/gu/support/acquisitions/AcquisitionData.scala
Allows the `threeTierCreateSupporterPlusSubscription` option to be passed from the client => `support-workers`.
This allows us to branch logically off of this `Boolean` to create a Supporter+ subscription for people ordering weekly via this route.
I have chosen the `AcquisitionData` model to attach this to as it percolates all the way through the step functions requiring fewer changes to the code. It also sort-of fits there.
[**Trello Card**](https://trello.com/c/zh96UwvO/486-create-support-subscription-for-supporter-buying-weekly-from-the-third-tier-in-3-tier-test)
Run support-workers with this property to see if it gets passed down the state machine.
> feat: add threeTierCreateSupporterPlusSubscription to form and state

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
AMOUNT CORRECTION TO ORIGINAL PR  [**HERE**](https://github.com/guardian/support-frontend/pull/5630) MONTHLY FROM (incorrect) $20 => (correct) $13
The US+ Global DRR is keen to pre test more emotional language on benefits on the current checkout, to support 3 tier LP testing. This is a copy test on the current checkout. If successful, this copy could be amended to 3 tier LP.
[**Trello Card**](https://trello.com/c/cSdCWciH/441-pre-testing-emotional-messaging-on-current-checkout-us-only)
https://support.thegulocal.com/us/contribute#ab-emotionalBenefits=variant
> US Emotional Messaging Around Benefits List - Amount Change

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Enables `ab-emotionalBenefits` test for these PR's
- [US Emotional Messaging Around Benefits List](https://github.com/guardian/support-frontend/pull/5618)
- [Equal Or Greater Than Amount Switching](https://github.com/guardian/support-frontend/pull/5630)
- [Amount Change](https://github.com/guardian/support-frontend/pull/5632)
The US+ Global DRR is keen to pre test more emotional language on benefits on the current checkout, to support 3 tier LP testing. This is a copy test on the current checkout. If successful, this copy could be amended to 3 tier LP.
[**Trello Card**](https://trello.com/c/cSdCWciH/441-pre-testing-emotional-messaging-on-current-checkout-us-only)
https://support.thegulocal.com/us/contribute#ab-emotionalBenefits=variant
> US Emotional Messaging Around Benefits List - Enable abTest

- support-frontend/package.json
- support-frontend/yarn.lock
Removes the `resolutions` from `package.json` as they're not needed any more. From the `yarn.lock` - they might actually be holding some packages back.
I assumed this by looking at the git blame and saw most were added yonks ago.
Health and hopefully it'll avoid any upgrade hell in the future.
**Snyk**
**Git Blame**
> chore(deps): remove outdated resolutions from package.json

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
LOWER BAND COPY CORRECTION TO ORIGINAL PR  [**HERE**](https://github.com/guardian/support-frontend/pull/5630) MONTHLY 
REFERRER CONTROL = FALSE (enables test to work without test name having to be in URL)
FROM (incorrect) 
`For $5 per month, support access to independent journalism for all those who want and need it, you'll unlock`
TO (correct)
`For $5 per month, support access to independent journalism for all those who want and need it, and you'll unlock`
The US+ Global DRR is keen to pre test more emotional language on benefits on the current checkout, to support 3 tier LP testing. This is a copy test on the current checkout. If successful, this copy could be amended to 3 tier LP.
[**Trello Card**](https://trello.com/c/cSdCWciH/441-pre-testing-emotional-messaging-on-current-checkout-us- …
> US Emotional Messaging Around Benefits List - Copy Change

- support-frontend/app/lib/CustomHttpErrorHandler.scala
Adds a little bit of logging to help debug some `5xx` errors we've seen coming through from `support-frontend`'s [CustomHttpErrorHandler](https://github.com/guardian/support-frontend/blob/main/support-frontend/app/lib/CustomHttpErrorHandler.scala#L87-L90).
We have an hypothesis that it could be from [this PR](https://github.com/guardian/support-frontend/pull/5596) - this should help analyse that hypothesis. 
[**Trello Card**](https://trello.com/c/Lsv2gWRn/526-5xx-error-increase-from-the-15-16-january-on-support-frontend)
> Add signedIn/Out logging to http error handler

- support-frontend/conf/riff-raff.yaml
Upgrades the last Java8 service to Java11!
Most of us have been running `support-frontend` on Java11 locally, so this has been dogfooded pretty well.
This will be tested on `CODE`.
> chore: update frontend java version 8 => 11

- support-models/src/main/scala/com/gu/support/workers/states/PreparePaymentMethodForReuseState.scala
- support-models/src/test/scala/com/gu/support/workers/SerialisationSpec.scala
- support-workers/cloud-formation/src/templates/state-machine.yaml
- support-workers/cloud-formation/src/templates/supporterPlusProduct.yaml
- support-workers/scripts/project/build.properties
- support-workers/scripts/update-code-cloudformation.sh
- support-workers/src/main/scala/com/gu/support/workers/lambdas/PreparePaymentMethodForReuse.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraSubscriptionCreator.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/ZuoraSubscriptionCreatorSpec.scala
- Adds `promoCode` `promoCode` to `PreparePaymentMethodForReuse` for Supporter+ bolt-on which then propagates through the system.
- Tightens the check to see if a payment is a duplicate by comparing the rate plans as well as the `requestId` as we were assuming the Supporter+ bolt on was a duplicate thus not being created.
- Adds a test for `subscribeIfApplicable`
The logic was quite hard to fathom in writing the tests for `ZuoraSubscriptionCreator`, which made me feel it could use with a little tidy, but that might be for another PR.
[**Trello Card**](https://trello.com/c/zFv8FO72/540-add-three-tier-promotion-codes)
> feat: add promoCode to SupporterPlusState

- support-frontend/conf/riff-raff.yaml
Reverts guardian/support-frontend#5608
This has stopped deployment because it's still requiring the old package.  This reverts to unblock so that a new PR can be tried in CODE first.
See a similar fix here:
https://github.com/guardian/members-data-api/pull/1037#discussion_r1400412892
Also see parameter changes possibly needed here:
https://github.com/guardian/members-data-api/pull/1037#discussion_r1400396814
Feel free to merge this PR if I'm not around, once it's approved.
> Revert "chore: update frontend java version 8 => 11"

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
TIER TYPE SIMPLIFICATION TO ORIGINAL PR  [**HERE**](https://github.com/guardian/support-frontend/pull/5656)
- Removal of Tier type. Created type errors (suspected naming issue with `Tier`)
- Rather than rename, decided to define as 1, 2 or 3 only.
[**Trello Card**](https://trello.com/c/MjmPGSGt/557-add-query-string-parameters-to-three-tier-links)
> Three Tier - Query string parameters to all links - Tier Type Correction

- support-frontend/app/services/pricing/PriceSummaryService.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala
Adding some logging to the `PriceSummaryService` to try and work out why we promoCodes on `PROD` as a test user intermittently work.
A working theory is that we aren't comparing the right data between the `promotionsService` and `catalogueService`.
[Trello card](https://trello.com/c/PtZJsS3h/582-get-promocodes-working-on-prod-for-test-users).
> feat: add verbose logging to pricesummaryesrvice

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/redux/commonState/reducer.ts
Currently there's some special logic in the reducer to prevent any other other AB test participations if the url specifies that the user should be in the `supporterPlusOnly` AB test.
[Example](https://support.theguardian.com/uk/contribute?acquisitionData={%20%22abTest%22:{%20%22name%22:%20%22supporterPlusOnly%22,%20%22variant%22:%20%22variant%22%20}%20})
We'd like to use this type of logic again for an upcoming feature. But really we want to avoid interfering with the `threeTierCheckout` test - if the user is in a referrer-controlled AB test then we do not want them to go into the `threeTierCheckout`.
This PR adds a new field to the AB test model: `excludeIfInReferrerControlledTest`.
If a test participation has `referrerControlled: true`, we exclude any other test which has …
> Add excludeIfInReferrerControlledTest to AB test model

- support-frontend/assets/components/paymentFrequencyButtons/paymentFrequencyButtons.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Accessibility improvement to 3-tier landing page : parity with existing landing page & helps QM track interactions with the Toggle.
[**Trello Card**](https://trello.com/c/9RUcZd0S/578-add-aria-attributes-to-3-tier-frequency-toggles)
-  [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
> Three tier aria labels added using  paymentFrequency

- support-services/src/main/scala/com/gu/support/promotions/PromotionCache.scala
- support-services/src/main/scala/com/gu/support/promotions/PromotionCollection.scala
- support-services/src/test/scala/com/gu/support/promotions/PromotionCacheSpec.scala
Currently the `PromomotionCache` is a singleton, meaning that any service using it will use the same cache, irrespective of which table it came from.
This means that if
- we fill the cache with `PROD` data
- Become a test user
- Try to read CODE data
We will actually get `PROD` data until we need to refresh the cache. 
```mermaid
flowchart TB
PriceSummaryService
PriceSummaryService --> codeService
PriceSummaryService --> prodService
subgraph PROD
prodService --> ProdPromotionService
ProdPromotionService --> ProdCachedDynamoPromotionCollection["new CachedDynamoPromotionCollection"]
end
subgraph CODE
codeService --> CodePromotionService
CodePromotionService --> CodeCachedDynamoPromotionCollection["new CachedDynamoPromotionCollection"]
end
ProdCachedDynamoPromotionCollection <-- read CODE …
```
> Promo cache respects stage

- .github/workflows/playwright.yaml
Fixes https://github.com/guardian/support-frontend/issues/5653
[Trello](https://trello.com/c/npqIGlkP/568-post-to-sr-dev-google-chat-when-e2e-tests-fail)
Our E2E tests were failing and the alarm in the chat channel was not being triggered. 
There is a few linting fixes here, but the main issue is that we were using `'$GOOGLE_CHAT_WEB_HOOK'` instead of `"$GOOGLE_CHAT_WEB_HOOK"`. [Double quotes are used for string interpolation in bash, single quotes do not do this](https://www.baeldung.com/linux/bash-double-quotes#variable-interpolation).
As a note these errors take ~15 minutes to run, and ~30 minutes to fail. I wonder if we could split them out into "Integral" vs "Subsidiary" or similar.
> Fix E2E failure alerting

- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierDisclaimer.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
3-tier landing and checkout page - copy updates
- Subscribe recurring buttons
- Dicount summary copy change
- Support Once, dash in copy, currency symbol pull through, spacing above paragraph (4px <desktop, 8px >desktop)
- Disclaimer full stop copy update
Tier Card's
[**Trello Card**](https://trello.com/c/AJZ1yIDO/548-3-tier-landing-and-checkout-page-copy-updates-additional-tooltip)
Checkout can be viewed at the following url behind (currently disabled) ab-Test named `threeTierCheckout` ->
> Three tier copy update revision

- project/LibraryVersions.scala
Our AWS dependencies are pulling in a vulnerable version of `ion-java` - https://security.snyk.io/vuln/SNYK-JAVA-SOFTWAREAMAZONION-6153869
The latest version of the AWS sdk does not depend on `ion-java` at all.
All apps tested in CODE
> Bump AWS sdk (v1)

- support-frontend/assets/components/subscriptionCheckouts/digitalPlusPrintSummary.tsx
These URL fragments for forcing yourself into an AB test should not be user facing at all, they're just a testing mechanism for engineers, we don't need to include it on this link as once the test has been enabled a user will be allocated into the correct AB test & cohort via their MVT cookie.
> Remove the URL fragment for forcing ab tests

- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- Change copy to `£16/month for the first year, then £25/month*` to discount summary on tier card3
|before|after|
|----|----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/f94f1b58-3b39-43aa-97f0-cce56ef5a89e)|![image](https://github.com/guardian/support-frontend/assets/76729591/8577bdf1-071b-4774-b39e-be906aab146d)|
- Tier1 (Support product) checkout button should read `Pay £4 per month` (Three-tier ONLY)
|before|after|
|----|----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/e8f3d8f6-5301-4a55-ac89-0628158ae190)|![image](https://github.com/guardian/support-frontend/assets/76729591/f5b69a98-7256-4a5c-9255-aa19fc473dd9)|
Final copy amendments to first test of 3-tier
> Three tier copy changes

- support-lambdas/it-test-runner/cfn.yaml
- support-services/src/main/scala/com/gu/support/catalog/CatalogJsonProvider.scala
Adds permissions to allow IT tests to access PROD catalog in S3.
We have widened the amount of tests we're are running because we've added [this line](https://github.com/guardian/support-frontend/pull/5673/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R161).
We'd like to follow this up by working out if we should be running this in other places, and potentially refactor the CatalogService to return an error rather than just [None when there is a loading fail](https://github.com/guardian/support-frontend/blob/main/support-services/src/main/scala/com/gu/support/catalog/CatalogService.scala#L66-L71).
> Add PROD catalogue S3 Access to IT tests

- support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala
re -> ALARM: "URGENT 9-5 - PROD support-frontend is returning 5XX errors" in EU (Ireland)
This was caused when:
- A user signs in
- A user then signs out
- And then signs again
That means `GU_U`, `GU_ID_TOKEN`, `GU_ACCESS_TOKEN` **and** `GU_SO` cookies are set, which means [this code](https://github.com/guardian/support-frontend/blob/main/support-frontend/app/actions/UserFromAuthCookiesActionBuilder.scala#L119-L130) is reached that then tries to convert a `java.lang.Integer` => `Scala.Long`.
Caused by UserClaim iat returning from identity as a `java.lang.Integer`, this is now explicitly converted to a `scala.Long`. 
`asInstanceOf` below is an example error thrown->
``` SCALA
val javaInt: java.lang.Integer = 123
javaInt.asInstanceOf[Long]
// ...Caused by: java.lang.ClassCastException: …
```
> Pd userclaims iat 5xx

- support-config/src/main/resources/touchpoint.CODE.conf
- support-config/src/test/scala/com/gu/support/config/PromotionsConfigSpec.scala
When we create acquisition discounts in support-workers, we do so by adding a specific discount product rate plan to the new subscription and overriding the amount of the discount. The product rate plan we use as the template for this in production is in the `Discounts` product and is called `Percentage`, however we haven't been using the equivalent product rate plan from the code environment even though it does exist. 
This PR updates the ids used by support-workers in the CODE environment to match the ones in PROD for the sake of consistency.
> Correct the ids used for discounts in CODE

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Uses the three tier pricing in the mobile total when in the test.
To make the prices accurate as to what someone will be paying.
|---|---|
| ![Screenshot 2024-02-13 at 08 37 59](https://github.com/guardian/support-frontend/assets/31692/80e552a4-dfd5-441f-96a6-ac338b1c73d4) | ![Screenshot 2024-02-13 at 08 33 36](https://github.com/guardian/support-frontend/assets/31692/58989759-aa1f-4c60-9c46-5a5815f0cecc) |
> fix: use three tier total on mobile checkout when applicable

- support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
**Objective:** Send Low, Middle And One-Off "Cart Value" to Quantum Metric.
On the existing checkout we use [Redux Toolkit's Listener Middlewear](https://redux-toolkit.js.org/api/createListenerMiddleware) to execute "side effects" when certain pieces of the Redux Store are updated. For example we Trigger tracking calls to Quantum Metric when the Contribution Amount or Frequency changes to indicate a change in "Cart Value".
**Low & Middle Tier**
- Stop reporting cart value to QM as a side effect of Redux state changing if a user is in the `threeTierCheckout` AB test `variant`, as the values stored in Redux on initial page load do not match the 3-tier landing page (we use hardcoded values on this page).
- Introduce a  CTA click handler on the 3-tier landing page to report cart value to QM …
> Three tier - Send low, middle And one-off cart values to Quantum Metric.

- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/helpers/tracking/quantumMetric.ts
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
**Objective:** Send Top Tier "Cart Value" to Quantum Metric.
**Top Tier**
- On GW weekly checkout page load,  report cart value to QM.
- When GW weekly checkout converted, report conversion with cart value to QM.
**Limitation:** ProductPrice for top tier currently does not support combined products (ie S+ & GW in this case), as this is an ThreeTier abTest currently total discounted price will be reported and promotion removed. This will need to be revisited  should we go ahead with more combined-products.
[**Trello Card**](https://trello.com/c/fshH8Spw/527-3-tier-tracking-review-and-implement)
Checkout can be viewed at the following url behind (currently disabled) ab-Test named threeTierCheckout ->
> Three tier - Send top tier cart values to Quantum Metric, click and conversion

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- **Objective:** Send Top Tier and One-Time click events
TopTier Button Click needs a manual Ophan click event→ 
`{"component":{"componentType":"ACQUISITIONS_OTHER","id":"npf-contribution-amount-toggle-GBPCountries-MONTHLY-10"},"action":"CLICK"}`
OneTime Button Click needs a manual Ophan click event→ 
`{"component":{"componentType":"ACQUISITIONS_OTHER","id":"npf-contribution-type-toggle-GBPCountries-ONE_OFF"},"action":"CLICK"}`
- This PR also fires a Top Tier click to Quantum Metric.
[**Trello Card**](https://trello.com/c/fshH8Spw/527-3-tier-tracking-review-and-implement)
Checkout can be viewed at the following url behind (currently disabled) ab-Test named threeTierCheckout ->
> Three tier - top tier and onetime click ophan events

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Testing the 3-tier checkout flow picked up some issues on the Guardian Weekly checkout (used by the Top Tier) when attempting to pay with PayPal. The conclusion was this is too complex to fix ahead of the test go live, so we'll remove PayPal as an available payment method for users in the test on this checkout.
> 3-Tier: Remove PayPal as a payment method from the GW checkout

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
3-tier landing page frequency toggle incorrectly showing "Annual" when returning from One-Time page 2 via 'back' CTA in Amount Container. 
Bug-fix frequency toggle to "Monthly" when returning from One-Time page 2 via 'back' CTA.
|Page1|Page2|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/9eb4eea0-e6fd-4e16-b356-53a3d729a729)|![image](https://github.com/guardian/support-frontend/assets/76729591/d881ec68-eaa1-4dd0-af3d-95b2e04bf972)|
[**Trello Card**](https://trello.com/c/71JatFGI/617-3-tier-landing-page-frequency-toggle-incorrectly-showing-annual-when-returning-from-one-time-page-2-via-back-cta-in-amount-conta)
Checkout can be viewed at the following url behind (currently disabled) ab-Test named threeTierCheckout -> …
> Three-tier:  one-time back cta returns to monthly state on first page

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierDisclaimer.tsx
This PR updates the 3 tier disclaimer to include /month, otherwise it sounds like the monthly cost covers the whole year
I copied the block from
https://github.com/guardian/support-frontend/blob/ca20f7f7c77d807795086571d9a4f777b7d3bd53/support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx#L170-L176
because it looked a bit neater and the overall logic looks the same as what this should be
> add `/month` to the 3 tier disclaimer

- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
This checks the `selected-contribution-type` URL parameter on every navigation rather than the instantiation of the router.
[**Trello Card**](https://trello.com/c/VAB8wUhc/615-back-button-in-amounts-container-doesnt-work-for-users-in-3-tier-variant-landing-directly-on-one-time-checkout-via-banner-epic?filter=label:3-tier)
Currently we set the value of `isThreeTierAndOneOffUrlParam: boolean` on instantiation of the router i.e. on a person's first landing.
This would be set to true if:
* They are in the three tier test
* `selected-contribution-type === 'ONE_OFF'`
So if you land on the page - https://support.theguardian.com/uk/contribute/checkout?selected-contribution-type=ONE_OFF&selected-amount=30#ab-threeTierCheckout=variant
That value will be set to `true` for that navigation session.
If …
> fix: Check 3-tier redirect on navigation rather instantiation

- support-frontend/nginx/support.conf
Uses `TLSv1.2` and `TLSv1.3` for local development. We were getting a `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` error locally and this fixes that.
We have seen strange behaviour where the TLS protocol version in this config was affected by the [promo tool's config](https://github.com/guardian/memsub-promotions/pull/281) - so we've updated that too, but will dig into that unexpected behaviour.
> fix: use modern TLS protocols and ciphers

- support-frontend/build.sbt
- support-frontend/conf/riff-raff.yaml
Another go at https://github.com/guardian/support-frontend/pull/5645 loosely based on https://github.com/guardian/members-data-api/pull/1037
This is needed before we can bump to play 3, not to mention being good practice.
tested ok in CODE!
> use JRE11 instead of 8 in preparation for play 3

- support-frontend/build.sbt
Following on from
https://github.com/guardian/support-frontend/pull/5682
Most of the time the stack traces was missing and we could only see "ClassCastExecption: null". This made it quite hard to understand what was going on.
It turns out this is an optimisation if an error is frequently generated, the JVM uses a generic instance without any useful information, in order to improve performance.  It can be turned off with `-XX:-OmitStackTraceInFastThrow,`
https://yoshihisaonoue.wordpress.com/2021/02/07/jvm-option-xx-omitstacktraceinfastthrow/
Tested on CODE - the instances come up healthy and the checkout displays correctly.
> make sure JVM always generates stack traces

- .github/workflows/chromatic.yml
"UI tests" are a required workflow
Previously we didn't run them for scala version bump prs, but that makes them unmergable as they are waiting for a status that wil never come.
As we have [`turbsnap`](https://www.chromatic.com/docs/github-actions/#enable-turbosnap) [enabled](https://github.com/guardian/support-frontend/blob/main/.github/workflows/chromatic.yml#L36) - I would opt for removing the Scala Steward check on the PR template.
TL;DR of turbosnap is that it won't run if it doesn't pick up on any changes via package.json or the component tree. It's very good.
This PR removes the line that skips them as per this pr https://github.com/guardian/support-frontend/pull/4547
> always run UI tests even for scala steward PRs

- support-workers/cloud-formation/src/templates/state-machine.yaml
- support-workers/cloud-formation/src/templates/supporterPlusProduct.yaml
- support-workers/cloud-formation/src/templates/supporterPlusProductChoice.yaml
- support-workers/cloud-formation/src/templates/three-tier-state-machine.yaml
As per @rupertbates' suggestion - uses the `fulfilmentOptions` to discern between `US` and `INT`. I've not used it elsewhere as those should always be domestic from my understanding which them makes it more explicit as to why we're using it.
**Aus**
**Germany**
**UK**
**India**
**US**
> fix: use fulfilmentOptions as discriminator in 3-tier step functions

- support-frontend/package.json
- support-frontend/webpack.dev.js
- support-frontend/yarn.lock
After a [recent webpack upgrade](https://github.com/guardian/support-frontend/pull/5706) we're unable to run locally
> Fix webpack

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Deactivates the `threeTierCheckout` test. There might be some post-tidy work, but this should at least make it invisible 👻 to readers.
[**Trello Card**](https://trello.com/c/DAkMywVt/626-stop-3-tier-lp-test-1)
The test has run it's course and we will be running some post-test analysis.
> feat: deactivate threeTierCheckout test

- supporter-product-data/cloudformation/cfn.yaml
We sometimes get many supporter-product-data state machine failures during the early hours. This is because zuora query results can be very slow at this time.
Currently the `FetchResults` step retries for 20 minutes.
This PR increases this to 40 minutes.
This chart (from @graham228221) suggests some queries can take up to an hour -
> Increase tolerance for slow zuora jobs

- support-frontend/assets/components/personalDetails/personalDetails.tsx
- support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
- support-frontend/stories/checkoutLayout/PersonalDetails.stories.tsx
- Removes `contributionType` in place of `hideNameFields` to determine whether to hide name fields.
[**Trello Card**](https://trello.com/c/ZY1dQDdY/619-generic-checkout-mvp-using-catalog-data)
In the aim of making these components useful for all products in the [the generic checkout](https://github.com/guardian/support-frontend/pull/5704/files#r1497743253) we can no longer rely on `contributionType` as it varies more widely across products.
Should be a no-op
| Annual | One-off |
|------|-----------|
| <img width="641" alt="Screenshot 2024-02-22 at 08 41 03" src="https://github.com/guardian/support-frontend/assets/31692/e02e221d-83d8-4017-a800-d7e88fe8ba7f"> | <img width="626" alt="Screenshot 2024-02-22 at 08 41 33" src="https://github.com/guardian/support-frontend/assets/31692/94db4dcd-963 …
> refactor: decouple PersonalDetails from contributionType

- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/pages/supporter-plus-landing/components/contributionsPriceCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierABTest.ts
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierConfig.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Checkout can be viewed at the following url behind (currently disabled) ab-Test named threeTierCheckout ->
FROM
1. https://support.thegulocal.com/uk/contribute#ab-threeTierCheckout=control
2. https://support.thegulocal.com/uk/contribute#ab-threeTierCheckoutV2=variantA
3. https://support.thegulocal.com/uk/contribute#ab-threeTierCheckoutV2=variantB
TO
1. https://support.thegulocal.com/uk/contribute#ab-threeTierCheckoutV2=control
3. https://support.thegulocal.com/uk/contribute#ab-threeTierCheckoutV2=variant
- Remove abTest threeTierCheckout
- Remove (FROM/2)
> Three tier, replace threeTierCheckout with threeTierCheckoutV2, control and variant only

- support-frontend/assets/components/checkList/checkList.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/components/subscriptionBenefitsListData.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/formSections/limitedPriceCards.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.tsx
- support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx
- support-frontend/stories/content/CheckmarkList.stories.tsx
- Renames `CheckmarkList` and `Accordion` => `CheckList` as they are all the same thing. ✨ consistency!
- Removes `contributionType` from `ContributionsOrderSummary` (with the aim of it becoming _the_ `OrderSummary` 🧹 
- Add `description` and `paymentFrequency` to `ContributionsOrderSummary`
[**Trello Card**](https://trello.com/c/ZY1dQDdY/619-generic-checkout-mvp-using-catalog-data)
In the aim of making these components useful for all products ([the generic checkout](https://github.com/guardian/support-frontend/pull/5704/files#r1497743253)) we can no longer rely on `contributionType` as it varies more widely across products. 
I have decided to go for the most vague of types, `string`, for `description` and `paymentFrequency` which would give us the greatest flexibility in the checkout. We …
> refactor: decouple orderSummary from contributionType

- supporter-product-data/cloudformation/cfn.yaml
This field is now defined under the `Metrics` block, and cloudformation complains
> Fix supporter-product-data alarm

- support-workers/cloud-formation/src/templates/state-machine.yaml
If the state machine fails but `testUser: true`, move to the `CheckoutFailure` state, which does not trigger an alarm
> Suppress support-workers alarm if test user

- support-frontend/assets/helpers/tracking/acquisitions.ts
Change to also generate acquisitionData from 5 utm_* parameters iff they are all present. This is to support v3 of the lynx tool.
[**Trello Card**](https://trello.com/c/wxnDQWVD)
Improving the lives of the Marketing and D&I teams in evaluating the effectiveness of marketing across our estate in BigQuery. See https://docs.google.com/document/d/1e3U3LK8OOa-mWrSvFwhyHFG7jL5r4K6NFKSmI9VSB8w/edit
1. Generate a CODE environment URL using the new v2 link builder: https://reader-revenue-lynx.s3.eu-west-1.amazonaws.com/v2.html. Visit URL in an Incognito window.
-  Check that the acquisitionData session storage is as expected
2. Generate a CODE environment URL using the new v3 link builder: https://reader-revenue-lynx.s3.eu-west-1.amazonaws.com/v3.html. Visit URL in an Incognito window.
-  Check …
> Support v3 of the Lynx tool

- stripe-patrons-data/build.sbt
- support-lambdas/acquisition-events-api/build.sbt
- support-payment-api/build.sbt
- supporter-product-data/build.sbt
following on from https://github.com/guardian/support-frontend/pull/5737
We had to bump logback to 1.3 or 1.4 latest, but play didn't start with either of those.
Having bumped play to 3.0 in the above PR, we can update the explicit version across the board.
All tests pass and support-frontend still can start (and log stuff)
> build: bump logback-classic

- support-workers/cloud-formation/src/templates/supporterPlusProduct.yaml
Further to 
https://github.com/guardian/support-frontend/pull/5684
The state machine synthesises the json during the top tier process (because this is currently a temporary situation)
Unfortunately I forgot about this, so anyone buying the top tier would only get the GW and not the S+ part.
> use new nonDiscountedAmount field

- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
Bug-fix so one-off price card amounts in the 3-tier variant should be fed from RRCP here ->
- Bug introduced in Test2 PR ( https://github.com/guardian/support-frontend/pull/5709 }
- Test1 unaffected
|From|To|
|------|------|
|![image](https://github.com/guardian/support-frontend/assets/76729591/f31a5275-01f3-4ada-9b3f-c19ccccbbdf0)|![image](https://github.com/guardian/support-frontend/assets/76729591/87682c19-1d0e-46d5-8dea-6745d2de35ae)|
> 3-tier: all one-off price card amounts should now be fed from RRCP, test2 bug-fix

- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Add unique attributes to 3-tier landing page CTAs so QM can track clicks:
**Low CTA:** `data-qm-trackable="tier-1-button"`
**Middle CTA:** `data-qm-trackable="tier-2-button"`
**Top CTA:** `data-qm-trackable="tier-3-button"`
**Support Once CTA:**  `data-qm-trackable="support-once-button"`
> add unique attributes to 3-tier landing page CTAs so QM can track clicks

- support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
- support-frontend/assets/components/personalDetails/personalDetails.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds personal fields to the generic checkout.
There's been a few choices made, mostly around trying not to use redux state for things where there are native HTML alternative (hopefully reducing complexity).
- Introduce the `form` element to be able to hook into native HTML form handling, and work with documented standard APIs
- [client side form validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)
- [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects)
- Start to create the shape of the request we would like to send over to `create` endpoint based on the Zuora model. This currently sends the `product`, `ratePlan` and `currency`, which should allow us to look up the cost from there e.g. <img width="502" …
> Generic checkout: add personal details

- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-workers/cloud-formation/src/templates/supporterPlusProduct.yaml
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SupporterPlusSubcriptionBuilder.scala
- support-workers/src/test/scala/com/gu/support/workers/DigitalSubscriptionGiftRedemptionSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/UpdateSupporterProductDataSpec.scala
Use `amount` non `nonDiscountedAmount` as we try to decode the JSON from the that's sent from the client that uses `amount`.
> fix: use amount not nonDiscountedAmount

- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/pages/supporter-plus-landing/components/contributionsPriceCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierABTest.ts
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierConfig.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
For vat compliant countries ->  
Users will be split 50/50 between 2 cohorts:
1. `variantFixed` will display ThreeTier Test1 landing page
2. `variantVariable` will be ThreeTier Test2 landing page
For non-vat compliant countires ->  
Through omission from `threeTierCheckoutV3` users will see the original contribute landing page with VAT compliant pricing (eg. below S+ threshold).
Tier1 Card copy change ('From') between Variant and Control
Tier1 Card price (& priceCard) changes between Variant and Control (as previously supplied)
Summary ABTest Changes->
- `ab-threeTierCheckoutV3=variantFixed` will now be Test1 (original `ab-threeTierCheckout=variant`)
-  `ab-threeTierCheckoutV3=variantVariable` will be Test2 (`ab-threeTierCheckoutV2=variant`)
|VariantFixed|VariantVariable|
|-----|-----| …
> 3-tier: replace current contribute landing page with ThreeTier test1 as variantFixed, three tier test2 as variantVariable

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/checkout.scala.html
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/windowGuardianPaymentConfig.scala.html
- Copy payment config from `contributions.html.scala` `windowGuardianPaymentConfig.scala.html` that contains the `window.guardian` JS config needed for payments
- Reference this in `contributions.html.scala`
- Create new `checkout.scala.html` page with `@windowGuardianPaymentConfig`
This should be a no-op on existing pages, and make payment config available on the new checkout page.
Part of #5722
> feat: add payment config to checkout

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/checkout.scala.html
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/windowGuardianPaymentConfig.scala.html
Adds the missing fields that were erroneously removed in https://github.com/guardian/support-frontend/pull/5759.
As a second PR I will try get some testing in that validates between server and [client](https://github.com/guardian/support-frontend/blob/main/support-frontend/window.d.ts) to make this a little more safe.
This was tested locally and on `CODE` across single and recurring contributions.
> fix: add missing payment config to window.guardian

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/test/controllers/ApplicationTest.scala
This puts the productPrices, including promoCodes on the to the window.guardian.productPrices field, which we will then be able to access in the React app to use promoCodes for Supporter Plus in the UI.
[**Trello Card**](https://trello.com/c/5t4LIRvo/564-promos-on-supporterplus-part-2-attach-active-promotions-to-supporterplus-thresholds-model-on-windowguardian)
To allow people to use promoCodes for Supporter Plus
This shows an active `promoCode` in the productPrices with `promoCode` set in the URL.
> feat: add productPrices to window.guardian

- support-frontend/assets/components/stripe/contributionsStripe.tsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.test.tsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.tsx
- support-frontend/assets/helpers/forms/stripe.ts
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx
A reader was having trouble doing a recurring contribution.
It turns out the client side uses the AU stripe account if country=AU, and the server side does the same if currency=AUD.
On the client side a country code is taken from the geolocation cookie [1] and if it's within the country group (e.g. "KI" is within AUDCountries from "/**au**/contribute") then it will use that as the country.  The currency to offer is also taken from the country group.
This means that readers in AUD countries other than AU, would use the ROW stripe account on the client side and the AUS stripe account on the server side.
Since the idea of having an AUS stripe account is to reduce the chance of international transaction fees, the transactions will still go through even if we get it wrong.  Generally we think …
> use currency before country to determine stripe account to use

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
In the efforts to be reusing our form fields on the #5722 - this adds the `name` attribute to allow reading of the values `onSubmit` of the `form` [as we are for other fields](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/pages/%5BcountryGroupId%5D/checkout.tsx#L286-L293).
[**Trello Card**](https://trello.com/c/tUUScZqY/674-add-delivery-and-billing-address-fields-to-checkout)
This is a no-op as it's completely additive. I have tested all the critical flows via playwright locally.
> feat: add names to address fields

- support-frontend/assets/pages/weekly-subscription-checkout/components/thankYou.tsx
`threeTierCheckoutEnabled` was returning `true` 
Instead of using this on GW checkout pages we can use the presence of the `threeTierCreateSupporterPlusSubscription` query string param as indication they're on the top-tier checkout as we no longer use the participation in a 3-tier AB test.
> Stop showing top-tier TY page to standard GW checkouts

- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierChecks.ts
We call `threeTierCheckoutEnabled` from [submit.ts](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/subscriptionsForms/submit.ts#L246 ) when building the payload to send to the `/create` endpoint. This logic is shared between the `/contribute` checkout and the `/subscribe` checkouts.
However in the standard GW checkout `threeTierCheckoutEnabled` was returning `true` (as the checks in `threeTierCheckoutEnabled` were only relevant to the `/contribute`  checkout, the consequence was we were setting `threeTierCreateSupporterPlusSubscription: true` in the payload for standard non 3-tier checkouts.
To resolve this I've made `threeTierCheckoutEnabled` work so it'll only return true for users on the GW checkout when the …
> Fix threeTierCheckoutEnabled conditional check on GW checkouts

- support-e2e/tests/utils/users.ts
[As per @johnduffell's good suggestion](https://github.com/guardian/support-frontend/pull/5779/files#r1521347342), let's prefix the names to help for ordering and search.
I've tried to keep the data in the name that might allow people to identify where this test user came from.
Related to #5779
> fix: prefix names with test info in e2e

- support-workers/cloud-formation/src/templates/cfn-template.yaml
\We have alarms that trigger when there are no acquisitions for a period of time, ont he assumption that it wouldn't be normal.
Previously S+ was used to augment the general RC figures, which makes sense and was done intentionally https://github.com/guardian/support-frontend/pull/4498#discussion_r1043147992 , however if there is some breakage in one but not the other, it can be worth separating them.
This PR separates then, and updates the time needed (increases it) due to the more dilution.
I did a query on the DL to check the required frequencies
```
with timegaps as(
select
product,
if (print_options.product is null, null, if(print_options.product = 'GUARDIAN_WEEKLY', 'WEEKLY', 'NEWSPAPER')) print_product,
payment_provider,
e.event_timestamp,
(lag(e.event_timestamp) over (partition by …
```
> split alarms for lack of S+ and RC

- support-workers/cloud-formation/src/templates/cfn-template.yaml
fixed version of https://github.com/guardian/support-frontend/pull/5770
It was missing the Statistic: Sum line.
Unfortunately testing in CODE wasn't possible as it doesn't create the alarms in CODE.
I have tested this one in PROD and it deployed correctly. (fingers crossed)
> attempt 2 at separating the supporter plus alarm from contributions

- support-workers/cloud-formation/src/templates/lambda.yaml
This PR bumps support workers to java 21.  This is supposed to give us performance improvements.
https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/
We are using scala 2.13.12 which is compatible with JRE21
https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
I have tested in CODE and looking at one lambda (create payment method) you can clearly see the performance improvement for the cold start
This is replicated for the whole state machine execution, although it is diluted by the different paths it can take through the state machine.
> update support-workers to java21 runtime

- support-workers/cloud-formation/src/templates/lambda.yaml
following on from https://github.com/guardian/support-frontend/pull/5792
this PR updates support workers to arm64 architecture.
This is not necessarily faster than x86, but it costs slightly less.  Since we have been using arm64 on our instances, it seems safe to swtich on our lambdas.
Tested in CODE and the latency cold start was slower for an individual lambda:
but only slightly slower overall for the state machine, suggesting it might share something?
I am in two minds whether to ship it - it would save us a tiny amount of money as arm is cheaper, also most of our production runs are warmed up so there's no cold start.  Given that we don't really do any processing when warm - most of the time is spent waiting for SF/Zuora/etc in actual runs, I doubt we will notice any benefit for warm …
> update support-workers to arm64 architecture

- support-e2e/.prettierrc.js
- support-e2e/package.json
- support-e2e/playwright.base.config.ts
- support-e2e/yarn.lock
We have set up our Playwright config to retry a failing test up to 3 times. This means if the tests fai the time taken to test & retry 3 times exceeds Github Action’s maximum execution time of 30 minutes, the consequence of this is the Action won't post about the failed test to Google Chat, which is the most visible way to notify engineers to learn the e2e Action has failed.
I therefore propose in the PR to reduce the retry count from 3 to 1. 
PRO: The Action is more likely to complete within 30 mins, if it fails we learn about a failed test quickly via the Action posting to Google Chat.
CON: We may fail tests on transient issues which may have been resolved after multiple retries? I think it's worth testing with a lower retry count and seeing if this is an issue.
> Reduce retry count in Playwright config

- support-frontend/assets/components/product/giftNonGiftCta.tsx
Updating the copy for student discounts to accurately reflect the student beans %
[**Trello Card**](https://trello.com/c/h2WCOpNo/285-change-gw-student-deal-copy-to-50)
> Update student discount percent

- support-frontend/build.sbt
- support-frontend/conf/riff-raff.yaml
Since updating support-workers to java 21, the cold start time has improved a lot.
This PR updates support-frontend to java 21 by using the new AMI that I created and baked
https://amigo.gutools.co.uk/recipes/jammy-membership-java21
This is as per the new recommendation in https://docs.google.com/document/d/1ZR-YnaXCT5_gLVmTCeGs0mWd3KPaAozPjQK8uUzHZ9w/edit
Tested in CODE and working to buy a middle tier (supporter plus)
> make support-frontend use java 21

- .github/workflows/payment-api-build.yml
- build.sbt
- support-internationalisation/build.sbt
- support-payment-api/project/build.properties
- support-payment-api/project/plugins.sbt
- support-payment-api/src/main/resources/riff-raff.yaml
This PR follows on from updating support-frontend to java 21 https://github.com/guardian/support-frontend/pull/5801
This one updates payment api similarly, also updates the JDK used to compile to java 21
Note there is a bug in 2.13.13 so I didn't update the main scala version, but it will be fixed in 2.13.14 https://github.com/scala/bug/issues/12955
Payment API deploys ok in CODE and I could do a single contribution
> make payment-api use java 21

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/helpers/productPrice/promotions.tsx
- support-frontend/assets/helpers/redux/checkout/product/reducer.ts
- support-frontend/assets/helpers/redux/checkout/product/selectors/isSupporterPlus.ts
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
PT2 : Code changes required to prepare for the PromoCode PR, 
No visual changes are made in this PR
- Improved isSupporterPlus, Ts&Cs, TierPlan function optimisations/naming
- contributionOrderSummary total can (optionally) display crossed out originalPrice
- contributionOrderSummaryContainer can (optionally) retrieve and pass onto contributionOrderSummary the originalPrice (alongside CurrentPrice)
- redux S+ amounts can be stored as fractional numbers (likely to be generated by promoCodes in future)
- getProductPrice try-catch wrapper to ensures errors returned are undefined as getPromotion function specifies (future storybook support without PromoCodes)
[Trello Card](https://trello.com/c/5t4LIRvo/564-promos-on-supporterplus-part-2-attach-active-promotions-to-supporterplus-thresholds-mode …
> Three tier: S+ promoCode non-visual optimisations PT2

- support-lambdas/acquisitions-firehose-transformer/src/main/scala/com/gu/acquisitionFirehoseTransformer/AcquisitionToJson.scala
- support-lambdas/acquisitions-firehose-transformer/src/test/scala/com/gu/acquisitionFirehoseTransformer/LambdaSpec.scala
Add test + variant names to the output of the acquisitions lambda
To support the multi-armed bandit prototype [(point 2b)](https://docs.google.com/document/d/1jV6DkkLLH90PetO1Os7c6pi8WEiCx2t9BUIraqIEAHU/edit)
Deploy to `CODE`, we should start getting the data in S3 …
> Add test + variant names to the output of the acquisitions lambda

- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierChecks.ts
`threeTierCheckoutEnabled()` is called via https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/subscriptionsForms/submit.ts#L246 when building the payload for ALL recurring subscriptions, including Paper and Digital Edition. 
Currently `threeTierCheckoutEnabled()` returns `true` on the Paper and Digital Edition checkout, meaning we pass `threeTierCreateSupporterPlusSubscription` as `true` in the payload to the `/create` endpoint, I've tested and luckily the step functions don't go down the path of creating an SupporterPlus sub for users who are purchasing Paper OR Digital Edition! But  `threeTierCheckoutEnabled()` should really return `false` for  Paper and Digital Edition checkouts.
> threeTierCreateSupporterPlusSubscription should be false in payload for Paper and Digital Edition subs

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
Don't show the `CountryGroupSwitcher` on the checkout if the user is in a country from the `countriesAffectedByVATStatus` list.
There is a list of countries in which we only offer contributions (not incurring VAT). This is done by using a amounts test target at these specific countries, and only allowing amounts under supporter+ threshold.
Changing the country/currency via the dropdown in the header allowed to bypass this and so this PR removes it when the user is in one of these countries.
Navigate to the checkout from one of the affected countries. You can force the country by adding the query string parameter `country` and a 2 letter country code (make sure the region matches the country) e.g. /uk/contribute?country=GB for UK or /int/contribute?country=TW for Taiwan. (browserstack can …
> Hide the country group dropdown if user is in a country from VAT group

- support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx
Fix the "See Pricing Options" CTA on the weekly subscription page. Add back ID to scroll to in the page.
[**Trello Card**](https://trello.com/c/EqiISinB/287-guardian-weekly-landing-page-fix-cta)
The button previously did nothing (introduced in #5572). It should scroll to the pricing section. This was flagged up by a designer.
Go to `uk/subscribe/weekly` and click "See pricing options". Page scrolls down automatically.
-  [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03- …
> Fix "see pricing options" CTA - Guardian Weekly

- support-workers/build.sbt
- support-workers/src/main/resources/logback.xml
- support-workers/src/main/scala/com/gu/support/workers/lambdas/Handler.scala
- support-workers/src/test/resources/logback.xml
It's quite hard to pick out individual fields in the state when looking at support-workers logs.
This PR updates it so that it's nicely formatted.
I had to pull in a new library pprint https://com-lihaoyi.github.io/PPrint/
Also I had to write a custom logback appender which uses the AWS functionality that doesn't split up multi line log statements https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#:~:text=The%20logger%20class%20supports%20multiline%20logs.
before (this is in CODE)
After (split into two screenshots due to length)
> print out supporter-workers input and output state in a much nicer way

- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
So far the support workers executions are just a wall of UUIDs
This PR makes them more useful
The format is
```
TEST-Monthly-GuardianWeekly-Domestic-GBP-DirectDebit-1409401929736666
^^^^ ^^^^^^^^product description^^^^^^^^ ^^^^^^^^^^^ ^^^^^nanosecond rolling time (292 year rollaround)
||||                                     pay_meth
present only if test user
```
> use useful name for support workers executions

- .git-blame-ignore-revs
- support-frontend/tsconfig.json
Lints the tsconfig file so it doesn't get caught in another PRs changes.
This doesn't happen automatically as [we only run the linter on `ts` and `tsx` files](https://github.com/guardian/support-frontend/blob/main/support-frontend/package.json#L8-L10).
I think I might try and make sure linting happens at the root of the project as we have JS elsewhere, and autofixing in the browser often catches things which I would prefer to ignore in the `ignore-revs` where possible.
> Lint tsconfig

- .github/workflows/playwright.yaml
browserstack link wasn't populated here https://github.com/guardian/support-frontend/actions/runs/8346808348/job/22844962434
`browserStackSearch="https://automate.browserstack.com/dashboard/v2/search?query=playwright-build-&type=builds"`
should have the commit ID in there too
This PR adds it back in so the var is set on failure, rather than skipped
> fix browserstack link

- support-frontend/test/controllers/PricesControllerSerialisationTest.scala
following on from 
https://github.com/guardian/support-frontend/pull/5818#issuecomment-2007240542
@mchv pointed out a test might find the NPE issue.
This is useful to have, because this endpoint https://support.theguardian.com/prices is used by dotcom, and wouldn't be tested routinely in CODE.  The existing testing is on the data, rather than the serialisation.  The first we would know of it would be a high 5xx rate alarm.
I wrote this test against main before the above PR and it passed.  I added the type annotation and it failed
```
[info] PricesControllerSerialisationTest:
[info] - should serialise a sample prices payload *** FAILED ***
[info]   java.lang.NullPointerException: Cannot invoke "io.circe.Encoder.apply(Object)" because "encoder" is null
[info]   at …
```
> add new test for prices encoder

- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Definition:-
- `promoPrices` : price including any promotional discount
- `prices` : price excluding any promotional discount 
Currently, on the 3-Tier landing, the paramURL generated (& associated redux) when you press 'Subscribe' on Tier2 with a promoCode exists is `?selected-amount=promoPrices`.  Zuora will apply the PromoCode discount to this already discounted amount.
1. Therefore we need to the price excluding promotional discount in the Url (ie FROM:`?selected-amount=promoPrices` TO:`?selected-amount=prices`)
2. Redux location `page.checkoutForm.product.selectedAmounts` set to price excluding promotional discount .
3. The discounted `promoPrices` must still be displayed in the checkoutSummary.
4. The discounted `promoPrices` must still be displayed in the paymentButtonController. …
> Three tier: S+ price excluding promotion passed to Zuora

- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Th following note added to the US SupporterPlus Thankyou page->
`Remember to claim your tote bag`
`To claim your tote, sign in to your account and complete your ‘Correspondence address’ located on the ‘Settings’ page.`
[**Trello Card**](https://trello.com/c/llPMl6Jh/711-s-thank-you-page-the-us-tote-copy-add-dev-effort)
> tote bag: Thankyou page copy for US supporterPlus

- support-frontend/assets/pages/digital-subscriber-thank-you/components/thankYouHeader.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Passes the promotion down from state into the thank you page heading.
I'm not sure we want it to look like this, but it will get us to stage 1. I wonder if a <sup>*</sup> style footnote might work better? e.g.
---
<sup>*</sup> For 6 months, then £10 every month.
---
☝️ has been done, I'll work with design to make sure it's all good.
> feat: promotion text on thank you page

- support-frontend/app/controllers/Application.scala
- support-frontend/app/services/ProductCatalogService.scala
- support-frontend/app/wiring/Controllers.scala
- support-frontend/app/wiring/Services.scala
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/test/services/ProductCatalogServiceSpec.scala
- Adds the ProductCatalogService from the [product-catalog API](https://product-catalog.guardianapis.com/product-catalog.json) (which is generated by https://github.com/guardian/support-service-lambdas/tree/main/handlers/generate-product-catalog )
- Adds the `CachedProductCatalogServiceProvider` to prevent having an HTTP call on each request for data that doesn't been to be mega-fresh
- Adds an integration test to help with debugging
Currently I am just using it for the endpoint that the generic checkout (#5722) uses, but I'll be making it available on the `window.guardian` object, negating the need to make an async call from the client for it.
[**Trello Card**](https://trello.com/c/IfPDMdrT/709-create-product-catalog-service-to-make-to-enable-making-it-available-on-windowguardian)
This …
> Add ProductCatalogService

- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/app/controllers/Application.scala
Uses `testMode` when fetching prices and injecting them on the client. This should only affect the `/contribution` route on `PROD`.
This was noticed as we are using `PROD` promotions even when a test user.
> fix: use testMode for product prices on contributions

- support-e2e/tests/tieredCheckout.test.ts
After [enabling the tests again](https://github.com/guardian/support-frontend/pull/5843) - I had forgotten to account for the fact that [we now pass the `promoCode` to the thank you page](https://github.com/guardian/support-frontend/pull/5837/files#diff-fd63b7bdddd1f8c8a686a6ba94bee4323ebd6d88ea919d35cdcf7dbecd9a6db5R41-R46).
This fixes that.
> fix(tests): add promoCode to thank you URL assertion

- support-frontend/assets/helpers/urls/routes.ts
We gain far more security by having [`noUncheckedIndexedAccess: true`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in [our `tsconfig`](https://github.com/guardian/support-frontend/blob/main/support-frontend/tsconfig.json#L23).
This starts to eat into the errors we have to be able to do that.
Part of #5829
> chore(ts): update routes to avoid noUncheckedIndexedAccess

- support-frontend/assets/helpers/contributions.ts
To help with #5829.
We needed to set the `numbersInWords` `as const` and removed some unused methods.
> chore(ts): tidy contributions helper

- support-frontend/app/services/stepfunctions/Client.scala
- support-frontend/test/services/stepfunctions/SupportWorkersClientTest.scala
Following on from https://github.com/guardian/support-frontend/pull/5823
It turns out that in extreme cases the execution name can be over 80 chars
`TestUser-Quarterly-GuardianWeekly-RestOfWorld-USD-StripeCheckout-1425327897029666`
is 81 characters, meaning that checkout is impossible.
This PR truncates it if necessary (and makes sure the unique number is in the non truncated section)
EDIT
I have updated this PR to use a the densest possible encoding of a long (see below), so the truncation problem has gone away probably.  However it could still happen unexpectedly in future, so I have added some tests.
example IDs as generated by the new test
```
12345678901234567890123456789012345678901234567890123456789012345678901234567890
=============================================================== …
```
> truncate execution names that are over 80 character

- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
Updates the thank you messaging for discounted prices.
Also makes the `*` a little smaller.
> fix: update thank you promotion messaging

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/setup/threeTierChecks.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
AB Test to show the Tote benefits, Ts&Cs and thankyou page. 
This is `enabled` & displayed to 100% audience to match production. 
A further PR this afternoon will reset the state to `disabled` at the end of the tote-bag offer.
[**Trello Card**](https://trello.com/c/H6GwdNkQ/723-remove-tote-copy-from-the-us-landing-and-ty-pages-tue-26th)
|ab-additionalBenefits=control|original|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/d59ef7e9-dc66-4514-94f4-52ad4c600876)|![image](https://github.com/guardian/support-frontend/assets/76729591/9a3fb720-93bd-48e7-99c4-d3e07077318e)|
> Feature switch additional benefits add (currently tote bag)

- support-e2e/tests/tieredCheckout.test.ts
We have to use two different `promoCodes` for annual vs monthly as we want them to have different durations.
This does that, makes the `promoCode` configurable, and makes the expected text configrable.
> Update tiered e2e promo tests to use Annual and Monthly `promoCodes`

- .github/workflows/playwright.yaml
- support-e2e/README.md
- support-e2e/package.json
- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
Adds checks at the multiple stages of buying a product with a promo.
- Asserts the promo text on the tier card
- Asserts the total text on the checkout
- Asserts the "Buy" button text
- Asserts the promo text on the thank you page
This has picked up a bug that I was using the full amount for the promo text on the thank you page. Nice ✨ .
Lastly we add the annual promo example and header.
The script names for the e2e tests now follow `test-{env}` as it was a tiny bit fiddly to remember what it was.
[Trello card](https://trello.com/c/6EA1c4B7/705-3-tier-promotion-playwright-test-improve)
> fix: update e2e promo tests to use multi-stage text checks

- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
SupporterPlus Disclaimer Ts&Cs Change  to second sentence only.
FROM->
`If you pay more than {ccy}{S+Threshold} per {month/year} , these additional amounts will be separate {monthly/annual} voluntary financial contributions to the Guardian.`
TO->
`If you increase your payments per {month/year} , these additional amounts will be separate {monthly/annual} voluntary financial contributions to the Guardian`
|before|after|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/c211f71d-e23f-4577-ab68-ae77e23f66d3)|![image](https://github.com/guardian/support-frontend/assets/76729591/019b3688-add2-447b-a2a0-e6c98aefed2a)|
> SupporterPlus Checkout Disclaimer Ts&Cs change  to second sentence

- .github/workflows/payment-api-build.yml
- .github/workflows/stripe-patrons-data.yml
- .github/workflows/support-frontend-build.yml
- .github/workflows/support-lambdas-build.yml
- .github/workflows/support-workers-build.yml
- .github/workflows/supporter-product-data.yml
Sometimes I do one PR and while it's waiting for review, I add another PR off the first one.
This means I am not blocked if the work depends on each other, but the second PR doesn't look like it includes the first PR, making it easier to review.
I noticed that if I do that, it doesn't run the builds on the second one, so I can't test in CODE.
This PR makes the Scala builds run on all PRs, and it also allows them to be manually run from the GH UI.
> run scala builds on non main PRs

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
The [axe plugin we're using](https://github.com/dequelabs/axe-core-npm) was reporting that [we had the headers in the wrong order](https://dequeuniversity.com/rules/axe/4.4/heading-order?application=axeAPI).
After re-assessing the markup, I have opted to use sections for each product and an H2 for it's name, and remove the heading for the price, which didn't seem to make semantic sense.
**Before**
https://github.com/guardian/support-frontend/assets/31692/df9eeed0-6985-49c9-b2f2-81beeb3dff1d
**After**
https://github.com/guardian/support-frontend/assets/31692/848e7377-6b6b-4d23-937c-26e813e18518
> fix: use h2 for heading and h3 for price

- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Reads the amount paid in the checkout from session storage.
This is currently read from redux state outside of the `isOneOffPayPal` condition, which resets once you refresh the page.
We had a discussion as to whether this state should be stored in the `URLParams` going forward, and are a little undecided as it might expose information users aren't happy with, so thought this the quickest fix for now.
- run playwright tests
- tested 1 off payment
- tested recurring payment
- tested S+ payment
- tested S+ promo payment
> Read thank you page amount from session storage

- support-modules/aws/src/main/scala/com/gu/aws/AwsCloudWatchMetricPut.scala
- support-services/src/test/scala/com/gu/aws/AwsCloudWatchMetricPutSpec.scala
I shipped a PR yesterday to update some of the AWS clients to v2, including cloudwatch.
https://github.com/guardian/support-frontend/pull/5833
This involved a rewrite to use the new API.  Unfortunately the `dimensions` method in the new SDK overwrites the set of dimensions, whereas in the old SDK the similar method it added to them.
This means that when I ported over the old code, I made it go through each dimension, replacing them all with that one,r ather than adding them all.  This meant that they all ended up only under the Stage=PROD dimension, rather than the right PaymentProvider and Product as well.
To exacerbate that initial error, the test I was using to check it was only sending one dimension, so it worked fine (I ran it locally and just inspected the AWS console).  In CODE …
> fix payment success metric

- support-e2e/tests/tieredCheckout.test.ts
Temporarily inactivate `PayPal` e2e tests as we are getting "To many login attempts" errors which are throwing false positives and creating 👻 fear 🧟‍♂️  where there shouldn't be.
> test: temporarily inactivate PayPal e2e tests

- support-workers/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala
After the PR to update to AWS v2 in https://github.com/guardian/support-frontend/pull/5850 , I noticed one of the IT tests are failing due to a simplified return type.
```
'send' is a *void method* and it *cannot* be stubbed with a *return value*!
Voids are usually stubbed with Throwables:
doThrow(exception).when(mock).someVoidMethod();
If you need to set the void method to do nothing you can use:
doNothing().when(mock).someVoidMethod();
For more information, check out the javadocs for Mockito.doNothing().
```
This PR fixes it.
> fix IT tests

- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
We now support promotions on the supporter plus product, however we are not currently sending promo code information to BigQuery with the acquisition event. This PR fixes that.
> Send promo code information in the acquisition event for supporter plus

- support-e2e/tests/gwCheckout.test.ts
- support-e2e/tests/newspaperCheckout.test.ts
- support-e2e/tests/oneOffContributions.test.ts
- support-e2e/tests/tieredCheckout.test.ts
Related to #5860 
Inactivates all PayPal E2E tests while we work out how to not be hit with the "To many login attempts" error.
> test: inactivate all PayPal tests

- support-frontend/.storybook/preview.js
- support-frontend/package.json
- support-frontend/yarn.lock
Uses [mockdate](https://www.npmjs.com/package/mockdate) in our storybook to void false positives in our test when the date changes. 
This was specifically noticed in [our support reminders](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/components/thankYou/supportReminder/supportReminderItems.tsx#L94-L96) for the thank you page.
> fix: use mockdate in storybook

- support-frontend/assets/helpers/redux/checkout/product/selectors/isSupporterPlus.ts
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
This is a hotfix and probably not **_the_** sustainable way to do this.
We will be looking at how data is passed to the thank you page in future which should help with this.
This only applies the promotion if it is `SupporterPlus`. I haven't found the route to how someone got to the checkout with a contribution amount and a `promoCode` e.g. https://support.theguardian.com/uk/contribute/checkout?selected-amount=4&selected-contribution-type=monthly&promoCode=50SPRING2024
The `promoCode` isn't reflected in the UI at that point:
But when the `promoCode` is in the thank-you page URL, it borks:
https://support.theguardian.com/uk/thankyou?promoCode=50SPRING2024
I think this is because we read amount from `localStorage` _OR_ state. Hopefully we can get around this by removing this condition. 
But …
> fix: only show promotion is supporter plus on thank you page

- support-e2e/playwright.base.config.ts
- support-e2e/tests/gwCheckout.test.ts
- support-e2e/tests/newspaperCheckout.test.ts
- support-e2e/tests/oneOffContributions.test.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-e2e/tests/utils/page.ts
- Reduces the timeout on out Playwright tests to avoid uncaught states that do not fail on locking up for a maximum of 2 minutes each, which we've seen accumulate into ~30 minutes in bad circumstanes.
- Sets the `expect.timeout` to the default 5 seconds, but sets a higher value in areas we know will take longer e.g. the thank you page.
- Sets the [`workers`](https://playwright.dev/docs/test-parallel#limit-workers) default of 5, which seems to increase the speed at which the test scenarios are run. @rBangay - was there a specific reason to have limited this?
These changes should create a situation in which we see failures quicker, but also hopefully raise issues where things should happen quick, but doesn't e.g. clicking through to checkout takes 20 seconds for an introduced bug.
> Playwright timeouts

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Following this diagram, this implements the red bounding boxes, namely, **the lowest amounts** in **`Monthly` and `Annual`** being reflected in **Recurring contribution tier (Tier-1)**.
> feat: use RRCP amounts for recurring tier

- support-e2e/playwright.base.config.ts
- support-e2e/tests/gwCheckout.test.ts
- support-e2e/tests/newspaperCheckout.test.ts
- support-e2e/tests/oneOffContributions.test.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-e2e/tests/utils/page.ts
Reverts guardian/support-frontend#5876
I'm reverting these for now because even though testing from local seemed to work a treat, now they're running from CI there's a tonne of errors being thrown.
I'm not sure what the cause of these are, but I'd like to get the tests back up and running while I debug.
> Revert "Playwright timeouts"

- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/pages/digital-subscriber-thank-you/digitalSubscriptionThankYou.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Updating the survey link for the post checkout journey, with a specific link for Australia and the same 3 links for the rest of the world dependant on whether you are making a one off contribution, recurring below the supporter plus treshold and recurring above the supporter plus threshold.
> [RB] - update post support survey links for AU and ROW

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/otherAmount/otherAmount.tsx
- support-frontend/assets/components/priceCards/priceCard.tsx
- support-frontend/assets/components/priceCards/priceCards.tsx
- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
- support-frontend/assets/helpers/__tests__/checkoutsTest.ts
- support-frontend/assets/helpers/forms/checkouts.ts
- support-frontend/assets/helpers/redux/checkout/product/selectors/productType.ts
- support-frontend/assets/pages/supporter-plus-landing/formSections/patronsPriceCards.tsx
- support-frontend/stories/checkouts/PriceCard.stories.tsx
- support-frontend/stories/checkouts/PriceCards.stories.tsx
Maintains the source data type of `number` for `amounts` rather than transforming to `string`.
This tightens the type making it easier to work with as a `number` when doing calculations, and then render to `string` at the rendering edge, rather than having to flip-flop between conversions dependant on context.
This was inspired by wanting to `round` in the `format` methods in a refactor I am doing and the `number | string` type created unnecessary checks.
[These are the examples of wanting rounding to happen at all instances](https://github.com/search?q=repo%3Aguardian%2Fsupport-frontend++promoPriceRounded&type=code).
Compile, E2E and visual tests are passing.
> Use type `number` for amounts

- support-e2e/tests/consent-management.test.ts
Adds a simple E22 test for our CMP integration.
Thought it might have given more confidence in [this PR](https://github.com/guardian/support-frontend/pull/5805) and other changes in the future.
This is the test
> feat: add CMP E2E test

- support-frontend/assets/components/nav/nav.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
I noticed a small layout issue on the VAT Compliant checkout where the horizontal rule at the top of the page was missing. A change went in recently to hide the country drop down (https://github.com/guardian/support-frontend/pull/5808) on the VAT Compliant checkout however the conditional was wrapping the entire `<Nav>` element, the horizontal rule isn't visible when the `<Nav>` isn't rendered, I've moved the conditional to the country drop down element within the `<Nav>` element. 
**Before**
**After**
> Fix layout issue on VAT compliant checkout

- .github/workflows/support-workers-build.yml
- build.sbt
- support-workers/build.sbt
use https://github.com/guardian/actions-riff-raff for uploading support-workers
This means it's more secure (don't expose the riffraff key to the whole build.
Also we can use snapstart (possibly)
I compared the riffraff.yaml generated which is semantically the same, and the file names and sizes that appear in the artifact, and they are identical 
see https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=support%3Asupport-workers-mono&id=18823
> use actions-riff-raff for support-workers

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
`amount` refers the percentage, not the actual price, causing very strange rendering of the total.
|---|---|
| <img width="527" alt="Screenshot 2024-04-11 at 12 22 28" src="https://github.com/guardian/support-frontend/assets/31692/8a3e9deb-6a3d-42a1-b85a-5e138626c430"> | <img width="571" alt="Screenshot 2024-04-11 at 12 22 34" src="https://github.com/guardian/support-frontend/assets/31692/68a8a1a4-6c29-4749-ae07-c812641a1f19"> |
> fix: use discountedPrice not amount

- support-frontend/assets/helpers/supporterPlus/benefitsThreshold.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- Removes checking the promotion value in S+ threshold check.
- Remove application of promotion on non-SupporterPlus products (recurring and one-off)
This was a hangover for when we included the promotion deduction in the `selectedAmount`.
We need to look into why this wasn't caught by the e2e tests and there's a potential to refactor the [`getPromotion` code](https://github.com/guardian/support-frontend/blob/5eb34e324d78d563bb280229b7639683307ae2bb/support-frontend/assets/helpers/productPrice/promotions.tsx#L103) to account for this at the source.
> fix: remove promotion value from S+ check

- support-workers/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/SupporterPlusSubcriptionBuilder.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
We have recently had a bug [documented here](https://docs.google.com/document/d/15P66QvoEPdt3Nd_td5D6FQ2Fm-inrzO04H3GFOnUH2k/edit) which enabled the creation of supporter plus subscriptions with a negative contribution element.
This PR prevents that by failing if the contribution amount is less than zero.
> Prevent creation of a supporter plus sub with a negative contribution

- support-e2e/tests/landingPages.test.ts
V2 of [this PR](https://github.com/guardian/support-frontend/pull/5798) as it's got some nasty conflicts that were harder to fix than replicating the PR.
It doesn't look like the e2e tests in `landingPages.test.ts` were actually testing anything.  This line in the tests `await page.locator("id=qa-paper-subscriptions").isVisible();`, would eventually resolve with `true` (element present) or `false` (element not present) however we didn't do anything with the return value of `isVisible`, so for example I could update the test to look for an element that doesn't exist `await page.locator("id=hello-world").isVisible();` and the test would still pass. The only expectation was to confirm the URL matched what we'd specified it is in the test.
Authored-by: GHaberis <george.haberis@guardian.co.uk>
> Update subscription landing page e2e tests to verify presence of expected HTML element

- support-frontend/assets/components/offer/offer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Minor visual tweaks requested by designers->
- book offer double asterix fontWeight:regular and fontSize:14px
- `to you**` should contain a non-breaking sace so both words wrap onto next line
[**Trello Card**](https://trello.com/c/iJV8lQJc/729-add-book-benefits-copy-to-the-us-landing-pages-and-ty-pages-15th-april-if-possible)
|TierCard2|TierCard3|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/a89118b7-6d8a-4bfe-a46b-7e74cbed3b28)|![image](https://github.com/guardian/support-frontend/assets/76729591/034816c7-929d-451a-84e9-41f3c5a66bb3)|
> Three tier (US book) benefit offers visual tweaks

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Depends on https://github.com/guardian/support-frontend/pull/5910
Uses the `productCatalogDescription` on the checkout.
To make sure we have and use 1 way to describe the product catalog.
> Use productCatalogDescription on checkout

- support-e2e/tests/consent-management.test.ts
Howfix to get e2e tests working. 
We'll follow up with a test that isn't as brittle given we don't control the copy of the CMP.
> fix: use new button label for CMP e2e test

- support-frontend/assets/helpers/legalCopy.ts
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
We were applying the promotion based on `!!promotion.discountedPrice`. This would evaluate to `false` in the case that `discountPrice === 0`.
It is now the case that if the promotion exists, we will apply it. If the `discountPrice` is missing, we will fallback to full price, and if `numberOfDiscountedPeriods` is missing, we will fallback to `0`.
So without neither of those you might expect to see
> You'll pay £10/month for the first 0 months, then £10/month afterwards unless you cancel.
This is odd - but then again it's odd input. If we'd like to guard against this, I'd suggest we do it at the source.
> Allow for 0 `discountPrice` (100% discount)

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
Allows for `0` discount price on contribution checkout.
I thought this was part of https://github.com/guardian/support-frontend/pull/5926 - but I think I managed to rebase it out (as I had actually got a screenshot of it).
|---|---|
| <img width="593" alt="Screenshot 2024-04-17 at 14 51 39" src="https://github.com/guardian/support-frontend/assets/31692/ccceca1a-c789-4595-a72c-d6cdbc7f8cdc"> | <img width="449" alt="Screenshot 2024-04-17 at 12 21 09" src="https://github.com/guardian/support-frontend/assets/31692/a24d3c40-91d0-4fbb-b906-7df373cdc955"> |
> fix: apply promotion on OrderSummary

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/page/page.ts
- support-frontend/assets/helpers/redux/utils/setup.ts
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingProps.ts
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLandingProps.ts
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLandingProps.ts
In https://github.com/guardian/support-frontend/pull/5925 I removed the array `countriesAffectedByVATStatus` from the codebase, and replaced any instances where it had been used (to identify whether a user's country was affected by VAT compliance) with a look-up that checked whether they were assigned to the `VAT_COMPLIANT` amounts instead.
`countriesAffectedByVATStatus` had previously been used in conjunction with the `omitCountries` property in our AB test definitions to make sure users viewing the VAT Compliant checkout weren't registered as participating in AB tests that didn't touch this checkout flow (eg. 3-tier tests). By removing `countriesAffectedByVATStatus`  I removed an easy way to achieve this omission.
This PR restores that by introducing a new prop to our AB test …
> Restore ability to exclude countries subject to VAT compliant Amounts from client-side AB tests

- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/main/scala/com/gu/support/workers/PreviewPaymentSchedule.scala
- support-workers/src/main/scala/com/gu/zuora/ZuoraSubscriptionCreator.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
Fixes a bug whereby discounted annual subscriptions were not told the correct billing information in their thank you email. 
The billing summary in the thank you email is worked out by retrieving a preview of future invoices from Zuora and then using this to generate a description such as '£5.99 every month for 3 months, then £11.99 every month'.
The bug was caused by us only fetching one preview invoice (the one with the discounted price) so the code which works out the message thought the initial price was the regular price.
[**Trello Card**](https://trello.com/c/rj9SSTDl/721-annual-s-ty-email-price-does-not-contain-discount-info)
> Fix discounts not showing in email for annual products

- support-frontend/assets/components/paymentFrequencyButtons/paymentFrequencyButtons.tsx
- support-frontend/stories/landingPage/PaymentFrequencyButtons.stories.tsx
Add to storybook the  `paymentFrequencyButton` to a new (three tier) landingPage section
> Storybook add payment frequency button to (three tier) landingPage section

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the `productFields` needed to `POST` to the `/subscribe/create` endpoint.
Existing types from [`readerRevenueApis`](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts) have been used to avoid replicating more than is needed.
I've hoisted a lot of the product config from the component as it's not needed.
There's a few renames, I'll try annotate them in the PR.
> Add `productFields` in checkout `POST` data

- support-frontend/stories/screens/supporterPlusThankYou/AusSupporterPlusThankYou.stories.tsx
- support-frontend/stories/screens/supporterPlusThankYou/ROWSupporterPlusThankYou.stories.tsx
Part of https://github.com/guardian/support-frontend/issues/5829
- Fixes arg type for decorators
- Check `0` index on countries before dispatching a potentially `undefined` value
> Fix `noUncheckedIndexedAccess` errors on thank you stories

- support-models/src/main/scala/com/gu/support/zuora/api/response/Responses.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala
Adds retry logic for the [Zuora `TEMPORARY_ERROR`](https://knowledgecenter.zuora.com/Zuora_Central_Platform/API/G_SOAP_API/L_Error_Handling/Errors#ErrorCode_Object).
We have seen this error raised a couple times.
> Add retrying for Zuora `TEMPORARY_ERROR`

- support-models/src/main/scala/com/gu/support/zuora/api/response/Responses.scala
- support-workers/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala
Makes the Zuora `TEMPORARY_ERROR` `RetryLimited`.
Based on [this conversation](https://github.com/guardian/support-frontend/pull/5939#discussion_r1574374387) it felt like knowing if a `TEMPORARY_ERROR` was lasting longer than 2 hours, we should know. The example case for this only lasted < 5 minutes, so it feels like designing to real life is a better plan.
> fix: RetryLimited on Zuora TEMPORARY_ERROR

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- SetUp the generic checkout abtest
- Tier1 (Support) Card redirects to the generic checkout only when in the variant
- name = `contribtionGenericCheckout`
[**Trello Card**](https://trello.com/c/UskqYuJO/805-run-a-b-test-that-changes-the-link-on-the-third-tier-card-to-generic-checkout)
https://support.thegulocal.com/uk/contribute#ab-contributionGenericCheckout=variant
From->
To->
> Generic Checkout : abtest contribution setup

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
I had mistakenly inferred the `productId = 'Contribution'` meant `ONE_OFF` payments. 
I've started dropping `TODO`s where we are going to have to think about supporting `ONE_OFF` as it's not actually in the catalog.
This means we now
* use the right stripe key
* show the state selector in relevant countries
* ask for personal details
> Don't use `productId = 'Contribution'` to infer `ONE_OFF`

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- Fixes the field name from where we fetch billing/delivery address
- Sets the billing-address for non-deliverable products
It's interesting that we set the `billingAddresss.country` from the [Fastly geo client](https://www.fastly.com/documentation/reference/vcl/variables/geolocation/) and don't allow a person to reset it.
This would mean the Billing Country could be wrong for people using VPNs etc - so maybe something to look into.
> fix: add billing-address country to non-deliverable products

- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
**Co-authored by:** Andrew Howe-Ely and Lakshmi Pillai
Adding "Student dscounts" on to GW landing page for AUS 
[**Trello Card**](https://trello.com/c/40Out071/395-adding-student-dscounts-on-to-gw-landing-page-for-aus-s?filter=member:lakshmirpillai1)
Guardian Weekly’s student discount has been successful in the UK since launch last year. The Australia team have indicated they would like to launch it in their region as a test, with the aid of diversifying acquisition streams for GW. They see it as a first stepping point onto providing student discounts for Supporter+ etc.
> Add Student Subscriptions to Australia

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Generic order Summary Populated By ProductDescription.benefits & ProductionDescription.label.
Limitations (seperate PR if deemed necessary)->
1. Does not match current checkout summary text, matches ProductDescription benefits list in TierCards only.
2. No bold, styling not defined on ProductDescription benefits 
3. No disabled/enabled extra benefit summary lines, styling not defined on ProductDescription benefits 
|Contributions|S+|
|------|------|
|![image](https://github.com/guardian/support-frontend/assets/76729591/0aaf00d3-21b3-4b3d-993a-c7f274f58e5d)|![image](https://github.com/guardian/support-frontend/assets/76729591/fea100f2-8ede-401a-bbb0-ca24752b6565)|
[**Trello Card**](https://trello.com/c/UskqYuJO/805-run-a-b-test-that-changes-the-link-on-the-third-tier-card-to-generic-checkou …
> Generic Checkout : Order Summary Populated By ProductDescription.benefits

- support-lambdas/it-test-runner/cfn.yaml
Currently these run hourly.
There's a limit on salesforce records in the sandbox, and zuora will also be enforcing limits soon.
Reducing integration test runs will help reduce our usage
> Run integration tests every 6 hours

- .github/workflows/compressed-size.yml
Adds recursive file checking for our `comrpessed-size-action`. I need this because [we have added a folder structure in the `webpack.entryPoints` which was missing the new `checkout`](https://github.com/guardian/support-frontend/blob/main/support-frontend/webpack.entryPoints.js#L3).
> feat: add recursive file matching on compressed-size action

- support-lambdas/it-test-runner/cfn.yaml
We recently changed these to run every 6 hours - https://github.com/guardian/support-frontend/pull/5959
This has triggered an alarm that checks if the metrics are being reported regularly.
> Update integration test 'not running' alarm

- .github/workflows/compressed-size.yml
- docs/adrs/2024-04-29-re-introducing-react-router.md
- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/router.scala.html
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/geoIdConfig.ts
- support-frontend/conf/routes
- support-frontend/webpack.entryPoints.js
- Uses `react-router` to encapsulate the `landing => checkout => thank-you` journey
- Adds the concept `GeoIdConfig` which is config that is variable on the `/{geoId}` segment of the URL
- Changes the `checkout` name for the route to `router` in the play app
- Copy/pastes the values dependant on the `geoId` in the checkout component into the component
I'm doing this because when setting up a whole new route for the thank you page from Play => rendering, the boilerplate was becoming immense and unwieldy. This replicates the pattern we had setup for `/{geoId}/contribution` from [Play](https://github.com/guardian/support-frontend/blob/main/support-frontend/conf/routes#L57-L69) => [Router](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/pages/supporter-plus-landi …
> Use react router for landing => checkout => thank-you route

- support-frontend/app/controllers/CreateSubscriptionController.scala
A quick update to link for user-features as frontend nor flow is no longer used.
> fix: update link to user-features.ts in DCR

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
Adds the thank you page to the generic checkout.
This uses a explicit object in session storage:
```JSON
{
"value": {
"firstName": "???",
"price": 5,
"product": "Contribution",
"ratePlan": "Monthly",
"paymentMethod": "Stripe"
}
}
```
This will last **only** for the session, and will be deleted if you visit the checkout again (the only place that sets it).
> feat: thank you page for generic checkout

- .github/workflows/chromatic.yml
- support-e2e/tests/consent-management.test.ts
Refines the search for the "Yes/No" buttons to
* Be a button
* Have only "Yes" or "No" in
This is slightly reactive to the work going on in CMP - so if it happens again, we might have to re-think - but we should have a test that CMP is working so maybe the `isVisible` test is enough.
We've updated the chromatic action to use `v11.3.0` as [`v11.3.1`](https://github.com/chromaui/action/commit/d208304630e76d960a80b9db40a838eb8babcebe) seemed to have introduced a bug.
If we update to `v11.3.1` - we'll need to add the `storybookBaseDir: "support-frontend"` to the Chromatic action.
> fix: refine cmp e2e test to buttons and simpler text

- support-frontend/assets/helpers/abTests/abtest.ts
Adds descriptions as to why we use the `non-null-assertions`.
This avoids this 👇 in PRs which always muddies the water.
[This was added in this PR](https://github.com/guardian/support-frontend/pull/5928/files) and should probably be refactored around with better typing rather than forced - but it's worked for ages as is.
> fix: describe why it is OK to use non-null-assertion

- support-frontend/stories/landingPage/ThreeTierCards.stories.tsx
Removes a stray `;` I noticed in a chromatic review.
> fix: remove ;😀

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- Check abTest `useGenericCheckout=variant` Tier1 routes to generic checkout
- Correct Tier ParamUrl contains `price` instead of `amount`
[**Trello Card**](https://trello.com/c/zFskeauG/835-a-b-test-setup)
|from|to (paramurl)|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/d7ff8ef0-8744-4859-ac90-2629928da63d)|![image](https://github.com/guardian/support-frontend/assets/76729591/aa137001-2966-4b97-93fd-540bd98ce341)|
https://support.thegulocal.com/uk/contribute#ab-useGenericCheckout=variant
> Generic Checkout: Tier1 param url amount changed to price

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Part of #5722 
* Removes the use of `PersonalDetails` component as the error API of that component was becoming difficult to integrate with. The abstraction isn't used anywhere that the checkout isn't going to make obsolete, so it's a little bit of code now, for less later.
* Adds validation using [browser APIs](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation). [The `ValidityState` is good to use in browsers we support](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState#browser_compatibility). I might try push this upstream to Source in a later PR once we've ironed some of this out.
It is probably easier to view this PR via [this commit](https://github.com/guardian/support-frontend/commit/fc8a1fc934bac0e44192b68124edfffa4832673c) and then [this …
> Personal details form validation

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
[Uses `CountryHelper.detect()` reads and also sets the `GU_Country` cookie](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/internationalisation/classes/country.ts#L245-L283).
> fix: detect countryId which also sets the GU_Country cookie

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
BAID corrected  for PayPal (set BEFORE form submitted). Checkout operating as expected
[**Trello Card**](https://trello.com/c/ihabrisb/802-form-validation-for-generic-checkout)
> Generic Checkout : PayPal Payment Request gets BAID

- support-frontend/assets/components/priceCards/priceCardsContainer.tsx
- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/package.json
Updating the cookie set on the second step of the checkout (#5972) with the updated amount when a user selects a different amount in the one-off contribution component.
[**Trello Card**](https://trello.com/c/5NzPmZK0/438-abandoned-basket-update-cookie-when-one-off-amount-changes)
To keep the cookie as up to date as possible with the last thing a user selected on the checkout.
Go to `/contribute/checkout?selected-contribution-type=one_off` and see the `GU_CO_INCOMPLETE` cookie update the amount when choosing different amounts, including `other`
> Abandoned basket update cookie when one off amount changes

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/router.scala.html
- support-frontend/app/views/windowGuardianPaymentConfig.scala.html
Adds the `user` to the checkout route.
- Adds a `user` object to `window.guardian` if a person is signed in
- Keeps this object as narrow as we need for https://github.com/guardian/support-frontend/pull/6000
- Doesn't use this for the `contributions` route to avoid bugs
> feat: add user to router

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
[Reviewing without whitespace is easier](https://github.com/guardian/support-frontend/pull/6003/files?w=1).
Part of #5722 
Adds the styles to the payment methods for the generic checkout.
I've avoided using [Source's `Accordion`](https://github.com/guardian/csnx/blob/main/libs/%40guardian/source-react-components/src/accordion/Accordion.tsx) as it provides none of the functionality and we override nearly all of the styles. I think this is because they are quite different use cases as you can [see in the design system](https://theguardian.design/2a1e5182b/p/38c5aa-accordion).
If we wanted to use this I imagine we would build an `AccordianSansStyles`, and then add themes. Maybe worth using the new design system process we have setup for this? …
> Add styles to payment methods on generic checkout

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Part of #5722 
- Uses and displays legends for Contribution checkout
- Adds Secure checkout SVG to payment details `fieldset`
I know that the `1.`, `2.`, `n.` won't work when we have delivery fields, I will reach out to Helene and see if there is a generic design solution to this.
[Worth avoiding whitedspace check in the diff](https://github.com/guardian/support-frontend/pull/6002/files?diff=unified&w=1).
|---|---|
| ![Screenshot 2024-05-14 at 15 44 26](https://github.com/guardian/support-frontend/assets/31692/b5c38be3-7fba-4cc2-8761-e00a02d907ae) | ![Screenshot 2024-05-14 at 15 44 11](https://github.com/guardian/support-frontend/assets/31692/caff5932-4e47-4715-a466-9a62826d4eab) |
> Add legends and secure checkout SVG to checkout

- support-e2e/tests/genericCheckout.test.ts
- support-e2e/tests/tieredCheckout.test.ts
Change generic Checkout Playwright tests to incorporate paymentType name changes ->
DirectDebit => Direct debit
Stripe=> Credit/Debit card
Change payment button check to include non-rounded amounts ie
£100 => £94.92
> Generic Checkout : Playwright PaymentType Fix

- support-frontend/assets/components/personalDetails/personalDetailsContainer.tsx
- support-frontend/assets/components/personalDetails/stateSelect.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Ensure Personal Details fields validate after editing when loose focus (onChange/onStateChange).
[**Trello Card**](https://trello.com/c/ihabrisb/802-form-validation-for-generic-checkout-state-zipcode)
> Generic Checkout: Personal Detail Fields Validate via OnChange 

- support-frontend/app/controllers/DiagnosticsController.scala
This PR removes the gu_contributions_reminder_signed_up cookie from the Diagnostics as it is no longer set.
[**Trello Card**](https://trello.com/c/GN0qOTJw/103-remove-gucontributionsremindersignedup-cookie)
The cookie has already been removed and is no longer set anywhere as confirmed by a full search of The G organisation in GitHub.  We are therefore removing it from the Diagnostics endpoint.
co-authored-by @andrewHEguardian
> Remove unused gu_contributions_reminder_signed_up cookie

- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
Fix the error message logged when the abandoned basket cookie fails to parse.
There a lot of sentry exceptions for failed parsing of the cookie, but the error message wasn't formatted correctly so can't see the actual parsing error.
Once we see what the errors are we can fix the issue, and potentially don't want this logged as an exception 
Running locally, go to one time checkout, manually edit the `GU_CO_INCOMPLETE` cookie to be invalid, and see error in console with readable error message.
> Abandoned Basket Cookie: fix valibot parsing error message

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
- support-frontend/webpack.dev.js
Removes the TT widget JS and uses an iframe directly.
What we lose is the iframe resizing capability, but this is OK as it's currently not working. This is with TT and they are raising a case for it.
This is mainly to allow people to test the flow E2E.
Weirdly it did work ([you can see it in this PR](https://github.com/guardian/support-frontend/pull/5980)) - I am not sure what has changed.
https://github.com/guardian/support-frontend/assets/31692/e81910f7-1dd1-4bd1-aad2-7ded0861bbe7
> fix: add hack to ticket tailor iframe sizing

- support-frontend/assets/pages/aus-moment-map/components/map.tsx
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.tsx
- support-frontend/package.json
- support-frontend/yarn.lock
Reverts guardian/support-frontend#6015 something about updating preact from 10.7.1 to 10.22.0 introduced a noticeable flash of unstyled content, as seen below. Quickest thing we can do is revert and look into this.
https://github.com/guardian/support-frontend/assets/1590704/296af959-4ac7-4264-ba97-1d340a76e37c
[Trello](https://trello.com/c/p2ghoWMI/871-flash-of-unstyled-content-on-3-tier-checkout-pages)
> Revert "build(deps-dev): bump preact from 10.7.1 to 10.22.0 in /support-frontend"

- cdk/lib/__snapshots__/acquisition-events-api.test.ts.snap
- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/acquisition-events-api.ts
- cdk/lib/bigquery-acquisitions-publisher.ts
- Migrate alarms for bigquery-acquisitions-publisher
- Refactor SNS topic for acquisition-events-api to not use hard-coded strings
> feat: migrate alarms for bigquery-acquisitions-publisher

- support-frontend/assets/__mocks__/settingsMock.ts
- support-frontend/assets/helpers/globalsAndSwitches/settings.ts
The property is not set or used anywhere, so assuming it's legacy and removing it. 
This is part of an effort to get parsing between server & client a little tighter.
> refactor: remove experiments from settings

- support-frontend/assets/helpers/user/user.ts
Remove option types from User type and use the more idiomatic optional parameter.
This is part of a larger piece of work to help with parsing between server and client.
> refactor: remove option types from user

- support-frontend/app/admin/ServersideAbTest.scala
Having an encoder for `Map[K, V]` is not necessary as circe has these build in.
The reason for removing this is it is creating conflicts on the `implicits` when I import these types into parts of the code that have semi-automatic derivation creating two possible encoders which the compiler doesn't know which to pick.
> Remove unnecessary encoder

- support-workers/cloud-formation/src/templates/cfn-template.yaml
[Using the alarms handler to handle the alarms](https://github.com/guardian/support-service-lambdas/pull/2295)
> Move support-workers alarms to alarms-handler

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- adds the back / change button to the generic checkout.
> Add checkout back button

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
Ticket Tailor has fixed the issue with cross-origin iframe communication.
This re-instates the use of the widget over just having an iframe.
> Reinstate the ticket tailor widget

- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the Ts & Cs to the summary on the checkout.
> Add Ts&Cs to price summary on checkout

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
This adds [`data-link-name` tracking](https://github.com/guardian/ophan/blob/a69e354d1bec4c0ba206a75fc62ea77a34f19a66/tracker-js/assets/click-path-capture.js#L31-L45) to the country `select`. I want to use this data to have an indication of how often we get the country wrong to help inform UX later on.
> Add ophan tracking to country select

- support-e2e/tests/tieredCheckout.test.ts
We've updated the CTA copy on the 3-tier landing page, so the e2e test need updating so they can find it.
> Fix e2e tests: update the cta selector on the 3-tier landing page

- support-e2e/tests/genericCheckout.test.ts
We need to update the tests to work with the changes implemented here https://github.com/guardian/support-frontend/pull/6049
(Note to self, we really need to get these tests running on PR).
> Update button text on pay button on e2e tests

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
Uses "You subscription" as a heading for subscription products on checkout
|---|---|
| ![Screenshot 2024-06-04 at 10 29 24](https://github.com/guardian/support-frontend/assets/31692/d27885fa-078a-42e6-8fd8-f44c5f5ac0f3) | ![Screenshot 2024-06-04 at 10 29 34](https://github.com/guardian/support-frontend/assets/31692/178ebe5d-d126-4e13-b44e-a425b9666ee7) |
> fix: use Your Subscription in checkout heading

- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/PaperSubscriptionController.scala
- support-frontend/app/controllers/PayPalOneOff.scala
- support-frontend/app/controllers/PayPalRegular.scala
- support-frontend/app/controllers/Promotions.scala
- support-frontend/app/controllers/SubscriptionsController.scala
- support-frontend/app/controllers/WeeklySubscriptionController.scala
- support-frontend/app/lib/CustomHttpErrorHandler.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/eventsRouter.scala.html
- support-frontend/app/views/main.scala.html
- support-frontend/app/views/router.scala.html
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/app/views/subscriptionRedemptionForm.scala.html
Makes the CSS `RefPath` optional for pages that aren't using CSS (and shouldn't be as this is the CSS generated via SASS).
[Fixes this bug](https://support.theguardian.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly) where the `RefPath` is not being found. This is a runtime error so wasn't picked up on hence I have attached the Playwright test results.
> fix: make css RefPath optional

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
This activate the `useGenericCheckout` test and removes the variant which would push traffic to the new checkout.
The reason to do this is to start collecting data where `ab_test.name=useGenericCheckout` in some dashboards before we launch.
> Activate `useGenericCheckout` test without variant

- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
When setting the abandoned basket cookie always use an uppercase version of the billing period.
[**Trello Card**](https://trello.com/c/laOsfKVH/476-abandoned-basket-set-cookie-with-billing-period-in-uppercase-always-support-frontend)
In the Guardian Weekly [checkout](https://github.com/guardian/support-frontend/blob/8ae6b184bcb6ec1605791a5bcb2fbf3789cdecf7/support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx#L231) we set the billing period in lower case, however in the other contributions checkout and the [schema](https://github.com/guardian/support-dotcom-components/blob/82e89beb6d516025611cfddaaf39022598bfc07c/packages/shared/src/types/targeting/shared.ts#L40) we expect an uppercase value. 
Go to Weekly checkout in 3 tier proposition and see …
> Abandoned Basket: Always set billingPeriod in uppercase in cookie

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
In prep for starting the work on using the checkout for the new S+ `ratePlans` - this
- adds those `ratePlans` to the `productCatalog` 
- moves `deliverableTo` to the `ratePlans` as it is no longer generalised to the product, but rather to the `ratePlans`
> Add new S+ `ratePlans` and move `deliverableTo`

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
Adds QA and GA analytics as per [the old thank you page](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx#L188-L216).
I haven't added the Ophan `trackUserData` due to our discussions that we are going to trim our tracking footprint as part of this migration.
There is still the idea of the `contributionType` on the thank you page that we are going to have to unpick. I don't want to block the checkout test for that though, so this is to parity, and we will do a little more as we move onto other products.
> feat: add QM and GA tracking to thank-you

- support-frontend/package.json
- support-frontend/yarn.lock
Updated the browserlist in response to this message which appears whenever you try to build the frontend assets (.js, .css) for `support-frontend`
> update browserlist dependency

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds `fulfilmentOptions` to the `SupporterPlus` product on the checkout based on the new `GuardianWeekly` `ratePlans`.
This is then [picked up by `support-workers`](https://github.com/guardian/support-frontend/pull/5968) and makes it way through the pipes. Thank @AndreaDiotallevi and @rupertbates!
I think it is about time we relook at the parsing and error handling.
> feat: add fulfilmentOptions to SupporterPlus

- support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the [Source isLoading prop](https://guardian.github.io/storybooks/?path=/story/source_react-components-button--is-loading-primary) to the Pay button.
I updated the text to be more specific about what triggered the load to add clarity.
I've done pass-
https://github.com/guardian/support-frontend/assets/31692/320888f9-97a3-43d8-bf79-866ddc852a17
thru props to the button to make change quicker.
> Add `isLoading` to checkout button

- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
Remove the logic to set the abandoned basket cookie for tier three of support/Guardian Weekly
The cookie set from the third tier checkout (Digital + Print) and the Guardian Weekly checkout (just Guardian Weekly) are identical - so we can't easily recreate the URL to return a user back to the same step in the checkout.
Go to `/subscribe/weekly/checkout?period=Monthly` and do not see `GU_CO_INCOMPLETE` cookie set.
Traffic for the 3rd tier is relatively low - so it should be fine to exclude this option from the abandoned basket test.
> Don't set abandoned basket cookie for guardian weekly checkout

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Sets `isTestUser` based on their cookies.
Completely missed this. No harm done, we rolled back and [reverted](https://github.com/guardian/support-frontend/pull/6087).
We missed this as we hadn't tried a transaction as a non-test user. We'll make sure we do this pre-turning the test back on.
> fix: dynamically set isTestUser on checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#6087
We fixed the issue here: https://github.com/guardian/support-frontend/pull/6088 and tested live payments.
> Revert "Revert "chore(test): activate `useGenericCheckout` test""

- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierLozenge.tsx
Takes the text from the promo tool (called `roundel`) and, if present, uses it instead of "Recommended" on the tier card.
There has been no text limi imposed, we could recommend this to editors or enforce it on the tooling side.
> feat: use roundel text on lozenge on product cards

- support-frontend/app/services/pricing/PriceSummary.scala
- support-frontend/app/services/pricing/PriceSummaryService.scala
- support-frontend/test/controllers/PricesControllerSerialisationTest.scala
- support-frontend/test/controllers/PricesControllerTest.scala
Adds `starts` and `expires` to the `PromotionSummary` model for us to be able to use in in the rendering of the Ts and Cs for promotions.
> feat: add starts and expires to PromotionSummary

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the TierThree product to the frontend.
- Adds it to the `productCatalogDescription`
- Adds it to the types (this could use a nice little refactor)
- Adds it to the `productFields` of the checkout to `POST` to the `create` endpoint.
- Removes unused `ratePlans` from `SupporterPlus`
- hoists `deliverableTo` back into the product as we no longer need it per `ratePlan`
[The error is because the `support-workers` needs updating (coming soon 🥳)](https://github.com/guardian/support-frontend/pull/6090)
> Add TierThree product to checkout

- support-frontend/build.sbt
the /test-users page was breaking with an error
JsResultException(errors:List((/locale,List(JsonValidationError(List(error.path.missing),List())))))
This PR seems to fix it - tested locally and in CODE.
Probably due to this fix https://github.com/guardian/play-googleauth/pull/218
I also raised this PR (edit: which has now been merged and released as 8.0.1), as we shoudl not be writing exception information to the UI
https://github.com/guardian/play-googleauth/pull/233
> update google auth library

- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
Create an AB test definition for the abandoned basket banner. If a user is in the variant - drop a cookie which will surface a banner on dotcom.
[**Trello Card**](https://trello.com/c/T7RKwJI9/475-abandoned-basket-special-ab-test)
We need to be able to analyse the overall revenue brought in by the new abandoned basket banner, to do this we will have a control group who do not see this new banner, and a variant who will see the banner.
Go to https://support.thegulocal.com/uk/contribute/checkout?selected-amount=3&selected-contribution-type=monthly#ab-abandonedBasket=variant and see the `GU_CO_INCOMPLETE` cookie.
Go to https://support.thegulocal.com/uk/contribute/checkout?selected-amount=3&selected-contribution-type=monthly#ab-abandonedBasket=control and do not see a `GU_CO_INCOMPLETE` …
> Abandoned Basket: create AB test

- support-e2e/tests/tieredCheckout.test.ts
Fix failing playwright test by adding the hardcoded AB test URL to the tiered checkout test. It failed because the test asserts the `GU_CO_INCOMPLETE` cookie is set. However this is only set in the variant.
Tested locally on playwright.
> Fix Playwright: Hardcode ab test url for abandoned basket cookie

- support-frontend/assets/helpers/redux/selectors/formValidation/personalDetailsValidation.ts
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
We would like to make the US ZipCode field non-mandatory (ie Displayed but not required to be filled in to checkout).  Currently this affects->
1. US Contributions : Contribution Checkout
2. US Recurring S+ Contributions : Contribution Checkout
3. US Recurring Contribution: Generic Checkout
This is the client-side aspect ONLY. Server-side aspects to be determined in follow-up PR.
As part of a change we made in Sep’23 we changes both the position of the Zipcode and made it mandatory , that has lead to an issue with Apple and Google pay payment in the US , as in these fail when the mandory field is not filled.
[**Trello Card**](https://trello.com/c/Cpvg3n5l/896-zipcode-make-it-non-mandatory-on-the-checkout-page-for-single-recurring-and-s-for-us)
> Non mandatory ZipCode in US checkout

- support-frontend/assets/helpers/__tests__/urlTest.ts
- support-frontend/assets/helpers/tracking/NavigateWithPageView.tsx
- support-frontend/assets/helpers/tracking/ophan.ts
- support-frontend/assets/helpers/urls/url.ts
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
Currently when a user lands on the 3-tier landing page via the Banner / Epic having pre-selected a single contribution amount we automatically redirect them to Page 2 of the checkout, the single contribution checkout form using client-side routing via React-Router-Dom's  `<Navigate>` component. The issue is we don't notify Ophan, so Ophan's data indicates they are still on Page 1 (`/contribute`) rather than Page 2 (`/contribute/checkout`) when they checkout. This has caused some issues in Data Analysis. 
Data Design have requested we notify Ophan that a user has landed on Page 2 via a new Page View event. I've therefore set-up a `<NavigateWithPageView>` component that wraps React-Router-Dom's  `<Navigate>` component and fires a new Ophan Page view. 
**Test url:** …
> NavigateWithPageView

- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
As per this pr https://github.com/guardian/support-frontend/pull/6092 - we'd like a querystring param on the thank you page to aid with tracking drop-off.
- **current:** `/uk/thankyou` | `/uk/thank-you`
- **next:** `/uk/thankyou?product=Contribution` | `/uk/thank-you?product=Contribution`
> feat: add product query param to thank you  pages

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Adds an A/B test to have the `TierThree` card be populated from the [product catalog API](https://product-catalog.guardianapis.com/product-catalog.json).
Next steps would be getting the promo codes to work.
> feat: add abtest to have Tier Three on landing page from api

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Ts&Cs moved to white background, font theme should be dark default
|From|To|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/1887ea18-2eaa-4507-bc39-e71b73278122)|![image](https://github.com/guardian/support-frontend/assets/76729591/b55ef171-e155-4e66-83ff-116e4f2e138e)|
> Ts&Cs moved to white background, font theme should be dark default

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
[In a PR that had a hard-to-read diff](https://github.com/guardian/support-frontend/commit/4d56bd5a6a0a9052f41b6c9b69bc76d0b059ecf1#diff-1673db1c74e930dd41928f75fce7d8c3dbf52774becd7e891adfc034a8b7c19cL121-R121) - we inadvertantly deactivated the three tier test.
I'll let D&I know about this.
> fix: reactivate useGenericCheckoutTest

- support-e2e/tests/genericCheckout.test.ts
- support-e2e/tests/landingPages.test.ts
- support-e2e/tests/oneOffContributions.test.ts
- support-e2e/tests/tieredCheckout.test.ts
As per testing libraries ideology:
> [The more your tests resemble the way your software is used, the more confidence they can give you.](https://testing-library.com/docs/guiding-principles)
This checks for a "thank you" `heading` on the page, rather than checking the URL, which, from a users perspective, is irrelevant 🐘.
We have extended this to subscription pages too.
> fix: do a heading check for thank you pages e2e test

- support-frontend/assets/pages/supporter-plus-landing/components/patronsMessage.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Copy Change to US support another way as shown. 
Affects:-
1. ThreeTierLanding Page
2. Patrons Checkout message
[**Trello Card**](https://trello.com/c/T0tvhsgX/873-copy-change-on-3-tiers-lp-the-us)
|Before|After|
|-----|-----|
|![image](https://github.com/guardian/support-frontend/assets/76729591/1cce5dba-61c1-4ae5-bf8f-d8a7d0a74604)|![image](https://github.com/guardian/support-frontend/assets/76729591/e01316ad-3a7c-4d12-b011-a67900295356)|
FROM: `To learn more about other ways to support the Guardian, including checks and tax-exempt options, please visit our `[help page](https://manage.theguardian.com/help-centre/article/contribute-another-way?INTCMP=gdnwb_copts_support_contributions_referral)` on this topic.`
TO : `If you are interested in contributing through a donor-advised fund, …
> US Support another way, copy change

- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
we should first check if the acquisition event was successfully written to BigQuery before replaying it from the DLQ
> Update bigquery-acquisitions-publisher alarm description

- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/bigquery-acquisitions-publisher.ts
This alarm is now too long, causing the deploy to fail
> Shorten alarm description

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Uses international pricing for `int` on tier three of the landing page.
|---|---|
| ![Screenshot 2024-06-19 at 13 59 15](https://github.com/guardian/support-frontend/assets/31692/4f8ce26d-d5e6-4a8d-92a5-d3c293977c41) | ![Screenshot 2024-06-19 at 13 54 56](https://github.com/guardian/support-frontend/assets/31692/e0e5617f-7fc6-4e43-ad90-d0014293db58) |
> fix: use international pricing for int on tier three

- support-frontend/assets/components/paymentButton/defaultPaymentButtonContainer.tsx
- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
Currently we use the backend to remove this cookie for recurring/subscriptions.
But we also need to delete it for single contributions. This PR adds logic to the CTA click handler to do this
> Remove abandoned basket cookie when cta clicked

- support-frontend/app/controllers/Application.scala
- support-frontend/app/services/ProductCatalogService.scala
Reads the product-catalog from [`CODE`](https://product-catalog.code.dev-guardianapis.com/product-catalog.json) when you are in `DEV`, `CODE` or a test user. 
This allows us to test updates to the catalog in `DEV` from `CODE`
> Read product catalog from CODE in DEV & CODE

- support-e2e/tests/genericCheckout.test.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Be price dynamic in our E2E tests.
This has come at a cost of
- readability
- annoyingly, being more whitespace sensitive
I think at a time of high rate of change - these tests really do help ensure we're not breaking core functionality, so this is a decent payoff. I assume we'll get to redinfing these once we reach a more stable set of user journeys.
Annoyingly I am not confident as I think they are failing in letting us know they're failing. I'll be looking into this next.
> fix: be price dynamic in e2e tests

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/__tests__/tierThreeDeliveryDays.ts
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.ts
- support-frontend/package.json
- support-frontend/yarn.lock
For the Tier Three (t3) product we want users to be able to cancel within 14 days without being charged as this is a regulatory requirement in some jurisdictions.
To do this we set the first delivery date of the Guardian Weekly part of the subscription, which is the date
on which the first payment will be taken, to be at least 14 (actually 15 to be safe) days from today.
> Add a function to work out the correct first delivery date for T3

- support-frontend/app/services/ProductCatalogService.scala
To help ensure the new prices are picket up as quickly as possible, we want to refresh the cache of the [Product API](https://product-catalog.guardianapis.com/product-catalog.json) every minute.
> Update ProductCatalog every minute

- support-frontend/app/views/testUsers.scala.html
as per this PR https://github.com/guardian/members-data-api/pull/1088, we now use email address not first name to detect test users in MDAPI/manage
This PR updates the bumf on the test users page to illustrate that.
> update docs for test user page

- support-frontend/assets/helpers/productCatalog.tsx
Adds a type alias of `ProductId` => `string`. 
This way features implementing anything to do with the product catalog could use this type and as we make it stricter, all should be good, but we'll pick up on the errors.
The reason to not do it properly now is that [we have a use case](https://github.com/guardian/support-frontend/pull/6129#discussion_r1655120195), and it will take a few minutes / hours to update this as it's used a lot across the checkout.
> refactor: add pseudo ProductId type

- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Setting the Abandoned Basket cookie on the generic checkout.
[**Trello Card**](https://trello.com/c/fJQjsvzY/513-enable-abandoned-basket-cookie-on-new-checkout)
The generic checkout is being AB tested at the same time as the abandoned basket banner. Currently the cooke is not set on the generic checkout, which means we're losing out on some potential banner views.
Go to `https://support.thegulocal.com/uk/contribute#ab-useGenericCheckout=variant`, select tier one.
Then add `#ab-abandonedBasket=variant` to the URL.
See `GU_CO_INCOMPLETE` cookie set.
The banner CTA URL goes to the existing checkout, not sure if this is a risk.
> Set abandoned basket cookie on generic checkout

- support-frontend/app/services/PayPalNvpService.scala
We are seeing PayPal acquisitions with the users email address in the postcode/zip code field. This PR adds more logging to  see whether the problem might be in the data returned from PayPal.
> Log the response from PayPal in PayPalNvpService

- support-frontend/assets/components/offer/offer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Tidy up the US book offer AB test, but keep the benefits component for future use.
[**Trello Card**](https://trello.com/c/98SiCSTO/907-clean-up-usfreebookoffer-ab-test)
The test has been inactive since #5956 
Checkout Supporter Plus in US, do not see book offer.
> Clean up US book offer AB test

- support-frontend/app/controllers/TestUsersManagement.scala
- support-frontend/app/views/testUsers.scala.html
- support-frontend/build.sbt
use lower case only test user tokens by pulling in updated library - see https://github.com/guardian/identity-test-users/pull/10
I have tested locally and it generates test users that work with MDAPI locally.
Also the test-users page is updated accordingly
> use updated test users library to produce lower case only tokens

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/helpers/productCatalog.tsx
Update the copy of the Feast benefit in tier 1 and 2 non-generic checkouts, and add it as a missing benefit to tier 1 generic.
[**Trello Card**](https://trello.com/c/pkmsmREF/949-change-copy-on-checkout-pages-dropdown-menu-for-feast-tier-2-checkout-page)
Non-generic
Go to `/uk/contribute/checkout?selected-amount=12&selected-contribution-type=monthly` and see benefit. 
Go to `/uk/contribute/checkout?selected-amount=4&selected-contribution-type=monthly` and see benefit greyed out.
Generic
Go to `/uk/checkout?product=Contribution&ratePlan=Annual` and see benefit greyed out.
Before
After
Before
After
> Update feast copy

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
GW ThreeTier Checkout incorrect, thankyou page incorrect.
ParamUrl was setback from `threeTierCreateSupporterPlusSubscription=true` to  `threeTierCreateSupporterPlusSubscriptionV2=true`.
V2 had been deprecated here -> [**PR here**](https://github.com/guardian/support-frontend/pull/6147/commits/fdc7fd5e6e53844bcad5bd64f260380daf7f8693)
And reset accidentally here -> [**PR here**](https://github.com/guardian/support-frontend/pull/6146/commits/becb0636f33b1c025faa877c98d575b637364e47)
> TierThree : GW Checkout and GW ThankyouPage re-correction

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
`productPrices` is used throughout the codebase, mostly in redux, so is used a lot in the redux state. This reinstates it in the contributions template.
We were trying to be more specific in our naming, but unfortunately this coupling caught us. We started to explore using the more explicit naming, but realised that the coupling is quite deep. 
Given that we are hoping to deprecate this template, and thus this implementation, I have just sign-posted how we use the values.
> fix: reinstate productPrices on contributions template

- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListContainer.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsListData.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummaryContainer.tsx
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/checkoutLayout/CheckoutBenefitsList.stories.tsx
- support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx
- support-frontend/stories/content/CheckmarkList.stories.tsx
Add support for regionalised benefits on landing page, generic and contributions checkout and a specific partner offer benefit in Australia.  🇦🇺
[**Trello Card**](https://trello.com/c/ltQnm7HS/925-aus-partner-offers-copy-add-on-tier-2-lp-checkout-drop-down-menu)
New benefit specifically for Australia - and in future we may want other regionalised benefits.
Go to `au/contribute`, checkout tier 1 or tier 2 and see new benefit for tier 2. 
Go to `uk/contribute`, checkout tier 1 or tier 2 do not see new benefit.
AU Landing page 
AU Generic checkout
AU Contributions checkout
> Regionalised benefits and AUS partner offers

- support-frontend/app/controllers/DigitalSubscriptionController.scala
- support-frontend/app/controllers/DigitalSubscriptionFormController.scala
- support-frontend/app/controllers/PaperSubscriptionFormController.scala
- support-frontend/app/controllers/WeeklySubscriptionFormController.scala
- support-frontend/app/views/subscriptionCheckout.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-workers/src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
- support-workers/src/main/scala/com/gu/threadpools/CustomPool.scala
Currently when trying to purchase [a digital edition](https://support.theguardian.com/uk/subscribe/digitaledition) - the loading screen never makes it to the thank you page as it breaks  when trying to read the `productCatalog`.
The purchase is still made, and emails sent, the user just never get's the feedback from the web UI that the transaction was successful.
As this template is used by all subscription checkouts, we needed to add it to all the controllers. This hopefully creates a little consistency in the short term.
Long term we are going to deprecate these checkout with the generic checkout.
> fix: add productCatalog to subscriptionCheckout

- support-frontend/app/controllers/Promotions.scala
support-frontend has some funtionality where a user can put in a url in the form `/p/[promocode]` and they will be redirected to the landing page for the particular product which the promo applies to.
It seems that this functionality has been forgotten about when recent products (supporter plus and tier three) have been added, so any promotions for those products which were sent through this endpoint were causing 500 errors.
This PR provides a default case for any unknown product types which is to redirect to the main three tier landing page. This is correct for supporter plus and tier three, and is better than an error page for any future products that we might develop.
> Provide a default product match for /p/ endpoint

- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
Fixing the decode to include TIER_THREE in the AcquisitionProduct after failure.
Fix missing item from decoder.
> Add tier three to decoder as quick fix

- .github/workflows/playwright.yaml
Alerts our SR dev team channel when the github action timeouts, or fails for a reason outside of the Browserstack context.
This is a reactive fix due to the fact that if a test suit in Browserstack takes more than the timeout, we abruptly disconnect, but don't get the failure state from browserstack and thus not alert.
We get into this state as some bugs can just leave the browser hanging without failing. We are going to do some more work around mitigating against this in the tests, but this will at least be a catch-all given that these tests are integral to catching system errors.
> feat: alert on e2e test timeouts

- support-e2e/playwright.base.config.ts
- support-e2e/playwright.local.config.ts
- support-e2e/tests/gwCheckout.test.ts
- support-e2e/tests/newspaperCheckout.test.ts
- Removes the large, global `expect` timeout in favour of only using long running `expect` assertions for the thank-you page wait
- Removes the `workers` settings as this is set automatically to the best it can be i.e. `"Defaults to half of the number of logical CPU cores"`. We only have 1 in CI, so it runs with 1 worker.
None of this is expected to speed up our playwright tests, but simplifies the config to help make impactful changes.
> Simplify playwright config

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
Bots regularly hit the loadbalancer probing for vulnerabilities. Most result in a 4XX from the server.
But Play handles unknown http methods by returning a 501. This is a problem because it triggers our 5XX alarm. We don't want to change the threshold for that alarm as in general we _do_ want to know when the server returns errors.
E.g. from the logs:
`Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: IOLFJZ`
This PR adds a loadbalancer target rule to only route requests with supported http methods to the server. Anything else will receive a 400.
Tested by making a single contribution in CODE
> payment-api: block unsupported http methods

- support-e2e/browserstack.config.ts
- support-e2e/tests/utils/recaptcha.ts
The reCaptcha can take more than the default `5000` milliseconds, so we've made it `10000`.
Standardising around the e2e naming as well.
> fix: up the timeout for recaptcha in our e2e tests

- support-e2e/tests/oneOffContributions.test.ts
Upping the PayPal timeout as it was failing at 5 seconds.
It feels like PayPal should be able to handle this - it might be because it's a sandbox,  but still feels a little slow.
> fix: up paypal timeout to 10 seconds in e2e test

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Value of a switch is `On` or `Off` - so the current check will always pass. 
This fixes that.
> fix: check stripeExpressCheckout for On value

- support-workers/src/main/scala/com/gu/emailservices/TierThreeEmailFields.scala
- support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
Adds these fields to the T3 email
- `billing_period`
- `first payment date`
- `subscription_details`
Whilst these fields are available via some of the other fields from the `paperFieldsGenerator` - I've chosen to just add these to align with the S+ fields as that's what we copied from in Braze.
We could probably start consolidating this - although I wonder if that would be part of a larger initiative to do this throughout the pipeline.
> Add billing_period into T3 email fields

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds the steps needed in the `StripeExpressCheckout` to pass the `setupIntent` through to our `create` endpoint.
- get the `clientSecret` from the server
- use that to get the `paymentMethod` from `Stripe`
- validate the `setupIntent` with the `paymentMethod`
- send that ID to the `/create` endpoint
https://github.com/user-attachments/assets/833e3ec1-1b6a-45ef-9ab3-4a72331f1ce2
> fix: update StripeExpressCheckout flow to include necessary steps

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Given this is the default way Stripe suggests doing this, it's the way it currently works, and we're unsure if asking someone for a card via this flow is a good UX, I've swapped this back.
It was also a mistake and was implemented as it was easier to test locally.
> fix: only show apple/google wallets if they're available

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Enable Generic checkout S+ 
1.  Setup abtest `ab-tierTwoFromApi=variant`
2. Tier2 card opens GenericCheckout whilst passing through Param Values
Associated Playwright tests remain at this location -> 
[**Trello Card**](https://trello.com/c/CnkbfpDV/979-generic-checkout-tier2-s-setup-abtest-identify-remaining-work)
https://support.thegulocal.com/uk/contribute#ab-tierTwoFromApi=variant
->
https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly&price=12
|control|variant|
|-----|-----|
|![image](https://github.com/user-attachments/assets/788815c2-5112-4180-8759-b4c389a45455)|![image](https://github.com/user-attachments/assets/c19d9b7c-3152-481d-af9f-e6e80becf251)|
> Generic Checkout: Tier2 S+ Setup ABTest

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
Enable the TicketTailor `chk` value (an identifier for the event's custom checkout) to be passed in for now till we can build the [`retrieve-an-event` API call](https://developers.tickettailor.com/#retrieve-an-event) in the Scala controller to get it from the public TT Event ID.
[**Trello Card**](https://trello.com/c/915GAuRd/965-ticket-tailor-ui-refinement)
Progress forward with solution and stakeholder testing.
Tested on CODE.
-  [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-tec …
> Enable the TicketTailor 'chk' value to be passed in for now till we can build the API call to retrieve it

- support-frontend/assets/components/payPalPaymentButton/payPalRecurringContainer.tsx
- support-frontend/assets/helpers/redux/checkout/payment/payPal/thunks.ts
Digital Edition PayPal checkout amounts shown incorrectly on Paypal confirmation screen. The correct amount is being charged in Zuora however.
[**Trello Card**](https://trello.com/c/4xkb0eHP/997-paypal-x-annual-on-digital-edition-checkout-incorrectly-labelled-on-paypal-confirmation-screen)
https://support.thegulocal.com/uk/subscribe/digitaledition
https://support.thegulocal.com/uk/subscribe/digitaledition?promoCode=KINDLE10
UK Annual 
|Before|After|Promo 10%|
|![image](https://github.com/user-attachments/assets/d94fe3d9-41cf-4068-88b8-1b25e71e7608)|![image](https://github.com/user-attachments/assets/a14d94cf-a87b-484c-8a8a-754dba5a89f3)|![image](https://github.com/user-attachments/assets/536e3eef-2f2e-46cf-9515-32d166ab5fb7)|
> Digital Edition: PayPal Checkout amount shown incorrect

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Uses the dynamic currencyKey instead of hardcoded `gbp` when making a recurring contribution.
> fix: use `currencyKey` instead of hardcoded `gbp` on `StripeExpressCheckout`

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Sets a the postcode and state of a person from the [Stripe billingAddress](https://docs.stripe.com/js/custom_checkout/session_object#custom_checkout_session_object-savedPaymentMethods-billingDetails-address) to ensure we pass the state validation.
This has a bug where if a person is accessing the site from `/us/checkout` but has a e.g. UK address and thus no state, we cannot take a payment as state is required.
https://trello.com/c/ZD2BbAod/932-supportworkers-alarm-promocode-country-not-aligning-with-applepay-googlepay-country
> fix: set StripeExpress payment postcode and state

- support-frontend/app/views/contributions.scala.html
- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds `productPrices` parsing to `AppConfig`. This means that the value is passed through to the app, and we can then calculate promotions.
This fixes the bug that promotions aren't working on the generic checkout - specifically for `SupporterPlus`.
> fix: add productPrices to appConfig

- support-payment-api/src/main/scala/backend/AmazonPayBackend.scala
- support-payment-api/src/main/scala/backend/PaypalBackend.scala
- support-payment-api/src/main/scala/backend/StripeBackend.scala
- support-payment-api/src/main/scala/services/SwitchService.scala
- support-payment-api/src/test/resources/switches_v2.json
- support-payment-api/src/test/scala/backend/AmazonPayBackendIntegrationSpec.scala
- support-payment-api/src/test/scala/backend/AmazonPayBackendSpec.scala
- support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
- support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
- support-payment-api/src/test/scala/model/switches/SwitchSerializationSpec.scala
Making payment api switches optional, after doing the same for the frontend in #6209 
[**Trello Card**](https://trello.com/c/1PkjvuVX/971-deleting-a-switch-in-rrcp-takes-the-whole-site-down)
We've prevented deleted feature switches crashing the frontend, it makes sense to do this for the payment-api too.
Tests pass, will deploy to `CODE` and test a payment
> Make payment api switches optional

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
This adds the `contribution-checkout | generic-checkout` to the `referrerAcquisitionData` posted to the create endpoint.
We are doing this to help with the analysis of how the new checkouts are performing.
The data we hope to compare is:
- Pageviews to contribution checkout / acquisitions from contributions checkout
- Pageviews to generic checkout / acquisitions from generic checkout
This PR should help with the right hand/consequent part of that ratio.
Currently we are using the `abTest: { useGenericCheckout: control | variant }` which is not completely reliable as there are multiple entry points into a checkout e.g. an email. So if you have a link that directly takes you to `/uk/contribute/checkout` you might be designated to `variant`, which in this case would be false data.
I have run …
> feat: add checkout label to referrerAcquisitionData

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
FulfilmentOptions change dependent on ProductType ->
S+/Contribution :  `NoFulFilmentOption`
TierThree :  `Domestic` / `RestOfWorld`
https://support.thegulocal.com/us/checkout?product=SupporterPlus&ratePlan=Monthly&price=15&promoCode=LX4FFRA8
https://support.thegulocal.com/uk/checkout?product=TierThree&ratePlan=DomesticMonthly&promoCode=TIER3_UK_MONTHLY
|S+|Tier3|
|-----|-----|
|![image](https://github.com/user-attachments/assets/60e500bc-75dc-418b-b3eb-9826b5f0399c)|![image](https://github.com/user-attachments/assets/fe95ddb3-5895-4b79-bd39-b0c526772055)|
> Generic Checkout : Tier2 and Tier3 Promotions Supported

- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Whilst trying to get the right abstraction to allow for both
- `Contribution`: a product, no price, a voluntary contribution, no discount
- `SupporterPlus`: a product, a price, a voluntary contribution, promotional discounts
And having 1 eye on the fact we will have to support
- `OneTime`: not a product, no price, a voluntary contribution, no discounts
It felt that could be abstracted to:
- `originalAmount` the person would pay without a discount or contribution
- `discountedAmount` the amount a person would pay with a discount applied
- `contribution` and amount extra to the `originalAmount`
- `finalAmount` the amount a person will pay
This PR has the naming in such a way that we transform product prices (what something costs) => payment (what someone pays).
While this isn't anything new …
> feat: use payment abstraction in checkout

- support-frontend/assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.tsx
Removes unused `setupSubscriptionPayPalPaymentWithShipping` from `payPalRecurringCheckout.ts` module, this export was not imported anywhere.
- Delete `setupSubscriptionPayPalPaymentWithShipping` as wasn't used anywhere.
- `setupSubscriptionPayPalPaymentNoShipping` was now only place where `setupSubscriptionPayPalPayment` was called, so I've removed `setupSubscriptionPayPalPaymentNoShipping` and replaced any places it was called with a direct call to `setupSubscriptionPayPalPayment`
- The `requireShippingAddress` parameter in `setupSubscriptionPayPalPayment` is no longer needed so I've removed it, and we just set this to `false` in the function.
The  `setupSubscriptionPayPalPaymentWithShipping`/``setupSubscriptionPayPalPaymentNoShipping`  functions were introduced in an AB test on the old …
> Remove unused setupSubscriptionPayPalPaymentWithShipping method

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Check what env we're in when selecting the PayPal env on the generic checkout
We were seeing this when testing Paypal locally/in CODE
> PayPal env in generic checkout

- support-e2e/tests/tieredCheckout.test.ts
Playwright Tier1 tests failing, appears to be misisng `/contribute` from URL. This PR explicitly defines.
Playwright Tier3 tests appear to be failing to load on old GW T3 checkout too..
[Temporarily turns on Tier3 switch in playwright tests]
> Playwright: Routing Fix

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Sends the correct `amount` to the `/create` endpoint for `SupporterPlus`.
The logic is described in a comment in the code.
Currently `promoCodes` don't work on the generic checkout for `SupporterPlus` because of this.
[This will get us closer to releasing the test for generic checkout for S+](https://github.com/guardian/support-frontend/pull/6236).
> fix: send correct amount to /create endpoint for `SupporterPlus`

- support-frontend/assets/helpers/campaigns/campaigns.ts
- support-frontend/assets/helpers/tracking/acquisitions.ts
- support-frontend/assets/pages/digital-subscriber-checkout/setup/setUpRedux.ts
- support-frontend/assets/pages/digital-subscriber-thank-you/digitalSubscriptionThankYou.tsx
- support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
Historically we've used the `CampaignSettings` model to customise parts of the support site for campaigns.
It's not currently in use, and much of the code is very old and not relevant.
We're going to revive the concept for the upcoming US end-of-year moment (and beyond), but first I want to clean up legacy code.
> Tidy old campaigns code

- support-frontend/app/views/windowGuardianPaymentConfig.scala.html
Currently this renders
```html
<script>
<script></script>
</script>
```
which is no good. This PR unnests that.
> fix: remove script tag from inside script tag

- support-frontend/assets/helpers/tracking/quantumMetric.ts
Send Ophan Page View ID to QM. This will help us debug alarms as we can query QM with Page View ID.
[**Trello Card**](https://trello.com/c/ne53rvdo/1020-send-page-view-id-to-qm)
> Send page view ID to Quantum Metric

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
Brings the way we get data into the thank you page more inline with the checkout page (as suggested by @rupertbates in a PR I can't find).
It is a copy/paste job (and labelled as such) - I'm not sure we're at the stage of abstracting it just yet. As we get into the world of working on the one-time checkout I think we will start to find good abstractions.
Fixes some bugs raised in https://github.com/guardian/support-frontend/pull/6236
> Use qs params to power thank-you page

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- Adds the `contribution` amount to the `urlParams` when sending someone to the `thank-you` page
- Adds promoCode only if it is available
Tests to follow as this fixes a live bug.
> fix: add contribution to thank-you linik if available

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/helpers/campaigns/campaigns.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This will make the support site configurable for the upcoming moment.
To begin with it'll be used to enable single contributions on the landing page.
Users will be eligible for the campaign if either:
1. the `usEoy2024` switch is enabled (from the RRCP) and the user is in the `UnitedStates` country group,
2. the url querystring contains `forceCampaign=usEoy2024`
> Add campaign settings for US EOY

- support-e2e/tests/tieredCheckout.test.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Enabled the 50% test for sending people to the generic checkout for SupporterPlus from Tier 2 of the landing page.
This also adds some test to ensure that we're working and that we don't add any regressions.
~Currently the tests do not pass - so I will be attaching some PRs until they do.~
> feat: Enable generic checkout 50% test for SupporterPlus

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/backButton.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
As part of building the new one time checkout - we created a skeleton page in #6247. This PR populates the amounts component with the correct props, for example the correct amounts test from the window object.
[**Trello Card**](https://trello.com/c/LimWTJAA/1027-one-time-checkout-amounts)
US
UK
> One Time Checkout - Amounts component

- support-frontend/app/config/Identity.scala
- support-frontend/app/controllers/AuthCodeFlowController.scala
- support-frontend/conf/CODE.public.conf
- support-frontend/conf/DEV.public.conf
- support-frontend/conf/PROD.public.conf
- support-frontend/test/controllers/AuthCodeFlowControllerTest.scala
This adds the ability to use `support.` _**OR**_ `live.` as a redirect URL for auth.
Currently we use `live.` to serve `/events`. This is because `support.` is considered a in-app-purchase URL from our apps and if we link to it, it's blocked.
An example workflow this supports
* Editor creates a new event
* The event is linked to from the site as `live.theguardian.com/events/{eventId}`
* A person has outdated cookies
* They're re-logged in, and redirected back to live.theguardian.com
> fix: add oauth callback URL for events domain

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
- support-frontend/assets/pages/[countryGroupId]/events/router.tsx
- Adds the geoId to the Ticket Tailor metadata as `meta_region_id`. This is the name used in TT  meetings - but I am still not sure what to call it. [Maybe `InternationalizationId`](https://github.com/guardian/support-frontend/pull/6094#issuecomment-2178378940)?
- Removes the QS check and always send this data across
> feat: add region to events metadata and always send it

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
this is a first pass at using the validation error messaging builid into `@guardian/source` components  on the generic checkouts address fields, this is an alternative approach to using native browser validation error messaging, implemented here: https://github.com/guardian/support-frontend/pull/6251
**support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx**
- I've set-up an `setErrorsOnInvalid` function that we can attach to our form fields and execute via the `onInvalid` handler. The `onInvalid` event handler  fires when a submittable element has been checked for validity and doesn't satisfy its constraints (see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event). `onAddressFieldInvalid`  manages adding/removing error message to …
> Use Source Components validation error message on generic checkout addresses

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds logging so we know how many people are being caught by a bug where we need a state for territories where we require it i.e. US, CA, AU, NZ.
> feat: add logging for when we do not get state from stripe

- support-frontend/assets/pages/[countryGroupId]/events/router.tsx
Uses the standard `setUpTrackingAndConsents`.
Not 100% sure why we didn't in the first place.
> fix: add consents to event page

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
On the non-generic checkout we removed the mandatory requirement to submit a Zip Code for users in the US Billing Region (https://github.com/guardian/support-frontend/pull/6099), this was in response to an issue (documented here in [Trello](https://trello.com/c/Cpvg3n5l/896-zipcode-make-it-non-mandatory-on-the-checkout-page-for-single-recurring-and-s-for-us?filter=zip)) that caused users checking out with the Stripe Payment Request Button to be blocked from submitting the form because of this requirement.
However, on the generic checkout this input element was still marked as `required`, by default the `<TextInput>` element has the required attribute, unless we override with the [optional](https://github.com/guardian/csnx/blob/main/libs/%40guardian/source/src/react-components/text-input/Te …
> Generic checkout: Optional Zip Code

- .github/workflows/playwright-cron.yml
- .github/workflows/playwright-smoke.yml
- support-e2e/package.json
- support-e2e/playwright.base.config.ts
- support-e2e/playwright.config.ts
- support-e2e/tests/cron/checkout.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/smoke/consent-management.test.ts
- support-e2e/tests/test/checkout.test.ts
- support-e2e/yarn.lock
This PR creates and categorises some Playwright tests to try and address the speed of the suite, as well as some flakiness issues we've been seeing with third party services timing out e.g. `PayPal`.
The categories we have created are:
- Smoke: tests to be run post-deploy
- Cron: tests that suffer from rate limiting, run on a schedule
Other changes that have been made in this PR:
- moving away from the `GitHub Action => Playwright => Browserstack` pattern to a `GitHub Action => Playwright` model
> Categorise Playwright tests

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
In the US Amazon Pay is rendered as an option but it's not implemented! It's not an option on the non-generic checkout
> Generic checkout - comment out amazon pay option

- support-e2e/tests/cron/checkout.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/smoke/non-delivery-state-selector.test.ts
- support-e2e/tests/test/checkout.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
This adds tests to ensure we sure the `StateSelect` for non-deliverable products.
The more important thing I am trying to capture here is the reason why, using comments and tests to explain that. 
This is part of a large set of institutional / team knowledge that it would be good to codify to socialise between ourselves, but also future folks who join the team and fancy changing this at some stage. 
This PR is more for discussion as opposed to a "We should do this".
> feat: add non-deliverable product state select tests

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Implementing the Stripe card payment functionality into the new one time checkout. Sends a request to the payment API endpoint `contribute/one-off/stripe/create-payment`.
[**Trello Card**](https://trello.com/c/wizKto6r/1037-one-time-checkout-implement-stripe)
Go to `https://support.thegulocal.com/au/one-time-checkout?product=SupporterPlus` and select Credit/debit card. Fill in card details and press payment CTA.
The contribution should show up in 
- Relevant Stripe test mode account
- `datatech-platform-code.datalake.fact_acquisition_event` table
The form does not yet redirect to a thank you page.
> One Time Checkout - Stripe payment

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Currently we show users from the EU "SEPA" as a payment method on the generic checkout. There are 2 issues here, 1) we have not implemented SEPA as a payment method, so selecting the payment method does nothing, and 2) SEPA is currently turned off on the non-generic checkout, so it shouldn't be listed as a valid payment method. The quickest change to resolve the issue we have right now is to comment out SEPA. Next steps would be:
1) Check payment method switch is ON when adding them to `validPaymentMethods`
2) Check whether we intend to reintroduce SEPA, and if so reimplement on the generic checkout.
> Comment out SEPA from validPaymenMethods on generic checkout

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adds error handling from support-workers onto the checkout.
> fix: add error handling from support-workers on checkout

- support-frontend/assets/components/checkoutBenefits/benefitsCheckList.tsx
- support-frontend/assets/components/checkoutBenefits/checkoutBenefitsList.tsx
- support-frontend/assets/components/checkoutBenefits/newBenefitPill.tsx
- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/components/subscriptionBenefitsListData.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/content/CheckList.stories.tsx
Adding an AB test for testing the newspaper archive benefit on the checkout landing page. Including a new "New" benefit pill. This constitutes Variant A. Variant B still to come (banner with images).
[**Trello Card**](https://trello.com/c/gFLnj2Vu/1017-add-newspaper-archive-benefit-to-lp-new-benefit-tooltip-and-checkout-test-a-b-c)
Testing the new newspaper archive benefit at point of conversion.
(Turn on AB test) go to `uk/contribute#ab-newspaperArchiveBenefit=v1` and see "New" benefit
> Newspaper archive benefit and new New benefit pill

- support-frontend/app/controllers/AuthCodeFlowController.scala
We're seeing the errors
```
{
"error": "invalid_grant",
"error_description": "The 'redirect_uri' does not match the redirection URI used in the authorization request."
}
```
popping up quite a lot [from `AuthCodeFlowController`](https://github.com/guardian/support-frontend/blob/main/support-frontend/app/controllers/AuthCodeFlowController.scala#L159). 
My hunch is this is for events that are hosted on live.theguardian.com.
This is with the aim of debugging why login isn't working on live.theguardian.com
> fix: add host and path to auth logging

- support-frontend/app/controllers/AuthCodeFlowController.scala
- support-frontend/app/controllers/CanonicalLinks.scala
- support-frontend/nginx/config.yml
- Uses a dynamic oauth `redirect_url` based on if you're on `live.` or `support.` 🗡️ 
- Adds support to test `live.` locally
- Removes the baseURL from redirect URLs as they are no longer static i.e. `support.`
🗡️ this is what was causing the bug
> Dynamic oauth redirect uri

- support-frontend/assets/pages/supporter-plus-landing/components/newspaperArchiveBanner.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/landingPage/NewspaperArchiveBanner.stories.tsx
Add a new banner (or product slice) promoting the new newspaper archive benefit. 
[**Trello Card**](https://trello.com/c/gFLnj2Vu/1017-add-newspaper-archive-benefit-to-lp-new-benefit-tooltip-and-checkout-test-a-b-c)
We are testing the new benefit at the point of acquisition, this is variant B. The final copy and images are TBC
Activate `newspaperArchiveBenefit` ab test. Go to `/contribute#ab-newspaperArchiveBenefit=v2` 
Or see Storybook - LandingPage: Newspaper Archive Banner
Mobile
Desktop
> Landing page - Newspaper archive banner

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
Add styling to prevent the state select having a red error border on page load. Use the [user-invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) selector to check whether it was actually the user form submission that caused the error. It seems like a [known issue](https://stackoverflow.com/questions/27021801/inputinvalid-css-rule-is-applied-on-page-load) that the `invalid` selector is applied on page load. Should this change in [source](https://github.com/guardian/csnx/blob/67fbe1c1ed95c043ede73fc48020fb4b1bfc5e4f/libs/%40guardian/source/src/react-components/select/styles.ts#L84)?
Before (on page load)
After (on page load)
However there is some strange behaviour now when interacting with the select but not selecting another option
After submit it looks as expected
> Address State Select - remove validation error style on page load

- support-frontend/assets/helpers/campaigns/campaigns.ts
- support-frontend/assets/pages/supporter-plus-landing/components/countdown.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/landingPage/Countdown.stories.tsx
Adding a new component to countdown to the US end of year Giving Tuesday event.
This is added to the threeTierLanding page but hidden with the campaign setting isEligible flag.
[**Trello card**](https://trello.com/c/MLXWgpD4/625-add-countdown-to-landing-page)
This is a feature request for the US End of Year 2024 campaign.
Uncomment and update the labelled test CountdownSetting in the usEoy2024 campaign in campaigns.ts to the appropriate date, time for testing the countdown to appear or not.
Run locally and force the flag in the parameter to see the countdown with: 
[https://support.thegulocal.com/us/contribute?forceCampaign=usEoy2024](https://support.thegulocal.com/us/contribute?forceCampaign=usEoy2024).
When the date and time in the settings are correct, can you see the countdown without …
> Add new countdown component for US EOY 2024

- support-frontend/conf/fastly-snippets/vat-compliance-redirects-recv.vcl
Adding China and Qatar to the list of countries where we sell only sell contributions to, meaning that the `/subscribe/digitaledition` URL will redirect to `/contributions`
Request from Tax/Finance team.
Tried and tested principle. Unit tests pass proving no typo in configuration.
Correct ISO country codes checked against [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1). China = CN, Qatar = QA.
> Adding China and Qatar to the list of countries where we sell only sell contributions to

- support-frontend/app/controllers/Application.scala
- support-frontend/conf/routes
As per this diagram - a step to work towards having a server side rendered page would be to make the app config accessible via a URL that a node app could read and render from.
This starts us on that journey.
Here's the full diagram with the end goal, the part this is focussing on is labelled "This PR" in purple.
> feat: add appconfig endpoint

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
[After an incredible investigation](https://docs.google.com/spreadsheets/d/19kkkQfEHxWx-hyvgXOaTS3YU9aYs2qDfvzFW8dn7RIM/edit?gid=872405396#gid=872405396)(🔒 Private) from @GHaberis - it looks like we're hitting at least parity with the contributions checkout - so off we pop to 100%
Great work by all.
> fix: move generic checkout to 100%

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Changes the default for `useGenericCheckout` test to `variant`.
Oopsie.
> fix: make variant the default for useGenericCheckout test

- support-frontend/assets/components/checkbox/Checkbox.tsx
- support-frontend/assets/components/checkbox/styles.ts
- support-frontend/assets/components/checkbox/theme.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
Cherry picking the latest Checkbox from Source to fix the Cover transaction checkbox styling from misaligning on mobile.
Unfortunately we have quite a few breaking changes in the upgrade path to source v7, which is where this fix is from.
The AB test is meant go live ASAP, so doing this hack should give us some time to upgrade smoothly and remove this temporary measure after
Before
After
> Fix Cover transaction checkbox on mobile

- .github/workflows/playwright-cron.yml
- .github/workflows/playwright-smoke.yml
Adds the Google Chat integration to the Playwright tests.
This is with the aim of having this implementation more fully featured and to remove the Browserstack integration.
[Here is a forced failure that we saw appear in our chat channel](https://github.com/guardian/support-frontend/actions/runs/10829675792/job/30047743319).
> feat: add GChat notification to playwright CI

- support-frontend/assets/components/checkoutHeading/checkoutHeading.tsx
- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
- Ts&Cs creates new tab
- Tablet resize backdrop upwards to display Ts&Cs clearly
- Remove border shown here ->
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/4a3bd2ab-b8d6-4df6-b16d-5a0792cac331)|![image](https://github.com/user-attachments/assets/41abac08-bf70-4d19-9cd9-a1dda9e9e07f)|
[**Trello Card**](https://trello.com/c/j6F32kdQ/1064-ticket-tailor-ui-border-tweak)
> Ticket Tailor: widget border hide

- support-frontend/assets/helpers/forms/paymentMethods.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Updating generic and one-time checkout to check payment method feature switches.
This is a screenshot of the payment method switches. The notion of recurring vs subscriptions isn't a distinction the generic checkout currently makes, so the plan is to use the recurring payment methods for all products on generic checkout and phase out `subscriptionsPaymentMethods`.
[**Trello Card**](https://trello.com/c/V5Y5w0xO/1044-check-feature-switches-when-populating-validpaymentmethods-on-generic-checkout)
> Generic checkout - check payment method feature switches

- support-frontend/app/views/eventsRouter.scala.html
Adds the SSR pre-render placeholder to the events route.
https://github.com/user-attachments/assets/f3ccf0fa-7be5-4a6b-adca-e58df251d04b
> fix: add SSR pre-render to events page

- .github/workflows/playwright-cron.yml
- .github/workflows/playwright-smoke.yml
- support-e2e/package.json
- support-e2e/tests/smoke/ticket-tailor.test.ts
Adds an e2e test that checks the ticket tailor iframe loads correctly.
90% generated with the prompt
```
Write me a playwright test that checks that an iframe with a tickettailor.com URL loads correctly
```
and then refined with 
```
elementHandle doesn't seem to be available on the iframe
```
Which then fixed trying access a method on the `frame` called `elementHandle` which didn't exist.
The main difference between #6313 and this is we use the [`contentFrame`](https://playwright.dev/docs/api/class-elementhandle#element-handle-content-frame) on the `iframe` element.
1. `test-smoke` script added.
2. `test-cron` script added.
To run script containing ticket tailor e2e test->
`yarn test-smoke`
> feat: add ticket tailor e2e test

- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
In prepping to get the homepage redux-free - I am removing the `PriceCardsContainer` from the `oneOffCard`.
This either replaces the values from the container with values from internal state (using `useState`) or passed down from the `threeTierLanding`.
This PR also hardcodes the `href` values of the one time checkout link (previously `Button`, now `LinkButton`).
~Screenshots coming once this is merged https://github.com/guardian/support-frontend/pull/6324~
https://github.com/user-attachments/assets/b35e1027-b01a-4330-81fd-3fbdf99ff839
> refactor: remove redux from oneOffCard

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/orderSummaryText.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/catalog/ProductOptions.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
We want to AB test adding the newspaper archive benefit to the tier three product, to see whether it causes an uplift in conversion - [more details in this presentation](https://docs.google.com/presentation/d/18f1uYissTG27WCxDrfV69fBG2tYX90aG_0cE1PkDvWI/edit#slide=id.g2fbf351fd3e_0_102)
To do this we need to introduce new product rate plans with an additional archive charge and sell these plans to users in the cohort who will be getting the new benefit. 
Because currently we only have one rate plan per billing period and fulfilment option for tier three, this PR differentiates the new plans by using a `productOption` value of `NewspaperArchive`, the original non-archive plans have a `productOption` value of `NoProductOptions`
[More details in this …
> New Plans for T3 archive benefit

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Deactivates the `coverTransactionCost` test as we have seen a drop in CVR.
> fix: deactivate coverTransactionCost ab test

- support-e2e/package.json
- support-e2e/playwright.config.ts
- support-e2e/playwright.dev.config.ts
Adds the ability to run the new style of e2e tests locally.
I'd like to make a change that I would feel way more comfortable knowing works locally - this would allow me to do that.
I've gone with the `.dev` naming as that what we, and other frameworks, tend to use e.g. `make dev` in dcr, `npm run dev` in other places in the ecosystem.
It also means I can keep the `.local` file which will be deleted soon.
I've left this running in `--ui` mode as I feel this is the most common `dev` way of doing it from working with @paul-daniel-dempsey and @andrewHEguardian
> feat: add local e2e testing

- .gitignore
- support-frontend/app/wiring/Assets.scala
- support-frontend/webpack.common.js
Renames the map generated by [Webpack Manifest Plugin](https://github.com/shellscape/webpack-manifest-plugin) to JSON.
This is so we can `import` it in NodeJs files without having to build any fancy loader for it as Node supporting JSON imports by default.
Another reason is that this is a JSON file
> refactor: rename assets.map to assets.json

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Uses the `ratePlan` querystring param to select the `contentType` (tab) for the page.
We will be able to remove the `useContributionsSelector` once this https://github.com/guardian/dotcom-rendering/pull/12437 has been merged in.
> fix: use ratePlan for selection on landing page

- support-frontend/assets/components/paymentRequestButton/hooks/paymentAuthorisation.ts
- support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestEvent.ts
- support-frontend/assets/helpers/page/analyticsAndConsent.ts
- support-frontend/assets/helpers/productPrice/subscriptions.ts
- support-frontend/assets/helpers/subscriptionsForms/__tests__/subscriptionCheckoutReducerTest.ts
- support-frontend/assets/helpers/thankYouPages/utils/ophan.ts
- support-frontend/assets/helpers/tracking/NavigateWithPageView.tsx
- support-frontend/assets/helpers/tracking/__tests__/ophanTest.ts
- support-frontend/assets/helpers/tracking/behaviour.ts
- support-frontend/assets/helpers/tracking/trackingOphan.ts
- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/contributionsPriceCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/firstStepLanding.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
This PR renames the ophan module to trackingOphan. 
The reason for doing this is that when it was named ophan it was not possible to test any functions in it because it is getting mocked by this code here: https://github.com/guardian/support-frontend/blob/08643c2d5aa3875a5934db82758c2d3f73852a06/support-frontend/jestSetup.js#L6-L10
Strangely, changing the module name to eg. ophanTracking still results in the same issue, the name needs to start with something other than ophan to work.
If anyone has a better solution for this please chip in!
> Rename ophan file to enable testing

- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/tracking/acquisitions.ts
- support-frontend/assets/helpers/tracking/trackingOphan.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This PR changes the newspaper archive AB test to use the new archive rate plans for all variants of the test, so the control group will also receive the new benefits. The only time when the old rate plans are used now is when the test is inactive.
More information about this test is [here](https://docs.google.com/document/d/1lL8SCyy-LRrHOxzP9C3HV1UFdQ8AMOuQxQEK77j4ogs/edit?usp=sharing)
To support this behaviour I have had to make a change to the `Participations` type in our TS code. This was not accurately describing the possible values of an AB test because it was of type `[string, string]` where the first string is the test name and the second is the variant which the user is in, however when a test is inactive (`isActive: false`) the variant value will be undefined. I have redefined …
> Use new T3 archive rate plans for all cohorts in archive AB test

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/frontend.ts
Having all alarms starting with the word urgent is making the non-dev members of the team anxious, and I don't think it adds any value as it was just getting prepended to all alarm names.
> Remove urgent wording from alarms

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
If you select a country that isn't in the correct location for a product, we redirect you to the correct country group and alert you to the fact this has happened.
This completes the work started in https://github.com/guardian/support-frontend/pull/6238
https://github.com/user-attachments/assets/547926fe-8b49-414c-b26d-59244b987a1f
> Info box with country change alert message

- support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
#6322 Added new rateplans for the newspaper archive benefit and introduced a new `productOptions` value to determine when they should be used. However it missed out some code in the UpdateSupporterProductData lambda which needs to take account of the new productOptions value - this PR fixes that.
> Use the correct productOptions when updating supporter-product-data

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
- support-frontend/app/views/router.scala.html
- support-frontend/app/wiring/Controllers.scala
- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/helpers/redux/checkout/product/state.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/secondStepCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/conf/routes
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/window.d.ts
Adds the `allProductPrices` object to the `window.guardian` `AppConfig`.
This makes the config less stateful - and relies on the client to calculate which bit of the config it should use.
It also unblocks the work @paul-daniel-dempsey is working on with the one off checkout.
The idea here is to have 1 `AppConfig` that each page can read from consistently. We have already seen on the Landing page that we need both `SupporterPlus` and `TierThree` - so why not just use that model. It's 1 extra lookup, but when you;'re swapping between the pages, you know where to look.
> Use productPrices consistently across landing/checkout in AppConfig.

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This removes all `useContributionsDispatch` and `useContributionsSelector` from the landing page, probably meaning we can implement this page without setting up redux.
I've branched off `remove-server-product-lookup` as that has [a couple changes](https://github.com/guardian/support-frontend/pull/6342/files#diff-9e9d19a3470db4ff48cd4c73865be05d061001afc0751360451d6d509f390e9b) that would be overridden here.
Part of #5722
> Remove redux from landing

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Existing Checkout works great with Stripe, can see payments appearing in [Stripe Test](https://dashboard.stripe.com/test/payments).
Adds RECAPTCHA as required field before you can submit form for payment.
[Trello Card](https://trello.com/c/RU9Pes3Q/1077-generic-checkout-one-time-implement-express-payment-options-for-one-time-note-use-one-time-stripe-accounts)
> One Time Checkout - Recaptcha required to submit form

- cdk/bin/cdk.ts
- cdk/lib/frontend.test.ts
- cdk/lib/frontend.ts
We don't want to create alarms in code for support-frontend. Previously we had a boolean which meant they were inactive, but there's no point in creating them at all as they just clutter things up, so this PR ensures that alarms are only created in PROD.
> Only create alarms in PROD

- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
Currently if the landing page url query string contains `selected-contribution-type=ONE_OFF`, we redirect to the checkout.
We no longer want this behaviour as we're about to run A/B tests on this journey.
> Remove redirect to checkout for one-off

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
We've been running an AB test with a 3rd tab for "One-time" on the landing page.
We've decided to end it early and show it to all users in the US.
This will help with an AB test we're about to run on the epic, which will link users to the landing page.
> Roll out 3-tab landing page to all US users

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
We want to test what the value of the 'Exclusive access to partner offers' benefit is in converting AU supporter plus customers, so this PR sets up an AB test - `auPartnerBenefit`:
- `control` - see the copy, as is the case now
- `variant` - do not see the copy
> Test the value of S+ partner offers in AU

- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Changing the UI of the _Support another way_ section of the landing page following this [design](https://www.figma.com/design/ijioQ84Nmo2IrMzLol33XV/US-EOY-Appeal-2024?node-id=455-39547&node-type=canvas&t=6e3sYcGTiPGWbVVI-0) which also includes some minor padding tweaks to the choice cards 
[**Trello Card**](https://trello.com/c/UGL60hAh/688-update-support-another-way-design-on-3tlp)
On the landing page check that the new 'Support another way' design is showing and that the padding is accurate - you can do this by using the dev tools on your browser.
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology …
> Landing page - Support another way and padding tweaks

- support-frontend/app/controllers/Application.scala
- support-frontend/test/controllers/ApplicationTest.scala
For recurring contributions, when we redirect from the old checkout to the new one we want to pass the `selected-amount` query string parameter across to the new checkout renamed to `contribution`. 
This PR does that.
> Keep contribution amount in the redirect for recurring contributions

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adding a minimum height to the Stripe Express Checkout element to prevent CLS.
[**Trello Card**](https://trello.com/c/32XTJ332/1070-layout-shift-on-generic-checkout)
Load generic checkout - do not see spacing shift.
Before: 
https://github.com/user-attachments/assets/c87218d8-e368-441b-a3e6-942c951595bc
After
https://github.com/user-attachments/assets/e779b723-76b7-44be-8986-b2380082ca42
> Prevent layout shift on generic checkout

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
We're disabling the one-time tab for now.
It can only be seen by adding `?enableOneTime` to the url.
I've also fixed the design when both the "support once" and "support another way" are displayed:
Mobile, no "support once":
Mobile, with "support once":
Desktop, no "support once":
Desktop, with "support once":
> Disable one-time tab on LP

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/services/RecaptchaService.scala
- support-frontend/assets/helpers/forms/errorReasons.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
This PR does a number of things:
- Adds recaptcha failure to the list of ignored alarms
- Fixes handling of error responses from the `/create` endpoint (CreateSubscriptionController.create) - previously these were not being handled, leaving the user with a never ending spinner
- Improve the logging of Identity errors to make it clear that they are from Identity
> Recaptcha alarm

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Adding 
1.  An AB test for the new one time checkout (inactive)
2. Capability for AB tests on the checkout
[**Trello Card**](https://trello.com/c/1s1OSFLd/1039-generic-checkout-one-time-ab-test-setup)
Once its ready we'll launch an AB test of the new one time checkout vs the old. We also want other AB testing to be possible on the page.
Activate AB test, go to landing page and add `uk/contribute#ab-newOneTimeCheckout=variant` to the URL. Click the support just once CTA and see the new checkout.
Datalake showing labels and AB test participations
> One Time Checkout - AB Testing

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/services/RecaptchaService.scala
Up until now we haven't been logging any [error codes returned from the Recaptcha service](https://developers.google.com/recaptcha/docs/verify#error_code_reference). As we are seeing regular checkout failures due to Recaptcha errors it makes sense to log these to see if there is a common theme.
> Log recaptcha error codes

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/thank-you.tsx
There are certain pieces of core product info that are required in the querystring params in order to render the generic checkout and thank-you page. If they're not present the client renders an almost entirely blank screen with a simple message, which won't mean much to users but indicates the problem.
This PR introduces some Sentry logging so we can be aware of if these issues are occurring, as right now we don't have this visibility.
> Log exception on issues that prevent page rendering

- support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Amazon Pay is used in the US one-time checkout only. This PR introduces a US only AB test for Amazon Pay as a payment method.
> AB test Amazon Pay

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Fixing the PayPal button enabling after the form has been completed and validation passes. We're having to workaround the fact that calling `checkValidity` on the form returns `false` even when the form is correctly filled out, this appears to be because we're using `setCustomValidity`. The solution is to call `checkValidity` a second time and use that result.
[**Trello Card**](https://trello.com/c/xt6Ikhcy/1093-generic-checkout-paypal-client-side-validation)
Previously a bug occurred where the button was disabled even after filling in the form.
1.  Go to any tier of the generic checkout eg. Tier 1: https://support.thegulocal.com/uk/checkout?product=Contribution&ratePlan=Monthly&contribution=3
2. Skip the required fields: Email, first name and last name and select the Paypal Payment …
> Generic checkout: fix paypal button load after validating form

- support-frontend/app/services/ProductCatalogService.scala
- support-modules/rest/src/main/scala/com/gu/rest/WebServiceHelper.scala
The ProductCatalogService polls the product catalog api once a minute to retrieve the latest version. As each request logs the request details and the full response, it quickly fills up the logs with identical messages. This can be particularly annoying when running the site locally as log files can quickly reach multiple megabytes in size making them hard to open and scan in an editor.
This PR allows WebServiceHelper derived classes (which ProductCatalogService is) to switch off verbose logging, and does switch them off for the ProductCatalogService.
> Supress ProductCatalogService logging

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/paymentMethod.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Making the entire payment method label clickable in the payment selection radio group. 
[**Trello Card**](https://trello.com/c/EaD6HHGx/1128-checkout-payment-selector-selection-beyond-radio-button)
Before only the label of the text selected the radio, which isn't a great user experience.
Go to generic checkout, hover over icon area of payment method - cursor is a pointer and clicking selects that box.
-  [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contras …
> Make whole payment radio area clickable

- .github/workflows/payment-api-build.yml
- .github/workflows/stripe-patrons-data.yml
- .github/workflows/support-frontend-build.yml
- .github/workflows/support-lambdas-build.yml
- .github/workflows/support-workers-build.yml
- .github/workflows/supporter-product-data.yml
We've had several Scala builds fail  with the message `sbt: command not found`. It turns out the latest Ubuntu image doesn't have SBT available by default. 22.04 (the previous version) did, but 24.04 doesn't: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md. Using the `setup-sbt` action seems to fix the problem.
> Fix build: use setup-sbt action

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
The Portfolio team is responsible for payment-api alarms as per this spreadsheet: https://docs.google.com/spreadsheets/d/1bb8WB-6ZFRdUwERHMOVIolN8WU8zJMcsyi-WJuwp07Q/edit?gid=0#gid=0
> Assign payment-api alarms to Portfolio team

- support-frontend/assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#6374
This test can end, we're removing Amazon Pay, I've switched the payment method off for now until we remove it.
> Revert "AB test Amazon Pay"

- support-frontend/assets/components/paymentRequestButton/hooks/usePaymentRequestCompletion.ts
- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.tsx
- support-frontend/assets/components/subscriptionCheckouts/summary.tsx
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/productPrice/paperSavingsVsRetail.ts
- support-frontend/assets/helpers/redux/checkout/personalDetails/thunks.ts
- support-frontend/assets/helpers/redux/checkout/product/selectors/subscriptionPrice.ts
- support-frontend/assets/helpers/redux/selectors/formValidation/otherAmountValidation.ts
- support-frontend/assets/helpers/redux/selectors/formValidation/paymentValidation.ts
- support-frontend/assets/helpers/supporterPlus/benefitsThreshold.ts
- support-frontend/assets/helpers/tracking/acquisitions.ts
- support-frontend/assets/helpers/tracking/quantumMetric.ts
- support-frontend/assets/helpers/tracking/quantumMetricHelpers.ts
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/countdown.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
- support-frontend/tsconfig.json
Turn off the `tsconfig` override of the `noImplicitReturns` rule and fix the errors 
This gets us closer to the @guardian/tsconfig ruleset
> chore: update missing returns and turn on `noImplicitReturns`

- support-frontend/assets/pages/supporter-plus-landing/components/coverTransactionCost.tsx
After [this PR](https://github.com/guardian/support-frontend/pull/6318) was merged, the main build started failing due to a change using the 'old' font style from source
> Fix to the main build to use new source update

- support-frontend/assets/pages/supporter-plus-landing/components/contributionsPriceCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/coverTransactionCost.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/finePrint.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Looks like a few sizing tweaks needed after a major Source update->
`secondStepCheckout` (old one-time) Change Summary->
1. TC's: changed to textSans14, set back to textSans12
2. Cover Transaction Cost Summary: changed to textSansBold12, set back to textSansBold17
3. Title `SupportUs`: changed to textSansBold14, set back to headlineBold24 (this appeared to be set to 28px from tablet previously to match `1 Your Details` & `2 Payment Method`)
`one-time-checkout` (new one-time) Summary->
1. TC's: changed to textSans14, set back to textSans12
`checkout` (new recurring) Summary->
1. TC's: changed to textSans14, set back to textSans12
> Source Upgrade : Font Sizing Corrections

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
When the campaign is enabled, users will see the one-time tab on the landing page:
> Enable one-time tab for US campaign

- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Configures the main subheading, and the one-time tab heading.
Before:
After:
> Configure US EOY copy

- .scalafix.conf
- support-frontend/app/actions/CachedActionBuilder.scala
- support-frontend/app/actions/NoCacheActionBuilder.scala
- support-frontend/app/actions/PrivateActionBuilder.scala
- support-frontend/app/admin/ServersideAbTest.scala
- support-frontend/app/admin/settings/ContributionTypes.scala
- support-frontend/app/models/identity/responses/SetGuestPasswordResponseCookie.scala
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/test/controllers/SiteMapTest.scala
- support-models/src/main/scala/com/gu/support/paperround/PaperRound.scala
- support-models/src/main/scala/com/gu/support/workers/GiftRecipient.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
- support-modules/rest/src/main/scala/com/gu/stripe/StripeError.scala
- support-payment-api/src/main/scala/MyApplicationLoader.scala
- support-payment-api/src/main/scala/model/stripe/StripePaymentIntentsApiResponse.scala
- support-payment-api/src/main/scala/model/stripe/StripeRequest.scala
- support-payment-api/src/main/scala/services/ContributionsStoreService.scala
- support-payment-api/src/test/scala/controllers/AmazonPayControllerSpec.scala
- support-payment-api/src/test/scala/controllers/GoCardlessControllerSpec.scala
- support-payment-api/src/test/scala/controllers/PaypalControllerSpec.scala
- support-payment-api/src/test/scala/controllers/StripeControllerSpec.scala
- support-payment-api/src/test/scala/services/EmailServiceSpec.scala
- support-payment-api/src/test/scala/services/PaypalServiceSpec.scala
This PR is the first of potentially several to fix Scala warnings in the support-frontend codebase, it contains two main changes:
- Add [Scalafix](https://scalacenter.github.io/scalafix/) to the project to enable a number of automated fixes
- Use Scalafix to carry out the [ExplicitResultTypes](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html) fix to add explicit types to all implicit vals in the project
> [Fix Scala Warnings] - Add explicit types to implicits

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
We have a  "Contributions Only" checkout flow for some countries: eg. https://support.theguardian.com/int/contribute?country=OM
We shouldn't be bucketing users on this "Contributions Only" checkout flow in the `coverTransactionCost` A/B/C test because this checkout doesn't show the one-time choice cards component on the checkout page, which means we users allocated to `variantB` will never see the cover transaction component as it sits in this component.
> Omit users on the Contributions Only checkout from the coverTransactionCost test

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Currently, if an AB test is targeted specifically at the landing page then the tracking doesn't carry through to the checkout. This means it doesn't get included in the acquisition event.
This PR fixes this by changing the landing page to add the AB test participations to session storage.
Subsequent pages will then pick up participations from session storage.
This is limited by the new `persistPage` field on the AB test model. A page will only pick up participations from session storage if `persistPage` matches the current path.
> Persist landing page test tracking

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
We're logging an error in Sentry if a user pays with a wallet payment method, but that payment method does not have a Billing State associated to it. Currently we throw this error in all country group id regions, however it's only an issue we care about in countries that require Billing State, eg. US, CA, AU. 
This PR updates the code that logs this issue, so we only report in the US, CA, AU. This will give us a better idea of how many users are experiencing an issue due to the missing Billing State.
Note: The objective here is to get a clearer picture of how many users are affected by a known issue where they're in the US, CA, AU but the Billing Address associated with their "wallet" payment method does not have a Billing State. Although we send `countryId` to `logException` this info is …
> Only throw missing Billing State error if required by checkout's country group

- .github/workflows/lighthouse.yml
- lighthouserc.json
Tweaking the lighthouse performance params, based on recent failures of the CI action (added in #4626 ). And alarm to the Google chat when the action fails
> Lighthouse - alarm on failure

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Creating the proper AB test of the Link payment method in the Stripe express checkout method, labelling the acquisitions which use this method.
[**Trello Card**](https://trello.com/c/aHoB0Ihf/1104-enabling-link-with-the-stripe-express-checkout-element)
Testing if this new payment method increases conversion. We have tested this in production with a real payment and it worked.
Go to `uk/checkout?product=Contribution&ratePlan=Monthly&contribution=3#ab-linkExpressCheckout=variant`. The acquisition is labelled with "express-checkout-link"
CVR
This did not work in our Australian Stripe account in test mode - so I have not enabled it there and Link will not be available in AUD territories.
Control
Variant
(other variations exist when paired with other express checkout methods available)
> Enable Link Express Checkout AB test 

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Change the stripe payment method passed to the backend to the old (inaccurate) value of 'stripePaymentRequestButton'. Our backend is expecting this
<!--
> New One Time - use old type for stripe payment method

- support-frontend/assets/components/offer/offer.tsx
- support-frontend/assets/components/thankYou/appDownload/appDownloadItems.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/newspaperArchiveBanner.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Update:
- Checkout benefit list includes newspaper archive benefit for v1,v2,control (see screenshot below)
- Recheck copy throughout against latest [**Figma**](https://www.figma.com/design/h53HMhA753GLQ4ycN1uoPc/newspaper-archive?node-id=545-17670&t=Lm4eiadk4JMJGR7f-1) updates
[**Trello Card**](https://trello.com/c/FjKV8faD/1054-update-copy-and-imagery-newspaper-archive-benefit-to-lp)
dev => `https://support.thegulocal.com/...`
prod => `https://support.theguardian.com/...`
`.../uk/contribute#ab-newspaperArchiveBenefit=v1`
`.../uk/contribute#ab-newspaperArchiveBenefit=v2`
`.../uk/contribute#ab-newspaperArchiveBenefit=control`
eg prod
`https://support.theguardian.com/uk/contribute#ab-newspaperArchiveBenefit=v1`
> Newspaper Archive : Checkout Benefit Add, Copy Checks

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Only show "Something went wrong" message when payment has been attempted. Also move this message to the right place.
Unset payment method validation on selection of a payment method.
[**Trello Card**](https://trello.com/c/LqHf2Xpl/1166-one-time-checkout-testing-pickups-validation)
Fixing some bugs found in end to end testing
Before (when should not show)
After (when should not show)
After (when should show)
Before 
After
> One Time Checkout - validation message

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
The variant with the one-time tab has performed well.
Now all users in the US EOY campaign will see it.
When the campaign ends, it will go back to normal (no one-time tab)
> End 3-tab LP test

- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
Add a validation that checks the minimum amount for an 'other' amount input by the user.
[**Trello Card**](https://trello.com/c/LqHf2Xpl/1166-one-time-checkout-testing-pickups-validation)
We found that entering a negative amount caused Stripe JS to crash on the page
Go to `/one-time-checkout` and Choose your amount. Enter a negative number, cannot press the CTA.
Before
After
> New One Time Checkout - validate minimum amount

- support-frontend/assets/components/thankYou/thankyouModules.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankyou.tsx
Thankyou cards re-sort, display missing benefit
1.  re-sort
2. missing benefit display
[**Trello Card**](https://trello.com/c/FjKV8faD/1054-update-copy-and-imagery-newspaper-archive-benefit-to-lp)
dev => `https://support.thegulocal.com/...`
prod => `https://support.theguardian.com/...`
`...uk/checkout?product=TierThree&ratePlan=DomesticMonthlyV2#ab-newspaperArchiveBenefit=control`
`...uk/thank-you?product=TierThree&ratePlan=DomesticMonthlyV2#ab-newspaperArchiveBenefit=control`
eg prod
`https://support.theguardian.com/uk/thank-you?product=TierThree&ratePlan=DomesticMonthlyV2#ab-newspaperArchiveBenefit=control`
> Newspaper Archive : Thankyou cards re-sort, display missing benefit

- support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx
Marketing have a promotion targeting Waitrose customers launching tomorrow. They've reached out as the campaign/promotion has been set-up however when the promotion is applied to the Newspaper landing pahe the Saturday & Sunday Home Delivery pricing cards are showing an overly high discount vs retail, the cards show 15% saving vs retail, when it's actually 10%, the price on the cards of £15.60 is correct.
There's concern about launching this promotion when incorrectly reporting the saving, for legal reasons. The logic to calculate this saving is complex and straddles the server & client, it's hard to troubleshoot given the time sensitivity! I'm  therefore proposing a temporary solution so this campaign can go live, of hardcoding the saving when the promo code used  applied to a pricing …
> temporarily force saving vs retail for WAITROSE promotion

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
We have been asked to reinstate the ab test to confirm earlier findings.
[**Trello Card**](https://trello.com/c/KAl5dgg6)
MRR are concerned about the RC levels and want to iterate on the 3-tabbed variant
This reverts this reversion: [PR6450](https://github.com/guardian/support-frontend/pull/6450).
There will also be another PR to change some copy that is not part of the AB test.
> Reinstate landingPageOneTimeTab2 ab test

- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Small alterations to the heading and subheading copy for the US EOY 2024 campaign only.
[**Trello Card**](https://trello.com/c/KAl5dgg6)
Concerns over the reduction in Supporter+ and towards less effective one-off contributions.
> small copy changes for us eoy campaign

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Turn off Link Express Checkout test
Because this test was bucketed on the checkout page the page view numbers did not come through correctly in the AB test dashboard. The numbers don't look good though (~-2%)
> Deactivate link express checkout ab test

- support-frontend/app/controllers/DiagnosticsController.scala
following https://github.com/guardian/support-frontend/pull/6489
I realised that none of the additional information comes from the client side, it's just key and value, so it's totally misleading and pointless
This PR removes all the info that is just default values.
OLD
NEW
> simplify cookies diagnostic info

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
#6449 failed to deploy because the names of the alarms defined in the new CDK were identical to the already existing ones in PROD but the logical ids were different. Rather than setting the logical ids to the old versions which are long and unwieldy, I've just changed the names slightly so we create new ones.
> Make alarm names different to existing non-cdk alarms

- prout/seen.md
Update prout checklist to link to correct workflow:
I noticed the workflow linked to from the prout-bot comment is one which is no longer run. So update it to point to the correct workflow, i.e. the one which runs the Playwright smoke tests against prod.
-  [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.m …
> Update prout checklist to link to correct workflow

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
we no longer want this on the US EOY landing page
> Remove one-time tab

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/backButton.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/package.json
- support-frontend/yarn.lock
First steps to support Guardian Light in the generic checkout.
[**Trello Card**](https://trello.com/c/5Bjvwbvg/1204-checkout-support-for-new-product-investigate-frontend-and-if-it-needs-light-design-if-any)
> First steps to support Guardian Light in the generic checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
`newOneTimeCheckout` A/B test had excludeCountriesSubjectToContributionsOnlyAmounts set to false, however we should exclude these countries as they're on the "Contributions Only" checkout
> Don't bucket users into new one time test on contributions only landing

- support-frontend/build.sbt
Exclude `net.sourceforge.htmlunit:htmlunit` from the project. 
Dependabot has reported a vulnerability for this library. It's brought in via `org.scalatestplus.play:scalatestplus-play` > `org.seleniumhq.selenium:htmlunit-driver` and even the latest version of those libraries rely on a vulnerable version, so there isn't an obvious upgrade path.
-  [ ] [The …
> Exclude `net.sourceforge.htmlunit:htmlunit` from the project

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.tsx
Remove AU partner benefit from landing page.
This regional benefit has basically no negative neither positive impact on that landing page key metrics, but we'll keep it there.
> Remove AU partner benefit test (keep control)

- support-payment-api/build.sbt
Exclude `net.sourceforge.htmlunit:htmlunit` from the `support-payment-api` project.
This library has a vulnerability and there isn't an obvious upgrade path. Follow on from #6510, which didn't completely get rid of the vulnerable dependency from the project. …
> Exclude `net.sourceforge.htmlunit:htmlunit` from support-payment-api

- support-frontend/app/controllers/IdentityController.scala
- support-frontend/conf/routes
Remove the "getUserType" endpoint from the support-frontend backend. 
We're now returning this information in the create endpoint (#6507). This PR needs to go in after #6523
> Remove getUserType from backend

- support-frontend/app/controllers/Application.scala
- support-frontend/conf/routes
Adding a geo redirect for the one time checkout, so that we can use the link https://support.theguardian.com/one-time-checkout
[**Trello Card**](https://trello.com/c/Xrbrvakd/1251-https-supporttheguardiancom-one-time-checkout-does-not-geo-redirect)
Go to `support.thegulocal.com/one-time-checkout`, be redirected to `support.thegulocal.com/uk/one-time-checkout`
> Add geo redirect for one time checkout

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Reverts guardian/support-frontend#6517 (which turned the test off), and increases the coverage to 100%
> Enable newOneTimeCheckout AB test

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Turning off autocomplete on the zip code field. We've seen this be filled in with an email address when payment method is PayPal. Our theory is somehow the modal or browser is autofilling this.
No PayPal email address in postcode support worker failures!
> Turn off zip code autocomplete

- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
Fix broken `PreparePaymentMethodForReuseSpec` it test.
In #6485 a mandatory `paymentType` field was added to this json data structure, so we need to add it to this fixture.
> Fix broken `PreparePaymentMethodForReuseSpec` it test

- support-workers/src/test/scala/com/gu/salesforce/Fixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
Update a couple of Salesforce IDs referenced in the tests. These need changing as the data in Salesforce itself has been updated.
Following on from #6525 and #6537 this is the final change to get the support-workers integration tests back to green 🍏. …
> Fix `CreateSalesforceContactSpec` integration test

- support-frontend/app/views/newspaperArchive.scala.html
Adding data-iframe-height and base target="_top"
Requirements from newspapers dot com to fix the height of the header, and target="_top" ensures links open outside the iframe
> Newspaper Archive - add iframe properties to header page

- support-workers/src/test/scala/com/gu/salesforce/Fixtures.scala
Similar to #6540, an ID has been updated in Salesforce and needs reflecting here.
This integration test is currently failing.
> Fix com.gu.salesforce.SalesforceSpec integration test

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Fix the payment method tracking of Stripe payments by adding the 'StripeCheckout' case for non Google or Apple pay.
We noticed in the data that no payments were recorded as 'Stripe' in the variant, which was obviously suspicious.
Put through a credit card payment. See 'Stripe' in the data.
Purchases with credit card on CODE before and after this change:
> Fix stripe payment method tracking on one time

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/validation.ts
Add whitespace to field validation, and extend the emoji matching.
[**Trello Card**](https://trello.com/c/AMNkTmfY/1208-generic-checkout-user-can-submit-whitespace-as-name)
We had an alarm where a user had submitted whitespace in the first name field. The extended pictograph regex matches more emojis, eg I tested  ✈️ which isn't strictly an emoji
On generic checkout, cannot submit whitespace or emoji. 
Before
After
Before
After
> Validation: update pattern to check for whitespace and more emoji-ish characters

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
From the checkout, fix the `Back` link when the product is Guardian Light. When this link was added we hadn't decided on the landing page path.
So the link doesn't 404.
> Fix back link to guardian light landing page

- support-frontend/devrun.sh
- support-frontend/package.json
- support-frontend/yarn.lock
In the `devrun.sh` script we run three processes:
* webpack (for the client)
* sbt (for the backend)
* storybook
The output from each is interleaved, and sometimes I find it can be hard to tell which command a line of output is coming from. I also find using `ctrl-c` to kill things doesn't always work and I'm left with orphaned processes running in the background. Then the next time I try to run e.g. storybook, it binds to a different port as its usual port is taken.
This PR introduces an npm package [`concurrently`](https://www.npmjs.com/package/concurrently) to improve the dev x.
Running our commands through `concurrently` seems to do a better job of managing processes (killing everything when I `ctrl-c`. It also adds a colour coded prefix to each output line, so we can easily know …
> Use `concurrently` npm package in `devrun.sh`

- support-frontend/app/views/newspaperArchive.scala.html
Changing the newspaper archive header iframe height to 125 as that's the intended design height
Before: 
White space is in our iframe
After:
... wait and see
> Update newspaperArchive iframe height

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
This label wasn't being added to PayPal acquisitions on the new one time checkout, which means we couldn't see these when querying the data by label
> Add one-time label to paypal acquisitions

- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/countdown.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/landingPage/Countdown.stories.tsx
Adds the ability to set up different colour and background colours for countdowns for each sub-campaign for US EOY.
[**Trello Card**](https://trello.com/c/gECTtqrM)
The US would like each sub-campaign to have a different colour scheme.
Set the datetime for the campaign to be around 'now' then run locally and go to the US 3-tier landing page with the feature flag of ?forceCampaign=usEoy2024 or check storybook
> Add sub-campaign theme to countdown

- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/validation.ts
Validation is broken on the delivery address, reverting
> Revert "Validation: update pattern to check for whitespace and more emoji-ish characters"

- support-frontend/app/controllers/TestUsersManagement.scala
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Adding an expiry of two days to the test_username cookie.
[**Trello Card**](https://trello.com/c/RsJrEweH/1159-test-users-cookie-out-of-sync-with-backend)
The cookie seems to persist longer than the backend accepts a test user (the old cookie maxAge was session, and modern browsers persist the session for a long time). The red banner stays present for days on end.
This mismatch causes an alarm if you actually try to make a purchase, as the frontend uses the test Stripe key, and the backend isn't expecting it.
I came up with 2 days because I found this [code](https://github.com/guardian/support-frontend/blob/5a7b58ae37d3142239704b38a8a4ea2ffa57b6ed/support-frontend/app/services/TestUserService.scala#L13) -> 
`  val ValidityPeriod = ofDays(2)`
I set the maxAge to a few seconds and went to …
> Set expiry to test user cookie

- project/LibraryVersions.scala
This forces an upgrade of `io.netty:netty-common`, which is flagged by dependabot as having a vulnerability.
[**Trello Card**](https://trello.com/c/6w5OCaXC/1273-dependabot-high-vulnerability-denial-of-service-attack-on-windows-app-using-netty)
-  [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-c …
> Upgrade AWS libs to fix a netty dependabot alert

- support-modules/acquisition-events/build.sbt
Add explicit dependency on `protobuf-java` so we can force `v3.25.5`.
[**Trello Card**](https://trello.com/c/g3pRbNsI/1276-dependabot-high-vulnerability-protobuf-java-has-potential-denial-of-service-issue)
This is to force a newer version than that brought in by `google-cloud-bigquery`. Dependabot has reported a vulnerability for the version we're on.
We tried upgrading `google-cloud-bigquery` itself, but this resulted in an issue with deploying as it pushed us over the lambda S3 compressed file size limit.
I deployed `support:lambdas:bigquery-acquisitions-publisher` to CODE and put through a transaction. I see the data as expected in the fact acquisition events BQ table.
-  [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual. …
> Add explicit dependency on protobuf-java

- supporter-product-data/cloudformation/cfn.yaml
Updating the cron schedule for the supporter-product-data step function in CODE to run Monday - Friday.
We noticed that the supporter product data export was running Sunday - Thursday in CODE and not Monday - Friday as intented. It turns out the cron expression specified `1-5` for the days of the week, but this is indexed from 1 which corresponds to Sunday, so `1-5` actually means Sunday - Thursday. You can also specify this using abbreviated day names, which I think is easier to understand.
See: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-scheduled-rule-pattern.html …
> Update supporter product data export schedule in CODE

- support-config/src/main/resources/touchpoint.CODE.conf
- support-config/src/main/scala/com/gu/support/config/ZuoraConfigProvider.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-models/src/main/scala/com/gu/support/catalog/Catalog.scala
- support-models/src/main/scala/com/gu/support/catalog/Product.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/main/scala/com/gu/support/workers/states/CreateZuoraSubscriptionState.scala
- support-models/src/main/scala/com/gu/support/workers/states/ExecutionTypeDiscriminators.scala
- support-models/src/main/scala/com/gu/support/workers/states/SendThankYouEmailState.scala
- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
- support-workers/src/main/scala/com/gu/acquisitions/AcquisitionDataRowBuilder.scala
- support-workers/src/main/scala/com/gu/emailservices/FailedContributionEmailFields.scala
- support-workers/src/main/scala/com/gu/emailservices/GuardianLightEmailFields.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/UpdateSupporterProductData.scala
- support-workers/src/main/scala/com/gu/zuora/productHandlers/ZuoraGuardianLightHandler.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/GuardianLightSubscriptionBuilder.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/UpdateSupporterProductDataSpec.scala
Following on from #6498 this PR adds support for purchasing Guardian Light on the backend.
**Note: does not include the thank you page or completed thank you/failure emails, this work will be done in future PRs.**
[**Trello Card**](https://trello.com/c/V7r1ALrC/1211-checkout-support-for-new-product-backend)
So that users can purchase Guardian Light and the correct data is added to Zuora.
I've been able to put through a transaction successfully in CODE: …
> Guardian Light Backend Support

- support-lambdas/acquisition-events-api/ExampleRequestBody.json
This change updates the sample json payload for acquisition-events-api, to match the schema from `AcquisitionDataRow`, defined here:  https://github.com/guardian/support-frontend/blob/f928ea46718881c867b649c139a5378ca361b84a/support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala (they have drifted from one another).
> documentation: update ExampleRequestBody.json

- support-frontend/build.sbt
- support-payment-api/build.sbt
Force `commons-io:commons-io` to 2.14.0
This addresses a vulnerability reported by dependabot.
> Force commons-io:commons-io to 2.14.0

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Adds the settings required for the UK Black Friday Countdown.
[**Trello Card**](https://trello.com/c/AQiMH4wU)
To engage readers to take up the discount available for Black Friday before the deadline.
Force campaign with `?forceCampaign=ukBlackFriday2024` at the end of the URL when running locally.
> Add UK Black Friday countdown

- support-frontend/assets/components/test-user-banner/thankYouUserTypeSelector.tsx
- support-frontend/assets/helpers/forms/errorReasons.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/oneOffContributions.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/redux/checkout/personalDetails/state.ts
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-payment-api/src/main/scala/backend/PaypalBackend.scala
- support-payment-api/src/main/scala/backend/StripeBackend.scala
- support-payment-api/src/main/scala/controllers/StripeController.scala
- support-payment-api/src/main/scala/model/UserType.scala
- support-payment-api/src/main/scala/model/paypal/EnrichedPaypalPayment.scala
- support-payment-api/src/main/scala/model/stripe/StripeCreateChargeResponse.scala
- support-payment-api/src/main/scala/model/stripe/StripePaymentIntentsApiResponse.scala
- support-payment-api/src/main/scala/services/IdentityService.scala
- support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
- support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
- support-payment-api/src/test/scala/controllers/StripeControllerSpec.scala
- support-payment-api/src/test/scala/model/stripe/StripeCreateChargeResponseSpec.scala
Returning the identity user type for one time payments through the API, and using this information on the client to set a URL param on the thank you page.
This client side solution does not work for PayPal, as we redirect them to the site and can't set the URL params
Use the new one time checkout and see "userType=x" when redirected to the thank you page. 
I used the [always authenticate](https://docs.stripe.com/testing?locale=en-GB#regulatory-cards) card to simulate 3DS, as that makes an additional API call
> One time checkout - get user type

- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
For the Black Friday 2024 campaign we have been asked to hide the campaign unless there is a promo code in the URL parameters.
[**Trello Card**](https://trello.com/c/wQSXGTnX)
So that users are not confused by the headline not matching the discount.
> Hide campaign without promo code

- support-frontend/assets/helpers/campaigns/campaigns.tsx
I noticed that the copy for the Giving Tuesday 24 hour extension label had changed slightly. The description text changes on the Trello card are not logged so it was not obvious that it had changed but spotted this morning.
[**Trello Card**](https://trello.com/c/gECTtqrM)
Update to text.
> Update Giving Tuesday extension label to match Trello card requirements

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
The `newOneTimeCheckout` A/B test has ended, the new one-time-checkout achieved parity with the existing checkout so we will be pushing all traffic to that. This is the first step in that roll-out, where we end the test and direct all traffic from 3-tier LP to new one-time-checkout.
> Send all traffic from 3-tier LP to new one-time-checkout

- support-frontend/assets/helpers/campaigns/campaigns.tsx
We have been asked to start the Giving Tuesday copy and countdown sub-campaign early so this brings the date forward.
[**Trello Card**](https://trello.com/c/gECTtqrM) see also team chat
> Start Giving Tuesday early - display countdown, headline copy

- support-frontend/assets/helpers/campaigns/campaigns.tsx
We noticed that the Black Friday campaign's extension label did not actually mention Black Friday so this is a quick fix for that.
Copy agreed with MRR.
[**Original Trello Card**](https://trello.com/c/AQiMH4wU)
> Add Black Friday to title to clarify discount

- support-modules/acquisition-events/src/main/scala/com/gu/support/acquisitions/models/AcquisitionDataRow.scala
We will soon be sending Feast related subscription acquisitions to the web acquisition API and here we are updating the model used by bigquery-acquisitions-publisher, by registering the product we will be using: `FEAST_APP`.
> Update AcquisitionData model to handle Feast app product

- support-frontend/app/controllers/Application.scala
- support-frontend/test/controllers/ApplicationTest.scala
We want to redirect from `/contribute/checkout?selected-contribution-type=one_off` to `/one-time-checkout`. If present we should convert the `selected-amount` query string parameter to `contribution`.
For example:
Old URL: https://support.theguardian.com/uk/contribute/checkout?selected-contribution-type=one_off&selected-amount=30
New URL: https://support.theguardian.com/uk/one-time-checkout?contribution=30
Note: we should preserve all other query string parameters.
[**Trello Card**](https://trello.com/c/nTYMv0x1/1281-add-redirect-on-old-url-to-new-url-as-we-did-for-generic-checkout)
All one time contributions should now be going through the new checkout. This ensures any old links will get the new checkout. …
> Add redirect to new one time checkout from old checkout

- support-frontend/assets/helpers/productCatalog.tsx
- support-frontend/assets/helpers/urls/url.ts
- support-frontend/assets/pages/[countryGroupId]/components/accordianComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/componentContainer.tsx
- support-frontend/assets/pages/[countryGroupId]/components/guardianLightCards.tsx
- support-frontend/assets/pages/[countryGroupId]/components/headerCards.tsx
- support-frontend/assets/pages/[countryGroupId]/components/landingPageLayout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/posterComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianLightLanding.tsx
Build Guardian Landing Page structure as per (initial / subject to change ) [Figma](https://www.figma.com/design/daOtcjwsPKfCc1GvSpuBn7/Consent-or-Pay---user-flows?node-id=1379-29821&t=Q1UQLFZz4buXMc00-1)
Will load the following PR components into this Structure->
- [HeaderCards](https://github.com/guardian/support-frontend/pull/6577)
- [PosterComponent](https://github.com/guardian/support-frontend/pull/6579)
- [AccordianComponent](https://github.com/guardian/support-frontend/pull/6578)
Note:
- Further PR's will refine this design as the Figma design gets approved. 
- Images/Icons to be confirmed, placeholders used currently.
[**Trello Card**](https://trello.com/c/AupUM3yM/1235-guardian-light-landing-page-structure)
https://support.thegulocal.com/uk/guardian-light
|mobile|tablet|desktop| …
> Guardian Light: Initial Landing Page Structure 

- support-e2e/package.json
- support-e2e/playwright.code.config.ts
Adds two new package scripts:
```
$ yarn test-smoke-code
$ yarn test-smoke-ui-code
```
So that we can run the playwright tests against CODE without having to manually change config.
> Add support for easily running playwright tests against CODE

- support-frontend/assets/helpers/campaigns/campaigns.tsx
Removing the countdown settings from the US End of Year campaign
[**Trello Card**](https://trello.com/c/zWf319Jp)
The US team have made the decision not to run the discount at this time.
> Remove discount countdown from useoy campaign as it is not happening after all

- support-frontend/assets/pages/[countryGroupId]/guardianLightLanding/guardianLightLanding.tsx
Guardian Light Landing Pages 
- Code/Dev : Display
- Prod: Hide 
To stop anyone checking out before the `GuardianLight` product is ready
|Prod|Dev or Code|
|-----|-----|
|![image](https://github.com/user-attachments/assets/9249847d-e551-4351-9dd8-aceb1ee24806)|![image](https://github.com/user-attachments/assets/a7d9a837-0ea0-4ff9-8436-d1ab3f45482a)|
> Guardian-Light :  Viewable in Dev or Code (only)

- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/paypal.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripe.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Refactor some server calls related to Stripe and PayPal out of the checkout. It's not a massive saving in terms of line numbers, but I think it reduces cognitive load because you don't have to mentally parse the ins and outs of the fetch calls when scanning the component, the nitty gritty is now abstracted away into another module.
-  [ ] [The change doesn't …
> Refactor some server calls related to Stripe & PayPal out of checkout

- support-frontend/assets/components/otherAmount/otherAmount.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/contributionsPriceCards.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/formSections/amountAndBenefits.tsx
- support-frontend/assets/pages/supporter-plus-landing/formSections/patronsPriceCards.tsx
We had some alarms from the one-time checkout where the other amount field was allowing large numbers, above the configured min/max contribution values, we found on investigation no validation to be in place on this input, so have used the native HTML min/max [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) available to `<input type='number />` to manage this validation:
> Apply min/max validation to other amount field on one-time checkout

- support-e2e/tests/utils/paypal.ts
Update one of the PayPal account prefixes used in the e2e tests. The account we're replacing had an issue, so we created a new one.
> Update one of the PayPal test account prefixes

- support-e2e/README.md
- support-e2e/package.json
- support-e2e/tests/cron/checkout.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/tieredCheckout.test.ts
- support-e2e/tests/utils/testUserDetails.ts
- support-e2e/tests/utils/userFields.ts
- support-e2e/tsconfig.json
- support-e2e/yarn.lock
Add a smoke test (card) and a cron test (PayPal) for Tier Three checkout.
I've done a bit of refactoring to pull some user details fixtures out into a separate file so they can be re-used.
[**Trello Card**](https://trello.com/c/L8LD1pz3/1270-tier-3-e2e-test)
We'd like to know if Tier Three checkouts are broken in prod.
Locally we can run:
`$ yarn test-smoke-ui`
`$ yarn test-cron-ui`
-  [ ] [The …
> Add Tier Three to smoke & cron e2e checkout tests

- support-e2e/tests/utils/paypal.ts
Fail e2e test noisily if the `PAYPAL_TEST_PASSWORD` env var isn't set.
Previously we silently allowed this env var to be undefined and then interpolated into the string we build up for the PayPal password, giving an incorrect password. Too many incorrect login attempts causes the account to be locked, which we want to avoid.
Run the tests locally with the env var: ✅ 
Run the tests locally without the env var:
-  [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md …
> Fail e2e test noisily if the `PAYPAL_TEST_PASSWORD` env var isn't set

- support-frontend/assets/helpers/campaigns/campaigns.tsx
Updates the colour theme for the countdown, updates the label that becomes the title during the duration of the countdown and updates the subheading text for the campaign.
[**Trello Card**](https://trello.com/c/jK383PT4)
Update the countdown ahead of the final week of the US end of year campaign before the code chill.
Clone the branch, duplicate the final countdown and alter the start and end date to around 'now'. Run locally and use the campaign id in the URL parameters to see the countdown in action.
> Final countdown checkout colour, title, subheader changes

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Adding an alarm for no successful Tier Three checkouts in 6 hours.
[**Trello Card**](https://trello.com/c/Pf7IkuIx/1271-tier-3-no-acquisitions-alarm)
So that we are alerted if something is broken in the checkout flow for Tier Three.
> Add alarm for no successful Tier Three checkouts in 6 hours

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Increase the time period for the Tier Three alarm.
Since adding this alarm we've had a few false positives.
> Make the Tier Three checkout alarm less sensitive

- support-frontend/app/views/main.scala.html
"mainJsBundle" is just an example name here...
Currently on the support site we put our `<script async src="myScript.js"></script>` tag at the bottom of the `<body>`, doing so in combination with the `async` attribute ensures that the script is downloaded without blocking other resources or rendering and is executed as soon as it is ready. However the browser needs to parse the page before it reaches this `<script>` tag, and we don't initialise download until then.
Including `<link href="myScript.js" rel="preload" as="script">` in the `<head>` instructs the browser to start fetching the specified resource (`myScript.js`) as soon as it encounters the `<link>` tag in the `<head>`. This helps reduce latency because the browser doesn't need to wait until it encounters the `<script>` tag to …
> Preload mainJsBundle bundle

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Fix the Tier Three alarm description and also increase the period to 24 hours.
The Tier Three alarm description is currently out of sync with the alarm config. This is because I forgot to update the description in #6634. Instead of having to remember, this PR changes approach to deriving the description from the alarm config so it's impossible to get out of sync. If we like the approach we can use if for the other alarms in here.
`yarn test` in the `cdk` dir. The snapshot contains the updated description.
> Update the Tier Three alarm description and increase period

- support-frontend/assets/pages/supporter-plus-landing/components/guardianTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/checkoutScaffold.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/firstStepLanding.tsx
Change the CTAs on the contributions only checkout (shown to users in certain countries) to redirect to the new generic or one time checkouts, instead of the old second step checkout.
Also remove the patrons section.
[**Trello Card**](https://trello.com/c/rhciXIi5/1289-contributions-only-landing-page-for-users-in-vat-affected-country-list-countries-that-dons-sell-subs-phase-1)
Part one of deprecating the old two step checkout
Go to https://support.thegulocal.com/int/contribute?country=lb (LB is an example that works in local), click "Continue to checkout" from any of the tabs and go to the correct checkout with the correct amount and rateplan
Link
> Contributions Only Landing - link to generic checkout

- support-e2e/tests/cron/checkout.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/test/checkout.ts
Add e2e Playwright tests for Guardian Ad-Lite, like we have for other products, so that we find out quickly if there are issues affecting users purchasing this product.
1. Add Smoke (`UK,Monthly,CC`) Guardian Light Test - GitHub Action Uon Build
2. Add Cron (`UK,Monthly`PayPal`) Guardian Light Test - GitHub Action Every Period
NOTE: 
- We will be in the process of renaming the product `guardianLight` to `guardianAdLite`. After this occurs, this product will be renamed.
- Preceeds Thankyou page work (as its in design currently)
[**Trello Card**](https://trello.com/c/zxHg6b8m/1274-prepare-guardian-light-e2e-playwright-tests)
{within `.../support-e2e`}
Cmd-Line Results->
- `yarn test-smoke`
- `yarn test-cron`
Chromium Playwright Interface->
- `yarn test-smoke-ui`
- `yarn test-cron-ui` …
> Guardian Ad-Lite: Playwright tests

- support-frontend/assets/components/checkoutBenefits/benefitsCheckList.tsx
Fix the improper nesting of table console error
[**Trello Card**](https://trello.com/c/djfq869M/1310-landing-pages-benefits-improper-use-of-nested-table-use-list)
Before
After
> Fix improper nesting of table

- support-frontend/assets/components/button/_sharedButton.tsx
- support-frontend/assets/components/content/content.tsx
- support-frontend/assets/helpers/images/theGrid.ts
- support-frontend/assets/helpers/internationalisation/country.ts
- support-frontend/assets/helpers/tracking/acquisitions.ts
- support-frontend/assets/helpers/user/details.ts
- support-frontend/assets/pages/aus-moment-map/hooks/useWindowWidth.ts
- support-frontend/package.json
- support-frontend/yarn.lock
Remove utility types package and replace all usages of $Keys with keyof
I noticed we had this dependency which only seemed to serve one purpose, which can be done with native Typescript
> Remove utility types package and replace all usages of $Keys

- support-frontend/assets/helpers/campaigns/campaigns.tsx
There has been a last minute request to change the headline and copy for the US end of year campaign.
[**Trello Card**](https://trello.com/c/t5guJPxW)
Run locally or deploy to code and use the ?forceCampaign=usEoy2024 campaign parameter to force the campaign.
> Copy change to headline and subhead for final countdown

- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This is to change the default copy in subheading for  US  post usEoy2024 campaign and after removing ticker
Change subheading for US  to:
We're not owned by a billionaire or profit-driven corporation: our fiercely independent journalism is funded by our readers. Monthly giving makes the most impact (and you can cancel anytime). Thank you.
[**Trello Card**](https://trello.com/c/Nw6Z4dG0/868-remove-ticker-on-us-lp-and-change-to-default-copy)
Tested in CODE
> Update the US default copy

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Enables the AB-Test in the `Move ad-free benefit from tier2 to tier3` [PR](https://github.com/guardian/support-frontend/pull/6637)
> Landing Page: Move ad-free benefit from tier2 to tier3 - ab-test enable

- support-frontend/assets/helpers/__tests__/validationTest.ts
- support-frontend/assets/pages/[countryGroupId]/validation.ts
Extending the checkout client side input validation to reject all emojis.
We had a case in prod where an emoji made it to the backend (and was correctly rejected). However we expected this to be rejected in the client side validation. It turns out that some emojis don't match `Extended_Pictographic` so the regex which said "anything other than `Extended_Pictographic`" let it through. We now reject `Extended_Pictographic` and `Emoji_Presentation`.
I've extended the tests and checked in CODE.
Emoji character accepted by client side validation:
Emoji character rejected by client side validation: …
> Extend client side input validation to reject all emojis

- support-frontend/assets/helpers/storage/contributionsCookies.ts
- support-frontend/assets/pages/supporter-plus-thank-you/supporterPlusThankYou.tsx
We want to stop working out user benefits from what products they have and instead delegate that to the user-benefits api.
As part of this work we no longer want to set a cookie to inform dotcom that a user has made a one time contribution, but instead set the 'hide support messaging' cookie which tells DCR & support-dotcom-components to show fewer support asks.
This PR works in combination with: https://github.com/guardian/dotcom-rendering/pull/13037
> Set 'hide support messaging' cookie for one time contributors

- support-e2e/tests/test/oneTimeCheckout.ts
- support-e2e/tests/utils/cardDetails.ts
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Ensure that the overlay is cleared on the one time checkout if a card payment fails server side.
Previously we noticed that if there was a server side failure on the one time checkout, you'd see an error message but the "processing payment" overlay would remain up, which meant you couldn't interact with the form to fix whatever the problem was.
We've also added some playwright coverage for this scenario.
We've added some playwright test coverage and tested in the browser.
I've also deployed this branch to CODE and put through a card and PayPal transaction.
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-tech …
> Remove overlay if one time card payment fails server side

- support-frontend/assets/helpers/__tests__/formValidation.ts
- support-frontend/assets/helpers/forms/formValidation.ts
- support-frontend/assets/helpers/subscriptionsForms/rules.ts
- support-frontend/package.json
- support-frontend/yarn.lock
Remove `react-day-picker` NPM package ~~and replace with our own implementation.~~ and the method which uses it (it's no longer needed, as it was only ever used for Digipack Gift subs which we no longer support).
The version of `react-day-picker` we're on is 5 years old, and the interface has changed. The only code paths which use it are no longer needed.
~~I took this approach:~~
~~1. Make the existing method (which does use `react-day-picker`) testable, by allowing passing in `now`~~
~~2. Add some tests~~
~~3. Update the method, removing `react-day-picker` and ensure tests still pass~~ …
> Remove react-day-picker

- support-frontend/app/admin/settings/Switches.scala
- support-frontend/assets/helpers/campaigns/campaigns.tsx
This PR is to remove the details of the  US EOY , AUS and UK Black Friday campaigns completed in 2024. 
[**Trello Card**](https://trello.com/c/YDRaegWn/874-eoy-campaigns-tidy-up)
General code clean up
Deployed the branch to CODE and tried the links 
https://support.code.dev-theguardian.com/us/contribute?forceCampaign=usEoy2024
https://support.code.dev-theguardian.com/us/contribute?forceCampaign=ausEoy2024
which did not return any campaign related details
> Remove the completed 2024 campaign details for US, AUS and UK Black Friday

- support-frontend/assets/helpers/forms/paymentMethods.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
Apply headline and associated copy changes reflecting a `payment processing`/`pending` status. This will be for recurring products only currently (as retry mechanism on generic checkout only).
1. Add `your recurring subscription is being processed` to end of headline.
2. Add new processing paragragh `Thankyou for subscribing to a recurring subscription. Your subscription is being processed and =you will receive an email when your account is live.`
3. Disable signUp thankyou components for unregistered users in pending (awaiting for signUp email according to copy).
Task:
- Add a  `status:pending/succeess` to session storage
- Read from it and apply messaging shown above
[**Trello Card**](https://trello.com/c/XnvxDsnY/1306-build-recurring-generic-ty-page-processing-state)
(`All-access …
> Thankyou Page: Pending Processing State Messaging For Recurring Products

- support-frontend/assets/helpers/page/page.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/events/router.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/assets/pages/digital-subscriber-checkout/digitalSubscriptionRouter.tsx
- support-frontend/assets/pages/error/error404.tsx
- support-frontend/assets/pages/error/error500.tsx
- support-frontend/assets/pages/error/maintenance.tsx
- support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingProps.ts
- support-frontend/assets/pages/paypal-error/payPalError.tsx
- support-frontend/assets/pages/promotion-terms/promotionTerms.tsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.tsx
- support-frontend/assets/pages/subscriptions-landing/subscriptionsLandingProps.ts
- support-frontend/assets/pages/subscriptions-redemption/subscriptionsRedemption.tsx
- support-frontend/assets/pages/supporter-plus-landing/supporterPlusRouter.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.tsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx
- support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLandingProps.ts
The existing `setUpTrackingAndConsents` function calls `abTest.init` in order to register ab tests with ophan.
We then call `abTest.init` again in various places, to decide what to render based on the ab participations.
This means we're running the same logic twice per pageview, and we call `abTest.init` from an awful lot of places.
With this refactor, we instead call `abTest.init` once at the start, and pass this down into the places it's needed.
This means `setUpTrackingAndConsents` now takes a `participations` parameter.
Also, any pages which are still using Redux already have the ab participations available in the store. So in these cases we now use this.
Context: I'm trying to simplify ab test participations logic ahead of some work on the landing page.
> Initialise ab participations once

- support-payment-api/src/main/scala/model/Currency.scala
- support-payment-api/src/main/scala/services/PaypalService.scala
- support-payment-api/src/main/scala/services/StripeService.scala
- support-payment-api/src/test/scala/model/CurrencyTest.scala
- support-payment-api/src/test/scala/services/PaypalServiceSpec.scala
Add min amount validation to the payment API for one time contributions.
[**Trello Card**](https://trello.com/c/NXeDtm19/1305-min-max-amount-server-side-validation)
We already have client side validation for this, but we'd like to enforce server side too as this makes us more robust.
I've tested this in CODE. In order to do this I had to temporarily remove the client side validation. The error message we show in this case is quite generic, but I think in general we don't expect users to hit this as the client side validation should kick in before the request even makes it to the backend.
Stripe:
PayPal:
If we need to, perhaps we could follow up with a more contextual error message in another PR.
-  [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-a …
> Add min amount validation to server side one time payments

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Add a max amount check to the 'Other' amount in one time checkout. If it is above the maximum - it does not go into the `finalAmount` variable where it can be used to set the amount in the rest of the page. This stops it reaching Stripe's JS where it could be above the maximum.
[**Trello Card**](https://trello.com/c/HPxFALFh/1360-revisit-client-side-max-validation-on-amount-field-in-one-time-checkout)
Type in a _very_ large number in the other amount, the amount is not listed in the payment button and does not crash the page.
Before:
(Above our max)
(Above Stripe's max)
After:
> One-time checkout: prevent large other amount causing error

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
We are seeing regular errors in the payment-api logs whenever a test user makes a one time contribution. This is because we record these contributions in the SupporterProductData DynamoDB table, and for test users these are written to the CODE version of the table. However currently the PROD app doesn't have permissions to write to the CODE table so there is an exception. This PR fixes the issue.
> PROD payment api needs to be able to write to CODE SupporterProductData dynamo table for test users

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
What are you doing in this PR?
Disable AB-Test in the `Move ad-free benefit from tier2 to tier3` for US-Only #6637
> Landing Page: Disable Move ad-free benefit from tier2 to tier3 - all regions

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
We attach the `pageViewId` to the URL of the Ticket Tailor iframe as a query string parameter, this allows us to track in the data-lake page view IDs against ticket purchases. However a high percentage (~60%) of ticket purchases in the data-lake have a `null` page view id. I'd like to rule out this being down to a race condition, where pageViewId is not defined when we construct the URL. I'm using sentry to log instances of `pageViewId` being falsy.
[**Trello Card**](https://trello.com/c/kCakcGbK/1322-page-view-id-missing-from-60-of-ticket-tailor-events)
> use sentry to log if pageviewId not available on event listing

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/router.scala.html
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/guardianAdLiteLanding.tsx
- support-frontend/assets/pages/[countryGroupId]/lazyRouter.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/webpack.entryPoints.js
Creating a server side A/B test: the variant is a lazy loading router previously implemented in #6628, the control is the router as normal.
[**Trello Card**](https://trello.com/c/ZWtVE5Xg/1313-spike-server-side-performance-a-b-test)
We want to test the changes by seeing whether better page performance improves our conversion and business metrics
We will probably use the normal A/B test dashboard for results. The participation in the test is rendered as a script tag in the HTML and is passed to the normal participations object.
> Create server side test for lazy loading router

- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
Fixing a typo on the generic thank you page
Before
After
> Fix thank you page typo

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/productCatalog.ts
Removes the unused code associated with this [Ad-free PR](https://github.com/guardian/support-frontend/pull/6637) 
Keeps  ab-test filter of `productCatalog` benefits for future use (including new display field)
> Landing Page: Remove code associated with the ad-free ab-test

- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
We noted an issue when making the `adFreeTierThree` A/B test target the US only.
**Main issue identified:** Once allocated to a country specific A/B test a user remains allocated to that test for the duration of their session, regardless of whether they change country to one not covered by the A/B test (eg. uses the country group switcher).
**Expected behaviour:** The user would not remain allocated to a country specific A/B test if they are no longer in the target country. 
**Underlying cause of issue:** The initial allocation to the country specific A/B test (eg. adFreeTierThree) is saved in session storage, any subsequent page views in the session reallocate the user to the test because of it's presence in session storage.
**Reproduce issue (dependent on country specific …
> Only check abParticipations in session storage if persistPage is defined in the abTestDefinition

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Removing the A/B test for the Link Stripe (Express checkout) payment method, which has been off for a while
[**Trello Card**](https://trello.com/c/uQE2EUU6/1329-remove-link-payment-method-ab-test)
> Remove Link as payment method AB test

- support-frontend/assets/helpers/storage/contributionsCookies.ts
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
We set a cookie after a successful one-time contribution on support-fronted so that the contributor will not see any support messaging on dotcom for 90 days.
In https://github.com/guardian/support-frontend/pull/6643 I switched from using the one-time contribution cookie for this to the gu_hide_support_messaging cookie which is used by dotcom to store the value returned from members-data-api/user-benefits api.
However dotcom will delete this cookie if it exists for non signed in users, so it is not suitable without reworking the behaviour in dotcom which I would rather not do at this point.
This PR reverts the earlier PR, taking account of the fact that the cookie is now set in the new one-time checkout thank you page rather than the old thank you page.
> Reinstate one-time contribution cookie.

- support-frontend/assets/pages/[countryGroupId]/lazyRouter.tsx
Use the updated path for the Guardian Ad-Lite landing page in the LazyRouter.
We noticed this path was sporadically 404ing (at the client side routing layer) before, it turns out this was because the path in the LazyRouter was still using the old name (the branch must have been created before the re-name, but merged after the re-name). …
> Fix LazyRouter /guardian-ad-lite landing page path

- support-e2e/tests/test/checkout.ts
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/getProductFields.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/subheading.tsx
- support-frontend/package.json
- support-frontend/yarn.lock
Update the support-services-lambdas package to bring in removal of the `GuardianLight` product from the catalog and type object.
[**Trello Card**](https://trello.com/c/3Hs3ntw0/1347-rename-guardian-light-to-guardian-ad-lite-in-the-product-catalogue)
~~**Note: this is based on #6700 and should be merged after that PR. Will need rebasing first.**~~ Done!
We've moved over to the newly named `GuardianAdLite`.
Visiting the checkout with the old product name now returns an error `Product not found`. Can put through a purchase of the new Ad-Lite product (and other products) successfully. …
> Update support-service-lambdas package and remove remaining GuardianLight references

- support-frontend/assets/pages/[countryGroupId]/events/events.tsx
An alternate log to https://github.com/guardian/support-frontend/pull/6694, as the original log didn't report anything in ~5 days. I wondered whether `hashUrlSearchParams` contained a `'p[meta_page_view_id]` key as we'd expect, we can check this using https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/has. If not log an expection in Sentry.
> Check if hashUrlSearchParams has p[meta_page_view_id]

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/controllers/SubscriptionProductCookiesCreator.scala
- support-frontend/test/controllers/SubscriptionProductCookiesCreatorTest.scala
Update the cookie set by the checkout when a user makes a Guardian Ad-Lite purchase to be persistent. It should persist for 7 days. Previously it was a session cookie. This includes a refactoring to support persistent cookies on the checkout in a product specific way.
[**Trello Card**](https://trello.com/c/fzP5uikS/1369-update-cookies-set-by-support-frontend)
This gives the user a 7 day grace period to sign in after purchasing.
Purchase Guardian Ad-Lite in CODE, see that the cookie is set correctly:
For other products, cookies continue to be correctly set as session cookies: …
> Update cookie set by Guardian Ad-Lite purchase to be persistent

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Add the `transaction-fee-covered` label to the acquisition data when the checkbox is ticket.
[**Trello Card**](https://trello.com/c/yz1SYX5r/1388-add-transaction-cost-label-to-new-one-time-checkout)
The label was missed when implementing the feature on the new checkout, which means it's harder (or impossible) to figure out how many people checked the box and bought a one-off contribution.
Buy a one-off contribution and see the label in the datalake
> Add transaction fee covered label to new one-time checkout

- support-frontend/app/actions/CustomActionBuilders.scala
We have some code which triggers an alarm every time we return a non 200 response from the `CreateSubscriptionController` class, however there are some non 200 responses which we do not want to alarm on like 400 errors.
This PR changes the behaviour to only alarm on a 500 error ie. an internal server error where our code has behaved in an unexpected way.
> Only alarm on 500 responses

- support-frontend/package.json
- support-frontend/yarn.lock
This updates the `@guardian/browserslist` package version and also the `caniuse-lite` db which contains browser stats. These are used in combination with `preset-env` to determine the code to be generated by babel. When I ran the upgrade I saw the following log line: `No target browser changes`. So I don't think this actually changes anything regarding the browsers we're targeting.
Update: I actually don't think we use caniuse-lite at all since `@guardian/browserslist-config` contains its own stats pulled from our GA data. We can see that this PR doesn't change any bundle sizes at all, so I think that confirms this upgrade is essentially a no-op.
We see the following warnings in local dev and CI:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why …
```
> Update browserslist packages

- support-frontend/assets/helpers/rendering/render.ts
When we call the metric-push-api, use a HEAD request.
This API now accepts HEAD requests instead of GET requests. See also guardian/support-service-lambdas#2652.
I've tested locally by forcing an error and can see the metric-push-api invoked as expected. …
> Make HEAD requests to the metric-push-api

- support-frontend/yarn.lock
Upgrade path-to-regex npm package.
Dependabot reported a vulnerability so bump this to 0.1.12.
> Upgrade path-to-regex

- support-frontend/knip.config.js
- support-frontend/knip.production.config.js
- support-frontend/package.json
Creating a production mode config file for knip and a new script to run it in production mode with that config.
Production mode is a useful feature because it identifies code only used in tests and not by production code. However in #6721 it became a lot noisier because `ignoreExportsUsedInFile` was set to false. I've set this to true in the new config
Run `yarn knip --production` and compare to `yarn knip:production`. 
There are much fewer errors in the latter, most of which are mocks and are easier to ignore
`yarn knip --production`
`yarn knip:production`
> Create knip production mode specific config

- lighthouserc.json
Removing the assertion of third party resource count from our lighthouse CI action, after refactoring the router in #6733 it's been bumped up to 33. But this doesn't seem like a metric worth tracking
Example of what these are from the generated report
> Lighthouse - remove third party resource count

- support-frontend/assets/helpers/rendering/render.ts
Reverts guardian/support-frontend#6732.
The alarm this was supposed to help quieten down has been noisier than ever overnight, so revert this change.
See also guardian/support-service-lambdas#2653.
> Revert "Make HEAD requests to the metric-push-api"

- support-frontend/app/services/HttpIdentityService.scala
Occassionally we see errors which we're pretty sure are coming from the /guest endpoint, but when we log the error the endpoint isn't specified. I think that's because the IdentityError instance doesn't have the endpoint set on it in some cases. This PR ensures we're doing that.
Related to: [**Trello Card**](https://trello.com/c/2Utb3wDH/1225-500-errors-from-identity)
Before: `ServerError(Error calling Identity: Email in use: This email has already been taken)`
After: `ServerError(Identity error calling /guest: Email in use; This email has already been taken)`
This removes some ambiguity when reading the error message in the logs.
Tested locally by forcing an error and saw the correct message get logged.
Smoke tests run fine against local app. …
> Log the endpoint if we get an error back from `/guest`

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/models/identity/responses/IdentityErrorResponse.scala
Don't alarm on `Email in use` response from Identity `/guest` endpoint.
Sometimes `POST /guest` returns `Email in use` even though we already checked whether the user existed using the `GET /user` endpoint. According to identity occasionally users get into a weird state and this is a result of that. I think this should still result in a 500 (it's not related to something the user has done) but we don't want to alarm on it.
I've tested locally by forcing the error, in the logs I see:
```
not pushing alarm metric for 500 Some(email_address_already_taken) as it is in our ignore list
``` …
> Don't alarm on "Email in use" response from Identity `/guest` endpoint

- support-frontend/assets/helpers/abTests/__tests__/abtestTest.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/subscriptionsForms/formActionCreators.ts
- support-frontend/assets/helpers/tracking/quantumMetric.ts
- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/promotion-terms/DigitalPackTerms.tsx
- support-frontend/assets/pages/subscriptions-landing/copy/subscriptionCopy.tsx
Removing any references to digisub gifting from the client side after it was removed from the server (#6736)
[**Trello Card**](https://trello.com/c/xP95HBiR/1400-remove-digi-pack-gift-code-client-side)
- Run through E2E tests
- Check digisub routes (`/subscribe/digital` redirects to `/contribute` through fastly)
> Remove digisub gift references from client side

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/frontend.ts
- support-frontend/app/actions/CustomActionBuilders.scala
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
This PR adds a new higher threshold alarm/metric.
[**Trello Card**](https://trello.com/c/2Utb3wDH/1225-500-errors-from-identity)
In #6745 we stopped alarming on the "email already taken" error from identity. It's a known issue and we don't want to spend time investigating every time it happens. However, we would like to know if it starts occurring at a higher volume. This PR adds the concept of a higher threshold alarm/metric which we can use to cover this case. The alarm will trigger if 10 or more minutes in the last hour have errors.
Forcing the "email already taken" error locally I see the following in the logs: 
```
pushing higher threshold alarm metric for 500 Some(email_address_already_taken)
```
I could also see the new metric in Cloudwatch: …
> Add a higher threshold alarm which we can use for known checkout failure reasons

- support-e2e/tests/test/checkout.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalDetailsFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/package.json
- support-frontend/yarn.lock
Implement the confirm email field but using HTML form validation - a pattern regex field that updates based on whatever is in the email field. 
This PR also enables it as an A/B test
[**Trello Card**](https://trello.com/c/mCYE3GTi/1373-add-confirm-email-field-across-products-generic-checkout-a-b-test)
This is a branch off of #6742 but using a different mechanism.
Comparison of this approach (HTML validation) vs the other approach (validate in JS)
Pros: 
- Fits with our other validation of the form
- Doesn't require a check based on the sign-in status in the form's submit function
Cons:
- Adds an additional dependency (we wanted to use [RegExp.escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/escape) but it has limited availability)
- ~Slightly …
> Confirm email - use pattern validation

- support-frontend/assets/helpers/legal.ts
Update to ad-lite terms -> `https://www.theguardian.com/guardian-ad-lite-tcs`
Affects:-
- LandingPage: 3rd Accordian Row
- Checkout: Ts&Cs Terms
NB: Currently 404'ing.
[**Trello Card**](https://trello.com/c/mskef35S/1309-add-correct-tcs-to-guardian-ad-lite-checkout-landing-page-faq)
> Guardian Ad-Lite: TsAndCs Url Update

- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This PR is to change the copy on the landing page in the US only
1. Update the benefit-  “Regular dispatches from the newsroom to see the impact of your support” [replacing Exclusive newsletter benefit on tier 2]
2. Update the heading -“Protect” [replacing “Support” in the first line of text]
[**Trello Card**](https://trello.com/c/PqlPr88B/919-change-copy-in-us-landing-page-only)
Test in CODE
> Changes for copy in US landing page only

- support-frontend/assets/helpers/productCatalog.ts
This is to add back the newsletter benefit for US
“Regular dispatches from the newsroom to see the impact of your support”
[**Trello Card**](https://trello.com/c/60Qrx4aU/926-add-newsletter-benefit-back-in-to-tier-1-in-us)
This went missing following the change in the [PR](https://github.com/guardian/support-frontend/pull/6760)
> Add newsletter benefit to tier 1 in US

- support-frontend/assets/components/stripe/stripeDisclaimer.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/guardianAdLiteCards.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/headerCards.tsx
It appears I have the Sign-In screen around the wrong way around
Change to ->
1. User is `NOT signedIn` SHOW SignIn option.
2. User is `signedIn` HIDE SignIn option.
NotSignedIn/SignedIn = regardless whether user has an ad-free account or not.
|Status|From (current CODE)|To (new DEV)|
|------------------|-----|-----|
|NotSignedIn|![image](https://github.com/user-attachments/assets/e3fc0260-830b-470e-8401-771ab14a489b)|![image](https://github.com/user-attachments/assets/2bac9794-a321-484a-8102-5e841a3e8fba)|
|SignedIn|![image](https://github.com/user-attachments/assets/00ac9ab4-64ae-4050-b49c-abc1cd95759f)|![image](https://github.com/user-attachments/assets/4d20bf0c-a7b7-4188-b004-d93969acbf6f)|
> Guardian Ad-Lite : LandingPage, display SignIn Copy when NOT Signed In

- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/forms/errorReasons.ts
- support-frontend/test/utils/CheckoutValidationRulesTest.scala
Add server side validation for billing address postcode.
[**Trello Card**](https://trello.com/c/h2sFEVzL/1399-paypal-server-side-validation-placeholder)
We've had an ongoing issue where requests where the payment method is PayPal make it to support workers with an email address in the billing postcode field. We're not sure why this happens but are hoping some server side validation will prevent it and alert users that they need to fix something. It primarily seems to affect USD Supporter Plus and recurring contributions (we collect the postcode for these) so I've focused on fixing those cases, in the PaidProductValidation object used by both products.
I've introduced a concept of a preservable error message, i.e. something we can map to copy to show the user. It'd be nice to extend this …
> Add server side validation for billing address postcode

- support-frontend/assets/components/subscriptionCheckouts/directDebit/directDebitTerms.tsx
- support-frontend/assets/components/subscriptionCheckouts/tierThreeTerms.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Copies the Ts&C's from the existing DigitalEdition LandingPage and places them in sam location on the new generic checkout when purchasing a DigitalSubscription.
Mis-matching Ts&Cs between the original DigitalEditionLandingPage and the generic checkout.
1. Align Ts&Cs
2. Remove un-required SummaryTsAndCs
3. Fixed format (half width) bug for TierThree TsAndCs
[**Trello Card**](https://trello.com/c/FXBoxx89/1415-dgital-edition-checkout-tscs)
Original->
https://support.thegulocal.com/uk/subscribe/digitaledition
New->
https://support.thegulocal.com/uk/checkout?product=DigitalSubscription&ratePlan=Monthly
https://support.thegulocal.com/uk/checkout?product=DigitalSubscription&ratePlan=Annual
|Original|New (Monthly)|New (Annual)| …
> Digital Editions: Ts&Cs align copy to original LandingPage

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- Enables the stripe express checkout (ApplePay & GooglePay in turn).
- Enable for Digital Editions too.
https://support.code.dev-theguardian.com/uk/checkout?product=GuardianAdLite&ratePlan=Monthly
> Guardian Ad-Lite : Enables the stripe express checkout (ApplePay & GooglePay in turn)

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Before this change, if the reader was paying with Stripe, and server side validation rejected the call to `/subscribe/create`, then even if the user fixed the issue which caused the validation failure, future form submissions (until the recaptcha expires) fail with the following error from Stripe: `You cannot confirm this SetupIntent because it has already succeeded` (`setup_intent_unexpected_state`).
This was happening because we were previously taking the recaptcha token, verifying it and retrieving a Stripe client secret all at the point where the recaptcha box was checked. This only happened once in the above scenario, and calling `stripe.confirmCardSetup` twice with the same client secret results in the above error.
Now, instead of getting the client secret (using the recaptcha …
> Create Stripe setup intent on form submit, not on recaptcha check

- support-frontend/assets/components/stripe/stripeDisclaimer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
1. TsCs: Footer should read `By proceeding, you are agreeing to the Guardian Ad-Lite Terms` and link to new Ts&Cs for Guardain-AdLite only.
2. TsCs: All Card payments links need capitalisation.
|Item|From|To|
|-----|------|-----|
|1/2|![image](https://github.com/user-attachments/assets/9c47e859-f82d-43a5-80da-d72897b4996f)|![image](https://github.com/user-attachments/assets/35f8f600-a597-4a73-b6e4-a19a757ee598)|
> Guardian Ad-Lite : Checkout Ts&Cs Update 

- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Adds the abandon basket cookie back into the one time checkout
The abandon basket cookie was removed from the one time checkout during a refactor and this PR adds it back in. 
One the time checkout, open the dev tools -> Application tab -> Cookies -> filter by GU_ and you should see....
when you change the amount on the choice card the cookie should update to reflect the selected amount, unless you select Other which just displays 'other'
-  [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/peop …
> Adds back the abandon basket cookie to one time checkout

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/guardianAdLiteLanding.tsx
Turn back on the Guardian Ad-Lite Landing Page so can be viewed on Prod
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/2b47a5de-d49f-4c89-a777-3809339b3c84)|![image](https://github.com/user-attachments/assets/0bc89239-83ed-4f1c-913f-4cf84223b586)|
> Guardian AdLite: Landing Page viewable in Prod

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/controllers/SubscriptionProductCookiesCreator.scala
- support-frontend/test/controllers/SubscriptionProductCookiesCreatorTest.scala
I've removed the following as they're no longer needed:
* `gu_recurring_contributor`
* `gu_digital_subscriber`
* `gu.contributions.recurring.contrib-timestamp.<billing period>`
I've refactored the cookie setting code a bit to consolidate things and make it clear where products set the same cookie(s).
[**Trello Card**](https://trello.com/c/fzP5uikS/1369-update-cookies-set-by-support-frontend)
These cookies are no longer needed.
Put through a purchase, see that these cookies are no longer set.
> Remove some cookies set by the checkout

- support-frontend/app/controllers/DiagnosticsController.scala
- support-frontend/app/controllers/SubscriptionProductCookiesCreator.scala
- support-frontend/assets/helpers/storage/contributionsCookies.ts
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/test/controllers/SubscriptionProductCookiesCreatorTest.scala
Some additional work on the cookies which support-frontend sets:
- Renames the gu_user_features_expiry to gu_user_benefits_expiry to match the same rename in DCR made [here](https://github.com/guardian/dotcom-rendering/pull/13277)
- Sets the gu_hide_support_messaging cookie on the succsessful completion of a one time contribution rather than the gu.contributions.contrib-timestamp cookie. This is to work with the new benefits mechanism introduced in the PR above
- Updates the DiagnosticController class which serves the /cookies page to only show currently relevant cookies
> More cookie changes

- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Adding an aria-label attribute to links on 3 tier landing page cards & the one time checkout link:
Example:
The actual text on these links reads "Support" in every case, with the meaning coming from the context of the card. To make this clearer for screen readers set the `aria-label` attribute to the product name/label.
-  [ ] [The change doesn't use only …
> Set `aria-label` for checkout links on 3 tier landing page

- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
Reverts guardian/support-frontend#6776
Reverting this while I investigate a smoke test failure.
> Revert "Set `aria-label` for checkout links on 3 tier landing page"

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
ABTest: digitalEditionCheckout ->
- Remove non-required use of `canRun` 
- Replace with `persistsPage` instead.
> Digital Editions: Subscribe Landing Page ab-test simplification

- support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.scss
Spacing bug in mobile, no margin-top between the dgital editions buttons
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/059e5b73-17ce-44c2-819b-c0ed801d39bc)|![image](https://github.com/user-attachments/assets/60f49fcc-0256-4935-b1d3-1ec705099c94)|
> Digital Editions: Subscribe Landing Page digital edition mobile button spacing

- support-e2e/tests/smoke/promo-codes.test.ts
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
This is a replay of #6776 which I reverted due to a smoke test failure. This version includes a small tweaks to the smoke tests and they now pass.
[**Trello Card**](https://trello.com/c/Zvj6K3rU/614-add-3-tier-improve-subscribe-voiceover-accessibility)
The actual text on these links reads "Support" in every case, with the meaning coming from the context of the card. To make this clearer for screen readers set the aria-text to the product name/label.
Also add aria-label to the support once button. …
> Set `aria-label` for checkout links on 3 tier landing page (attempt 2)

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/posterComponent.tsx
Inserts (guim optimised) poster image onto Guardian Ad-Lite Landing Page
[**Trello Card**](https://trello.com/c/mocDMfVV/1405-guardian-ad-lite-landing-page-image-update)
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/468469cc-2af5-4066-b28b-09183b4ddbca)|![image](https://github.com/user-attachments/assets/442956d9-e0f1-4fb1-9b05-7c34bdcb0b11)|
> GuardianAdLite: Add Landing Page poster image

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/contributions.scala.html
We have an issue with Google failing to to index the US variant of the support checkout: [https://support.theguardian.com/us/contribute](https://support.theguardian.com/us/contribute "‌") .
All other regional variants of the `/contribute` route are indexed by Google eg. `uk/contribute` [https://search.google.com/search-console/inspect?resource\_id=sc-domain%3Asupport.theguardian.com&id=H5PfelVvg08EcNH\_uiooAA&hl=en-GB](https://search.google.com/search-console/inspect?resource_id=sc-domain%3Asupport.theguardian.com&id=H5PfelVvg08EcNH_uiooAA&hl=en-GB "‌"), however `us/contribute` cannot be indexed [https://search.google.com/search-console/inspect?resource_id=sc-domain%3Asupport.theguardian.com&id=7Zou81TL8dIg3wBxbshnhg&hl=en-GB](https://search.google.com/search-console/inspect?resource_id=sc …
> Add a canonical link tag for the contributions landing page

- support-frontend/assets/helpers/productPrice/productPrices.test.ts
- support-frontend/assets/helpers/productPrice/productPrices.ts
`getDiscountVsRetail` returns the "saving vs retail" % to show on a pricing card on the print subscriptions pages when a promotion is applied. Marketing have stated that we should never overstate a discount, even by a fraction of a %, so a saving vs retail of 5.75% should be advertised as 5%, not 6% as it is now. Therefore we always round down to the nearest whole number.
> round print saving vs retail % down

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
SEVERITY 2 BUG
One-Time-Checkout ->
- ApplePay/GooglePay/PayPal amount on PriceCard not reflected in checkout
- StripeExpressCheckout, upon initial load, is defaulting to minimum amount not the PriceCard shown
Therefore, check stripe elements available before enabling stripe express checkout.  
[**Trello Card**](https://trello.com/c/q5Jt80mO/1443-severity-2-medium-bug-report-218-system-impacted-guardian-checkout-supporttheguardiancom-guardian-website)
Checkout via any of three payment methods above without selecting a PriceCard and view amount on checkout screen.
Before
|onetimecheckout|from|to|
|![image](https://github.com/user-attachments/assets/8aa7baed-d650-432d-a6b3-91da1a31af0f)|![image](https://github.com/user-attachments/assets/03c05341-7d6f-4f95-9f4b-20317869fc …
> One-Time-Checkout: check stripe elements available before enabling stripe express checkout

- support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.tsx
- support-frontend/assets/helpers/abTests/abtest.ts
When the user changes their country group, clear any previously persisted A/B test participations. 
[**Trello Card**](https://trello.com/c/yWgx6fqN/1363-ab-test-allocation-issues-session-storage-country)
This is to prevent users being incorrectly attributed to an A/B test variant for a country they were previously in after changing their country code via the dropdown. We considered adding an extra layer to the persisted A/B tests to index by country but decided this was covering such an edge case that it'd be clearer just to delete all their participations.
Visit a page which puts you into a persisted test. See that it appears in session storage:
No visit the 3 tier checkout and change your country group. See that the session storage item has been reset: …
> Remove persisted A/B test participations on country group change

- support-e2e/tests/test/checkout.ts
- support-e2e/tests/utils/testUserDetails.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalDetailsFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- Remove the abtest `ab-confirmEmail`
- Apply the `variant` to Production (confirm email applied)
[**Trello Card**](https://trello.com/c/yyvdWPKo/1418-end-confirm-email-a-b-test-and-keep-variant-with-confirmation-field)
|from|to|
|-----|-----|
|![image](https://github.com/user-attachments/assets/65b62632-c5cd-4f8f-8299-107f3773db0e)|![image](https://github.com/user-attachments/assets/95d9173c-9011-4a1a-abd6-5e24c55234d1)|
> Generic Checkout: Enables confirm email address 

- support-e2e/tests/test/oneTimeCheckout.ts
- support-e2e/tests/utils/testUserDetails.ts
After enabling the [confirmEmail PR](https://github.com/guardian/support-frontend/pull/6784).
- Playwright tests for the `checkout` were correctd.
- This correction was in-advertantly applied to the `one-time-checkout` which, currently, has no `confirmEmail`
Thse tests are failing and requirement modification.
[**Trello Card**](https://trello.com/c/yyvdWPKo/1418-end-confirm-email-a-b-test-and-keep-variant-with-confirmation-field)
`/support-e2e/yarn test-smoke-dev`
`/support-e2e/yarn test-cron-dev`
> Playwright Tests: Confirm email address, not required for the One-Time-Checkout

- support-frontend/assets/helpers/productCatalog.ts
- Support Card benefits should now read `Give to the Guardian every month with Support` 
- Support Card has bullet hidden
- US specific copy and bullet remains unchanged.
- All-Access-Digital remains with `Exclusive newsletter for supporters, sent every week from the Guardian newsroom` benefit
[**Trello Card**](https://trello.com/c/V6mQcUiU/1409-remove-newsletter-benefit-from-tier-1-but-keep-in-s-for-tax-reasons-global-change-excluding-the-us)
|before|after|
|-----|-----|
|![image](https://github.com/user-attachments/assets/679c3485-bf6b-440e-91c5-67c3aab349c5)|![image](https://github.com/user-attachments/assets/60ceb61d-921b-40d5-a264-a016dfcf6c87)|
> Landing Page: Support benefit updated for all regions except US

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/assets/helpers/forms/errorReasons.ts
Stops SignedIn Ad-Free Users from re-purchasing Guardian Ad-Lite 
Different messages dependent on Sign-In status (see CODE screenshot's below)
[**Trello Card**](https://trello.com/c/gauWaokI/1424-on-the-guardian-ad-lite-checkout-check-for-adfree-or-rejecttracking-benefits-and-block-purchase-for-signed-in-users)
1. Login through CODE [MMA](https://profile.code.dev-theguardian.com/signin?) (Ad-Lite or Ad-Free User)
2. Goto Guardian Ad-Lite [Checkout](https://support.code.dev-theguardian.com/uk/checkout?product=GuardianAdLite&ratePlan=Monthly),
3. Checkout (will get error message show below)
4. Sign-Out
5. Repeat Checkout with same email address (just not-signed in)
|Not Signed-In|Sign-In|
|-----|-----|
|![image](https://github.com/user-attachments/assets/5fa60f34-e526-4a71-8526-f6571364cc66) …
> GuardianAdLite: Stop SignedIn Ad-Free Users from re-purchasing Guardian Ad-Lite

- project/LibraryVersions.scala
Update the AWS SDK v2 version.
This pulls in a newer version of io.netty:netty-handler which dependabot has reported a vulnerability for.
Verified that the smoke tests pass on this branch.
> Upgrade the AWS SDK v2 version from 2.29.17 to 2.30.21

- support-frontend/app/controllers/SubscriptionsController.scala
Cheapeast NewPaper Delivery advertised as £33.99.
Change to Staurday (currently) £20.99
[**Trello Card**](https://trello.com/c/WcSwWgt4/1425-update-subscribe-landing-page-to-reflect-cheapest-newspaper-product-wrong-price-atm)
> Subscribe: Landing Page update to Saturday as cheapest paper package

- support-frontend/app/controllers/TestUsersManagement.scala
I noticed that there was a fix in https://github.com/guardian/support-frontend/pull/6556 to make the test users expire after 2 days.
However the [maxAge is defined in seconds](https://www.playframework.com/documentation/3.0.0/api/java/play/core/cookie/encoding/Cookie.html#maxAge()) rather than minutes, meaning that we only actually got 48 minutes of lifetime for the cookie.
This PR changes it so that we calculate the seconds instead of minutes when setting the maxAge.
> update test user expiry to 2 days

- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/paper-subscription-checkout/components/paperCheckoutForm.tsx
- support-frontend/assets/pages/paper-subscription-checkout/components/paperOrderSummary/paperOrderSummary.tsx
- support-frontend/assets/pages/paper-subscription-checkout/helpers/__tests__/deliveryDays.test.ts
- support-frontend/assets/pages/paper-subscription-checkout/helpers/subsCardDays.ts
Looking at the product options defined for newspaper we have a type `ActivePaperProducts` and a list of values `ActivePaperProductTypes`, however these are out of sync with each other.
This PR derives the type from the list so that they will always be in sync.
> Unify ActivePaperProducts and ActivePaperProductTypes

- support-frontend/assets/helpers/utilities/utilities.ts
Fix warning from eslint about the `DOMPurify` import.
Previously eslint was emitting a warning about the default import of `DOMPurify` (which is how the `DOMPurify` docs recommend using this import).
~It looks like we're getting the cjs version of the compiled JS, and this doesn't always play nicely with default imports. See https://www.typescriptlang.org/tsconfig/#esModuleInterop for more details.~ This didn't work (though it did fix the warning in VSCode!). Take the easy route and just rename the default import :-)
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-techno …
> Fix warning from eslint

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
**TODO: Enable the switch in prod before merging** ✅ 
Adding support for a switch around Stripe Express (which powers Apple Pay and Google Pay) on the one time checkout.
[**Trello Card**](https://trello.com/c/lq9WEyx0/1444-one-time-payment-method-switches)
We recently discovered that although a switch exists in the RRCP it isn't respected in the one time checkout. So if we ever wanted to disable Stripe Express for any reason, the switch wouldn't have worked.
Deployed to CODE and toggled the switch in the CODE RRCP. When enabled the Apple Pay button is rendered on the one time checkout. When disabled, the Apple Pay button is not rendered (it takes a moment to take effect due to the polling mechanism on the backend). …
> Put a switch around Stripe Express on the one time checkout

- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/helpers/productPrice/fulfilmentOptions.ts
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/deliveryDates.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/getProductFields.ts
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
This PR makes the generic checkout work for home delivery and subscription card subs. It still will not work for national delivery subscriptions because those require a delivery agent to be selected but that work will follow in a separate PR.
[**Trello Card**](https://trello.com/c/VO1eUa15/1386-newspaper-products-create-payload)
We want to be able to sell newspaper products through the generic checkout so that we can decommission the old subs checkout and unify the codebase.
Go to: 
https://support.thegulocal.com/uk/checkout?product=HomeDelivery&ratePlan=Everyday
or:
https://support.thegulocal.com/uk/checkout?product=SubscriptionCard&ratePlan=Saturday
You should be able to check out successfully.
> Make the generic checkout work for Home Delivery and Subscription Card subscriptions

- support-frontend/assets/helpers/productPrice/fulfilmentOptions.ts
- support-frontend/assets/helpers/productPrice/productOptions.ts
We were seeing errors in prod (via the smoke and cron playwright tests) because no fulfilment options were specified for GuardianAdLite. I've removed the default so that the type system can give us feedback on uncovered cases and done the same for product options. …
> Make fulfilment options switch statement exhaustive

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/posterComponent.tsx
Updates the mobile and desktop breakpoints with hi-res (x4 png) images.
[**Trello Card**](https://trello.com/c/DqsPCOvA/1460-image-change-for-the-landing-page)
|from|to|
|-----|-----|
|<img width="497" alt="image" src="https://github.com/user-attachments/assets/c83862b4-45e0-4007-8769-9dae1eb64833" />|<img width="497" alt="image" src="https://github.com/user-attachments/assets/5b1cf74d-c997-4856-aaf2-53f25f0e69e1" />|
> GuardianAdLite: Add hi-res images for mobile and desktop breakpoints

- support-frontend/package.json
- support-frontend/yarn.lock
Updating @guardian/libs version to latest.
Sending both propertyHref and propertyId to Sourcepoint.
To ensure correct property is selected by Sourcepoint
> Bump @guardian/libs to 21.4.0

- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
re: [oneTimeCheckout PR](https://github.com/guardian/support-frontend/pull/6795/commits/59fdf84b47eae812f7bcdfc8f3799f955e0bcc44) 
ApplePay not checking out in variant as confirmEmail missing. 
> oneTimeCheckout: ApplePay email confirmation  correction

- support-payment-api/src/main/scala/backend/StripeBackend.scala
The payment-api emits a payment-success metric from the StripeBackend. Before, the payment-provider dimension was always hard coded to Stripe. This change makes the payment-provider dimension more granular so we'll send one of:
* Stripe
* StripeApplePay
* StripePaymentRequestButton
Related to:
[**Trello Card**](https://trello.com/c/lq9WEyx0/1444-one-time-payment-method-switches)
The reason I want to do this is to have separate alarms for each of these when we go a period without any successful payments.
I deployed to CODE and made one time contributions with Stripe (card) and Apple Pay, I can see the granular metrics in the Cloudwatch UI:
-  [ ] …
> Make payment-success metric for Stripe more granular

- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/headerCards.tsx
Small horizontal spacing adjustment to Guardian Ad-Lite Landing Page
> Guardian Ad-Lite: Container vertical spacing  adjustment

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
Add alarm for no Stripe Express payments in 1 hour via payment-api.
This alarm uses a composite metric based on the `StripeApplePay` and `StripePaymentRequestButton` metrics. I think it makes sense to combine them as they both handled via Stripe Express, and rolling them both together means we can keep the same time period (1 hour) as for other alarms.
We want to know if Stripe Express is failing in prod.
I tested this in CODE: …
> Add alarm for no Stripe Express payments in 1 hour via payment-api

- support-frontend/assets/helpers/redux/checkout/addressMeta/reducer.ts
- support-frontend/assets/helpers/redux/checkout/addressMeta/state.ts
- support-frontend/assets/helpers/redux/checkout/addressMeta/thunks.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/getDeliveryAgents.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/getProductFields.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx
- support-services/src/main/scala/com/gu/support/paperround/PaperRoundService.scala
We want to make the generic checkout support National Delivery subscriptions. To do this we need to fetch a list of valid delivery agents for users whose postcode is not in our list of 'inside the M25' postcodes.
We also need to send a different `FulfilmentOptions` value through to the back end when creating the sub - `NationalDelivery` rather than `HomeDelivery`.
I've chosen to make this work without changing the productKey query string parameter as this would cause a full page refesh and be a worse user experience. Instead we send a different fulfilment option for postcodes that are outside the M25 and change the product key which is passed through to the thank you page.
> Support National Delivery on the generic checkout

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
This PR prevents users who live outside the M25 from purchasing a home delivery Saturday or Sunday only subscription through the generic checkout.
[**Trello Card**](https://trello.com/c/K7d35lpd/1457-saturday-national-delivery-validation)
This matches existing functionality on the old print checkout. It is not economical for us to fulfil single day subscriptions using PaperRound, hence the restriction.
- Go to the checkout locally with the product set to HomeDelivery and the rate plan set to Saturday:
https://support.thegulocal.com/uk/checkout?product=HomeDelivery&ratePlan=Saturday
- Enter a postcode outside the M25, for example BS19GU, you should see the error message in the screenshot below.
- Change the postcode to one inside the M25, for example N19GU and there should be no error …
> Don't allow Saturday or Sunday rate plans for National Delivery

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
I missed pushing this commit to #6845
It just clears the error message related to single day home delivery plans for postcodes outside the M25 when the postcode is changed.
> Remove postcode error when postcode changes

- support-e2e/tests/smoke/promo-codes.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/test/oneTimeCheckout.ts
- support-e2e/tests/utils/testUserDetails.ts
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalDetailsFields.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalEmailFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- Makes the CONTROL live for this [PR](https://github.com/guardian/support-frontend/pull/6795)
- Remove AbTest
[**Trello Card**](https://trello.com/c/SizWySqG/1476-end-onetimeconfirmemail-a-b-test)
|From|To|
|-----|-----|
|![image](https://github.com/user-attachments/assets/8d3dedc4-714b-4234-ab75-463fa948cc0c)|![image](https://github.com/user-attachments/assets/64373ac6-71f7-40b9-b69a-90c068186fb5)|
> oneTimeCheckout: email confirmation remove (control)

- support-frontend/assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx
A bug was introduced in #6825 which means that all visitors to the newspaper checkout would see an error message until they entered a valid postcode which is outside of the M25:
For customers who live inside the M25 they would continue to see this error message even after entering their valid postcode, however they WOULD still be able to purchase successfully as the validation was working correctly.
This PR fixes that error.
> Don't show National Delivery error for London postcodes

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
Newspaper home delivery should have a 'delivery instructions' field on the checkout so that customers can give us more information about how to delivery their paper successfully.
This PR adds that field to the generic checkout, taking the design from the old newspaper checkout
> Add delivery instructions to generic checkout

- support-e2e/tests/smoke/promo-codes.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/test/oneTimeCheckout.ts
- support-e2e/tests/utils/testUserDetails.ts
This is a further tidy-up to this [PR](https://github.com/guardian/support-frontend/pull/6851)
[**Trello Card**](https://trello.com/c/SizWySqG/1476-end-onetimeconfirmemail-a-b-test)
Refactored `setTestUserConfirmRequiredDetails` + `setTestUserConfirmRequiredDetails` to a single call with optional parameter as shown->
setTestUserDetails -
page: Page,
email: string,
firstName?: string,
lastName?: string,
confirmEmail?: boolean,
)
Where confirmEmail is switch to display/hide the confirmEmail field for checkout/oneTimeCheckout respectively.
> oneTimeCheckout: email confirmation optional field amendment (control) 

- support-frontend/app/controllers/Application.scala
- support-frontend/app/views/router.scala.html
- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx
- support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
This PR sets up a 0% AB test on the newspaper landing page where the variant will send purchasers to the generic checkout rather than the old paper checkout.
1. https://support.thegulocal.com/uk/subscribe/paper#ab-newspaperGenericCheckout=control
2. https://support.thegulocal.com/uk/subscribe/paper#ab-newspaperGenericCheckout=variant
> AB test for selling Newspaper on the generic checkout

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Add alarm for no successful Ad-Lite checkouts in 12 hours
[**Trello Card**](https://trello.com/c/t0bnXb5x/1488-guardian-ad-lite-alarm-setup)
How I tested:
1. Watched the Alarm for Ad-Lite without purchases on Cloudwatch.
2. Made a Ad-Lite purchase on site.
3. See the Alarm state dropping to `ok` on Cloudwatch.
go to AWS cloud watch and check last 12h purchases for the Ad-Lite alarm.
-  [ ] [The …
> Add alarm for no successful Ad-Lite checkouts in 12 hours

- support-lambdas/bigquery-acquisitions-publisher/typescript/acquisitions.ts
- support-lambdas/bigquery-acquisitions-publisher/typescript/schemas.ts
Loosen schema so that payment provider can be undefined in acquisition events.
[**Trello Card**](https://trello.com/c/iQqk6Nrl/1275-migrate-bigquery-acquisitions-publisher-to-typescript)
We've seen this in prod for Feast IAPs.
> Payment provider can be undefined in acquisition events

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/submitButton.tsx
Extract `SubmitButton` component from generic `CheckoutComponent`.
This will be easier to work with as we add a new CTA for Stripe Hosted Checkout.
I've deployed to CODE and run the smoke and cron tests.
-  [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colo …
> Extract `SubmitButton` component from generic `CheckoutComponent`

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/charitableDonationMessage.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/contributionCheckoutFinePrint.tsx
There are 2 components on the generic checkout that need the conditions in which they're rendered updating 
1) The "Guardian Patrons" message and 
2) The "charitable donation" message that sits directly beneath it.
These components are currently conditionally rendered using these rules:
- We hide them both for the Ad-Lite product, eg. https://support.theguardian.com/uk/checkout?product=GuardianAdLite&ratePlan=Monthly
- We hide the "Guardian Patrons" container for all products in the US, eg. https://support.theguardian.com/us/checkout?product=Contribution&ratePlan=Monthly&contribution=5
Both messages are "support" orientated in the messaging, which isn't appropriate for non-Contributions product checkouts, in this PR I'm therefore making the following changes
- Rename `GuardianTsAndCs` to …
> Update conditionals for checkout messages

- support-lambdas/bigquery-acquisitions-publisher/typescript/acquisitions.test.ts
- support-lambdas/bigquery-acquisitions-publisher/typescript/acquisitions.ts
When we migrated the bigquery-acquisitions-publisher lambda in #6787 to TypeScript the `source` field got omitted. This PR adds it back in.
> Include source in fact_acquisition_event rows

- support-frontend/assets/components/orderSummary/orderSummaryTsAndCs.tsx
Displays the following  DEFAULT summary for products that are NOT
-  Contributions
- S+
- TierThree
From (DS for example, )
To
> Checkout : Display default order summary  for non-Tier products

- lighthouserc.json
Bump the resource-summary:document:size threshold (lighthouse metric).
This lighthouse check is failing on every PR merge which is spamming the SR Dev chat channel. 
For now lets increase the threshold slightly so we stop spamming the chat channel.
> Lighthouse: Bump the resource-summary:document:size threshold

- support-workers/src/main/scala/com/gu/stripe/StripeService.scala
- support-workers/src/main/scala/com/gu/stripe/createCustomerFromPaymentMethod.scala
- support-workers/src/main/scala/com/gu/stripe/getPaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
Following on from #6884, rename `StripeServiceForCurrency` to `StripeServiceForAccount` as it isn't really related to the currency any longer.
> Rename StripeServiceForCurrency to StripeServiceForAccount

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
Currently 100% discounts don't work correctly on the generic checkout - the order summary shows the correct price, but the CTA doesn't. This PR fixes that.
- The reason for the issue was a falsy boolean where a zero price is equivalent to no discount. This has been changed to be more explicit
- After the first change, the CTA showed the correct amount but it was no longer possible to checkout out with Stripe, the fields on the form didn't appear:
This is because we pass the amount in to the Stripe Elements component and the minimum amount which it supports is $0.50.
- The fix to this issue is to change the `mode` setting of the Elements component from `payment` to `subscription`. As [the documentation](https://docs.stripe.com/js/elements_object/create_without_intent) says 'The minimum …
> Fix 100% discounts on the generic checkout

- support-frontend/assets/helpers/abTests/__tests__/landingPageAbTests.spec.ts
- support-frontend/assets/helpers/abTests/abtest.ts
- support-frontend/assets/helpers/abTests/landingPageAbTests.ts
- support-frontend/assets/helpers/abTests/mvt.ts
- support-frontend/assets/helpers/page/page.ts
- support-frontend/assets/helpers/redux/utils/setup.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/__tests__/thankYouComponent.test.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/landingPage.tsx
- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
The AB tests [initialisation function](https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/helpers/abTests/abtest.ts#L70) calls `getLandingPageParticipations`, which uses the settings from the landing page tool. If the user is on the landing page, or has a landing page participation in session storage, then it is added here to the set of test participations.
Later, we resolve the test participation to the actual landing page settings using `getLandingPageVariant`, for use in the components. The checkout and thankyou components also need these settings, as they may need the product benefits.
If a user arrives directly onto the checkout (not via the landing page) then the user is not put into a landing page test, and we use the `fallBackLandingPageSelection` …
> Refactor landing page test participations

- support-frontend/assets/pages/[countryGroupId]/__tests__/formDataExtractorsTest.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/__tests__/stripeCheckoutSessionTest.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/formDataExtractors.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripeCheckoutSession.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
For the Stripe hosted checkout flow the checkout process looks like this:
```
+----------------------+     +------------------------+     +----------------------+
| Normal checkout form | --> | Stripe hosted checkout | --> | Back to support site |
+----------------------+     +------------------------+     +----------------------+
```
Validation of form fields etc takes place in the first step, before transferring to Stripe. When the user returns to our site, we don't want them to have to fill in their details again, but these details are needed to submit the create subscription request to support-workers. It's also possible that something may go wrong with the support-workers execution, in which case we'd want to place the user on the checkout form, with an error message, but their form …
> Persist and retrieve persisted form fields on checkout

- support-config/src/main/scala/com/gu/support/config/StripeConfig.scala
- support-frontend/app/utils/CheckoutValidationRules.scala
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/__tests__/stripeCheckoutSessionTest.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripeCheckoutSession.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
- support-frontend/assets/pages/[countryGroupId]/components/paymentFields.ts
- support-frontend/assets/pages/subscriptions-redemption/api.ts
- support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
- support-models/src/main/scala/com/gu/support/workers/PaymentProvider.scala
- support-workers/src/main/scala/com/gu/stripe/StripeService.scala
- support-workers/src/main/scala/com/gu/stripe/retrieveCheckoutSession.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com.gu.config/PaymentConfigSpec.scala
Following on from #6863 and #6891 this PR adds code to connect the stripe hosted checkout to the backend and support-workers.
Now after the user returns from Stripe we can submit a request to the `/subscribe/create` endpoint containing the checkout session ID, which will be used in the support-workers execution to retrieve a setup intent and payment method.
Incrementally working toward the complete Stripe hosted checkout flow for Sunday newspaper subscriptions.
Visit the generic checkout for Sunday HomeDelivery or SubscriptionCard and select Credit/Debit card as the payment method. Use test card details when transferred to Stripe. When you return back to the generic checkout select Credit/Debit card again and submit the form. This will create the support workers execution which should …
> Connect Stripe hosted checkout frontend and backend changes

- support-frontend/assets/components/thankYou/guardianAdLite/whatNext.tsx
- support-frontend/assets/components/thankYou/subscriptionStart/subscriptionStartItems.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/digital-subscriber-thank-you/digitalSubscriptionThankYou.tsx
- support-frontend/assets/pages/weekly-subscription-checkout/helpers/deliveryDays.ts
- support-frontend/stories/checkouts/thankYouModule.stories.tsx
Thankyou component updates ->
- `SubscriptionStartItems` : Currently display's Weekly Start Date not Paper Start Date.
- `whatNext` : tidy to use new call from fix above.
[**Trello Card**](https://trello.com/c/CXqJlXXP/1549-ty-component-subscriptionstart-date-component-fix)
1. Checkout via -> https://support.thegulocal.com/uk/checkout?product=NationalDelivery&ratePlan=Everyday&userType=current
2. Checkout via -> https://support.thegulocal.com/uk/checkout?product=HomelDelivery&ratePlan=Everyday&userType=current
3. Checkout via -> https://support.thegulocal.com/uk/checkout?product=SubscriptionCard&ratePlan=Everyday&userType=current
|before|after|
|----|----|
|![image](https://github.com/user-attachments/assets/4940ef88-a41c-415b-bab4-dcb81da8f4fe)|![image](https://github.com/user-attachments …
> Checkout Thankyou: Subscription Start Component paper date correction

- support-frontend/app/services/StripeCheckoutSessionService.scala
In the StripeCheckoutSessionService switch from using basic auth to specifying a Bearer token.
Compared with using basic auth this is more expected and consistent with how we do auth in other places, including with Stripe.
The Stripe hosted checkout flow continues to work as normal.
-  [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/peop …
> Use Bearer token for auth with Stripe when creating checkout session

- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
re:https://github.com/guardian/support-frontend/pull/6888
Small Signed-In bugfix as shown below->
|before|after|
|---|---|
|![image](https://github.com/user-attachments/assets/6ee57e60-8663-4e95-8788-5624c8dbe234)|![image](https://github.com/user-attachments/assets/69d82114-cf7d-4905-8d02-47ff7219a0ff)|
[**Trello Card**](https://trello.com/c/AglZdDpe/1451-update-ty-page-for-sunday-only)
Via CODE (checked-In), HomeDelivery/Sunday
https://profile.code.dev-theguardian.com/signin?
https://support.code.dev-theguardian.com/uk/checkout?product=HomeDelivery&ratePlan=Sunday
https://support.code.dev-theguardian.com/uk/thank-you?product=HomeDelivery&ratePlan=Sunday&userType=current
> Checkout Thankyou: Subscription feedback hide when Observer signed in

- .github/workflows/playwright-cron.yml
This PR prevents the Playwright cron job from notifying on the SR Dev chat channel. 
This is to stop that channel getting spammed until we can make the tests less flakey.
> Don't notify on Playwright cron failures

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Don't offer PayPal as a payment method on Sunday only subscriptions.
[**Trello Card**](https://trello.com/c/XFEN8o50/1506-remove-paypal-as-payment-method-for-sunday-only)
It removes some complexity if we don't offer PayPal as a payment option for Sunday only.
On Sunday only checkouts, PayPal is not available (this is Sunday / SubscriptionCard):
For all other products, PayPal remains available:
To ensure no existing products are affected, I ran the smoke and cron tests.
> Remove PayPal as payment option from Sunday only subs

- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouFooter.tsx
re: https://github.com/guardian/support-frontend/pull/6888
Hide thankyou page footer copy only for Observer only 
[**Trello Card**](https://trello.com/c/AglZdDpe/1451-update-ty-page-for-sunday-only)
https://support.code.dev-theguardian.com/uk/thank-you?product=HomeDelivery&ratePlan=Sunday&userType=current
> Observer: Checkout Thankyou footer hidden for Observer only

- support-config/src/main/resources/touchpoint.CODE.conf
- support-config/src/main/resources/touchpoint.PROD.conf
- support-config/src/main/scala/com/gu/support/config/StripeConfig.scala
- support-config/src/main/scala/com/gu/support/config/StripePublicConfig.scala
- support-frontend/app/controllers/Application.scala
- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/services/StripeCheckoutSessionService.scala
- support-frontend/app/views/windowGuardianPaymentConfig.scala.html
- support-frontend/assets/components/stripe/contributionsStripe.tsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeProviderForCountry.tsx
- support-frontend/assets/helpers/forms/stripe.ts
- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/paymentRequestButton/state.ts
- support-frontend/assets/helpers/redux/checkout/payment/stripeAccountDetails/reducer.ts
- support-frontend/assets/helpers/redux/checkout/payment/stripeAccountDetails/state.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/oneTimeCheckout.tsx
- support-frontend/assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts
- support-frontend/test/controllers/SubscriptionsTest.scala
- support-models/src/main/scala/com/gu/support/zuora/api/PaymentGateway.scala
- support-workers/src/test/resources/reference.conf
This PR add key config and a new payment gateway for the Tortoise media Stripe account. This is so that we can process payment for Sunday only newspaper sales using their Stripe account not ours.
- Add new Stripe public keys to the touchpoint.conf files which we can then use to look up the secret keys
- Create all the relevant secret keys in config - S3 for support-workers and parameter store for support-frontend
- Add a new payment gateway for the Tortoise media Stripe account
- Use the new config and Stripe account throughout the stack for Sunday only newspaper subscription. Blended subscriptions (those which contain both a Guardian and an Observer element) are unchanged.
[**Trello Card**](https://trello.com/c/P8mvEADx/1507-use-sunday-only-payment-gateway-support-workers)
> Use Tortoise Stripe account for Sunday newspaper payments

- support-frontend/package.json
Add `start` command to project.
Keep consistency between project commands. Also this abstraction will allow us to configure flags if needed in the future.
1. run `pnpm start` from the console
> Add start command to project

- support-frontend/assets/helpers/legal.ts
- support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
Adding a disclaimer for the Sunday only (Observer) on the newspaper page below the package cards.
[**Trello Card**](https://trello.com/c/LGmBdpgX/1437-wording-changes-to-blended-newspaper-product-cards-and-sunday-product-card-add-disclaimer-plus-update-privacy-policy-and-terms-a)
Sunday only (Observer) is sell via Tortoise Media and we need to add their disclaimer info.
Locally by adding the `?enableObserver=true` query param.
eg. https://support.thegulocal.com/uk/subscribe/paper?enableObserver=true …
> Add Observer disclaimer to newspaper packages cards

- support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
This PR adds two new day zero/thank-you email mappings for Sunday only newspaper subscriptions (one for subscription card, one for home delivery - the two supported products on the support site).
[**Trello Card**](https://trello.com/c/kJ77lF1E/1452-trigger-new-day-0-email-for-sunday-only)
Customers taking out Observer only subs should receive separate email comms.
Take out Sunday only sub in code and ensure correct email is received.
> Different email campaigns for Sunday only

- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripeCheckoutSession.ts
Allow persisted `deliveryInstructions` field to be null (saved in session storage before transferring to Stripe and retrieved when the user comes back to the support site).
I noticed that when checking out an Observer subscription with SubscriptionCard that the persisted form details were failing to parse. This was because deliveryInstructions was set to null (it isn't offered on the form) rather than undefined. This small schema change means we're able to de-serialize the persisted json and complete the checkout flow.
-  [ …
> [Stripe hosted checkout] Allow persisted deliveryInstructions field to be null

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Building on #6892, when the user returns from the Stripe hosted checkout with a checkoutSessionId in the query string, we want to immediately submit the checkout form to the server to trigger the support workers request.
To provide a smooth user journey throughout the payment flow.
Go through the Stripe hosted checkout flow for Sunday only. After completing payment details with Stripe, the user is returned to the generic checkout which is immediately in a processing state having automatically submitted the checkout form.
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-te …
> When the user returns from Stripe hosted checkout, immediately submit the checkout form

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
We have a bug on the generic checkout for National Delivery where if a customer's postcode only has one available delivery agent, then that agent will not be set as the chosen agent, meaning it is impossible to complete the checkout.
This is because the code currently relies on the user clicking the checkbox for their chosen provider to set the correct state.
This PR fixes that.
[**Trello Card**](https://trello.com/c/p1Vr9yu6/1568-fix-national-delivery-single-provider-bug)
> FIX: Set chosen delivery agent for postcodes with only one possible agent

- cdk/README.md
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
We have noticed that test users throw an alarm for soft opt ins.  This is because PROD payment api  needs access to CODE soft opt ins queue because that's what test users write to.
There seems to be an automated test running during working hours that triggers this alarm (on paypal)
This was lost (presumably accidentally) during some work on Acquisitions event bus in 2023
https://github.com/guardian/support-frontend/pull/5287/files#diff-b6df073cd69dab873008f8d5446751972fbe3a60543c01dc9a2ccd2a7ababba9L145-L146
https://github.com/guardian/support-frontend/pull/5287
This PR adds the necesssary permission.
> allow PROD to access CODE soft opt ins queue for test users

- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
We have noticed that some failures from Zuora are not being alarmed on. This is because if the FailureHandler doesn't requestInfo.failed = true in it's output JSON the failure will be silent and the alarm will not be triggered.
I think that any TRANSACTION_FAILED message should probably be alarmed on. I'm not sure why most weren't being, there's probably a reason lost in the mists of time somewhere, but let's make sure they are for now and we can take it from there.
[**Trello Card**](https://trello.com/c/zexoCkvb/1574-check-why-dd-support-workers-failures-are-not-alarming)
> Fail on any TRANSACTION_FAILED message from Zuora

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
The `variant` is performing consistently with the `control` so we'd like to send all traffic the `variant`.  This is the fastest way to do this, in a follow-up we'll: 
1. Redirect the old Newspaper checkout URLs to the new Newspaper URLs.
2. Remove the A/B test / set the variant as the default / remove the old Newspaper checkout code
> Push the newspaperGenericCheckout variant live to all users

- support-frontend/assets/helpers/legal.ts
- support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
Change observer terms and privacy links urls and color
[**Trello Card for updating colour**](https://trello.com/c/lCatMwoH/1584-accessibility-change-link-colour-to-white-for-tcs-and-privacy-policy)
[**Trello Card for updating links**](https://trello.com/c/PRmL0dtu/1581-update-the-new-observer-tortoise-media-urls-for-privacy-policy-and-terms-and-conditions-to-their-post-completion-urls)
To match layout specs.
Locally
https://support.thegulocal.com/uk/subscribe/paper?enableObserver=true …
> Change observer terms and privacy links urls and color

- support-frontend/assets/components/directDebit/directDebitForm/directDebitForm.tsx
- support-frontend/assets/components/directDebit/directDebitForm/directDebitFormStyles.ts
- support-frontend/assets/components/directDebit/directDebitForm/directDebitGuarantee.tsx
- support-frontend/assets/components/directDebit/directDebitForm/directDebitGuaranteeStyles.ts
- support-frontend/assets/components/directDebit/directDebitForm/legalNotice.tsx
- support-frontend/assets/components/directDebit/directDebitForm/legalNoticeStyles.ts
- support-frontend/assets/helpers/legal.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Display different copy for the Direct Debit payment option on the checkout for the Sunday only.
Refactored Direct Debit guarantee component and move state management inside the component.
prevent form submission on user click in the direct debit guarantee button 
Direct Debit is not managed by the guardian for the Sunday only.
Go to the checkout page using the following params:
Product  = HomeDelivery
ratePlan  = Sunday 
eg https://support.thegulocal.com/uk/checkout?product=HomeDelivery&ratePlan=Sunday
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physica …
> Direct Debit Legał copy  for Sunday only

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/services/StripeCheckoutSessionService.scala
- support-frontend/test/services/StripeCheckoutSessionServiceSpec.scala
When the user is transferred to the Stripe hosted checkout, provide a back button by specifying a `cancel_url` when creating the Stripe checkout session. We use the referer, after validating that it's a sensible domain and https.
[**Trello Card**](https://trello.com/c/I4Lql8UR/1585-add-back-url-link-to-stripe-hosted-checkout)
It's confusing to transfer the user to Stripe and not give them a route back to the support site.
Visit the generic checkout for HomeDelivery/SubscriptionCard for Sunday only. Fill in the form and select Credit/Debit Card as the payment method and click `Continue to Payment`. After transferring to Stripe, there should be a back CTA at the top right. Clicking this takes you back to the generic checkout with the same product options as before. Note the form itself will …
> Provide a back button on Stripe hosted checkout

- support-models/src/main/scala/com/gu/support/workers/PaymentMethods.scala
- support-models/src/main/scala/com/gu/support/zuora/api/PaymentGateway.scala
- support-models/src/test/scala/com/gu/support/zuora/api/Fixtures.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
- support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
- support-workers/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
- support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
- support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
- support-workers/src/test/scala/com/gu/zuora/ZuoraITSpec.scala
This PR configures support-frontend to use a different Zuora payment gateway for Observer (Sunday only) newspaper subscriptions. 
This is required as we now want to process Observer payments through Tortoise media's Go Cardless account, not GNMs.
~~Because of a difference in the way that GNM and Tortoise Media's Go Cardless accounts are configured, we need to pass an email address in the payment method object for the Tortoise account. This is not needed for our account and may be removed in future if the Tortoise account is updated to match the GNM one.~~ The Tortoise account has now been reconfigured to no longer require an email address so this additional code was removed from this PR.
[**Trello Card**](https://trello.com/c/lrrRQHUb/1551-use-different-gateway-for-gocardless-sunday-subs-i …
> Add Tortoise Direct Debit Payment Gateway

- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
#6927 flipped the alarm behaviour for transaction failed error messages from Zuora so that we would alarm by default and only not do so for particular specified error messages.
This PR follows on from #6931 which added an exception to the alarm exclusion list by adding ~~two~~ three more error messages which it is safe to ignore.
[**Trello Card**](https://trello.com/c/lFopxdf3/1589-add-more-excluded-messages-to-zuora-transaction-failed-alarm)
> Three new transaction declined messages to ignore

- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripeCheckoutSession.ts
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
When the user is checking out with Stripe hosted checkout we store their form fields in session storage (with a 24 hours expiry added by guardian/libs). But once we've retrieved them, submitted the support-workers request and transferred the user to the thank you page we won't ever use these details again. So remove them just before the thank you page (client side) redirect.
Although the form data is stored in session storage (so will be deleted when the browser tab is closed) and is wrapped in a 24 hour expiration applied by guardian/libs, we should proactively delete it if it's no longer needed. …
> Delete persisted form details just before thank you page

- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/utils/userFields.ts
This PR adds PlayWright checkout smoke tests for three scenarios
- A home delivery purchase
- A National delivery purchase where there is only one available delivery provider - in this case the user does not need to take an action to proceed
- A National delivery purchase where there is more than one delivery provider - in this case the user needs to select a provider before proceeding
[**Trello Card**](https://trello.com/c/Xh6K9Gdl/1534-expand-playwrite-tests-for-print-products)
To improve our smoke test coverage so that we can have greater certainty when making changs that no regressions have been introduced.
Get fresh Janus credentials for the membership account
```
cd support-e2e
yarn test-smoke-dev
```
Run these three tests:
> Add PlayWright tests for Home Delivery and National Delivery

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
This PR adds some more transaction declined messages which we don't want to alarm on and also refactors them into a separate object to reduce clutter in the FailureHandler class.
[**Trello Card**](https://trello.com/c/lFopxdf3/1589-add-more-excluded-messages-to-zuora-transaction-failed-alarm)
> Add more transaction declined message to ignore + refactor

- support-frontend/assets/components/directDebit/directDebitForm/directDebitGuarantee.tsx
Prefer string interpolation when using variables in messages.
[**Trello Card**](https://trello.com/c/38YBwQX1/1590-direct-debit-payment-section-direct-debit-guarantee-the-fourth-bullet-down-needs-a-gap-between-by-gc-currently-reads-as-bygc)
No space was being applied between items message and variables.
1. Go to a checkout page (https://support.thegulocal.com/uk/checkout?product=HomeDelivery&ratePlan=Sunday)
2. select Direct Debit as a payment option
3. Click the direct debit guarantee to expand items
4. voilá
-  [ ] [Colour …
> Fix spaces in Direct debit guarantee items

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Adding two new Cloudwatch alarm for going a given period with no Stripe Apple Pay/Google Pay payments for any recurring product.
[**Trello Card**](https://trello.com/c/hPyvKKvX/1582-alarms-to-monitor-payment-methods)
The Stripe Express integration was broken on the generic checkout for a period and this made us realise there wasn't an alarm to pro-actively alert us.
I tested by deploying support-workers in CODE and tested the Apple Pay alarm. Initially it was in an alarm state. Then I put through an Apple Pay transaction (S+) and it changed to OK:
> Add alarms for period with no Stripe Apple Pay/Google Pay payments

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
Including Apple Pay and Google Pay in the combined Guardian Ad Lite alarm.
Previously we didn't include Apple Pay or Google Pay, so the alarm wasn't considering the full picture.
> Include all payment methods in combined AdLite alarm

- support-frontend/assets/pages/paper-subscription-landing/helpers/shouldShowObserver.ts
We need to enable observer on prod environment.
Ready for 22/4/25 go-live.
Note: we can remove the function  `shouldShowObserverCard` & associated `enableObserver` completely in a seperate PR after go-live would suggest. 
[**Trello Card**](https://trello.com/c/7Vu7ZLxa/1593-enable-observer-in-prod)
|from|to|
|-----|-----|
|![image](https://github.com/user-attachments/assets/709f706f-6539-4873-ad3a-3d77b48ddbff)|![image](https://github.com/user-attachments/assets/bb4ff411-fe63-4744-b406-aa01900d960b)|
> Observer:  Landing Page Cards & Checkout enabled in Production

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
Following on from #6956 and others, this adds another card declined error which we don't want to alarm on.
[**Trello Card**](https://trello.com/c/lFopxdf3/1589-add-more-excluded-messages-to-zuora-transaction-failed-alarm)
These types of errors can be addressed by the user, so we don't want additional noise from alarming on them.
> Add new card decline message which we shouldn't alarm on

- support-frontend/assets/components/packshots/guardian-weekly-packshot-hero.tsx
- support-frontend/assets/components/packshots/paper-packshot.tsx
- support-frontend/assets/helpers/images/imageCatalogue.json
Swap observer sale packshot image from the guardian weekly to the newspaper weekly.
Images are incorrect for the product.
> Fix observer image packshot for newsppaper

- support-frontend/assets/components/thankYou/thankyouModules.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
Move away from manual assigning thank you cards in the thank you page, and use css column count instead.
This will scale better and will reduce complexity.
Force page CTA's to sit at the bottom of the page.
[**Trello Card**](https://trello.com/c/Wx8gPstv/1588-thank-you-page-items-alignment-and-cta-links)
1. Go to the thankYou page (eg:  [TierThree for Domestic Monthly](https://support.thegulocal.com/uk/thank-you?product=TierThree&ratePlan=DomesticMonthly))
2. Add the sessionStorage values if you haven't: 
```
sessionStorage.setItem('thankYouOrder', JSON.stringify({"value":{"firstName":"John  Doe","email":"John.doe@theguardian.com","paymentMethod":"DirectDebit","status":"success"}}))
```
3. Change to any valid product/ratePlan Combination to test other scenarios …
> ThankYou page layout fixs

- support-frontend/assets/components/thankYou/thankYouModule.tsx
- support-frontend/assets/components/thankYou/thankyouModules.tsx
Move styles to inner element.
Safari is the new internet explorer and was misbehaving due to bottom margin in the modules.
> Thankyou safari fix

- .github/workflows/playwright-cron.yml
Re-instating playwright cron test failure alerts
The alerting part was commented out a few weeks ago (see #6909) due to flakiness, we think on the PayPal sandbox end. The tests have continued running and it looks like they've been much more reliable recently so let's turn the alerting back on so we find out about any genuine failures.
> Re-instate playwright cron test failure alerts

- .github/workflows/lighthouse.yml
Hide the CMP banner when running lighthouse tests.
[**Trello Card**](https://trello.com/c/pFHFaLRq/1463-disable-cmp-from-lighthouse-tests)
We think loading the CMP banner affects metrics like largest-contentful-paint. This isn't something we can control so we want to remove this variability from our tests. Typically the user will have already interacted with the CMP before hitting the landing page.
> Don't render the CMP banner in lighthouse tests

- support-frontend/app/admin/settings/LandingPageTest.scala
- support-frontend/assets/helpers/campaigns/campaigns.tsx
- support-frontend/assets/helpers/globalsAndSwitches/landingPageSettings.ts
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/tickerContainer.tsx
- support-frontend/test/services/LandingPageTestServiceSpec.scala
This PR has changes to use the tickerSetting from the Landing Page Tests 
The related support-admin -console changes are in the [ SAC PR](https://github.com/guardian/support-admin-console/pull/725) 
[**Trello Card**](https://trello.com/c/Jeyu43yW/1039-landing-page-tool-ticker-config)
This is  to support  Landing Page Tooling 
Test in CODE 
**For US/AU campaign that has a "Money" countType would should show the ticker with the currencySymbol**
**For global  campaign that has a "SupporterCount" countType would just show the total and goal values**
> Changes for getting tickerSettings from landing page tests

- .github/workflows/lighthouse.yml
Reverts guardian/support-frontend#6976
> Revert "Don't render the CMP banner in lighthouse tests"

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
Following on from #6969, #6966 and others, add more Stripe errors to the list we don't want to alarm on.
[**Trello Card**](https://trello.com/c/lFopxdf3/1589-add-more-excluded-messages-to-zuora-transaction-failed-alarm)
These types of errors aren't anything we can do to fix. We should show informative messages to the user to allow them to fix themselves where possible.
> Add another two Stripe errors to the list we don't want to alarm on

- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
I had an unpushed commit when I merged #6957!
Currently we will send similarProductsConsent = false from the client for products which do not have a consent checkbox (Guardian Ad-Lite & Observer). This should actually be undefined; this PR fixes that.
> Pass undefined for similarProductsConsent for products with no checkbox

- support-frontend/assets/helpers/tracking/behaviour.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalDetailsFields.tsx
- support-frontend/assets/pages/[countryGroupId]/components/SimilarProductsConsent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
This PR adds an Ophan component event for when a user checks or unchecks the similar products consent checkbox. It records the new value of the checkbox, ie. when the checkbox is checked and the user clicks to uncheck it a `false` value is sent. 
- Go to the generic checkout making sure that you are in an AB test variant which sees the checkbox eg. https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly#ab-similarProductsConsent=VariantB
- Open the network tab
- Uncheck the similar product consents checkbox
- Check that there is a new request in the network tab similar to: https://ophan.theguardian.com/img/2?viewId=ma2eewtv3cj00qe9yjy2&componentEvent={"component":{"componentType":"ACQUISITIONS_OTHER","id":"similar-products-con …
> Ophan component event for the similar products checkbox

- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/__tests__/benefitsChecklistTest.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/benefitsChecklist.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
This PR refactors the code responsible for creating the benefits checklist on the three tier landing page.
The reason for the refactor is that we are trying to break code out of checkoutComponent.tsx to make it easier to work with. 
The PR also adds a test for the output of the function which loads benefits from the landing page configuration to ensure that nothing was broken in the refactor.
> Refactor benefits checklist logic into a separate file

- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Now that we are explicitly asking users to consent to 'Similar Guardian products' marketing by adding a checkbox to the checkout (see #6957), we need to make sure that we are not showing the checkbox for products where we do not want marketing consent - Guardian Ad-Lite and The Observer.
This PR adds a new boolean named `hideSimilarProductsConsent` onto the `ProductDescription.ratePlan` object in the product catalog. This has to be at the rate plan level rather than the product level because Observer is a rate plan of the home delivery and subscription card products, not a product in its own right.
> Don't show the similar products consent checkbox for some products

- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/pages/[countryGroupId]/components/SimilarProductsConsent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
Update `SimilarProductsConsent` to specify `defaultChecked` instead of `checked`.
Previously the checkbox reverted to a checked state any time the component re-rendered. This way we specify the initial state but let the browser handle the state going forward (this is an uncontrolled component). …
> Use defaultChecked instead of checked prop in `SimilarProductsConsent.tsx`

- cdk/lib/__snapshots__/bigquery-acquisitions-publisher.test.ts.snap
- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
Upgrade the version of CDK we use as far as we can, this is slightly restricted by the latest version of the @guardian/cdk library.
This failed to deploy support-frontend 
https://riffraff.gutools.co.uk/deployment/view/7d6a029c-2fa3-4b10-85dd-065007c00767
& payment-api 
https://riffraff.gutools.co.uk/deployment/view/98cdc537-98b3-4b03-8ff2-0d17f5200b0d
in testing
> Upgrade CDK versions

- support-lambdas/it-test-runner/cfn.yaml
Fixing the support-workers integration tests alarm so that we're notified when integration tests are failing. Since we've been running them less frequently (see #5959) the alarm configuration means we've not been picking up failures.
I've also changed the alarm definitions so they're created in both CODE and PROD (though actions are only enabled in PROD). This makes it easier to test.
[**Trello Card**](https://trello.com/c/bkG3KOja/1255-check-whether-support-integration-tests-are-running)
We want to know when integration tests are failing.
Currently the integration tests are actually failing. So I've deployed the alarm changes to CODE and can now see that the alarm is correctly in an ALARM state:
> Fix integration test alarms

- support-frontend/app/controllers/CreateSubscriptionController.scala
- support-frontend/app/models/FormFieldsHash.scala
- support-frontend/app/services/StripeCheckoutSessionService.scala
- support-models/src/main/scala/com/gu/support/workers/FormFieldsHash.scala
- support-services/src/main/scala/com/gu/aws/AwsCloudWatchMetricSetup.scala
- support-workers/src/main/scala/com/gu/stripe/retrieveCheckoutSession.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
When the checkout session is created store the SHA256 hash of the user entered form fields in the `metadata` field. When retrieving the checkout session in support-workers, compare the hash with the hash of the form fields provided. If they don't match, ~~return an error~~ send a CloudWatch metric event.
[**Trello Card**](https://trello.com/c/88hS6qF5/1571-ensure-that-the-checkout-session-matches-the-form-fields-persisted-hash-these-and-add-the-hash-to-the-checkout-session-metadata)
There's no scenario where the form fields (which we stash in session storage) should change between redirecting the user to Stripe and coming back to the support site to complete the transaction, so let's make sure it doesn't. Before rolling this out in a way which actually prevents a purchase, let's emit a …
> Hosted checkout: verify that user entered form fields match the checkout session

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
We have been adding card declined error messages to our list of errors not to alarm on for a while now. This is the latest one.
> Another card declined error message to ignore

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/helpers/forms/stripe.ts
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/helpers/productPrice/productOptions.ts
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/getProductFields.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/helpers/isSundayOnlyNewspaperSub.test.tsx
- support-frontend/assets/pages/[countryGroupId]/helpers/isSundayOnlyNewspaperSub.ts
- support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.test.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
- support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
- support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx
Utilising `ProductRatePlanKey<P extends ProductKey> ` in support-service-lambdas (which we have as a dependency).
- Setup `ActiveRatePlan` within `ProductCatalog.ts`
- Replace `ratePlanKey : string` with `ratePlanKey : ActiveRatePlan` throughout (props/functions/tests)
[**Trello Card**](https://trello.com/c/Ilhra1GU/1496-activerateplankey-type-add)
This is a No-Op change.
> ActiveRatePlanKey Type Applied

- support-frontend/assets/helpers/globalsAndSwitches/landingPageSettings.ts
- support-frontend/assets/pages/supporter-plus-landing/components/countdown.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
- support-frontend/stories/landingPage/Countdown.stories.tsx
Removes some of the complexity from the landing page countdown logic.
In particular, it removes much of the code from `ThreeTierLanding`, which largely duplicates the checks done inside the `Countdown` component.
- all timestamp parsing/checking happens inside the `Countdown` component
- the state used to decide whether to display the countdown is now inside the `Countdown` component
- a `setHeadingOverride` callback is used to set the heading in the `ThreeTierLanding` component
- the `Countdown` component now takes the same `CountdownSettings` model that RRCP publishes
One advantage is that the storybook stories no longer take a `showCountdown` boolean, and instead decide to render the countdown based on the actual timestamps.
> Simplify countdown

- supporter-product-data/src/main/scala/com/gu/lambdas/ProcessSupporterRatePlanItemLambda.scala
- supporter-product-data/src/main/scala/com/gu/model/zuora/response/MinimalZuoraSubscription.scala
I noticed that there were a lot of errors in the ProcessSupporterRatePlanItem lambda. This is the one which is responsible for syncing subscriptions between Zuora and the SupporterProductData Dynamo store which drives the user benefits api.
This PR fixes an error which is caused by the way we were trying to find out the contribution amount for recurring contribution records - we assumed that there would only be one rate plan on the subscription, and at one point that was true, but now we are using discounts for cancellation saves in MMA, and this means that the subscription will have two rate plans - one for the contribution and one for the discount.
The error was actually caused by trying to deserialise a discount rate plan which doesn't have a price to a case class model which insists …
> Handle discount rate plans when fetching contribution amount in ProcessSupporterProductDataLambda

- support-e2e/tests/cron/checkout.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/utils/userFields.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/deliveryDates.ts
Currently, checkout not going through, looks like not passing in first delivery date (from tier3 setup).
Add Playwright Checkout `Monthly`,`Annual`,`Quarterly` testing cases for 
- CreditCard
1. UK
2. US
3. AU
4. INT
- PayPal (smaller subset for speed)
1. US
2. UK
3. INT
[**Trello Card**](https://trello.com/c/5IUkaPoD/1510-gw-test-generic-vs-old)
From `./support-e2e/` folder ->
`pnpm test smoke-dev`
`pnpm test-cron-dev``
Example paths ->
https://support.thegulocal.com/us/checkout?product=GuardianWeeklyDomestic&ratePlan=Quarterly
https://support.thegulocal.com/int/checkout?product=GuardianWeeklyRestOfWorld&ratePlan=Annual
|before|after|
|----|----|
|![image](https://github.com/user-attachments/assets/a669e875-1ff2-42ea-9f43-4686f9c8d28e)|![image](https://github.com/user-attachments/assets/e …
> Guardian Weekly Checkout: Correct and setup tests

- support-frontend/assets/helpers/tracking/quantumMetric.ts
We have a reduced allowance for the number of user interactions we can record in Quantum Metric. This PR introduces a sampling mechanism for users based on their MVT ID (stored in a cookie for all Guardian users).
Initially we are going to send 50% of the current traffic to QM to see how that affects reports. If everything is still working we will reduce it further to 10%.
[**Trello Card**](https://trello.com/c/RM5I9RgQ/1624-qm-with-the-new-contract-change-we-cant-use-qm-at-the-same-usage-as-before-can-we-instead-use-a-sample-and-see-if-that-is-benefi)
- Go to the checkout https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Monthly
- Set the value of your `GU_mvt_id` cookie to any even number
- Refresh the page and check your network tab, you should see requests to …
> Only send a percentage of traffic to QM

- support-frontend/package.json
- support-frontend/pnpm-lock.yaml
Improves the performance of the ticker animation. This component is used by the landing page.
See https://github.com/guardian/csnx/pull/2089 for details
Checked the ticker still works locally -
> Improve ticker animation

- .github/workflows/playwright-smoke.yml
#7041 broke the playwright smoke test github action because the syntax of the command to install Playwright browsers wasn't correct. This PR fixes that.
> Fix the playwright install step

- .github/workflows/playwright-cron.yml
The syntax for installing Playwright browsers wasn't quite right so fix it. This is the same change made in #7050 but for the cron tests.
> Fix cron e2e tests setup

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Enable `guardianWeeklyGenericCheckout` ab-test, set `control` and `variant` to cover 100% of audience.
Ensure these (non-gifting) GuardianWeekly paths are part of the test->
`.../<countryGroupId>/subscribe/weekly`
`.../<countryGroupId>/subscribe/weekly/checkout`
`.../subscribe/weekly/checkout`
`.../<countryGroupId>/thank-you`
`.../<countryGroupId>/thankyou`
Checkouts->
|control|variant|
|----|----|
|![image](https://github.com/user-attachments/assets/c07f5927-e16b-43a4-bc83-b318b548b290)|![image](https://github.com/user-attachments/assets/0e3ee185-c80e-434e-8bc3-50355988ec64)|
> Guardian Weekly : Generic Checkout AB-Test Enable

- support-frontend/app/services/StripeCheckoutSessionService.scala
- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/checkout/hooks/useStateWithCheckoutSession.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/hooks/useStripeHostedCheckoutSession.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/test/services/StripeCheckoutSessionServiceSpec.scala
If a user returns from the Stripe hosted checkout and receives an error from our backend, clear the form fields and start the checkout process over again.
As part of this I've migrated the checkout session retrieval logic to a custom hook which wraps useState and useEffect. The reason I'm doing this is so that we can manipulate/clear the checkout session state and cause a re-render as expected.
[**Trello Card**](https://trello.com/c/9YD5ZbkO/1647-handle-server-side-errors-when-user-returns-from-stripe-hosted-checkout)
TODO:
When a user returns from the Stripe hosted checkout to the generic checkout we automatically retrieve their form details and submit the form. It's theoretically possible (though we haven't seen it) that we may return an error from our backend at this point. If this …
> Handle errors from our backend after returning from the Stripe hosted checkout

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.test.ts
- cdk/lib/support-workers.ts
The PROD version of the createPaymentMethod lambda needs access to the CODE parameter store values so that it can load config for test users. This PR gives it that access.
> Fix createPaymentMethod lambda access to param store

- support-frontend/assets/helpers/tracking/quantumMetric.ts
Following on from #7037 this PR reduces the proportion of events we send to Quantum Metric to 10%.
[**Trello Card**](https://trello.com/c/WUzy7xfG/1677-reduce-quantum-metrics-sampling-to-10)
We have a reduced allowance so need to fit within this.
> Reduce Quantum Metric sampling to 10%

- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/payment-api.ts
Removing two payment-api alarms which I think are already covered by other alarms with a lower threshold:
`NoPaypalPaymentsInTwoHours247Alarm` is covered by `NoPaypalPaymentsInOneHourAlarm`.
`NoStripePaymentsInThreeHours247Alarm` is covered by `NoStripePaymentsInOneHourAlarm`.
I don't think there's a reason to have these - they all go to the same channel so it'll be the same people looking at these as those with a lower threshold.
> Remove two redundant payment-api alarms

- support-frontend/build.sbt
- support-payment-api/build.sbt
Fixes https://github.com/guardian/support-frontend/security/dependabot/220
commons-beanutils is brought into the project via play-test which is in turn included by the play-framework plugin but we don't use it in any of our tests so I am using an exclusion rule to remove it from the dependency tree.
> Exclude commons-beanutils to fix vulnerability

- pnpm-lock.yaml
- support-frontend/assets/helpers/globalsAndSwitches/window.test.ts
- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/helpers/storage/abandonedBasketCookies.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/sessionStorage.ts
- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/stripeCheckoutSession.ts
- support-frontend/package.json
Currently we have a mix of Valibot and Zod schemas in support-frontend. We have decided to standardise on Zod for now, mostly because it is more of a standard across our code bases (support-service-lambdas uses it extensively for example).
This PR removes Valibot and migrates the schemas which used it to Zod.
> Remove valibot

- support-frontend/assets/helpers/globalsAndSwitches/window.ts
- support-frontend/assets/helpers/productPrice/productOptions.ts
This PR follows on from #7087 and adds full typing for the allProductPrices object on window.guardian - previously this was only quite loosely typed as an object due to some issue with Valibot.
There are a number of new schemas which can be shared with support-workers but I am going to move those to the `modules` folder in a follow up PR because it will be very noisy as I'll also move the types those schemas validate at the same time.
> Full typing for the ProductPricesSchema

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/frontend.ts
- cdk/lib/payment-api.ts
- cdk/package.json
- pnpm-lock.yaml
This upgrade originally happened in #7044. However this caused deploys to fail so it was rolled back (in #7101). Now we're moving forward again using the strategy documented here: https://github.com/guardian/cdk/blob/main/CHANGELOG.md#minor-changes-3
We found that after we reverted #7044 typechecking started failing. We're not 100% sure why but fixing forward seems to get things working.
-  [ ] …
> Move forward with @guardian/cdk 61.8.1 upgrade

- support-workers/src/typescript/lambdas/createPaymentMethodLambda.ts
- support-workers/src/typescript/model/paymentMethod.ts
- support-workers/src/typescript/model/productType.ts
Consider the product when specifying the direct debit (GoCardless) payment gateway.
Since the create payment method lambda was migrated to TypeScript (#7017) we lost some functionality around GoCardless payment gateways. For Sunday paper subs we want to use a different payment gateway.
In the Scala version of this lambda we set the GoCardless payment gateway depending on the product (see #6913 for the original change), so implement the same logic here.
I'd like to follow up with adding some unit tests around this, but to get things moving I'll test in CODE and check the payment gateway in Zuora.
Sunday Paper subs should be created with the correct direct debit payment gateway.
> Use correct GoCardless payment gateway for Sunday paper subs

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/__snapshots__/payment-api.test.ts.snap
- cdk/lib/frontend.ts
- cdk/lib/payment-api.ts
Removing temporary security group added in #7103.
Wazuh is deprecated, and from gu/cdk v61.5.0 the security group is no longer created, but this must [happen in 2 steps](https://github.com/guardian/cdk/blob/main/CHANGELOG.md#6150). So in #7103 we created it, but detached from the ASG. Now it can be removed completely.
Deployed to CODE (payment-api and support-frontend) and everything seems fine.
> Remove temporary Wazuh security group

- support-workers/package.json
- support-workers/src/typescript/lambdas/createPaymentMethodLambda.ts
- support-workers/src/typescript/model/paymentGateway.ts
- support-workers/src/typescript/model/paymentMethod.ts
- support-workers/src/typescript/test/createPaymentMethodLambda.test.ts
Building on top of #7104 add some tests for the lambda handler, specifically testing the thing which #7104 touches (which Direct Debit payment gateway to use).
Build confidence in the code by increasing test coverage, and make it easier to add to these tests in future.
`pnpm --filter support-workers test`
> Add tests for the CreatePaymentMethod lambda handler

- .github/dependabot.yml
- .github/workflows/dependabot.yml
- modules/package.json
- package.json
This PR configures dependabot to run against the root of the pnpm workspace rather than on individual projects. 
This is because the root is now where the pnpm-lock.yml file lives, and should hopefully fix the issue of dependabot PRs not updating the lockfile.
> Make dependabot run against the root pnpm workspace

- support-frontend/assets/components/stripeCardForm/elementDecorator.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/components/paymentFields.ts
- support-frontend/assets/pages/[countryGroupId]/helpers/maybeArrayWrap.ts
When a user selects the Credit/Debit card payment method and submits the form without entering one or more of the required card fields, show specific errors next to the field and scroll to them.
[**Trello Card**](https://trello.com/c/sXWIyRpu/1676-handle-missing-payment-fields-on-the-generic-checkout)
Currently if the user performs the actions above, it's not very clear what's gone wrong. A very generic error message is show below the pay/submit button and we don't make it clear what the user can do to fix things. There's no indication of the actual problem:
Currently this causes an exception which is reported to Sentry. The volumes of this error suggests this situation is actually happening to users.
Now, when this happens we'll show an error message next to the relevant field(s) and …
> Make missing Stripe card payment fields on the checkout more obvious to the user

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
In the checkoutComponent move the `setIsProcessingPayment(false)` call to catch block of the form submit handler because it has the effect of removing the processing overlay. Previously it was below/outside of the catch and this had the effect of removing the overlay even in the case where the submitForm was successful which meant there was a flash of the checkout with no overlap before the redirect to the thank you page. There's no need to remove the overlay unless we're dropping the user back on the checkout with errors in case something went wrong.
Prevent the flash of checkout without overlay when payment is successful before the (client side) redirect to the thank you page.
Put through a transaction and watch the redirect to the thank you page.
> Prevent flash of checkout without overlay before redirect to thank you page

- support-e2e/tests/smoke/ad-lite.test.ts
- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/test/adLiteCheckout.ts
- support-e2e/tests/test/checkout.ts
Extracting Ad-Lite e2e tests out to start from landing page instead of the going directly to the checkout.
This establishes a new pattern where checkout tests start on the landing page for the relevant product. Eventually this will be applied to all the current tests defined in `checkout.test.ts`, which will be grouped by the landing page. I've extracted a method `completeCheckout` which can be used to fill in the checkout and submit. This is shared by the new tests which start on the landing page and the existing checkout tests.
[**Trello Card**](https://trello.com/c/lnE2F0us/1690-update-playwright-e2e-tests-to-begin-checkout-flows-on-the-relevant-landing-page)
We'd like to start tests on the landing page as this is closer to how real users will interact with the site.
> Extract Ad-Lite e2e tests out to start from landing page

- support-frontend/assets/pages/paper-subscription-landing/helpers/getPlans.tsx
- support-frontend/assets/pages/paper-subscription-landing/planData.tsx
update the plans data with the correct active ratePlans for the newspaper products.
Updated the Type to make use of  Typescript `Partial`, so we don't have to maintain  unused ratePlans in the data.
We went live with the Plus ratePlans and the plans data which is not live stayed stale with the old ratePlans. …
> Fix newspaper redesign cards benefits list

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
- support-frontend/assets/pages/[countryGroupId]/student/helpers/getProductContents.ts
Disable back button on the checkout order summary using a query param.
There is no point to having the back navigations because there aren't any other options to choose from on the student page.
> Disable back button for student offer

- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/student/StudentLandingPage.tsx
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentHeader.tsx
- support-frontend/assets/pages/[countryGroupId]/student/helpers/getProductContents.ts
Fetch benefits list rom the pageSettings variant.
For the Benefits list we want to mimic what's being displayed on the Australian  page for the supporter plus Product.
> fetch benefits from the pageSettings variant

- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Fix the vertical alignment within the Direct Debit payment method radio on the generic checkout.
Before:
After:
And on mobile:
[**Trello Card**](https://trello.com/c/xikkkGLc/1715-fix-alignment-of-direct-debit-payment-method-selector)
In #7077 the source library was updated and this brought in a new Direct Debit icon. This new icon slightly broke the alignment of the radio button component. Here we limit the height of the SVG icon by specifying a height for the SVG container.
> Fix issue with new Direct Debit icon vertical alignment

- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/smoke/three-tier.test.ts
- support-e2e/tests/test/adLiteCheckout.ts
- support-e2e/tests/test/checkout.ts
- support-e2e/tests/test/threeTierCheckout.ts
- support-e2e/tests/utils/completeGenericCheckout.ts
Following on from #7126, move the e2e smoke tests for 3 tier products out to a separate test file which start on the 3 tier landing page.
[**Trello Card**](https://trello.com/c/lnE2F0us/1690-update-playwright-e2e-tests-to-begin-checkout-flows-on-the-relevant-landing-page)
This more closely reflects the journey that real users take, and will surface any issues navigating from the landing page to chckout.
Run the new tests via the Playwright UI:
> Three tier product e2e smoke tests start on the three tier landing page

- support-workers/src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
- support-workers/src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
While e2e testing the student Aus offer that the subscription amount was badly formatted in the day zero email:
We were showing: "$.00 every month"
But it should be "$0.00 every month"
This PR makes that change. I've added some tests for zero amounts and verified that the existing tests continue to pass.
[**Trello Card**](https://trello.com/c/sLPngorh/1743-fix-payment-formatting-in-day-zero-email-for-aus-student-offer)
The zero amount looks broken in the email:
Take out the student offer and inspect the email.
In CODE with a zero amount:
and verifying that a non-zero amount is unaffected:
> Fix formatting of zero amounts in day zero email

- support-e2e/tests/smoke/checkout.test.ts
- support-e2e/tests/smoke/newspaper.test.ts
- support-e2e/tests/test/newspaperCheckout.ts
Begin the newspaper checkout smoke tests on the newspaper landing page.
[**Trello Card**](https://trello.com/c/lnE2F0us/1690-update-playwright-e2e-tests-to-begin-checkout-flows-on-the-relevant-landing-page)
This is closer to the real user experience. See also #7134 #7126.
> Begin newspaper e2e smoke tests on the landing page

- .github/workflows/support-workers-build.yml
- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/support-workers.ts
- modules/internationalisation/country.ts
- pnpm-lock.yaml
- support-workers/deploy-to-code.sh
- support-workers/package.json
- support-workers/src/typescript/lambdas/createSalesforceContactLambda.ts
- support-workers/src/typescript/model/address.ts
- support-workers/src/typescript/model/createZuoraSubscriptionState.ts
- support-workers/src/typescript/model/stateSchemas.ts
- support-workers/src/typescript/services/salesforce.ts
- support-workers/src/typescript/services/salesforceClient.ts
- support-workers/src/typescript/test/errorHandler.test.ts
- support-workers/src/typescript/test/fixtures/createSalesforceContact/gwGiftDirectDebit.json
- support-workers/src/typescript/test/fixtures/salesforceFixtures.ts
- support-workers/src/typescript/test/salesforce.it.test.ts
- support-workers/src/typescript/test/salesforce.test.ts
- support-workers/src/typescript/test/salesforceClientIntegration.test.ts
- support-workers/src/typescript/util/errorHandler.ts
This PR follows on from https://github.com/guardian/support-frontend/pull/7017 and is the next step in moving support-workers from Scala to Typescript.
This is a simpler lambda than the CreatePaymentMethod lambda and most of the schemas and model classes were already in place so this PR is smaller than previous ones. 
TODO:
[**Trello Card**](https://trello.com/c/UPZDpNiB/1745-createsalesforcecontact-lambda)
- Deploy this branch of support-workers to CODE
- Run smoke tests against CODE
- All the resulting support-workers executions should succeed
> Migrate the CreateSalesforceContact Lambda to Typescript

- support-frontend/assets/components/orderSummary/orderSummaryTsAndCs.tsx
- support-frontend/assets/helpers/supporterPlus/benefitsThreshold.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
Add Promotion message to the order summary Terms and Conditions.
[**Trello Card**](https://trello.com/c/1kuP0IIQ/1753-newspaper-promos-wording-not-appearing-checkout)
> FIX: add promotion terms and condition for newspaper products

- support-frontend/test/utils/CheckoutValidationRulesTest.scala
- support-models/src/main/scala/com/gu/support/workers/ProductTypeRatePlans.scala
- support-models/src/main/scala/com/gu/support/workers/Products.scala
- support-models/src/test/scala/com/gu/support/workers/SendThankYouEmailStateSerialisationSpec.scala
- support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilder.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/DigitalSubscriptionBuilderSpec.scala
- support-workers/src/typescript/model/productType.ts
I have started to look at using the product catalog throughout the whole support-frontend stack, getting rid of the mapping to the old way of doing things that happens when the form is submitted. 
As preparation for this I am trying to remove any bits of complexity  which are no longer needed, and one of these is the `readerType` field on the DigitalPack product type. This used to be used to differentiate between gift, corporate and regular digital subscriptions, but we no longer sell gift or corporate, so it is just clutter now.
> Remove `readerType` from DigitalPack ProductType

- lighthouserc.json
Update paint metrics using the 99th percentile over 30days from [grafana support site metrics](https://metrics.gutools.co.uk/d/aepxbypfcitxcb/support-site-core-web-vitals?orgId=1&from=now-14d&to=now&timezone=utc&refresh=1d)
- first-contentful-paint metrics  : 4000msecs
- largest-contentful-paint : 10000msecs 
|fcp|lcp|
|----|-----|
|<img width="584" height="303" alt="image" src="https://github.com/user-attachments/assets/541acf5c-eb70-4e48-9b23-6c9de46bd65f" />|<img width="577" height="288" alt="image" src="https://github.com/user-attachments/assets/0c0bd90c-e3c5-49e4-b408-5bb6405648a1" />|
To dampen down the false-positive lighthouse alarms, over this threshold we deem to be genuine.
Later we may develop introduce metric alarms in  [grafana support site …
> Lighthouse: lcp and fcp metrics update from 99th percentile over 30days from grafana

- support-workers/src/typescript/model/stateSchemas.ts
- support-workers/src/typescript/test/salesforce.it.test.ts
#7168 removed the accountExists boolean from the Scala models, but did not remove it from the Typescript one. This caused failures when support-frontend stopped sending this field.
> Remove accountExists boolean from TS requestInfo schema

- pnpm-lock.yaml
This fixes a dependabot vulnerability (see also #7170).
There were two places where 4.0.2 existed in the lockfile (both as dev dependencies, brought in by jsdom):
In support-frontend:
```
devDependencies:
jest-environment-jsdom 29.7.0
└─┬ jsdom 20.0.3
└── form-data 4.0.2
jest-environment-jsdom-global 4.0.0
└─┬ jest-environment-jsdom 29.7.0 peer
└─┬ jsdom 20.0.3
└── form-data 4.0.2
```
In bigquery-acquisitions-publisher:
```
devDependencies:
vitest 3.1.4
└─┬ jsdom 20.0.3 peer
└── form-data 4.0.2
```
In both cases it was being brought in as a transative dependency of jsdom, which species a version range of `^4.0.0`. So the non-vulnerable version 4.0.4 fits this range. Unfortunately using `pnpm update form-data` resulted in lots of unrelated changes so I resorted to updating the lockfile …
> Update form-data NPM package from 4.0.2 to 4.0.4

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
Declutter order summary from the check form.
- Remove orderSummary logic from `checkoutComponent.tsx` into `checkoutSummary.tsx`.
- Rename `checkoutComponent.tsx` to `checkoutForm.tsx`
- import both from `checkout.tsx` module.
The checkout component is doing to much, and following the single responsibility principle they should be diferent components.
-  [ ] …
> split checkout form from summary

- support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
- support-frontend/assets/pages/[countryGroupId]/components/submitButton.tsx
Run form submission on Paypal click in order to mimic the other payment methods error focus.
[**Trello Card**](https://trello.com/c/9FL7KWx9/1714-generic-checkout-clicking-paypal-cta-with-unfilled-personal-details-doesnt-scroll-to-errors) …
> Scroll to Errors for PayPal click

- supporter-product-data/cloudformation/cfn.yaml
Alarms from supporter-product-data still go to the old reader-revenue-dev SNS topic. This send them to the alarms handler instead so we get chat notifications.
The standard in Supporter Revenue is to use the alarms-handler and route to the relevant chat channel.
> Send supporter-product-data alarms to the alarms handler SNS topic

- support-workers/src/typescript/model/productType.ts
Add `deliveryAgent` field to CreateSalesforceContact state. It's an optional field because it's only there for national delivery paper subscriptions (not home delivery or subs card).
We lost this field in the migration from TypeScript to Scala and it means that some national delivery subscriptions haven't been able to be fulfilled. I don't think this field is actually used by the CreateSalesforceContact lambda but it's used by the CreateZuoraSubscription lambda so we need to pass it through.
I've deployed to CODE and taken out a national delivery subscription, and can see this value make to to the CreateZuoraSubscription lambda (and can see it set in Zuora). For non national delivery paper subs the field is set to null which mirrors the old Scala behaviour.
> Add deliveryAgent to CreateSalesforceContact state

- support-e2e/tests/cron/digital-subscription.test.ts
- support-e2e/tests/smoke/digital-subscription.test.ts
An amendment to [Playwright: Digital Subscription Tests PR](https://github.com/guardian/support-frontend/pull/7182)
Orignallly added a US/EU tests to the DigitalEdition product.
Unlike dev, the prod route from the [us/eu subscription landing page](https://support.theguardian.com/us/subscribe) is redirected (via fastly)
Currenty, our test needs to start from [subscription landing page](https://support.theguardian.com/uk/subscribe). Therfore neds to be uk-only dues to fastly redirect setup. 
Think makes sense to :-
1. correct this out initally for cron and smoke tests (this PR).
2. possibly look to not start from the landing page for non-uk digital edition product (future PR)
> Playwright: Digital Subscription Tests - UK-Only

- support-frontend/app/controllers/Promotions.scala
Before this was erroring when the promo code specified in the URL path was for a newspaper product. The reverse route lookup was failing, I think because uk/subscribe/paper is not a geo aware path, it only exists for uk.
I've tested locally and now visiting `/p/<promo code>` redirects to `/uk/subscribe/paper?promoCode=<promo code>`, which I think is the expected behaviour.
We noticed this issue as we had a spike of 500s for this endpoint.
I've tested locally by visiting the endpoint with a newspaper promo code in the path.
> Fix `/p/<promo code>` endpoint

- support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/components/form.tsx
- support-frontend/assets/components/directDebit/directDebitProgressiveDisclosure/components/playback.tsx
- support-frontend/assets/components/footerCompliant/Footer.tsx
- support-frontend/assets/components/paymentButton/defaultPaymentButton.tsx
- support-frontend/assets/components/product/productOption.tsx
- support-frontend/assets/components/subscriptionCheckouts/address/postcodeFinder.tsx
- support-frontend/assets/components/subscriptionCheckouts/personalDetails.tsx
- support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.tsx
- support-frontend/assets/components/subscriptionCheckouts/thankYou/returnSection.tsx
- support-frontend/assets/components/test-user-banner/thankYouUserTypeSelector.tsx
- support-frontend/assets/pages/[countryGroupId]/guardianAdLiteLanding/components/guardianAdLiteCard.tsx
- support-frontend/assets/pages/aus-moment-map/components/header.tsx
- support-frontend/assets/pages/aus-moment-map/components/testimonialsContainer.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/content/PaperHero.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/amountsCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.tsx
Migrating away from `ThemeProvider`, passing the theme directly to the relevant source component.
[**Trello Card**](https://trello.com/c/GDnEbUWn/1709-move-away-from-themeprovider-for-source-components)
Using `ThemeProvider` with source components is deprecated.
Chromatic is happy. Manually inspecting revealed one small diff, which I've left a comment for.
> Migrate away from deprecated ThemeProvider

- support-workers/src/main/scala/com/gu/zuora/subscriptionBuilders/PaperSubscriptionBuilder.scala
- support-workers/src/test/scala/com/gu/zuora/subscriptionBuilders/PaperSubscriptionBuilderSpec.scala
We have had two incidents over the last month or two; in the first Observer subscriptions were being created with the wrong payment gateway and in the second National Delivery subscriptions were created with no delivery agent id set, meaning that their papers could not be delivered successfully.
In both cases we should have prevented creation of these subs and triggered an alarm to alert us to the invalid state. This is what this PR puts in place.
> Improved validation for Paper subscriptions in support-workers

- support-frontend/assets/pages/[countryGroupId]/checkout/components/PersonalEmailFields.tsx
Add a short delay before checking the validity of the email confirmation field.
When using browser auto-fill we sometimes see the validity check for the email confirmation field being equal to the email field fail (seems to be Firefox specific). I think this is happening because the state hasn't updated by the time we trigger the check on blur. Delaying this slightly seems to fix the issue. It isn't super elegant but I'm not sure of a better way to handle this.
Previously it was possible to end up in situations like this:
Use browser autofill and verify that the email confirmation confirmation field has no unexpected errors.
More generally run the smoke tests to ensure no regressions.
> Prevent invalid email confirmation validation error when using autofill

- support-frontend/assets/pages/[countryGroupId]/components/submitButton.tsx
Working on functionality to scroll to form fields with errors when attempting to click the PayPal submit button on the generic checkout.
In #7173 a change was made to programatically submit the checkout form in the validate callback in order to get the form validation to kick in and scroll the user to the relevant form field errors. It looks like this had an unintended side effect of actually submitting to the backend in the case that the fields were all valid. However since the user hasn't yet auth'd with PayPal there's no BAID so the backend correctly rejects the request. This PR changes things to only scroll to the errors on attempting to submit the form, and only if we know that there are errors.
* Leave one or more required form fields blank on the generic checkout (e.g. email, name) …
> Fix unintended submission of PayPal checkout without BAID

- support-frontend/assets/pages/[countryGroupId]/router.tsx
- support-frontend/assets/pages/[countryGroupId]/student/StudentLandingPage.test.tsx
- support-frontend/assets/pages/[countryGroupId]/student/StudentLandingPage.tsx
- support-frontend/conf/routes
This pr enables `uk`, `us`, and `ca` country ids to list of  available countries that render student landing page.
Add country Switcher to global student page.
[**Trello Card**](https://trello.com/c/C7yTVxHV/1796-global-student-page-enable-routing)
Beginning of development for the global student page.
Go any any of the urls:
- https://support.thegulocal.com/uk/student
- https://support.thegulocal.com/ca/student
- https://support.thegulocal.com/us/student
Any other regions should 404 eg: 
- https://support.thegulocal.com/eu/student
-  [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyb …
> Enable routing for global student page

- support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
Updating wording at Tortoise Media's request about what Observer subscribers get access to
One of several [requests](https://docs.google.com/document/d/1TPhNbmvF-8CIKUWMzMEOx52HM9r5ODeW4yO_z5qRoHc/edit?tab=t.0) from Tortoise Media.
Before:
Home Delivery:
Subs card:
After:
Home Delivery:
Subs card:
> Updating wording about what Observer subscribers get access to

- support-frontend/app/controllers/Application.scala
- support-frontend/assets/helpers/globalsAndSwitches/window.ts
To be able to present correct pricing and promotion information for Guardian Weekly gifts on the generic checkout we need to add product prices to the window.guardian.allProductPrices object.
This PR does that by adding a new top level object with allProductPrices named `GuardianWeeklyGift`. This is a slight hack because previously all the other top level objects were valid product types whereas this is just a variation on Guardian Weekly, but it is by far the most straightforward way to get the information to the page and this area is likely to be reworked quite soon to use the product catalog instead.
_The new object:_
> Add GuardianWeeklyGift product prices to allProductPrices object

- support-frontend/assets/pages/supporter-plus-landing/components/studentOffer.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
This PR adds a new section to the 3 tier landing page, under the `Support us just once` section, with a link to the student offer landing page. It's only ever displayed in uk, us and ca, and currently a query string arg is needed to show it at all (we don't want it to be visible in prod yet).
[**Trello Card**](https://trello.com/c/o2O49aP9/1769-tier3-landing-page-add-student-link-container)
Signposting the new student offer.
Visit the 3 tier landing page with a region code of `uk`, `us` or `ca` and add `enableStudentOffer` as a query string arg (no value needed).
> Add Student Offer link to 3 Tier landing page

- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
Suppressing a specific card declined message from Zuora.
We don't want this to trigger an alarm because this isn't something we can address.
> Suppress this card declined message from Zuora

- support-frontend/app/services/LandingPageTestService.scala
We noticed that the support-frontend logs are full of logging related to epic tests which are running on the site. This is very noisy as these tests contain a lot of information and are refeshed every minute. 
This PR changes the logging so that we will only log if there is a failure, not on success.
> Removing the noisy logging when we retrieve epic tests

- support-frontend/assets/pages/[countryGroupId]/student/components/StudentHeader.tsx
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentHeaderStyles.tsx
- support-frontend/assets/pages/[countryGroupId]/student/components/StudentLandingPageGlobal.tsx
Add toggleable "Not a student?" signposting to the landing page with a link to the 3 tier landing page.
Note: This is controllable with a prop on the `StudentHeader` component which defaults to `false`. After #7224 is merged we can override this by passing `true` from the global student landing page component.
[**Trello Card**](https://trello.com/c/Tvk2HjkK/1801-global-student-page-create-not-a-student-return-link)
To give users an onwards journey from the student landing page if the student offer isn't for them.
> Add toggleable "Not a student?" signposting to landing page

- pnpm-lock.yaml
- pnpm-workspace.yaml
- support-workers/jest.config.js
- support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
- support-workers/src/typescript/errors/errorHandler.ts
- support-workers/src/typescript/errors/retryError.ts
- support-workers/src/typescript/errors/zuoraErrors.ts
- support-workers/src/typescript/lambdas/createPaymentMethodLambda.ts
- support-workers/src/typescript/lambdas/createSalesforceContactLambda.ts
- support-workers/src/typescript/lambdas/createZuoraSubscriptionTSLambda.ts
- support-workers/src/typescript/test/createPaymentMethodLambda.test.ts
- support-workers/src/typescript/test/createZuoraSubscriptionLambda.it.test.ts
- support-workers/src/typescript/test/errorHandler.test.ts
- support-workers/src/typescript/test/fixtures/createZuoraSubscription/transactionDeclinedInput.json
- support-workers/src/typescript/test/getZuoraPaymentMethod.test.ts
- support-workers/src/typescript/test/salesforce.it.test.ts
- support-workers/src/typescript/test/test-setup.ts
This PR follows on from #7230 and is the next step in the work to move the CreateZuoraSubscription lambda in the support-workers step function to a new Typescript implementation. The benefits of this are:
- Migrating from Scala to Typescript is a strategic goal for us to increase our ability to find developers to work on our codebase
- Moving from Zuora's deprecated subscribe and amend API to their newer Orders API
- Start using the product catalog to define which subscriptions we create rather than the old deprecated model
Specifically in this PR we add the error handling to the CreateZuoraSubscription Typescript lambda to match the Scala version.
Note that at this stage there is still no traffic going to the new lambda, it is all being routed to the old one as described in this PR …
> Error handling for CreateZuoraSubscription lambda

- support-frontend/assets/pages/paper-subscription-landing/components/NewspaperProductTabs.tsx
Updating the new newspaper plus landing page to make Collection the default fulfillment tab, not HomeDelivery.
[**Trello Card**](https://trello.com/c/SyLWVrA6/1862-print-design-feedback-on-landing-page)
Design feedback. Current default of HomeDelivery does not match what's in Figma.
Visit the new landing page and see that the Collection tab is selected by default.
> On the new newspaper plus landing page, collection should be the default tab

- support-frontend/assets/pages/[countryGroupId]/checkout/helpers/benefitsChecklist.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
- support-frontend/assets/pages/paper-subscription-landing/components/NewspaperRatePlanCard.tsx
- support-frontend/assets/pages/paper-subscription-landing/planData.tsx
Update the description copy shown on the product cards on the new paper plus landing page. Note: this description is only shown at mobile width.
[**Trello Card**](https://trello.com/c/SyLWVrA6/1862-print-design-feedback-on-landing-page)
The copy is out of date vs the Figma. The copy was not varied between home delivery and collection but it needs to, some refactoring was required to support this.
Visit the new paper plus landing page at mobile width. Toggle between collection and home delivery to see the description copy.
Just as an example, here's how six day now looks for collection and home delivery:
> Newspaper Plus landing page card description copy

- support-frontend/assets/helpers/utilities/__tests__/parseCustomAmounts.test.ts
- support-frontend/assets/helpers/utilities/utilities.ts
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.test.tsx
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
This PR adds support for custom contribution amounts via URL query parameters for one-time contributions. When the `amounts` URL parameter is provided (e.g., `?amounts=15,30,75`), it overrides the default A/B test variant amounts with the custom values specified by the marketing team.
The feature includes:
- A new `parseCustomAmounts` utility function that safely parses comma-separated amount strings
- URL parameter processing in `OneTimeCheckoutComponent` to extract and apply custom amounts
- Robust input validation that filters out invalid values (NaN, negative, zero, infinite)
- Deduplication of amount values
- Comprehensive test coverage for both the utility function and component integration
**Trello Card**: [Custom top-up amounts for one-time …
> Custom top up amounts for one time off contributions

- support-frontend/app/actions/CustomActionBuilders.scala
- support-frontend/app/wiring/ActionBuilders.scala
- support-frontend/test/actions/ActionRefinerTest.scala
- support-frontend/test/controllers/ApplicationTest.scala
- support-frontend/test/controllers/SiteMapTest.scala
- support-frontend/test/fixtures/DisplayFormMocks.scala
When the current user is a test user, emit the `ServerSideCreateFailure` metric with a stage of CODE rather than PROD. 
[**Trello Card**](https://trello.com/c/0FJuz17y/1857-dont-trigger-support-frontend-create-recurring-product-call-failed-alarm-for-test-users)
This change means the prod alarm won't be triggered by test users which is the behaviour we want. In prod test users use CODE APIs. We don't want a CODE API call failing to trigger this alarm.
I've verified this change by breaking one of the server side API calls (delivery coverage) to trigger the `ServerSideCreateFailure` to be emitted. In CODE a stage of CODE is used in both cases. In Dev when you're a test user a stage of CODE is user, when not a test user a stage of DEV is used. This shows that the distinction between test …
> Don't trigger the create recurring product fail alarm for test users in prod

- support-frontend/assets/pages/paper-subscription-landing/components/NewspaperProductTabs.tsx
On the new print+ landing page, only add the tab anchor parameter to the URL when the user actively selects a tab, not by default when the page loads.
Previously when `windowSetHashProperty` was called from the `useEffect` this ran whenver the tab was changed but also on the initial render. This had the effect of adding and scrolling to the tab section whenever the user lands on the page. Instead, do this when a user actively selects a tab.
Navigate to the print+ landing page. The browser should not scroll to the tab section by default. When selecting a different tab, the anchor is added to the URL.
https://github.com/user-attachments/assets/f37a4e4c-ee2e-4e67-ab8d-f06ca0d15829
> Only add tab anchor to URL when the user selects a tab

- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/frontend.ts
Add SSM param (via CDK) containing the ALB ARN for support-frontend.
This is used by https://github.com/guardian/waf, which we'd like to enable, initially in CODE.
> Add SSM param containing ALB ARN for support-frontend

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/frontend.test.ts.snap
- cdk/lib/frontend.test.ts
- cdk/lib/frontend.ts
Enabling access logs from the Application Load Balancer for support-frontend (only CODE for now).
This depends on work done in guardian/aws-account-setup#414 which will ensure these logs go to the right bucket with the correct retention policy, access etc.
Combined with the PR mentioned above, this will unlock better insights into issues and usage by enabling querying access logs with Athena.
Deploy to CODE and inspect access logs. Ensure there are no issues.
> Enable ALB access logs for support-frontend (CODE only)

- support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.test.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.tsx
- support-frontend/stories/checkouts/SummaryTsAndCs.stories.tsx
SummaryTsAndCs appears to be displaying Paper copy for all products since the `inPaperProducts` switch went live yesterday.
Old: https://support.theguardian.com/uk/checkout?product=SupporterPlus&ratePlan=Annual
vs
New: https://support.thegulocal.com/uk/checkout?product=SupporterPlus&ratePlan=Annual
|old|new|
|----|----|
|<img width="695" height="555" alt="image" src="https://github.com/user-attachments/assets/7a17cc48-ea1f-4527-9612-e095c7c4b94d" />|<img width="695" height="555" alt="image" src="https://github.com/user-attachments/assets/81bbab8d-8746-45ef-b491-70d9f4d57a9c" />|
> NewPaper Plus Digital: SummaryTsAndCs Paper Copy Fix

- support-frontend/assets/pages/[countryGroupId]/student/helpers/studentFAQs.tsx
Tiny copy change to add fullstops to the end of a couple of FAQs on the student landing page.
[**Trello Card**](https://trello.com/c/KBVBDOPm/1896-missing-in-the-faqs-on-student-page)
Spotted during e2e testing.
> Add missing fullstops to FAQ copy

- pnpm-lock.yaml
- pnpm-workspace.yaml
- support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.tsx
- support-frontend/assets/components/headers/links/links.tsx
- support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
- support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
- support-frontend/assets/helpers/internationalisation/Readme.md
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/helpers/productPrice/__tests__/productPricesTests.ts
- support-frontend/assets/helpers/subscriptionsForms/submit.ts
- support-frontend/assets/helpers/urls/externalLinks.ts
- support-frontend/assets/helpers/urls/routes.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
- support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
- support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/studentOffer.tsx
- support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
- support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
https://github.com/guardian/support-service-lambdas/pull/3072 renamed the `SupportInternationalisationId` type to `SupportRegionId` for the following reasons:
- It makes more sense to talk about a support region than a 'support internationalisation'
- It is more concise - quite a lot shorter to type
- There is no spelling ambiguity (internationalization vs internationalisation)
This PR updates support-frontend to use the renamed type.
Next step after this is to remove the `GeoId` type which is an exact duplicate of SupportRegionId.
> Rename `SupportInternationalisationId` to `SupportRegionId`

- cdk/lib/__snapshots__/support-workers.test.ts.snap
- cdk/lib/frontend.ts
- cdk/lib/support-workers.ts
Enabling OK actions for product acquisition Cloudwatch alarms.
These are the alarms which are of the format "No successful x in y hours" which we have for most product/payment method combinations. Usually if one goes off the first thing to check is whether it's back to OK already (for example if we see one of these overnight or over the weekend). This will surface that information in the alarms channel.
Hard to test in CODE because actions aren't enabled. Once this is out I'll manually trigger the alarm (and then put it back to OK). We should see both of these show up in the alarms channel.
Reduced time spent investigating these alarms.
> Enable OK actions for product acquisition alarms

- support-workers/src/typescript/services/salesforce.ts
- support-workers/src/typescript/test/salesforce.test.ts
Fix a bug introduced in #7302. Billing address fields for digital only subscriptions should be saved to relevant Salesforce contacts created or updated during the acquisition process. #7302 introduced a bug which stopped this from happening. 
_Address fields not being saved:_
_Should be:_
Note the data was still saved to Zuora as expected.
[**Trello Card**](https://trello.com/c/dFGa0J5v/636-fix-ensure-billing-country-fields-are-written-to-salesforce-on-digital-only-acquisition)
It is important that Billing address fields in Salesforce match those in Zuora, so that our CSRs have accurate information for resolving customer issues.
Billing address fields were only being saved to Salesforce when there was no associated gift recipient and there were delivery details provided from the user …
> Fix missing billing country on digital only subs

- support-frontend/app/services/pricing/PriceSummary.scala
- support-frontend/app/services/pricing/PriceSummaryService.scala
- support-frontend/assets/helpers/productPrice/productPrices.test.ts
- support-frontend/assets/pages/paper-subscription-landing/helpers/getPlans.tsx
- support-models/src/main/scala/com/gu/support/catalog/Catalog.scala
- support-models/src/main/scala/com/gu/support/catalog/Pricelist.scala
On the newspaper landing page, we show the discount amount given by promotions as the discount vs the _retail_ price of the newspaper (not the subscription price it sells for on the website). 
This is different to all other products and we work it out by taking the savings vs retail amount stored in Zuora and doing a calculation with the discount amount. Unfortunately until now this calculation has not been completely accurate as we were storing a rounded amount for the saving value. 
This PR changes that so that we store the full fractional amount of the saving in Zuora, meaning that the 'discount vs retail' amount is correct. This also means that we need to round down the amount before we display it to end users.
[**Trello Card**](https://trello.com/c/w8qXiXpB/1921-fix-discount-vs-retail …
> Support fractional savings vs retail amounts

- support-frontend/assets/helpers/abTests/abtestDefinitions.ts
- support-frontend/assets/helpers/featureFlags.ts
- support-frontend/assets/helpers/productCatalog.ts
- support-frontend/assets/helpers/productPrice/billingPeriods.ts
- support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
- support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
- support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Remove ab test definition for the `newspaperArchiveBenefit` and use a url  based feature flag to control the functionality.
[**Trello Card**](https://trello.com/c/fYIcX0Dk/1918-setup-feature-flag-remove-abtest-newspaperarchivebenefit)
Since newspaper archive benefit will be part of the new Premium digital product, we need a way to control all related features.
1. visit `https://support.thegulocal.com/uk/contribute`
2. add `?enablePremiumDigital` to the url …
> PremiumDigital: Remove Ab test and create feature flag

- support-frontend/conf/CODE.public.conf
- support-frontend/conf/DEV.public.conf
- support-frontend/conf/PROD.public.conf
As part of the support onboarding journey we want to encourage users to register or sign in after they have made a purchase. 
To do this we want to iframe in the signin journey into the thankyou page. 
We need to add profile.theguardian.com (more specifically the correct profile domains for the particular stage that support and profile are running on) into the default-src CSP directive to allow iframing from the correct domain.
> Adding profile.theguardian to the default-src csp directive to allow us 

- support-payment-api/build.sbt
- support-payment-api/src/main/scala/MyApplicationLoader.scala
- support-payment-api/src/main/scala/aws/AWSClientBuilder.scala
- support-payment-api/src/main/scala/backend/PaypalBackend.scala
- support-payment-api/src/main/scala/backend/StripeBackend.scala
- support-payment-api/src/main/scala/services/SwitchService.scala
- support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
Follows on from https://github.com/guardian/support-frontend/pull/7336 This PR upgrades S3 to the V2 SDK in payment-api
[**Trello Card**](https://trello.com/c/gVQ076wZ/1859-migrate-remaining-aws-sdk-v1-libraries-in-support-frontend-to-v2)
> Upgrade S3 to v2 in payment-api

- support-payment-api/build.sbt
- support-payment-api/src/main/scala/aws/AWSClientBuilder.scala
- support-payment-api/src/main/scala/backend/StripeBackend.scala
- support-payment-api/src/main/scala/services/ContributionsStoreService.scala
- support-payment-api/src/main/scala/services/EmailService.scala
- support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
- support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
- support-payment-api/src/test/scala/services/EmailServiceSpec.scala
Follows on from #7337 this PR upgrades the AWS SQS SDK to version 2
[**Trello Card**](https://trello.com/c/gVQ076wZ/1859-migrate-remaining-aws-sdk-v1-libraries-in-support-frontend-to-v2)
> Upgrade SQS to v2 in payment-api

- support-frontend/assets/components/thankYou/newspaperArchive/newspaperArchiveImage.tsx
- support-frontend/assets/components/thankYou/thankYouModule.tsx
- support-frontend/assets/components/thankYou/thankYouModuleData.tsx
- support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
A few changes on for the newspaper archive thank you module:
- change order to last position
- update copy
- Fix bleeding images in leftCol screen size
[**Trello Card**](https://trello.com/c/fuqLTW5B/1916-thankyou-display-newspaper-archive-component)
Newspaper Archive benefit is part of the Premium Digital product 
1. go to a [DigitalSubscription Thank You page](https://support.thegulocal.com/uk/thank-you?product=DigitalSubscription&ratePlan=Monthly&enablePremiumDigital)
2. open the console and run the following command.
```
sessionStorage.setItem('thankYouOrder', JSON.stringify({"value":{"firstName":"John","email":"testing@theguardian.com","paymentMethod":"DirectDebit","status":"success"}}))
```
3. Refresh the page …
> Premium Digital: Newspaper archive ThankYou module  updates

- support-frontend/conf/fastly-snippets/observerarchive-redirect-recv.vcl
Adding /favicon.ico to the list of exclusions to the Observer Archive redirect.
https://trello.com/c/VpzTq7pQ/1941-move-observertheguardiancom-domain-from-the-www-fastly-service-to-the-support-fastly-service
Because the favicon should display rather than redirect.
> Adding /favicon.ico to the list of exclusions to the Observer Archive redirect

- support-frontend/assets/pages/[countryGroupId]/checkout.tsx
The recurring contribution checkout requires a contribution amount, e.g.
`/checkout?product=Contribution&ratePlan=Monthly&contribution=4`
If the `contribution` param isn't supplied then there's an error -
We want to link direct to checkout from the choice cards (in epic + banner). Currently the DCR page doesn't know about the contribution amount. We always use the amount from the product catalog, so we can just fall back on this value if the url doesn't specify an amount.
This PR makes it possible to visit e.g.
`/checkout?product=Contribution&ratePlan=Monthly`
and it will choose the contribution amount from the product catalog instead of showing an error.
> Make contribution amount optional on checkout
