.github/PULL_REQUEST_TEMPLATE.md
To improve the quality of our PRs. PRs are documentation for future contributors.
- Added a PR template for Github.
=> Add A Pull Request Template

README.md
First instructions about how to run the server in `DEV` mode.
[**Trello Card**](https://trello.com/c/MzjBfSvj/468-update-readme)
* Update the README.md
=> Added the first version of the README.

app/wiring/AppComponents.scala, app/wiring/AppLoader.scala, app/wiring/PlayComponents.scala, conf/application.conf
Based on Guardian recommendations (https://github.com/guardian/recommendations/blob/master/scala.md)
=> Replace run-time dependency injection with explicit wiring

app/wiring/AppComponents.scala, conf/routes
To fix the build
* Re-order controllers
* Tidy routes whitespace
=> Re-order controllers because routes order changed.

README.md, package.json
Refactoring the npm scripts. 
[**Trello Card**](https://trello.com/c/SCGBA8PY/474-update-npm-scripts)
* Deleted `precommit` command
* Deleted `lint` step from dev run
* Added `lint` and `test` steps into `build-prod` command.
* Updated the `README.mk`
=> Updated npm scripts.

app/assets/AssetsResolver.scala, app/controllers/Application.scala, app/views/bundlesLanding.scala.html, app/views/index.scala.html, app/wiring/AppComponents.scala, build.sbt, package.json, test/controllers/ApplicationTest.scala, webpack.config.js
So that we can more aggressively cache JS assets
[**Trello Card**](https://trello.com/c/32Fj8QEk/476-sort-out-caching-and-asset-hashing-for-support-frontend)
=> Hash JS assets

LICENSE
Since we are an open source project we need a LICENSE file. 
[**Trello Card**](https://trello.com/c/x0BTsiBq/498-add-license)
* Add LICENSE file
If in the future we add the fonts to the project, we have to update this LICENSE to include them.
=> Added license file.

assets/components/footers/simpleFooter/simpleFooter.jsx, assets/components/footers/simpleFooter/simpleFooter.scss, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/bundles-landing/bundlesLanding.scss, assets/stylesheets/main.scss
This PR add the dummy component SimpleFooter. This component is implemented as a shared component using only react since it has no interaction.
[**Trello Card**](https://trello.com/c/Ua2RhelN/515-footer-of-the-bundle-landing-page)
* Created the simple footer.
* Added the simple footer to the bundle landing page.
=> Simple footer

assets/components/bodyCopy/bodyCopy.jsx, assets/components/bodyCopy/bodyCopy.scss, assets/components/svg/svg.jsx, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/bundles-landing/bundlesLanding.scss, assets/pages/bundles-landing/components/WhySupport.jsx, assets/stylesheets/main.scss
Adding the "Why do we need your support?" section to the bundles landing page.
[**Trello Card**](https://trello.com/c/h98O74Hh/529-why-support)
- Added a `BodyCopy` component for paragraphs.
- Added a video svg.
- Added a `WhySupport` component to the bundles landing page, and styled it.
No images or video yet!
**Narrow:**
**Medium:**
**Wide:**
=> Bundles Landing - Why Support

assets/pages/bundles-landing/bundlesLanding.scss, assets/pages/bundles-landing/components/WaysOfSupport.jsx
Copy fix and CSS fix.
[**Trello Card**](https://trello.com/c/pgO4KZyO/546-the-grauniad) and [another](https://trello.com/c/2YOLx1uI/538-oh-dear-patrons-cta-css-bug).
* Fix a typo in the Patron box.
* Fix CSS bug.
=> Become patron box

app/lib/CustomHttpErrorHandler.scala, build.sbt, project/plugins.sbt
Make code automatically more consistent, so that PR reviews don't need to speed time on formatting
=> Add scalariform

README.md
Adding documentation about running the server in PROD and DEV mode.
=> Adding instructions to run the server in PROD and DEV mode.

app/views/react.scala.html
@davidfurey correctly pointed that the current copy is not clear. The new copy addresses that problem. 
* New copy
=> New copy for the No Js message

.eslintrc, app/views/main.scala.html, assets/helpers/logger.js, assets/pages/bundles-landing/bundlesLanding.jsx, package.json, webpack.config.js, yarn.lock
We want to be able to log our errors using [Sentry](https://sentry.io/). Therefore, in this PR we are adding it as a helper. 
[**Trello Card**](https://trello.com/c/El0F8Sjd/544-add-sentry-logging-to-support-frontend-client-side)
* Created the sentry helper.
* Generating source maps in production.
N/A
=> Sentry client side

assets/components/doubleHeading/doubleHeading.scss, assets/components/featureList/featureList.scss, assets/pages/bundles-landing/bundlesLanding.scss, assets/pages/bundles-landing/components/Bundles.jsx, assets/pages/bundles-landing/components/Introduction.jsx, assets/pages/bundles-landing/components/WaysOfSupport.jsx, assets/stylesheets/gu-sass/helpers.scss, assets/stylesheets/gu-sass/layout.scss, assets/stylesheets/main.scss
This polishes the design of the landing page, fixing issues with typography, colour scheme, and layout across the breakpoints.
Still a couple of graphical issues in IE and Safari 8, but probably not blockers to going live.
[**Trello Card**](https://trello.com/c/gW9gfqZW/567-polish-design-details-of-the-new-site-in-order-to-go-live)
- Updated typography and layout of the introduction text.
- Updated colours, copy and twiddly bits (radio triangle, ticks) for the bundles.
- Fixed bundle layout across the breakpoints.
- Fixed font usage across the page.
- Fixed layout of 'other ways' section.
- Tweaked `.gu-content-margin` to get the right padding.
To follow.
=> Bundles Landing Design Tweaks

README.md, docs/development.md
This PR is part of the process to allow new developers to understand better the architecture of Support frontend.
[**Trello Card**](https://trello.com/c/0pjYG7QS/576-writing-documentation-for-support-frontend)
* Created a `docs` folder with a `development.md`
N/A
=> Documentation

app/lib/aws/AwsAsync.scala, app/lib/stepfunctions/Client.scala, app/lib/stepfunctions/ResourceManager.scala, app/lib/stepfunctions/StateMachineContainer.scala, app/lib/stepfunctions/StateMachineLookup.scala, app/lib/stepfunctions/package.scala, build.sbt, scalastyle-config.xml, test/lib/stepfunctions/ResourceManagerTest.scala, test/lib/stepfunctions/StateMachineContainerTest.scala, test/lib/stepfunctions/StateMachineLookupTest.scala
So that we can call step functions from support-frontend
[**Trello Card**](https://trello.com/c/6VZ3B2Fb/528-trigger-aws-step-function-from-support-frontend)
=> Add step function discovery helpers

.prout.json, app/views/main.scala.html
We want releases information in Sentry.
[**Trello Card**](https://trello.com/c/0yrxy8lx/585-add-prout)
* Add `.prout.json` configuration
* Add the gitcommit id to `main.scala.html`
N/A
=> Added prout configuration.

assets/helpers/abtest.js, assets/helpers/cookie.js, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/bundles-landing/components/WaysOfSupport.jsx, assets/pages/bundles-landing/helpers/abtest.js, assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap, assets/pages/bundles-landing/reducers/reducers.js, package.json
We want to be able to test features using A/B tests, in this PR we add a shared helper which handle the AB tests logic and an example test that set up different messages for a title on the landing page. The example test is turn off currently.
[**Trello Card**](https://trello.com/c/diAPTYG7/557-a-b-testing-module)
N/A
=> AB test framework

app/codecs/CirceDecoders.scala, app/controllers/MonthlyContributions.scala, app/lib/actions/PrivateAction.scala, app/lib/aws/package.scala, app/lib/stepfunctions/Client.scala, app/lib/stepfunctions/MonthlyContributionsClient.scala, app/wiring/AppComponents.scala, build.sbt, conf/routes
So that js clients can trigger step function to create a monthly recurring contribution
=> Add monthly-contributions endpoint

docs/setup.md
So that people know how to set up the project
=> Download DEV config from S3

app/controllers/MonthlyContributions.scala, app/lib/stepfunctions/MonthlyContributionsClient.scala
This joins the requestId to the statemachine execution arn, which will simplify debugging failures
=> Log monthly subscription attempts

README.md, docs/development.md
To document the process of creating a new ab test.
[**Trello Card**](https://trello.com/c/98Ajh7Sz/591-documentation-for-ab-test-framework)
* Added table of content in README.
* Added Ab Test framework section in the development guide.
N/A
=> Ab test docs

docs/development.md
Fixing a typo.
* Change 1
* Change 2
=> Minor fix (typo)

assets/pages/monthly-contributions-thankyou/monthlyContributionsThankyou.jsx, assets/pages/monthly-contributions-thankyou/monthlyContributionsThankyou.scss, assets/stylesheets/main.scss, conf/routes, webpack.config.js
The thank you page for monthly contributions. It's not amazingly beautiful right now, but it's better than the 404 that #87 is linking to.
This is mainly a placeholder for now, so that we have something working for the whole flow; it will be tweaked when we apply some UXD to it.
[**Trello Card**](https://trello.com/c/bthrjAkK/607-create-a-thank-you-page-for-monthly-contributions)
- Added thank you page files.
- Added route for thank you page.
- Added page to webpack.
**Mobile:**
**Desktop:**
=> Monthly Contributions Thank You page

assets/helpers/pageStartup.js, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/monthly-contributions-thankyou/monthlyContributionsThankyou.jsx, assets/pages/monthly-contributions/monthlyContributions.jsx
There are a lot of boilerplate methods when you create a new page. This PR seeks to delete as much as possible by introducing a new module that executes the basics steps of the startup process.
=> Page startup

assets/pages/monthly-contributions-thankyou/monthlyContributionsThankyou.jsx, assets/pages/monthly-contributions/monthlyContributions.jsx
Fix for #93, default export broke some imports.
=> Fix PageStartup

docs/development.md
To make the ReadMe slightly clearer to read
=> Some grammatical and spelling tweaks for the ReadMe

app/controllers/MonthlyContributions.scala, app/views/monthlyContributions.scala.html, assets/components/testUserBanner/testUserBanner.jsx, assets/components/testUserBanner/testUserBanner.scss, assets/helpers/user/userReducer.js, assets/pages/monthly-contributions/monthlyContributions.jsx, assets/stylesheets/main.scss
We need a dialogue to tell us if the current logged user is a test user or not.
[**Trello Card**](https://trello.com/c/qircCC2I/641-test-user-banner-for-support-frontend)
* Added the TestUserBanner component.
* Added the Banner to the `monthlyContributions.jsx`
=> Test user banner

app/codecs/CirceDecoders.scala, app/config/Configuration.scala, app/lib/aws/AwsConfig.scala, app/lib/stepfunctions/Client.scala, app/lib/stepfunctions/Encryption.scala, app/lib/stepfunctions/MonthlyContributionsClient.scala, app/lib/stepfunctions/StateMachineContainer.scala, app/lib/stepfunctions/StateWrapper.scala, app/wiring/AppComponents.scala, build.sbt, cloud-formation/cfn.yaml
For data protection reasons, we want to encrypt the state we pass in to step functions. This PR does that.
[**Trello Card**](https://trello.com/c/c6wlfctI/631-add-step-function-encryption-support-to-support-frontend)
=> Encrypt state

assets/stylesheets/main.scss
Fixing https://github.com/guardian/support-frontend/pull/121
=> Removed a non existing dependency.

assets/components/stripePopUpButton/stripePopUpButton.jsx, assets/components/stripePopUpButton/stripePopUpButton.scss, assets/components/svg/svg.jsx
This SVG will improve the user experience.
[**Trello Card**](https://trello.com/c/lBtSiDYb/672-q2-test-2-css-issues)
* Add the credit card SVG.
| Mobile | Tablet | Desktop |
|--------|--------|---------|
|  ![mobile-credit-card](https://user-images.githubusercontent.com/825398/28077489-cac95202-6659-11e7-95c3-d86c925fa395.png)      |  ![tablet-credit-card](https://user-images.githubusercontent.com/825398/28077502-d6d625de-6659-11e7-9f5e-59e3668e2cbd.png)   |  ![desktop-credit-card](https://user-images.githubusercontent.com/825398/28077538-f7a342a6-6659-11e7-9eaf-8c0186fe1046.png) |
=> Credit card SVG

assets/components/errorMessage/errorMessage.jsx, assets/components/errorMessage/errorMessage.scss, assets/components/svg/svg.jsx, assets/components/textInput/textInput.scss, assets/pages/monthly-contributions/components/paymentMethods.jsx, assets/stylesheets/main.scss
If the server returns 500 we are not showing an error message and this can lead to a confused user experience. This PR adds an error message.
[**Trello Card**](https://trello.com/c/8vmUpeTk/690-add-error-message-on-monthly-contributions-page)
| Mobile | Tablet | Desktop |
|--------|--------|---------|
| ![error-mobile](https://user-images.githubusercontent.com/825398/28118990-31a22a92-670b-11e7-8e88-31034e129dd5.png) | ![error-tablet](https://user-images.githubusercontent.com/825398/28119058-6881b9b0-670b-11e7-8f4b-45f1d9c938c1.png) |   ![error-desktop](https://user-images.githubusercontent.com/825398/28118771-53403bb8-670a-11e7-97aa-e09593e75c4c.png)   |
=> Error message for recurring contribution flow

app/actions/CSRFAction.scala, app/actions/CacheControl.scala, app/actions/CustomActionBuilders.scala, app/filters/SetCookiesCheck.scala, app/views/monthlyContributions.scala.html, app/wiring/ActionBuilders.scala, app/wiring/AppComponents.scala, assets/helpers/csrf/csrfActions.js, assets/helpers/csrf/csrfReducer.js, assets/pages/monthly-contributions/helpers/ajax.js, assets/pages/monthly-contributions/reducers/reducers.js, conf/CODE.public.conf, conf/DEV.public.conf, conf/PROD.public.conf, conf/application.conf, test/actions/ActionRefinerTest.scala, test/controllers/ApplicationTest.scala, test/controllers/MonthlyContributionsTest.scala, test/fixtures/TestCSRFComponents.scala
To protect against cross site request forging attacks.
* Enable CSRF on private actions
* Check that cookies haven't been read or set for cached pages
=> Add CSRF filtering

build.sbt, nginx/support.conf, package.json, webpack.config.js
We are currently clashing with contributions.thegulocal.com
=> Run on a different port from contributions

assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap, assets/pages/bundles-landing/reducers/__tests__/reducersTest.js, package.json
Adding test and refactoring the current set of tests of bundle-landing-page's reducers.
[**Trello Card**](https://trello.com/c/d2de0Wow/533-add-jest-test-for-components)
* Added update snapshot command to package.json
* Refactor bundle-landing-page's reducer test
=> Test for the bundle landing's reducer 

assets/helpers/payPalExpressCheckout/__tests__/__snapshots__/reducersTest.js.snap, assets/helpers/payPalExpressCheckout/__tests__/reducersTest.js
To ensure quality in the PayPal's reducer.
* Added PayPal's reducer test
=> Test for PayPal's reducer

app/actions/CSRFAction.scala, app/actions/CustomActionBuilders.scala, app/actions/PrivateActionBuilder.scala, app/codecs/CirceDecoders.scala, app/services/MembersDataService.scala, app/services/stepfunctions/ResourceManager.scala, app/services/stepfunctions/StateWrapper.scala
=> Tidying up a few things

assets/components/payPalExpressButton/payPalExpressButton.scss, assets/helpers/payPalExpressCheckout/payPalExpressCheckout.js
=> PayPal css fix

nginx/support.conf
Because I keep putting support.thegulocal.com into my browser and then wondering why I get a 502 error from Nginx.
=> Add additional nginx config to redirect all connections to https

app/controllers/MonthlyContributions.scala, app/controllers/OneOffContributions.scala, test/controllers/MonthlyContributionsTest.scala
By default, we want to show the PayPal button.
=> Change the default behaviour of the paypal switch.

app/controllers/MonthlyContributions.scala
So that monthly contributors aren't sent membership mail
=> Allow membership mail should be false

assets/helpers/abtest.js
We ended up not using this logic. So let's remove it.
* Removed unused logic from `abtests.js`
N/A
=> Delete old code written for the first version of test 2

assets/helpers/payPalContributionsCheckout/__tests__/__snapshots__/payPalContributionsCheckoutReducerTests.js.snap, assets/helpers/payPalContributionsCheckout/__tests__/payPalContributionsCheckoutActionsTests.js, assets/helpers/payPalContributionsCheckout/__tests__/payPalContributionsCheckoutReducerTests.js, assets/helpers/payPalContributionsCheckout/payPalContributionsCheckoutActions.js, assets/helpers/payPalContributionsCheckout/payPalContributionsCheckoutReducer.js, assets/pages/oneoff-contributions/reducers/reducers.js
One-off paypal contributions - this fixes.
=> Paypal amount/currency are not optional fields

app/views/main.scala.html, assets/helpers/logger.js
In order to know when we break stuff.
* Logger
[Here](https://docs.sentry.io/clients/javascript/config/)
=> Add release field to sentry logger

assets/pages/bundles-landing/helpers/subscriptionsLinks.js
Two missing promo codes for test 4.
* Two promo codes.
=> Added two extra campaign codes.

assets/pages/bundles-landing/helpers/subscriptionsLinks.js
=> campaign codes for test 4 side menu

app/views/main.scala.html, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/bundles-landing/helpers/subscriptionsLinks.js
We saw people becoming a supporter (supporter/partner/friend) in the support variant of test 4. We believe that they are doing this via the Patron link. Therefore, we remove that section for this test.
| Campaign Code    | Screenshot |  
|-------------------|------------| 
|No Campaign Code | ![no-campaign-code](https://user-images.githubusercontent.com/825398/29877413-780545ac-8d97-11e7-9500-8b76aa37ff00.png)|
|gdnwb_copts_memco_sandc_support_baseline_support_header_become_supporter | ![ladinggdnwb_copts_memco_sandc_support_baseline_support_header_become_supporter](https://user-images.githubusercontent.com/825398/29877705-4484f618-8d98-11e7-98a9-7263bfb53e1b.png)|
|gdnwb_copts_memco_sandc_support_baseline_support_header_subscribe …
=> Removing ways support test 4

app/controllers/TestUsersManagement.scala, app/views/testUsers.scala.html, assets/helpers/payPalContributionsCheckout/payPalContributionsCheckout.js
So that we can use test users for paypal in production
=> Send test user info to contributions

assets/components/paymentMethods/paymentMethods.jsx, assets/pages/monthly-contributions/reducers/reducers.js
So that the page works better for users whose first payment has failed
=> Show pending message when attempting payment for the second time

.gitignore, app/codecs/CirceDecoders.scala, app/controllers/MonthlyContributions.scala, assets/components/contribAmounts/contribAmounts.jsx, assets/components/contribAmounts/contribAmounts.scss, assets/components/payPalContributionButton/payPalContributionButton.jsx, assets/components/radioToggle/radioToggle.jsx, assets/helpers/contributions.js, assets/helpers/tracking/guTracking.js, assets/helpers/utilities.js, assets/pages/bundles-landing/actions/__tests__/bundlesLandingActionsTest.js, assets/pages/bundles-landing/actions/bundlesLandingActions.js, assets/pages/bundles-landing/components/Bundles.jsx, assets/pages/bundles-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap, assets/pages/bundles-landing/reducers/__tests__/reducersTest.js, assets/pages/bundles-landing/reducers/reducers.js, assets/pages/contributions-landing/actions/contributionsLandingActions.js, assets/pages/contributions-landing/components/contributionsBundle.jsx, assets/pages/contributions-landing/reducers/__tests__/__snapshots__/reducersTest.js.snap, assets/pages/contributions-landing/reducers/__tests__/reducersTest.js, assets/pages/contributions-landing/reducers/reducers.js, assets/pages/monthly-contributions/helpers/ajax.js, assets/pages/monthly-contributions/monthlyContributions.jsx, build.sbt, yarn.lock
To enable supporters to pay annually.
The annual payments version is hidden behind a querystring parameter, to see it showAnnual=true to the url.
NB. The work to turn this into an AB test is still outstanding.
[**Trello Card**](https://trello.com/c/mxWzhDt2/882-update-support-frontend-to-allow-users-to-make-annual-regular-contributions)
=> Annual contributions

assets/components/contribAmounts/contribAmounts.jsx, assets/components/payPalContributionButton/payPalContributionButton.jsx, assets/components/radioToggle/radioToggle.jsx, assets/pages/contributions-thankyou/oneoffContributionsThankyou.jsx, conf/CODE.public.conf, conf/DEV.public.conf, conf/PROD.public.conf, conf/application.conf, test/selenium/ContributorSpec.scala, test/selenium/conf/selenium-test.conf, test/selenium/pages/ContributionsLanding.scala, test/selenium/pages/MonthlyContribution.scala, test/selenium/pages/OneOffContributionthankYou.scala, test/selenium/pages/RecurringContributionThankYou.scala, test/selenium/util/Config.scala, test/selenium/util/Dependencies.scala, test/selenium/util/Driver.scala, test/selenium/util/PayPalCheckout.scala, test/selenium/util/SeleniumTag.scala, test/selenium/util/TestUser.scala
Adding post-deploy selenium test for one-off (paypal) contribution.
[**Trello Card**](https://trello.com/c/S8e1FCOv/888-post-deployment-tests-for-one-off-contributions-support-frontend)
* Added a paypal test for one off.
N/A
=> Selenium one off tests for PayPal

assets/helpers/user/__tests__/__snapshots__/userReducerTest.js.snap, assets/helpers/user/__tests__/userReducerTest.js, assets/helpers/user/userReducer.js, assets/pages/oneoff-contributions/__tests__/oneoffContributionsActionsTest.js, assets/pages/oneoff-contributions/oneOffContributionsReducers.js, assets/pages/regular-contributions/regularContributionsReducers.js
=> Unit Tests

docs/development.md
To keep the docs up to date. Created the env table.
=> Update test docs

app/controllers/Application.scala, app/controllers/OneOffContributions.scala, app/controllers/PayPal.scala, app/views/ViewHelpers.scala, app/views/contributionsLanding.scala.html, app/views/main.scala.html, app/views/oneOffContributions.scala.html, app/views/react.scala.html
So that we don't track users who have asked not to be tracked
[**Trello Card**](https://trello.com/c/OUISd7lS/865-tracking-parity-with-membershiptheguardiancom)
=> Switch off tagging for users who have sent a Do Not Track header

assets/components/video/video.jsx, assets/pages/bundles-landing/components/Bundles.jsx
Bad grammar is bad. Also, the new video has finally been uploaded!
- Changed `off` to `on`.
- Changed video id to use new version of Scott Trust video.
=> Landing Page Language Tweak and New Video

cloud-formation/cfn.yaml
To fix the status endpoint so that users stop seeing the /pending endpoint
=> Allow support-frontend to decrypt the state

app/views/main.scala.html
To enable google webmaster tools
=> Add site verification tag

app/controllers/Application.scala, app/wiring/AppComponents.scala, conf/routes
So when the user is redirected to `/uk` we send the query params too.
=> Index redirect

assets/pages/contributions-landing/components/contributionsBundle.jsx, assets/pages/contributions-landing/components/contributionsIntroduction.jsx, assets/pages/contributions-landing/contributionsLanding.scss
To put everything in place before launching.
[**Trello Card**](https://trello.com/c/Cb1JZh4N/956-contributions-landing-page-review)
|   Breakpoints     | Before | After |
|-----------------|---------|-------|
| Mobile (from: `320px`) | ![mobileold](https://user-images.githubusercontent.com/825398/31668623-9a187c30-b34a-11e7-9cfa-043fc1c63ee2.png) |    ![mobilenew](https://user-images.githubusercontent.com/825398/31668674-c2724d96-b34a-11e7-9522-363f6dd74b02.png)   |
|    Phablet (from:`660px`)     |    ![phabletnew](https://user-images.githubusercontent.com/825398/31668869-464061bc-b34b-11e7-9046-f94ee06022ce.png)    |  ![phablet-new](https://user-images.githubusercontent.com/825398/31668885-4fc268d4-b34b-11e7-854a-96fe0b48d753.png) |
|     Tablet (from:`740px`)     | …
=> [US launch 🚀]   Copy changes

assets/helpers/tracking/googleTagManagerScript.js
To track using the GTM new account.
=>  Added the new container id

assets/helpers/page/page.js, assets/helpers/render.js, assets/helpers/tracking/googleTagManagerScript.js, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/contributions-landing/contributionsLandingUK.jsx, assets/pages/contributions-landing/contributionsLandingUS.jsx, assets/pages/contributions-thankyou/oneoffContributionsThankyou.jsx, assets/pages/contributions-thankyou/regularContributionsPending.jsx, assets/pages/contributions-thankyou/regularContributionsThankyou.jsx, assets/pages/oneoff-contributions/oneoffContributions.jsx, assets/pages/paypal-error/payPalError.jsx, assets/pages/regular-contributions-existing/regularContributionsExisting.jsx, assets/pages/regular-contributions/regularContributions.jsx, package.json, yarn.lock
To keep our codebase up to date.
* https://github.com/guardian/support-frontend/pull/295
* https://github.com/guardian/support-frontend/pull/292
=> Updated flow and file-loader libs

app/actions/NoCacheActionBuilder.scala, app/controllers/Application.scala, app/utils/RequestCountry.scala, conf/routes
This PR is addersses a couple of points raised by @davidfurey from https://github.com/guardian/support-frontend/pull/304
=> A few fixups left over from https://github.com/guardian/support-frontend/pull/304

assets/helpers/tracking/acquisitions.js, assets/pages/bundles-landing/helpers/externalLinks.js
So we can track subs signups from our test https://github.com/guardian/frontend/pull/18080
=> Add promo codes for Ease Of Payment epic test

assets/helpers/tracking/acquisitions.js, assets/pages/bundles-landing/helpers/externalLinks.js
Adds the promo codes for the campaign codes associated with the upcoming 750,00 supporters piece.
=> Add promo codes for 750 peice

build-tc
To run the latest stable version of yarn in TeamCity.
* Update `build-tc`
=> Upgrading team-city yarn version.

assets/helpers/tracking/googleTagManager.js
To be able to send OphanBrowserId to GTM.
[**Trello Card**](https://trello.com/c/uJPKkDRB/1040-populate-ophan-browser-id-to-a-datalayer)
=> Adding ophanBrowserID to the GTM

cloud-formation/cfn.yaml
While checking the security groups for support-frontend I noticed that the description was out of date.
[**Trello Card**](https://trello.com/c/QVxm5eYS/1014-check-that-security-groups-for-support-frontend-and-membership-frontend-expose-the-minimum-entry-and-exit-ports)
=> Comment correction

assets/helpers/tracking/acquisitions.js, assets/pages/bundles-landing/helpers/externalLinks.js
Promo codes for big banner test
=> Add promo codes for big banner test

assets/helpers/tracking/acquisitions.js, assets/pages/bundles-landing/helpers/externalLinks.js
=> update promo codes for big banner test

.prout.json
=> Fix prout integration test

project/plugins.sbt
Also adds OWASP dependency checker and dependency graph plugins
=> Upgrade to play 2.6.7

assets/components/contribAmounts/contribAmounts.scss, assets/components/radioToggle/radioToggle.jsx, assets/components/radioToggle/radioToggle.scss, assets/pages/bundles-landing/bundlesLanding.scss
More circles-linked work. There's a couple of bits and pieces here that are making it difficult to develop circles because they're a bit messy. In the spirit of trying not to touch other parts of the site in the main circles PRs I'm doing them separately.
- Drops a wrapping `div` from the `RadioToggle` component.
- Put some CSS relating to the contribution amount selection in a more specific (less globally interfering) place.
=> Tidy Up The Contributions Selection

app/config/StringsConfig.scala, app/controllers/Application.scala, app/views/contributionsLanding.scala.html, conf/strings.conf
To improve SEO of our contribution landing pages.
=> Adding meta tag for the contribution landing pages.

app/controllers/SiteMap.scala
=> Fix sitemap logic.

build.sbt
Upgrades from medium severity bouncycastle version
=> Upgrade to latest identity-play-auth

cloud-formation/cfn.yaml
To keep all the servers synced.
=> Allow outgoing NTP traffic

assets/helpers/abtestDefinitions.js, assets/pages/contributions-landing/contributionsLandingUS.jsx
=> Remove US default contribution test

app/views/main.scala.html
To improve our SEO
[**Trello Card**](https://trello.com/c/6eCsUucV/973-add-structured-data)
* `main.scala.html`
=> Added structured data to the main template

app/views/main.scala.html
To fix google structured data parser
=>  Fixed structured data parsing error

assets/helpers/abtestDefinitions.js
The tracking of the conversions is not set up yet, so the test should be turned off for now
=> Turn digipack test off

assets/helpers/tracking/googleTagManager.js
I'm doing some research into why the Digital Operations and Optimisation team are currently not able to use Krux effectively on the membership, subs or support site. This PR will hopefully allow us to get it working correctly on support.
=> Add two new fields to the data layer to help with Krux targeting

assets/helpers/abtestDefinitions.js
=> Turn on digipack test

assets/helpers/abtestDefinitions.js, assets/pages/bundles-landing/bundlesLanding.jsx, assets/pages/bundles-landing/bundlesLanding.scss, assets/pages/bundles-landing/components/Introduction.jsx
This test tries out 2 new variants which change the copy in the header
Control mobile:
Control desktop:
How and why mobile:
How and why desktop:
Number of supporters mobile:
Number of supporters desktop:
=> UK Header copy test

assets/helpers/abtestDefinitions.js, assets/pages/contributions-landing/components/contributionsBundle.jsx, assets/pages/contributions-landing/components/contributionsBundleContent.jsx, assets/pages/contributions-landing/components/contributionsIntroduction.jsx, assets/pages/contributions-landing/contributionsLanding.scss
This adds a recurring payment upsell message test to the US contribute landing page.
- adds the tests
- updates the control design slightly!
**control:**
https://support.theguardian.com/us/contribute#ab-usRecurringCopyTest=control
**subtitle variant**
https://support.theguardian.com/us/contribute#ab-usRecurringCopyTest=subtitle
**contribute box variant**
https://support.theguardian.com/us/contribute#ab-usRecurringCopyTest=contributeBox
=> Us recurring copy test

assets/components/svg/svg.jsx, assets/pages/bundles-landing/support-landing-ab-test/components/behindTheScenesNewDesign.jsx, assets/pages/bundles-landing/support-landing-ab-test/supportLanding.jsx, assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss
New section going in to explain about newsroom emails.
[**Trello Card**](https://trello.com/c/ngQQL50q/1098-support-landing-behind-the-scenes)
cc: @Amohkhan
- Added a new svg of a moving circle.
- Added new Behind The Scenes section.
- Styled it.
**Section:**
**Within Page:**
=> Support Landing Page - Part 6 - Behind The Scenes

assets/helpers/contributions.js
For an upcoming new test, we are changing the minimum recurring amount allowed to $2. This PR implement this change.
I have checked on code, and this frontend validation is the only place we enforce the minimum amount
=> Change minimum recurring contribution to 2

docs/development.md
So that I can deploy something, in order to test a [change to Prout](https://github.com/guardian/prout/pull/56).
=> Minor README tweak

assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss
The 'behind the scenes' section looks a little spartan at the moment. This adds a background circle to make it look fancier. CSS-only PR!
cc: @Amohkhan
[**Trello Card**](https://trello.com/c/MszNznxy/1114-add-background-circle-to-behind-the-scenes)
- Added a background circle and positioned it correctly above the background but behind the content.
|| Desktop | Mobile
-|-|-
Before | ![bgcircle-desktop-before](https://user-images.githubusercontent.com/5131341/33182021-36a67732-d06a-11e7-9e99-e3c66de4c9ef.png) | ![bgcircle-mobile-before](https://user-images.githubusercontent.com/5131341/33182079-699a5df2-d06a-11e7-9458-880692717a47.png)
After | ![bgcircle-desktop-after](https://user-images.githubusercontent.com/5131341/33182030-3c4fb036-d06a-11e7-8f63-85beaaedeb42.png) | …
=> Support Landing Page - Part 9 - Background Circle

assets/pages/bundles-landing/helpers/blackFriday.js
The logic for the black friday test has a bug somewhere so I'm hard coding it to true for now
=> Hard code black friday copy on

assets/pages/bundles-landing/helpers/blackFriday.js
To correct the date logic in the Black Friday code.
=> Fix the date logic - months are 0 based

docs/development.md
To keep the docs up to date.
* development.md
=> Updated the AB Test's fields section

assets/helpers/__tests__/utilitiesTest.js, assets/helpers/utilities.js, assets/pages/oneoff-contributions/components/oneoffContributionsPayment.jsx
If someone enters an invalid email address, we get an error from the POST to contributions-frontend and the payment fails.  This PR displays an error message before the user enters their card details
[**Trello Card**](https://trello.com/c/FAyF2NBs/1057-invalid-email-for-one-off-contributions)
=> Client side email validation for one-off contributions

app/services/stepfunctions/RegularContributionsClient.scala
To make it clear which status we are returning to the client during a recurring contribution sign-up journey.
* Add logging to status polling functionality.
=> Add logging to status polling

build.sbt
To address this vulnerability: https://snyk.io/vuln/SNYK-JAVA-ORGSCALALANG-31592?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln
=> Upgrade Scala compiler to 2.11.12

assets/pages/bundles-landing/support-landing-ab-test/components/mothershipNewDesign.jsx, assets/pages/bundles-landing/support-landing-ab-test/components/whySupportNewDesign.jsx, assets/pages/bundles-landing/support-landing-ab-test/supportLanding.scss
There are some updates to the copy, based in part on some tests acquisitions have been running.
[**Trello Card**](https://trello.com/c/I5DNpu8r/1099-support-landing-copy-tweaks)
cc: @Amohkhan
- Tweaked the copy in the mothership.
- Tweaked the copy in the "why support" section.
=> Support Landing Page - Part 11 - Copy Tweaks

assets/pages/regular-contributions/components/regularContributionsPayment.jsx
Before starting the Direct Debit work, I noticed there is a little of duplication in regularContributionPayment, this PR remove the majority of it. 
* **regularContributionPayment**
N/A
=> Refactor of the regularContributionPayment for directDebit work

assets/pages/bundles-landing/bundlesLanding.scss, assets/pages/bundles-landing/components/bundles.jsx, assets/pages/bundles-landing/components/introduction.jsx, assets/pages/bundles-landing/components/stackedBundle.jsx, assets/pages/bundles-landing/components/waysOfSupport.jsx, assets/pages/bundles-landing/components/whySupport.jsx, assets/stylesheets/garnett.scss
Tidy up the bundles landing page.
cc: @Amohkhan
- Updated the introduction.
- Updated the bundles headings and CTAs.
- Updated the "why support" and "other ways" sections.
=> Post Garnett Tidy Landing Page

README.md, docs/development.md
To specify the CSS convention of `support-frontend`.
* Added an extra section in the `development.md` file
N/A
=> Added the CSS guidelines

docs/setup.md
=> Mention support-config in readme

docs/development.md
To state the CSS convention into the readme.
N/A
=> Adding the two-spaces indentation to the CSS guidelines

app/controllers/RegularContributions.scala, app/views/monthlyContributions.scala.html, assets/helpers/abTests/abtestDefinitions.js, assets/pages/regular-contributions/components/regularContributionsPayment.jsx, conf/routes, test/controllers/RegularContributionsTest.scala
We want to test that adding Direct Debit as a payment method won't negatively impact conversion. This PR sets up an AB test to do this.
I still need to discuss the numbers with Devina but the code is complete
[**Trello Card**](https://trello.com/c/3ax49Rhk/1254-implement-ab-test-for-direct-debit)
=> Add an AB test for direct debit

docs/development.md
Added a chunk of documentation on presentational vs container components, and scoped actions and reducers. This can be found in the 'Architecture' section. Also ran the file through a markdown linter and tweaked to fixed any issues.
- Two new subsections, one on presentational vs container components, and one on scoping actions and reducers.
- Ran the markdown through a linter and fixed issues.
=> Documentation For Container Components

app/controllers/Application.scala, assets/components/contribute/contribute.scss, assets/components/dotcomCta/dotcomCta.scss, assets/components/questionsContact/questionsContact.jsx, assets/components/questionsContact/questionsContact.scss, assets/components/spreadTheWord/spreadTheWord.scss, assets/pages/regular-contributions-thank-you/components/emailConfirmation.jsx, assets/pages/regular-contributions-thank-you/regularContributionsThankYou.jsx, assets/pages/regular-contributions-thank-you/regularContributionsThankYou.scss, conf/routes
This applies some final design tweaks to the regular contributions thank you page. It sets up routing for the pending URL to serve this page as well.
[**Trello Card**](https://trello.com/c/xLvz94EB/1307-regular-pending-page)
cc @JustinPinner
- Created a new application method to serve the circles version of the pending page.
- Minor CSS tidying.
- Tweaks and fixes for the design of the thank you page.
- Added copy telling the user to look out for a confirmation email.
**Desktop:**
**Tablet:**
**Mobile:**
=> Circles Rebuild - Part X - Regular Thank You and Pending

build.sbt
To keep the libs in sync.
* `build.sbt`
N/A
=> support-internationalisation upgrade

cloud-formation/cfn.yaml
See https://github.com/guardian/ssm-scala
This should allow us to disable SSH (GDPR!)
=> Add policy for SSM

assets/components/countryGroupSwitcher/countryGroupSwitcher.scss, assets/components/headers/countrySwitcherHeader/countrySwitcherHeader.scss
To fix mobile header.
* css changes
| Mobile | Mobile Medium | Mobile Landscape | Phablet | Tablet | Desktop |
|--------|---------------|------------------|---------|--------|---------|
| ![support thegulocal com_uk mobile](https://user-images.githubusercontent.com/825398/36600469-48e89f3c-18aa-11e8-88c9-adca39b3a3e1.png)|               ![support thegulocal com_uk mobilemedium](https://user-images.githubusercontent.com/825398/36600507-63028a36-18aa-11e8-9b37-115680f601ba.png)|         ![support thegulocal com_uk mobilemedium](https://user-images.githubusercontent.com/825398/36600535-78134ac8-18aa-11e8-9ed5-5d2862187b75.png) |         ![support thegulocal com_uk phablet](https://user-images.githubusercontent.com/825398/36600597-a28148b4-18aa-11e8-9256-486f6c5b40b5.png)|![support thegulocal …
=> Fix mobile header

assets/helpers/abTests/abtestDefinitions.js
Switch on the Direct Debit AB test
[**Trello Card**](https://trello.com/c/DrVp26Bk/1269-switch-on-direct-debit-ab-test)
=> Switch DD test on

assets/components/bundle/bundle.jsx, assets/components/inlinePaymentLogos/inlinePaymentLogos.scss, assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/components/contributionsBundle.jsx, assets/pages/contributions-landing/contributionsLanding.scss
To remove the padlock test.
[**Trello Card**](https://trello.com/c/L9zmjWqK/138-remove-finished-tests-on-support-frontend)
* Removed the padlock lock test from all the files.
=> Removed the padlock test

README.md, docs/supported-browsers.md
To specify which browsers we should support. 
[**Trello Card**](https://trello.com/c/RtFaZJMP/1347-codify-browser-support-list)
N/A
=> Adding document containing the supported browsers

build.sbt
=> Update jackson-databind to resolve CVE-2018-7489

package.json, yarn.lock
To keep sentry up to date.
* package.json
* yarn.lock
N/A
=> Updated sentry

assets/containerisableComponents/marketingConsent/marketingConsent.jsx, assets/containerisableComponents/marketingConsent/marketingConsent.scss
Fix some CSS tech debt
[**Trello Card**](https://trello.com/c/NnPSZaF4/153-thank-you-page-visuals-fix)
* Marketing consent CSS
=> Fix some css issues in the marketing consent page

assets/components/contribAmounts/contribAmounts.jsx, assets/helpers/contributions.js, assets/pages/contributions-landing/contributionsLandingAU.jsx
New monthly values for AUD.
* The monthly values should be 10, 20. 40
* The minimum value should be 10
=> New values for AUD

assets/pages/contributions-landing-us/contributionsLandingUS.jsx
=> Revert the US contributions landing page copy back to the control

app/controllers/Application.scala
To start driving traffic to Europe.
=>  Adding Europe's redirects

assets/components/subscriptionBundle/subscriptionBundle.jsx, assets/components/threeSubscriptions/threeSubscriptions.jsx, assets/components/threeSubscriptions/threeSubscriptions.scss, assets/helpers/theGrid.js
Applying Circles designs to the Subscribe section on the showcase page.
[**Trello Card**](https://trello.com/c/2N22rZD7/1283-subscribe-module)
- Added images of the Subscribe bundles from the Grid.
- Wrapped the ThreeSubscriptions component in a div with a class containing its name.
- Styled the Subscribe section.
**Wide**
**Desktop**
**Tablet**
**Mobile**
=> Showcase Page - Circles For Subscribe

assets/components/contribAmounts/contribAmounts.jsx, assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx, assets/components/headers/countrySwitcherHeader/countrySwitcherHeader.jsx, assets/helpers/contributions.js, assets/helpers/internationalisation/country.js, assets/helpers/internationalisation/countryGroup.js, assets/helpers/internationalisation/currency.js, assets/pages/contributions-landing-au/components/contributionsBundle.jsx, assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js, assets/pages/contributions-landing/contributionsLanding.jsx, assets/pages/regular-contributions/components/formFields.jsx, conf/routes
To have a page for NZD countries
* Created an NZDCountries country group.
* Implemented the NZ page
* Propagate NZDCountries to pages with an old copy.
=> Adding NZDCountries landing page

assets/components/contribAmounts/contribAmounts.jsx, assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx, assets/helpers/contributions.js, assets/helpers/internationalisation/country.js, assets/helpers/internationalisation/countryGroup.js, assets/helpers/internationalisation/currency.js, assets/pages/contributions-landing-au/components/contributionsBundle.jsx, assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js, assets/pages/contributions-landing/contributionsLanding.jsx, assets/pages/regular-contributions/components/formFields.jsx, conf/routes
Reverts guardian/support-frontend#586
We can't build with teamcity, let's keep master in sync with PROD.
=> Revert "Adding NZDCountries landing page"

assets/components/contribAmounts/contribAmounts.jsx, assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx, assets/helpers/contributions.js, assets/helpers/internationalisation/country.js, assets/helpers/internationalisation/countryGroup.js, assets/helpers/internationalisation/currency.js, assets/pages/contributions-landing-au/components/contributionsBundle.jsx, assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js, assets/pages/contributions-landing/contributionsLanding.jsx, assets/pages/regular-contributions/components/formFields.jsx, conf/routes
Reverts guardian/support-frontend#592
PR to be merged after typesafe is working again.
=> Revert "Revert "Adding NZDCountries landing page""

assets/helpers/contributions.js
Preparation for NZ page launch. Updating values.
* Updating one-off and monthly values.
=> Update nzd values

app/controllers/Application.scala, assets/pages/bundles-landing/components/countrySwitcherHeaderContainer.jsx, assets/pages/contributions-landing/containers/countrySwitcherHeaderContainer.js
To enable start driving traffic to this new sites.
* Added redirects for new countries.
* Added the new countries in the country selector.
=> Releasing CA, NZ and Int regions

assets/components/patronsEvents/patronsEvents.scss, assets/components/readyToSupport/readyToSupport.scss, assets/components/svg/svg.jsx
To make the showcase page ready for release. This fixes problems that existed in IE. It also makes a couple of tweaks to the patrons and events section on tablets.
[**Trello Card**](https://trello.com/c/rPaWrGBf/1411-cross-browser-test-showcase-page)
- Fixed IE SVG issues.
- Tweaked the Patrons and Events section to sort out wrapping issues.
=> Showcase Page - Cross Browser Fixes

app/controllers/Application.scala
To take Canadians to the correct contribute page
=> Fixed contribute redirect

app/controllers/RegularContributions.scala, app/views/monthlyContributions.scala.html, assets/helpers/abTests/abtestDefinitions.js, assets/pages/regular-contributions/components/regularContributionsPayment.jsx, conf/routes, test/controllers/RegularContributionsTest.scala
After the successful test of Direct Debit as a payment method we now have sign off to push it live.
[**Trello Card**](https://trello.com/c/KzR37rCl/1458-put-direct-debit-live)
=> Launch DirectDebit as a payment option for the UK

package.json, yarn.lock
To keep our dependencies up to date.
* `preact`
* `flow-bin`
* `webpack-dev-server`
* `webpack-manifest-plugin`
* `package.json`
* `yarn.lock`
=> Update client side dependencies 

assets/components/threeSubscriptions/threeSubscriptions.jsx, assets/helpers/flashSale.js
To support the May 2018 Flash sale on Paper & Paper + Digital
[**Trello Card**](https://trello.com/c/enZjDCmQ/1503-voucher-and-delivery-sale)
=> May Flash Sale

public/robots.txt
To allow crawlers to read our site.
* robots.txt
N/A
=> Updating robots.txt

assets/containerisableComponents/contributionSelection/contributionSelection.jsx, assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/contributionsLanding.jsx, assets/pages/contributions-landing/contributionsLanding.scss, assets/pages/contributions-landing/oneOffOnlyTest.scss
The test has completed, and we are sticking with the control
=> Remove one-off only for mobile test

assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/contributionsLanding.jsx
To set up the "dropping intro text" test. It will only run in the contributions landing pages.
|                       | Mobile                 | Tablet            | Desktop  |
|-----------------------|------------------------|-------------------|----------|
| Contributions Landing | ![droptthetextmobile](https://user-images.githubusercontent.com/825398/40921104-7180f380-6806-11e8-95ce-2261c47280a5.png)|![dropthetexttablet](https://user-images.githubusercontent.com/825398/40921103-7169d182-6806-11e8-9e3f-9331f9365008.png) |![dropthetextdesktop](https://user-images.githubusercontent.com/825398/40921201-b277f78a-6806-11e8-8316-9ede2176c6f3.png)|
|                       | Mobile                 | Tablet            | Desktop  |
|-----------------------|------------------------|---------------- …
=> "Dropping intro text" test

assets/helpers/page/page.js, assets/pages/contributions-landing/contributionsLanding.jsx, assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
In the upcoming version of the landing page, there are two types of layouts, one vertical and one horizontal (the current one). This basically extracts the current one and place it in a separate file to make the A/B testing easier in the near future.
[**Trello Card**](https://trello.com/c/uPEYmQ1a/507-implementation-of-the-new-contributions-landing-page)
N/A
=> Preparation work for vertical layout [New Contributions Design]

assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/pagesVersions/horizontalLayoutLandingPage.jsx
We decide to stop the test and keep the variant.
* Deleted test definition
* Deleted test logic
=> Delete "Drop intro text" test

assets/components/leftMarginSection/leftMarginSection.scss, assets/components/svgs/amberRudd.jsx, assets/components/svgs/amberZuck.jsx, assets/components/svgs/zuck.jsx, assets/helpers/theGrid.js, assets/pages/digital-subscription-landing/components/independentJournalismSection.jsx, assets/pages/digital-subscription-landing/components/independentJournalismSection.scss, assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
This PR adds in the bottom third of the new digital subscription page
[**Trello Card**](https://trello.com/c/owe2K3bS/1533-independent-journalism-block)
=> Independent journalism section

README.md
To point to the new wiki's links and add two new sections.
* `Readme.md`
N/A
=> Update README's links

assets/components/directDebit/directDebitForm/directDebitForm.jsx, assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx, assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.jsx, assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx, assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.jsx, assets/components/stripeInlineForm/stripeInlineForm.jsx, assets/components/stripeInlineForm/stripeInlineFormActions.js, assets/components/stripeInlineForm/stripeInlineFormReducer.js, assets/helpers/abTests/abtestDefinitions.js, assets/helpers/checkouts.js, assets/helpers/paymentIntegrations/payPalExpressCheckout.js, assets/helpers/paymentIntegrations/stripeCheckout.js, assets/pages/oneoff-contributions/__tests__/__snapshots__/oneoffContributionsReducersTest.js.snap, assets/pages/oneoff-contributions/components/oneOffContributionsPage.jsx, assets/pages/oneoff-contributions/components/oneoffInlineContributionsPayment.jsx, assets/pages/oneoff-contributions/helpers/ajax.js, assets/pages/oneoff-contributions/oneOffContributionsReducers.js, assets/pages/oneoff-contributions/oneoffContributions.scss, assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap, assets/pages/regular-contributions/components/regularContributionsPayment.jsx, assets/pages/regular-contributions/components/regularInlineContributionsPayment.jsx, assets/pages/regular-contributions/helpers/ajax.js
To add stripe inline component into the one-off flow and release the test.
* Added stripe inline component into the one-off flow
* Handled stripe error validation for regular and one-off contribution flow
* Deleted all the Function appearances in one-off and regular flows
* Start the test
=> Stripe inline test part 2

assets/helpers/abTests/abtestDefinitions.js
We are not passing the email to Stripe. Let's fix that and rollout again
* Change 1
* Change 2
=> Disabling Stripe Elements

assets/helpers/abTests/abtestDefinitions.js, assets/pages/oneoff-contributions/components/oneOffContributionsPage.jsx, assets/pages/regular-contributions/components/regularContributionsPage.jsx
In order to avoid miscounting conversion, I am updating the test name.
* Updating test names
=> Update Stripe inline  test name

assets/helpers/abTests/abtestDefinitions.js
So the tests have different seed. 
* New seed for Stripe Test.
N/A
=> New seed for stripe test

assets/containerisableComponents/contributionSelection/contributionSelection.jsx, assets/helpers/abTests/abtestDefinitions.js, assets/helpers/contributions.js, assets/pages/contributions-landing/containers/contributionSelectionContainer.js, assets/pages/support-landing/components/contributionSelectionContainer.js
To measure the impact of one-time in the US.
=> One-time vs. One-off vs. Just once vs. Single for US

app/actions/CustomActionBuilders.scala
=> Reverse client id logic

assets/pages/subscriptions-landing/subscriptionsLanding.jsx
To fix the subscribe page.
* Subscriptions page
=>  Update header

conf/PROD.public.conf
To make it as simple as possible for the poor souls on 24/7 support
=> Make the 24-7 instructions even more obvious

conf/CODE.public.conf
To include the 24/7 instructions in the CODE conf
=> Add the 24-7 instructions into the CODE conf

.flowconfig, assets/helpers/__tests__/urlTest.js, assets/helpers/internationalisation/__tests__/countryGroupTest.js, assets/helpers/internationalisation/__tests__/countryTest.js, assets/helpers/internationalisation/__tests__/currencyTest.js, assets/helpers/page/__tests__/__snapshots__/pageTest.js.snap, assets/helpers/page/__tests__/pageTest.js, assets/helpers/page/page.js, assets/helpers/tracking/__tests__/acquisitionsTest.js, assets/pages/regular-contributions/__tests__/__snapshots__/regularContributionsReducersTest.js.snap, assets/pages/regular-contributions/__tests__/regularContributionsReducersTest.js, flow-typed/npm/jest_v23.x.x.js, flow-typed/npm/react-router-dom_v4.x.x.js, flow-typed/npm/react-router_v4.x.x.js, flow-typed/npm/redux_v4.x.x.js
To be able to check the test files with Flow. This will enable us to capture more bugs since it will keep track of the type changes.
* Remove tests folder from flow ignore
* Updated flow-typed definitions
* Updated tests to pass flow's check
N/A
=> Enabling flow in tests

assets/helpers/externalLinks.js, assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, assets/pages/digital-subscription-landing/components/independentJournalismSection.jsx, assets/pages/digital-subscription-landing/components/priceCtaContainer.jsx, assets/pages/digital-subscription-landing/components/productBlock.jsx
So that we can analyse usage of the CTAs on this page 
[**Trello Card**](https://trello.com/c/eIw5HUyo/1752-add-tracking-to-new-product-page-and-old-subscribe-page-for-a-b-test)
=> CTA tracking for Digital pack product page

conf/PROD.public.conf
Reverts guardian/support-frontend#772
It's fixed now
=> Revert "Switch PayPal off while it is broken"

app/wiring/GoogleAuth.scala, build.sbt
Version bump of `"com.gu" %% "play-googleauth"` to address Snyk issues.
=> bump play-googleauth; update google auth config

assets/helpers/abTests/abtestDefinitions.js
The seed of this test should not be the same as any of the other tests, so I'm changing it to be different from the other tests.
=> Change the seed of sign in flow test

build.sbt
As part of our obligation to protect our systems, we need to fix all high severity vulnerabilities.  There is a patch available so I am suggesting to update the library concerned.  Details at:
https://snyk.io/org/the-guardian-cuu/project/013f590b-0d03-4657-9bda-04e1712eb955/
Pull in https://github.com/guardian/identity-play-auth/pull/22
as it contains the fixed dep.
=> fix snyk issue

package.json, yarn.lock
To keep webpack updated to the latest version.
* `yarn.lock`
* `package.json`
=> Bumping Webpack up to the latest version

assets/helpers/tracking/googleTagManager.js
Add a function for sending GA events
=> Add a function for sending GA events

assets/components/svgs/windrush.jsx, assets/components/svgs/windrushZuck.jsx, assets/helpers/theGrid.js, assets/pages/digital-subscription-landing/components/independentJournalismSection.jsx, assets/pages/digital-subscription-landing/components/independentJournalismSection.scss
Because we feel it more accurately represents the impact The Guardian is trying to achieve with its journalism.
=> Use Windrush svg on the Digital Pack page

assets/helpers/internationalisation/currency.js, assets/helpers/tracking/googleTagManager.js
* Always take the currency from the query param if present
* Contribution amount is a float not an int
=> Fix a couple of tracking issues

assets/helpers/tracking/googleTagManager.js
We are adding [Google Analytics Enhanced Ecommerce tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce) to the site to allow us to carry out more advanced analysis purchase behaviour as well as using revenue as objectives in Google Optimize tests.
=> Add GA enhanced ecommerce purchase tracking

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx, assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/containers/contributionPaymentCtasContainer.js, assets/pages/support-landing/components/contributionPaymentCtasContainer.js
This PR creates a test that sends half of the audience to the guest checkout flow ([PR with guest checkout implementation here](https://github.com/guardian/support-frontend/pull/796)).
=> Guest checkout for Recurring Contributions test

app/views/main.scala.html, assets/helpers/subscriptions.js, assets/helpers/utilities.js
Adding a polyfill for `Number.isInteger`, follow-up from @joelochlann's suggestion in #845.
- Added `Number.isInteger` to the polyfill request.
- Deleted custom `isInteger` function.
=> Polyfill Number.isInteger

app/codecs/CirceDecoders.scala, app/services/stepfunctions/RegularContributionsClient.scala, build.sbt
To bring this project up to date with the latest version of support-models.
* Use the latest version of support models
* Add encoders/decoders for new ProductTypes
* Remove unused CompletedState codec
=> Use the latest version of support-models

app/views/newMain.scala.html, app/views/newPaymentFlow.scala.html, conf/CODE.public.conf, conf/DEV.public.conf, conf/PROD.public.conf
This is enough to get me started with the CSS. This HTML can already be tested for a11y if necessary. It is also a good opportunity to make sure all the content that will be displayed in this page is present, before layers of style and interaction mess it all up.
Currently missing afaik:
=> Payment flow: basic HTML structure

app/views/newPaymentFlow.scala.html
Couple of small validation attributes that will later be completed with more involved validation, e.g. _`Other amount` is required if `Other` is checked_.
=> Payment flow: validation attributes

app/views/newPaymentFlow.scala.html
Small one to link an error message to its corresponding input field.
=> Payment flow: add validation error markup

app/views/newPaymentFlow.scala.html
Initial markup for the new country selector.
=> Payment Flow: Add country selector

app/views/newPaymentFlow.scala.html, public/assets-new-ui/styles.css
To fix a few rendering issues:
- Add a missing class on an input field
- Hide the spinner on `input[type="number"]` by default
=> Small fixes

assets/helpers/flashSale.js
To support the flash sale coming up.
[**Trello Card**](https://trello.com/c/3wVpGbeA/1751-voucher-home-delivery-flash-sale-updates)
* Updated the dates of the flash sale period  
* Switched the flash sale to be paper and paper + digital
* Updated the promo codes for paper and paper + digital
During flash sale period:
Outside flash sale period:
=> Change dates for upcoming flash sale.

app/cookies/RecurringContributionCookie.scala
Simplify logic.
[**Trello Card**](https://trello.com/c/LIzM8Rza/702-clean-up-after-https-githubcom-guardian-support-frontend-pull-849)
=> simplify logic for recurring contribution cookie

app/services/stepfunctions/RegularContributionsClient.scala
In response to: https://github.com/guardian/support-frontend/pull/856#pullrequestreview-146809714
=> Simplify checkout success/failure polling logic 

assets/helpers/tracking/optimize.js
To enable us to run more than 5 Google Optimize tests concurrently we are going to add 2 GO containers, one for the Simple & Coherent team and one for the Contributions team. This PR tells support-frontend to run tests from both containers.
=> Multiple optimize containers

assets/pages/contributions-landing/newContributionsLanding.jsx, assets/pages/contributions-landing/newContributionsLanding.scss
Moving the form into React-land so we can move on and wire the rendering with actual server-side logic.
TODO
I will add logic in follow-up PRs, just want to get the rendering done so it's out of the way.
[**Trello Card**](https://trello.com/c/CrXQYkiX/748-npf-contribution-form-in-react)
=> Add form to component

assets/pages/contributions-landing/newContributionsLanding.scss
=> Fix var name

app/controllers/Application.scala, app/views/newMain.scala.html, app/views/newPaymentFlow.scala.html, app/views/newThankYou.scala.html, conf/routes, public/assets-new-ui/styles.css
Getting the markup and styles done for the new thank you page.
The focus in this PR is purely semantics and styles, the follow-up will be moving this into React-land and wiring the logic to display the proper content based on the values submitted in the form.
Alas I don't have the images required to display the social links and a few other things, @Amohkhan will provide when he's available.
[**Trello Card**](https://trello.com/c/EKUSANZt/714-npf-add-thank-you-page)
=> Add temporary "thank you" page

assets/pages/regular-contributions/components/contributionsCheckoutContainer/contributionsCheckoutContainer.js, assets/pages/regular-contributions/components/formFields.jsx, assets/pages/regular-contributions/components/marketingConsentContainer.jsx, assets/pages/regular-contributions/helpers/checkoutFormFieldsSelector.js, assets/pages/regular-contributions/regularContributionsReducer.js
There were some confusingly named types and some old practices being used in this file.
- Renamed types for consistency with the rest of the codebase.
- Switched to object spread syntax.
=> Tidy Up Regular Contributions Reducer

assets/components/directDebit/directDebitForm/directDebitForm.jsx, assets/components/directDebit/directDebitPopUpForm/directDebitPopUpForm.jsx, assets/components/featureList/featureList.jsx
These disable comments aren't needed.
- Removed three linter disable comments.
=> Remove Unnecessary Linter Disable Comments

assets/pages/new-contributions-landing/components/ContributionPayment.jsx
My last PR was marked green but a previous PR of mine was merged meanwhile and it contained a conflicting change.
* Change 1
* Change 2
=> Fix cross merge

assets/components/page/page.jsx, assets/components/svgs/contributionsBgDesktop.jsx, assets/components/svgs/contributionsBgMobile.jsx, assets/helpers/contributions.js, assets/pages/new-contributions-landing/components/ContributionAmount.jsx, assets/pages/new-contributions-landing/components/ContributionBackground.jsx, assets/pages/new-contributions-landing/components/ContributionPayment.jsx, assets/pages/new-contributions-landing/components/ContributionThanks.jsx, assets/pages/new-contributions-landing/contributionsLanding.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss, assets/pages/new-contributions-landing/contributionsLandingReducer.js
Best to look at each commit separately, using the Trello card as a guide. The only thing that is missing from the card is that the background images had to be removed for a fair test. I did that and replaced them with plain circles as per @Amohkhan 's design. Also the background between the form and thank you pages changes.
[**Trello Card**](https://trello.com/c/OdiSJB7B/827-npf-last-design-copy-changes)
=> Final design changes

assets/components/contributionsThankYou/contributionsThankYouPage.jsx, assets/helpers/legal.js, assets/pages/oneoff-contributions/oneoffContributions.jsx, assets/pages/regular-contributions/components/contributionsThankYouPageContainer.jsx, assets/pages/regular-contributions/regularContributions.jsx
Have correct links for AU version of the site. 
[**Trello Card**](https://trello.com/c/HQnwFxBH/607-australian-terms-and-conditions)
* Sets t&cs link to au version
* Have correct contact email on au thank you page (by passing in the country group id)
=> australia updates

assets/helpers/contributions.js
[**Trello Card**](https://trello.com/c/8uOfS30e/823-change-amounts-in-australia-nz)
For NZ and AU
* Monthly min --> $10
* Monthly max --> $200
=> updates au/nz monthly amounts

assets/pages/new-contributions-landing/components/ContributionAmount.jsx, assets/pages/new-contributions-landing/components/ContributionSubmit.jsx, assets/pages/new-contributions-landing/components/ContributionThanks.jsx, assets/pages/new-contributions-landing/contributionsLanding.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss, assets/pages/new-contributions-landing/contributionsLandingActions.js, assets/pages/new-contributions-landing/contributionsLandingReducer.js
Addresses the points in the Trello card. Each commit handles one item. The outstanding item is because there is no SVG icon for other currencies (pound, euro). cc @Amohkhan 
[**Trello Card**](https://trello.com/c/akWdWS2N/852-npf-minor-ui-fixes)
=> NPF: a few design fixes

app/controllers/Subscriptions.scala, assets/pages/digital-subscription-landing/components/productBlock.jsx, assets/pages/premium-tier-landing/components/independentJournalismSection.jsx, assets/pages/premium-tier-landing/components/independentJournalismSection.scss, assets/pages/premium-tier-landing/components/premiumTierLandingHeader.jsx, assets/pages/premium-tier-landing/components/priceCtaContainer.jsx, assets/pages/premium-tier-landing/components/productBlock.jsx, assets/pages/premium-tier-landing/premiumTierLanding.jsx, assets/pages/premium-tier-landing/premiumTierLanding.scss, conf/routes, public/robots.txt, webpack.common.js
To create a placeholder page for the new premium tier product page.
[**Trello Card**](https://trello.com/c/cyzK7snY/1900-premium-app-product-page-skeleton-all-regions)
* Add new routes
* Create new page & components - this is a copy of the digipack page at the moment
* Add the new routes to the `robots.txt` file.
* Update some copy on the digipack page
=> Premium tier product page skeleton

assets/components/contributionPaymentCtas/contributionPaymentCtas.jsx, assets/helpers/abTests/abtestDefinitions.js, assets/pages/contributions-landing/containers/contributionPaymentCtasContainer.js, assets/pages/support-landing/components/contributionPaymentCtasContainer.js
The test has completed, so we can turn off the test and remove the test code.
=> Turn off guest checkout test

assets/components/headers/new-header/Header.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss
=> NPF: Fix country selector in Safari

assets/helpers/paymentIntegrations/readerRevenueApis.js, assets/pages/new-contributions-landing/components/ContributionForm.jsx, assets/pages/new-contributions-landing/contributionsLandingActions.js
This actually puts the Direct Debit details through to the recurring payment endpoint.
It works, but could be cleaner. There are some TODO comments around things I'm not happy with - would appreciate any advice on those!
=> NPF: direct debit payment

assets/helpers/internationalisation/contributions.js, assets/pages/new-contributions-landing/components/ContributionThanks.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss
Font and text updated as per documented in the Trello card.
[**Trello Card**](https://trello.com/c/U8ggGUNJ/885-npf-landing-page-interaction-design-copy-tweaks-2-2)
=> NPF: two small design fixes

assets/helpers/user/userReducer.js, assets/pages/new-contributions-landing/components/ContributionForm.jsx, assets/pages/new-contributions-landing/contributionsLandingReducer.js
~~Cause I wanted to raise the 1000th PR against support frontend~~
This PR gives the `done` variable in the state a more descriptive name, as lots of things can be "done" on this page so it was a bit ambiguous without looking at how it was used in the code. 
@joelochlann @Mullefa @regiskuckaertz @Ap0c @rupertbates @johnduffell
=> Rename "done" to "paymentComplete" in page state for NPF

assets/pages/new-contributions-landing/components/ContributionThankYouContainer.jsx, assets/pages/new-contributions-landing/contributionsLandingReducer.js
This guards us against not dealing with all thank you page stages
=> Add thankYouPageStageMap type

prout/seen.md
This should be more helpful than just linking to the test code.
=> Link to post deployment test wiki section from Prout message

build-tc, yarn.lock
Updates the teamcity yarn version and updates the lockfile to have integrity checks as they are added automatically on newer versions of yarn
[**Trello Card**](https://trello.com/c/l25l67no/1492-bump-team-city-yarn-version)
=> Update yarn version

assets/helpers/subscriptions.js
We need to update this pricing on Wednesday morning, so this PR is just getting things ready.
[**Trello Card**](https://trello.com/c/9RFRRpem/1980-update-pricing-on-uk-subs-landing-page-for-the-support-site-just-before-switchover)
* Update standard pricing
=> GW copy update for subscriptions landing page

app/config/StringsConfig.scala, app/controllers/Application.scala, app/controllers/Subscriptions.scala, app/views/main.scala.html, app/wiring/Controllers.scala, conf/strings.conf
Marketing asked us to improve the SEO of the digipack page, this PR adds the following changes:
[**Trello Card**](https://trello.com/c/PQeyeXKJ/1933-improve-support-pages-seo)
- Update page title info as per recommendation from Chris
- Update page metadata as per recommendation from Chris
- Add a canonical meta tag
- Add canonical href lanf links
N/A
=> Improve SEO on digipack page

assets/helpers/theGrid.js
Keep the Guardian Weekly packshot up to date 😎 
[**Trello Card**](https://trello.com/c/Ohg6ocAj/2007-update-gw-packshots)
* Update the Guardian Weekly packshot
=> Update packshot for Guardian Weekly

assets/components/introduction/investIntroduction.jsx, assets/components/introduction/investIntroduction.scss, assets/components/subscriptionsByCountryGroup/components/digitalSection.jsx, assets/components/subscriptionsByCountryGroup/components/internationalSection.jsx, assets/helpers/theGrid.js, assets/pages/subscriptions-landing/subscriptionsLanding.jsx, assets/pages/subscriptions-landing/subscriptionsLanding.scss, assets/stylesheets/gu-sass/breakpoints.scss, assets/stylesheets/gu-sass/colours.scss
To add a new header to the subscribe page to match the current marketing campaign
[**Trello Card**](https://trello.com/c/J5PY6pIm/1824-update-header-on-subscriptions-landing-pages-for-september-campaign)
=> New subscribe header

assets/components/paymentButtons/payPalExpressButton/payPalExpressButton.jsx, assets/components/paymentButtons/payPalExpressButton/payPalExpressButtonNewFlow.jsx, assets/helpers/paymentIntegrations/newPaymentFlow/payPalExpressCheckout.js, assets/helpers/paymentIntegrations/payPalExpressCheckout.js, assets/pages/new-contributions-landing/components/ContributionForm.jsx, assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx, assets/pages/new-contributions-landing/components/ContributionSubmit.jsx, assets/pages/new-contributions-landing/contributionsLandingActions.js
This was branched off #1036, so merging into a branch rather than master
cc @jranks123
=> Take account of amount in PayPal recurring

app/controllers/PayPalOneOff.scala, assets/helpers/routes.js, assets/pages/new-contributions-landing/components/ContributionForm.jsx, conf/routes
Successful paypal one-off contribution redirects to:
=> Use new thankyou page for single contributions

assets/helpers/paymentIntegrations/newPaymentFlow/stripeCheckout.js, assets/pages/new-contributions-landing/contributionsLandingInit.js
So the stripe library is loaded once 😎
* Removes `loadStripe` from loop
=> load stripe once not thrice

assets/components/headers/new-header/Header.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss, assets/stylesheets/gu-sass/helpers.scss
🎨Consistent branding / design across dotcom and support. 
If you have a comment about the design, please speak to @ionamckendrick @Amohkhan @blongden73 
[**Trello Card**](https://trello.com/c/VBkTI0qr/89-npf-ui-tweaks-to-landing-page)
Tracked in commits. The drop down menu still needs some further styling but will address in a follow up PR.
=> css tweaks

assets/components/svgs/information.jsx, assets/pages/new-contributions-landing/components/marketingConsent.jsx, assets/pages/new-contributions-landing/contributionsLanding.scss
A small update to the message below the "Sign me up" button on thank you page
[**Trello Card**](https://trello.com/c/8EC5132z/105-npf-update-sign-up-message-style)
=> Update signup info message

assets/components/directDebit/directDebitForm/directDebitForm.jsx
To be compliant with GoCardless
[**Trello Card**](https://trello.com/c/rpu5BTvg/79-npf-have-we-checked-the-wording-for-direct-debit-are-we-okay-to-ship-or-do-they-need-to-approve-it)
* Name --> Account Name
* Adds blurb about GoCardless and link to their privacy policy.
=> gc amendments

assets/pages/new-contributions-landing/contributionsLanding.scss
[**Trello Card**](https://trello.com/c/EA3KhWmf/104-npf-css-drop-down-menu-should-match-styling-of-edition-picker-on-dotcom)
* Radio buttons closer
* Country selector styling closer to dotcom.
=> css tweaks 2

assets/pages/new-contributions-landing/components/ContributionThankYouPasswordSet.jsx
Fix another button that's actually a link on thank you page.
=> change another button to cta

.gitignore
I need to define some custom project settings to avoid the ts formatter going wild and to do that I need to not commit my workspace file!
=> gitignore vscode settings

assets/components/contributionsThankYou/contributionsThankYouPage.jsx, assets/components/contributionsThankYou/emailConfirmation.jsx, assets/components/survey/contributionsSurvey.jsx, assets/components/survey/contributionsSurveySection.jsx, assets/components/survey/survey.scss, assets/components/survey/surveySection.scss, assets/pages/oneoff-contributions/oneoffContributions.scss, assets/pages/regular-contributions/regularContributions.scss
Re-enable the survey, this time for video testimonials
[**Trello Card**](https://trello.com/c/c1h9rIJu/112-re-deploy-testimonial-survey)
=> Re-enable survey

assets/components/svgs/information.jsx, assets/helpers/externalLinks.js, assets/pages/digital-subscription-checkout/components/checkoutStage.jsx, assets/pages/digital-subscription-checkout/components/thankYouContent.jsx, assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
Updated the structure of the copy, and added some SVGs.
[**Trello Card**](https://trello.com/c/SM61ZIPe/2015-update-existing-thank-you-page-with-new-copy-and-design)
- Added a class to the information SVG.
- Added a link to the identity email preferences page.
- Tweaked structure of the copy.
- Added newsletter and information SVGs to the email preferences section.
Mobile | Tablet | Desktop
-|-|-
=> Tweak Digital Subs Thank You Layout and Copy

app/controllers/Subscriptions.scala, assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx, assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss, conf/routes, public/robots.txt, webpack.common.js
Humble beginnings
[**Trello Card**](https://trello.com/c/SGDARHeu/2055-gw-product-page-skeleton)
=> Route for new GW landing page

assets/pages/new-contributions-landing/components/MustSignIn.jsx
So that the link works even when you click on the `<span>` within the `<div>`
=> Do not use event.target.href as URL

assets/helpers/tracking/ophanComponentEventTracking.js, assets/pages/new-contributions-landing/components/MarketingConsent.jsx, assets/pages/new-contributions-landing/components/MustSignIn.jsx, assets/pages/new-contributions-landing/components/SetPassword/SetPasswordForm.jsx, assets/pages/regular-contributions/components/marketingConsentContainer.jsx, assets/pages/regular-contributions/components/mustSignIn.jsx
=> Click tracking for set password, marketing consents, must sign in on old flow

assets/pages/new-contributions-landing/contributionsLanding.scss
Because otherwise it doesn't feel like you can interact with it
=> Pointer cursor on country dropdown

app/controllers/Subscriptions.scala, conf/routes, public/robots.txt
=> move /subscribe/guardian-weekly to /subscribe/weekly

assets/stylesheets/gu-sass/gu-sass.scss
Darkening the letter colour on the contributions roundel.
- Fill colour update.
=> Roundel Tweaks

app/views/main.scala.html
Adds a class for the header tweaks, not yet used.
- Added a class to the body.
=> [WIP] Header Tweaks Class

app/controllers/Application.scala, app/controllers/PayPalOneOff.scala, app/controllers/SiteMap.scala, assets/components/headers/new-header/Header.jsx, assets/helpers/routes.js, assets/pages/new-contributions-landing/contributionsLanding.jsx, assets/pages/new-contributions-landing/contributionsLandingActions.js, conf/routes, public/robots.txt
The NPF did well, we're moving all users over.
Note - there is a lot of cleanup to be done later
* Change 1
* Change 2
=> Switch to NPF

assets/components/survey/contributionsSurvey.jsx
An updated survey for the 1m launch
[**Trello Card**](https://trello.com/c/rn5nmyWW/159-update-survey-link-once-1mm-launched)
=> DO NOT MERGE YET - Update survey url for 1m

assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
Forgot to push this in #1175, sorry!
=> Grab bag of GW updates  – shorter copy

assets/components/countryGroupSwitcher/countryGroupSwitcher.scss
It looked like this (not my screenshot)
This makes it look like this
=> Fix country select box on windows

assets/components/headingBlock/headingBlock.scss, assets/components/leftMarginSection/leftMarginSection.scss, assets/components/productPage/productPageContentBlock/productPageContentBlock.scss, assets/components/productPage/productPageTextBlock/productPageTextBlock.scss, assets/pages/weekly-subscription-landing/components/weeklyFeatureList.scss, assets/pages/weekly-subscription-landing/components/weeklyFormLabel.jsx, assets/pages/weekly-subscription-landing/components/weeklyFormLabel.scss, assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx, assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.scss, assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js, assets/stylesheets/gu-sass/typography.scss
- Make fonts smaller on smaller breakpoints
- Use full links for T&C's
- Use full currency symbols for intl dollars
- Use new style price cards
- Tweak sizes to fix grid 
- _More to come_
[**Trello Card**](https://trello.com/c/TsZ9rxCE/2076-final-gw-page-touches)
=> Minor weekly tweaks

public/robots.txt
=> Take new GW page out of robots.txt

assets/helpers/abTests/abtestDefinitions.js
Whoops! fixes something stupid from #1193
=> ENGAGMENT!??

test/selenium/contributions/new_flow/pages/ContributionsLanding.scala
=> Correct id on contribution tab

assets/pages/new-contributions-landing/components/ContributionFormFields.jsx, assets/pages/new-contributions-landing/components/ContributionState.jsx
say 'province' not 'state' on the Canada contribution page
US:
Canada:
=> Canada has provinces

app/controllers/Subscriptions.scala
This is a bit awkward but I forgot to pass these in.
=> Actually add SEO tags on GW page

assets/helpers/checkoutForm/checkoutForm.js, assets/helpers/checkoutForm/onFormSubmit.js, assets/helpers/contributions.js
If someone is a recurring contributor, we shouldn't block them from making a one-off contribution. 
That this PR has to do everything twice is exactly why I've made [this PR](https://github.com/guardian/support-frontend/pull/1209)
=> Allow existing recurring contributors to make single contributions

assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
Marketing request and it was a oneliner
=> Add subscribe/weekly#benefits url

assets/components/footer/footer.jsx, assets/components/legal/contribLegal/contribLegal.jsx, yarn.lock
=> Add privacy terms to NPF footer

assets/helpers/abTests/abtestDefinitions.js
Amanda's requested we remove this one
=> Remove a poorer-performing variant

assets/components/radioToggle/radioToggle.jsx
The `label` has an `htmlFor` on it.
- Removed unecessary ESLint disable.
=> Removed Unnecessary ESLint Disable

assets/helpers/flashSale.js, assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
Following the A/B that confirmed positive impact on conversion rates, we're rolling it out to everyone.
[**Trello Card**](https://trello.com/c/R64yrpsc)
=> Rolling out the countdown timer to everyone

app/controllers/Subscriptions.scala, app/models/ZuoraCatalog/ZuoraCatalog.scala, app/views/ViewHelpers.scala, app/views/main.scala.html, assets/components/productPage/productPagePlanForm/productPagePlanForm.jsx, assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.jsx, assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.scss, assets/components/productPage/productPagePlanForm/productPagePlanFormPrice.jsx, assets/helpers/subscriptions.js, assets/pages/paper-subscription-landing/components/form.jsx, assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx, assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js, assets/pages/weekly-subscription-landing/components/weeklyForm.jsx
Display is ugly because this is meant to be merged after #1228, all prices are a-ok 👌
Bonus! The new boxes ripple down to the weekly page, here's how they look:
=> WIP: Display prices and savings

assets/components/productPage/productPageContentBlock/productPageContentBlock.scss, assets/helpers/externalLinks.js, assets/pages/paper-subscription-landing/components/form.jsx, assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx, assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.scss, assets/pages/paper-subscription-landing/paperSubscriptionLandingPageActions.js, assets/pages/paper-subscription-landing/paperSubscriptionLandingPageReducer.js
Also slightly fix the side images bc they were too big
=> Paper subs - links to checkout flow

assets/components/productPage/productPageContentBlock/productPageContentBlock.jsx, assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
The secondary feature is themed yellow (primary feature is blue). This is for the showcase page redesign.
=> add a secondary feature

assets/components/productPage/productPageContentBlock/productPageContentBlock.scss
=> content-block--grey shouldn't have (visible) borders

assets/stylesheets/gu-sass/typography.scss
=> render strong elements as bold

assets/components/subscriptionBundles/digitalPack.jsx, assets/components/subscriptionBundles/premiumTier.jsx
Title Case
[**Trello Card**](https://trello.com/c/Hy1lZa32/2095-digital-pack-flash-sale)
* Change 1
* Change 2
=> Title Case

assets/helpers/theGrid.js
Use the correct hero image for the showcase page.
=> update showcase hero image

app/controllers/Subscriptions.scala, assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
SEO, baby!
[**Trello Card**](https://trello.com/c/oEuRfoyO/1977-seo-requirements-for-print-product-page)
**Before:**
**After:**
=> Apply meta description and correct <h1> to print landing page

assets/helpers/externalLinks.js
Testing the new page.
* Change 1
* Change 2
=> update print subscription link to new page

assets/components/productPage/productPageButton/productPageButton.scss, assets/components/productPage/productPageContentBlock/productPageContentBlock.scss, assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.scss, assets/components/productPage/productPageTabs/productPageTabs.scss, assets/helpers/theGrid.js, assets/pages/paper-subscription-landing/components/content.jsx, assets/stylesheets/gu-sass/colours.scss
=> Little tweaks

build-tc
Bumping the Yarn version.
- Bump Yarn to 1.12.3.
=> Bump Yarn Version To 1.12.3

assets/helpers/abTests/abtestDefinitions.js
Have checked and everything seems to be working, so I'm going to turn on the test for everyone
=> Turn on Apple Pay test for all users

assets/pages/new-contributions-landing/components/StripePaymentRequestButton.jsx
Some temporary client-side tracking whilst we get the proper tracking in order
=> Add some tracking around Apple Pay

assets/pages/new-contributions-landing/components/StripePaymentRequestButton.jsx
My [previous PR](https://github.com/guardian/support-frontend/pull/1307) used the wrong tracking function. This PR amends it
=> Use correct tracking function

assets/components/productPage/productPageButton/productPageButton.jsx, assets/components/productPage/productPageContentBlock/productPageContentBlock.scss, assets/components/productPage/productPageContentBlock/productPageContentBlockOutset.jsx
Some parts of `ProductPage` are not super intuitive at first. Inline documentation to the rescue!
=> Document seemingly weird bits of productPage

assets/helpers/theGrid.js, assets/pages/digital-subscription-landing/components/productBlock.jsx
Keeping things up to date 👌 
[**Trello Card**](https://trello.com/c/AzXNLghz/2122-update-daily-edition-image-on-the-digital-pack-product-page)
* Update the digital edition packshot
before: 
after:
=> Update daily edition packshot

assets/helpers/internationalisation/contributions.js
New copy for the US end of year campaign
[**Trello Card**](https://trello.com/c/asEUnxam/272-update-us-landing-page-copy)
=> Update US eoy copy

assets/pages/new-contributions-landing/components/ContributionThankYou.jsx, assets/pages/new-contributions-landing/components/ContributionThankYouPasswordSet.jsx
We are temporarily removing the survey link. It will be back.
=> Remove survey from thank you page

nginx/support.conf, setup.sh
The SSL certificate we use for local development is about to expire, this PR updates it to a new one.
=> Update the gulocal.com ssl certificate

build.sbt
fix snyk issues in jackson-databind - [project in snyk](https://app.snyk.io/org/the-guardian-cuu/project/013f590b-0d03-4657-9bda-04e1712eb955/)
[**Trello Card**](https://trello.com/c/PM8I1TCU/253-snyk-vulnerabilities-payment-api-zuora-auto-cancel-support-works-support-frontend)
Seems to work OK locally. Not expecting any major issue though.
=> update jackson (and AWS library) to latest - snyk

assets/pages/digital-subscription-checkout/digitalSubscriptionCheckoutReducer.js
Needed for AB test. Can use `&period=Annual` on the URL to switch to Annual.
[**Trello Card**](https://trello.com/c/C5ZGMHaX/2160-digital-pack-annual-subscription-checkout-link)
=> Set a default billing period in the DP checkout from the URL

.storybook/addons.js, .storybook/config.js, .storybook/decorators/withCenterAlignment.js, .storybook/webpack.config.js, assets/components/button/_sharedButton.jsx, package.json, stories/button.jsx, yarn.lock
(don't freak out about the line count! it's the yarn lockfile)
So we can have a canonical place to display, build, and test shared UI components in. The goals of this are:
- To have a unified point of reference for this stuff for dev, visual design and uxd to refer to and avoid rebuilding.
- To allow visual design to propose (or ship) enhancements at a component level (for example @zeftilldeath fixing all the hover states of the buttons, mine are atrocious)
- To allow me, Laura, to play around with setting up storybook and knobs.
[[Read more on storybook here]](https://storybook.js.org/)
Still quite early stages as this is checkout week. Use`yarn storybook` to run.
**No** that's a cursed word, it's a tool for UI development that I'm keen for us to start using, let's see how we use it and …
=> Install storybook

assets/pages/new-contributions-landing/contributionsLanding.scss
=> Fix alignment of country dropdown

assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
=> International countries dont have images and this crashes the ty page

assets/components/productPage/productPageTextBlock/productPageTextBlock.jsx, assets/components/productPage/productPageTextBlock/productPageTextBlock.scss, assets/components/productPage/productPageTextBlock/productPageTextBlockOrderedList.jsx
We needed a `<ol>` component so I made one! 
[**Trello Card**](https://trello.com/c/ecK4Jpqq/2146-print-product-page-optimisation)
* Added component jsx and scss
=> Ordered list component

assets/helpers/abTests/abtest.js
I accidentally left a few console.logs in [this PR](https://github.com/guardian/support-frontend/pull/1419) and got over excited and shipped it!
@jranks123
=> remove console.logs!!

app/views/test.scala.html
better copy for https://github.com/guardian/support-frontend/pull/1419
I mentioned the copy was on its way and here it is.
I also plan to do a fade in transition so it doesn't flash briefly on a fast connection as I feel this will affect the test negatively due to it looking broken.
@ionamckendrick @jranks123
=> Patience message

cloud-formation/cfn.yaml
The app needs permissions to access the promotions dynamo db tables.
=> Allow the app to access the promotions Dynamo tables

assets/helpers/flashSale.js, assets/helpers/theGrid.js, assets/pages/paper-subscription-landing/components/hero/hero.jsx, assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
Adding updates to the hero for the Joy of Print flash sale. 
[**Trello Card**](https://trello.com/c/ecK4Jpqq/2146-print-product-page-optimisation)
* Updating 'savings badge' copy and colour. There's some magic numbers here due to extra characters being added in the copy. Please don't judge me!
* I snuck in an updated voucher image that marketing has supplied.
=> Hero updates for flash sale

assets/pages/showcase/components/ctaContribute.jsx, assets/pages/showcase/components/ctaSubscribe.jsx, assets/pages/showcase/components/otherProduct.jsx, assets/pages/showcase/showcase.scss
Couple of minor thingies i spotted, and since we are 100%ing this next week I wanted to make sure it was all nice.
* The buttons are using appearance modifiers instead of deep css nesting
* The svgs are aligned with the text
=> Fix some stuff in the showcase page that had been nagging at me forever

assets/helpers/page/page.js
We don't currently track Optimize tests properly on pages which don't use Redux, this PR fixes this.
[**Trello Card**](https://trello.com/c/4kEtf6ia/2181-ab-test-tracking)
=> Optimize tracking fixes

app/admin/settings/SettingsProvider.scala
=> Reduce logging in S3SettingsProvider

assets/components/button/button.scss, assets/components/contributionPaymentCtas/contributionPaymentCtas.scss, assets/components/ctaLink/ctaLink.scss, assets/components/directDebit/directDebitForm/directDebitForm.scss, assets/components/headers/header/header.scss, assets/components/payPalContributionButton/payPalContributionButton.scss, assets/components/paymentButtons/directDebitPopUpButton/directDebitPopUpButton.scss, assets/components/paymentButtons/stripePopUpButton/stripePopUpButton.scss, assets/pages/oneoff-contributions/oneoffContributions.scss, assets/stylesheets/gu-sass/colours.scss, assets/stylesheets/gu-sass/layout.scss
To realise the perfect button. 
* Updated css styling for buttons including variables and animation
* Updated green-main
=> Tweaked button scss

assets/pages/new-contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx
Quick bit of tracking to see the values that are coming through in the methodName part of the payment response.
=> Track Stripe Payment Request Button payments method name

assets/components/promotionSummary/promotionSummary.jsx, assets/helpers/productPrice/productPrices.js, assets/pages/digital-subscription-checkout/helpers/paymentProviders.js
We noticed a few problems with the Digital pack checkout:
* Discounts applied to the Annual price are described as being a percentage discount on the Monthly price but the actual discount is less because there is already a discount built in for paying annually.
* We were passing the wrong price to Stripe
=> Digital pack tweaks

cloud-formation/cfn.yaml
Code needs to be able to access the dev catalog on S3
=> Give the app access to the dev S3 catalog

.storybook/config.js
With #1471 i forgot to include the base styles in storybook and it looks a bit off. This remarkably short PR for my standards fixes it
=> Fix CSS in storybook

assets/helpers/externalLinks.js
The current setup of our Digital Pack checkout experiment is problematic, because it is not recording the behaviour of users who drop out of the flow after hitting the Identity sign in/sign up step. This is likely to unfairly skew the result in favour of the new flow.
In order to work around this problem, this PR uses the OptimizeExperiments array to determine whether a user should see the variant or not. If they should, we flip the links on the landing page so that they point to the new flow. This allows us to set up a new test which uses the Digital Pack landing page as the entry point.
All users will now be served a page on support.theguardian.com _before_ any redirects to identity occur, which should ensure that a user's session is included in the experiment, even if they drop out of …
=> Set up AB test for Digital Pack Checkout links

assets/helpers/flashSale.js, assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, assets/pages/subscriptions-landing/components/featuredProductAb.jsx
=> Fix countdown timer

assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
=> There was a bit of padding missing in the DP page after the header harmony PR

app/utils/QueryStringUtils.scala
This will put everyone in the new design variant. 
Clean up PR to follow
=> Put variant in formDesignTest to 100%

assets/pages/new-contributions-landing/contributionsLanding.scss
Left the form AB looking transparent before
=> Rename last brightness- vars

assets/components/spinners/animatedDots.scss
Keeping up to date with the new color naming
=> Fix color of animated dots

support-models/build.sbt
To start setting the custom metric 'successfulsubscriptionSignUp' in GA acquisition events
[**Trello Card**](https://trello.com/c/TUauJtUi/2137-set-custom-metric-successfulsubscriptionsignup-in-ga-acquisition-events)
=> Upgrade acquisition-event-producer

devrun-frontend.sh, support-frontend/devrun.sh
For my convenience really.
This fixes `devrun.sh`
=> Fix devrun.sh

support-workers/src/main/scala/com/gu/acquisitions/AcquisitionServiceBuilder.scala, support-workers/src/main/scala/com/gu/services/Services.scala, support-workers/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala, support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala, support-workers/src/main/scala/com/gu/support/workers/lambdas/ServicesHandler.scala, support-workers/src/test/scala/com/gu/support/workers/lambdas/SendAcquisitionEventSpec.scala
Since moving to a mono repo there have been some failing integration tests in the support-workers project. This fixes them.
=> Fix the integration tests

support-frontend/assets/components/forms/standardFields/fieldset.jsx, support-frontend/assets/components/productPage/productPagePlanForm/productPagePlanForm.jsx, support-frontend/assets/components/productPage/productPagePlanForm/productPagePlanFormLabel.jsx
Sorry, this was quite egregious at the sesh today and i wanted to fix it
=> Let screen readers announce the inputs in the product form earlier

support-frontend/assets/components/checkoutForm/checkoutForm.scss, support-frontend/assets/components/forms/customFields/radioInput.jsx, support-frontend/assets/components/forms/customFields/radioInput.scss, support-frontend/stories/form.jsx
They are beautiful and I love them
No trello card but this is off the back of #1562
=> The chonky boys!

devrun-frontend.sh, support-frontend/devrun.sh
=> Fix devrun again

support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Because Iona told me to.
|Before|After|
|----|----|
|![image](https://user-images.githubusercontent.com/2844554/53563510-253fc400-3b4c-11e9-91aa-e824e6a89a58.png)|![image](https://user-images.githubusercontent.com/2844554/53563480-0e00d680-3b4c-11e9-9c8e-f3cc5da228f6.png)|
=> Change font size on landing page copy

support-frontend/assets/helpers/abTests/abtestDefinitions.js, support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/new-contributions-landing/components/ContributionForm.jsx, support-frontend/assets/pages/new-contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLandingActions.js, support-frontend/assets/pages/new-contributions-landing/contributionsLandingReducer.js
the test was unsuccessful. This PR removes the test from the codebase
=> Turn off Stripe Payment Request Button improvement test

support-frontend/assets/pages/showcase/components/ctaContribute.jsx, support-frontend/assets/pages/showcase/showcase.scss
Contributions needed some copy updated and I took the opportunity to fix a layout bug on the subscribe panel. 
* Copy update
* Hacky(ish) layout fix
=> Copy update and part layout fix

support-frontend/assets/components/checkout/checkout.scss, support-frontend/assets/components/checkoutForm/checkoutForm.jsx, support-frontend/assets/components/checkoutForm/checkoutForm.scss, support-frontend/assets/components/headers/header/header.scss, support-frontend/assets/components/leftMarginSection/leftMarginSection.scss
=> Fix several grid misalignments

support-frontend/assets/components/priceLabel/priceLabel.jsx, support-frontend/assets/helpers/productPrice/paperProductPrices.js, support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/paper-subscription-checkout/helpers/paymentProviders.js
So people can pay the correct amount!
UI is not final, just trying to visualize it for this PR
=> Fetch paper prices from backend

support-frontend/assets/components/headers/header/header.scss
It's very subtle but it was driving me bananas
=> Fix header's grid alignment in desktop & leftcol

support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/showcase/showcase.scss
This is part 2 of the Showcase bug fix and includes the new image. 
* Add new image
* Teeny css updates
=> Jy showcase img fix

support-frontend/assets/pages/paper-subscription-checkout/_legacyImports.scss, support-frontend/assets/pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx
To make the DD form look like this instead of completely unstyled:
=> Add missing CSS in the paper checkout

support-frontend/assets/pages/showcase/components/ctaContribute.jsx
I missed a space between 2 sentences. It's back now.
* Added a non breaking space
=> jy showcase typo

support-frontend/assets/helpers/abTests/abtestDefinitions.js, support-frontend/assets/helpers/checkouts.js, support-frontend/assets/pages/new-contributions-landing/components/ContributionTypeTabs.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js
The results of [this test](https://github.com/guardian/support-frontend/pull/1587) are in and we have made the decision to roll out the dropping of monthly contributions (for the next few weeks) in all regions except US and GB.
=> Drop monthly for everywhere except GB and US

support-frontend/assets/helpers/url.js
We're going to use the url query string to determine if the user should see a custom landing page for this campaign
=> Query param check for 'Frontline' campaign

support-workers/scripts/decode.sh
This script needs minor changes to cope with the new repo structure.
=> Fix decode.sh

support-frontend/assets/components/headingBlock/headingBlock.scss, support-frontend/assets/components/productPage/productPageHero/productPageHero.jsx, support-frontend/assets/components/productPage/productPageHero/productPageHero.scss, support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx, support-frontend/assets/pages/showcase/showcase.jsx, support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx, support-frontend/assets/stylesheets/gu-sass/typography.scss, support-frontend/stories/layout.jsx
We are trying to standardise the way Hero panels are built and hope to essentially have 2 types: 
* Default
* Campaign (this will be bespoke layout)
There have been some typography updates which required shifting DOM object around and new components. 
Only pages using the most recent versions of Product Page Hero components will get these updates. Eventually all ages will be migrated to new Hero panels.
There is more work to be done here but I need to get this initial PR out of the way to start building a new Campaign Hero panel.
[**Trello Card**](https://trello.com/c/Bs50rgUV/2277-weekly-hero-panel-design)
* Update Hero Panel components
* Update Storybook to reflect changes
Updated Hero Panel
Example blank Campaign Hero Panel
=> jy banner update pt 1

support-frontend/assets/components/productPage/productPageHero/productPageHero.scss, support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
Updates to Digital Pack Hero panel to reflect current campaign 
[**Trello Card**](https://trello.com/c/J0X4PCRe/2278-digital-pack-hero-panel-design)
* Add new hero panel
* Some Digi Pack temporary bug fixes
=> jy banner update pt2

support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
=> Living for the weekend

support-frontend/assets/pages/showcase/components/hero.scss
=> Friday? FriYAY

support-frontend/assets/components/productPage/productPageHero/productPageHero.scss, support-frontend/assets/pages/showcase/components/hero.jsx, support-frontend/assets/pages/showcase/components/hero.scss
=> Fix checkout heros

support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/weekly-subscription-landing/components/hero/hero.jsx, support-frontend/assets/pages/weekly-subscription-landing/components/hero/weeklyCampaign.scss, support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx
This PR moves the Weekly banner onto the updated format, allowing us to switch easier between _Campaign_ and _Default_ state and includes a campaign design based on current marketing material.
[**Trello Card**](https://trello.com/c/Bs50rgUV/2277-weekly-hero-panel-design-dev)
* Add SaleHeader and DefaultHeader components to Weekly page
* Add a campaign layout to hero banner for Weekly
=> Weekly banner update

support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
=> Paragraph spacing and form message background colour

support-frontend/assets/helpers/externalLinks.js
=> Fix paper checkout urls

support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.jsx, support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.scss, support-frontend/public/ticker.json
=> Ticker post goal

support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.jsx, support-frontend/assets/pages/new-contributions-landing/components/ContributionTicker/ContributionTicker.scss
Reverts guardian/support-frontend#1656
We now want to continue the campaign beyond the goal, not discourage people from giving more after the goal is reached
=> Revert "Ticker post goal"

support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.scss
Add the flash sale countdown ticker to the Digital Pack landing page.
=> Add ticker to digipack sale header

support-frontend/assets/components/legal/termsPrivacy/termsPrivacy.jsx
We've updated the goal for the Frontline campaign
=> Increase goal in Frontline T&Cs

support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
An update to the copy now that the goal has changed
[**Trello Card**](https://trello.com/c/1mhFiBKr/472-update-landing-page-tcs-for-150k-goal)
=> Update Frontline campaign copy

support-frontend/assets/helpers/tracking/acquisitions.js
We're using the campaign code `thefrontline` to calculate the ticker
=> Change frontline campaign code

support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx
=> Remove highlighted line from The Frontline landing page

support-frontend/fetch-config.sh, support-frontend/nginx/support.conf, support-frontend/setup.sh
I have recently been bestowed a new laptop and the very first thing I did right after getting the long end of my old charger into the new shorter charger with the intention of returning a shorter charger with the old laptop and keeping a long one myself, was getting `support-frontend` up and running. In the process I ran into a few quirks, mostly missing comments, I thought I could iron them out for everybody but also for me should I need to do this again.
I commented the pr!
=> minor QoL improvements to startup scripts

support-frontend/assets/components/legal/subscriptionTermsPrivacy/subscriptionTermsPrivacy.jsx, support-frontend/assets/components/subscriptionFaq/subscriptionFaq.jsx, support-frontend/assets/pages/paper-subscription-checkout/components-ty/thankYou.jsx
To better understand our users. 
[**Trello Card**](https://trello.com/c/ENjN34vd/2264-analytics)
* Add tracking to subscriptions terms page and privacy policy
* Add tracking to faq links
* Add tracking to MMA and my account links on the paper checkout thank you page
=> More onward links tracking

support-frontend/assets/components/featuredProductHero/featuredProductHero.jsx, support-frontend/assets/components/featuredProductHero/featuredProductHero.scss, support-frontend/assets/components/threeSubscriptions/threeSubscriptions.jsx, support-frontend/assets/components/threeSubscriptions/threeSubscriptions.scss, support-frontend/assets/pages/subscriptions-landing/components/featuredProductAb.jsx
This was upsetting me
Spot the differences!
=> Align subs landing page to the grid

support-frontend/assets/helpers/externalLinks.js
it was pointing to quarterly 🤭
=> Fix GW link for annual ROW subs

support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx
We are going to re-run the PayPal AB test now that we have tweaked the form a bit.
=> Update the id of the paypal test

support-frontend/assets/components/forms/customFields/radioInput.jsx, support-frontend/assets/components/forms/customFields/radioInput.scss, support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx, support-frontend/assets/components/subscriptionCheckouts/paymentMethodSelector.jsx.orig, support-frontend/assets/components/subscriptionCheckouts/subscriptionSubmitButtons.jsx, support-frontend/assets/pages/digital-subscription-checkout/components/addressForm.jsx, support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/digital-subscription-checkout/digitalSubscriptionCheckout.scss
This PR will hopefully in improve conversions on the paypal payments
[**Trello Card**](https://trello.com/c/pufad5wP/2295-paypal-optimisations)
* Add payment logo to payment radio buttons
* Moved payment button above Money Back Guarantee text
=> Digital checkout optimisations

support-frontend/assets/components/headers/header/header.jsx, support-frontend/assets/components/headers/header/headerWithCountrySwitcher.jsx, support-frontend/assets/components/headers/header/mobileMenuToggler.jsx, support-frontend/assets/components/headers/links/links.jsx, support-frontend/assets/components/headers/mobileMenu/mobileMenu.jsx, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, support-frontend/assets/pages/premium-tier-landing/premiumTierLanding.jsx, support-frontend/assets/pages/subscriptions-landing/subscriptionsLanding.jsx, support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.jsx, support-frontend/webpack.common.js
Remove non-uk links for countries that are not the uk.
[**Trello Card**](https://trello.com/c/4sK5yvgL/2238-spike-understand-how-to-better-localise-our-pages)
* Removed links for non-uk countries
* Add a country picker to the subs landing
=> Brexit header 🇬🇧💷☕️💂

support-workers/cloud-formation/src/templates/cfn-template.yaml
Allows us to complete the final point in this checklist: https://github.com/guardian/support-frontend/pull/1638.
I'm planning to merge this on Monday 25th March.
=> Remove old Step Functions

support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
=> Tweak checkout delivery wording

support-frontend/assets/components/priceLabel/priceLabel.jsx, support-frontend/assets/helpers/productPrice/productPrices.js
It was broken and not applying itself (ah types), now only the wording is broken (it's free for 1 year)
=> Fix patrons code

support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.jsx, support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.module.scss, support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.scss, support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcherContainer.js, support-frontend/assets/components/menu/menu.jsx, support-frontend/assets/components/menu/menu.module.scss
This was ongoing health work from the new header. it replaces the country switcher dropdown with a menu, like the contributions landing has
=> Clean up the country switcher

support-frontend/assets/components/subscriptionBundle/subscriptionBundle.jsx
Making Gus happy makes us all happy
=> Click on the pictures in the subs page to open them

support-workers/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
Before rolling out 'existing payment options' feature (see https://github.com/guardian/support-frontend/pull/1673 and https://github.com/guardian/support-frontend/pull/1730) we must be able to attribute acquisitions accordingly (for use in the 'Acquisitions Slicer' for example).
Wrap the `SendAcquisitionEventState` (previously what was passed through to build the `thrift.Acquisition`) along with the `RequestInfo` (which contains `accountExists` flag) in a new case class, which can be passed as the single paramater to the `AcquisitionSubmissionBuilder`... so that it can be used to add `"REUSED_EXISTING_PAYMENT_METHOD"` to the `labels` field of the acquisition event if applicable (i.e. if `accountExists` is true and hence the payment method was reused/cloned).
=> label existing payment reuse in acquisition event

support-frontend/assets/components/subscriptionCheckouts/summary.module.scss, support-frontend/assets/helpers/routes.js, support-frontend/assets/pages/paper-subscription-checkout/components-checkout/checkoutForm.jsx
Its a nice thing to do for people
=> Clarify vouchers in newspaper checkout

support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/digital-subscription-checkout/components/checkoutStage.jsx
Align this with the paper checkout
=> Product deets on DP checkout

support-frontend/assets/pages/showcase/components/hero.scss
This remove the object fit stuff.
* Remove object fit stuff
=> Whoops missed the last commit!

support-frontend/assets/components/priceLabel/priceLabel.jsx, support-frontend/assets/components/subscriptionCheckouts/summary.jsx, support-frontend/assets/helpers/productPrice/digitalProductPrices.js, support-frontend/assets/helpers/productPrice/paperProductPrices.js, support-frontend/assets/helpers/productPrice/productPrices.js
#1717 Broke the checkout for promo codes without a discount (any tracking code or free trial)
#1745 Broke any promo codes where the price with discount is 0 eg. DIGIPATRON, (because 0 is falsey)
This PR fixes both cases
=> Fix promo summary

support-frontend/.flowconfig, support-frontend/assets/helpers/productPrice/__tests__/productPricesTests.js, support-frontend/assets/helpers/productPrice/productPrices.js
The logic for whether a promotion has a discount is non-trivial mostly because of Javascript's truthiness so I've added a test.
=> Test `hasDiscount()` function with all possible inputs

support-frontend/assets/helpers/productPrice/productPrices.js
Tiny PR from running lint on the branch to fix an earlier commit.
=> Whitespace linting

support-frontend/assets/helpers/externalLinks.js, support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
We are switching over to the new Paper checkout exclusively, this PR does that.
=> Send 100% of paper checkouts to the new checkout

support-frontend/stories/header.jsx
This is an update to storybook to include the new navbar for checkout.
* Removes the 'plain' navbar (since the default is to have the navigation)
* Adds the checkout navbar
=> Add checkout nav to storybook

support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx, support-frontend/assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.jsx
#1788 caused some Flow errors in master when it was merged
=> Fix Flow errors in master from failed merge

support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx, support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.js, support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx, support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss, support-frontend/webpack.dev.js, support-frontend/yarn.lock
feat: Added marketing copy variants for paper subscriptions landing page, 
The query parameter is currently `discount`
The variants are `control, B, C, D`
[**Trello Card**](https://trello.com/c/EKVExn6b/2379-marketing-test-discount-copy)
* updated CSS in the hero 
* Add new query string to control the copy variant.
=> feat: added marketing copy variants

support-frontend/assets/components/page/page.jsx, support-frontend/assets/helpers/campaigns.jsx, support-frontend/assets/helpers/url.js, support-frontend/assets/pages/new-contributions-landing/components/ContributionFormContainer.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Preparing to launch the US campaign
[**Trello Card**](https://trello.com/c/U1GQQfeS/1049-summary-list-of-what-we-need-to-launch-us-fundraiser)
* Organizing configuration to be inside of `campaigns.jsx` including background image
* New styles for this campaign
Please note: ignore the payments types - they are configured to be single payment only on another branch. The selector will be hidden in production.
Desktop:
Tablet:
Mobile:
=> Updates for the US Campaign

support-frontend/assets/helpers/subscriptionsForms/countryPaymentMethods.js
Reverts guardian/support-frontend#1810
Do not merge until Monday!
=> Revert "Temporarily remove direct debit payment method"

support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
I think some commits didn't get linted when there was an urgent push to fix a bug. Doing this on a separate branch/PR to keep my other changes on the campaign clean.
=> Misc linting

support-frontend/assets/helpers/campaigns.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLanding.scss
Final changes for the US campaign (mostly copy, one IE styles fix)
[**Trello Card**](https://trello.com/c/U1GQQfeS/1049-summary-card-us-fundraiser)
* Updated copy
* Put in ie style fix
=> Final US campaign copy changes, fit and finish

support-frontend/assets/components/forms/label.jsx, support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx
Two copy changes
- optional = Optional
- Where should we bill you? = Your billing address
[**Trello Card**](https://trello.com/c/gfGpS141/2380-copy-updates-in-checkout)
=> copy: change in checkout forms

support-frontend/app/controllers/Subscriptions.scala, support-frontend/app/views/subscriptionCheckout.scala.html, support-frontend/app/wiring/Controllers.scala, support-frontend/assets/pages/weekly-subscription-landing/weeklySubscriptionLandingReducer.js
I broke the Weekly landing page with my last PR #1827 because it didn't have Zuora pricing information available in the page. This fixes it.
=> Fix the Guardian Weekly landing page

support-frontend/assets/helpers/existingPaymentMethods/existingPaymentMethods.js, support-frontend/assets/pages/new-contributions-landing/components/ContributionForm.jsx, support-frontend/assets/pages/new-contributions-landing/components/PaymentMethodSelector.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLandingActions.js, support-frontend/assets/pages/new-contributions-landing/contributionsLandingInit.js, support-frontend/assets/pages/new-contributions-landing/contributionsLandingReducer.js
some minor refactors following comments on https://github.com/guardian/support-frontend/pull/1673
_Somehow managed to forget to create a PR for these_
=> existing-payment-options : belated minor refactors

support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
I noticed an integration test was failing because the fixture json was wrong, this fixes it.
=> Fix an integration test

support-frontend/assets/components/button/anchorButton.jsx, support-frontend/assets/components/productOption/productOption.jsx, support-frontend/assets/components/productOption/productOption.scss, support-frontend/package.json, support-frontend/stories/_index.js, support-frontend/stories/cards.jsx, support-frontend/yarn.lock
feat: added a new productOption card to story book
This new card has been added to test out variants of the product option cards
[**Trello Card**](https://trello.com/c/7rn0MCD5/2324-product-option-card-design-iteration)
New product option cards added
=> feat: added a new productOption card to story book

support-frontend/assets/components/page/page.jsx, support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouContainer.jsx, support-frontend/assets/pages/new-contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx, support-frontend/assets/pages/new-contributions-landing/contributionsLanding.jsx
Reverts guardian/support-frontend#1841
=> Revert "Thank you 'set password' screen UX updates"

support-frontend/assets/helpers/page/page.js, support-frontend/assets/helpers/render.js
Adds the exception message to the reported error message in the instance where a page fails to render.
=> Add more useful error message when page fails to render

support-frontend/app/controllers/Application.scala, support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js, support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js, support-frontend/assets/pages/contributions-landing/contributionsLandingReducer.js
... and rename `guestAccountToken` response from Payment API to `guestAccountCreationToken` for consistency with support-frontend
=> Get token correctly from flash session

support-frontend/app/views/main.scala.html, support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
We have a hypothesis that the polyfill script is failing to load for a significant amount of our users. This PR adds some tracking to test that hypothesis
=> Track the status of the polyfill script load

support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
`analyticsInitialisation` is called in `pageInit` and any GA calls have to come after that
=> Move GA call to after init

support-frontend/app/views/main.scala.html, support-frontend/assets/helpers/tracking/ophanComponentEventTracking.js, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
To tell us whether `Object.values` and `Object.entries` are available before & after polyfill
=> Extra polyfill tracking

support-frontend/assets/components/radioToggle/radioToggle.jsx, support-frontend/assets/components/socialShare/socialShare.jsx, support-frontend/assets/components/subscriptionCheckouts/thankYou/marketingConsentContainer.jsx, support-frontend/assets/helpers/checkoutForm/onFormSubmit.js, support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js, support-frontend/assets/helpers/page/page.js, support-frontend/assets/helpers/subscriptions.js, support-frontend/assets/helpers/subscriptionsForms/formActions.js, support-frontend/assets/helpers/tracking/conversions.js, support-frontend/assets/helpers/tracking/ophan.js, support-frontend/assets/pages/contributions-landing/components/ContributionAmount.jsx, support-frontend/assets/pages/contributions-landing/components/ContributionTypeTabs.jsx, support-frontend/assets/pages/contributions-landing/components/ExistingRecurringContributorErrorMessage.jsx, support-frontend/assets/pages/contributions-landing/components/MarketingConsentContainer.jsx, support-frontend/assets/pages/contributions-landing/components/MustSignIn.jsx, support-frontend/assets/pages/contributions-landing/components/SetPasswordForm.jsx, support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButton.jsx, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx
It does a lot more than just component events
=> Rename ophanComponentEventTracking to just ophan

support-frontend/assets/components/priceLabel/priceLabel.jsx, support-frontend/assets/components/promotionSummary/promotionSummary.jsx, support-frontend/assets/components/subscriptionCheckouts/billingPeriodSelector.jsx, support-frontend/assets/components/subscriptionCheckouts/summary.jsx, support-frontend/assets/helpers/internationalisation/currency.js, support-frontend/assets/helpers/productPrice/__tests__/priceDescriptionsTests.js, support-frontend/assets/helpers/productPrice/__tests__/weeklyProductPrice.js, support-frontend/assets/helpers/productPrice/fulfilmentOptions.js, support-frontend/assets/helpers/productPrice/paperProductPrices.js, support-frontend/assets/helpers/productPrice/priceDescriptions.js, support-frontend/assets/helpers/productPrice/productPrices.js, support-frontend/assets/helpers/productPrice/weeklyProductPrice.js, support-frontend/assets/helpers/render.js, support-frontend/assets/helpers/subscriptions.js, support-frontend/assets/helpers/subscriptionsForms/formReducer.js, support-frontend/assets/helpers/subscriptionsForms/submit.js, support-frontend/assets/pages/contributions-landing/components/ContributionState.jsx, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx, support-frontend/assets/pages/digital-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/digital-subscription-landing/components/form.jsx, support-frontend/assets/pages/paper-subscription-checkout/components/checkoutForm.jsx, support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx, support-frontend/assets/pages/subscriptions-landing/components/featuredProducts.jsx, support-frontend/assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.jsx, support-frontend/assets/pages/weekly-subscription-landing/components/weeklyForm.jsx, support-frontend/test/controllers/SubscriptionsTest.scala, support-services/src/main/scala/com/gu/support/pricing/PriceSummary.scala, support-services/src/main/scala/com/gu/support/pricing/PriceSummaryService.scala
Reverts guardian/support-frontend#1857
=> Revert "Price summary updates"

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx
Updates the header on the right
Before:
After:
=> Update thank you/set password copy

support-services/build.sbt, support-services/src/main/scala/com/gu/support/promotions/PromotionCache.scala, support-services/src/main/scala/com/gu/support/promotions/PromotionCollection.scala, support-services/src/main/scala/com/gu/support/promotions/PromotionService.scala, support-services/src/test/scala/com/gu/support/promotions/PromotionCacheSpec.scala
Reverts guardian/support-frontend#1876 which I reverted while trying to fix an issue yesterday but it wasn't the problem.
=> Revert "Revert "Cache list of promotions in memory""

support-frontend/app/controllers/Application.scala
We've had a steady flow of requests where the url querystring contains some of the text from the article body.
These appear to come from web crawlers. Investigating why that's happening (something wrong on dotcom?) is a separate piece of work.
This PR addresses the fact that these requests result in a 500 response, which is causing our alarms to go off.
The reason is that support-frontend tries to return a 302 redirect when the client hits e.g. `/contribute?acquisitionData=%7B&quo.%E2%80%99`, but when Play constructs the `Location` header of the redirect response it only encodes the value parts of the querystring, not the keys.
This results in an exception when akka-http processes the headers:
`java.lang.IllegalArgumentException: Character 8217 cannot match AsciiSet because it is out of …
=> Fix handling of redirects with special chars in the queryString

support-frontend/assets/pages/contributions-landing/components/SetPasswordForm.jsx
So we can see the split between one-off and recurring.
=> Add contribution type to set password tracking

support-frontend/setup.sh
As per @akash1810's suggestion, we could merge these into one script - don't want to get too distracted by this right now though
=> Run nginx setup from main setup script

support-frontend/conf/routes
Had a minute while I was waiting for something, had wanted to fix the spacing in the routes file for awhile
=> fixed spacing in routes file 🧹

support-frontend/Brewfile
Adding a dependancy to the Brewfile.
* Add cask "AdoptOpenJDK/openjdk/adoptopenjdk8"
=> Jy brewfile update

support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
feat: new optimise experimentID
This adds a fresh Optimise experiment ID for the digital landing page a/b test
=> feat: new optimise experimentID

support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.jsx
feat: copy updates
This fixes copy changes on production
=> feat: copy updates

support-frontend/assets/components/adFreeSectionB/adFreeSectionB.scss, support-frontend/assets/pages/digital-subscription-landing/components/independentJournalismSection.scss, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.jsx, support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.scss, support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
Update to the style on digi-pack-landing-page
[**Trello Card**](https://trello.com/c/36OnHU6p/2441-update-landing-page-styling)
https://app.zeplin.io/project/5c3c9a2881e8042985ba9cbe/screen/5d134a324b9926697beb3769
=> style: update the style on digi-pack-landing-page

support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
updated google optimize experiment, id because we started a new experiment
=> updated: optimize experiment id

support-frontend/yarn.lock
We need to upgrade the lock file when we upgrade dependencies
=> updated yarn lock with upgraded dependencies

support-workers/cloud-formation/src/templates/cfn-template.yaml
This alert triggered a false alarm today, so I'm giving it a bit more space. 
* Change 8h to 12h
=> Change digipack alert threshold to 12h

support-frontend/build.sbt
I am using JDK11 locally so all scala code is compiled to java 11 bytecode.  Since mockito has fun with bytecode to do its magic, the old version was failing to run the tests locally.
This PR updates it to a version that can handle that.
This was the stack trace I was getting, in case it's useful
```
[info] Mockito can only mock non-private & non-final classes.
[info] If you're not sure why you're getting this error, please report to the mailing list.
[info] 
[info] 
[info] Java               : 11
[info] JVM vendor name    : AdoptOpenJDK
[info] JVM vendor version : 11.0.3+7
[info] JVM name           : OpenJDK 64-Bit Server VM
[info] JVM version        : 11.0.3+7
[info] JVM info           : mixed mode
[info] OS name            : Mac OS X
[info] OS version         : 10.14.3
[info] 
[info] …
```
=> update mockito so it understand jdk11 bytecode

support-frontend/assets/helpers/tracking/doNotTrack.js
I made a school boy error in the `maybeTrack` function
=> Fix for the maybeTrack function

support-frontend/assets/components/forms/customFields/radioInput.scss
The hover doesn't work for GW, but we want it to work!
Special thanks to @jesseyuen for pairing on this one!
before
after
=> make hover work for weekly frequency radio buttons

support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYou.jsx, support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouPasswordSet.jsx
Survey is over
[**Trello Card**](https://trello.com/c/iaYwmpPB/1305-take-down-the-survey)
=> take down moment survey

support-frontend/assets/helpers/checkoutForm/onFormSubmit.js, support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js, support-frontend/assets/helpers/subscriptionsForms/submit.js, support-frontend/assets/helpers/tracking/behaviour.js, support-models/build.sbt
Reverts guardian/support-frontend#2004
=> Revert "Add additional tracking for the product checkout"

support-frontend/assets/helpers/checkoutForm/onFormSubmit.js, support-frontend/assets/helpers/checkoutForm/onFormSubmitOld.js, support-frontend/assets/helpers/subscriptionsForms/submit.js, support-frontend/assets/helpers/tracking/behaviour.js, support-models/build.sbt
Reverts guardian/support-frontend#2007
This reapplies #2004 which failed post deployment tests. 
I've run the tests locally and they pass so I think this was a spurious result
=> Revert "Revert "Add additional tracking for the product checkout""

support-frontend/assets/components/productOption/productOption.jsx, support-frontend/assets/components/productOption/productOption.scss, support-frontend/assets/components/productPage/productPageHero/productPageHero.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, support-frontend/stories/cards.jsx
Reverts guardian/support-frontend#2010
=> Revert "feat: optimize test for product cards"

support-frontend/assets/components/productPage/productPageHero/productPageHero.scss, support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx, support-frontend/test/selenium/subscriptions/pages/DigitalPackProductPage.scala
The responsive styles are broken on the current version of the digital pack product page, this PR is to fix those problems
* CSS changes
=> styling: responsive updates

support-frontend/assets/helpers/productPrice/productPrices.js, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/__tests__/paymentSelectionTests.js, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx, support-frontend/package.json
The tests are to catch any changes to data before they go to production 
[**Trello Card**](https://trello.com/c/mih6w6j0/2536-product-card-clean-up)
* add Tests for paymentSelection 
N/A
=> Payment selection tests

support-config/src/main/resources/touchpoint.PROD.conf, support-config/src/main/resources/touchpoint.SANDBOX.conf, support-config/src/main/resources/touchpoint.UAT.conf, support-config/src/main/scala/com/gu/support/config/StripeConfig.scala, support-frontend/app/views/contributions.scala.html, support-frontend/app/views/subscriptionCheckout.scala.html, support-frontend/assets/helpers/paymentIntegrations/oneOffContributions.js, support-frontend/assets/helpers/paymentIntegrations/stripeCheckout.js, support-frontend/assets/helpers/subscriptionsForms/submit.js, support-frontend/assets/pages/contributions-landing/components/StripePaymentRequestButton/StripePaymentRequestButtonContainer.jsx, support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js, support-frontend/assets/pages/contributions-landing/contributionsLandingInit.js, support-frontend/test/controllers/SubscriptionsTest.scala
Reverts guardian/support-frontend#2040 in case we need to...
=> Revert "Modifications to enable a third US-based Stripe account"

support-frontend/assets/helpers/paymentIntegrations/stripeCheckout.js, support-frontend/assets/helpers/subscriptionsForms/submit.js, support-frontend/assets/pages/contributions-landing/contributionsLandingActions.js
Keeping master in line with our linter's suggestions
=> linting master

support-frontend/assets/components/productOption/productOption.jsx, support-frontend/assets/components/productOption/productOption.scss, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx, support-frontend/assets/pages/digital-subscription-landing/digitalSubscriptionLanding.jsx
To remove the now completed wording test which was running on the Digital Pack homepage.
* Remove the test code
* Turn off the 'Optimize ready' check on the DP landing page
=> Remove dp test

support-frontend/assets/helpers/flashSale.js
Correct the showcase page copy for DP sale
=> Update DP flash sale copy

support-frontend/assets/helpers/abTests/abtestDefinitions.js, support-frontend/assets/helpers/campaigns.jsx, support-frontend/assets/pages/contributions-landing/components/ContributionFormContainer.jsx, support-frontend/assets/pages/contributions-landing/contributionsLanding.jsx, support-frontend/assets/pages/contributions-landing/contributionsLanding.scss, support-frontend/assets/pages/contributions-landing/contributionsLandingEnvironmentMoment.scss
All of the copy and assets for the upcoming environment pledge moment built out on https://support.theguardian.com/uk/contribute/environmentpledge
The code is built around a test to support our current background color ("control") and a new background color suggested from marketing ("yellow" variant). Screenshots below, and variants can be entered using the following links (when live):
https://support.theguardian.com/uk/contribute/environmentpledge#ab-landingPageMomentBackgroundColour=control
https://support.theguardian.com/uk/contribute/environmentpledge#ab-landingPageMomentBackgroundColour=yellow
* Built out the landing page
* Created test variants for the landing page
Desktop-Wide - Control
Desktop-Wide - Variant
Desktop-Small - Control …
=> Environment pledge moment landing page

project/LibraryVersions.scala, support-frontend/build.sbt, support-workers/build.sbt
Another [snyk alert](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-467016) for jackson-databind.
Happily the version is now in sync with the rest of the jackson libraries
=> Jackson 2.10.0

support-frontend/assets/helpers/flashSale.js, support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx, support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.js, support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx, support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
Turn off the print sale at 00.00hrs on 7/10/19
[**Trello Card**](https://trello.com/c/0xSqkfkQ/2651-end-of-print-campaign-post-6th-oct-revert-back-pages)
=> End print sale

support-frontend/assets/components/contributionsReminder/contributionsReminder.jsx, support-frontend/assets/components/subscriptionCheckouts/stripeForm/stripeForm.jsx, support-frontend/assets/helpers/flashSale.js, support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSetPassword.jsx, support-frontend/test/selenium/subscriptions/CheckoutsSpec.scala, support-frontend/test/selenium/subscriptions/pages/CheckoutPage.scala
This is the frontend component for the reminder proof of concept
[**Trello Card**](https://trello.com/c/os7AbR3n/1502-poc-remind-me-later-feature)
=> "Reminder" proof of concept frontend component

support-frontend/assets/helpers/abTests/abtestDefinitions.js, support-frontend/assets/helpers/abTests/data/testAmountsData.js
The next amounts test, to be run during the moment.
The control values are set from the admin console
=> Amounts test round 4

support-frontend/README.md, support-frontend/cloud-formation/cfn.yaml
https://trello.com/c/2lA8pxcz/1501-enable-ssh-access-to-all-our-servers
* Change 1
* Change 2
=> Adding bastion to ingress rules, removing unused rule

support-frontend/assets/helpers/externalLinks.js, support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/appsSection.jsx
Updated thank you page to the new wireframe in the screenshot below
the additional "see your subscription details" button will be added later
[**Trello Card**](https://trello.com/c/pKDRgtsL/2609-dp-launch-thank-you-page-16-10-mvp)
* additional Guardian Daily buttons
* new links added to buttons
* product order change
**WireFrame**
**New Thank you page**
=> feat: updated thank you page

support-frontend/assets/pages/digital-subscription-checkout/components/thankYou/hero.jsx
Update header image on the Digital Pack thank you page and existing subscriber page
[**Trello Card**](https://trello.com/c/pKDRgtsL/2609-dp-launch-thank-you-page-16-10-mvp)
=> Update the images on the thank you and existing subscriber pages

support-frontend/devrun.sh
SBT keeps running out of memory, this should fix it.
=> Give SBT more memory

support-frontend/assets/helpers/theGrid.js, support-frontend/assets/pages/digital-subscription-landing/components/cta.jsx, support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLanding.scss, support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss, support-frontend/assets/pages/digital-subscription-landing/components/productBlock.jsx, support-frontend/assets/pages/digital-subscription-landing/componentsB/theMoment.scss, support-frontend/devrun.sh
This is a bunch of small, fiddly fixes that tweaks typography and alignment on the new dp page with some markup changes for EO and A11Y benefit. 
[**Trello Card**](https://trello.com/c/gE2y7vNm/2686-design-tweaks-to-dp-product-page)
* Lots of css updates
* Some small markup changes
Desktop
**Before**
**After**
Tablet
**Before**
**After**
Mobile
**Before**
**After**
=> Digital Subscriptions page design updates
